#include "totvs.ch"
#include "msobject.ch"
#include "totvs.framework.treports.integratedprovider.th"
#include "tlpp-core.th"
#include "tlpp-rest.th"
#include "manufacturing.pcp.projecao.estoque.ch"

namespace totvs.protheus.sigapcp.treportsintegratedprovider

@totvsFrameworkTReportsIntegratedProvider(active=.T., team="SIGAPCP", tables="SB1,SB2,SB8,SBF", name="Projeção de Estoque", country="ALL", initialRelease="12.1.2310", customTables="SB1,SB2")

/*/{Protheus.doc} ProjecaoEstoqueTReportsBusinessObject
Classe para criação do Objeto de Negócio para listagem de Projeção de Estoque

@author ana.paula
@since 24/10/2023
@version 1.0
/*/
class ProjecaoEstoqueTReportsBusinessObject from totvs.framework.treports.integratedprovider.IntegratedProvider
    public method new() as object
    public method getData() as object
    public method getSchema() as object

    protected data aFields as array
    protected data aStruct as array
endclass


/*/{Protheus.doc} new
Método de instância da classe
 
@return object: self

@author ana.paula
@since 24/10/2023
@version 1.0
/*/ 
method new() as object class ProjecaoEstoqueTReportsBusinessObject
    _Super:new()
    //Define a Área
    self:appendArea(STR0001)//STR0001 = "Manufatura"   
 
    //Define o nome do Objeto de Negócio
    self:setDisplayName(STR0002)//STR0002 - "Relacao por Ordem de Producao"
    
    //Define a descrição do Objeto de Negócio
    self:setDescription(STR0003)//STR0003 - "O objetivo deste relatório é exibir os registro do Bloco K (K230/K235/K260/K265/K270/K275/K290/K291/K292)"

    self:setPergunte("TRPEST") //Indica o pergunte que será utilizado no relatório
return self

/*/{Protheus.doc} getData
Retorna os dados do objeto de negócio
 
@param nPage, numérico, indica a página atual do relatório
@param oFilter, objeto, contém o filtro do TReports
 
@return object: self:oData

@author ana.paula
@since 30/10/2023
@version 1.0
/*/
method getData(nPage as numeric, oFilter as object) as object class ProjecaoEstoqueTReportsBusinessObject
    Local aDocs    := {}             as array
    Local aParam   := Array(10)      as array
    Local aTables  := {}             as Array
    Local cAlias   := ""             as character
    Local cCodAnt  := ""             as character
    Local cDescEmp := ""             as character
    Local cDescFil := ""             as character
    Local cQuery   := ""             as character
    Local jParams  := Nil            as json
    Local lSaldo   := .F.            as logical
    Local nCont    := 0              as numeric
    Local nContDC  := 0              as numeric
    Local nX       := 0              as numeric
    Local oExec    := Nil            as object
    Local ojItems  := Nil            as json

    jParams := oFilter:getParameters() //metodo para retorno do json dos parâmetros

    aParam[1]  := pcpValidParam(jParams["MV_PAR01"][1]) //Do Produto?
    aParam[2]  := pcpValidParam(jParams["MV_PAR02"][1]) //Ate o Produto?
    aParam[3]  := pcpValidParam(jParams["MV_PAR03"][1]) //Do Tipo?
    aParam[4]  := pcpValidParam(jParams["MV_PAR04"][1]) //Até o Tipo?
    aParam[5]  := pcpValidParam(jParams["MV_PAR05"][1]) //Do Grupo?
    aParam[6]  := pcpValidParam(jParams["MV_PAR06"][1]) //Até o Grupo?
    aParam[7]  := jParams["MV_PAR07"][1] //Considera OPs? (1-Firmes/2-Previstas/3-Ambas)
    aParam[8]  := jParams["MV_PAR08"][1] //Lista Lote? (1-Sim/2-Não -> Default)
    aParam[9]  := jParams["MV_PAR09"][1] //Lista Endereço? (1-Sim/2-Não -> Default)
    aParam[10] := jParams["MV_PAR10"][1] //Considera Somente TES que atualiza estoque? (1-Sim/2-Não -> Default)

    //SB1 
    cQuery := " SELECT SB1.B1_COD, "
    cQuery +=        " SB1.B1_DESC, "
    cQuery +=        " SB1.B1_TIPO, "
    cQuery +=        " SB1.B1_UM, "
    cQuery +=        " SB1.B1_GRUPO, "
    cQuery +=        " SB2.B2_FILIAL, " 
    cQuery +=        " SB2.B2_QATU, "
    cQuery +=        " SB2.B2_QNPT, "
    cQuery +=        " SB2.B2_SALPEDI, "
    cQuery +=        " SB2.B2_SALPPRE, "
    cQuery +=        " SB2.B2_COD, "
    cQuery +=        " SB2.B2_QEMP, "
    cQuery +=        " SB2.B2_QEMPN, "
    cQuery +=        " SB2.B2_QEMPPRE, "
    cQuery +=        " SB2.B2_QEMPPRJ, "
    cQuery +=        " SB2.B2_QPEDVEN, "
    cQuery +=        " SB2.B2_LOCAL, "
    cQuery +=        " SB2.B2_RESERVA "

    aadd(aTables,{'B1_','SB1.'})
    aadd(aTables,{'B2_','SB2.'})
    PcpInCposPerson(@self:aStruct, @cQuery, self:getCustomFields(),.T.,.T.,,aTables)
    aTables := {}

	cQuery +=   " FROM " + RetSqlName("SB2") + " SB2 "
    cQuery +=  " INNER JOIN " + RetSqlName("SB1") + " SB1 "
    cQuery +=    "  ON SB1.B1_FILIAL   = ? "
    cQuery +=    " AND SB1.B1_COD      = SB2.B2_COD "
    cQuery +=    " AND SB1.B1_TIPO     >= ? "
    cQuery +=    " AND SB1.B1_TIPO     <= ? "
    cQuery +=    " AND SB1.B1_GRUPO    >= ? "
    cQuery +=    " AND SB1.B1_GRUPO    <= ? "
    cQuery +=    " AND SB1.D_E_L_E_T_  = ' ' "
    cQuery +=  " WHERE SB2.B2_FILIAL   = ? "
    cQuery +=    " AND (SB2.B2_QATU    > 0 "
    cQuery +=     " OR  SB2.B2_QEMP    > 0 "
    cQuery +=     " OR  SB2.B2_QEMPN   > 0 "
    cQuery +=     " OR  SB2.B2_RESERVA > 0 "
	cQuery +=     " OR  SB2.B2_QPEDVEN > 0 "
	cQuery +=     " OR  SB2.B2_SALPEDI > 0 "
    cQuery +=     " OR  SB2.B2_QEMPPRE > 0 "
	cQuery +=     " OR  SB2.B2_SALPPRE > 0 "
    cQuery +=     " OR  SB2.B2_QEMPPRJ > 0 "
    cQuery +=     " OR  SB2.B2_QNPT    > 0 "
    cQuery +=     " OR  SB2.B2_QTNP    > 0) "
    cQuery +=    " AND SB2.B2_COD      >= ? "
    cQuery +=    " AND SB2.B2_COD      <= ? "
    cQuery +=    " AND SB2.D_E_L_E_T_  = ' ' "
    cQuery += " ORDER BY SB1.B1_COD "

    oExec := FwExecStatement():New(cQuery)

    oExec:SetString(1, xFilial("SB1"))
    oExec:SetString(2, aParam[3])
    oExec:SetString(3, aParam[4])
    oExec:SetString(4, aParam[5])
    oExec:SetString(5, aParam[6])
    oExec:SetString(6, xFilial("SB2"))
    oExec:SetString(7, aParam[1])
    oExec:SetString(8, aParam[2])


    cAlias := oExec:OpenAlias() 

    If (cAlias)->(!Eof())
        cDescEmp := FWGrpName()
        cDescFil := FWFilialName(, (cAlias)->B2_FILIAL, 1)
    EndIf
    
    while (cAlias)->(!Eof())

        aDocs := {}
        lSaldo := .F.

        //Lista Lote = 1-Sim  E  Lista Endereço = 1-Sim
        If aParam[8] == 1 .and. aParam[9] == 1
            //Se o produto controla LOTE e ENDEREÇO
            If Rastro((cAlias)->B1_COD) .or. Localiza((cAlias)->B1_COD)
                DBSELECTAREA("SB8")
		        SB8->(DBSETORDER(1))
                SB8->(DBSEEK(xFilial("SB8")+(cAlias)->B1_COD))

                While SB8->(!Eof()) .AND. xFilial("SD1")+(cAlias)->B1_COD == SB8->B8_FILIAL+SB8->B8_PRODUTO

                    if SB8->B8_SALDO > 0

                        lSaldoSBF := .F.

                        DBSELECTAREA("SBF")
                        SBF->(DBSETORDER(2))
                        SBF->(DBSEEK(xFilial("SBF")+(cAlias)->B1_COD+SB8->B8_LOCAL+SB8->B8_LOTECTL+SB8->B8_NUMLOTE))

                        While SBF->(!Eof()) .AND.;
                            xFilial("SD1")+(cAlias)->B1_COD+SB8->B8_LOCAL+SB8->B8_LOTECTL+SB8->B8_NUMLOTE ==;
                            SBF->BF_FILIAL+SBF->BF_PRODUTO+SBF->BF_LOCAL+SBF->BF_LOTECTL+SBF->BF_NUMLOTE

                            if SBF->BF_QUANT > 0

                                //Grava registro de saldo inicial do produto - POR LOTE e ENDERECO
                                lSaldo := .T.
                                lSaldoSBF := .T.
                                ojItems := JsonObject():new()

                                for nX := 1 To Len(self:aStruct)
                                    //Campos auxiliares
                                    if self:aStruct[nX][1] == 'DESCEMP'
                                        ojItems[self:aStruct[nX][1]] := cDescEmp
                                    elseif self:aStruct[nX][1] == 'DESCFIL'
                                        ojItems[self:aStruct[nX][1]] := cDescFil
                                    elseif self:aStruct[nX][1] == 'REGISTRO'
                                        ojItems[self:aStruct[nX][1]] := STR0004 //'Saldo'
                                    elseif self:aStruct[nX][1] == 'DATA'
                                            ojItems[self:aStruct[nX][1]] := Nil
                                    elseif self:aStruct[nX][1] == 'TIPO'
                                        ojItems[self:aStruct[nX][1]] := STR0005 //'Saldo Inicial'
                                    elseif self:aStruct[nX][1] == 'DOCUMENTO'
                                        ojItems[self:aStruct[nX][1]] := STR0007 /*'Armazém: '*/ + SB8->B8_LOCAL
                                    elseif self:aStruct[nX][1] == 'STATUS'
                                            ojItems[self:aStruct[nX][1]] := Nil
                                    elseif self:aStruct[nX][1] == 'ARMAZEM'
                                            ojItems[self:aStruct[nX][1]] := Nil
                                    elseif self:aStruct[nX][1] == 'QUANTIDADE'
                                        ojItems[self:aStruct[nX][1]] := SBF->BF_QUANT
                                    elseif self:aStruct[nX][1] == 'PRODUTO_PAI'
                                        ojItems[self:aStruct[nX][1]] := Nil
                                    elseif self:aStruct[nX][1] == 'LOTE'
                                        If Rastro( (cAlias)->B1_COD,"S")
                                            ojItems[self:aStruct[nX][1]] := SBF->BF_LOTECTL+SBF->BF_NUMLOTE
                                        else
                                            ojItems[self:aStruct[nX][1]] := SBF->BF_LOTECTL
                                        endif
                                    elseif self:aStruct[nX][1] == 'ENDERECO'
                                        ojItems[self:aStruct[nX][1]] := SBF->BF_LOCALIZ
                                    else 
                                        //Campos do select principal
                                        if self:aStruct[nX][3] == "date" //Converter data para o formato padrão - 2023-01-27T15:31:43Z
                                            ojItems[self:aStruct[nX][1]] :=totvs.framework.treports.date.stringToTimeStamp((cAlias)->&(self:aStruct[nX][5]))
                                        else
                                            ojItems[self:aStruct[nX][1]] := (cAlias)->&(self:aStruct[nX][5])  
                                        endif
                                    EndIf
                                next nX

                                self:ProcessData()
                                self:oData:appendData(ojItems)
                            endif

                            SBF->(DBSkip())

				        EndDo

                        if !lSaldoSBF 
                            //Grava registro de saldo inicial do produto - POR LOTE
                            lSaldo := .T.
                            ojItems := JsonObject():new()

                            for nX := 1 To Len(self:aStruct)
                                //Campos auxiliares
                                if self:aStruct[nX][1] == 'DESCEMP'
                                    ojItems[self:aStruct[nX][1]] := cDescEmp
                                elseif self:aStruct[nX][1] == 'DESCFIL'
                                    ojItems[self:aStruct[nX][1]] := cDescFil
                                elseif self:aStruct[nX][1] == 'REGISTRO'
                                    ojItems[self:aStruct[nX][1]] := STR0004 //'Saldo'
                                elseif self:aStruct[nX][1] == 'DATA'
                                        ojItems[self:aStruct[nX][1]] := Nil
                                elseif self:aStruct[nX][1] == 'TIPO'
                                    ojItems[self:aStruct[nX][1]] := STR0005 //'Saldo Inicial'
                                elseif self:aStruct[nX][1] == 'DOCUMENTO'
                                    ojItems[self:aStruct[nX][1]] := STR0007 /*'Armazém: '*/ + SB8->B8_LOCAL
                                elseif self:aStruct[nX][1] == 'STATUS'
                                        ojItems[self:aStruct[nX][1]] := Nil
                                elseif self:aStruct[nX][1] == 'ARMAZEM'
                                        ojItems[self:aStruct[nX][1]] := Nil
                                elseif self:aStruct[nX][1] == 'QUANTIDADE'
                                    ojItems[self:aStruct[nX][1]] := SB8->B8_SALDO
                                elseif self:aStruct[nX][1] == 'PRODUTO_PAI'
                                    ojItems[self:aStruct[nX][1]] := Nil
                                elseif self:aStruct[nX][1] == 'LOTE'
                                    If Rastro( (cAlias)->B1_COD,"S")
                                        ojItems[self:aStruct[nX][1]] := SB8->B8_LOTECTL+SB8->B8_NUMLOTE
                                    else
                                        ojItems[self:aStruct[nX][1]] := SB8->B8_LOTECTL
                                    endif
                                elseif self:aStruct[nX][1] == 'ENDERECO'
                                    ojItems[self:aStruct[nX][1]] := Nil
                                else 
                                    //Campos do select principal
                                    if self:aStruct[nX][3] == "date" //Converter data para o formato padrão - 2023-01-27T15:31:43Z
                                        ojItems[self:aStruct[nX][1]] := totvs.framework.treports.date.stringToTimeStamp((cAlias)->&(self:aStruct[nX][5]))
                                    else
                                        ojItems[self:aStruct[nX][1]] := (cAlias)->&(self:aStruct[nX][5])  
                                    endif
                                EndIf
                            next nX

                            self:ProcessData()
                            self:oData:appendData(ojItems)
                        endif
                        
                    endif

                    SB8->(DBSkip())

				EndDo
			EndIf	
        //Lista Lote = 1-Sim (somente)
        ElseIf aParam[8] == 1
            If Rastro((cAlias)->B1_COD)
                DBSELECTAREA("SB8")
		        SB8->(DBSETORDER(1))
                SB8->(DBSEEK(xFilial("SB8")+(cAlias)->B1_COD))

                While SB8->(!Eof()) .AND. (cAlias)->B1_COD == SB8->B8_PRODUTO

                    if SB8->B8_SALDO > 0
                        //Grava registro de saldo inicial do produto - POR LOTE
                        lSaldo := .T.
                        ojItems := JsonObject():new()

                        for nX := 1 To Len(self:aStruct)
                            //Campos auxiliares
                            if self:aStruct[nX][1] == 'DESCEMP'
                                ojItems[self:aStruct[nX][1]] := cDescEmp
                            elseif self:aStruct[nX][1] == 'DESCFIL'
                                ojItems[self:aStruct[nX][1]] := cDescFil
                            elseif self:aStruct[nX][1] == 'REGISTRO'
                                ojItems[self:aStruct[nX][1]] := STR0004 //'Saldo'
                            elseif self:aStruct[nX][1] == 'DATA'
                                    ojItems[self:aStruct[nX][1]] := Nil
                            elseif self:aStruct[nX][1] == 'TIPO'
                                ojItems[self:aStruct[nX][1]] := STR0005 //'Saldo Inicial'
                            elseif self:aStruct[nX][1] == 'DOCUMENTO'
                                ojItems[self:aStruct[nX][1]] := STR0007 /*'Armazém: '*/ + SB8->B8_LOCAL
                            elseif self:aStruct[nX][1] == 'STATUS'
                                    ojItems[self:aStruct[nX][1]] := Nil
                            elseif self:aStruct[nX][1] == 'ARMAZEM'
                                    ojItems[self:aStruct[nX][1]] := Nil
                            elseif self:aStruct[nX][1] == 'QUANTIDADE'
                                ojItems[self:aStruct[nX][1]] := SB8->B8_SALDO
                            elseif self:aStruct[nX][1] == 'PRODUTO_PAI'
                                ojItems[self:aStruct[nX][1]] := Nil
                            elseif self:aStruct[nX][1] == 'LOTE'
                                If Rastro( (cAlias)->B1_COD,"S")
                                    ojItems[self:aStruct[nX][1]] := SB8->B8_LOTECTL+SB8->B8_NUMLOTE
                                else
                                    ojItems[self:aStruct[nX][1]] := SB8->B8_LOTECTL
                                endif
                            elseif self:aStruct[nX][1] == 'ENDERECO'
                                ojItems[self:aStruct[nX][1]] := Nil
                            else 
                                //Campos do select principal
                                if self:aStruct[nX][3] == "date" //Converter data para o formato padrão - 2023-01-27T15:31:43Z
                                    ojItems[self:aStruct[nX][1]] := totvs.framework.treports.date.stringToTimeStamp((cAlias)->&(self:aStruct[nX][5]))
                                else
                                    ojItems[self:aStruct[nX][1]] := (cAlias)->&(self:aStruct[nX][5])  
                                endif
                            EndIf
                        next nX

                        self:ProcessData()
                        self:oData:appendData(ojItems)
                    endif

                    SB8->(DBSkip())

				EndDo
			EndIf	
        //Lista Endereço = 1-Sim (somente)
        ElseIf aParam[9] == 1
            if Localiza((cAlias)->B1_COD)
                DBSELECTAREA("SBF")
		        SBF->(DBSETORDER(2))
                SBF->(DBSEEK(xFilial("SBF")+(cAlias)->B1_COD))

                While SBF->(!Eof()) .AND. (cAlias)->B1_COD == SBF->BF_PRODUTO

                    if SBF->BF_QUANT > 0
                        //Grava registro de saldo inicial do produto - POR ENDERECO
                        lSaldo := .T.
                        ojItems := JsonObject():new()

                        for nX := 1 To Len(self:aStruct)
                            //Campos auxiliares
                            if self:aStruct[nX][1] == 'DESCEMP'
                                ojItems[self:aStruct[nX][1]] := cDescEmp
                            elseif self:aStruct[nX][1] == 'DESCFIL'
                                ojItems[self:aStruct[nX][1]] := cDescFil
                            elseif self:aStruct[nX][1] == 'REGISTRO'
                                ojItems[self:aStruct[nX][1]] := STR0004 //'Saldo'
                            elseif self:aStruct[nX][1] == 'DATA'
                                    ojItems[self:aStruct[nX][1]] := Nil
                            elseif self:aStruct[nX][1] == 'TIPO'
                                ojItems[self:aStruct[nX][1]] := STR0005 //'Saldo Inicial'
                            elseif self:aStruct[nX][1] == 'DOCUMENTO'
                                ojItems[self:aStruct[nX][1]] := STR0007 /*'Armazém: '*/ + SBF->BF_LOCAL
                            elseif self:aStruct[nX][1] == 'STATUS'
                                    ojItems[self:aStruct[nX][1]] := Nil
                            elseif self:aStruct[nX][1] == 'ARMAZEM'
                                    ojItems[self:aStruct[nX][1]] := Nil
                            elseif self:aStruct[nX][1] == 'QUANTIDADE'
                                ojItems[self:aStruct[nX][1]] := SBF->BF_QUANT
                            elseif self:aStruct[nX][1] == 'PRODUTO_PAI'
                                ojItems[self:aStruct[nX][1]] := Nil
                            elseif self:aStruct[nX][1] == 'LOTE'
                                If Rastro( (cAlias)->B1_COD,"S")
                                    ojItems[self:aStruct[nX][1]] := SBF->BF_LOTECTL+SBF->BF_NUMLOTE
                                else
                                    ojItems[self:aStruct[nX][1]] := SBF->BF_LOTECTL
                                endif
                            elseif self:aStruct[nX][1] == 'ENDERECO'
                                ojItems[self:aStruct[nX][1]] := SBF->BF_LOCALIZ
                            else 
                                //Campos do select principal
                                if self:aStruct[nX][3] == "date" //Converter data para o formato padrão - 2023-01-27T15:31:43Z
                                    ojItems[self:aStruct[nX][1]] := totvs.framework.treports.date.stringToTimeStamp((cAlias)->&(self:aStruct[nX][5]))
                                else
                                    ojItems[self:aStruct[nX][1]] := (cAlias)->&(self:aStruct[nX][5])  
                                endif  
                            EndIf
                        next nX

                        self:ProcessData()
                        self:oData:appendData(ojItems)
                    endif

                    SBF->(DBSkip())

				EndDo
			EndIf	
        endif

        if !lSaldo
            //Grava registro de saldo inicial do produto
            ojItems := JsonObject():new()

            for nX := 1 To Len(self:aStruct)
                //Campos auxiliares
                if self:aStruct[nX][1] == 'DESCEMP'
                    ojItems[self:aStruct[nX][1]] := cDescEmp
                elseif self:aStruct[nX][1] == 'DESCFIL'
                    ojItems[self:aStruct[nX][1]] := cDescFil
                elseif self:aStruct[nX][1] == 'REGISTRO'
                    ojItems[self:aStruct[nX][1]] := STR0004 //'Saldo'
                elseif self:aStruct[nX][1] == 'DATA'
                        ojItems[self:aStruct[nX][1]] := Nil
                elseif self:aStruct[nX][1] == 'TIPO'
                    ojItems[self:aStruct[nX][1]] := STR0005 //'Saldo Inicial'
                elseif self:aStruct[nX][1] == 'DOCUMENTO'
                    ojItems[self:aStruct[nX][1]] := STR0007 /*'Armazém: '*/ + (cAlias)->B2_LOCAL
                elseif self:aStruct[nX][1] == 'STATUS'
                        ojItems[self:aStruct[nX][1]] := Nil
                elseif self:aStruct[nX][1] == 'ARMAZEM'
                        ojItems[self:aStruct[nX][1]] := Nil
                elseif self:aStruct[nX][1] == 'QUANTIDADE'
                    ojItems[self:aStruct[nX][1]] := (cAlias)->B2_QATU
                elseif self:aStruct[nX][1] == 'PRODUTO_PAI'
                    ojItems[self:aStruct[nX][1]] := Nil
                elseif self:aStruct[nX][1] == 'LOTE'
                    ojItems[self:aStruct[nX][1]] := Nil
                elseif self:aStruct[nX][1] == 'ENDERECO'
                    ojItems[self:aStruct[nX][1]] := Nil                
                else 
                    //Campos do select principal
                    if self:aStruct[nX][3] == "date" //Converter data para o formato padrão - 2023-01-27T15:31:43Z
                        ojItems[self:aStruct[nX][1]] := totvs.framework.treports.date.stringToTimeStamp((cAlias)->&(self:aStruct[nX][5]))
                    else
                        ojItems[self:aStruct[nX][1]] := (cAlias)->&(self:aStruct[nX][5])  
                    endif
                EndIf
            next nX

            self:ProcessData()
            self:oData:appendData(ojItems)
        endif
        
        //Se houver saldo em terceiro - grava um registro
        if (cAlias)->B2_QNPT > 0
            ojItems := JsonObject():new()

            for nX := 1 To Len(self:aStruct)
                //Campos auxiliares
                if self:aStruct[nX][1] == 'DESCEMP'
                    ojItems[self:aStruct[nX][1]] := cDescEmp
                elseif self:aStruct[nX][1] == 'DESCFIL'
                    ojItems[self:aStruct[nX][1]] := cDescFil
                elseif self:aStruct[nX][1] == 'REGISTRO'
                    ojItems[self:aStruct[nX][1]] := 'Saldo'
                elseif self:aStruct[nX][1] == 'DATA'
                        ojItems[self:aStruct[nX][1]] := Nil
                elseif self:aStruct[nX][1] == 'TIPO'
                    ojItems[self:aStruct[nX][1]] := STR0006 //'Em Terceiro'
                elseif self:aStruct[nX][1] == 'DOCUMENTO'
                    ojItems[self:aStruct[nX][1]] := STR0007 /*'Armazém: '*/ + (cAlias)->B2_LOCAL
                elseif self:aStruct[nX][1] == 'STATUS'
                        ojItems[self:aStruct[nX][1]] := Nil
                elseif self:aStruct[nX][1] == 'ARMAZEM'
                        ojItems[self:aStruct[nX][1]] := Nil
                elseif self:aStruct[nX][1] == 'QUANTIDADE'
                    ojItems[self:aStruct[nX][1]] := (cAlias)->B2_QNPT
                elseif self:aStruct[nX][1] == 'PRODUTO_PAI'
                    ojItems[self:aStruct[nX][1]] := Nil
                elseif self:aStruct[nX][1] == 'LOTE'
                    ojItems[self:aStruct[nX][1]] := Nil
                elseif self:aStruct[nX][1] == 'ENDERECO'
                    ojItems[self:aStruct[nX][1]] := Nil                
                else 
                    //Campos do select principal
                    if self:aStruct[nX][3] == "date" //Converter data para o formato padrão - 2023-01-27T15:31:43Z
                        ojItems[self:aStruct[nX][1]] := totvs.framework.treports.date.stringToTimeStamp((cAlias)->&(self:aStruct[nX][5]))
                    else
                        ojItems[self:aStruct[nX][1]] := (cAlias)->&(self:aStruct[nX][5])  
                    endif
                EndIf
            next nX

            self:ProcessData()
            self:oData:appendData(ojItems)
        endif

        //Busca as quantidades detalhadas do produto
        if cCodAnt != (cAlias)->B1_COD

            cCodAnt := (cAlias)->B1_COD

            //Se houver quantidade prevista para entrar
            if (cAlias)->B2_SALPEDI > 0 .or. (cAlias)->B2_SALPPRE > 0
                //Busca os registros de SC do produto
                aSC1 := buscaSC1((cAlias)->B2_COD)

                for nCont := 1 To Len(aSC1)

                    aAdd(aDocs,{aSC1[nCont][1],;//Data da necessidade
                                aSC1[nCont][2],;//Número
                                aSC1[nCont][3],;//Item                   
                                if(aSC1[nCont][4]="F",STR0008,STR0009),;//Status // "Firme" // "Previsto
                                aSC1[nCont][5],;//Armazém
                                aSC1[nCont][6],;//Quantidade
                                STR0012,;//Tipo-Solicitação de Compra
                                STR0010,;//Registro-Entrada
                                '',;//Produto Pai
                                '',;//Lote
                                '',;//Sublote
                                ''})//Endereço

                next nCont

                //Busca os registros de PC do produto
                aSC7 := buscaSC7((cAlias)->B2_COD)

                for nCont := 1 To Len(aSC7)

                    aAdd(aDocs,{aSC7[nCont][1],;//Data de entrega
                                aSC7[nCont][2],;//Número
                                aSC7[nCont][3],;//Item                   
                                if(aSC7[nCont][4]="P",STR0009,STR0008),;//Status // "Previsto // "Firme"
                                aSC7[nCont][5],;//Armazém
                                aSC7[nCont][6],;//Quantidade
                                if(aSC7[nCont][7]=1,STR0013,STR0019),;//Tipo: //1-Pedido de Compra //2-Autorização de Entrega
                                STR0010,;//Registro-Entrada
                                '',;//Produto Pai
                                '',;//Lote
                                '',;//Sublote
                                ''})//Endereço

                next nCont

                //Busca os registros de OP do produto
                aSC2 := buscaSC2((cAlias)->B2_COD, aParam[7])

                for nCont := 1 To Len(aSC2)

                    aAdd(aDocs,{aSC2[nCont][1],;//Data de entrega
                                aSC2[nCont][2],;//Número
                                aSC2[nCont][3],;//Item+Sequênia                   
                                aSC2[nCont][4],;//Status
                                aSC2[nCont][5],;//Armazém
                                aSC2[nCont][6],;//Quantidade
                                STR0014,;//Tipo-Ordem de Produção
                                STR0010,;//Registro-Entrada
                                '',;//Produto Pai
                                '',;//Lote
                                '',;//Sublote
                                ''})//Endereço

                next nCont
            endif

            //Se houver quantidade empenhada
            if (cAlias)->B2_QEMP > 0 .or. (cAlias)->B2_QEMPN > 0 .or.;
               (cAlias)->B2_QEMPPRE > 0 .or. (cAlias)->B2_QEMPPRJ > 0

                //Busca os empenhos do produto
                aSD4 := buscaSD4((cAlias)->B2_COD)                

                for nCont := 1 To Len(aSD4)

                    aSDC := {}

                    if aParam[9] == 1 .and. (!EMPTY(aSD4[nCont][8]) .or. !EMPTY(aSD4[nCont][9]))
                        //Busca a composição dos empenhos do produto
                        aSDC := buscaSDC((cAlias)->B2_COD,aSD4[nCont][2],aSD4[nCont][8],aSD4[nCont][9])                            
                    endif

                    if Len(aSDC) > 0
                        for nContDC := 1 To Len(aSDC)

                            aAdd(aDocs,{aSD4[nCont][1],;//Data do empenho
                                        aSD4[nCont][2],;//Número
                                        aSDC[nContDC][3],;//Item                   
                                        aSDC[nContDC][4],;//Status
                                        aSDC[nContDC][5],;//Armazém
                                        aSDC[nContDC][6],;//Quantidade
                                        STR0015,;//Tipo-Empenho
                                        STR0011,;//Registro-Saída
                                        aSD4[nCont][7],;//Produto Pai
                                        aSDC[nContDC][8],;//Lote
                                        aSDC[nContDC][9],;//Sublote
                                        aSDC[nContDC][10]})//Endereço
                        next nContDC
                    else
                        aAdd(aDocs,{aSD4[nCont][1],;//Data do empenho
                                    aSD4[nCont][2],;//Número
                                    aSD4[nCont][3],;//Item                   
                                    aSD4[nCont][4],;//Status
                                    aSD4[nCont][5],;//Armazém
                                    aSD4[nCont][6],;//Quantidade
                                    STR0015,;//Tipo-Empenho
                                    STR0011,;//Registro-Saída
                                    aSD4[nCont][7],;//Produto Pai
                                    aSD4[nCont][8],;//Lote
                                    aSD4[nCont][9],;//Sublote
                                    ''})//Endereço
                    endif                  

                next nCont

                //Busca os empenhos de projeto
                aAFJ := buscaAFJ((cAlias)->B2_COD)

                for nCont := 1 To Len(aAFJ)

                    aAdd(aDocs,{aAFJ[nCont][1],;//Data de emissão
                                aAFJ[nCont][2],;//Número
                                aAFJ[nCont][3],;//Item                   
                                aAFJ[nCont][4],;//Status
                                aAFJ[nCont][5],;//Armazém
                                aAFJ[nCont][6],;//Quantidade
                                STR0016,;//Tipo-Emp.Projeto
                                STR0011,;//Registro-Saída
                                aAFJ[nCont][7],;//Produto Pai
                                '',;//Lote
                                '',;//Sublote
                                ''})//Endereço

                next nCont
            endif

            //Se houver quantidade de pedidos de venda
            if (cAlias)->B2_QPEDVEN > 0

                //Busca os pedidos de venda do produto
                aSC6 := buscaSC6((cAlias)->B2_COD, aParam[10])

                for nCont := 1 To Len(aSC6)

                    aAdd(aDocs,{aSC6[nCont][1],;//Data de emissão
                                aSC6[nCont][2],;//Número
                                aSC6[nCont][3],;//Item                   
                                aSC6[nCont][4],;//Status
                                aSC6[nCont][5],;//Armazém
                                aSC6[nCont][6],;//Quantidade
                                STR0017,;//Tipo-Pedido de Venda
                                STR0011,;//Registro-Saída
                                '',;//Produto Pai
                                aSC6[nCont][8],;//Lote
                                aSC6[nCont][9],;//Sublote
                                ''})//Endereço

                next nCont
            endif

            //Se houver reserva
            if (cAlias)->B2_RESERVA > 0

                //Busca as reservas para Faturamento
                aSC0 := buscaSC0((cAlias)->B2_COD)

                for nCont := 1 To Len(aSC0)

                    aAdd(aDocs,{aSC0[nCont][1],;//Data de emissão
                                aSC0[nCont][2],;//Número
                                aSC0[nCont][3],;//Item                   
                                aSC0[nCont][4],;//Status
                                aSC0[nCont][5],;//Armazém
                                aSC0[nCont][6],;//Quantidade
                                STR0018,;//Tipo-Reserva para Faturamento
                                STR0011,;//Registro-Saída
                                '',;//Produto Pai
                                aSC0[nCont][8],;//Lote
                                aSC0[nCont][9],;//Sublote
                                ''})//Endereço

                next nCont
            endif

            //Envia os registros para o Smart View
            for nCont := 1 To Len(aDocs)

                ojItems := JsonObject():new()

                for nX := 1 To Len(self:aStruct)
                    //Campos auxiliares
                    if self:aStruct[nX][1] == 'DESCEMP'
                        ojItems[self:aStruct[nX][1]] := cDescEmp
                    elseif self:aStruct[nX][1] == 'DESCFIL'
                        ojItems[self:aStruct[nX][1]] := cDescFil
                    elseif self:aStruct[nX][1] == 'REGISTRO'
                        ojItems[self:aStruct[nX][1]] := aDocs[nCont][8]
                    elseif self:aStruct[nX][1] == 'DATA'
                        ojItems[self:aStruct[nX][1]] := totvs.framework.treports.date.stringToTimeStamp(aDocs[nCont][1])
                    elseif self:aStruct[nX][1] == 'TIPO'
                        ojItems[self:aStruct[nX][1]] := aDocs[nCont][7]
                    elseif self:aStruct[nX][1] == 'DOCUMENTO'
                        ojItems[self:aStruct[nX][1]] := aDocs[nCont][2]+aDocs[nCont][3]
                    elseif self:aStruct[nX][1] == 'STATUS'
                        ojItems[self:aStruct[nX][1]] := aDocs[nCont][4]
                    elseif self:aStruct[nX][1] == 'ARMAZEM'
                        ojItems[self:aStruct[nX][1]] := aDocs[nCont][5]
                    elseif self:aStruct[nX][1] == 'QUANTIDADE'
                        ojItems[self:aStruct[nX][1]] := aDocs[nCont][6]
                    elseif self:aStruct[nX][1] == 'PRODUTO_PAI'
                        ojItems[self:aStruct[nX][1]] := aDocs[nCont][9]
                    elseif self:aStruct[nX][1] == 'LOTE'
                        If Rastro( (cAlias)->B1_COD,"S")
                            ojItems[self:aStruct[nX][1]] := aDocs[nCont][10]+aDocs[nCont][11]
                        else
                            ojItems[self:aStruct[nX][1]] := aDocs[nCont][10]
                        endif
                    elseif self:aStruct[nX][1] == 'ENDERECO'
                        ojItems[self:aStruct[nX][1]] := aDocs[nCont][12]                
                    else 
                        //Campos do select principal
                        if self:aStruct[nX][3] == "date" //Converter data para o formato padrão - 2023-01-27T15:31:43Z
                            ojItems[self:aStruct[nX][1]] := totvs.framework.treports.date.stringToTimeStamp((cAlias)->&(self:aStruct[nX][5]))
                        else
                            ojItems[self:aStruct[nX][1]] := (cAlias)->&(self:aStruct[nX][5])  
                        endif
                    EndIf
                next nX

                self:ProcessData()
                self:oData:appendData(ojItems)

            next nCont
        endif

        (cAlias)->(DBSkip())

    enddo 

    (cAlias)->(DBCloseArea())
    oExec:Destroy()
    FreeObj(oExec)
    
return self:oData

/*/{Protheus.doc} getSchema
Retorna a estrutura dos campos
 
@return object: self:oSchema

@author ana.paula
@since 30/10/2023
@version 1.0
/*/
method getSchema() as object class ProjecaoEstoqueTReportsBusinessObject
    Local nX        := 0 as numeric

    //Campos do Select Principal
    self:aFields := {"B1_COD","B1_DESC","B1_TIPO","B1_UM","B1_GRUPO",;
                     "B2_LOCAL","B2_QATU","B2_QEMP","B2_QPEDVEN","B2_SALPEDI","B2_SALPPRE"}                     
    self:aStruct := PcpTrGetStruct(self:aFields)

    //Campos Auxiliares
    AAdd(self:aStruct , {"DESCEMP"    , "DESC_EMP"   , "string", "DESC_EMP"   , "DESC_EMP"   })
    AAdd(self:aStruct , {"DESCFIL"    , "DESC_FIL"   , "string", "DESC_FIL"   , "DESC_FIL"   })
    AAdd(self:aStruct , {"REGISTRO"   , "REGISTRO"   , "string", "REGISTRO"   , "REGISTRO"   })
    AAdd(self:aStruct , {"DATA"       , "DATA"       , "date"  , "DATA"       , "DATA"       })
    AAdd(self:aStruct , {"TIPO"       , "TIPO"       , "string", "TIPO"       , "TIPO"       })
    AAdd(self:aStruct , {"DOCUMENTO"  , "DOCUMENTO"  , "string", "DOCUMENTO"  , "DOCUMENTO"  })
    AAdd(self:aStruct , {"STATUS"     , "STATUS"     , "string", "STATUS"     , "STATUS"     })
    AAdd(self:aStruct , {"PRODUTO_PAI", "PRODUTO_PAI", "string", "PRODUTO_PAI", "PRODUTO_PAI"})
    AAdd(self:aStruct , {"ARMAZEM"    , "ARMAZEM"    , "string", "ARMAZEM"    , "ARMAZEM"    })
    AAdd(self:aStruct , {"QUANTIDADE" , "QUANTIDADE" , "number", "QUANTIDADE" , "QUANTIDADE" })
    AAdd(self:aStruct , {"LOTE"       , "LOTE"       , "string", "LOTE"       , "LOTE"       })
    AAdd(self:aStruct , {"ENDERECO"   , "ENDERECO"   , "string", "ENDERECO"   , "ENDERECO"   })
    
    for nX := 1 To Len(self:aStruct)
        self:addProperty(self:aStruct[nX][1], self:aStruct[nX][2], self:aStruct[nX][3], self:aStruct[nX][4], self:aStruct[nX][5])
    next nX

return self:oSchema

/*/{Protheus.doc} buscaSC1
Retorna as solicitações de compra do produto.
@type     Static Function
@author   Ana Paula dos Santos
@since    31/10/2023
@version  P12
@param 01 cProduto  , Caracter, Código do Produto.
@return   aSC1, Array, Array com as informações de retorno.
/*/
Static Function buscaSC1(cProduto)
    Local aSC1      := {}             as array
    Local cAliasSC1 := ""             as character
    Local cQuery    := ""             as character
    Local oExec     := Nil            as object

	cQuery := " SELECT SC1.C1_DATPRF, "
	cQuery += "        SC1.C1_NUM, "
	cQuery += "        SC1.C1_ITEM, "
	cQuery += "        (SC1.C1_QUANT - SC1.C1_QUJE) as saldoSC, "
	cQuery += "        SC1.C1_TPOP, "
	cQuery += "        SC1.C1_LOCAL "
	cQuery += "   FROM " + RetSqlName("SC1") + " SC1 "
	cQuery += "  WHERE SC1.C1_FILIAL  = ? "
	cQuery += "    AND SC1.C1_PRODUTO = ? "
    cQuery +=    " AND (SC1.C1_QUANT - SC1.C1_QUJE) > 0 "
	cQuery += "    AND SC1.D_E_L_E_T_ = ' ' "

    oExec := FwExecStatement():New(cQuery)

    oExec:SetString(1, xFilial("SC1"))
    oExec:SetString(2, cProduto)

    cAliasSC1 := oExec:OpenAlias()

    While (cAliasSC1)->(!Eof())

        aAdd(aSC1,{(cAliasSC1)->C1_DATPRF,;
                   (cAliasSC1)->C1_NUM,;
                   (cAliasSC1)->C1_ITEM,;                   
                   (cAliasSC1)->C1_TPOP,;
                   (cAliasSC1)->C1_LOCAL,;
                   (cAliasSC1)->saldoSC})

		(cAliasSC1)->(dbSkip())
	End

	(cAliasSC1)->(dbCloseArea())
    oExec:Destroy()
    FreeObj(oExec)

Return aSC1

/*/{Protheus.doc} buscaSC7
Retorna os pedidos de compra do produto.
@type     Static Function
@author   Ana Paula dos Santos
@since    01/11/2023
@version  P12
@param 01 cProduto  , Caracter, Código do Produto.
@return   aSC7, Array, Array com as informações de retorno.
/*/
Static Function buscaSC7(cProduto)
    Local aSC7      := {}             as array
    Local cAliasSC7 := ""             as character
    Local cQuery    := ""             as character
    Local oExec     := Nil            as object

	cQuery := " SELECT SC7.C7_DATPRF, "
	cQuery += "        SC7.C7_NUM, "
	cQuery += "        SC7.C7_ITEM, "
	cQuery += "        (SC7.C7_QUANT - SC7.C7_QUJE) as saldoPC, "
	cQuery += "        SC7.C7_TPOP, "
	cQuery += "        SC7.C7_LOCAL, "
    cQuery += "        SC7.C7_TIPO "
	cQuery += "   FROM " + RetSqlName("SC7") + " SC7 "
	cQuery += "  WHERE SC7.C7_FILIAL  = ? "
	cQuery += "    AND SC7.C7_PRODUTO = ? "
    cQuery += "    AND SC7.C7_RESIDUO = ? "
    cQuery += "    AND (SC7.C7_QUANT - SC7.C7_QUJE) > 0 "
	cQuery += "    AND SC7.D_E_L_E_T_ = ' ' "

    oExec := FwExecStatement():New(cQuery)

    oExec:SetString(1, xFilial("SC7"))
    oExec:SetString(2, cProduto)
    oExec:SetString(3, space(len(SC7->C7_RESIDUO)))

    cAliasSC7 := oExec:OpenAlias()

    While (cAliasSC7)->(!Eof())

        aAdd(aSC7,{(cAliasSC7)->C7_DATPRF,;
                   (cAliasSC7)->C7_NUM,;
                   (cAliasSC7)->C7_ITEM,;
                   (cAliasSC7)->C7_TPOP,;
                   (cAliasSC7)->C7_LOCAL,;
                   (cAliasSC7)->saldoPC,;
                   (cAliasSC7)->C7_TIPO,})

		(cAliasSC7)->(dbSkip())
	End

	(cAliasSC7)->(dbCloseArea())
    oExec:Destroy()
    FreeObj(oExec)

Return aSC7

/*/{Protheus.doc} buscaSC2
Retorna as ordens de produção do produto.
@type     Static Function
@author   Ana Paula dos Santos
@since    09/11/2023
@version  P12
@param 01 cProduto  , Caracter, Código do Produto.
@Param 02 nParam, numeric, Considera OPs? (1-Firmes/2-Previstas/3-Ambas)
@return   aSC2, Array, Array com as informações de retorno.
/*/
Static Function buscaSC2(cProduto, nParam)
    Local aSC2      := {}             as array
    Local cAliasSC2 := ""             as character
    Local cQuery    := ""             as character
    Local oExec     := Nil            as object

	cQuery := " SELECT SC2.C2_DATPRF, "
	cQuery += "        SC2.C2_NUM, "
	cQuery += "        SC2.C2_ITEM, "
    cQuery += "        SC2.C2_SEQUEN, "
	cQuery += "        (SC2.C2_QUANT - SC2.C2_QUJE) as saldoOP, "
	cQuery +=        " CASE "
    cQuery +=           " WHEN SC2.C2_TPOP = 'F' THEN 'Firme' "
	cQuery +=           " ELSE 'Previsto' "
	cQuery +=        " END status, "
	cQuery += "        SC2.C2_LOCAL "
	cQuery += "   FROM " + RetSqlName("SC2") + " SC2 "
	cQuery += "  WHERE SC2.C2_FILIAL  = ? "
	cQuery += "    AND SC2.C2_PRODUTO = ? "
    cQuery += "    AND (SC2.C2_QUANT - SC2.C2_QUJE) > 0 "
    If nParam == 1
        cQuery += " AND SC2.C2_TPOP = 'F' "
    ElseIf nParam == 2
        cQuery += " AND SC2.C2_TPOP = 'P' "
    EndIf
	cQuery += "    AND SC2.D_E_L_E_T_ = ' ' "

    oExec := FwExecStatement():New(cQuery)

    oExec:SetString(1, xFilial("SC2"))
    oExec:SetString(2, cProduto)

    cAliasSC2 := oExec:OpenAlias()

    While (cAliasSC2)->(!Eof())

        aAdd(aSC2,{(cAliasSC2)->C2_DATPRF,;
                   (cAliasSC2)->C2_NUM,;
                   (cAliasSC2)->C2_ITEM+(cAliasSC2)->C2_SEQUEN,;                   
                   (cAliasSC2)->status,;
                   (cAliasSC2)->C2_LOCAL,;
                   (cAliasSC2)->saldoOP,})

		(cAliasSC2)->(dbSkip())
	End

	(cAliasSC2)->(dbCloseArea())
    oExec:Destroy()
    FreeObj(oExec)

Return aSC2

/*/{Protheus.doc} buscaSD4
Retorna os empenhos do produto.
@type     Static Function
@author   Ana Paula dos Santos
@since    08/11/2023
@version  P12
@param 01 cProduto  , Caracter, Código do Produto.
@return   aSD4, Array, Array com as informações de retorno.
/*/
Static Function buscaSD4(cProduto)
    Local aSD4      := {}  as array
    Local cAliasSD4 := ""  as character
    Local cQuery    := ""  as character
    Local cTipo     := ""  as character
    Local oExec     := Nil as object

	cQuery := " SELECT SD4.D4_DATA, "
	cQuery +=        " SD4.D4_OP, "
	cQuery +=        " SD4.D4_QUANT, "
	cQuery +=        " SD4.D4_LOCAL, "
    cQuery +=        " SD4.D4_PRODUTO, " //Item Pai
    cQuery +=        " SC2.C2_TPOP, "
    cQuery +=        " SD4.D4_LOTECTL, "
    cQuery +=        " SD4.D4_NUMLOTE "
	cQuery += "   FROM " + RetSqlName("SD4") + " SD4 "
    cQuery +=  " INNER JOIN " + RetSqlName("SC2") + " SC2 "
    cQuery += "     ON SC2.C2_FILIAL  = ? "
    cQuery += "    AND " + PCPQrySC2("SC2", "SD4.D4_OP")
    cQuery += "    AND SC2.D_E_L_E_T_ = ' ' "
	cQuery += "  WHERE SD4.D4_FILIAL  = ? "
	cQuery += "    AND SD4.D4_COD     = ? "
    cQuery += "    AND SD4.D_E_L_E_T_ = ' ' "

    oExec := FwExecStatement():New(cQuery)

    oExec:SetString(1, xFilial("SC2"))
    oExec:SetString(2, xFilial("SD4"))
    oExec:SetString(3, cProduto)

    cAliasSD4 := oExec:OpenAlias()

    While (cAliasSD4)->(!Eof())

        If (cAliasSD4)->C2_TPOP == 'F'
            cTipo := STR0008 //"Firme"
        Else
            cTipo := STR0009 //"Previsto"
        EndIf

        aAdd(aSD4,{(cAliasSD4)->D4_DATA,;
                   (cAliasSD4)->D4_OP,;
                   '',;                   
                   cTipo,;
                   (cAliasSD4)->D4_LOCAL,;
                   (cAliasSD4)->D4_QUANT,;
                   (cAliasSD4)->D4_PRODUTO,;
                   (cAliasSD4)->D4_LOTECTL,;
                   (cAliasSD4)->D4_NUMLOTE})

		(cAliasSD4)->(dbSkip())
	End

	(cAliasSD4)->(dbCloseArea())
    oExec:Destroy()
    FreeObj(oExec)

Return aSD4

/*/{Protheus.doc} buscaSDC
Retorna a composição dos empenhos do produto.
@type     Static Function
@author   Ana Paula dos Santos
@since    20/11/2023
@version  P12
@param 01 cProduto  , Caracter, Código do Produto.
@param 02 cOp       , Caracter, Número da OP.
@param 03 cLote     , Caracter, Lote
@param 04 cSubLt    , Caracter, SubLote
@return   aSDC, Array, Array com as informações de retorno.
/*/
Static Function buscaSDC(cProduto,cOp,cLote,cSubLt)
    Local aSDC      := {}             as array
    Local cAliasSDC := ""             as character
    Local cQuery    := ""             as character
    Local oExec     := Nil            as object

    cQuery := " SELECT SDC.DC_PEDIDO, "
    cQuery += "        SDC.DC_QUANT, "
    cQuery += "        SDC.DC_LOCAL, "
    cQuery += "        SDC.DC_LOTECTL, "
    cQuery += "        SDC.DC_NUMLOTE, "
    cQuery += "        SDC.DC_LOCALIZ "
    cQuery += "   FROM " + RetSqlName("SDC") + " SDC "
    cQuery += "  WHERE SDC.DC_FILIAL  = ? "
    cQuery += "    AND SDC.DC_PRODUTO = ? "
    cQuery += "    AND SDC.DC_OP      = ? "
    cQuery += "    AND SDC.DC_LOTECTL = ? "
    cQuery += "    AND SDC.DC_NUMLOTE = ? "
    cQuery += "    AND SDC.D_E_L_E_T_ = ' ' "

    oExec := FwExecStatement():New(cQuery)

    oExec:SetString(1, xFilial("SDC"))
    oExec:SetString(2, cProduto)
    oExec:SetString(3, cOp)
    oExec:SetString(4, cLote)
    oExec:SetString(5, cSubLt)

    cAliasSDC := oExec:OpenAlias()

    While (cAliasSDC)->(!Eof())

        aAdd(aSDC,{DtoS(dDataBase),;
                   (cAliasSDC)->DC_PEDIDO,;
                   '',;                   
                   '',;
                   (cAliasSDC)->DC_LOCAL,;
                   (cAliasSDC)->DC_QUANT,;
                   '',;
                   (cAliasSDC)->DC_LOTECTL,;
                   (cAliasSDC)->DC_NUMLOTE,;
                   (cAliasSDC)->DC_LOCALIZ})

		(cAliasSDC)->(dbSkip())
	End

	(cAliasSDC)->(dbCloseArea())
    oExec:Destroy()
    FreeObj(oExec)

Return aSDC

/*/{Protheus.doc} buscaAFJ
Retorna os empenhos de projeto produto.
@type     Static Function
@author   Ana Paula dos Santos
@since    08/11/2023
@version  P12
@param 01 cProduto  , Caracter, Código do Produto.
@return   aAFJ, Array, Array com as informações de retorno.
/*/
Static Function buscaAFJ(cProduto)
    Local aAFJ      := {}  as array
    Local cAliasAFJ := ""  as character
    Local cQuery    := ""  as character
    Local oExec     := Nil as object

	cQuery := " SELECT AFJ.AFJ_DATA, "
	cQuery += "        AFJ.AFJ_PROJET, "
	cQuery += "        AFJ.AFJ_QEMP, "
	cQuery += "        AFJ.AFJ_LOCAL, "
    cQuery += "        AFJ.AFJ_COD "
	cQuery += "   FROM " + RetSqlName("AFJ") + " AFJ "
	cQuery += "  WHERE AFJ.AFJ_FILIAL = ? "
	cQuery += "    AND AFJ.AFJ_COD    = ? "
    cQuery += "    AND AFJ.D_E_L_E_T_ = ' ' "

    oExec := FwExecStatement():New(cQuery)

    oExec:SetString(1, xFilial("AFJ"))
    oExec:setString(2, cProduto)
    
    cAliasAFJ := oExec:OpenAlias()

    While (cAliasAFJ)->(!Eof())

        aAdd(aAFJ,{(cAliasAFJ)->AFJ_DATA,;
                   (cAliasAFJ)->AFJ_PROJET,;
                   '',;                   
                   '',;
                   (cAliasAFJ)->AFJ_LOCAL,;
                   (cAliasAFJ)->AFJ_QEMP,;
                   (cAliasAFJ)->AFJ_COD})

		(cAliasAFJ)->(dbSkip())
	End

	(cAliasAFJ)->(dbCloseArea())
    oExec:Destroy()
    FreeObj(oExec)

Return aAFJ

/*/{Protheus.doc} buscaSC6
Retorna os pedidos de venda do produto.
@type     Static Function
@author   Ana Paula dos Santos
@since    07/11/2023
@version  P12
@param 01 cProduto , Caracter, Código do Produto.
@param 02 nParam, numeric, Considera Somente TES que atualiza estoque? (1-Sim/2-Não -> Default)
@return   aSC6, Array, Array com as informações de retorno.
/*/
Static Function buscaSC6(cProduto, nParam)
    Local aSC6      := {}  as array
    Local cAliasSC6 := ""  as character
    Local cQuery    := ""  as character
    Local cTipo     := ""  as character
    Local nPosParam := 0   as numeric
    Local nQtdEnt   := 0   as numeric
    Local nQtdPV    := 0   as numeric
    Local oExec     := Nil as object

	cQuery := " SELECT SC6.C6_ENTREG, "
	cQuery +=        " SC6.C6_NUM, "
	cQuery +=        " SC6.C6_QTDVEN, "
	cQuery +=        " SC6.C6_LOCAL, "
    cQuery +=        " SC6.C6_TPOP, "
    cQuery +=        " SC9.C9_QTDLIB, "
    cQuery +=        " SC6.C6_LOTECTL, "
    cQuery +=        " SC6.C6_NUMLOTE "
	cQuery += "   FROM " + RetSqlName("SC6") + " SC6 "

    If nParam == 1
        cQuery += " INNER JOIN " + RetSqlName("SF4") + " SF4 "
        cQuery += "  ON SF4.F4_FILIAL = ? "
        cQuery += " AND SF4.F4_CODIGO = SC6.C6_TES "
        cQuery += " AND SF4.F4_ESTOQUE = 'S' "
        cQuery += " AND SF4.D_E_L_E_T_ = ' ' "
    EndIf

    cQuery +=      " LEFT OUTER JOIN " + RetSqlName("SC9") + " SC9 "
    cQuery +=       "  ON SC9.C9_FILIAL = ? "
    cQuery +=       " AND SC9.C9_PEDIDO = SC6.C6_NUM "
	cQuery +=       " AND SC9.C9_ITEM   = SC6.C6_ITEM "
	cQuery +=       " AND SC9.C9_PRODUTO = SC6.C6_PRODUTO "
    cQuery +=       " AND (SC9.C9_BLEST = '10' OR ( SC9.C9_BLEST = ? AND SC9.C9_BLCRED = ? )) "
	cQuery +=       " AND SC9.D_E_L_E_T_ = ' ' "

	cQuery += "  WHERE SC6.C6_FILIAL  = ? "
	cQuery += "    AND SC6.C6_PRODUTO = ? "
    cQuery += "    AND SC6.D_E_L_E_T_ = ' ' "

    nPosParam := 1

    oExec := FwExecStatement():New(cQuery)

    If nParam == 1
        oExec:SetString(nPosParam++, xFilial("SF4"))
    EndIf
    oExec:SetString(nPosParam++, xFilial("SC9"))
    oExec:SetString(nPosParam++, space(len(SC9->C9_BLEST)))
    oExec:setString(nPosParam++, space(len(SC9->C9_BLCRED)))
    oExec:SetString(nPosParam++, xFilial("SC6"))
    oExec:SetString(nPosParam++, cProduto)

    cAliasSC6 := oExec:OpenAlias()

    While (cAliasSC6)->(!Eof())

        If EMPTY( (cAliasSC6)->C9_QTDLIB )
            nQtdEnt := 0
        else
            nQtdEnt := (cAliasSC6)->C9_QTDLIB
        endif

        nQtdPV := (cAliasSC6)->C6_QTDVEN - nQtdEnt

        if nQtdPV = 0
            (cAliasSC6)->(dbSkip())
            loop
        end if

        If (cAliasSC6)->C6_TPOP == 'F'
            cTipo := STR0008 //"Firme"
        Else
            cTipo := STR0009 //"Previsto"
        EndIf

        aAdd(aSC6,{(cAliasSC6)->C6_ENTREG,;
                   (cAliasSC6)->C6_NUM,;
                   '',;                   
                   cTipo,;
                   (cAliasSC6)->C6_LOCAL,;
                   nQtdPV,;
                   '',;
                   (cAliasSC6)->C6_LOTECTL,;
                   (cAliasSC6)->C6_NUMLOTE})

		(cAliasSC6)->(dbSkip())
	End

	(cAliasSC6)->(dbCloseArea())
    oExec:Destroy()
    FreeObj(oExec)

Return aSC6

/*/{Protheus.doc} buscaSC0
Retorna as reservas para faturamento do produto.
@type     Static Function
@author   Ana Paula dos Santos
@since    20/11/2023
@version  P12
@param 01 cProduto  , Caracter, Código do Produto.
@return   aSC0, Array, Array com as informações de retorno.
/*/
Static Function buscaSC0(cProduto)
    Local aSC0      := {}             as array
    Local cAliasSC0 := ""             as character
    Local cQuery    := ""             as character
    Local oExec     := Nil            as object

	cQuery := " SELECT SC0.C0_EMISSAO, "
	cQuery += "        SC0.C0_NUM, "
	cQuery += "        SC0.C0_QUANT, "
	cQuery += "        SC0.C0_LOCAL, "
    cQuery += "        SC0.C0_LOTECTL, "
    cQuery += "        SC0.C0_NUMLOTE "
    cQuery += "   FROM " + RetSqlName("SC0") + " SC0 "
	cQuery += "  WHERE SC0.C0_FILIAL  = ? "
	cQuery += "    AND SC0.C0_PRODUTO = ? "
    cQuery += "    AND SC0.D_E_L_E_T_ = ' ' "

    oExec := FwExecStatement():New(cQuery)

    oExec:SetString(1, xFilial("SC6"))
    oExec:SetString(2, cProduto)

    cAliasSC0 := oExec:OpenAlias()

    While (cAliasSC0)->(!Eof())

        aAdd(aSC0,{(cAliasSC0)->C0_EMISSAO,;
                   (cAliasSC0)->C0_NUM,;
                   '',;                   
                   STR0008,;
                   (cAliasSC0)->C0_LOCAL,;
                   (cAliasSC0)->C0_QUANT,;
                   '',;
                   (cAliasSC0)->C0_LOTECTL,;
                   (cAliasSC0)->C0_NUMLOTE})

		(cAliasSC0)->(dbSkip())
	End

	(cAliasSC0)->(dbCloseArea())
    oExec:Destroy()
    FreeObj(oExec)

Return aSC0
