#include "tlpp-core.th"
#include "tlpp-rest.th"

namespace tr.receiptDetail

using namespace tr.util
using namespace tr.receiptDetail.Service

/*/{Protheus.doc} receiptDetailController
Clase donde se declaran los endpoints
@type class
@version  1
@author José González
@since 04/03/2021
/*/
class receiptDetailController

    public method New()

    @Post('/api/v1/totvsRecibos/titles/receiptDetail')
    public method postReceipDetail()
    
endclass

/*/{Protheus.doc} receiptDetailController::new
Constructor de clase
@type method
@version  1
@author José González
@since 04/03/2021
/*/
Method new() class receiptDetailController
return 

/*/{Protheus.doc} receiptDetailController::postReceipDetail
Endpoint para obtener el detalle del titulo seleccionado
@type method
@version  1
@author José González
@since 04/03/2021
/*/
Method postReceipDetail() Class receiptDetailController

	Local oReceiptDetailService as Object
	Local body 
	Local bodyContent 
	Local response as Object

	body := JsonObject():New()
	bodyContent := body:fromJson(oRest:GetBodyRequest())

	If ( bodyContent <> nil )
		oRest:setStatusCode ( 403 )
		oRest:setResponse( "NULL" + bodyContent )
	Else
		oReceiptDetailService := receiptDetailService():new()
		response  := oReceiptDetailService:getreceiptDetailService(body)		
	EndIf
	AnswerRest(response)
Return .T.
