#INCLUDE "loca037.ch" 
/*/{PROTHEUS.DOC} LOCA037.PRW
ITUP BUSINESS - TOTVS RENTAL
VALIDA SE A HORA QUE FOI DIGITADA NO CAMPO FPP_HR PARA UMA DATA VALIDA
@TYPE FUNCTION
@AUTHOR FRANK ZWARG FUGA
@SINCE 03/12/2020
@VERSION P12
@HISTORY 03/12/2020, FRANK ZWARG FUGA, FONTE PRODUTIZADO.
/*/

#INCLUDE "RWMAKE.CH" 
#INCLUDE "PROTHEUS.CH" 
#INCLUDE "TOPCONN.CH" 

FUNCTION LOCA037()
LOCAL LRET
LOCAL LHORA := .F.
LOCAL LMIN  := .F.
LOCAL NHORA := VAL(SUBSTR(M->FPP_HRPARA,1,2))
LOCAL NMIN  := VAL(SUBSTR(M->FPP_HRPARA,4,2))

IF (NHORA > 24)
	LRET  := .F.
	LHORA := .T.
ENDIF

IF (NMIN > 59)
	LRET  := .F.
	LMIN  := .T.
ENDIF

IF LHORA .AND. LMIN 
	MSGALERT(STR0001+CVALTOCHAR(NHORA) +STR0002+CVALTOCHAR(NMIN)+STR0003 , STR0004)  //"ATENÇÃO: HORA(S) "###" E MINUTO(S) "###" DIGITADOS INVALIDOS !"###"GPO - LOCF106.PRW"
ELSEIF LHORA 
	MSGALERT(STR0001+CVALTOCHAR(NHORA) +STR0005 , STR0004)  //"ATENÇÃO: HORA(S) "###" DIGITADA INVALIDA !"###"GPO - LOCF106.PRW"
ELSEIF LMIN 
	MSGALERT(STR0006+CVALTOCHAR(NMIN) +STR0007 , STR0004)  //"ATENÇÃO: MINUTO(S) "###" DIGITADO INVALIDO !"###"GPO - LOCF106.PRW"
ELSE 
	LRET := .T. 
ENDIF 

RETURN(LRET) 
