#include "TOTVS.CH"

Class CenMprBkr from CenMapper

    Method New() Constructor

EndClass

Method New() Class CenMprBkr
    _Super:new()

    aAdd(self:aFields,{"BKR_ANO" ,"referenceYear"})
    aAdd(self:aFields,{"BKR_CDCOMP" ,"commitmentCode"})
    aAdd(self:aFields,{"BKR_CDOBRI" ,"requirementCode"})
    aAdd(self:aFields,{"BKR_CODOPE" ,"operatorRecord"})
    aAdd(self:aFields,{"BKR_NMGOPE" ,"operatorFormNumber"})
    aAdd(self:aFields,{"BKR_DTPRGU" ,"formProcDt"})
    aAdd(self:aFields,{"BKR_LOTE" ,"batchCode"})
    aAdd(self:aFields,{"BKR_MATRIC" ,"registration"})
    aAdd(self:aFields,{"BKR_MOTSAI" ,"outflowType"})
    aAdd(self:aFields,{"BKR_DTPROT" ,"collectionProtocolDate"})
    aAdd(self:aFields,{"BKR_FORENV" ,"submissionMethod"})
    aAdd(self:aFields,{"BKR_HORINC" ,"inclusionTime"})
    aAdd(self:aFields,{"BKR_HORPRO" ,"processingTime"})
    aAdd(self:aFields,{"BKR_IDEEXC" ,"executerId"})
    aAdd(self:aFields,{"BKR_IDEREE" ,"refundId"})
    aAdd(self:aFields,{"BKR_IDVLRP" ,"presetValueIdent"})
    aAdd(self:aFields,{"BKR_INAVIV" ,"newborn"})
    aAdd(self:aFields,{"BKR_INDACI" ,"indicAccident"})
    aAdd(self:aFields,{"BKR_NMGPRE" ,"providerFormNumber"})
    aAdd(self:aFields,{"BKR_NMGPRI" ,"mainFormNumb"})
    aAdd(self:aFields,{"BKR_OREVAT" ,"eventOrigin"})
    aAdd(self:aFields,{"BKR_REGINT" ,"hospRegime"})
    aAdd(self:aFields,{"BKR_RGOPIN" ,"ansRecordNumber"})
    aAdd(self:aFields,{"BKR_SOLINT" ,"hospitalizationRequest"})
    aAdd(self:aFields,{"BKR_STATUS" ,"status"})
    aAdd(self:aFields,{"BKR_TIPADM" ,"admissionType"})
    aAdd(self:aFields,{"BKR_TIPATE" ,"serviceType"})
    aAdd(self:aFields,{"BKR_TIPCON" ,"appointmentType"})
    aAdd(self:aFields,{"BKR_TIPFAT" ,"invoicingTp"})
    aAdd(self:aFields,{"BKR_TIPINT" ,"hospTp"})
    aAdd(self:aFields,{"BKR_TPEVAT" ,"aEventType"})
    aAdd(self:aFields,{"BKR_TPRGMN" ,"monitoringRecordType"})
    aAdd(self:aFields,{"BKR_VLTCOP" ,"coPaymentTotalValue"})
    aAdd(self:aFields,{"BKR_VLTDIA" ,"dailyRatesTotalValue"})
    aAdd(self:aFields,{"BKR_VLTFOR" ,"valuePaidSuppliers"})
    aAdd(self:aFields,{"BKR_VLTGLO" ,"formDisallowanceValue"})
    aAdd(self:aFields,{"BKR_VLTGUI" ,"valuePaidForm"})
    aAdd(self:aFields,{"BKR_VLTINF" ,"totalValueEntered"})
    aAdd(self:aFields,{"BKR_VLTMAT" ,"materialsTotalValue"})
    aAdd(self:aFields,{"BKR_VLTMED" ,"medicationTotalValue"})
    aAdd(self:aFields,{"BKR_VLTOPM" ,"totalOpmeValue"})
    aAdd(self:aFields,{"BKR_VLTPGP" ,"procedureTotalValuePai"})
    aAdd(self:aFields,{"BKR_VLTPRO" ,"valueProcessed"})
    aAdd(self:aFields,{"BKR_VLTTAX" ,"feesTotalValue"})
    aAdd(self:aFields,{"BKR_VLTTBP" ,"ownTableTotalValue"})
    aAdd(self:aFields,{"BKR_VTISPR" ,"tissProviderVersion"})
    aAdd(self:aFields,{"BKR_CPFCNP" ,"providerCpfCnpj"})
    aAdd(self:aFields,{"BKR_DATAUT" ,"authorizationDate"})
    aAdd(self:aFields,{"BKR_DATINC" ,"inclusionDate"})
    aAdd(self:aFields,{"BKR_DATPRO" ,"processingDate"})
    aAdd(self:aFields,{"BKR_DATREA" ,"executionDate"})
    aAdd(self:aFields,{"BKR_DATSOL" ,"requestDate"})
    aAdd(self:aFields,{"BKR_DIAACP" ,"escortDailyRates"})
    aAdd(self:aFields,{"BKR_DIAUTI" ,"icuDailyRates"})
    aAdd(self:aFields,{"BKR_DTFIFT" ,"invoicingEndDate"})
    aAdd(self:aFields,{"BKR_DTINFT" ,"invoicingStartDate"})
    aAdd(self:aFields,{"BKR_DTPAGT" ,"paymentDt"})
    aAdd(self:aFields,{"BKR_CNES" ,"cnes"})
    aAdd(self:aFields,{"BKR_CDMNEX" ,"executingCityCode"})
    aAdd(self:aFields,{"BKR_CBOS" ,"cboSCode"})
    aAdd(self:aFields,{"BKR_CDCID1" ,"icdDiagnosis1"})
    aAdd(self:aFields,{"BKR_CDCID2" ,"icdDiagnosis2"})
    aAdd(self:aFields,{"BKR_CDCID3" ,"icdDiagnosis3"})
    aAdd(self:aFields,{"BKR_CDCID4" ,"icdDiagnosis4"})

Return self
