#INCLUDE "PROTHEUS.CH"
#INCLUDE "APWEBSRV.CH"

/* ===============================================================================
WSDL Location    http://10.172.68.90:1112/ws/RHVACATIONNOTICE.apw?WSDL
Gerado em        09/08/17 16:48:27
Observações      Código-Fonte gerado por ADVPL WSDL Client 1.120703
                 Alterações neste arquivo podem causar funcionamento incorreto
                 e serão perdidas caso o código-fonte seja gerado novamente.
=============================================================================== */

User Function _TUJTEPG ; Return  // "dummy" function - Internal Use 

/* -------------------------------------------------------------------------------
WSDL Service WSRHVACATIONNOTICE
------------------------------------------------------------------------------- */

WSCLIENT WSRHVACATIONNOTICE

	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD RESET
	WSMETHOD CLONE
	WSMETHOD ACCEPTNOTICE
	WSMETHOD BROWSEVACATIONNOTICE
	WSMETHOD GETVACATIONNOTICE

	WSDATA   _URL                      AS String
	WSDATA   _HEADOUT                  AS Array of String
	WSDATA   _COOKIES                  AS Array of String
	WSDATA   cBRANCH                   AS string
	WSDATA   cREGISTRATION             AS string
	WSDATA   dENJOYMENTSTARTDATE       AS date
	WSDATA   oWSACCEPTNOTICERESULT     AS RHVACATIONNOTICE_TVACATIONNOTICE
	WSDATA   nCURRENTPAGE              AS integer
	WSDATA   cFILTERFIELD              AS string
	WSDATA   cFILTERVALUE              AS string
	WSDATA   oWSBROWSEVACATIONNOTICERESULT AS RHVACATIONNOTICE_TVACATIONNOTICEBROWSE
	WSDATA   dACQUISITIVESTARTDATE     AS date
	WSDATA   dACQUISITIVEENDDATE       AS date
	WSDATA   dENJOYMENTENDDATE         AS date
	WSDATA   nPECUNIARYALLOWANCE       AS integer
	WSDATA   cNOTICETYPE               AS string
	WSDATA   cNOTICEACCEPTANCE         AS string
	WSDATA   oWSGETVACATIONNOTICERESULT AS RHVACATIONNOTICE_TVACATIONNOTICE

ENDWSCLIENT

WSMETHOD NEW WSCLIENT WSRHVACATIONNOTICE
::Init()
If !FindFunction("XMLCHILDEX")
	UserException("O Código-Fonte Client atual requer os executáveis do Protheus Build [7.00.131227A-20170213 NG] ou superior. Atualize o Protheus ou gere o Código-Fonte novamente utilizando o Build atual.")
EndIf
Return Self

WSMETHOD INIT WSCLIENT WSRHVACATIONNOTICE
	::oWSACCEPTNOTICERESULT := RHVACATIONNOTICE_TVACATIONNOTICE():New()
	::oWSBROWSEVACATIONNOTICERESULT := RHVACATIONNOTICE_TVACATIONNOTICEBROWSE():New()
	::oWSGETVACATIONNOTICERESULT := RHVACATIONNOTICE_TVACATIONNOTICE():New()
Return

WSMETHOD RESET WSCLIENT WSRHVACATIONNOTICE
	::cBRANCH            := NIL 
	::cREGISTRATION      := NIL 
	::dENJOYMENTSTARTDATE := NIL 
	::oWSACCEPTNOTICERESULT := NIL 
	::nCURRENTPAGE       := NIL 
	::cFILTERFIELD       := NIL 
	::cFILTERVALUE       := NIL 
	::oWSBROWSEVACATIONNOTICERESULT := NIL 
	::dACQUISITIVESTARTDATE := NIL 
	::dACQUISITIVEENDDATE := NIL 
	::dENJOYMENTENDDATE  := NIL 
	::nPECUNIARYALLOWANCE := NIL 
	::cNOTICETYPE        := NIL 
	::cNOTICEACCEPTANCE  := NIL 
	::oWSGETVACATIONNOTICERESULT := NIL 
	::Init()
Return

WSMETHOD CLONE WSCLIENT WSRHVACATIONNOTICE
Local oClone := WSRHVACATIONNOTICE():New()
	oClone:_URL          := ::_URL 
	oClone:cBRANCH       := ::cBRANCH
	oClone:cREGISTRATION := ::cREGISTRATION
	oClone:dENJOYMENTSTARTDATE := ::dENJOYMENTSTARTDATE
	oClone:oWSACCEPTNOTICERESULT :=  IIF(::oWSACCEPTNOTICERESULT = NIL , NIL ,::oWSACCEPTNOTICERESULT:Clone() )
	oClone:nCURRENTPAGE  := ::nCURRENTPAGE
	oClone:cFILTERFIELD  := ::cFILTERFIELD
	oClone:cFILTERVALUE  := ::cFILTERVALUE
	oClone:oWSBROWSEVACATIONNOTICERESULT :=  IIF(::oWSBROWSEVACATIONNOTICERESULT = NIL , NIL ,::oWSBROWSEVACATIONNOTICERESULT:Clone() )
	oClone:dACQUISITIVESTARTDATE := ::dACQUISITIVESTARTDATE
	oClone:dACQUISITIVEENDDATE := ::dACQUISITIVEENDDATE
	oClone:dENJOYMENTENDDATE := ::dENJOYMENTENDDATE
	oClone:nPECUNIARYALLOWANCE := ::nPECUNIARYALLOWANCE
	oClone:cNOTICETYPE   := ::cNOTICETYPE
	oClone:cNOTICEACCEPTANCE := ::cNOTICEACCEPTANCE
	oClone:oWSGETVACATIONNOTICERESULT :=  IIF(::oWSGETVACATIONNOTICERESULT = NIL , NIL ,::oWSGETVACATIONNOTICERESULT:Clone() )
Return oClone

// WSDL Method ACCEPTNOTICE of Service WSRHVACATIONNOTICE

WSMETHOD ACCEPTNOTICE WSSEND cBRANCH,cREGISTRATION,dENJOYMENTSTARTDATE WSRECEIVE oWSACCEPTNOTICERESULT WSCLIENT WSRHVACATIONNOTICE
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<ACCEPTNOTICE xmlns="http://10.172.68.90:1112/">'
cSoap += WSSoapValue("BRANCH", ::cBRANCH, cBRANCH , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("REGISTRATION", ::cREGISTRATION, cREGISTRATION , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("ENJOYMENTSTARTDATE", ::dENJOYMENTSTARTDATE, dENJOYMENTSTARTDATE , "date", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += "</ACCEPTNOTICE>"

oXmlRet := SvcSoapCall(	Self,cSoap,; 
	"http://10.172.68.90:1112/ACCEPTNOTICE",; 
	"DOCUMENT","http://10.172.68.90:1112/",,"1.031217",; 
	"http://10.172.68.90:1112/ws/RHVACATIONNOTICE.apw")

::Init()
::oWSACCEPTNOTICERESULT:SoapRecv( WSAdvValue( oXmlRet,"_ACCEPTNOTICERESPONSE:_ACCEPTNOTICERESULT","TVACATIONNOTICE",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.

// WSDL Method BROWSEVACATIONNOTICE of Service WSRHVACATIONNOTICE

WSMETHOD BROWSEVACATIONNOTICE WSSEND cBRANCH,cREGISTRATION,nCURRENTPAGE,cFILTERFIELD,cFILTERVALUE WSRECEIVE oWSBROWSEVACATIONNOTICERESULT WSCLIENT WSRHVACATIONNOTICE
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<BROWSEVACATIONNOTICE xmlns="http://10.172.68.90:1112/">'
cSoap += WSSoapValue("BRANCH", ::cBRANCH, cBRANCH , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("REGISTRATION", ::cREGISTRATION, cREGISTRATION , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("CURRENTPAGE", ::nCURRENTPAGE, nCURRENTPAGE , "integer", .F. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("FILTERFIELD", ::cFILTERFIELD, cFILTERFIELD , "string", .F. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("FILTERVALUE", ::cFILTERVALUE, cFILTERVALUE , "string", .F. , .F., 0 , NIL, .F.,.F.) 
cSoap += "</BROWSEVACATIONNOTICE>"

oXmlRet := SvcSoapCall(	Self,cSoap,; 
	"http://10.172.68.90:1112/BROWSEVACATIONNOTICE",; 
	"DOCUMENT","http://10.172.68.90:1112/",,"1.031217",; 
	"http://10.172.68.90:1112/ws/RHVACATIONNOTICE.apw")

::Init()
::oWSBROWSEVACATIONNOTICERESULT:SoapRecv( WSAdvValue( oXmlRet,"_BROWSEVACATIONNOTICERESPONSE:_BROWSEVACATIONNOTICERESULT","TVACATIONNOTICEBROWSE",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.

// WSDL Method GETVACATIONNOTICE of Service WSRHVACATIONNOTICE

WSMETHOD GETVACATIONNOTICE WSSEND cBRANCH,cREGISTRATION,dACQUISITIVESTARTDATE,dACQUISITIVEENDDATE,dENJOYMENTSTARTDATE,dENJOYMENTENDDATE,nPECUNIARYALLOWANCE,cNOTICETYPE,cNOTICEACCEPTANCE WSRECEIVE oWSGETVACATIONNOTICERESULT WSCLIENT WSRHVACATIONNOTICE
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<GETVACATIONNOTICE xmlns="http://10.172.68.90:1112/">'
cSoap += WSSoapValue("BRANCH", ::cBRANCH, cBRANCH , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("REGISTRATION", ::cREGISTRATION, cREGISTRATION , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("ACQUISITIVESTARTDATE", ::dACQUISITIVESTARTDATE, dACQUISITIVESTARTDATE , "date", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("ACQUISITIVEENDDATE", ::dACQUISITIVEENDDATE, dACQUISITIVEENDDATE , "date", .F. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("ENJOYMENTSTARTDATE", ::dENJOYMENTSTARTDATE, dENJOYMENTSTARTDATE , "date", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("ENJOYMENTENDDATE", ::dENJOYMENTENDDATE, dENJOYMENTENDDATE , "date", .F. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("PECUNIARYALLOWANCE", ::nPECUNIARYALLOWANCE, nPECUNIARYALLOWANCE , "integer", .F. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("NOTICETYPE", ::cNOTICETYPE, cNOTICETYPE , "string", .F. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("NOTICEACCEPTANCE", ::cNOTICEACCEPTANCE, cNOTICEACCEPTANCE , "string", .F. , .F., 0 , NIL, .F.,.F.) 
cSoap += "</GETVACATIONNOTICE>"

oXmlRet := SvcSoapCall(	Self,cSoap,; 
	"http://10.172.68.90:1112/GETVACATIONNOTICE",; 
	"DOCUMENT","http://10.172.68.90:1112/",,"1.031217",; 
	"http://10.172.68.90:1112/ws/RHVACATIONNOTICE.apw")

::Init()
::oWSGETVACATIONNOTICERESULT:SoapRecv( WSAdvValue( oXmlRet,"_GETVACATIONNOTICERESPONSE:_GETVACATIONNOTICERESULT","TVACATIONNOTICE",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.


// WSDL Data Structure TVACATIONNOTICE

WSSTRUCT RHVACATIONNOTICE_TVACATIONNOTICE
	WSDATA   dACQUISITIVEENDDATE       AS date
	WSDATA   dACQUISITIVESTARTDATE     AS date
	WSDATA   dADMISSIONDATE            AS date
	WSDATA   cBANKACCOUNT              AS string
	WSDATA   cBANKAGENCY               AS string
	WSDATA   cBANKNAME                 AS string
	WSDATA   cBRANCH                   AS string
	WSDATA   cCNPJ                     AS string
	WSDATA   cCOMPANYNAME              AS string
	WSDATA   cCOMPANYSTATE             AS string
	WSDATA   cCPF                      AS string
	WSDATA   cEMPLOYEENAME             AS string
	WSDATA   cEMPLOYEESOCIALNAME       AS string
	WSDATA   cEMPLOYEEREGISTRATION     AS string
	WSDATA   dENJOYMENTENDDATE         AS date
	WSDATA   dENJOYMENTSTARTDATE       AS date
	WSDATA   cFUNCTIONDESCRIPTION      AS string
	WSDATA   cIDENTITY                 AS string
	WSDATA   nIRRFDEPENDENTS           AS integer
	WSDATA   oWSITENS                  AS RHVACATIONNOTICE_ARRAYOFTVACATIONNOTICEITEM OPTIONAL
	WSDATA   cLABORCARDNUMBER          AS string
	WSDATA   cLABORCARDSERIES          AS string
	WSDATA   cLABORCARDSTATE           AS string
	WSDATA   cLOGO                     AS string OPTIONAL
	WSDATA   cNOTICEACCEPTANCE         AS string
	WSDATA   dNOTICEDATE               AS date OPTIONAL
	WSDATA   cNOTICETYPE               AS string
	WSDATA   dOVERDUEDATE              AS date
	WSDATA   nPAYDLEAVE                AS integer
	WSDATA   nPAYDLEAVEFOLLOW          AS integer
	WSDATA   nPECUNIARYALLOWANCE       AS integer
	WSDATA   dRECEIPTDATE              AS date
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT RHVACATIONNOTICE_TVACATIONNOTICE
	::Init()
Return Self

WSMETHOD INIT WSCLIENT RHVACATIONNOTICE_TVACATIONNOTICE
Return

WSMETHOD CLONE WSCLIENT RHVACATIONNOTICE_TVACATIONNOTICE
	Local oClone := RHVACATIONNOTICE_TVACATIONNOTICE():NEW()
	oClone:dACQUISITIVEENDDATE  := ::dACQUISITIVEENDDATE
	oClone:dACQUISITIVESTARTDATE := ::dACQUISITIVESTARTDATE
	oClone:dADMISSIONDATE       := ::dADMISSIONDATE
	oClone:cBANKACCOUNT         := ::cBANKACCOUNT
	oClone:cBANKAGENCY          := ::cBANKAGENCY
	oClone:cBANKNAME            := ::cBANKNAME
	oClone:cBRANCH              := ::cBRANCH
	oClone:cCNPJ                := ::cCNPJ
	oClone:cCOMPANYNAME         := ::cCOMPANYNAME
	oClone:cCOMPANYSTATE        := ::cCOMPANYSTATE
	oClone:cCPF                 := ::cCPF
	oClone:cEMPLOYEENAME        := ::cEMPLOYEENAME
	oClone:cEMPLOYEESOCIALNAME  := ::cEMPLOYEESOCIALNAME
	oClone:cEMPLOYEEREGISTRATION := ::cEMPLOYEEREGISTRATION
	oClone:dENJOYMENTENDDATE    := ::dENJOYMENTENDDATE
	oClone:dENJOYMENTSTARTDATE  := ::dENJOYMENTSTARTDATE
	oClone:cFUNCTIONDESCRIPTION := ::cFUNCTIONDESCRIPTION
	oClone:cIDENTITY            := ::cIDENTITY
	oClone:nIRRFDEPENDENTS      := ::nIRRFDEPENDENTS
	oClone:oWSITENS             := IIF(::oWSITENS = NIL , NIL , ::oWSITENS:Clone() )
	oClone:cLABORCARDNUMBER     := ::cLABORCARDNUMBER
	oClone:cLABORCARDSERIES     := ::cLABORCARDSERIES
	oClone:cLABORCARDSTATE      := ::cLABORCARDSTATE
	oClone:cLOGO                := ::cLOGO
	oClone:cNOTICEACCEPTANCE    := ::cNOTICEACCEPTANCE
	oClone:dNOTICEDATE          := ::dNOTICEDATE
	oClone:cNOTICETYPE          := ::cNOTICETYPE
	oClone:dOVERDUEDATE         := ::dOVERDUEDATE
	oClone:nPAYDLEAVE           := ::nPAYDLEAVE
	oClone:nPAYDLEAVEFOLLOW     := ::nPAYDLEAVEFOLLOW
	oClone:nPECUNIARYALLOWANCE  := ::nPECUNIARYALLOWANCE
	oClone:dRECEIPTDATE         := ::dRECEIPTDATE
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT RHVACATIONNOTICE_TVACATIONNOTICE
	Local oNode19
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::dACQUISITIVEENDDATE :=  WSAdvValue( oResponse,"_ACQUISITIVEENDDATE","date",NIL,"Property dACQUISITIVEENDDATE as s:date on SOAP Response not found.",NIL,"D",NIL,NIL) 
	::dACQUISITIVESTARTDATE :=  WSAdvValue( oResponse,"_ACQUISITIVESTARTDATE","date",NIL,"Property dACQUISITIVESTARTDATE as s:date on SOAP Response not found.",NIL,"D",NIL,NIL) 
	::dADMISSIONDATE     :=  WSAdvValue( oResponse,"_ADMISSIONDATE","date",NIL,"Property dADMISSIONDATE as s:date on SOAP Response not found.",NIL,"D",NIL,NIL) 
	::cBANKACCOUNT       :=  WSAdvValue( oResponse,"_BANKACCOUNT","string",NIL,"Property cBANKACCOUNT as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cBANKAGENCY        :=  WSAdvValue( oResponse,"_BANKAGENCY","string",NIL,"Property cBANKAGENCY as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cBANKNAME          :=  WSAdvValue( oResponse,"_BANKNAME","string",NIL,"Property cBANKNAME as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cBRANCH            :=  WSAdvValue( oResponse,"_BRANCH","string",NIL,"Property cBRANCH as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCNPJ              :=  WSAdvValue( oResponse,"_CNPJ","string",NIL,"Property cCNPJ as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCOMPANYNAME       :=  WSAdvValue( oResponse,"_COMPANYNAME","string",NIL,"Property cCOMPANYNAME as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCOMPANYSTATE      :=  WSAdvValue( oResponse,"_COMPANYSTATE","string",NIL,"Property cCOMPANYSTATE as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCPF               :=  WSAdvValue( oResponse,"_CPF","string",NIL,"Property cCPF as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cEMPLOYEENAME      :=  WSAdvValue( oResponse,"_EMPLOYEENAME","string",NIL,"Property cEMPLOYEENAME as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cEMPLOYEESOCIALNAME :=  WSAdvValue( oResponse,"_EMPLOYEESOCIALNAME","string",NIL,"Property cEMPLOYEESOCIALNAME as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cEMPLOYEEREGISTRATION :=  WSAdvValue( oResponse,"_EMPLOYEEREGISTRATION","string",NIL,"Property cEMPLOYEEREGISTRATION as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::dENJOYMENTENDDATE  :=  WSAdvValue( oResponse,"_ENJOYMENTENDDATE","date",NIL,"Property dENJOYMENTENDDATE as s:date on SOAP Response not found.",NIL,"D",NIL,NIL) 
	::dENJOYMENTSTARTDATE :=  WSAdvValue( oResponse,"_ENJOYMENTSTARTDATE","date",NIL,"Property dENJOYMENTSTARTDATE as s:date on SOAP Response not found.",NIL,"D",NIL,NIL) 
	::cFUNCTIONDESCRIPTION :=  WSAdvValue( oResponse,"_FUNCTIONDESCRIPTION","string",NIL,"Property cFUNCTIONDESCRIPTION as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cIDENTITY          :=  WSAdvValue( oResponse,"_IDENTITY","string",NIL,"Property cIDENTITY as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::nIRRFDEPENDENTS    :=  WSAdvValue( oResponse,"_IRRFDEPENDENTS","integer",NIL,"Property nIRRFDEPENDENTS as s:integer on SOAP Response not found.",NIL,"N",NIL,NIL) 
	oNode19 :=  WSAdvValue( oResponse,"_ITENS","ARRAYOFTVACATIONNOTICEITEM",NIL,NIL,NIL,"O",NIL,NIL) 
	If oNode19 != NIL
		::oWSITENS := RHVACATIONNOTICE_ARRAYOFTVACATIONNOTICEITEM():New()
		::oWSITENS:SoapRecv(oNode19)
	EndIf
	::cLABORCARDNUMBER   :=  WSAdvValue( oResponse,"_LABORCARDNUMBER","string",NIL,"Property cLABORCARDNUMBER as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cLABORCARDSERIES   :=  WSAdvValue( oResponse,"_LABORCARDSERIES","string",NIL,"Property cLABORCARDSERIES as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cLABORCARDSTATE    :=  WSAdvValue( oResponse,"_LABORCARDSTATE","string",NIL,"Property cLABORCARDSTATE as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cLOGO              :=  WSAdvValue( oResponse,"_LOGO","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cNOTICEACCEPTANCE  :=  WSAdvValue( oResponse,"_NOTICEACCEPTANCE","string",NIL,"Property cNOTICEACCEPTANCE as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::dNOTICEDATE        :=  WSAdvValue( oResponse,"_NOTICEDATE","date",NIL,NIL,NIL,"D",NIL,NIL) 
	::cNOTICETYPE        :=  WSAdvValue( oResponse,"_NOTICETYPE","string",NIL,"Property cNOTICETYPE as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::dOVERDUEDATE       :=  WSAdvValue( oResponse,"_OVERDUEDATE","date",NIL,"Property dOVERDUEDATE as s:date on SOAP Response not found.",NIL,"D",NIL,NIL) 
	::nPAYDLEAVE         :=  WSAdvValue( oResponse,"_PAYDLEAVE","integer",NIL,"Property nPAYDLEAVE as s:integer on SOAP Response not found.",NIL,"N",NIL,NIL) 
	::nPAYDLEAVEFOLLOW   :=  WSAdvValue( oResponse,"_PAYDLEAVEFOLLOW","integer",NIL,"Property nPAYDLEAVEFOLLOW as s:integer on SOAP Response not found.",NIL,"N",NIL,NIL) 
	::nPECUNIARYALLOWANCE :=  WSAdvValue( oResponse,"_PECUNIARYALLOWANCE","integer",NIL,"Property nPECUNIARYALLOWANCE as s:integer on SOAP Response not found.",NIL,"N",NIL,NIL) 
	::dRECEIPTDATE       :=  WSAdvValue( oResponse,"_RECEIPTDATE","date",NIL,"Property dRECEIPTDATE as s:date on SOAP Response not found.",NIL,"D",NIL,NIL) 
Return

// WSDL Data Structure TVACATIONNOTICEBROWSE

WSSTRUCT RHVACATIONNOTICE_TVACATIONNOTICEBROWSE
	WSDATA   oWSITENS                  AS RHVACATIONNOTICE_ARRAYOFTVACATIONNOTICELIST OPTIONAL
	WSDATA   nPAGESTOTAL               AS integer OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT RHVACATIONNOTICE_TVACATIONNOTICEBROWSE
	::Init()
Return Self

WSMETHOD INIT WSCLIENT RHVACATIONNOTICE_TVACATIONNOTICEBROWSE
Return

WSMETHOD CLONE WSCLIENT RHVACATIONNOTICE_TVACATIONNOTICEBROWSE
	Local oClone := RHVACATIONNOTICE_TVACATIONNOTICEBROWSE():NEW()
	oClone:oWSITENS             := IIF(::oWSITENS = NIL , NIL , ::oWSITENS:Clone() )
	oClone:nPAGESTOTAL          := ::nPAGESTOTAL
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT RHVACATIONNOTICE_TVACATIONNOTICEBROWSE
	Local oNode1
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNode1 :=  WSAdvValue( oResponse,"_ITENS","ARRAYOFTVACATIONNOTICELIST",NIL,NIL,NIL,"O",NIL,NIL) 
	If oNode1 != NIL
		::oWSITENS := RHVACATIONNOTICE_ARRAYOFTVACATIONNOTICELIST():New()
		::oWSITENS:SoapRecv(oNode1)
	EndIf
	::nPAGESTOTAL        :=  WSAdvValue( oResponse,"_PAGESTOTAL","integer",NIL,NIL,NIL,"N",NIL,NIL) 
Return

// WSDL Data Structure ARRAYOFTVACATIONNOTICEITEM

WSSTRUCT RHVACATIONNOTICE_ARRAYOFTVACATIONNOTICEITEM
	WSDATA   oWSTVACATIONNOTICEITEM    AS RHVACATIONNOTICE_TVACATIONNOTICEITEM OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT RHVACATIONNOTICE_ARRAYOFTVACATIONNOTICEITEM
	::Init()
Return Self

WSMETHOD INIT WSCLIENT RHVACATIONNOTICE_ARRAYOFTVACATIONNOTICEITEM
	::oWSTVACATIONNOTICEITEM := {} // Array Of  RHVACATIONNOTICE_TVACATIONNOTICEITEM():New()
Return

WSMETHOD CLONE WSCLIENT RHVACATIONNOTICE_ARRAYOFTVACATIONNOTICEITEM
	Local oClone := RHVACATIONNOTICE_ARRAYOFTVACATIONNOTICEITEM():NEW()
	oClone:oWSTVACATIONNOTICEITEM := NIL
	If ::oWSTVACATIONNOTICEITEM <> NIL 
		oClone:oWSTVACATIONNOTICEITEM := {}
		aEval( ::oWSTVACATIONNOTICEITEM , { |x| aadd( oClone:oWSTVACATIONNOTICEITEM , x:Clone() ) } )
	Endif 
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT RHVACATIONNOTICE_ARRAYOFTVACATIONNOTICEITEM
	Local nRElem1, oNodes1, nTElem1
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNodes1 :=  WSAdvValue( oResponse,"_TVACATIONNOTICEITEM","TVACATIONNOTICEITEM",{},NIL,.T.,"O",NIL,NIL) 
	nTElem1 := len(oNodes1)
	For nRElem1 := 1 to nTElem1 
		If !WSIsNilNode( oNodes1[nRElem1] )
			aadd(::oWSTVACATIONNOTICEITEM , RHVACATIONNOTICE_TVACATIONNOTICEITEM():New() )
			::oWSTVACATIONNOTICEITEM[len(::oWSTVACATIONNOTICEITEM)]:SoapRecv(oNodes1[nRElem1])
		Endif
	Next
Return

// WSDL Data Structure ARRAYOFTVACATIONNOTICELIST

WSSTRUCT RHVACATIONNOTICE_ARRAYOFTVACATIONNOTICELIST
	WSDATA   oWSTVACATIONNOTICELIST    AS RHVACATIONNOTICE_TVACATIONNOTICELIST OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT RHVACATIONNOTICE_ARRAYOFTVACATIONNOTICELIST
	::Init()
Return Self

WSMETHOD INIT WSCLIENT RHVACATIONNOTICE_ARRAYOFTVACATIONNOTICELIST
	::oWSTVACATIONNOTICELIST := {} // Array Of  RHVACATIONNOTICE_TVACATIONNOTICELIST():New()
Return

WSMETHOD CLONE WSCLIENT RHVACATIONNOTICE_ARRAYOFTVACATIONNOTICELIST
	Local oClone := RHVACATIONNOTICE_ARRAYOFTVACATIONNOTICELIST():NEW()
	oClone:oWSTVACATIONNOTICELIST := NIL
	If ::oWSTVACATIONNOTICELIST <> NIL 
		oClone:oWSTVACATIONNOTICELIST := {}
		aEval( ::oWSTVACATIONNOTICELIST , { |x| aadd( oClone:oWSTVACATIONNOTICELIST , x:Clone() ) } )
	Endif 
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT RHVACATIONNOTICE_ARRAYOFTVACATIONNOTICELIST
	Local nRElem1, oNodes1, nTElem1
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNodes1 :=  WSAdvValue( oResponse,"_TVACATIONNOTICELIST","TVACATIONNOTICELIST",{},NIL,.T.,"O",NIL,NIL) 
	nTElem1 := len(oNodes1)
	For nRElem1 := 1 to nTElem1 
		If !WSIsNilNode( oNodes1[nRElem1] )
			aadd(::oWSTVACATIONNOTICELIST , RHVACATIONNOTICE_TVACATIONNOTICELIST():New() )
			::oWSTVACATIONNOTICELIST[len(::oWSTVACATIONNOTICELIST)]:SoapRecv(oNodes1[nRElem1])
		Endif
	Next
Return

// WSDL Data Structure TVACATIONNOTICEITEM

WSSTRUCT RHVACATIONNOTICE_TVACATIONNOTICEITEM
	WSDATA   cCODE                     AS string
	WSDATA   cDESCRIPTION              AS string
	WSDATA   nDISCOUNT                 AS float
	WSDATA   nREFERENCE                AS float
	WSDATA   nREVENUE                  AS float
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT RHVACATIONNOTICE_TVACATIONNOTICEITEM
	::Init()
Return Self

WSMETHOD INIT WSCLIENT RHVACATIONNOTICE_TVACATIONNOTICEITEM
Return

WSMETHOD CLONE WSCLIENT RHVACATIONNOTICE_TVACATIONNOTICEITEM
	Local oClone := RHVACATIONNOTICE_TVACATIONNOTICEITEM():NEW()
	oClone:cCODE                := ::cCODE
	oClone:cDESCRIPTION         := ::cDESCRIPTION
	oClone:nDISCOUNT            := ::nDISCOUNT
	oClone:nREFERENCE           := ::nREFERENCE
	oClone:nREVENUE             := ::nREVENUE
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT RHVACATIONNOTICE_TVACATIONNOTICEITEM
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::cCODE              :=  WSAdvValue( oResponse,"_CODE","string",NIL,"Property cCODE as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cDESCRIPTION       :=  WSAdvValue( oResponse,"_DESCRIPTION","string",NIL,"Property cDESCRIPTION as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::nDISCOUNT          :=  WSAdvValue( oResponse,"_DISCOUNT","float",NIL,"Property nDISCOUNT as s:float on SOAP Response not found.",NIL,"N",NIL,NIL) 
	::nREFERENCE         :=  WSAdvValue( oResponse,"_REFERENCE","float",NIL,"Property nREFERENCE as s:float on SOAP Response not found.",NIL,"N",NIL,NIL) 
	::nREVENUE           :=  WSAdvValue( oResponse,"_REVENUE","float",NIL,"Property nREVENUE as s:float on SOAP Response not found.",NIL,"N",NIL,NIL) 
Return

// WSDL Data Structure TVACATIONNOTICELIST

WSSTRUCT RHVACATIONNOTICE_TVACATIONNOTICELIST
	WSDATA   dACQUISITIVEENDDATE       AS date
	WSDATA   dACQUISITIVESTARTDATE     AS date
	WSDATA   dENJOYMENTENDDATE         AS date
	WSDATA   dENJOYMENTSTARTDATE       AS date
	WSDATA   cNOTICEACCEPTANCE         AS string
	WSDATA   cNOTICETYPE               AS string
	WSDATA   nPECUNIARYALLOWANCE       AS integer
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT RHVACATIONNOTICE_TVACATIONNOTICELIST
	::Init()
Return Self

WSMETHOD INIT WSCLIENT RHVACATIONNOTICE_TVACATIONNOTICELIST
Return

WSMETHOD CLONE WSCLIENT RHVACATIONNOTICE_TVACATIONNOTICELIST
	Local oClone := RHVACATIONNOTICE_TVACATIONNOTICELIST():NEW()
	oClone:dACQUISITIVEENDDATE  := ::dACQUISITIVEENDDATE
	oClone:dACQUISITIVESTARTDATE := ::dACQUISITIVESTARTDATE
	oClone:dENJOYMENTENDDATE    := ::dENJOYMENTENDDATE
	oClone:dENJOYMENTSTARTDATE  := ::dENJOYMENTSTARTDATE
	oClone:cNOTICEACCEPTANCE    := ::cNOTICEACCEPTANCE
	oClone:cNOTICETYPE          := ::cNOTICETYPE
	oClone:nPECUNIARYALLOWANCE  := ::nPECUNIARYALLOWANCE
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT RHVACATIONNOTICE_TVACATIONNOTICELIST
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::dACQUISITIVEENDDATE :=  WSAdvValue( oResponse,"_ACQUISITIVEENDDATE","date",NIL,"Property dACQUISITIVEENDDATE as s:date on SOAP Response not found.",NIL,"D",NIL,NIL) 
	::dACQUISITIVESTARTDATE :=  WSAdvValue( oResponse,"_ACQUISITIVESTARTDATE","date",NIL,"Property dACQUISITIVESTARTDATE as s:date on SOAP Response not found.",NIL,"D",NIL,NIL) 
	::dENJOYMENTENDDATE  :=  WSAdvValue( oResponse,"_ENJOYMENTENDDATE","date",NIL,"Property dENJOYMENTENDDATE as s:date on SOAP Response not found.",NIL,"D",NIL,NIL) 
	::dENJOYMENTSTARTDATE :=  WSAdvValue( oResponse,"_ENJOYMENTSTARTDATE","date",NIL,"Property dENJOYMENTSTARTDATE as s:date on SOAP Response not found.",NIL,"D",NIL,NIL) 
	::cNOTICEACCEPTANCE  :=  WSAdvValue( oResponse,"_NOTICEACCEPTANCE","string",NIL,"Property cNOTICEACCEPTANCE as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cNOTICETYPE        :=  WSAdvValue( oResponse,"_NOTICETYPE","string",NIL,"Property cNOTICETYPE as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::nPECUNIARYALLOWANCE :=  WSAdvValue( oResponse,"_PECUNIARYALLOWANCE","integer",NIL,"Property nPECUNIARYALLOWANCE as s:integer on SOAP Response not found.",NIL,"N",NIL,NIL) 
Return


