#INCLUDE "protheus.ch"
#INCLUDE "apwebsrv.ch"

/* ===============================================================================
WSDL Location    http://localhost:8059/ws/PMSREPORT.apw?WSDL
Gerado em        12/14/20 11:23:56
Observações      Código-Fonte gerado por ADVPL WSDL Client 1.120703
                 Alterações neste arquivo podem causar funcionamento incorreto
                 e serão perdidas caso o código-fonte seja gerado novamente.
=============================================================================== */

User Function _CCSVJPS ; Return  // "dummy" function - Internal Use 

/* -------------------------------------------------------------------------------
WSDL Service WSPMSREPORT
------------------------------------------------------------------------------- */

WSCLIENT WSPMSREPORT

	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD RESET
	WSMETHOD CLONE
	WSMETHOD GETGANTT
	WSMETHOD GETGANTTRES
	WSMETHOD GETGANTTTEAM
	WSMETHOD GETHEADER
	WSMETHOD GETHEADERPMS
	WSMETHOD GETMYRESOURCE
	WSMETHOD GETOCORRENCELIST
	WSMETHOD GETPROJECTLIST
	WSMETHOD GETPROJLISTBYCLIENT
	WSMETHOD GETRESOURCELIST
	WSMETHOD GETTASKLIST
	WSMETHOD GETTEAMLIST

	WSDATA   _URL                      AS String
	WSDATA   _HEADOUT                  AS Array of String
	WSDATA   _COOKIES                  AS Array of String
	WSDATA   cUSERCODE                 AS string
	WSDATA   cPROTHEUSUSERCODE         AS string
	WSDATA   cPROJECTCODE              AS string
	WSDATA   cWBSCODE                  AS string
	WSDATA   oWSGETGANTTRESULT         AS PMSREPORT_ARRAYOFGANTTTASKVIEW
	WSDATA   cRESOURCESCODES           AS string
	WSDATA   dDATEINITIAL              AS date
	WSDATA   dDATEFINAL                AS date
	WSDATA   nTASKSOPTION              AS integer
	WSDATA   oWSGETGANTTRESRESULT      AS PMSREPORT_ARRAYOFGANTTTASKVIEW
	WSDATA   cTEAMSCODES               AS string
	WSDATA   oWSGETGANTTTEAMRESULT     AS PMSREPORT_ARRAYOFGANTTTASKVIEW
	WSDATA   cHEADERTYPE               AS string
	WSDATA   oWSGETHEADERRESULT        AS PMSREPORT_ARRAYOFBRWHEADER
	WSDATA   oWSGETHEADERPMSRESULT     AS PMSREPORT_ARRAYOFBRWHEADERPMS
	WSDATA   oWSGETMYRESOURCERESULT    AS PMSREPORT_RESOURCEVIEW
	WSDATA   cOCORRENCEINITIAL         AS string
	WSDATA   cOCORRENCEFINAL           AS string
	WSDATA   nPAGELEN                  AS integer
	WSDATA   nPAGEFIRST                AS integer
	WSDATA   cQRYADD                   AS string
	WSDATA   nINDEXKEY                 AS integer
	WSDATA   oWSGETOCORRENCELISTRESULT AS PMSREPORT_ARRAYOFOCORRENCEVIEW
	WSDATA   cPROJECTINITIAL           AS string
	WSDATA   cPROJECTFINAL             AS string
	WSDATA   oWSGETPROJECTLISTRESULT   AS PMSREPORT_ARRAYOFPROJECTLISTVIEW
	WSDATA   cCLIENTINITIAL            AS string
	WSDATA   cCLIENTFINAL              AS string
	WSDATA   oWSGETPROJLISTBYCLIENTRESULT AS PMSREPORT_ARRAYOFPROJECTLISTVIEW
	WSDATA   cRESOURCEINITIAL          AS string
	WSDATA   cRESOURCEFINAL            AS string
	WSDATA   oWSGETRESOURCELISTRESULT  AS PMSREPORT_ARRAYOFRESOURCEVIEW
	WSDATA   oWSGETTASKLISTRESULT      AS PMSREPORT_ARRAYOFGANTTTASKVIEW
	WSDATA   cTEAMINITIAL              AS string
	WSDATA   cTEAMFINAL                AS string
	WSDATA   oWSGETTEAMLISTRESULT      AS PMSREPORT_ARRAYOFTEAMVIEW

ENDWSCLIENT

WSMETHOD NEW WSCLIENT WSPMSREPORT
::Init()
If !FindFunction("XMLCHILDEX")
	UserException("O Código-Fonte Client atual requer os executáveis do Protheus Build [7.00.191205P-20201009] ou superior. Atualize o Protheus ou gere o Código-Fonte novamente utilizando o Build atual.")
EndIf
Return Self

WSMETHOD INIT WSCLIENT WSPMSREPORT
	::oWSGETGANTTRESULT  := PMSREPORT_ARRAYOFGANTTTASKVIEW():New()
	::oWSGETGANTTRESRESULT := PMSREPORT_ARRAYOFGANTTTASKVIEW():New()
	::oWSGETGANTTTEAMRESULT := PMSREPORT_ARRAYOFGANTTTASKVIEW():New()
	::oWSGETHEADERRESULT := PMSREPORT_ARRAYOFBRWHEADER():New()
	::oWSGETHEADERPMSRESULT := PMSREPORT_ARRAYOFBRWHEADERPMS():New()
	::oWSGETMYRESOURCERESULT := PMSREPORT_RESOURCEVIEW():New()
	::oWSGETOCORRENCELISTRESULT := PMSREPORT_ARRAYOFOCORRENCEVIEW():New()
	::oWSGETPROJECTLISTRESULT := PMSREPORT_ARRAYOFPROJECTLISTVIEW():New()
	::oWSGETPROJLISTBYCLIENTRESULT := PMSREPORT_ARRAYOFPROJECTLISTVIEW():New()
	::oWSGETRESOURCELISTRESULT := PMSREPORT_ARRAYOFRESOURCEVIEW():New()
	::oWSGETTASKLISTRESULT := PMSREPORT_ARRAYOFGANTTTASKVIEW():New()
	::oWSGETTEAMLISTRESULT := PMSREPORT_ARRAYOFTEAMVIEW():New()
Return

WSMETHOD RESET WSCLIENT WSPMSREPORT
	::cUSERCODE          := NIL 
	::cPROTHEUSUSERCODE  := NIL 
	::cPROJECTCODE       := NIL 
	::cWBSCODE           := NIL 
	::oWSGETGANTTRESULT  := NIL 
	::cRESOURCESCODES    := NIL 
	::dDATEINITIAL       := NIL 
	::dDATEFINAL         := NIL 
	::nTASKSOPTION       := NIL 
	::oWSGETGANTTRESRESULT := NIL 
	::cTEAMSCODES        := NIL 
	::oWSGETGANTTTEAMRESULT := NIL 
	::cHEADERTYPE        := NIL 
	::oWSGETHEADERRESULT := NIL 
	::oWSGETHEADERPMSRESULT := NIL 
	::oWSGETMYRESOURCERESULT := NIL 
	::cOCORRENCEINITIAL  := NIL 
	::cOCORRENCEFINAL    := NIL 
	::nPAGELEN           := NIL 
	::nPAGEFIRST         := NIL 
	::cQRYADD            := NIL 
	::nINDEXKEY          := NIL 
	::oWSGETOCORRENCELISTRESULT := NIL 
	::cPROJECTINITIAL    := NIL 
	::cPROJECTFINAL      := NIL 
	::oWSGETPROJECTLISTRESULT := NIL 
	::cCLIENTINITIAL     := NIL 
	::cCLIENTFINAL       := NIL 
	::oWSGETPROJLISTBYCLIENTRESULT := NIL 
	::cRESOURCEINITIAL   := NIL 
	::cRESOURCEFINAL     := NIL 
	::oWSGETRESOURCELISTRESULT := NIL 
	::oWSGETTASKLISTRESULT := NIL 
	::cTEAMINITIAL       := NIL 
	::cTEAMFINAL         := NIL 
	::oWSGETTEAMLISTRESULT := NIL 
	::Init()
Return

WSMETHOD CLONE WSCLIENT WSPMSREPORT
Local oClone := WSPMSREPORT():New()
	oClone:_URL          := ::_URL 
	oClone:cUSERCODE     := ::cUSERCODE
	oClone:cPROTHEUSUSERCODE := ::cPROTHEUSUSERCODE
	oClone:cPROJECTCODE  := ::cPROJECTCODE
	oClone:cWBSCODE      := ::cWBSCODE
	oClone:oWSGETGANTTRESULT :=  IIF(::oWSGETGANTTRESULT = NIL , NIL ,::oWSGETGANTTRESULT:Clone() )
	oClone:cRESOURCESCODES := ::cRESOURCESCODES
	oClone:dDATEINITIAL  := ::dDATEINITIAL
	oClone:dDATEFINAL    := ::dDATEFINAL
	oClone:nTASKSOPTION  := ::nTASKSOPTION
	oClone:oWSGETGANTTRESRESULT :=  IIF(::oWSGETGANTTRESRESULT = NIL , NIL ,::oWSGETGANTTRESRESULT:Clone() )
	oClone:cTEAMSCODES   := ::cTEAMSCODES
	oClone:oWSGETGANTTTEAMRESULT :=  IIF(::oWSGETGANTTTEAMRESULT = NIL , NIL ,::oWSGETGANTTTEAMRESULT:Clone() )
	oClone:cHEADERTYPE   := ::cHEADERTYPE
	oClone:oWSGETHEADERRESULT :=  IIF(::oWSGETHEADERRESULT = NIL , NIL ,::oWSGETHEADERRESULT:Clone() )
	oClone:oWSGETHEADERPMSRESULT :=  IIF(::oWSGETHEADERPMSRESULT = NIL , NIL ,::oWSGETHEADERPMSRESULT:Clone() )
	oClone:oWSGETMYRESOURCERESULT :=  IIF(::oWSGETMYRESOURCERESULT = NIL , NIL ,::oWSGETMYRESOURCERESULT:Clone() )
	oClone:cOCORRENCEINITIAL := ::cOCORRENCEINITIAL
	oClone:cOCORRENCEFINAL := ::cOCORRENCEFINAL
	oClone:nPAGELEN      := ::nPAGELEN
	oClone:nPAGEFIRST    := ::nPAGEFIRST
	oClone:cQRYADD       := ::cQRYADD
	oClone:nINDEXKEY     := ::nINDEXKEY
	oClone:oWSGETOCORRENCELISTRESULT :=  IIF(::oWSGETOCORRENCELISTRESULT = NIL , NIL ,::oWSGETOCORRENCELISTRESULT:Clone() )
	oClone:cPROJECTINITIAL := ::cPROJECTINITIAL
	oClone:cPROJECTFINAL := ::cPROJECTFINAL
	oClone:oWSGETPROJECTLISTRESULT :=  IIF(::oWSGETPROJECTLISTRESULT = NIL , NIL ,::oWSGETPROJECTLISTRESULT:Clone() )
	oClone:cCLIENTINITIAL := ::cCLIENTINITIAL
	oClone:cCLIENTFINAL  := ::cCLIENTFINAL
	oClone:oWSGETPROJLISTBYCLIENTRESULT :=  IIF(::oWSGETPROJLISTBYCLIENTRESULT = NIL , NIL ,::oWSGETPROJLISTBYCLIENTRESULT:Clone() )
	oClone:cRESOURCEINITIAL := ::cRESOURCEINITIAL
	oClone:cRESOURCEFINAL := ::cRESOURCEFINAL
	oClone:oWSGETRESOURCELISTRESULT :=  IIF(::oWSGETRESOURCELISTRESULT = NIL , NIL ,::oWSGETRESOURCELISTRESULT:Clone() )
	oClone:oWSGETTASKLISTRESULT :=  IIF(::oWSGETTASKLISTRESULT = NIL , NIL ,::oWSGETTASKLISTRESULT:Clone() )
	oClone:cTEAMINITIAL  := ::cTEAMINITIAL
	oClone:cTEAMFINAL    := ::cTEAMFINAL
	oClone:oWSGETTEAMLISTRESULT :=  IIF(::oWSGETTEAMLISTRESULT = NIL , NIL ,::oWSGETTEAMLISTRESULT:Clone() )
Return oClone

// WSDL Method GETGANTT of Service WSPMSREPORT

WSMETHOD GETGANTT WSSEND cUSERCODE,cPROTHEUSUSERCODE,cPROJECTCODE,cWBSCODE WSRECEIVE oWSGETGANTTRESULT WSCLIENT WSPMSREPORT
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<GETGANTT xmlns="http://localhost:8059/">'
cSoap += WSSoapValue("USERCODE", ::cUSERCODE, cUSERCODE , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("PROTHEUSUSERCODE", ::cPROTHEUSUSERCODE, cPROTHEUSUSERCODE , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("PROJECTCODE", ::cPROJECTCODE, cPROJECTCODE , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("WBSCODE", ::cWBSCODE, cWBSCODE , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += "</GETGANTT>"

oXmlRet := SvcSoapCall(Self,cSoap,; 
	"http://localhost:8059/GETGANTT",; 
	"DOCUMENT","http://localhost:8059/",,"1.031217",; 
	"http://localhost:8059/ws/PMSREPORT.apw")

::Init()
::oWSGETGANTTRESULT:SoapRecv( WSAdvValue( oXmlRet,"_GETGANTTRESPONSE:_GETGANTTRESULT","ARRAYOFGANTTTASKVIEW",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.

// WSDL Method GETGANTTRES of Service WSPMSREPORT

WSMETHOD GETGANTTRES WSSEND cUSERCODE,cPROTHEUSUSERCODE,cRESOURCESCODES,dDATEINITIAL,dDATEFINAL,nTASKSOPTION WSRECEIVE oWSGETGANTTRESRESULT WSCLIENT WSPMSREPORT
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<GETGANTTRES xmlns="http://localhost:8059/">'
cSoap += WSSoapValue("USERCODE", ::cUSERCODE, cUSERCODE , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("PROTHEUSUSERCODE", ::cPROTHEUSUSERCODE, cPROTHEUSUSERCODE , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("RESOURCESCODES", ::cRESOURCESCODES, cRESOURCESCODES , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("DATEINITIAL", ::dDATEINITIAL, dDATEINITIAL , "date", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("DATEFINAL", ::dDATEFINAL, dDATEFINAL , "date", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("TASKSOPTION", ::nTASKSOPTION, nTASKSOPTION , "integer", .F. , .F., 0 , NIL, .F.,.F.) 
cSoap += "</GETGANTTRES>"

oXmlRet := SvcSoapCall(Self,cSoap,; 
	"http://localhost:8059/GETGANTTRES",; 
	"DOCUMENT","http://localhost:8059/",,"1.031217",; 
	"http://localhost:8059/ws/PMSREPORT.apw")

::Init()
::oWSGETGANTTRESRESULT:SoapRecv( WSAdvValue( oXmlRet,"_GETGANTTRESRESPONSE:_GETGANTTRESRESULT","ARRAYOFGANTTTASKVIEW",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.

// WSDL Method GETGANTTTEAM of Service WSPMSREPORT

WSMETHOD GETGANTTTEAM WSSEND cUSERCODE,cPROTHEUSUSERCODE,cTEAMSCODES,dDATEINITIAL,dDATEFINAL,nTASKSOPTION WSRECEIVE oWSGETGANTTTEAMRESULT WSCLIENT WSPMSREPORT
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<GETGANTTTEAM xmlns="http://localhost:8059/">'
cSoap += WSSoapValue("USERCODE", ::cUSERCODE, cUSERCODE , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("PROTHEUSUSERCODE", ::cPROTHEUSUSERCODE, cPROTHEUSUSERCODE , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("TEAMSCODES", ::cTEAMSCODES, cTEAMSCODES , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("DATEINITIAL", ::dDATEINITIAL, dDATEINITIAL , "date", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("DATEFINAL", ::dDATEFINAL, dDATEFINAL , "date", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("TASKSOPTION", ::nTASKSOPTION, nTASKSOPTION , "integer", .F. , .F., 0 , NIL, .F.,.F.) 
cSoap += "</GETGANTTTEAM>"

oXmlRet := SvcSoapCall(Self,cSoap,; 
	"http://localhost:8059/GETGANTTTEAM",; 
	"DOCUMENT","http://localhost:8059/",,"1.031217",; 
	"http://localhost:8059/ws/PMSREPORT.apw")

::Init()
::oWSGETGANTTTEAMRESULT:SoapRecv( WSAdvValue( oXmlRet,"_GETGANTTTEAMRESPONSE:_GETGANTTTEAMRESULT","ARRAYOFGANTTTASKVIEW",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.

// WSDL Method GETHEADER of Service WSPMSREPORT

WSMETHOD GETHEADER WSSEND cHEADERTYPE WSRECEIVE oWSGETHEADERRESULT WSCLIENT WSPMSREPORT
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<GETHEADER xmlns="http://localhost:8059/">'
cSoap += WSSoapValue("HEADERTYPE", ::cHEADERTYPE, cHEADERTYPE , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += "</GETHEADER>"

oXmlRet := SvcSoapCall(Self,cSoap,; 
	"http://localhost:8059/GETHEADER",; 
	"DOCUMENT","http://localhost:8059/",,"1.031217",; 
	"http://localhost:8059/ws/PMSREPORT.apw")

::Init()
::oWSGETHEADERRESULT:SoapRecv( WSAdvValue( oXmlRet,"_GETHEADERRESPONSE:_GETHEADERRESULT","ARRAYOFBRWHEADER",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.

// WSDL Method GETHEADERPMS of Service WSPMSREPORT

WSMETHOD GETHEADERPMS WSSEND cHEADERTYPE WSRECEIVE oWSGETHEADERPMSRESULT WSCLIENT WSPMSREPORT
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<GETHEADERPMS xmlns="http://localhost:8059/">'
cSoap += WSSoapValue("HEADERTYPE", ::cHEADERTYPE, cHEADERTYPE , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += "</GETHEADERPMS>"

oXmlRet := SvcSoapCall(Self,cSoap,; 
	"http://localhost:8059/GETHEADERPMS",; 
	"DOCUMENT","http://localhost:8059/",,"1.031217",; 
	"http://localhost:8059/ws/PMSREPORT.apw")

::Init()
::oWSGETHEADERPMSRESULT:SoapRecv( WSAdvValue( oXmlRet,"_GETHEADERPMSRESPONSE:_GETHEADERPMSRESULT","ARRAYOFBRWHEADERPMS",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.

// WSDL Method GETMYRESOURCE of Service WSPMSREPORT

WSMETHOD GETMYRESOURCE WSSEND cUSERCODE,cPROTHEUSUSERCODE WSRECEIVE oWSGETMYRESOURCERESULT WSCLIENT WSPMSREPORT
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<GETMYRESOURCE xmlns="http://localhost:8059/">'
cSoap += WSSoapValue("USERCODE", ::cUSERCODE, cUSERCODE , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("PROTHEUSUSERCODE", ::cPROTHEUSUSERCODE, cPROTHEUSUSERCODE , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += "</GETMYRESOURCE>"

oXmlRet := SvcSoapCall(Self,cSoap,; 
	"http://localhost:8059/GETMYRESOURCE",; 
	"DOCUMENT","http://localhost:8059/",,"1.031217",; 
	"http://localhost:8059/ws/PMSREPORT.apw")

::Init()
::oWSGETMYRESOURCERESULT:SoapRecv( WSAdvValue( oXmlRet,"_GETMYRESOURCERESPONSE:_GETMYRESOURCERESULT","RESOURCEVIEW",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.

// WSDL Method GETOCORRENCELIST of Service WSPMSREPORT

WSMETHOD GETOCORRENCELIST WSSEND cUSERCODE,cPROTHEUSUSERCODE,cOCORRENCEINITIAL,cOCORRENCEFINAL,nPAGELEN,nPAGEFIRST,cQRYADD,nINDEXKEY WSRECEIVE oWSGETOCORRENCELISTRESULT WSCLIENT WSPMSREPORT
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<GETOCORRENCELIST xmlns="http://localhost:8059/">'
cSoap += WSSoapValue("USERCODE", ::cUSERCODE, cUSERCODE , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("PROTHEUSUSERCODE", ::cPROTHEUSUSERCODE, cPROTHEUSUSERCODE , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("OCORRENCEINITIAL", ::cOCORRENCEINITIAL, cOCORRENCEINITIAL , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("OCORRENCEFINAL", ::cOCORRENCEFINAL, cOCORRENCEFINAL , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("PAGELEN", ::nPAGELEN, nPAGELEN , "integer", .F. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("PAGEFIRST", ::nPAGEFIRST, nPAGEFIRST , "integer", .F. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("QRYADD", ::cQRYADD, cQRYADD , "string", .F. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("INDEXKEY", ::nINDEXKEY, nINDEXKEY , "integer", .F. , .F., 0 , NIL, .F.,.F.) 
cSoap += "</GETOCORRENCELIST>"

oXmlRet := SvcSoapCall(Self,cSoap,; 
	"http://localhost:8059/GETOCORRENCELIST",; 
	"DOCUMENT","http://localhost:8059/",,"1.031217",; 
	"http://localhost:8059/ws/PMSREPORT.apw")

::Init()
::oWSGETOCORRENCELISTRESULT:SoapRecv( WSAdvValue( oXmlRet,"_GETOCORRENCELISTRESPONSE:_GETOCORRENCELISTRESULT","ARRAYOFOCORRENCEVIEW",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.

// WSDL Method GETPROJECTLIST of Service WSPMSREPORT

WSMETHOD GETPROJECTLIST WSSEND cUSERCODE,cPROTHEUSUSERCODE,dDATEINITIAL,dDATEFINAL,cPROJECTINITIAL,cPROJECTFINAL,nPAGELEN,nPAGEFIRST,cQRYADD,nINDEXKEY WSRECEIVE oWSGETPROJECTLISTRESULT WSCLIENT WSPMSREPORT
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<GETPROJECTLIST xmlns="http://localhost:8059/">'
cSoap += WSSoapValue("USERCODE", ::cUSERCODE, cUSERCODE , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("PROTHEUSUSERCODE", ::cPROTHEUSUSERCODE, cPROTHEUSUSERCODE , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("DATEINITIAL", ::dDATEINITIAL, dDATEINITIAL , "date", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("DATEFINAL", ::dDATEFINAL, dDATEFINAL , "date", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("PROJECTINITIAL", ::cPROJECTINITIAL, cPROJECTINITIAL , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("PROJECTFINAL", ::cPROJECTFINAL, cPROJECTFINAL , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("PAGELEN", ::nPAGELEN, nPAGELEN , "integer", .F. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("PAGEFIRST", ::nPAGEFIRST, nPAGEFIRST , "integer", .F. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("QRYADD", ::cQRYADD, cQRYADD , "string", .F. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("INDEXKEY", ::nINDEXKEY, nINDEXKEY , "integer", .F. , .F., 0 , NIL, .F.,.F.) 
cSoap += "</GETPROJECTLIST>"

oXmlRet := SvcSoapCall(Self,cSoap,; 
	"http://localhost:8059/GETPROJECTLIST",; 
	"DOCUMENT","http://localhost:8059/",,"1.031217",; 
	"http://localhost:8059/ws/PMSREPORT.apw")

::Init()
::oWSGETPROJECTLISTRESULT:SoapRecv( WSAdvValue( oXmlRet,"_GETPROJECTLISTRESPONSE:_GETPROJECTLISTRESULT","ARRAYOFPROJECTLISTVIEW",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.

// WSDL Method GETPROJLISTBYCLIENT of Service WSPMSREPORT

WSMETHOD GETPROJLISTBYCLIENT WSSEND cUSERCODE,cPROTHEUSUSERCODE,dDATEINITIAL,dDATEFINAL,cPROJECTINITIAL,cPROJECTFINAL,cCLIENTINITIAL,cCLIENTFINAL,nPAGELEN,nPAGEFIRST,cQRYADD,nINDEXKEY WSRECEIVE oWSGETPROJLISTBYCLIENTRESULT WSCLIENT WSPMSREPORT
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<GETPROJLISTBYCLIENT xmlns="http://localhost:8059/">'
cSoap += WSSoapValue("USERCODE", ::cUSERCODE, cUSERCODE , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("PROTHEUSUSERCODE", ::cPROTHEUSUSERCODE, cPROTHEUSUSERCODE , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("DATEINITIAL", ::dDATEINITIAL, dDATEINITIAL , "date", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("DATEFINAL", ::dDATEFINAL, dDATEFINAL , "date", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("PROJECTINITIAL", ::cPROJECTINITIAL, cPROJECTINITIAL , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("PROJECTFINAL", ::cPROJECTFINAL, cPROJECTFINAL , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("CLIENTINITIAL", ::cCLIENTINITIAL, cCLIENTINITIAL , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("CLIENTFINAL", ::cCLIENTFINAL, cCLIENTFINAL , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("PAGELEN", ::nPAGELEN, nPAGELEN , "integer", .F. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("PAGEFIRST", ::nPAGEFIRST, nPAGEFIRST , "integer", .F. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("QRYADD", ::cQRYADD, cQRYADD , "string", .F. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("INDEXKEY", ::nINDEXKEY, nINDEXKEY , "integer", .F. , .F., 0 , NIL, .F.,.F.) 
cSoap += "</GETPROJLISTBYCLIENT>"

oXmlRet := SvcSoapCall(Self,cSoap,; 
	"http://localhost:8059/GETPROJLISTBYCLIENT",; 
	"DOCUMENT","http://localhost:8059/",,"1.031217",; 
	"http://localhost:8059/ws/PMSREPORT.apw")

::Init()
::oWSGETPROJLISTBYCLIENTRESULT:SoapRecv( WSAdvValue( oXmlRet,"_GETPROJLISTBYCLIENTRESPONSE:_GETPROJLISTBYCLIENTRESULT","ARRAYOFPROJECTLISTVIEW",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.

// WSDL Method GETRESOURCELIST of Service WSPMSREPORT

WSMETHOD GETRESOURCELIST WSSEND cUSERCODE,cPROTHEUSUSERCODE,cRESOURCEINITIAL,cRESOURCEFINAL,nPAGELEN,nPAGEFIRST,cQRYADD,nINDEXKEY WSRECEIVE oWSGETRESOURCELISTRESULT WSCLIENT WSPMSREPORT
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<GETRESOURCELIST xmlns="http://localhost:8059/">'
cSoap += WSSoapValue("USERCODE", ::cUSERCODE, cUSERCODE , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("PROTHEUSUSERCODE", ::cPROTHEUSUSERCODE, cPROTHEUSUSERCODE , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("RESOURCEINITIAL", ::cRESOURCEINITIAL, cRESOURCEINITIAL , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("RESOURCEFINAL", ::cRESOURCEFINAL, cRESOURCEFINAL , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("PAGELEN", ::nPAGELEN, nPAGELEN , "integer", .F. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("PAGEFIRST", ::nPAGEFIRST, nPAGEFIRST , "integer", .F. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("QRYADD", ::cQRYADD, cQRYADD , "string", .F. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("INDEXKEY", ::nINDEXKEY, nINDEXKEY , "integer", .F. , .F., 0 , NIL, .F.,.F.) 
cSoap += "</GETRESOURCELIST>"

oXmlRet := SvcSoapCall(Self,cSoap,; 
	"http://localhost:8059/GETRESOURCELIST",; 
	"DOCUMENT","http://localhost:8059/",,"1.031217",; 
	"http://localhost:8059/ws/PMSREPORT.apw")

::Init()
::oWSGETRESOURCELISTRESULT:SoapRecv( WSAdvValue( oXmlRet,"_GETRESOURCELISTRESPONSE:_GETRESOURCELISTRESULT","ARRAYOFRESOURCEVIEW",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.

// WSDL Method GETTASKLIST of Service WSPMSREPORT

WSMETHOD GETTASKLIST WSSEND cUSERCODE,cPROTHEUSUSERCODE,cPROJECTCODE,nPAGELEN,nPAGEFIRST,cQRYADD,nINDEXKEY WSRECEIVE oWSGETTASKLISTRESULT WSCLIENT WSPMSREPORT
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<GETTASKLIST xmlns="http://localhost:8059/">'
cSoap += WSSoapValue("USERCODE", ::cUSERCODE, cUSERCODE , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("PROTHEUSUSERCODE", ::cPROTHEUSUSERCODE, cPROTHEUSUSERCODE , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("PROJECTCODE", ::cPROJECTCODE, cPROJECTCODE , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("PAGELEN", ::nPAGELEN, nPAGELEN , "integer", .F. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("PAGEFIRST", ::nPAGEFIRST, nPAGEFIRST , "integer", .F. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("QRYADD", ::cQRYADD, cQRYADD , "string", .F. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("INDEXKEY", ::nINDEXKEY, nINDEXKEY , "integer", .F. , .F., 0 , NIL, .F.,.F.) 
cSoap += "</GETTASKLIST>"

oXmlRet := SvcSoapCall(Self,cSoap,; 
	"http://localhost:8059/GETTASKLIST",; 
	"DOCUMENT","http://localhost:8059/",,"1.031217",; 
	"http://localhost:8059/ws/PMSREPORT.apw")

::Init()
::oWSGETTASKLISTRESULT:SoapRecv( WSAdvValue( oXmlRet,"_GETTASKLISTRESPONSE:_GETTASKLISTRESULT","ARRAYOFGANTTTASKVIEW",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.

// WSDL Method GETTEAMLIST of Service WSPMSREPORT

WSMETHOD GETTEAMLIST WSSEND cUSERCODE,cPROTHEUSUSERCODE,cTEAMINITIAL,cTEAMFINAL,nPAGELEN,nPAGEFIRST,cQRYADD,nINDEXKEY WSRECEIVE oWSGETTEAMLISTRESULT WSCLIENT WSPMSREPORT
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<GETTEAMLIST xmlns="http://localhost:8059/">'
cSoap += WSSoapValue("USERCODE", ::cUSERCODE, cUSERCODE , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("PROTHEUSUSERCODE", ::cPROTHEUSUSERCODE, cPROTHEUSUSERCODE , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("TEAMINITIAL", ::cTEAMINITIAL, cTEAMINITIAL , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("TEAMFINAL", ::cTEAMFINAL, cTEAMFINAL , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("PAGELEN", ::nPAGELEN, nPAGELEN , "integer", .F. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("PAGEFIRST", ::nPAGEFIRST, nPAGEFIRST , "integer", .F. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("QRYADD", ::cQRYADD, cQRYADD , "string", .F. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("INDEXKEY", ::nINDEXKEY, nINDEXKEY , "integer", .F. , .F., 0 , NIL, .F.,.F.) 
cSoap += "</GETTEAMLIST>"

oXmlRet := SvcSoapCall(Self,cSoap,; 
	"http://localhost:8059/GETTEAMLIST",; 
	"DOCUMENT","http://localhost:8059/",,"1.031217",; 
	"http://localhost:8059/ws/PMSREPORT.apw")

::Init()
::oWSGETTEAMLISTRESULT:SoapRecv( WSAdvValue( oXmlRet,"_GETTEAMLISTRESPONSE:_GETTEAMLISTRESULT","ARRAYOFTEAMVIEW",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.


// WSDL Data Structure ARRAYOFGANTTTASKVIEW

WSSTRUCT PMSREPORT_ARRAYOFGANTTTASKVIEW
	WSDATA   oWSGANTTTASKVIEW          AS PMSREPORT_GANTTTASKVIEW OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PMSREPORT_ARRAYOFGANTTTASKVIEW
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PMSREPORT_ARRAYOFGANTTTASKVIEW
	::oWSGANTTTASKVIEW     := {} // Array Of  PMSREPORT_GANTTTASKVIEW():New()
Return

WSMETHOD CLONE WSCLIENT PMSREPORT_ARRAYOFGANTTTASKVIEW
	Local oClone := PMSREPORT_ARRAYOFGANTTTASKVIEW():NEW()
	oClone:oWSGANTTTASKVIEW := NIL
	If ::oWSGANTTTASKVIEW <> NIL 
		oClone:oWSGANTTTASKVIEW := {}
		aEval( ::oWSGANTTTASKVIEW , { |x| aadd( oClone:oWSGANTTTASKVIEW , x:Clone() ) } )
	Endif 
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PMSREPORT_ARRAYOFGANTTTASKVIEW
	Local nRElem1, oNodes1, nTElem1
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNodes1 :=  WSAdvValue( oResponse,"_GANTTTASKVIEW","GANTTTASKVIEW",{},NIL,.T.,"O",NIL,NIL) 
	nTElem1 := len(oNodes1)
	For nRElem1 := 1 to nTElem1 
		If !WSIsNilNode( oNodes1[nRElem1] )
			aadd(::oWSGANTTTASKVIEW , PMSREPORT_GANTTTASKVIEW():New() )
			::oWSGANTTTASKVIEW[len(::oWSGANTTTASKVIEW)]:SoapRecv(oNodes1[nRElem1])
		Endif
	Next
Return

// WSDL Data Structure ARRAYOFBRWHEADER

WSSTRUCT PMSREPORT_ARRAYOFBRWHEADER
	WSDATA   oWSBRWHEADER              AS PMSREPORT_BRWHEADER OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PMSREPORT_ARRAYOFBRWHEADER
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PMSREPORT_ARRAYOFBRWHEADER
	::oWSBRWHEADER         := {} // Array Of  PMSREPORT_BRWHEADER():New()
Return

WSMETHOD CLONE WSCLIENT PMSREPORT_ARRAYOFBRWHEADER
	Local oClone := PMSREPORT_ARRAYOFBRWHEADER():NEW()
	oClone:oWSBRWHEADER := NIL
	If ::oWSBRWHEADER <> NIL 
		oClone:oWSBRWHEADER := {}
		aEval( ::oWSBRWHEADER , { |x| aadd( oClone:oWSBRWHEADER , x:Clone() ) } )
	Endif 
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PMSREPORT_ARRAYOFBRWHEADER
	Local nRElem1, oNodes1, nTElem1
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNodes1 :=  WSAdvValue( oResponse,"_BRWHEADER","BRWHEADER",{},NIL,.T.,"O",NIL,NIL) 
	nTElem1 := len(oNodes1)
	For nRElem1 := 1 to nTElem1 
		If !WSIsNilNode( oNodes1[nRElem1] )
			aadd(::oWSBRWHEADER , PMSREPORT_BRWHEADER():New() )
			::oWSBRWHEADER[len(::oWSBRWHEADER)]:SoapRecv(oNodes1[nRElem1])
		Endif
	Next
Return

// WSDL Data Structure ARRAYOFBRWHEADERPMS

WSSTRUCT PMSREPORT_ARRAYOFBRWHEADERPMS
	WSDATA   oWSBRWHEADERPMS           AS PMSREPORT_BRWHEADERPMS OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PMSREPORT_ARRAYOFBRWHEADERPMS
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PMSREPORT_ARRAYOFBRWHEADERPMS
	::oWSBRWHEADERPMS      := {} // Array Of  PMSREPORT_BRWHEADERPMS():New()
Return

WSMETHOD CLONE WSCLIENT PMSREPORT_ARRAYOFBRWHEADERPMS
	Local oClone := PMSREPORT_ARRAYOFBRWHEADERPMS():NEW()
	oClone:oWSBRWHEADERPMS := NIL
	If ::oWSBRWHEADERPMS <> NIL 
		oClone:oWSBRWHEADERPMS := {}
		aEval( ::oWSBRWHEADERPMS , { |x| aadd( oClone:oWSBRWHEADERPMS , x:Clone() ) } )
	Endif 
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PMSREPORT_ARRAYOFBRWHEADERPMS
	Local nRElem1, oNodes1, nTElem1
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNodes1 :=  WSAdvValue( oResponse,"_BRWHEADERPMS","BRWHEADERPMS",{},NIL,.T.,"O",NIL,NIL) 
	nTElem1 := len(oNodes1)
	For nRElem1 := 1 to nTElem1 
		If !WSIsNilNode( oNodes1[nRElem1] )
			aadd(::oWSBRWHEADERPMS , PMSREPORT_BRWHEADERPMS():New() )
			::oWSBRWHEADERPMS[len(::oWSBRWHEADERPMS)]:SoapRecv(oNodes1[nRElem1])
		Endif
	Next
Return

// WSDL Data Structure RESOURCEVIEW

WSSTRUCT PMSREPORT_RESOURCEVIEW
	WSDATA   cCALENDAR                 AS string OPTIONAL
	WSDATA   cPRODUCTCODE              AS string OPTIONAL
	WSDATA   cRESOURCECODE             AS string OPTIONAL
	WSDATA   cRESOURCENAME             AS string OPTIONAL
	WSDATA   cTEAMCODE                 AS string OPTIONAL
	WSDATA   cTEAMNAME                 AS string OPTIONAL
	WSDATA   oWSUSERFIELDS             AS PMSREPORT_ARRAYOFUSERFIELD OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PMSREPORT_RESOURCEVIEW
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PMSREPORT_RESOURCEVIEW
Return

WSMETHOD CLONE WSCLIENT PMSREPORT_RESOURCEVIEW
	Local oClone := PMSREPORT_RESOURCEVIEW():NEW()
	oClone:cCALENDAR            := ::cCALENDAR
	oClone:cPRODUCTCODE         := ::cPRODUCTCODE
	oClone:cRESOURCECODE        := ::cRESOURCECODE
	oClone:cRESOURCENAME        := ::cRESOURCENAME
	oClone:cTEAMCODE            := ::cTEAMCODE
	oClone:cTEAMNAME            := ::cTEAMNAME
	oClone:oWSUSERFIELDS        := IIF(::oWSUSERFIELDS = NIL , NIL , ::oWSUSERFIELDS:Clone() )
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PMSREPORT_RESOURCEVIEW
	Local oNode7
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::cCALENDAR          :=  WSAdvValue( oResponse,"_CALENDAR","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cPRODUCTCODE       :=  WSAdvValue( oResponse,"_PRODUCTCODE","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cRESOURCECODE      :=  WSAdvValue( oResponse,"_RESOURCECODE","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cRESOURCENAME      :=  WSAdvValue( oResponse,"_RESOURCENAME","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cTEAMCODE          :=  WSAdvValue( oResponse,"_TEAMCODE","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cTEAMNAME          :=  WSAdvValue( oResponse,"_TEAMNAME","string",NIL,NIL,NIL,"S",NIL,NIL) 
	oNode7 :=  WSAdvValue( oResponse,"_USERFIELDS","ARRAYOFUSERFIELD",NIL,NIL,NIL,"O",NIL,NIL) 
	If oNode7 != NIL
		::oWSUSERFIELDS := PMSREPORT_ARRAYOFUSERFIELD():New()
		::oWSUSERFIELDS:SoapRecv(oNode7)
	EndIf
Return

// WSDL Data Structure ARRAYOFOCORRENCEVIEW

WSSTRUCT PMSREPORT_ARRAYOFOCORRENCEVIEW
	WSDATA   oWSOCORRENCEVIEW          AS PMSREPORT_OCORRENCEVIEW OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PMSREPORT_ARRAYOFOCORRENCEVIEW
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PMSREPORT_ARRAYOFOCORRENCEVIEW
	::oWSOCORRENCEVIEW     := {} // Array Of  PMSREPORT_OCORRENCEVIEW():New()
Return

WSMETHOD CLONE WSCLIENT PMSREPORT_ARRAYOFOCORRENCEVIEW
	Local oClone := PMSREPORT_ARRAYOFOCORRENCEVIEW():NEW()
	oClone:oWSOCORRENCEVIEW := NIL
	If ::oWSOCORRENCEVIEW <> NIL 
		oClone:oWSOCORRENCEVIEW := {}
		aEval( ::oWSOCORRENCEVIEW , { |x| aadd( oClone:oWSOCORRENCEVIEW , x:Clone() ) } )
	Endif 
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PMSREPORT_ARRAYOFOCORRENCEVIEW
	Local nRElem1, oNodes1, nTElem1
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNodes1 :=  WSAdvValue( oResponse,"_OCORRENCEVIEW","OCORRENCEVIEW",{},NIL,.T.,"O",NIL,NIL) 
	nTElem1 := len(oNodes1)
	For nRElem1 := 1 to nTElem1 
		If !WSIsNilNode( oNodes1[nRElem1] )
			aadd(::oWSOCORRENCEVIEW , PMSREPORT_OCORRENCEVIEW():New() )
			::oWSOCORRENCEVIEW[len(::oWSOCORRENCEVIEW)]:SoapRecv(oNodes1[nRElem1])
		Endif
	Next
Return

// WSDL Data Structure ARRAYOFPROJECTLISTVIEW

WSSTRUCT PMSREPORT_ARRAYOFPROJECTLISTVIEW
	WSDATA   oWSPROJECTLISTVIEW        AS PMSREPORT_PROJECTLISTVIEW OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PMSREPORT_ARRAYOFPROJECTLISTVIEW
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PMSREPORT_ARRAYOFPROJECTLISTVIEW
	::oWSPROJECTLISTVIEW   := {} // Array Of  PMSREPORT_PROJECTLISTVIEW():New()
Return

WSMETHOD CLONE WSCLIENT PMSREPORT_ARRAYOFPROJECTLISTVIEW
	Local oClone := PMSREPORT_ARRAYOFPROJECTLISTVIEW():NEW()
	oClone:oWSPROJECTLISTVIEW := NIL
	If ::oWSPROJECTLISTVIEW <> NIL 
		oClone:oWSPROJECTLISTVIEW := {}
		aEval( ::oWSPROJECTLISTVIEW , { |x| aadd( oClone:oWSPROJECTLISTVIEW , x:Clone() ) } )
	Endif 
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PMSREPORT_ARRAYOFPROJECTLISTVIEW
	Local nRElem1, oNodes1, nTElem1
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNodes1 :=  WSAdvValue( oResponse,"_PROJECTLISTVIEW","PROJECTLISTVIEW",{},NIL,.T.,"O",NIL,NIL) 
	nTElem1 := len(oNodes1)
	For nRElem1 := 1 to nTElem1 
		If !WSIsNilNode( oNodes1[nRElem1] )
			aadd(::oWSPROJECTLISTVIEW , PMSREPORT_PROJECTLISTVIEW():New() )
			::oWSPROJECTLISTVIEW[len(::oWSPROJECTLISTVIEW)]:SoapRecv(oNodes1[nRElem1])
		Endif
	Next
Return

// WSDL Data Structure ARRAYOFRESOURCEVIEW

WSSTRUCT PMSREPORT_ARRAYOFRESOURCEVIEW
	WSDATA   oWSRESOURCEVIEW           AS PMSREPORT_RESOURCEVIEW OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PMSREPORT_ARRAYOFRESOURCEVIEW
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PMSREPORT_ARRAYOFRESOURCEVIEW
	::oWSRESOURCEVIEW      := {} // Array Of  PMSREPORT_RESOURCEVIEW():New()
Return

WSMETHOD CLONE WSCLIENT PMSREPORT_ARRAYOFRESOURCEVIEW
	Local oClone := PMSREPORT_ARRAYOFRESOURCEVIEW():NEW()
	oClone:oWSRESOURCEVIEW := NIL
	If ::oWSRESOURCEVIEW <> NIL 
		oClone:oWSRESOURCEVIEW := {}
		aEval( ::oWSRESOURCEVIEW , { |x| aadd( oClone:oWSRESOURCEVIEW , x:Clone() ) } )
	Endif 
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PMSREPORT_ARRAYOFRESOURCEVIEW
	Local nRElem1, oNodes1, nTElem1
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNodes1 :=  WSAdvValue( oResponse,"_RESOURCEVIEW","RESOURCEVIEW",{},NIL,.T.,"O",NIL,NIL) 
	nTElem1 := len(oNodes1)
	For nRElem1 := 1 to nTElem1 
		If !WSIsNilNode( oNodes1[nRElem1] )
			aadd(::oWSRESOURCEVIEW , PMSREPORT_RESOURCEVIEW():New() )
			::oWSRESOURCEVIEW[len(::oWSRESOURCEVIEW)]:SoapRecv(oNodes1[nRElem1])
		Endif
	Next
Return

// WSDL Data Structure ARRAYOFTEAMVIEW

WSSTRUCT PMSREPORT_ARRAYOFTEAMVIEW
	WSDATA   oWSTEAMVIEW               AS PMSREPORT_TEAMVIEW OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PMSREPORT_ARRAYOFTEAMVIEW
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PMSREPORT_ARRAYOFTEAMVIEW
	::oWSTEAMVIEW          := {} // Array Of  PMSREPORT_TEAMVIEW():New()
Return

WSMETHOD CLONE WSCLIENT PMSREPORT_ARRAYOFTEAMVIEW
	Local oClone := PMSREPORT_ARRAYOFTEAMVIEW():NEW()
	oClone:oWSTEAMVIEW := NIL
	If ::oWSTEAMVIEW <> NIL 
		oClone:oWSTEAMVIEW := {}
		aEval( ::oWSTEAMVIEW , { |x| aadd( oClone:oWSTEAMVIEW , x:Clone() ) } )
	Endif 
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PMSREPORT_ARRAYOFTEAMVIEW
	Local nRElem1, oNodes1, nTElem1
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNodes1 :=  WSAdvValue( oResponse,"_TEAMVIEW","TEAMVIEW",{},NIL,.T.,"O",NIL,NIL) 
	nTElem1 := len(oNodes1)
	For nRElem1 := 1 to nTElem1 
		If !WSIsNilNode( oNodes1[nRElem1] )
			aadd(::oWSTEAMVIEW , PMSREPORT_TEAMVIEW():New() )
			::oWSTEAMVIEW[len(::oWSTEAMVIEW)]:SoapRecv(oNodes1[nRElem1])
		Endif
	Next
Return

// WSDL Data Structure GANTTTASKVIEW

WSSTRUCT PMSREPORT_GANTTTASKVIEW
	WSDATA   cBITMAP                   AS string OPTIONAL
	WSDATA   nCPM                      AS integer OPTIONAL
	WSDATA   nDBRECORD                 AS integer OPTIONAL
	WSDATA   dESTIMATEDFINALDATE       AS date
	WSDATA   cESTIMATEDFINALHOUR       AS string OPTIONAL
	WSDATA   dESTIMATEDINITIALDATE     AS date
	WSDATA   cESTIMATEDINITIALHOUR     AS string
	WSDATA   dEXECUTIONFINALDATE       AS date OPTIONAL
	WSDATA   dEXECUTIONINITIALDATE     AS date OPTIONAL
	WSDATA   cLEVEL                    AS string
	WSDATA   nPOC                      AS float OPTIONAL
	WSDATA   cPROJECTCODE              AS string
	WSDATA   nQUANTITY                 AS float OPTIONAL
	WSDATA   cRESOURCES                AS string OPTIONAL
	WSDATA   cTASKCODE                 AS string
	WSDATA   cTASKDESCRIPTION          AS string
	WSDATA   nTASKTYPE                 AS integer
	WSDATA   nTIMEDURATION             AS float OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PMSREPORT_GANTTTASKVIEW
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PMSREPORT_GANTTTASKVIEW
Return

WSMETHOD CLONE WSCLIENT PMSREPORT_GANTTTASKVIEW
	Local oClone := PMSREPORT_GANTTTASKVIEW():NEW()
	oClone:cBITMAP              := ::cBITMAP
	oClone:nCPM                 := ::nCPM
	oClone:nDBRECORD            := ::nDBRECORD
	oClone:dESTIMATEDFINALDATE  := ::dESTIMATEDFINALDATE
	oClone:cESTIMATEDFINALHOUR  := ::cESTIMATEDFINALHOUR
	oClone:dESTIMATEDINITIALDATE := ::dESTIMATEDINITIALDATE
	oClone:cESTIMATEDINITIALHOUR := ::cESTIMATEDINITIALHOUR
	oClone:dEXECUTIONFINALDATE  := ::dEXECUTIONFINALDATE
	oClone:dEXECUTIONINITIALDATE := ::dEXECUTIONINITIALDATE
	oClone:cLEVEL               := ::cLEVEL
	oClone:nPOC                 := ::nPOC
	oClone:cPROJECTCODE         := ::cPROJECTCODE
	oClone:nQUANTITY            := ::nQUANTITY
	oClone:cRESOURCES           := ::cRESOURCES
	oClone:cTASKCODE            := ::cTASKCODE
	oClone:cTASKDESCRIPTION     := ::cTASKDESCRIPTION
	oClone:nTASKTYPE            := ::nTASKTYPE
	oClone:nTIMEDURATION        := ::nTIMEDURATION
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PMSREPORT_GANTTTASKVIEW
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::cBITMAP            :=  WSAdvValue( oResponse,"_BITMAP","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::nCPM               :=  WSAdvValue( oResponse,"_CPM","integer",NIL,NIL,NIL,"N",NIL,NIL) 
	::nDBRECORD          :=  WSAdvValue( oResponse,"_DBRECORD","integer",NIL,NIL,NIL,"N",NIL,NIL) 
	::dESTIMATEDFINALDATE :=  WSAdvValue( oResponse,"_ESTIMATEDFINALDATE","date",NIL,"Property dESTIMATEDFINALDATE as s:date on SOAP Response not found.",NIL,"D",NIL,NIL) 
	::cESTIMATEDFINALHOUR :=  WSAdvValue( oResponse,"_ESTIMATEDFINALHOUR","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::dESTIMATEDINITIALDATE :=  WSAdvValue( oResponse,"_ESTIMATEDINITIALDATE","date",NIL,"Property dESTIMATEDINITIALDATE as s:date on SOAP Response not found.",NIL,"D",NIL,NIL) 
	::cESTIMATEDINITIALHOUR :=  WSAdvValue( oResponse,"_ESTIMATEDINITIALHOUR","string",NIL,"Property cESTIMATEDINITIALHOUR as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::dEXECUTIONFINALDATE :=  WSAdvValue( oResponse,"_EXECUTIONFINALDATE","date",NIL,NIL,NIL,"D",NIL,NIL) 
	::dEXECUTIONINITIALDATE :=  WSAdvValue( oResponse,"_EXECUTIONINITIALDATE","date",NIL,NIL,NIL,"D",NIL,NIL) 
	::cLEVEL             :=  WSAdvValue( oResponse,"_LEVEL","string",NIL,"Property cLEVEL as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::nPOC               :=  WSAdvValue( oResponse,"_POC","float",NIL,NIL,NIL,"N",NIL,NIL) 
	::cPROJECTCODE       :=  WSAdvValue( oResponse,"_PROJECTCODE","string",NIL,"Property cPROJECTCODE as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::nQUANTITY          :=  WSAdvValue( oResponse,"_QUANTITY","float",NIL,NIL,NIL,"N",NIL,NIL) 
	::cRESOURCES         :=  WSAdvValue( oResponse,"_RESOURCES","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cTASKCODE          :=  WSAdvValue( oResponse,"_TASKCODE","string",NIL,"Property cTASKCODE as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cTASKDESCRIPTION   :=  WSAdvValue( oResponse,"_TASKDESCRIPTION","string",NIL,"Property cTASKDESCRIPTION as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::nTASKTYPE          :=  WSAdvValue( oResponse,"_TASKTYPE","integer",NIL,"Property nTASKTYPE as s:integer on SOAP Response not found.",NIL,"N",NIL,NIL) 
	::nTIMEDURATION      :=  WSAdvValue( oResponse,"_TIMEDURATION","float",NIL,NIL,NIL,"N",NIL,NIL) 
Return

// WSDL Data Structure BRWHEADER

WSSTRUCT PMSREPORT_BRWHEADER
	WSDATA   cHEADERCOMBOBOX           AS string OPTIONAL
	WSDATA   nHEADERDEC                AS integer
	WSDATA   cHEADERF3                 AS string OPTIONAL
	WSDATA   cHEADERFIELD              AS string
	WSDATA   lHEADEROBLIG              AS boolean OPTIONAL
	WSDATA   cHEADERPICTURE            AS string
	WSDATA   nHEADERSIZE               AS integer
	WSDATA   cHEADERTITLE              AS string
	WSDATA   cHEADERTYPE               AS string
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PMSREPORT_BRWHEADER
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PMSREPORT_BRWHEADER
Return

WSMETHOD CLONE WSCLIENT PMSREPORT_BRWHEADER
	Local oClone := PMSREPORT_BRWHEADER():NEW()
	oClone:cHEADERCOMBOBOX      := ::cHEADERCOMBOBOX
	oClone:nHEADERDEC           := ::nHEADERDEC
	oClone:cHEADERF3            := ::cHEADERF3
	oClone:cHEADERFIELD         := ::cHEADERFIELD
	oClone:lHEADEROBLIG         := ::lHEADEROBLIG
	oClone:cHEADERPICTURE       := ::cHEADERPICTURE
	oClone:nHEADERSIZE          := ::nHEADERSIZE
	oClone:cHEADERTITLE         := ::cHEADERTITLE
	oClone:cHEADERTYPE          := ::cHEADERTYPE
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PMSREPORT_BRWHEADER
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::cHEADERCOMBOBOX    :=  WSAdvValue( oResponse,"_HEADERCOMBOBOX","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::nHEADERDEC         :=  WSAdvValue( oResponse,"_HEADERDEC","integer",NIL,"Property nHEADERDEC as s:integer on SOAP Response not found.",NIL,"N",NIL,NIL) 
	::cHEADERF3          :=  WSAdvValue( oResponse,"_HEADERF3","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cHEADERFIELD       :=  WSAdvValue( oResponse,"_HEADERFIELD","string",NIL,"Property cHEADERFIELD as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::lHEADEROBLIG       :=  WSAdvValue( oResponse,"_HEADEROBLIG","boolean",NIL,NIL,NIL,"L",NIL,NIL) 
	::cHEADERPICTURE     :=  WSAdvValue( oResponse,"_HEADERPICTURE","string",NIL,"Property cHEADERPICTURE as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::nHEADERSIZE        :=  WSAdvValue( oResponse,"_HEADERSIZE","integer",NIL,"Property nHEADERSIZE as s:integer on SOAP Response not found.",NIL,"N",NIL,NIL) 
	::cHEADERTITLE       :=  WSAdvValue( oResponse,"_HEADERTITLE","string",NIL,"Property cHEADERTITLE as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cHEADERTYPE        :=  WSAdvValue( oResponse,"_HEADERTYPE","string",NIL,"Property cHEADERTYPE as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
Return

// WSDL Data Structure BRWHEADERPMS

WSSTRUCT PMSREPORT_BRWHEADERPMS
	WSDATA   cEDITABLE                 AS string OPTIONAL
	WSDATA   cHEADERCOMBOBOX           AS string OPTIONAL
	WSDATA   nHEADERDEC                AS integer OPTIONAL
	WSDATA   cHEADERF3                 AS string OPTIONAL
	WSDATA   cHEADERFIELD              AS string OPTIONAL
	WSDATA   cHEADERFOLDER             AS string OPTIONAL
	WSDATA   lHEADEROBLIG              AS boolean OPTIONAL
	WSDATA   cHEADERORDER              AS string OPTIONAL
	WSDATA   cHEADERPICTURE            AS string OPTIONAL
	WSDATA   nHEADERSIZE               AS integer OPTIONAL
	WSDATA   cHEADERTITLE              AS string OPTIONAL
	WSDATA   cHEADERTYPE               AS string OPTIONAL
	WSDATA   cHEADERTYPE2              AS string OPTIONAL
	WSDATA   cINITIALVALUE             AS string OPTIONAL
	WSDATA   cPROPRIETYNAME            AS string OPTIONAL
	WSDATA   lUSERFIELD                AS boolean OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PMSREPORT_BRWHEADERPMS
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PMSREPORT_BRWHEADERPMS
Return

WSMETHOD CLONE WSCLIENT PMSREPORT_BRWHEADERPMS
	Local oClone := PMSREPORT_BRWHEADERPMS():NEW()
	oClone:cEDITABLE            := ::cEDITABLE
	oClone:cHEADERCOMBOBOX      := ::cHEADERCOMBOBOX
	oClone:nHEADERDEC           := ::nHEADERDEC
	oClone:cHEADERF3            := ::cHEADERF3
	oClone:cHEADERFIELD         := ::cHEADERFIELD
	oClone:cHEADERFOLDER        := ::cHEADERFOLDER
	oClone:lHEADEROBLIG         := ::lHEADEROBLIG
	oClone:cHEADERORDER         := ::cHEADERORDER
	oClone:cHEADERPICTURE       := ::cHEADERPICTURE
	oClone:nHEADERSIZE          := ::nHEADERSIZE
	oClone:cHEADERTITLE         := ::cHEADERTITLE
	oClone:cHEADERTYPE          := ::cHEADERTYPE
	oClone:cHEADERTYPE2         := ::cHEADERTYPE2
	oClone:cINITIALVALUE        := ::cINITIALVALUE
	oClone:cPROPRIETYNAME       := ::cPROPRIETYNAME
	oClone:lUSERFIELD           := ::lUSERFIELD
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PMSREPORT_BRWHEADERPMS
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::cEDITABLE          :=  WSAdvValue( oResponse,"_EDITABLE","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cHEADERCOMBOBOX    :=  WSAdvValue( oResponse,"_HEADERCOMBOBOX","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::nHEADERDEC         :=  WSAdvValue( oResponse,"_HEADERDEC","integer",NIL,NIL,NIL,"N",NIL,NIL) 
	::cHEADERF3          :=  WSAdvValue( oResponse,"_HEADERF3","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cHEADERFIELD       :=  WSAdvValue( oResponse,"_HEADERFIELD","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cHEADERFOLDER      :=  WSAdvValue( oResponse,"_HEADERFOLDER","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::lHEADEROBLIG       :=  WSAdvValue( oResponse,"_HEADEROBLIG","boolean",NIL,NIL,NIL,"L",NIL,NIL) 
	::cHEADERORDER       :=  WSAdvValue( oResponse,"_HEADERORDER","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cHEADERPICTURE     :=  WSAdvValue( oResponse,"_HEADERPICTURE","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::nHEADERSIZE        :=  WSAdvValue( oResponse,"_HEADERSIZE","integer",NIL,NIL,NIL,"N",NIL,NIL) 
	::cHEADERTITLE       :=  WSAdvValue( oResponse,"_HEADERTITLE","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cHEADERTYPE        :=  WSAdvValue( oResponse,"_HEADERTYPE","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cHEADERTYPE2       :=  WSAdvValue( oResponse,"_HEADERTYPE2","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cINITIALVALUE      :=  WSAdvValue( oResponse,"_INITIALVALUE","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cPROPRIETYNAME     :=  WSAdvValue( oResponse,"_PROPRIETYNAME","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::lUSERFIELD         :=  WSAdvValue( oResponse,"_USERFIELD","boolean",NIL,NIL,NIL,"L",NIL,NIL) 
Return

// WSDL Data Structure ARRAYOFUSERFIELD

WSSTRUCT PMSREPORT_ARRAYOFUSERFIELD
	WSDATA   oWSUSERFIELD              AS PMSREPORT_USERFIELD OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PMSREPORT_ARRAYOFUSERFIELD
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PMSREPORT_ARRAYOFUSERFIELD
	::oWSUSERFIELD         := {} // Array Of  PMSREPORT_USERFIELD():New()
Return

WSMETHOD CLONE WSCLIENT PMSREPORT_ARRAYOFUSERFIELD
	Local oClone := PMSREPORT_ARRAYOFUSERFIELD():NEW()
	oClone:oWSUSERFIELD := NIL
	If ::oWSUSERFIELD <> NIL 
		oClone:oWSUSERFIELD := {}
		aEval( ::oWSUSERFIELD , { |x| aadd( oClone:oWSUSERFIELD , x:Clone() ) } )
	Endif 
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PMSREPORT_ARRAYOFUSERFIELD
	Local nRElem1, oNodes1, nTElem1
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNodes1 :=  WSAdvValue( oResponse,"_USERFIELD","USERFIELD",{},NIL,.T.,"O",NIL,NIL) 
	nTElem1 := len(oNodes1)
	For nRElem1 := 1 to nTElem1 
		If !WSIsNilNode( oNodes1[nRElem1] )
			aadd(::oWSUSERFIELD , PMSREPORT_USERFIELD():New() )
			::oWSUSERFIELD[len(::oWSUSERFIELD)]:SoapRecv(oNodes1[nRElem1])
		Endif
	Next
Return

// WSDL Data Structure OCORRENCEVIEW

WSSTRUCT PMSREPORT_OCORRENCEVIEW
	WSDATA   cOCORRENCECODE            AS string OPTIONAL
	WSDATA   cOCORRENCEDESCRIPTION     AS string OPTIONAL
	WSDATA   oWSUSERFIELDS             AS PMSREPORT_ARRAYOFUSERFIELD OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PMSREPORT_OCORRENCEVIEW
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PMSREPORT_OCORRENCEVIEW
Return

WSMETHOD CLONE WSCLIENT PMSREPORT_OCORRENCEVIEW
	Local oClone := PMSREPORT_OCORRENCEVIEW():NEW()
	oClone:cOCORRENCECODE       := ::cOCORRENCECODE
	oClone:cOCORRENCEDESCRIPTION := ::cOCORRENCEDESCRIPTION
	oClone:oWSUSERFIELDS        := IIF(::oWSUSERFIELDS = NIL , NIL , ::oWSUSERFIELDS:Clone() )
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PMSREPORT_OCORRENCEVIEW
	Local oNode3
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::cOCORRENCECODE     :=  WSAdvValue( oResponse,"_OCORRENCECODE","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cOCORRENCEDESCRIPTION :=  WSAdvValue( oResponse,"_OCORRENCEDESCRIPTION","string",NIL,NIL,NIL,"S",NIL,NIL) 
	oNode3 :=  WSAdvValue( oResponse,"_USERFIELDS","ARRAYOFUSERFIELD",NIL,NIL,NIL,"O",NIL,NIL) 
	If oNode3 != NIL
		::oWSUSERFIELDS := PMSREPORT_ARRAYOFUSERFIELD():New()
		::oWSUSERFIELDS:SoapRecv(oNode3)
	EndIf
Return

// WSDL Data Structure PROJECTLISTVIEW

WSSTRUCT PMSREPORT_PROJECTLISTVIEW
	WSDATA   cDESCRIPTION              AS string OPTIONAL
	WSDATA   cPROJECTCLIENTE           AS string OPTIONAL
	WSDATA   cPROJECTCODE              AS string OPTIONAL
	WSDATA   dPROJECTDATE              AS date OPTIONAL
	WSDATA   cPROJECTREVISION          AS string OPTIONAL
	WSDATA   cPROJECTSTAGE             AS string OPTIONAL
	WSDATA   cPROJECTUNIT              AS string OPTIONAL
	WSDATA   oWSUSERFIELDS             AS PMSREPORT_ARRAYOFUSERFIELD OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PMSREPORT_PROJECTLISTVIEW
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PMSREPORT_PROJECTLISTVIEW
Return

WSMETHOD CLONE WSCLIENT PMSREPORT_PROJECTLISTVIEW
	Local oClone := PMSREPORT_PROJECTLISTVIEW():NEW()
	oClone:cDESCRIPTION         := ::cDESCRIPTION
	oClone:cPROJECTCLIENTE      := ::cPROJECTCLIENTE
	oClone:cPROJECTCODE         := ::cPROJECTCODE
	oClone:dPROJECTDATE         := ::dPROJECTDATE
	oClone:cPROJECTREVISION     := ::cPROJECTREVISION
	oClone:cPROJECTSTAGE        := ::cPROJECTSTAGE
	oClone:cPROJECTUNIT         := ::cPROJECTUNIT
	oClone:oWSUSERFIELDS        := IIF(::oWSUSERFIELDS = NIL , NIL , ::oWSUSERFIELDS:Clone() )
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PMSREPORT_PROJECTLISTVIEW
	Local oNode8
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::cDESCRIPTION       :=  WSAdvValue( oResponse,"_DESCRIPTION","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cPROJECTCLIENTE    :=  WSAdvValue( oResponse,"_PROJECTCLIENTE","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cPROJECTCODE       :=  WSAdvValue( oResponse,"_PROJECTCODE","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::dPROJECTDATE       :=  WSAdvValue( oResponse,"_PROJECTDATE","date",NIL,NIL,NIL,"D",NIL,NIL) 
	::cPROJECTREVISION   :=  WSAdvValue( oResponse,"_PROJECTREVISION","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cPROJECTSTAGE      :=  WSAdvValue( oResponse,"_PROJECTSTAGE","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cPROJECTUNIT       :=  WSAdvValue( oResponse,"_PROJECTUNIT","string",NIL,NIL,NIL,"S",NIL,NIL) 
	oNode8 :=  WSAdvValue( oResponse,"_USERFIELDS","ARRAYOFUSERFIELD",NIL,NIL,NIL,"O",NIL,NIL) 
	If oNode8 != NIL
		::oWSUSERFIELDS := PMSREPORT_ARRAYOFUSERFIELD():New()
		::oWSUSERFIELDS:SoapRecv(oNode8)
	EndIf
Return

// WSDL Data Structure TEAMVIEW

WSSTRUCT PMSREPORT_TEAMVIEW
	WSDATA   cTEAMCODE                 AS string OPTIONAL
	WSDATA   cTEAMNAME                 AS string OPTIONAL
	WSDATA   oWSUSERFIELDS             AS PMSREPORT_ARRAYOFUSERFIELD OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PMSREPORT_TEAMVIEW
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PMSREPORT_TEAMVIEW
Return

WSMETHOD CLONE WSCLIENT PMSREPORT_TEAMVIEW
	Local oClone := PMSREPORT_TEAMVIEW():NEW()
	oClone:cTEAMCODE            := ::cTEAMCODE
	oClone:cTEAMNAME            := ::cTEAMNAME
	oClone:oWSUSERFIELDS        := IIF(::oWSUSERFIELDS = NIL , NIL , ::oWSUSERFIELDS:Clone() )
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PMSREPORT_TEAMVIEW
	Local oNode3
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::cTEAMCODE          :=  WSAdvValue( oResponse,"_TEAMCODE","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cTEAMNAME          :=  WSAdvValue( oResponse,"_TEAMNAME","string",NIL,NIL,NIL,"S",NIL,NIL) 
	oNode3 :=  WSAdvValue( oResponse,"_USERFIELDS","ARRAYOFUSERFIELD",NIL,NIL,NIL,"O",NIL,NIL) 
	If oNode3 != NIL
		::oWSUSERFIELDS := PMSREPORT_ARRAYOFUSERFIELD():New()
		::oWSUSERFIELDS:SoapRecv(oNode3)
	EndIf
Return

// WSDL Data Structure USERFIELD

WSSTRUCT PMSREPORT_USERFIELD
	WSDATA   cUSERCOMBOBOX             AS string OPTIONAL
	WSDATA   nUSERDEC                  AS integer OPTIONAL
	WSDATA   cUSERF3                   AS string OPTIONAL
	WSDATA   cUSERNAME                 AS string
	WSDATA   lUSEROBLIG                AS boolean OPTIONAL
	WSDATA   cUSERPICTURE              AS string OPTIONAL
	WSDATA   nUSERSIZE                 AS integer OPTIONAL
	WSDATA   cUSERTAG                  AS string OPTIONAL
	WSDATA   cUSERTITLE                AS string OPTIONAL
	WSDATA   cUSERTYPE                 AS string
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PMSREPORT_USERFIELD
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PMSREPORT_USERFIELD
Return

WSMETHOD CLONE WSCLIENT PMSREPORT_USERFIELD
	Local oClone := PMSREPORT_USERFIELD():NEW()
	oClone:cUSERCOMBOBOX        := ::cUSERCOMBOBOX
	oClone:nUSERDEC             := ::nUSERDEC
	oClone:cUSERF3              := ::cUSERF3
	oClone:cUSERNAME            := ::cUSERNAME
	oClone:lUSEROBLIG           := ::lUSEROBLIG
	oClone:cUSERPICTURE         := ::cUSERPICTURE
	oClone:nUSERSIZE            := ::nUSERSIZE
	oClone:cUSERTAG             := ::cUSERTAG
	oClone:cUSERTITLE           := ::cUSERTITLE
	oClone:cUSERTYPE            := ::cUSERTYPE
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PMSREPORT_USERFIELD
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::cUSERCOMBOBOX      :=  WSAdvValue( oResponse,"_USERCOMBOBOX","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::nUSERDEC           :=  WSAdvValue( oResponse,"_USERDEC","integer",NIL,NIL,NIL,"N",NIL,NIL) 
	::cUSERF3            :=  WSAdvValue( oResponse,"_USERF3","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cUSERNAME          :=  WSAdvValue( oResponse,"_USERNAME","string",NIL,"Property cUSERNAME as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::lUSEROBLIG         :=  WSAdvValue( oResponse,"_USEROBLIG","boolean",NIL,NIL,NIL,"L",NIL,NIL) 
	::cUSERPICTURE       :=  WSAdvValue( oResponse,"_USERPICTURE","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::nUSERSIZE          :=  WSAdvValue( oResponse,"_USERSIZE","integer",NIL,NIL,NIL,"N",NIL,NIL) 
	::cUSERTAG           :=  WSAdvValue( oResponse,"_USERTAG","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cUSERTITLE         :=  WSAdvValue( oResponse,"_USERTITLE","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cUSERTYPE          :=  WSAdvValue( oResponse,"_USERTYPE","string",NIL,"Property cUSERTYPE as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
Return


