#INCLUDE "protheus.ch"
#INCLUDE "apwebsrv.ch"

/* ===============================================================================
WSDL Location    http://localhost:8059/ws/PMSCONFIRMATIONS.apw?WSDL
Gerado em        12/14/20 11:21:30
Observações      Código-Fonte gerado por ADVPL WSDL Client 1.120703
                 Alterações neste arquivo podem causar funcionamento incorreto
                 e serão perdidas caso o código-fonte seja gerado novamente.
=============================================================================== */

User Function _KRMZASR ; Return  // "dummy" function - Internal Use 

/* -------------------------------------------------------------------------------
WSDL Service WSPMSCONFIRMATIONS
------------------------------------------------------------------------------- */

WSCLIENT WSPMSCONFIRMATIONS

	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD RESET
	WSMETHOD CLONE
	WSMETHOD CONFIRMATIONHANDLE
	WSMETHOD GETCONFIRMATION
	WSMETHOD GETCONFIRMATIONBYRECORD
	WSMETHOD GETCONFIRMATIONSLIST
	WSMETHOD GETHEADER
	WSMETHOD GETHEADERPMS

	WSDATA   _URL                      AS String
	WSDATA   _HEADOUT                  AS Array of String
	WSDATA   _COOKIES                  AS Array of String
	WSDATA   cUSERCODE                 AS string
	WSDATA   cPROTHEUSUSERCODE         AS string
	WSDATA   oWSCONFIRMATIONHANDLE     AS PMSCONFIRMATIONS_CONFIRMATIONVIEW
	WSDATA   nOPERATIONNUMBER          AS integer
	WSDATA   oWSCONFIRMATIONHANDLERESULT AS PMSCONFIRMATIONS_ARRAYOFMESSAGEVIEW
	WSDATA   cPROJECTCODE              AS string
	WSDATA   cTASKCODE                 AS string
	WSDATA   dDATECONF                 AS date
	WSDATA   oWSGETCONFIRMATIONRESULT  AS PMSCONFIRMATIONS_ARRAYOFCONFIRMATIONVIEW
	WSDATA   nDBRECORD                 AS integer
	WSDATA   oWSGETCONFIRMATIONBYRECORDRESULT AS PMSCONFIRMATIONS_ARRAYOFCONFIRMATIONVIEW
	WSDATA   cTASKINITIAL              AS string
	WSDATA   cTASKFINAL                AS string
	WSDATA   cPROJECTINITIAL           AS string
	WSDATA   cPROJECTFINAL             AS string
	WSDATA   nPAGELEN                  AS integer
	WSDATA   nPAGEFIRST                AS integer
	WSDATA   cQRYADD                   AS string
	WSDATA   nINDEXKEY                 AS integer
	WSDATA   oWSGETCONFIRMATIONSLISTRESULT AS PMSCONFIRMATIONS_ARRAYOFCONFIRMATIONSLISTVIEW
	WSDATA   cHEADERTYPE               AS string
	WSDATA   oWSGETHEADERRESULT        AS PMSCONFIRMATIONS_ARRAYOFBRWHEADER
	WSDATA   oWSGETHEADERPMSRESULT     AS PMSCONFIRMATIONS_ARRAYOFBRWHEADERPMS

	// Estruturas mantidas por compatibilidade - NÃO USAR
	WSDATA   oWSCONFIRMATIONVIEW       AS PMSCONFIRMATIONS_CONFIRMATIONVIEW

ENDWSCLIENT

WSMETHOD NEW WSCLIENT WSPMSCONFIRMATIONS
::Init()
If !FindFunction("XMLCHILDEX")
	UserException("O Código-Fonte Client atual requer os executáveis do Protheus Build [7.00.191205P-20201009] ou superior. Atualize o Protheus ou gere o Código-Fonte novamente utilizando o Build atual.")
EndIf
Return Self

WSMETHOD INIT WSCLIENT WSPMSCONFIRMATIONS
	::oWSCONFIRMATIONHANDLE := PMSCONFIRMATIONS_CONFIRMATIONVIEW():New()
	::oWSCONFIRMATIONHANDLERESULT := PMSCONFIRMATIONS_ARRAYOFMESSAGEVIEW():New()
	::oWSGETCONFIRMATIONRESULT := PMSCONFIRMATIONS_ARRAYOFCONFIRMATIONVIEW():New()
	::oWSGETCONFIRMATIONBYRECORDRESULT := PMSCONFIRMATIONS_ARRAYOFCONFIRMATIONVIEW():New()
	::oWSGETCONFIRMATIONSLISTRESULT := PMSCONFIRMATIONS_ARRAYOFCONFIRMATIONSLISTVIEW():New()
	::oWSGETHEADERRESULT := PMSCONFIRMATIONS_ARRAYOFBRWHEADER():New()
	::oWSGETHEADERPMSRESULT := PMSCONFIRMATIONS_ARRAYOFBRWHEADERPMS():New()

	// Estruturas mantidas por compatibilidade - NÃO USAR
	::oWSCONFIRMATIONVIEW := ::oWSCONFIRMATIONHANDLE
Return

WSMETHOD RESET WSCLIENT WSPMSCONFIRMATIONS
	::cUSERCODE          := NIL 
	::cPROTHEUSUSERCODE  := NIL 
	::oWSCONFIRMATIONHANDLE := NIL 
	::nOPERATIONNUMBER   := NIL 
	::oWSCONFIRMATIONHANDLERESULT := NIL 
	::cPROJECTCODE       := NIL 
	::cTASKCODE          := NIL 
	::dDATECONF          := NIL 
	::oWSGETCONFIRMATIONRESULT := NIL 
	::nDBRECORD          := NIL 
	::oWSGETCONFIRMATIONBYRECORDRESULT := NIL 
	::cTASKINITIAL       := NIL 
	::cTASKFINAL         := NIL 
	::cPROJECTINITIAL    := NIL 
	::cPROJECTFINAL      := NIL 
	::nPAGELEN           := NIL 
	::nPAGEFIRST         := NIL 
	::cQRYADD            := NIL 
	::nINDEXKEY          := NIL 
	::oWSGETCONFIRMATIONSLISTRESULT := NIL 
	::cHEADERTYPE        := NIL 
	::oWSGETHEADERRESULT := NIL 
	::oWSGETHEADERPMSRESULT := NIL 

	// Estruturas mantidas por compatibilidade - NÃO USAR
	::oWSCONFIRMATIONVIEW := NIL
	::Init()
Return

WSMETHOD CLONE WSCLIENT WSPMSCONFIRMATIONS
Local oClone := WSPMSCONFIRMATIONS():New()
	oClone:_URL          := ::_URL 
	oClone:cUSERCODE     := ::cUSERCODE
	oClone:cPROTHEUSUSERCODE := ::cPROTHEUSUSERCODE
	oClone:oWSCONFIRMATIONHANDLE :=  IIF(::oWSCONFIRMATIONHANDLE = NIL , NIL ,::oWSCONFIRMATIONHANDLE:Clone() )
	oClone:nOPERATIONNUMBER := ::nOPERATIONNUMBER
	oClone:oWSCONFIRMATIONHANDLERESULT :=  IIF(::oWSCONFIRMATIONHANDLERESULT = NIL , NIL ,::oWSCONFIRMATIONHANDLERESULT:Clone() )
	oClone:cPROJECTCODE  := ::cPROJECTCODE
	oClone:cTASKCODE     := ::cTASKCODE
	oClone:dDATECONF     := ::dDATECONF
	oClone:oWSGETCONFIRMATIONRESULT :=  IIF(::oWSGETCONFIRMATIONRESULT = NIL , NIL ,::oWSGETCONFIRMATIONRESULT:Clone() )
	oClone:nDBRECORD     := ::nDBRECORD
	oClone:oWSGETCONFIRMATIONBYRECORDRESULT :=  IIF(::oWSGETCONFIRMATIONBYRECORDRESULT = NIL , NIL ,::oWSGETCONFIRMATIONBYRECORDRESULT:Clone() )
	oClone:cTASKINITIAL  := ::cTASKINITIAL
	oClone:cTASKFINAL    := ::cTASKFINAL
	oClone:cPROJECTINITIAL := ::cPROJECTINITIAL
	oClone:cPROJECTFINAL := ::cPROJECTFINAL
	oClone:nPAGELEN      := ::nPAGELEN
	oClone:nPAGEFIRST    := ::nPAGEFIRST
	oClone:cQRYADD       := ::cQRYADD
	oClone:nINDEXKEY     := ::nINDEXKEY
	oClone:oWSGETCONFIRMATIONSLISTRESULT :=  IIF(::oWSGETCONFIRMATIONSLISTRESULT = NIL , NIL ,::oWSGETCONFIRMATIONSLISTRESULT:Clone() )
	oClone:cHEADERTYPE   := ::cHEADERTYPE
	oClone:oWSGETHEADERRESULT :=  IIF(::oWSGETHEADERRESULT = NIL , NIL ,::oWSGETHEADERRESULT:Clone() )
	oClone:oWSGETHEADERPMSRESULT :=  IIF(::oWSGETHEADERPMSRESULT = NIL , NIL ,::oWSGETHEADERPMSRESULT:Clone() )

	// Estruturas mantidas por compatibilidade - NÃO USAR
	oClone:oWSCONFIRMATIONVIEW := oClone:oWSCONFIRMATIONHANDLE
Return oClone

// WSDL Method CONFIRMATIONHANDLE of Service WSPMSCONFIRMATIONS

WSMETHOD CONFIRMATIONHANDLE WSSEND cUSERCODE,cPROTHEUSUSERCODE,oWSCONFIRMATIONHANDLE,nOPERATIONNUMBER WSRECEIVE oWSCONFIRMATIONHANDLERESULT WSCLIENT WSPMSCONFIRMATIONS
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<CONFIRMATIONHANDLE xmlns="http://localhost:8059/">'
cSoap += WSSoapValue("USERCODE", ::cUSERCODE, cUSERCODE , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("PROTHEUSUSERCODE", ::cPROTHEUSUSERCODE, cPROTHEUSUSERCODE , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("CONFIRMATIONHANDLE", ::oWSCONFIRMATIONHANDLE, oWSCONFIRMATIONHANDLE , "CONFIRMATIONVIEW", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("OPERATIONNUMBER", ::nOPERATIONNUMBER, nOPERATIONNUMBER , "integer", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += "</CONFIRMATIONHANDLE>"

oXmlRet := SvcSoapCall(Self,cSoap,; 
	"http://localhost:8059/CONFIRMATIONHANDLE",; 
	"DOCUMENT","http://localhost:8059/",,"1.031217",; 
	"http://localhost:8059/ws/PMSCONFIRMATIONS.apw")

::Init()
::oWSCONFIRMATIONHANDLERESULT:SoapRecv( WSAdvValue( oXmlRet,"_CONFIRMATIONHANDLERESPONSE:_CONFIRMATIONHANDLERESULT","ARRAYOFMESSAGEVIEW",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.

// WSDL Method GETCONFIRMATION of Service WSPMSCONFIRMATIONS

WSMETHOD GETCONFIRMATION WSSEND cUSERCODE,nOPERATIONNUMBER,cPROTHEUSUSERCODE,cPROJECTCODE,cTASKCODE,dDATECONF WSRECEIVE oWSGETCONFIRMATIONRESULT WSCLIENT WSPMSCONFIRMATIONS
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<GETCONFIRMATION xmlns="http://localhost:8059/">'
cSoap += WSSoapValue("USERCODE", ::cUSERCODE, cUSERCODE , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("OPERATIONNUMBER", ::nOPERATIONNUMBER, nOPERATIONNUMBER , "integer", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("PROTHEUSUSERCODE", ::cPROTHEUSUSERCODE, cPROTHEUSUSERCODE , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("PROJECTCODE", ::cPROJECTCODE, cPROJECTCODE , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("TASKCODE", ::cTASKCODE, cTASKCODE , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("DATECONF", ::dDATECONF, dDATECONF , "date", .F. , .F., 0 , NIL, .F.,.F.) 
cSoap += "</GETCONFIRMATION>"

oXmlRet := SvcSoapCall(Self,cSoap,; 
	"http://localhost:8059/GETCONFIRMATION",; 
	"DOCUMENT","http://localhost:8059/",,"1.031217",; 
	"http://localhost:8059/ws/PMSCONFIRMATIONS.apw")

::Init()
::oWSGETCONFIRMATIONRESULT:SoapRecv( WSAdvValue( oXmlRet,"_GETCONFIRMATIONRESPONSE:_GETCONFIRMATIONRESULT","ARRAYOFCONFIRMATIONVIEW",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.

// WSDL Method GETCONFIRMATIONBYRECORD of Service WSPMSCONFIRMATIONS

WSMETHOD GETCONFIRMATIONBYRECORD WSSEND cUSERCODE,nOPERATIONNUMBER,cPROTHEUSUSERCODE,nDBRECORD WSRECEIVE oWSGETCONFIRMATIONBYRECORDRESULT WSCLIENT WSPMSCONFIRMATIONS
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<GETCONFIRMATIONBYRECORD xmlns="http://localhost:8059/">'
cSoap += WSSoapValue("USERCODE", ::cUSERCODE, cUSERCODE , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("OPERATIONNUMBER", ::nOPERATIONNUMBER, nOPERATIONNUMBER , "integer", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("PROTHEUSUSERCODE", ::cPROTHEUSUSERCODE, cPROTHEUSUSERCODE , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("DBRECORD", ::nDBRECORD, nDBRECORD , "integer", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += "</GETCONFIRMATIONBYRECORD>"

oXmlRet := SvcSoapCall(Self,cSoap,; 
	"http://localhost:8059/GETCONFIRMATIONBYRECORD",; 
	"DOCUMENT","http://localhost:8059/",,"1.031217",; 
	"http://localhost:8059/ws/PMSCONFIRMATIONS.apw")

::Init()
::oWSGETCONFIRMATIONBYRECORDRESULT:SoapRecv( WSAdvValue( oXmlRet,"_GETCONFIRMATIONBYRECORDRESPONSE:_GETCONFIRMATIONBYRECORDRESULT","ARRAYOFCONFIRMATIONVIEW",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.

// WSDL Method GETCONFIRMATIONSLIST of Service WSPMSCONFIRMATIONS

WSMETHOD GETCONFIRMATIONSLIST WSSEND cUSERCODE,cPROTHEUSUSERCODE,cTASKINITIAL,cTASKFINAL,cPROJECTINITIAL,cPROJECTFINAL,nPAGELEN,nPAGEFIRST,cQRYADD,nINDEXKEY WSRECEIVE oWSGETCONFIRMATIONSLISTRESULT WSCLIENT WSPMSCONFIRMATIONS
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<GETCONFIRMATIONSLIST xmlns="http://localhost:8059/">'
cSoap += WSSoapValue("USERCODE", ::cUSERCODE, cUSERCODE , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("PROTHEUSUSERCODE", ::cPROTHEUSUSERCODE, cPROTHEUSUSERCODE , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("TASKINITIAL", ::cTASKINITIAL, cTASKINITIAL , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("TASKFINAL", ::cTASKFINAL, cTASKFINAL , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("PROJECTINITIAL", ::cPROJECTINITIAL, cPROJECTINITIAL , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("PROJECTFINAL", ::cPROJECTFINAL, cPROJECTFINAL , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("PAGELEN", ::nPAGELEN, nPAGELEN , "integer", .F. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("PAGEFIRST", ::nPAGEFIRST, nPAGEFIRST , "integer", .F. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("QRYADD", ::cQRYADD, cQRYADD , "string", .F. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("INDEXKEY", ::nINDEXKEY, nINDEXKEY , "integer", .F. , .F., 0 , NIL, .F.,.F.) 
cSoap += "</GETCONFIRMATIONSLIST>"

oXmlRet := SvcSoapCall(Self,cSoap,; 
	"http://localhost:8059/GETCONFIRMATIONSLIST",; 
	"DOCUMENT","http://localhost:8059/",,"1.031217",; 
	"http://localhost:8059/ws/PMSCONFIRMATIONS.apw")

::Init()
::oWSGETCONFIRMATIONSLISTRESULT:SoapRecv( WSAdvValue( oXmlRet,"_GETCONFIRMATIONSLISTRESPONSE:_GETCONFIRMATIONSLISTRESULT","ARRAYOFCONFIRMATIONSLISTVIEW",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.

// WSDL Method GETHEADER of Service WSPMSCONFIRMATIONS

WSMETHOD GETHEADER WSSEND cHEADERTYPE WSRECEIVE oWSGETHEADERRESULT WSCLIENT WSPMSCONFIRMATIONS
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<GETHEADER xmlns="http://localhost:8059/">'
cSoap += WSSoapValue("HEADERTYPE", ::cHEADERTYPE, cHEADERTYPE , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += "</GETHEADER>"

oXmlRet := SvcSoapCall(Self,cSoap,; 
	"http://localhost:8059/GETHEADER",; 
	"DOCUMENT","http://localhost:8059/",,"1.031217",; 
	"http://localhost:8059/ws/PMSCONFIRMATIONS.apw")

::Init()
::oWSGETHEADERRESULT:SoapRecv( WSAdvValue( oXmlRet,"_GETHEADERRESPONSE:_GETHEADERRESULT","ARRAYOFBRWHEADER",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.

// WSDL Method GETHEADERPMS of Service WSPMSCONFIRMATIONS

WSMETHOD GETHEADERPMS WSSEND cHEADERTYPE WSRECEIVE oWSGETHEADERPMSRESULT WSCLIENT WSPMSCONFIRMATIONS
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<GETHEADERPMS xmlns="http://localhost:8059/">'
cSoap += WSSoapValue("HEADERTYPE", ::cHEADERTYPE, cHEADERTYPE , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += "</GETHEADERPMS>"

oXmlRet := SvcSoapCall(Self,cSoap,; 
	"http://localhost:8059/GETHEADERPMS",; 
	"DOCUMENT","http://localhost:8059/",,"1.031217",; 
	"http://localhost:8059/ws/PMSCONFIRMATIONS.apw")

::Init()
::oWSGETHEADERPMSRESULT:SoapRecv( WSAdvValue( oXmlRet,"_GETHEADERPMSRESPONSE:_GETHEADERPMSRESULT","ARRAYOFBRWHEADERPMS",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.


// WSDL Data Structure ARRAYOFMESSAGEVIEW

WSSTRUCT PMSCONFIRMATIONS_ARRAYOFMESSAGEVIEW
	WSDATA   oWSMESSAGEVIEW            AS PMSCONFIRMATIONS_MESSAGEVIEW OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PMSCONFIRMATIONS_ARRAYOFMESSAGEVIEW
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PMSCONFIRMATIONS_ARRAYOFMESSAGEVIEW
	::oWSMESSAGEVIEW       := {} // Array Of  PMSCONFIRMATIONS_MESSAGEVIEW():New()
Return

WSMETHOD CLONE WSCLIENT PMSCONFIRMATIONS_ARRAYOFMESSAGEVIEW
	Local oClone := PMSCONFIRMATIONS_ARRAYOFMESSAGEVIEW():NEW()
	oClone:oWSMESSAGEVIEW := NIL
	If ::oWSMESSAGEVIEW <> NIL 
		oClone:oWSMESSAGEVIEW := {}
		aEval( ::oWSMESSAGEVIEW , { |x| aadd( oClone:oWSMESSAGEVIEW , x:Clone() ) } )
	Endif 
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PMSCONFIRMATIONS_ARRAYOFMESSAGEVIEW
	Local nRElem1, oNodes1, nTElem1
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNodes1 :=  WSAdvValue( oResponse,"_MESSAGEVIEW","MESSAGEVIEW",{},NIL,.T.,"O",NIL,NIL) 
	nTElem1 := len(oNodes1)
	For nRElem1 := 1 to nTElem1 
		If !WSIsNilNode( oNodes1[nRElem1] )
			aadd(::oWSMESSAGEVIEW , PMSCONFIRMATIONS_MESSAGEVIEW():New() )
			::oWSMESSAGEVIEW[len(::oWSMESSAGEVIEW)]:SoapRecv(oNodes1[nRElem1])
		Endif
	Next
Return

// WSDL Data Structure ARRAYOFCONFIRMATIONVIEW

WSSTRUCT PMSCONFIRMATIONS_ARRAYOFCONFIRMATIONVIEW
	WSDATA   oWSCONFIRMATIONVIEW       AS PMSCONFIRMATIONS_CONFIRMATIONVIEW OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PMSCONFIRMATIONS_ARRAYOFCONFIRMATIONVIEW
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PMSCONFIRMATIONS_ARRAYOFCONFIRMATIONVIEW
	::oWSCONFIRMATIONVIEW  := {} // Array Of  PMSCONFIRMATIONS_CONFIRMATIONVIEW():New()
Return

WSMETHOD CLONE WSCLIENT PMSCONFIRMATIONS_ARRAYOFCONFIRMATIONVIEW
	Local oClone := PMSCONFIRMATIONS_ARRAYOFCONFIRMATIONVIEW():NEW()
	oClone:oWSCONFIRMATIONVIEW := NIL
	If ::oWSCONFIRMATIONVIEW <> NIL 
		oClone:oWSCONFIRMATIONVIEW := {}
		aEval( ::oWSCONFIRMATIONVIEW , { |x| aadd( oClone:oWSCONFIRMATIONVIEW , x:Clone() ) } )
	Endif 
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PMSCONFIRMATIONS_ARRAYOFCONFIRMATIONVIEW
	Local nRElem1, oNodes1, nTElem1
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNodes1 :=  WSAdvValue( oResponse,"_CONFIRMATIONVIEW","CONFIRMATIONVIEW",{},NIL,.T.,"O",NIL,NIL) 
	nTElem1 := len(oNodes1)
	For nRElem1 := 1 to nTElem1 
		If !WSIsNilNode( oNodes1[nRElem1] )
			aadd(::oWSCONFIRMATIONVIEW , PMSCONFIRMATIONS_CONFIRMATIONVIEW():New() )
			::oWSCONFIRMATIONVIEW[len(::oWSCONFIRMATIONVIEW)]:SoapRecv(oNodes1[nRElem1])
		Endif
	Next
Return

// WSDL Data Structure ARRAYOFCONFIRMATIONSLISTVIEW

WSSTRUCT PMSCONFIRMATIONS_ARRAYOFCONFIRMATIONSLISTVIEW
	WSDATA   oWSCONFIRMATIONSLISTVIEW  AS PMSCONFIRMATIONS_CONFIRMATIONSLISTVIEW OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PMSCONFIRMATIONS_ARRAYOFCONFIRMATIONSLISTVIEW
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PMSCONFIRMATIONS_ARRAYOFCONFIRMATIONSLISTVIEW
	::oWSCONFIRMATIONSLISTVIEW := {} // Array Of  PMSCONFIRMATIONS_CONFIRMATIONSLISTVIEW():New()
Return

WSMETHOD CLONE WSCLIENT PMSCONFIRMATIONS_ARRAYOFCONFIRMATIONSLISTVIEW
	Local oClone := PMSCONFIRMATIONS_ARRAYOFCONFIRMATIONSLISTVIEW():NEW()
	oClone:oWSCONFIRMATIONSLISTVIEW := NIL
	If ::oWSCONFIRMATIONSLISTVIEW <> NIL 
		oClone:oWSCONFIRMATIONSLISTVIEW := {}
		aEval( ::oWSCONFIRMATIONSLISTVIEW , { |x| aadd( oClone:oWSCONFIRMATIONSLISTVIEW , x:Clone() ) } )
	Endif 
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PMSCONFIRMATIONS_ARRAYOFCONFIRMATIONSLISTVIEW
	Local nRElem1, oNodes1, nTElem1
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNodes1 :=  WSAdvValue( oResponse,"_CONFIRMATIONSLISTVIEW","CONFIRMATIONSLISTVIEW",{},NIL,.T.,"O",NIL,NIL) 
	nTElem1 := len(oNodes1)
	For nRElem1 := 1 to nTElem1 
		If !WSIsNilNode( oNodes1[nRElem1] )
			aadd(::oWSCONFIRMATIONSLISTVIEW , PMSCONFIRMATIONS_CONFIRMATIONSLISTVIEW():New() )
			::oWSCONFIRMATIONSLISTVIEW[len(::oWSCONFIRMATIONSLISTVIEW)]:SoapRecv(oNodes1[nRElem1])
		Endif
	Next
Return

// WSDL Data Structure ARRAYOFBRWHEADER

WSSTRUCT PMSCONFIRMATIONS_ARRAYOFBRWHEADER
	WSDATA   oWSBRWHEADER              AS PMSCONFIRMATIONS_BRWHEADER OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PMSCONFIRMATIONS_ARRAYOFBRWHEADER
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PMSCONFIRMATIONS_ARRAYOFBRWHEADER
	::oWSBRWHEADER         := {} // Array Of  PMSCONFIRMATIONS_BRWHEADER():New()
Return

WSMETHOD CLONE WSCLIENT PMSCONFIRMATIONS_ARRAYOFBRWHEADER
	Local oClone := PMSCONFIRMATIONS_ARRAYOFBRWHEADER():NEW()
	oClone:oWSBRWHEADER := NIL
	If ::oWSBRWHEADER <> NIL 
		oClone:oWSBRWHEADER := {}
		aEval( ::oWSBRWHEADER , { |x| aadd( oClone:oWSBRWHEADER , x:Clone() ) } )
	Endif 
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PMSCONFIRMATIONS_ARRAYOFBRWHEADER
	Local nRElem1, oNodes1, nTElem1
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNodes1 :=  WSAdvValue( oResponse,"_BRWHEADER","BRWHEADER",{},NIL,.T.,"O",NIL,NIL) 
	nTElem1 := len(oNodes1)
	For nRElem1 := 1 to nTElem1 
		If !WSIsNilNode( oNodes1[nRElem1] )
			aadd(::oWSBRWHEADER , PMSCONFIRMATIONS_BRWHEADER():New() )
			::oWSBRWHEADER[len(::oWSBRWHEADER)]:SoapRecv(oNodes1[nRElem1])
		Endif
	Next
Return

// WSDL Data Structure ARRAYOFBRWHEADERPMS

WSSTRUCT PMSCONFIRMATIONS_ARRAYOFBRWHEADERPMS
	WSDATA   oWSBRWHEADERPMS           AS PMSCONFIRMATIONS_BRWHEADERPMS OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PMSCONFIRMATIONS_ARRAYOFBRWHEADERPMS
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PMSCONFIRMATIONS_ARRAYOFBRWHEADERPMS
	::oWSBRWHEADERPMS      := {} // Array Of  PMSCONFIRMATIONS_BRWHEADERPMS():New()
Return

WSMETHOD CLONE WSCLIENT PMSCONFIRMATIONS_ARRAYOFBRWHEADERPMS
	Local oClone := PMSCONFIRMATIONS_ARRAYOFBRWHEADERPMS():NEW()
	oClone:oWSBRWHEADERPMS := NIL
	If ::oWSBRWHEADERPMS <> NIL 
		oClone:oWSBRWHEADERPMS := {}
		aEval( ::oWSBRWHEADERPMS , { |x| aadd( oClone:oWSBRWHEADERPMS , x:Clone() ) } )
	Endif 
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PMSCONFIRMATIONS_ARRAYOFBRWHEADERPMS
	Local nRElem1, oNodes1, nTElem1
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNodes1 :=  WSAdvValue( oResponse,"_BRWHEADERPMS","BRWHEADERPMS",{},NIL,.T.,"O",NIL,NIL) 
	nTElem1 := len(oNodes1)
	For nRElem1 := 1 to nTElem1 
		If !WSIsNilNode( oNodes1[nRElem1] )
			aadd(::oWSBRWHEADERPMS , PMSCONFIRMATIONS_BRWHEADERPMS():New() )
			::oWSBRWHEADERPMS[len(::oWSBRWHEADERPMS)]:SoapRecv(oNodes1[nRElem1])
		Endif
	Next
Return

// WSDL Data Structure MESSAGEVIEW

WSSTRUCT PMSCONFIRMATIONS_MESSAGEVIEW
	WSDATA   cMESSAGETEXT              AS string
	WSDATA   nMESSAGETYPE              AS float
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PMSCONFIRMATIONS_MESSAGEVIEW
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PMSCONFIRMATIONS_MESSAGEVIEW
Return

WSMETHOD CLONE WSCLIENT PMSCONFIRMATIONS_MESSAGEVIEW
	Local oClone := PMSCONFIRMATIONS_MESSAGEVIEW():NEW()
	oClone:cMESSAGETEXT         := ::cMESSAGETEXT
	oClone:nMESSAGETYPE         := ::nMESSAGETYPE
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PMSCONFIRMATIONS_MESSAGEVIEW
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::cMESSAGETEXT       :=  WSAdvValue( oResponse,"_MESSAGETEXT","string",NIL,"Property cMESSAGETEXT as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::nMESSAGETYPE       :=  WSAdvValue( oResponse,"_MESSAGETYPE","float",NIL,"Property nMESSAGETYPE as s:float on SOAP Response not found.",NIL,"N",NIL,NIL) 
Return

// WSDL Data Structure CONFIRMATIONVIEW

WSSTRUCT PMSCONFIRMATIONS_CONFIRMATIONVIEW
	WSDATA   nDBRECORD                 AS integer OPTIONAL
	WSDATA   cDELIVERYAUTHORIZATION    AS string OPTIONAL
	WSDATA   cFINALHOUR                AS string OPTIONAL
	WSDATA   cINITIALHOUR              AS string OPTIONAL
	WSDATA   oWSNOTES                  AS PMSCONFIRMATIONS_ARRAYOFNOTESVIEW OPTIONAL
	WSDATA   cOBS                      AS string OPTIONAL
	WSDATA   cOCORRENCECODE            AS string OPTIONAL
	WSDATA   cOCORRENCEDESCRIPTION     AS string OPTIONAL
	WSDATA   nPERCENTAGEEXECUTED       AS float OPTIONAL
	WSDATA   cPROJECTCODE              AS string OPTIONAL
	WSDATA   cPROJECTVERSION           AS string OPTIONAL
	WSDATA   nQUANTITYEXECUTED         AS float OPTIONAL
	WSDATA   dREFERENCEDATE            AS date OPTIONAL
	WSDATA   cTASKCODE                 AS string OPTIONAL
	WSDATA   cTASKDESCRIPTION          AS string OPTIONAL
	WSDATA   cTASKQTDTOT               AS string OPTIONAL
	WSDATA   cUSERCODE                 AS string OPTIONAL
	WSDATA   oWSUSERFIELDS             AS PMSCONFIRMATIONS_ARRAYOFUSERFIELD OPTIONAL
	WSDATA   cUSERNAME                 AS string OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPSEND
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PMSCONFIRMATIONS_CONFIRMATIONVIEW
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PMSCONFIRMATIONS_CONFIRMATIONVIEW
Return

WSMETHOD CLONE WSCLIENT PMSCONFIRMATIONS_CONFIRMATIONVIEW
	Local oClone := PMSCONFIRMATIONS_CONFIRMATIONVIEW():NEW()
	oClone:nDBRECORD            := ::nDBRECORD
	oClone:cDELIVERYAUTHORIZATION := ::cDELIVERYAUTHORIZATION
	oClone:cFINALHOUR           := ::cFINALHOUR
	oClone:cINITIALHOUR         := ::cINITIALHOUR
	oClone:oWSNOTES             := IIF(::oWSNOTES = NIL , NIL , ::oWSNOTES:Clone() )
	oClone:cOBS                 := ::cOBS
	oClone:cOCORRENCECODE       := ::cOCORRENCECODE
	oClone:cOCORRENCEDESCRIPTION := ::cOCORRENCEDESCRIPTION
	oClone:nPERCENTAGEEXECUTED  := ::nPERCENTAGEEXECUTED
	oClone:cPROJECTCODE         := ::cPROJECTCODE
	oClone:cPROJECTVERSION      := ::cPROJECTVERSION
	oClone:nQUANTITYEXECUTED    := ::nQUANTITYEXECUTED
	oClone:dREFERENCEDATE       := ::dREFERENCEDATE
	oClone:cTASKCODE            := ::cTASKCODE
	oClone:cTASKDESCRIPTION     := ::cTASKDESCRIPTION
	oClone:cTASKQTDTOT          := ::cTASKQTDTOT
	oClone:cUSERCODE            := ::cUSERCODE
	oClone:oWSUSERFIELDS        := IIF(::oWSUSERFIELDS = NIL , NIL , ::oWSUSERFIELDS:Clone() )
	oClone:cUSERNAME            := ::cUSERNAME
Return oClone

WSMETHOD SOAPSEND WSCLIENT PMSCONFIRMATIONS_CONFIRMATIONVIEW
	Local cSoap := ""
	cSoap += WSSoapValue("DBRECORD", ::nDBRECORD, ::nDBRECORD , "integer", .F. , .F., 0 , NIL, .F.,.F.) 
	cSoap += WSSoapValue("DELIVERYAUTHORIZATION", ::cDELIVERYAUTHORIZATION, ::cDELIVERYAUTHORIZATION , "string", .F. , .F., 0 , NIL, .F.,.F.) 
	cSoap += WSSoapValue("FINALHOUR", ::cFINALHOUR, ::cFINALHOUR , "string", .F. , .F., 0 , NIL, .F.,.F.) 
	cSoap += WSSoapValue("INITIALHOUR", ::cINITIALHOUR, ::cINITIALHOUR , "string", .F. , .F., 0 , NIL, .F.,.F.) 
	cSoap += WSSoapValue("NOTES", ::oWSNOTES, ::oWSNOTES , "ARRAYOFNOTESVIEW", .F. , .F., 0 , NIL, .F.,.F.) 
	cSoap += WSSoapValue("OBS", ::cOBS, ::cOBS , "string", .F. , .F., 0 , NIL, .F.,.F.) 
	cSoap += WSSoapValue("OCORRENCECODE", ::cOCORRENCECODE, ::cOCORRENCECODE , "string", .F. , .F., 0 , NIL, .F.,.F.) 
	cSoap += WSSoapValue("OCORRENCEDESCRIPTION", ::cOCORRENCEDESCRIPTION, ::cOCORRENCEDESCRIPTION , "string", .F. , .F., 0 , NIL, .F.,.F.) 
	cSoap += WSSoapValue("PERCENTAGEEXECUTED", ::nPERCENTAGEEXECUTED, ::nPERCENTAGEEXECUTED , "float", .F. , .F., 0 , NIL, .F.,.F.) 
	cSoap += WSSoapValue("PROJECTCODE", ::cPROJECTCODE, ::cPROJECTCODE , "string", .F. , .F., 0 , NIL, .F.,.F.) 
	cSoap += WSSoapValue("PROJECTVERSION", ::cPROJECTVERSION, ::cPROJECTVERSION , "string", .F. , .F., 0 , NIL, .F.,.F.) 
	cSoap += WSSoapValue("QUANTITYEXECUTED", ::nQUANTITYEXECUTED, ::nQUANTITYEXECUTED , "float", .F. , .F., 0 , NIL, .F.,.F.) 
	cSoap += WSSoapValue("REFERENCEDATE", ::dREFERENCEDATE, ::dREFERENCEDATE , "date", .F. , .F., 0 , NIL, .F.,.F.) 
	cSoap += WSSoapValue("TASKCODE", ::cTASKCODE, ::cTASKCODE , "string", .F. , .F., 0 , NIL, .F.,.F.) 
	cSoap += WSSoapValue("TASKDESCRIPTION", ::cTASKDESCRIPTION, ::cTASKDESCRIPTION , "string", .F. , .F., 0 , NIL, .F.,.F.) 
	cSoap += WSSoapValue("TASKQTDTOT", ::cTASKQTDTOT, ::cTASKQTDTOT , "string", .F. , .F., 0 , NIL, .F.,.F.) 
	cSoap += WSSoapValue("USERCODE", ::cUSERCODE, ::cUSERCODE , "string", .F. , .F., 0 , NIL, .F.,.F.) 
	cSoap += WSSoapValue("USERFIELDS", ::oWSUSERFIELDS, ::oWSUSERFIELDS , "ARRAYOFUSERFIELD", .F. , .F., 0 , NIL, .F.,.F.) 
	cSoap += WSSoapValue("USERNAME", ::cUSERNAME, ::cUSERNAME , "string", .F. , .F., 0 , NIL, .F.,.F.) 
Return cSoap

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PMSCONFIRMATIONS_CONFIRMATIONVIEW
	Local oNode5
	Local oNode18
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::nDBRECORD          :=  WSAdvValue( oResponse,"_DBRECORD","integer",NIL,NIL,NIL,"N",NIL,NIL) 
	::cDELIVERYAUTHORIZATION :=  WSAdvValue( oResponse,"_DELIVERYAUTHORIZATION","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cFINALHOUR         :=  WSAdvValue( oResponse,"_FINALHOUR","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cINITIALHOUR       :=  WSAdvValue( oResponse,"_INITIALHOUR","string",NIL,NIL,NIL,"S",NIL,NIL) 
	oNode5 :=  WSAdvValue( oResponse,"_NOTES","ARRAYOFNOTESVIEW",NIL,NIL,NIL,"O",NIL,NIL) 
	If oNode5 != NIL
		::oWSNOTES := PMSCONFIRMATIONS_ARRAYOFNOTESVIEW():New()
		::oWSNOTES:SoapRecv(oNode5)
	EndIf
	::cOBS               :=  WSAdvValue( oResponse,"_OBS","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cOCORRENCECODE     :=  WSAdvValue( oResponse,"_OCORRENCECODE","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cOCORRENCEDESCRIPTION :=  WSAdvValue( oResponse,"_OCORRENCEDESCRIPTION","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::nPERCENTAGEEXECUTED :=  WSAdvValue( oResponse,"_PERCENTAGEEXECUTED","float",NIL,NIL,NIL,"N",NIL,NIL) 
	::cPROJECTCODE       :=  WSAdvValue( oResponse,"_PROJECTCODE","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cPROJECTVERSION    :=  WSAdvValue( oResponse,"_PROJECTVERSION","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::nQUANTITYEXECUTED  :=  WSAdvValue( oResponse,"_QUANTITYEXECUTED","float",NIL,NIL,NIL,"N",NIL,NIL) 
	::dREFERENCEDATE     :=  WSAdvValue( oResponse,"_REFERENCEDATE","date",NIL,NIL,NIL,"D",NIL,NIL) 
	::cTASKCODE          :=  WSAdvValue( oResponse,"_TASKCODE","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cTASKDESCRIPTION   :=  WSAdvValue( oResponse,"_TASKDESCRIPTION","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cTASKQTDTOT        :=  WSAdvValue( oResponse,"_TASKQTDTOT","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cUSERCODE          :=  WSAdvValue( oResponse,"_USERCODE","string",NIL,NIL,NIL,"S",NIL,NIL) 
	oNode18 :=  WSAdvValue( oResponse,"_USERFIELDS","ARRAYOFUSERFIELD",NIL,NIL,NIL,"O",NIL,NIL) 
	If oNode18 != NIL
		::oWSUSERFIELDS := PMSCONFIRMATIONS_ARRAYOFUSERFIELD():New()
		::oWSUSERFIELDS:SoapRecv(oNode18)
	EndIf
	::cUSERNAME          :=  WSAdvValue( oResponse,"_USERNAME","string",NIL,NIL,NIL,"S",NIL,NIL) 
Return

// WSDL Data Structure CONFIRMATIONSLISTVIEW

WSSTRUCT PMSCONFIRMATIONS_CONFIRMATIONSLISTVIEW
	WSDATA   nDBRECORD                 AS integer OPTIONAL
	WSDATA   cDELIVERYAUTHORIZATION    AS string OPTIONAL
	WSDATA   cDELIVERYCOMBOBOXTEXT     AS string OPTIONAL
	WSDATA   cFINALHOUR                AS string OPTIONAL
	WSDATA   cINITIALHOUR              AS string OPTIONAL
	WSDATA   cOCORRENCECODE            AS string OPTIONAL
	WSDATA   cOCORRENCEDESCRIPTION     AS string OPTIONAL
	WSDATA   nPERCENTAGEEXECUTED       AS float OPTIONAL
	WSDATA   cPROJECTCODE              AS string OPTIONAL
	WSDATA   nQUANTITYEXECUTED         AS float OPTIONAL
	WSDATA   dREFERENCEDATE            AS date OPTIONAL
	WSDATA   cTASKCODE                 AS string OPTIONAL
	WSDATA   oWSUSERFIELDS             AS PMSCONFIRMATIONS_ARRAYOFUSERFIELD OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PMSCONFIRMATIONS_CONFIRMATIONSLISTVIEW
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PMSCONFIRMATIONS_CONFIRMATIONSLISTVIEW
Return

WSMETHOD CLONE WSCLIENT PMSCONFIRMATIONS_CONFIRMATIONSLISTVIEW
	Local oClone := PMSCONFIRMATIONS_CONFIRMATIONSLISTVIEW():NEW()
	oClone:nDBRECORD            := ::nDBRECORD
	oClone:cDELIVERYAUTHORIZATION := ::cDELIVERYAUTHORIZATION
	oClone:cDELIVERYCOMBOBOXTEXT := ::cDELIVERYCOMBOBOXTEXT
	oClone:cFINALHOUR           := ::cFINALHOUR
	oClone:cINITIALHOUR         := ::cINITIALHOUR
	oClone:cOCORRENCECODE       := ::cOCORRENCECODE
	oClone:cOCORRENCEDESCRIPTION := ::cOCORRENCEDESCRIPTION
	oClone:nPERCENTAGEEXECUTED  := ::nPERCENTAGEEXECUTED
	oClone:cPROJECTCODE         := ::cPROJECTCODE
	oClone:nQUANTITYEXECUTED    := ::nQUANTITYEXECUTED
	oClone:dREFERENCEDATE       := ::dREFERENCEDATE
	oClone:cTASKCODE            := ::cTASKCODE
	oClone:oWSUSERFIELDS        := IIF(::oWSUSERFIELDS = NIL , NIL , ::oWSUSERFIELDS:Clone() )
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PMSCONFIRMATIONS_CONFIRMATIONSLISTVIEW
	Local oNode13
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::nDBRECORD          :=  WSAdvValue( oResponse,"_DBRECORD","integer",NIL,NIL,NIL,"N",NIL,NIL) 
	::cDELIVERYAUTHORIZATION :=  WSAdvValue( oResponse,"_DELIVERYAUTHORIZATION","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cDELIVERYCOMBOBOXTEXT :=  WSAdvValue( oResponse,"_DELIVERYCOMBOBOXTEXT","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cFINALHOUR         :=  WSAdvValue( oResponse,"_FINALHOUR","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cINITIALHOUR       :=  WSAdvValue( oResponse,"_INITIALHOUR","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cOCORRENCECODE     :=  WSAdvValue( oResponse,"_OCORRENCECODE","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cOCORRENCEDESCRIPTION :=  WSAdvValue( oResponse,"_OCORRENCEDESCRIPTION","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::nPERCENTAGEEXECUTED :=  WSAdvValue( oResponse,"_PERCENTAGEEXECUTED","float",NIL,NIL,NIL,"N",NIL,NIL) 
	::cPROJECTCODE       :=  WSAdvValue( oResponse,"_PROJECTCODE","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::nQUANTITYEXECUTED  :=  WSAdvValue( oResponse,"_QUANTITYEXECUTED","float",NIL,NIL,NIL,"N",NIL,NIL) 
	::dREFERENCEDATE     :=  WSAdvValue( oResponse,"_REFERENCEDATE","date",NIL,NIL,NIL,"D",NIL,NIL) 
	::cTASKCODE          :=  WSAdvValue( oResponse,"_TASKCODE","string",NIL,NIL,NIL,"S",NIL,NIL) 
	oNode13 :=  WSAdvValue( oResponse,"_USERFIELDS","ARRAYOFUSERFIELD",NIL,NIL,NIL,"O",NIL,NIL) 
	If oNode13 != NIL
		::oWSUSERFIELDS := PMSCONFIRMATIONS_ARRAYOFUSERFIELD():New()
		::oWSUSERFIELDS:SoapRecv(oNode13)
	EndIf
Return

// WSDL Data Structure BRWHEADER

WSSTRUCT PMSCONFIRMATIONS_BRWHEADER
	WSDATA   cHEADERCOMBOBOX           AS string OPTIONAL
	WSDATA   nHEADERDEC                AS integer
	WSDATA   cHEADERF3                 AS string OPTIONAL
	WSDATA   cHEADERFIELD              AS string
	WSDATA   lHEADEROBLIG              AS boolean OPTIONAL
	WSDATA   cHEADERPICTURE            AS string
	WSDATA   nHEADERSIZE               AS integer
	WSDATA   cHEADERTITLE              AS string
	WSDATA   cHEADERTYPE               AS string
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PMSCONFIRMATIONS_BRWHEADER
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PMSCONFIRMATIONS_BRWHEADER
Return

WSMETHOD CLONE WSCLIENT PMSCONFIRMATIONS_BRWHEADER
	Local oClone := PMSCONFIRMATIONS_BRWHEADER():NEW()
	oClone:cHEADERCOMBOBOX      := ::cHEADERCOMBOBOX
	oClone:nHEADERDEC           := ::nHEADERDEC
	oClone:cHEADERF3            := ::cHEADERF3
	oClone:cHEADERFIELD         := ::cHEADERFIELD
	oClone:lHEADEROBLIG         := ::lHEADEROBLIG
	oClone:cHEADERPICTURE       := ::cHEADERPICTURE
	oClone:nHEADERSIZE          := ::nHEADERSIZE
	oClone:cHEADERTITLE         := ::cHEADERTITLE
	oClone:cHEADERTYPE          := ::cHEADERTYPE
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PMSCONFIRMATIONS_BRWHEADER
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::cHEADERCOMBOBOX    :=  WSAdvValue( oResponse,"_HEADERCOMBOBOX","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::nHEADERDEC         :=  WSAdvValue( oResponse,"_HEADERDEC","integer",NIL,"Property nHEADERDEC as s:integer on SOAP Response not found.",NIL,"N",NIL,NIL) 
	::cHEADERF3          :=  WSAdvValue( oResponse,"_HEADERF3","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cHEADERFIELD       :=  WSAdvValue( oResponse,"_HEADERFIELD","string",NIL,"Property cHEADERFIELD as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::lHEADEROBLIG       :=  WSAdvValue( oResponse,"_HEADEROBLIG","boolean",NIL,NIL,NIL,"L",NIL,NIL) 
	::cHEADERPICTURE     :=  WSAdvValue( oResponse,"_HEADERPICTURE","string",NIL,"Property cHEADERPICTURE as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::nHEADERSIZE        :=  WSAdvValue( oResponse,"_HEADERSIZE","integer",NIL,"Property nHEADERSIZE as s:integer on SOAP Response not found.",NIL,"N",NIL,NIL) 
	::cHEADERTITLE       :=  WSAdvValue( oResponse,"_HEADERTITLE","string",NIL,"Property cHEADERTITLE as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cHEADERTYPE        :=  WSAdvValue( oResponse,"_HEADERTYPE","string",NIL,"Property cHEADERTYPE as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
Return

// WSDL Data Structure BRWHEADERPMS

WSSTRUCT PMSCONFIRMATIONS_BRWHEADERPMS
	WSDATA   cEDITABLE                 AS string OPTIONAL
	WSDATA   cHEADERCOMBOBOX           AS string OPTIONAL
	WSDATA   nHEADERDEC                AS integer OPTIONAL
	WSDATA   cHEADERF3                 AS string OPTIONAL
	WSDATA   cHEADERFIELD              AS string OPTIONAL
	WSDATA   cHEADERFOLDER             AS string OPTIONAL
	WSDATA   lHEADEROBLIG              AS boolean OPTIONAL
	WSDATA   cHEADERORDER              AS string OPTIONAL
	WSDATA   cHEADERPICTURE            AS string OPTIONAL
	WSDATA   nHEADERSIZE               AS integer OPTIONAL
	WSDATA   cHEADERTITLE              AS string OPTIONAL
	WSDATA   cHEADERTYPE               AS string OPTIONAL
	WSDATA   cHEADERTYPE2              AS string OPTIONAL
	WSDATA   cINITIALVALUE             AS string OPTIONAL
	WSDATA   cPROPRIETYNAME            AS string OPTIONAL
	WSDATA   lUSERFIELD                AS boolean OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PMSCONFIRMATIONS_BRWHEADERPMS
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PMSCONFIRMATIONS_BRWHEADERPMS
Return

WSMETHOD CLONE WSCLIENT PMSCONFIRMATIONS_BRWHEADERPMS
	Local oClone := PMSCONFIRMATIONS_BRWHEADERPMS():NEW()
	oClone:cEDITABLE            := ::cEDITABLE
	oClone:cHEADERCOMBOBOX      := ::cHEADERCOMBOBOX
	oClone:nHEADERDEC           := ::nHEADERDEC
	oClone:cHEADERF3            := ::cHEADERF3
	oClone:cHEADERFIELD         := ::cHEADERFIELD
	oClone:cHEADERFOLDER        := ::cHEADERFOLDER
	oClone:lHEADEROBLIG         := ::lHEADEROBLIG
	oClone:cHEADERORDER         := ::cHEADERORDER
	oClone:cHEADERPICTURE       := ::cHEADERPICTURE
	oClone:nHEADERSIZE          := ::nHEADERSIZE
	oClone:cHEADERTITLE         := ::cHEADERTITLE
	oClone:cHEADERTYPE          := ::cHEADERTYPE
	oClone:cHEADERTYPE2         := ::cHEADERTYPE2
	oClone:cINITIALVALUE        := ::cINITIALVALUE
	oClone:cPROPRIETYNAME       := ::cPROPRIETYNAME
	oClone:lUSERFIELD           := ::lUSERFIELD
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PMSCONFIRMATIONS_BRWHEADERPMS
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::cEDITABLE          :=  WSAdvValue( oResponse,"_EDITABLE","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cHEADERCOMBOBOX    :=  WSAdvValue( oResponse,"_HEADERCOMBOBOX","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::nHEADERDEC         :=  WSAdvValue( oResponse,"_HEADERDEC","integer",NIL,NIL,NIL,"N",NIL,NIL) 
	::cHEADERF3          :=  WSAdvValue( oResponse,"_HEADERF3","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cHEADERFIELD       :=  WSAdvValue( oResponse,"_HEADERFIELD","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cHEADERFOLDER      :=  WSAdvValue( oResponse,"_HEADERFOLDER","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::lHEADEROBLIG       :=  WSAdvValue( oResponse,"_HEADEROBLIG","boolean",NIL,NIL,NIL,"L",NIL,NIL) 
	::cHEADERORDER       :=  WSAdvValue( oResponse,"_HEADERORDER","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cHEADERPICTURE     :=  WSAdvValue( oResponse,"_HEADERPICTURE","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::nHEADERSIZE        :=  WSAdvValue( oResponse,"_HEADERSIZE","integer",NIL,NIL,NIL,"N",NIL,NIL) 
	::cHEADERTITLE       :=  WSAdvValue( oResponse,"_HEADERTITLE","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cHEADERTYPE        :=  WSAdvValue( oResponse,"_HEADERTYPE","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cHEADERTYPE2       :=  WSAdvValue( oResponse,"_HEADERTYPE2","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cINITIALVALUE      :=  WSAdvValue( oResponse,"_INITIALVALUE","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cPROPRIETYNAME     :=  WSAdvValue( oResponse,"_PROPRIETYNAME","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::lUSERFIELD         :=  WSAdvValue( oResponse,"_USERFIELD","boolean",NIL,NIL,NIL,"L",NIL,NIL) 
Return

// WSDL Data Structure ARRAYOFNOTESVIEW

WSSTRUCT PMSCONFIRMATIONS_ARRAYOFNOTESVIEW
	WSDATA   oWSNOTESVIEW              AS PMSCONFIRMATIONS_NOTESVIEW OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPSEND
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PMSCONFIRMATIONS_ARRAYOFNOTESVIEW
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PMSCONFIRMATIONS_ARRAYOFNOTESVIEW
	::oWSNOTESVIEW         := {} // Array Of  PMSCONFIRMATIONS_NOTESVIEW():New()
Return

WSMETHOD CLONE WSCLIENT PMSCONFIRMATIONS_ARRAYOFNOTESVIEW
	Local oClone := PMSCONFIRMATIONS_ARRAYOFNOTESVIEW():NEW()
	oClone:oWSNOTESVIEW := NIL
	If ::oWSNOTESVIEW <> NIL 
		oClone:oWSNOTESVIEW := {}
		aEval( ::oWSNOTESVIEW , { |x| aadd( oClone:oWSNOTESVIEW , x:Clone() ) } )
	Endif 
Return oClone

WSMETHOD SOAPSEND WSCLIENT PMSCONFIRMATIONS_ARRAYOFNOTESVIEW
	Local cSoap := ""
	aEval( ::oWSNOTESVIEW , {|x| cSoap := cSoap  +  WSSoapValue("NOTESVIEW", x , x , "NOTESVIEW", .F. , .F., 0 , NIL, .F.,.F.)  } ) 
Return cSoap

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PMSCONFIRMATIONS_ARRAYOFNOTESVIEW
	Local nRElem1, oNodes1, nTElem1
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNodes1 :=  WSAdvValue( oResponse,"_NOTESVIEW","NOTESVIEW",{},NIL,.T.,"O",NIL,NIL) 
	nTElem1 := len(oNodes1)
	For nRElem1 := 1 to nTElem1 
		If !WSIsNilNode( oNodes1[nRElem1] )
			aadd(::oWSNOTESVIEW , PMSCONFIRMATIONS_NOTESVIEW():New() )
			::oWSNOTESVIEW[len(::oWSNOTESVIEW)]:SoapRecv(oNodes1[nRElem1])
		Endif
	Next
Return

// WSDL Data Structure ARRAYOFUSERFIELD

WSSTRUCT PMSCONFIRMATIONS_ARRAYOFUSERFIELD
	WSDATA   oWSUSERFIELD              AS PMSCONFIRMATIONS_USERFIELD OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPSEND
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PMSCONFIRMATIONS_ARRAYOFUSERFIELD
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PMSCONFIRMATIONS_ARRAYOFUSERFIELD
	::oWSUSERFIELD         := {} // Array Of  PMSCONFIRMATIONS_USERFIELD():New()
Return

WSMETHOD CLONE WSCLIENT PMSCONFIRMATIONS_ARRAYOFUSERFIELD
	Local oClone := PMSCONFIRMATIONS_ARRAYOFUSERFIELD():NEW()
	oClone:oWSUSERFIELD := NIL
	If ::oWSUSERFIELD <> NIL 
		oClone:oWSUSERFIELD := {}
		aEval( ::oWSUSERFIELD , { |x| aadd( oClone:oWSUSERFIELD , x:Clone() ) } )
	Endif 
Return oClone

WSMETHOD SOAPSEND WSCLIENT PMSCONFIRMATIONS_ARRAYOFUSERFIELD
	Local cSoap := ""
	aEval( ::oWSUSERFIELD , {|x| cSoap := cSoap  +  WSSoapValue("USERFIELD", x , x , "USERFIELD", .F. , .F., 0 , NIL, .F.,.F.)  } ) 
Return cSoap

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PMSCONFIRMATIONS_ARRAYOFUSERFIELD
	Local nRElem1, oNodes1, nTElem1
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNodes1 :=  WSAdvValue( oResponse,"_USERFIELD","USERFIELD",{},NIL,.T.,"O",NIL,NIL) 
	nTElem1 := len(oNodes1)
	For nRElem1 := 1 to nTElem1 
		If !WSIsNilNode( oNodes1[nRElem1] )
			aadd(::oWSUSERFIELD , PMSCONFIRMATIONS_USERFIELD():New() )
			::oWSUSERFIELD[len(::oWSUSERFIELD)]:SoapRecv(oNodes1[nRElem1])
		Endif
	Next
Return

// WSDL Data Structure NOTESVIEW

WSSTRUCT PMSCONFIRMATIONS_NOTESVIEW
	WSDATA   cNOTES                    AS string OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPSEND
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PMSCONFIRMATIONS_NOTESVIEW
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PMSCONFIRMATIONS_NOTESVIEW
Return

WSMETHOD CLONE WSCLIENT PMSCONFIRMATIONS_NOTESVIEW
	Local oClone := PMSCONFIRMATIONS_NOTESVIEW():NEW()
	oClone:cNOTES               := ::cNOTES
Return oClone

WSMETHOD SOAPSEND WSCLIENT PMSCONFIRMATIONS_NOTESVIEW
	Local cSoap := ""
	cSoap += WSSoapValue("NOTES", ::cNOTES, ::cNOTES , "string", .F. , .F., 0 , NIL, .F.,.F.) 
Return cSoap

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PMSCONFIRMATIONS_NOTESVIEW
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::cNOTES             :=  WSAdvValue( oResponse,"_NOTES","string",NIL,NIL,NIL,"S",NIL,NIL) 
Return

// WSDL Data Structure USERFIELD

WSSTRUCT PMSCONFIRMATIONS_USERFIELD
	WSDATA   cUSERCOMBOBOX             AS string OPTIONAL
	WSDATA   nUSERDEC                  AS integer OPTIONAL
	WSDATA   cUSERF3                   AS string OPTIONAL
	WSDATA   cUSERNAME                 AS string
	WSDATA   lUSEROBLIG                AS boolean OPTIONAL
	WSDATA   cUSERPICTURE              AS string OPTIONAL
	WSDATA   nUSERSIZE                 AS integer OPTIONAL
	WSDATA   cUSERTAG                  AS string OPTIONAL
	WSDATA   cUSERTITLE                AS string OPTIONAL
	WSDATA   cUSERTYPE                 AS string
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPSEND
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PMSCONFIRMATIONS_USERFIELD
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PMSCONFIRMATIONS_USERFIELD
Return

WSMETHOD CLONE WSCLIENT PMSCONFIRMATIONS_USERFIELD
	Local oClone := PMSCONFIRMATIONS_USERFIELD():NEW()
	oClone:cUSERCOMBOBOX        := ::cUSERCOMBOBOX
	oClone:nUSERDEC             := ::nUSERDEC
	oClone:cUSERF3              := ::cUSERF3
	oClone:cUSERNAME            := ::cUSERNAME
	oClone:lUSEROBLIG           := ::lUSEROBLIG
	oClone:cUSERPICTURE         := ::cUSERPICTURE
	oClone:nUSERSIZE            := ::nUSERSIZE
	oClone:cUSERTAG             := ::cUSERTAG
	oClone:cUSERTITLE           := ::cUSERTITLE
	oClone:cUSERTYPE            := ::cUSERTYPE
Return oClone

WSMETHOD SOAPSEND WSCLIENT PMSCONFIRMATIONS_USERFIELD
	Local cSoap := ""
	cSoap += WSSoapValue("USERCOMBOBOX", ::cUSERCOMBOBOX, ::cUSERCOMBOBOX , "string", .F. , .F., 0 , NIL, .F.,.F.) 
	cSoap += WSSoapValue("USERDEC", ::nUSERDEC, ::nUSERDEC , "integer", .F. , .F., 0 , NIL, .F.,.F.) 
	cSoap += WSSoapValue("USERF3", ::cUSERF3, ::cUSERF3 , "string", .F. , .F., 0 , NIL, .F.,.F.) 
	cSoap += WSSoapValue("USERNAME", ::cUSERNAME, ::cUSERNAME , "string", .T. , .F., 0 , NIL, .F.,.F.) 
	cSoap += WSSoapValue("USEROBLIG", ::lUSEROBLIG, ::lUSEROBLIG , "boolean", .F. , .F., 0 , NIL, .F.,.F.) 
	cSoap += WSSoapValue("USERPICTURE", ::cUSERPICTURE, ::cUSERPICTURE , "string", .F. , .F., 0 , NIL, .F.,.F.) 
	cSoap += WSSoapValue("USERSIZE", ::nUSERSIZE, ::nUSERSIZE , "integer", .F. , .F., 0 , NIL, .F.,.F.) 
	cSoap += WSSoapValue("USERTAG", ::cUSERTAG, ::cUSERTAG , "string", .F. , .F., 0 , NIL, .F.,.F.) 
	cSoap += WSSoapValue("USERTITLE", ::cUSERTITLE, ::cUSERTITLE , "string", .F. , .F., 0 , NIL, .F.,.F.) 
	cSoap += WSSoapValue("USERTYPE", ::cUSERTYPE, ::cUSERTYPE , "string", .T. , .F., 0 , NIL, .F.,.F.) 
Return cSoap

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PMSCONFIRMATIONS_USERFIELD
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::cUSERCOMBOBOX      :=  WSAdvValue( oResponse,"_USERCOMBOBOX","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::nUSERDEC           :=  WSAdvValue( oResponse,"_USERDEC","integer",NIL,NIL,NIL,"N",NIL,NIL) 
	::cUSERF3            :=  WSAdvValue( oResponse,"_USERF3","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cUSERNAME          :=  WSAdvValue( oResponse,"_USERNAME","string",NIL,"Property cUSERNAME as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::lUSEROBLIG         :=  WSAdvValue( oResponse,"_USEROBLIG","boolean",NIL,NIL,NIL,"L",NIL,NIL) 
	::cUSERPICTURE       :=  WSAdvValue( oResponse,"_USERPICTURE","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::nUSERSIZE          :=  WSAdvValue( oResponse,"_USERSIZE","integer",NIL,NIL,NIL,"N",NIL,NIL) 
	::cUSERTAG           :=  WSAdvValue( oResponse,"_USERTAG","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cUSERTITLE         :=  WSAdvValue( oResponse,"_USERTITLE","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cUSERTYPE          :=  WSAdvValue( oResponse,"_USERTYPE","string",NIL,"Property cUSERTYPE as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
Return


