#INCLUDE "PROTHEUS.CH"
#INCLUDE "APWEBSRV.CH"

/* ===============================================================================
WSDL Location    http://localhost:7087/ws/RHAPDCONSOLIDATED.apw?WSDL
Gerado em        07/05/16 11:36:10
Observações      Código-Fonte gerado por ADVPL WSDL Client 1.120703
                 Alterações neste arquivo podem causar funcionamento incorreto
                 e serão perdidas caso o código-fonte seja gerado novamente.
=============================================================================== */

User Function _BMMGVEP ; Return  // "dummy" function - Internal Use 

/* -------------------------------------------------------------------------------
WSDL Service WSRHAPDCONSOLIDATED
------------------------------------------------------------------------------- */

WSCLIENT WSRHAPDCONSOLIDATED

	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD RESET
	WSMETHOD CLONE
	WSMETHOD GETCONSOLIDATED
	WSMETHOD GETPOLICIES
	WSMETHOD GETSTRUCTRANKING

	WSDATA   _URL                      AS String
	WSDATA   _HEADOUT                  AS Array of String
	WSDATA   _COOKIES                  AS Array of String
	WSDATA   cPOLICY                   AS string
	WSDATA   cPARTICIPANTID            AS string
	WSDATA   oWSGETCONSOLIDATEDRESULT  AS RHAPDCONSOLIDATED_TCONSOLIDATEDDATA
	WSDATA   oWSGETPOLICIESRESULT      AS RHAPDCONSOLIDATED_TPOLICYDATA
	WSDATA   cTYPEORG                  AS string
	WSDATA   cVISION                   AS string
	WSDATA   cEMPLOYEEFIL              AS string
	WSDATA   cREGISTRATION             AS string
	WSDATA   nPAGE                     AS integer
	WSDATA   nPAGELENGTH               AS integer
	WSDATA   cFILTERVALUE              AS string
	WSDATA   cFILTERFIELD              AS string
	WSDATA   cRANKINGORDER             AS string
	WSDATA   oWSGETSTRUCTRANKINGRESULT AS RHAPDCONSOLIDATED_TEMPLOYEEDATA

ENDWSCLIENT

WSMETHOD NEW WSCLIENT WSRHAPDCONSOLIDATED
::Init()
If !FindFunction("XMLCHILDEX")
	UserException("O Código-Fonte Client atual requer os executáveis do Protheus Build [7.00.131227A-20160510 NG] ou superior. Atualize o Protheus ou gere o Código-Fonte novamente utilizando o Build atual.")
EndIf
Return Self

WSMETHOD INIT WSCLIENT WSRHAPDCONSOLIDATED
	::oWSGETCONSOLIDATEDRESULT := RHAPDCONSOLIDATED_TCONSOLIDATEDDATA():New()
	::oWSGETPOLICIESRESULT := RHAPDCONSOLIDATED_TPOLICYDATA():New()
	::oWSGETSTRUCTRANKINGRESULT := RHAPDCONSOLIDATED_TEMPLOYEEDATA():New()
Return

WSMETHOD RESET WSCLIENT WSRHAPDCONSOLIDATED
	::cPOLICY            := NIL 
	::cPARTICIPANTID     := NIL 
	::oWSGETCONSOLIDATEDRESULT := NIL 
	::oWSGETPOLICIESRESULT := NIL 
	::cTYPEORG           := NIL 
	::cVISION            := NIL 
	::cEMPLOYEEFIL       := NIL 
	::cREGISTRATION      := NIL 
	::nPAGE              := NIL 
	::nPAGELENGTH        := NIL 
	::cFILTERVALUE       := NIL 
	::cFILTERFIELD       := NIL 
	::cRANKINGORDER      := NIL 
	::oWSGETSTRUCTRANKINGRESULT := NIL 
	::Init()
Return

WSMETHOD CLONE WSCLIENT WSRHAPDCONSOLIDATED
Local oClone := WSRHAPDCONSOLIDATED():New()
	oClone:_URL          := ::_URL 
	oClone:cPOLICY       := ::cPOLICY
	oClone:cPARTICIPANTID := ::cPARTICIPANTID
	oClone:oWSGETCONSOLIDATEDRESULT :=  IIF(::oWSGETCONSOLIDATEDRESULT = NIL , NIL ,::oWSGETCONSOLIDATEDRESULT:Clone() )
	oClone:oWSGETPOLICIESRESULT :=  IIF(::oWSGETPOLICIESRESULT = NIL , NIL ,::oWSGETPOLICIESRESULT:Clone() )
	oClone:cTYPEORG      := ::cTYPEORG
	oClone:cVISION       := ::cVISION
	oClone:cEMPLOYEEFIL  := ::cEMPLOYEEFIL
	oClone:cREGISTRATION := ::cREGISTRATION
	oClone:nPAGE         := ::nPAGE
	oClone:nPAGELENGTH   := ::nPAGELENGTH
	oClone:cFILTERVALUE  := ::cFILTERVALUE
	oClone:cFILTERFIELD  := ::cFILTERFIELD
	oClone:cRANKINGORDER := ::cRANKINGORDER
	oClone:oWSGETSTRUCTRANKINGRESULT :=  IIF(::oWSGETSTRUCTRANKINGRESULT = NIL , NIL ,::oWSGETSTRUCTRANKINGRESULT:Clone() )
Return oClone

// WSDL Method GETCONSOLIDATED of Service WSRHAPDCONSOLIDATED

WSMETHOD GETCONSOLIDATED WSSEND cPOLICY,cPARTICIPANTID WSRECEIVE oWSGETCONSOLIDATEDRESULT WSCLIENT WSRHAPDCONSOLIDATED
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<GETCONSOLIDATED xmlns="http://localhost:7087/">'
cSoap += WSSoapValue("POLICY", ::cPOLICY, cPOLICY , "string", .F. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("PARTICIPANTID", ::cPARTICIPANTID, cPARTICIPANTID , "string", .F. , .F., 0 , NIL, .F.) 
cSoap += "</GETCONSOLIDATED>"

oXmlRet := SvcSoapCall(	Self,cSoap,; 
	"http://localhost:7087/GETCONSOLIDATED",; 
	"DOCUMENT","http://localhost:7087/",,"1.031217",; 
	"http://localhost:7087/ws/RHAPDCONSOLIDATED.apw")

::Init()
::oWSGETCONSOLIDATEDRESULT:SoapRecv( WSAdvValue( oXmlRet,"_GETCONSOLIDATEDRESPONSE:_GETCONSOLIDATEDRESULT","TCONSOLIDATEDDATA",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.

// WSDL Method GETPOLICIES of Service WSRHAPDCONSOLIDATED

WSMETHOD GETPOLICIES WSSEND cPOLICY WSRECEIVE oWSGETPOLICIESRESULT WSCLIENT WSRHAPDCONSOLIDATED
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<GETPOLICIES xmlns="http://localhost:7087/">'
cSoap += WSSoapValue("POLICY", ::cPOLICY, cPOLICY , "string", .F. , .F., 0 , NIL, .F.) 
cSoap += "</GETPOLICIES>"

oXmlRet := SvcSoapCall(	Self,cSoap,; 
	"http://localhost:7087/GETPOLICIES",; 
	"DOCUMENT","http://localhost:7087/",,"1.031217",; 
	"http://localhost:7087/ws/RHAPDCONSOLIDATED.apw")

::Init()
::oWSGETPOLICIESRESULT:SoapRecv( WSAdvValue( oXmlRet,"_GETPOLICIESRESPONSE:_GETPOLICIESRESULT","TPOLICYDATA",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.

// WSDL Method GETSTRUCTRANKING of Service WSRHAPDCONSOLIDATED

WSMETHOD GETSTRUCTRANKING WSSEND cPOLICY,cPARTICIPANTID,cTYPEORG,cVISION,cEMPLOYEEFIL,cREGISTRATION,nPAGE,nPAGELENGTH,cFILTERVALUE,cFILTERFIELD,cRANKINGORDER WSRECEIVE oWSGETSTRUCTRANKINGRESULT WSCLIENT WSRHAPDCONSOLIDATED
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<GETSTRUCTRANKING xmlns="http://localhost:7087/">'
cSoap += WSSoapValue("POLICY", ::cPOLICY, cPOLICY , "string", .F. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("PARTICIPANTID", ::cPARTICIPANTID, cPARTICIPANTID , "string", .F. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("TYPEORG", ::cTYPEORG, cTYPEORG , "string", .F. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("VISION", ::cVISION, cVISION , "string", .F. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("EMPLOYEEFIL", ::cEMPLOYEEFIL, cEMPLOYEEFIL , "string", .F. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("REGISTRATION", ::cREGISTRATION, cREGISTRATION , "string", .F. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("PAGE", ::nPAGE, nPAGE , "integer", .F. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("PAGELENGTH", ::nPAGELENGTH, nPAGELENGTH , "integer", .F. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("FILTERVALUE", ::cFILTERVALUE, cFILTERVALUE , "string", .F. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("FILTERFIELD", ::cFILTERFIELD, cFILTERFIELD , "string", .F. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("RANKINGORDER", ::cRANKINGORDER, cRANKINGORDER , "string", .F. , .F., 0 , NIL, .F.) 
cSoap += "</GETSTRUCTRANKING>"

oXmlRet := SvcSoapCall(	Self,cSoap,; 
	"http://localhost:7087/GETSTRUCTRANKING",; 
	"DOCUMENT","http://localhost:7087/",,"1.031217",; 
	"http://localhost:7087/ws/RHAPDCONSOLIDATED.apw")

::Init()
::oWSGETSTRUCTRANKINGRESULT:SoapRecv( WSAdvValue( oXmlRet,"_GETSTRUCTRANKINGRESPONSE:_GETSTRUCTRANKINGRESULT","TEMPLOYEEDATA",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.


// WSDL Data Structure TCONSOLIDATEDDATA

WSSTRUCT RHAPDCONSOLIDATED_TCONSOLIDATEDDATA
	WSDATA   oWSITEMSOFCONSOLIDATED    AS RHAPDCONSOLIDATED_ARRAYOFCONSOLIDATEDRESULT OPTIONAL
	WSDATA   nITEMSTOTALASSESSMENTS    AS integer OPTIONAL
	WSDATA   nITEMSTOTALGOALS          AS integer OPTIONAL
	WSDATA   nITEMSTOTALOTHERS         AS integer OPTIONAL
	WSDATA   cNAME                     AS string
	WSDATA   cPARTICIPANT              AS string OPTIONAL
	WSDATA   cPOLICYDESC               AS string OPTIONAL
	WSDATA   cPOLICYID                 AS string
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT RHAPDCONSOLIDATED_TCONSOLIDATEDDATA
	::Init()
Return Self

WSMETHOD INIT WSCLIENT RHAPDCONSOLIDATED_TCONSOLIDATEDDATA
Return

WSMETHOD CLONE WSCLIENT RHAPDCONSOLIDATED_TCONSOLIDATEDDATA
	Local oClone := RHAPDCONSOLIDATED_TCONSOLIDATEDDATA():NEW()
	oClone:oWSITEMSOFCONSOLIDATED := IIF(::oWSITEMSOFCONSOLIDATED = NIL , NIL , ::oWSITEMSOFCONSOLIDATED:Clone() )
	oClone:nITEMSTOTALASSESSMENTS := ::nITEMSTOTALASSESSMENTS
	oClone:nITEMSTOTALGOALS     := ::nITEMSTOTALGOALS
	oClone:nITEMSTOTALOTHERS    := ::nITEMSTOTALOTHERS
	oClone:cNAME                := ::cNAME
	oClone:cPARTICIPANT         := ::cPARTICIPANT
	oClone:cPOLICYDESC          := ::cPOLICYDESC
	oClone:cPOLICYID            := ::cPOLICYID
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT RHAPDCONSOLIDATED_TCONSOLIDATEDDATA
	Local oNode1
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNode1 :=  WSAdvValue( oResponse,"_ITEMSOFCONSOLIDATED","ARRAYOFCONSOLIDATEDRESULT",NIL,NIL,NIL,"O",NIL,NIL) 
	If oNode1 != NIL
		::oWSITEMSOFCONSOLIDATED := RHAPDCONSOLIDATED_ARRAYOFCONSOLIDATEDRESULT():New()
		::oWSITEMSOFCONSOLIDATED:SoapRecv(oNode1)
	EndIf
	::nITEMSTOTALASSESSMENTS :=  WSAdvValue( oResponse,"_ITEMSTOTALASSESSMENTS","integer",NIL,NIL,NIL,"N",NIL,NIL) 
	::nITEMSTOTALGOALS   :=  WSAdvValue( oResponse,"_ITEMSTOTALGOALS","integer",NIL,NIL,NIL,"N",NIL,NIL) 
	::nITEMSTOTALOTHERS  :=  WSAdvValue( oResponse,"_ITEMSTOTALOTHERS","integer",NIL,NIL,NIL,"N",NIL,NIL) 
	::cNAME              :=  WSAdvValue( oResponse,"_NAME","string",NIL,"Property cNAME as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cPARTICIPANT       :=  WSAdvValue( oResponse,"_PARTICIPANT","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cPOLICYDESC        :=  WSAdvValue( oResponse,"_POLICYDESC","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cPOLICYID          :=  WSAdvValue( oResponse,"_POLICYID","string",NIL,"Property cPOLICYID as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
Return

// WSDL Data Structure TPOLICYDATA

WSSTRUCT RHAPDCONSOLIDATED_TPOLICYDATA
	WSDATA   oWSITEMSOFPOLICY          AS RHAPDCONSOLIDATED_ARRAYOFPOLICYCABEC OPTIONAL
	WSDATA   nITEMSTOTAL               AS integer OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT RHAPDCONSOLIDATED_TPOLICYDATA
	::Init()
Return Self

WSMETHOD INIT WSCLIENT RHAPDCONSOLIDATED_TPOLICYDATA
Return

WSMETHOD CLONE WSCLIENT RHAPDCONSOLIDATED_TPOLICYDATA
	Local oClone := RHAPDCONSOLIDATED_TPOLICYDATA():NEW()
	oClone:oWSITEMSOFPOLICY     := IIF(::oWSITEMSOFPOLICY = NIL , NIL , ::oWSITEMSOFPOLICY:Clone() )
	oClone:nITEMSTOTAL          := ::nITEMSTOTAL
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT RHAPDCONSOLIDATED_TPOLICYDATA
	Local oNode1
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNode1 :=  WSAdvValue( oResponse,"_ITEMSOFPOLICY","ARRAYOFPOLICYCABEC",NIL,NIL,NIL,"O",NIL,NIL) 
	If oNode1 != NIL
		::oWSITEMSOFPOLICY := RHAPDCONSOLIDATED_ARRAYOFPOLICYCABEC():New()
		::oWSITEMSOFPOLICY:SoapRecv(oNode1)
	EndIf
	::nITEMSTOTAL        :=  WSAdvValue( oResponse,"_ITEMSTOTAL","integer",NIL,NIL,NIL,"N",NIL,NIL) 
Return

// WSDL Data Structure TEMPLOYEEDATA

WSSTRUCT RHAPDCONSOLIDATED_TEMPLOYEEDATA
	WSDATA   oWSLISTOFEMPLOYEE         AS RHAPDCONSOLIDATED_ARRAYOFDATAEMPLOYEE OPTIONAL
	WSDATA   nPAGESTOTAL               AS integer OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT RHAPDCONSOLIDATED_TEMPLOYEEDATA
	::Init()
Return Self

WSMETHOD INIT WSCLIENT RHAPDCONSOLIDATED_TEMPLOYEEDATA
Return

WSMETHOD CLONE WSCLIENT RHAPDCONSOLIDATED_TEMPLOYEEDATA
	Local oClone := RHAPDCONSOLIDATED_TEMPLOYEEDATA():NEW()
	oClone:oWSLISTOFEMPLOYEE    := IIF(::oWSLISTOFEMPLOYEE = NIL , NIL , ::oWSLISTOFEMPLOYEE:Clone() )
	oClone:nPAGESTOTAL          := ::nPAGESTOTAL
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT RHAPDCONSOLIDATED_TEMPLOYEEDATA
	Local oNode1
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNode1 :=  WSAdvValue( oResponse,"_LISTOFEMPLOYEE","ARRAYOFDATAEMPLOYEE",NIL,NIL,NIL,"O",NIL,NIL) 
	If oNode1 != NIL
		::oWSLISTOFEMPLOYEE := RHAPDCONSOLIDATED_ARRAYOFDATAEMPLOYEE():New()
		::oWSLISTOFEMPLOYEE:SoapRecv(oNode1)
	EndIf
	::nPAGESTOTAL        :=  WSAdvValue( oResponse,"_PAGESTOTAL","integer",NIL,NIL,NIL,"N",NIL,NIL) 
Return

// WSDL Data Structure ARRAYOFCONSOLIDATEDRESULT

WSSTRUCT RHAPDCONSOLIDATED_ARRAYOFCONSOLIDATEDRESULT
	WSDATA   oWSCONSOLIDATEDRESULT     AS RHAPDCONSOLIDATED_CONSOLIDATEDRESULT OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT RHAPDCONSOLIDATED_ARRAYOFCONSOLIDATEDRESULT
	::Init()
Return Self

WSMETHOD INIT WSCLIENT RHAPDCONSOLIDATED_ARRAYOFCONSOLIDATEDRESULT
	::oWSCONSOLIDATEDRESULT := {} // Array Of  RHAPDCONSOLIDATED_CONSOLIDATEDRESULT():New()
Return

WSMETHOD CLONE WSCLIENT RHAPDCONSOLIDATED_ARRAYOFCONSOLIDATEDRESULT
	Local oClone := RHAPDCONSOLIDATED_ARRAYOFCONSOLIDATEDRESULT():NEW()
	oClone:oWSCONSOLIDATEDRESULT := NIL
	If ::oWSCONSOLIDATEDRESULT <> NIL 
		oClone:oWSCONSOLIDATEDRESULT := {}
		aEval( ::oWSCONSOLIDATEDRESULT , { |x| aadd( oClone:oWSCONSOLIDATEDRESULT , x:Clone() ) } )
	Endif 
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT RHAPDCONSOLIDATED_ARRAYOFCONSOLIDATEDRESULT
	Local nRElem1, oNodes1, nTElem1
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNodes1 :=  WSAdvValue( oResponse,"_CONSOLIDATEDRESULT","CONSOLIDATEDRESULT",{},NIL,.T.,"O",NIL,NIL) 
	nTElem1 := len(oNodes1)
	For nRElem1 := 1 to nTElem1 
		If !WSIsNilNode( oNodes1[nRElem1] )
			aadd(::oWSCONSOLIDATEDRESULT , RHAPDCONSOLIDATED_CONSOLIDATEDRESULT():New() )
			::oWSCONSOLIDATEDRESULT[len(::oWSCONSOLIDATEDRESULT)]:SoapRecv(oNodes1[nRElem1])
		Endif
	Next
Return

// WSDL Data Structure ARRAYOFPOLICYCABEC

WSSTRUCT RHAPDCONSOLIDATED_ARRAYOFPOLICYCABEC
	WSDATA   oWSPOLICYCABEC            AS RHAPDCONSOLIDATED_POLICYCABEC OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT RHAPDCONSOLIDATED_ARRAYOFPOLICYCABEC
	::Init()
Return Self

WSMETHOD INIT WSCLIENT RHAPDCONSOLIDATED_ARRAYOFPOLICYCABEC
	::oWSPOLICYCABEC       := {} // Array Of  RHAPDCONSOLIDATED_POLICYCABEC():New()
Return

WSMETHOD CLONE WSCLIENT RHAPDCONSOLIDATED_ARRAYOFPOLICYCABEC
	Local oClone := RHAPDCONSOLIDATED_ARRAYOFPOLICYCABEC():NEW()
	oClone:oWSPOLICYCABEC := NIL
	If ::oWSPOLICYCABEC <> NIL 
		oClone:oWSPOLICYCABEC := {}
		aEval( ::oWSPOLICYCABEC , { |x| aadd( oClone:oWSPOLICYCABEC , x:Clone() ) } )
	Endif 
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT RHAPDCONSOLIDATED_ARRAYOFPOLICYCABEC
	Local nRElem1, oNodes1, nTElem1
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNodes1 :=  WSAdvValue( oResponse,"_POLICYCABEC","POLICYCABEC",{},NIL,.T.,"O",NIL,NIL) 
	nTElem1 := len(oNodes1)
	For nRElem1 := 1 to nTElem1 
		If !WSIsNilNode( oNodes1[nRElem1] )
			aadd(::oWSPOLICYCABEC , RHAPDCONSOLIDATED_POLICYCABEC():New() )
			::oWSPOLICYCABEC[len(::oWSPOLICYCABEC)]:SoapRecv(oNodes1[nRElem1])
		Endif
	Next
Return

// WSDL Data Structure ARRAYOFDATAEMPLOYEE

WSSTRUCT RHAPDCONSOLIDATED_ARRAYOFDATAEMPLOYEE
	WSDATA   oWSDATAEMPLOYEE           AS RHAPDCONSOLIDATED_DATAEMPLOYEE OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT RHAPDCONSOLIDATED_ARRAYOFDATAEMPLOYEE
	::Init()
Return Self

WSMETHOD INIT WSCLIENT RHAPDCONSOLIDATED_ARRAYOFDATAEMPLOYEE
	::oWSDATAEMPLOYEE      := {} // Array Of  RHAPDCONSOLIDATED_DATAEMPLOYEE():New()
Return

WSMETHOD CLONE WSCLIENT RHAPDCONSOLIDATED_ARRAYOFDATAEMPLOYEE
	Local oClone := RHAPDCONSOLIDATED_ARRAYOFDATAEMPLOYEE():NEW()
	oClone:oWSDATAEMPLOYEE := NIL
	If ::oWSDATAEMPLOYEE <> NIL 
		oClone:oWSDATAEMPLOYEE := {}
		aEval( ::oWSDATAEMPLOYEE , { |x| aadd( oClone:oWSDATAEMPLOYEE , x:Clone() ) } )
	Endif 
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT RHAPDCONSOLIDATED_ARRAYOFDATAEMPLOYEE
	Local nRElem1, oNodes1, nTElem1
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNodes1 :=  WSAdvValue( oResponse,"_DATAEMPLOYEE","DATAEMPLOYEE",{},NIL,.T.,"O",NIL,NIL) 
	nTElem1 := len(oNodes1)
	For nRElem1 := 1 to nTElem1 
		If !WSIsNilNode( oNodes1[nRElem1] )
			aadd(::oWSDATAEMPLOYEE , RHAPDCONSOLIDATED_DATAEMPLOYEE():New() )
			::oWSDATAEMPLOYEE[len(::oWSDATAEMPLOYEE)]:SoapRecv(oNodes1[nRElem1])
		Endif
	Next
Return

// WSDL Data Structure CONSOLIDATEDRESULT

WSSTRUCT RHAPDCONSOLIDATED_CONSOLIDATEDRESULT
	WSDATA   cGROUP                    AS string OPTIONAL
	WSDATA   cGROUPDESC                AS string OPTIONAL
	WSDATA   cKEY                      AS string OPTIONAL
	WSDATA   cKEYDESC                  AS string OPTIONAL
	WSDATA   cPARTIALAVERAGE           AS string OPTIONAL
	WSDATA   cPROCESSDATE              AS string OPTIONAL
	WSDATA   cPROFITFOR                AS string OPTIONAL
	WSDATA   cTOTALAVERAGE             AS string OPTIONAL
	WSDATA   cWEIGHT                   AS string OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT RHAPDCONSOLIDATED_CONSOLIDATEDRESULT
	::Init()
Return Self

WSMETHOD INIT WSCLIENT RHAPDCONSOLIDATED_CONSOLIDATEDRESULT
Return

WSMETHOD CLONE WSCLIENT RHAPDCONSOLIDATED_CONSOLIDATEDRESULT
	Local oClone := RHAPDCONSOLIDATED_CONSOLIDATEDRESULT():NEW()
	oClone:cGROUP               := ::cGROUP
	oClone:cGROUPDESC           := ::cGROUPDESC
	oClone:cKEY                 := ::cKEY
	oClone:cKEYDESC             := ::cKEYDESC
	oClone:cPARTIALAVERAGE      := ::cPARTIALAVERAGE
	oClone:cPROCESSDATE         := ::cPROCESSDATE
	oClone:cPROFITFOR           := ::cPROFITFOR
	oClone:cTOTALAVERAGE        := ::cTOTALAVERAGE
	oClone:cWEIGHT              := ::cWEIGHT
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT RHAPDCONSOLIDATED_CONSOLIDATEDRESULT
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::cGROUP             :=  WSAdvValue( oResponse,"_GROUP","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cGROUPDESC         :=  WSAdvValue( oResponse,"_GROUPDESC","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cKEY               :=  WSAdvValue( oResponse,"_KEY","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cKEYDESC           :=  WSAdvValue( oResponse,"_KEYDESC","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cPARTIALAVERAGE    :=  WSAdvValue( oResponse,"_PARTIALAVERAGE","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cPROCESSDATE       :=  WSAdvValue( oResponse,"_PROCESSDATE","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cPROFITFOR         :=  WSAdvValue( oResponse,"_PROFITFOR","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cTOTALAVERAGE      :=  WSAdvValue( oResponse,"_TOTALAVERAGE","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cWEIGHT            :=  WSAdvValue( oResponse,"_WEIGHT","string",NIL,NIL,NIL,"S",NIL,NIL) 
Return

// WSDL Data Structure POLICYCABEC

WSSTRUCT RHAPDCONSOLIDATED_POLICYCABEC
	WSDATA   cBRANCHPOLICYID           AS string OPTIONAL
	WSDATA   oWSITEMSOFPOLICYDETAIL    AS RHAPDCONSOLIDATED_ARRAYOFPOLICYDETAIL OPTIONAL
	WSDATA   nITEMSTOTALDETAIL         AS integer OPTIONAL
	WSDATA   nPERCCOMPETENCE           AS float OPTIONAL
	WSDATA   nPERCFORMATION            AS float OPTIONAL
	WSDATA   nPERCGOAL                 AS float OPTIONAL
	WSDATA   cPOLICYDESC               AS string OPTIONAL
	WSDATA   cPOLICYID                 AS string OPTIONAL
	WSDATA   nREGID                    AS integer OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT RHAPDCONSOLIDATED_POLICYCABEC
	::Init()
Return Self

WSMETHOD INIT WSCLIENT RHAPDCONSOLIDATED_POLICYCABEC
Return

WSMETHOD CLONE WSCLIENT RHAPDCONSOLIDATED_POLICYCABEC
	Local oClone := RHAPDCONSOLIDATED_POLICYCABEC():NEW()
	oClone:cBRANCHPOLICYID      := ::cBRANCHPOLICYID
	oClone:oWSITEMSOFPOLICYDETAIL := IIF(::oWSITEMSOFPOLICYDETAIL = NIL , NIL , ::oWSITEMSOFPOLICYDETAIL:Clone() )
	oClone:nITEMSTOTALDETAIL    := ::nITEMSTOTALDETAIL
	oClone:nPERCCOMPETENCE      := ::nPERCCOMPETENCE
	oClone:nPERCFORMATION       := ::nPERCFORMATION
	oClone:nPERCGOAL            := ::nPERCGOAL
	oClone:cPOLICYDESC          := ::cPOLICYDESC
	oClone:cPOLICYID            := ::cPOLICYID
	oClone:nREGID               := ::nREGID
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT RHAPDCONSOLIDATED_POLICYCABEC
	Local oNode2
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::cBRANCHPOLICYID    :=  WSAdvValue( oResponse,"_BRANCHPOLICYID","string",NIL,NIL,NIL,"S",NIL,NIL) 
	oNode2 :=  WSAdvValue( oResponse,"_ITEMSOFPOLICYDETAIL","ARRAYOFPOLICYDETAIL",NIL,NIL,NIL,"O",NIL,NIL) 
	If oNode2 != NIL
		::oWSITEMSOFPOLICYDETAIL := RHAPDCONSOLIDATED_ARRAYOFPOLICYDETAIL():New()
		::oWSITEMSOFPOLICYDETAIL:SoapRecv(oNode2)
	EndIf
	::nITEMSTOTALDETAIL  :=  WSAdvValue( oResponse,"_ITEMSTOTALDETAIL","integer",NIL,NIL,NIL,"N",NIL,NIL) 
	::nPERCCOMPETENCE    :=  WSAdvValue( oResponse,"_PERCCOMPETENCE","float",NIL,NIL,NIL,"N",NIL,NIL) 
	::nPERCFORMATION     :=  WSAdvValue( oResponse,"_PERCFORMATION","float",NIL,NIL,NIL,"N",NIL,NIL) 
	::nPERCGOAL          :=  WSAdvValue( oResponse,"_PERCGOAL","float",NIL,NIL,NIL,"N",NIL,NIL) 
	::cPOLICYDESC        :=  WSAdvValue( oResponse,"_POLICYDESC","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cPOLICYID          :=  WSAdvValue( oResponse,"_POLICYID","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::nREGID             :=  WSAdvValue( oResponse,"_REGID","integer",NIL,NIL,NIL,"N",NIL,NIL) 
Return

// WSDL Data Structure DATAEMPLOYEE

WSSTRUCT RHAPDCONSOLIDATED_DATAEMPLOYEE
	WSDATA   cADMISSIONDATE            AS string
	WSDATA   cCATFUNC                  AS string OPTIONAL
	WSDATA   cCATFUNCDESC              AS string OPTIONAL
	WSDATA   cCATFUNCDESCSUP           AS string OPTIONAL
	WSDATA   cCATFUNCSUP               AS string OPTIONAL
	WSDATA   cCOST                     AS string OPTIONAL
	WSDATA   cCOSTID                   AS string OPTIONAL
	WSDATA   cDEPARTMENT               AS string
	WSDATA   cDESCRDEPARTMENT          AS string OPTIONAL
	WSDATA   cDESCSITUACAO             AS string OPTIONAL
	WSDATA   cEMAIL                    AS string OPTIONAL
	WSDATA   cEMPLOYEEEMP              AS string OPTIONAL
	WSDATA   cEMPLOYEEFILIAL           AS string
	WSDATA   cFILIALDESCR              AS string OPTIONAL
	WSDATA   cFUNCTIONDESC             AS string OPTIONAL
	WSDATA   cFUNCTIONID               AS string OPTIONAL
	WSDATA   lFUNCTIONSUBST            AS boolean OPTIONAL
	WSDATA   cHOURSMONTH               AS string OPTIONAL
	WSDATA   cITEM                     AS string OPTIONAL
	WSDATA   cKEYVISION                AS string OPTIONAL
	WSDATA   nLEVELHIERAR              AS integer OPTIONAL
	WSDATA   nLEVELSUP                 AS integer OPTIONAL
	WSDATA   cNAME                     AS string
	WSDATA   cNAMESUP                  AS string OPTIONAL
	WSDATA   cPARTICIPANTID            AS string OPTIONAL
	WSDATA   cPOSITION                 AS string OPTIONAL
	WSDATA   cPOSITIONID               AS string OPTIONAL
	WSDATA   lPOSSUIEQUIPE             AS boolean OPTIONAL
	WSDATA   lPOSSUISOLIC              AS boolean OPTIONAL
	WSDATA   cREGISTRATION             AS string
	WSDATA   cRESULTCONSOLID           AS string OPTIONAL
	WSDATA   nSALARY                   AS float OPTIONAL
	WSDATA   cSITUACAO                 AS string OPTIONAL
	WSDATA   cSTATUSEMPLOYEE           AS string OPTIONAL
	WSDATA   cSUPEMPRESA               AS string OPTIONAL
	WSDATA   cSUPFILIAL                AS string OPTIONAL
	WSDATA   cSUPREGISTRATION          AS string OPTIONAL
	WSDATA   nTOTAL                    AS integer OPTIONAL
	WSDATA   cTYPEEMPLOYEE             AS string OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT RHAPDCONSOLIDATED_DATAEMPLOYEE
	::Init()
Return Self

WSMETHOD INIT WSCLIENT RHAPDCONSOLIDATED_DATAEMPLOYEE
Return

WSMETHOD CLONE WSCLIENT RHAPDCONSOLIDATED_DATAEMPLOYEE
	Local oClone := RHAPDCONSOLIDATED_DATAEMPLOYEE():NEW()
	oClone:cADMISSIONDATE       := ::cADMISSIONDATE
	oClone:cCATFUNC             := ::cCATFUNC
	oClone:cCATFUNCDESC         := ::cCATFUNCDESC
	oClone:cCATFUNCDESCSUP      := ::cCATFUNCDESCSUP
	oClone:cCATFUNCSUP          := ::cCATFUNCSUP
	oClone:cCOST                := ::cCOST
	oClone:cCOSTID              := ::cCOSTID
	oClone:cDEPARTMENT          := ::cDEPARTMENT
	oClone:cDESCRDEPARTMENT     := ::cDESCRDEPARTMENT
	oClone:cDESCSITUACAO        := ::cDESCSITUACAO
	oClone:cEMAIL               := ::cEMAIL
	oClone:cEMPLOYEEEMP         := ::cEMPLOYEEEMP
	oClone:cEMPLOYEEFILIAL      := ::cEMPLOYEEFILIAL
	oClone:cFILIALDESCR         := ::cFILIALDESCR
	oClone:cFUNCTIONDESC        := ::cFUNCTIONDESC
	oClone:cFUNCTIONID          := ::cFUNCTIONID
	oClone:lFUNCTIONSUBST       := ::lFUNCTIONSUBST
	oClone:cHOURSMONTH          := ::cHOURSMONTH
	oClone:cITEM                := ::cITEM
	oClone:cKEYVISION           := ::cKEYVISION
	oClone:nLEVELHIERAR         := ::nLEVELHIERAR
	oClone:nLEVELSUP            := ::nLEVELSUP
	oClone:cNAME                := ::cNAME
	oClone:cNAMESUP             := ::cNAMESUP
	oClone:cPARTICIPANTID       := ::cPARTICIPANTID
	oClone:cPOSITION            := ::cPOSITION
	oClone:cPOSITIONID          := ::cPOSITIONID
	oClone:lPOSSUIEQUIPE        := ::lPOSSUIEQUIPE
	oClone:lPOSSUISOLIC         := ::lPOSSUISOLIC
	oClone:cREGISTRATION        := ::cREGISTRATION
	oClone:cRESULTCONSOLID      := ::cRESULTCONSOLID
	oClone:nSALARY              := ::nSALARY
	oClone:cSITUACAO            := ::cSITUACAO
	oClone:cSTATUSEMPLOYEE      := ::cSTATUSEMPLOYEE
	oClone:cSUPEMPRESA          := ::cSUPEMPRESA
	oClone:cSUPFILIAL           := ::cSUPFILIAL
	oClone:cSUPREGISTRATION     := ::cSUPREGISTRATION
	oClone:nTOTAL               := ::nTOTAL
	oClone:cTYPEEMPLOYEE        := ::cTYPEEMPLOYEE
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT RHAPDCONSOLIDATED_DATAEMPLOYEE
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::cADMISSIONDATE     :=  WSAdvValue( oResponse,"_ADMISSIONDATE","string",NIL,"Property cADMISSIONDATE as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCATFUNC           :=  WSAdvValue( oResponse,"_CATFUNC","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cCATFUNCDESC       :=  WSAdvValue( oResponse,"_CATFUNCDESC","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cCATFUNCDESCSUP    :=  WSAdvValue( oResponse,"_CATFUNCDESCSUP","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cCATFUNCSUP        :=  WSAdvValue( oResponse,"_CATFUNCSUP","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cCOST              :=  WSAdvValue( oResponse,"_COST","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cCOSTID            :=  WSAdvValue( oResponse,"_COSTID","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cDEPARTMENT        :=  WSAdvValue( oResponse,"_DEPARTMENT","string",NIL,"Property cDEPARTMENT as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cDESCRDEPARTMENT   :=  WSAdvValue( oResponse,"_DESCRDEPARTMENT","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cDESCSITUACAO      :=  WSAdvValue( oResponse,"_DESCSITUACAO","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cEMAIL             :=  WSAdvValue( oResponse,"_EMAIL","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cEMPLOYEEEMP       :=  WSAdvValue( oResponse,"_EMPLOYEEEMP","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cEMPLOYEEFILIAL    :=  WSAdvValue( oResponse,"_EMPLOYEEFILIAL","string",NIL,"Property cEMPLOYEEFILIAL as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cFILIALDESCR       :=  WSAdvValue( oResponse,"_FILIALDESCR","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cFUNCTIONDESC      :=  WSAdvValue( oResponse,"_FUNCTIONDESC","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cFUNCTIONID        :=  WSAdvValue( oResponse,"_FUNCTIONID","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::lFUNCTIONSUBST     :=  WSAdvValue( oResponse,"_FUNCTIONSUBST","boolean",NIL,NIL,NIL,"L",NIL,NIL) 
	::cHOURSMONTH        :=  WSAdvValue( oResponse,"_HOURSMONTH","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cITEM              :=  WSAdvValue( oResponse,"_ITEM","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cKEYVISION         :=  WSAdvValue( oResponse,"_KEYVISION","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::nLEVELHIERAR       :=  WSAdvValue( oResponse,"_LEVELHIERAR","integer",NIL,NIL,NIL,"N",NIL,NIL) 
	::nLEVELSUP          :=  WSAdvValue( oResponse,"_LEVELSUP","integer",NIL,NIL,NIL,"N",NIL,NIL) 
	::cNAME              :=  WSAdvValue( oResponse,"_NAME","string",NIL,"Property cNAME as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cNAMESUP           :=  WSAdvValue( oResponse,"_NAMESUP","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cPARTICIPANTID     :=  WSAdvValue( oResponse,"_PARTICIPANTID","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cPOSITION          :=  WSAdvValue( oResponse,"_POSITION","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cPOSITIONID        :=  WSAdvValue( oResponse,"_POSITIONID","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::lPOSSUIEQUIPE      :=  WSAdvValue( oResponse,"_POSSUIEQUIPE","boolean",NIL,NIL,NIL,"L",NIL,NIL) 
	::lPOSSUISOLIC       :=  WSAdvValue( oResponse,"_POSSUISOLIC","boolean",NIL,NIL,NIL,"L",NIL,NIL) 
	::cREGISTRATION      :=  WSAdvValue( oResponse,"_REGISTRATION","string",NIL,"Property cREGISTRATION as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cRESULTCONSOLID    :=  WSAdvValue( oResponse,"_RESULTCONSOLID","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::nSALARY            :=  WSAdvValue( oResponse,"_SALARY","float",NIL,NIL,NIL,"N",NIL,NIL) 
	::cSITUACAO          :=  WSAdvValue( oResponse,"_SITUACAO","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cSTATUSEMPLOYEE    :=  WSAdvValue( oResponse,"_STATUSEMPLOYEE","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cSUPEMPRESA        :=  WSAdvValue( oResponse,"_SUPEMPRESA","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cSUPFILIAL         :=  WSAdvValue( oResponse,"_SUPFILIAL","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cSUPREGISTRATION   :=  WSAdvValue( oResponse,"_SUPREGISTRATION","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::nTOTAL             :=  WSAdvValue( oResponse,"_TOTAL","integer",NIL,NIL,NIL,"N",NIL,NIL) 
	::cTYPEEMPLOYEE      :=  WSAdvValue( oResponse,"_TYPEEMPLOYEE","string",NIL,NIL,NIL,"S",NIL,NIL) 
Return

// WSDL Data Structure ARRAYOFPOLICYDETAIL

WSSTRUCT RHAPDCONSOLIDATED_ARRAYOFPOLICYDETAIL
	WSDATA   oWSPOLICYDETAIL           AS RHAPDCONSOLIDATED_POLICYDETAIL OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT RHAPDCONSOLIDATED_ARRAYOFPOLICYDETAIL
	::Init()
Return Self

WSMETHOD INIT WSCLIENT RHAPDCONSOLIDATED_ARRAYOFPOLICYDETAIL
	::oWSPOLICYDETAIL      := {} // Array Of  RHAPDCONSOLIDATED_POLICYDETAIL():New()
Return

WSMETHOD CLONE WSCLIENT RHAPDCONSOLIDATED_ARRAYOFPOLICYDETAIL
	Local oClone := RHAPDCONSOLIDATED_ARRAYOFPOLICYDETAIL():NEW()
	oClone:oWSPOLICYDETAIL := NIL
	If ::oWSPOLICYDETAIL <> NIL 
		oClone:oWSPOLICYDETAIL := {}
		aEval( ::oWSPOLICYDETAIL , { |x| aadd( oClone:oWSPOLICYDETAIL , x:Clone() ) } )
	Endif 
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT RHAPDCONSOLIDATED_ARRAYOFPOLICYDETAIL
	Local nRElem1, oNodes1, nTElem1
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNodes1 :=  WSAdvValue( oResponse,"_POLICYDETAIL","POLICYDETAIL",{},NIL,.T.,"O",NIL,NIL) 
	nTElem1 := len(oNodes1)
	For nRElem1 := 1 to nTElem1 
		If !WSIsNilNode( oNodes1[nRElem1] )
			aadd(::oWSPOLICYDETAIL , RHAPDCONSOLIDATED_POLICYDETAIL():New() )
			::oWSPOLICYDETAIL[len(::oWSPOLICYDETAIL)]:SoapRecv(oNodes1[nRElem1])
		Endif
	Next
Return

// WSDL Data Structure POLICYDETAIL

WSSTRUCT RHAPDCONSOLIDATED_POLICYDETAIL
	WSDATA   cPERIODDESC               AS string OPTIONAL
	WSDATA   cPERIODFINALDATE          AS string OPTIONAL
	WSDATA   cPERIODID                 AS string OPTIONAL
	WSDATA   cPERIODINITIALDATE        AS string OPTIONAL
	WSDATA   cPERIODTYPE               AS string OPTIONAL
	WSDATA   cPERIODTYPEDESC           AS string OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT RHAPDCONSOLIDATED_POLICYDETAIL
	::Init()
Return Self

WSMETHOD INIT WSCLIENT RHAPDCONSOLIDATED_POLICYDETAIL
Return

WSMETHOD CLONE WSCLIENT RHAPDCONSOLIDATED_POLICYDETAIL
	Local oClone := RHAPDCONSOLIDATED_POLICYDETAIL():NEW()
	oClone:cPERIODDESC          := ::cPERIODDESC
	oClone:cPERIODFINALDATE     := ::cPERIODFINALDATE
	oClone:cPERIODID            := ::cPERIODID
	oClone:cPERIODINITIALDATE   := ::cPERIODINITIALDATE
	oClone:cPERIODTYPE          := ::cPERIODTYPE
	oClone:cPERIODTYPEDESC      := ::cPERIODTYPEDESC
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT RHAPDCONSOLIDATED_POLICYDETAIL
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::cPERIODDESC        :=  WSAdvValue( oResponse,"_PERIODDESC","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cPERIODFINALDATE   :=  WSAdvValue( oResponse,"_PERIODFINALDATE","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cPERIODID          :=  WSAdvValue( oResponse,"_PERIODID","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cPERIODINITIALDATE :=  WSAdvValue( oResponse,"_PERIODINITIALDATE","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cPERIODTYPE        :=  WSAdvValue( oResponse,"_PERIODTYPE","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cPERIODTYPEDESC    :=  WSAdvValue( oResponse,"_PERIODTYPEDESC","string",NIL,NIL,NIL,"S",NIL,NIL) 
Return


