#INCLUDE "protheus.ch"
#INCLUDE "apwebsrv.ch"

/* ===============================================================================
WSDL Location    http://localhost:8059/ws/PMSANNOTATIONS.apw?WSDL
Gerado em        12/14/20 11:20:39
Observações      Código-Fonte gerado por ADVPL WSDL Client 1.120703
                 Alterações neste arquivo podem causar funcionamento incorreto
                 e serão perdidas caso o código-fonte seja gerado novamente.
=============================================================================== */

User Function _TFSYFSQ ; Return  // "dummy" function - Internal Use 

/* -------------------------------------------------------------------------------
WSDL Service WSPMSANNOTATIONS
------------------------------------------------------------------------------- */

WSCLIENT WSPMSANNOTATIONS

	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD RESET
	WSMETHOD CLONE
	WSMETHOD ANNOTATIONHANDLE
	WSMETHOD GETANNOTATION
	WSMETHOD GETANNOTATIONSLIST
	WSMETHOD GETHEADER
	WSMETHOD GETHEADERPMS
	WSMETHOD GETINSERTANNOTATION
	WSMETHOD GETRECORDCOUNT

	WSDATA   _URL                      AS String
	WSDATA   _HEADOUT                  AS Array of String
	WSDATA   _COOKIES                  AS Array of String
	WSDATA   cUSERCODE                 AS string
	WSDATA   cPROTHEUSUSERCODE         AS string
	WSDATA   oWSANNOTATIONHANDLE       AS PMSANNOTATIONS_ANNOTATIONVIEW
	WSDATA   nOPERATIONNUMBER          AS integer
	WSDATA   oWSANNOTATIONHANDLERESULT AS PMSANNOTATIONS_ARRAYOFMESSAGEVIEW
	WSDATA   nDBRECORD                 AS integer
	WSDATA   oWSGETANNOTATIONRESULT    AS PMSANNOTATIONS_ARRAYOFANNOTATIONVIEW
	WSDATA   cRESOURCEINITIAL          AS string
	WSDATA   cRESOURCEFINAL            AS string
	WSDATA   cPROJECTINITIAL           AS string
	WSDATA   cPROJECTFINAL             AS string
	WSDATA   nPAGELEN                  AS integer
	WSDATA   nPAGEFIRST                AS integer
	WSDATA   cQRYADD                   AS string
	WSDATA   oWSGETANNOTATIONSLISTRESULT AS PMSANNOTATIONS_ARRAYOFANNOTATIONSLISTVIEW
	WSDATA   cHEADERTYPE               AS string
	WSDATA   oWSGETHEADERRESULT        AS PMSANNOTATIONS_ARRAYOFBRWHEADER
	WSDATA   oWSGETHEADERPMSRESULT     AS PMSANNOTATIONS_ARRAYOFBRWHEADERPMS
	WSDATA   cPROJECTCODE              AS string
	WSDATA   cTASKCODE                 AS string
	WSDATA   cGETINSERTANNOTATIONRESULT AS string
	WSDATA   nGETRECORDCOUNTRESULT     AS integer

	// Estruturas mantidas por compatibilidade - NÃO USAR
	WSDATA   oWSANNOTATIONVIEW         AS PMSANNOTATIONS_ANNOTATIONVIEW

ENDWSCLIENT

WSMETHOD NEW WSCLIENT WSPMSANNOTATIONS
::Init()
If !FindFunction("XMLCHILDEX")
	UserException("O Código-Fonte Client atual requer os executáveis do Protheus Build [7.00.191205P-20201009] ou superior. Atualize o Protheus ou gere o Código-Fonte novamente utilizando o Build atual.")
EndIf
Return Self

WSMETHOD INIT WSCLIENT WSPMSANNOTATIONS
	::oWSANNOTATIONHANDLE := PMSANNOTATIONS_ANNOTATIONVIEW():New()
	::oWSANNOTATIONHANDLERESULT := PMSANNOTATIONS_ARRAYOFMESSAGEVIEW():New()
	::oWSGETANNOTATIONRESULT := PMSANNOTATIONS_ARRAYOFANNOTATIONVIEW():New()
	::oWSGETANNOTATIONSLISTRESULT := PMSANNOTATIONS_ARRAYOFANNOTATIONSLISTVIEW():New()
	::oWSGETHEADERRESULT := PMSANNOTATIONS_ARRAYOFBRWHEADER():New()
	::oWSGETHEADERPMSRESULT := PMSANNOTATIONS_ARRAYOFBRWHEADERPMS():New()

	// Estruturas mantidas por compatibilidade - NÃO USAR
	::oWSANNOTATIONVIEW  := ::oWSANNOTATIONHANDLE
Return

WSMETHOD RESET WSCLIENT WSPMSANNOTATIONS
	::cUSERCODE          := NIL 
	::cPROTHEUSUSERCODE  := NIL 
	::oWSANNOTATIONHANDLE := NIL 
	::nOPERATIONNUMBER   := NIL 
	::oWSANNOTATIONHANDLERESULT := NIL 
	::nDBRECORD          := NIL 
	::oWSGETANNOTATIONRESULT := NIL 
	::cRESOURCEINITIAL   := NIL 
	::cRESOURCEFINAL     := NIL 
	::cPROJECTINITIAL    := NIL 
	::cPROJECTFINAL      := NIL 
	::nPAGELEN           := NIL 
	::nPAGEFIRST         := NIL 
	::cQRYADD            := NIL 
	::oWSGETANNOTATIONSLISTRESULT := NIL 
	::cHEADERTYPE        := NIL 
	::oWSGETHEADERRESULT := NIL 
	::oWSGETHEADERPMSRESULT := NIL 
	::cPROJECTCODE       := NIL 
	::cTASKCODE          := NIL 
	::cGETINSERTANNOTATIONRESULT := NIL 
	::nGETRECORDCOUNTRESULT := NIL 

	// Estruturas mantidas por compatibilidade - NÃO USAR
	::oWSANNOTATIONVIEW  := NIL
	::Init()
Return

WSMETHOD CLONE WSCLIENT WSPMSANNOTATIONS
Local oClone := WSPMSANNOTATIONS():New()
	oClone:_URL          := ::_URL 
	oClone:cUSERCODE     := ::cUSERCODE
	oClone:cPROTHEUSUSERCODE := ::cPROTHEUSUSERCODE
	oClone:oWSANNOTATIONHANDLE :=  IIF(::oWSANNOTATIONHANDLE = NIL , NIL ,::oWSANNOTATIONHANDLE:Clone() )
	oClone:nOPERATIONNUMBER := ::nOPERATIONNUMBER
	oClone:oWSANNOTATIONHANDLERESULT :=  IIF(::oWSANNOTATIONHANDLERESULT = NIL , NIL ,::oWSANNOTATIONHANDLERESULT:Clone() )
	oClone:nDBRECORD     := ::nDBRECORD
	oClone:oWSGETANNOTATIONRESULT :=  IIF(::oWSGETANNOTATIONRESULT = NIL , NIL ,::oWSGETANNOTATIONRESULT:Clone() )
	oClone:cRESOURCEINITIAL := ::cRESOURCEINITIAL
	oClone:cRESOURCEFINAL := ::cRESOURCEFINAL
	oClone:cPROJECTINITIAL := ::cPROJECTINITIAL
	oClone:cPROJECTFINAL := ::cPROJECTFINAL
	oClone:nPAGELEN      := ::nPAGELEN
	oClone:nPAGEFIRST    := ::nPAGEFIRST
	oClone:cQRYADD       := ::cQRYADD
	oClone:oWSGETANNOTATIONSLISTRESULT :=  IIF(::oWSGETANNOTATIONSLISTRESULT = NIL , NIL ,::oWSGETANNOTATIONSLISTRESULT:Clone() )
	oClone:cHEADERTYPE   := ::cHEADERTYPE
	oClone:oWSGETHEADERRESULT :=  IIF(::oWSGETHEADERRESULT = NIL , NIL ,::oWSGETHEADERRESULT:Clone() )
	oClone:oWSGETHEADERPMSRESULT :=  IIF(::oWSGETHEADERPMSRESULT = NIL , NIL ,::oWSGETHEADERPMSRESULT:Clone() )
	oClone:cPROJECTCODE  := ::cPROJECTCODE
	oClone:cTASKCODE     := ::cTASKCODE
	oClone:cGETINSERTANNOTATIONRESULT := ::cGETINSERTANNOTATIONRESULT
	oClone:nGETRECORDCOUNTRESULT := ::nGETRECORDCOUNTRESULT

	// Estruturas mantidas por compatibilidade - NÃO USAR
	oClone:oWSANNOTATIONVIEW := oClone:oWSANNOTATIONHANDLE
Return oClone

// WSDL Method ANNOTATIONHANDLE of Service WSPMSANNOTATIONS

WSMETHOD ANNOTATIONHANDLE WSSEND cUSERCODE,cPROTHEUSUSERCODE,oWSANNOTATIONHANDLE,nOPERATIONNUMBER WSRECEIVE oWSANNOTATIONHANDLERESULT WSCLIENT WSPMSANNOTATIONS
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<ANNOTATIONHANDLE xmlns="http://localhost:8059/">'
cSoap += WSSoapValue("USERCODE", ::cUSERCODE, cUSERCODE , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("PROTHEUSUSERCODE", ::cPROTHEUSUSERCODE, cPROTHEUSUSERCODE , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("ANNOTATIONHANDLE", ::oWSANNOTATIONHANDLE, oWSANNOTATIONHANDLE , "ANNOTATIONVIEW", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("OPERATIONNUMBER", ::nOPERATIONNUMBER, nOPERATIONNUMBER , "integer", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += "</ANNOTATIONHANDLE>"

oXmlRet := SvcSoapCall(Self,cSoap,; 
	"http://localhost:8059/ANNOTATIONHANDLE",; 
	"DOCUMENT","http://localhost:8059/",,"1.031217",; 
	"http://localhost:8059/ws/PMSANNOTATIONS.apw")

::Init()
::oWSANNOTATIONHANDLERESULT:SoapRecv( WSAdvValue( oXmlRet,"_ANNOTATIONHANDLERESPONSE:_ANNOTATIONHANDLERESULT","ARRAYOFMESSAGEVIEW",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.

// WSDL Method GETANNOTATION of Service WSPMSANNOTATIONS

WSMETHOD GETANNOTATION WSSEND cUSERCODE,cPROTHEUSUSERCODE,nDBRECORD,nOPERATIONNUMBER WSRECEIVE oWSGETANNOTATIONRESULT WSCLIENT WSPMSANNOTATIONS
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<GETANNOTATION xmlns="http://localhost:8059/">'
cSoap += WSSoapValue("USERCODE", ::cUSERCODE, cUSERCODE , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("PROTHEUSUSERCODE", ::cPROTHEUSUSERCODE, cPROTHEUSUSERCODE , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("DBRECORD", ::nDBRECORD, nDBRECORD , "integer", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("OPERATIONNUMBER", ::nOPERATIONNUMBER, nOPERATIONNUMBER , "integer", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += "</GETANNOTATION>"

oXmlRet := SvcSoapCall(Self,cSoap,; 
	"http://localhost:8059/GETANNOTATION",; 
	"DOCUMENT","http://localhost:8059/",,"1.031217",; 
	"http://localhost:8059/ws/PMSANNOTATIONS.apw")

::Init()
::oWSGETANNOTATIONRESULT:SoapRecv( WSAdvValue( oXmlRet,"_GETANNOTATIONRESPONSE:_GETANNOTATIONRESULT","ARRAYOFANNOTATIONVIEW",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.

// WSDL Method GETANNOTATIONSLIST of Service WSPMSANNOTATIONS

WSMETHOD GETANNOTATIONSLIST WSSEND cUSERCODE,cPROTHEUSUSERCODE,cRESOURCEINITIAL,cRESOURCEFINAL,cPROJECTINITIAL,cPROJECTFINAL,nPAGELEN,nPAGEFIRST,cQRYADD WSRECEIVE oWSGETANNOTATIONSLISTRESULT WSCLIENT WSPMSANNOTATIONS
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<GETANNOTATIONSLIST xmlns="http://localhost:8059/">'
cSoap += WSSoapValue("USERCODE", ::cUSERCODE, cUSERCODE , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("PROTHEUSUSERCODE", ::cPROTHEUSUSERCODE, cPROTHEUSUSERCODE , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("RESOURCEINITIAL", ::cRESOURCEINITIAL, cRESOURCEINITIAL , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("RESOURCEFINAL", ::cRESOURCEFINAL, cRESOURCEFINAL , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("PROJECTINITIAL", ::cPROJECTINITIAL, cPROJECTINITIAL , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("PROJECTFINAL", ::cPROJECTFINAL, cPROJECTFINAL , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("PAGELEN", ::nPAGELEN, nPAGELEN , "integer", .F. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("PAGEFIRST", ::nPAGEFIRST, nPAGEFIRST , "integer", .F. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("QRYADD", ::cQRYADD, cQRYADD , "string", .F. , .F., 0 , NIL, .F.,.F.) 
cSoap += "</GETANNOTATIONSLIST>"

oXmlRet := SvcSoapCall(Self,cSoap,; 
	"http://localhost:8059/GETANNOTATIONSLIST",; 
	"DOCUMENT","http://localhost:8059/",,"1.031217",; 
	"http://localhost:8059/ws/PMSANNOTATIONS.apw")

::Init()
::oWSGETANNOTATIONSLISTRESULT:SoapRecv( WSAdvValue( oXmlRet,"_GETANNOTATIONSLISTRESPONSE:_GETANNOTATIONSLISTRESULT","ARRAYOFANNOTATIONSLISTVIEW",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.

// WSDL Method GETHEADER of Service WSPMSANNOTATIONS

WSMETHOD GETHEADER WSSEND cHEADERTYPE WSRECEIVE oWSGETHEADERRESULT WSCLIENT WSPMSANNOTATIONS
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<GETHEADER xmlns="http://localhost:8059/">'
cSoap += WSSoapValue("HEADERTYPE", ::cHEADERTYPE, cHEADERTYPE , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += "</GETHEADER>"

oXmlRet := SvcSoapCall(Self,cSoap,; 
	"http://localhost:8059/GETHEADER",; 
	"DOCUMENT","http://localhost:8059/",,"1.031217",; 
	"http://localhost:8059/ws/PMSANNOTATIONS.apw")

::Init()
::oWSGETHEADERRESULT:SoapRecv( WSAdvValue( oXmlRet,"_GETHEADERRESPONSE:_GETHEADERRESULT","ARRAYOFBRWHEADER",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.

// WSDL Method GETHEADERPMS of Service WSPMSANNOTATIONS

WSMETHOD GETHEADERPMS WSSEND cHEADERTYPE WSRECEIVE oWSGETHEADERPMSRESULT WSCLIENT WSPMSANNOTATIONS
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<GETHEADERPMS xmlns="http://localhost:8059/">'
cSoap += WSSoapValue("HEADERTYPE", ::cHEADERTYPE, cHEADERTYPE , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += "</GETHEADERPMS>"

oXmlRet := SvcSoapCall(Self,cSoap,; 
	"http://localhost:8059/GETHEADERPMS",; 
	"DOCUMENT","http://localhost:8059/",,"1.031217",; 
	"http://localhost:8059/ws/PMSANNOTATIONS.apw")

::Init()
::oWSGETHEADERPMSRESULT:SoapRecv( WSAdvValue( oXmlRet,"_GETHEADERPMSRESPONSE:_GETHEADERPMSRESULT","ARRAYOFBRWHEADERPMS",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.

// WSDL Method GETINSERTANNOTATION of Service WSPMSANNOTATIONS

WSMETHOD GETINSERTANNOTATION WSSEND cUSERCODE,cPROTHEUSUSERCODE,cPROJECTCODE,cTASKCODE WSRECEIVE cGETINSERTANNOTATIONRESULT WSCLIENT WSPMSANNOTATIONS
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<GETINSERTANNOTATION xmlns="http://localhost:8059/">'
cSoap += WSSoapValue("USERCODE", ::cUSERCODE, cUSERCODE , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("PROTHEUSUSERCODE", ::cPROTHEUSUSERCODE, cPROTHEUSUSERCODE , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("PROJECTCODE", ::cPROJECTCODE, cPROJECTCODE , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("TASKCODE", ::cTASKCODE, cTASKCODE , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += "</GETINSERTANNOTATION>"

oXmlRet := SvcSoapCall(Self,cSoap,; 
	"http://localhost:8059/GETINSERTANNOTATION",; 
	"DOCUMENT","http://localhost:8059/",,"1.031217",; 
	"http://localhost:8059/ws/PMSANNOTATIONS.apw")

::Init()
::cGETINSERTANNOTATIONRESULT :=  WSAdvValue( oXmlRet,"_GETINSERTANNOTATIONRESPONSE:_GETINSERTANNOTATIONRESULT:TEXT","string",NIL,NIL,NIL,NIL,NIL,NIL) 

END WSMETHOD

oXmlRet := NIL
Return .T.

// WSDL Method GETRECORDCOUNT of Service WSPMSANNOTATIONS

WSMETHOD GETRECORDCOUNT WSSEND cUSERCODE,cPROTHEUSUSERCODE,cRESOURCEINITIAL,cRESOURCEFINAL,cPROJECTINITIAL,cPROJECTFINAL WSRECEIVE nGETRECORDCOUNTRESULT WSCLIENT WSPMSANNOTATIONS
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<GETRECORDCOUNT xmlns="http://localhost:8059/">'
cSoap += WSSoapValue("USERCODE", ::cUSERCODE, cUSERCODE , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("PROTHEUSUSERCODE", ::cPROTHEUSUSERCODE, cPROTHEUSUSERCODE , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("RESOURCEINITIAL", ::cRESOURCEINITIAL, cRESOURCEINITIAL , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("RESOURCEFINAL", ::cRESOURCEFINAL, cRESOURCEFINAL , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("PROJECTINITIAL", ::cPROJECTINITIAL, cPROJECTINITIAL , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("PROJECTFINAL", ::cPROJECTFINAL, cPROJECTFINAL , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += "</GETRECORDCOUNT>"

oXmlRet := SvcSoapCall(Self,cSoap,; 
	"http://localhost:8059/GETRECORDCOUNT",; 
	"DOCUMENT","http://localhost:8059/",,"1.031217",; 
	"http://localhost:8059/ws/PMSANNOTATIONS.apw")

::Init()
::nGETRECORDCOUNTRESULT :=  WSAdvValue( oXmlRet,"_GETRECORDCOUNTRESPONSE:_GETRECORDCOUNTRESULT:TEXT","integer",NIL,NIL,NIL,NIL,NIL,NIL) 

END WSMETHOD

oXmlRet := NIL
Return .T.


// WSDL Data Structure ARRAYOFMESSAGEVIEW

WSSTRUCT PMSANNOTATIONS_ARRAYOFMESSAGEVIEW
	WSDATA   oWSMESSAGEVIEW            AS PMSANNOTATIONS_MESSAGEVIEW OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PMSANNOTATIONS_ARRAYOFMESSAGEVIEW
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PMSANNOTATIONS_ARRAYOFMESSAGEVIEW
	::oWSMESSAGEVIEW       := {} // Array Of  PMSANNOTATIONS_MESSAGEVIEW():New()
Return

WSMETHOD CLONE WSCLIENT PMSANNOTATIONS_ARRAYOFMESSAGEVIEW
	Local oClone := PMSANNOTATIONS_ARRAYOFMESSAGEVIEW():NEW()
	oClone:oWSMESSAGEVIEW := NIL
	If ::oWSMESSAGEVIEW <> NIL 
		oClone:oWSMESSAGEVIEW := {}
		aEval( ::oWSMESSAGEVIEW , { |x| aadd( oClone:oWSMESSAGEVIEW , x:Clone() ) } )
	Endif 
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PMSANNOTATIONS_ARRAYOFMESSAGEVIEW
	Local nRElem1, oNodes1, nTElem1
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNodes1 :=  WSAdvValue( oResponse,"_MESSAGEVIEW","MESSAGEVIEW",{},NIL,.T.,"O",NIL,NIL) 
	nTElem1 := len(oNodes1)
	For nRElem1 := 1 to nTElem1 
		If !WSIsNilNode( oNodes1[nRElem1] )
			aadd(::oWSMESSAGEVIEW , PMSANNOTATIONS_MESSAGEVIEW():New() )
			::oWSMESSAGEVIEW[len(::oWSMESSAGEVIEW)]:SoapRecv(oNodes1[nRElem1])
		Endif
	Next
Return

// WSDL Data Structure ARRAYOFANNOTATIONVIEW

WSSTRUCT PMSANNOTATIONS_ARRAYOFANNOTATIONVIEW
	WSDATA   oWSANNOTATIONVIEW         AS PMSANNOTATIONS_ANNOTATIONVIEW OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PMSANNOTATIONS_ARRAYOFANNOTATIONVIEW
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PMSANNOTATIONS_ARRAYOFANNOTATIONVIEW
	::oWSANNOTATIONVIEW    := {} // Array Of  PMSANNOTATIONS_ANNOTATIONVIEW():New()
Return

WSMETHOD CLONE WSCLIENT PMSANNOTATIONS_ARRAYOFANNOTATIONVIEW
	Local oClone := PMSANNOTATIONS_ARRAYOFANNOTATIONVIEW():NEW()
	oClone:oWSANNOTATIONVIEW := NIL
	If ::oWSANNOTATIONVIEW <> NIL 
		oClone:oWSANNOTATIONVIEW := {}
		aEval( ::oWSANNOTATIONVIEW , { |x| aadd( oClone:oWSANNOTATIONVIEW , x:Clone() ) } )
	Endif 
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PMSANNOTATIONS_ARRAYOFANNOTATIONVIEW
	Local nRElem1, oNodes1, nTElem1
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNodes1 :=  WSAdvValue( oResponse,"_ANNOTATIONVIEW","ANNOTATIONVIEW",{},NIL,.T.,"O",NIL,NIL) 
	nTElem1 := len(oNodes1)
	For nRElem1 := 1 to nTElem1 
		If !WSIsNilNode( oNodes1[nRElem1] )
			aadd(::oWSANNOTATIONVIEW , PMSANNOTATIONS_ANNOTATIONVIEW():New() )
			::oWSANNOTATIONVIEW[len(::oWSANNOTATIONVIEW)]:SoapRecv(oNodes1[nRElem1])
		Endif
	Next
Return

// WSDL Data Structure ARRAYOFANNOTATIONSLISTVIEW

WSSTRUCT PMSANNOTATIONS_ARRAYOFANNOTATIONSLISTVIEW
	WSDATA   oWSANNOTATIONSLISTVIEW    AS PMSANNOTATIONS_ANNOTATIONSLISTVIEW OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PMSANNOTATIONS_ARRAYOFANNOTATIONSLISTVIEW
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PMSANNOTATIONS_ARRAYOFANNOTATIONSLISTVIEW
	::oWSANNOTATIONSLISTVIEW := {} // Array Of  PMSANNOTATIONS_ANNOTATIONSLISTVIEW():New()
Return

WSMETHOD CLONE WSCLIENT PMSANNOTATIONS_ARRAYOFANNOTATIONSLISTVIEW
	Local oClone := PMSANNOTATIONS_ARRAYOFANNOTATIONSLISTVIEW():NEW()
	oClone:oWSANNOTATIONSLISTVIEW := NIL
	If ::oWSANNOTATIONSLISTVIEW <> NIL 
		oClone:oWSANNOTATIONSLISTVIEW := {}
		aEval( ::oWSANNOTATIONSLISTVIEW , { |x| aadd( oClone:oWSANNOTATIONSLISTVIEW , x:Clone() ) } )
	Endif 
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PMSANNOTATIONS_ARRAYOFANNOTATIONSLISTVIEW
	Local nRElem1, oNodes1, nTElem1
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNodes1 :=  WSAdvValue( oResponse,"_ANNOTATIONSLISTVIEW","ANNOTATIONSLISTVIEW",{},NIL,.T.,"O",NIL,NIL) 
	nTElem1 := len(oNodes1)
	For nRElem1 := 1 to nTElem1 
		If !WSIsNilNode( oNodes1[nRElem1] )
			aadd(::oWSANNOTATIONSLISTVIEW , PMSANNOTATIONS_ANNOTATIONSLISTVIEW():New() )
			::oWSANNOTATIONSLISTVIEW[len(::oWSANNOTATIONSLISTVIEW)]:SoapRecv(oNodes1[nRElem1])
		Endif
	Next
Return

// WSDL Data Structure ARRAYOFBRWHEADER

WSSTRUCT PMSANNOTATIONS_ARRAYOFBRWHEADER
	WSDATA   oWSBRWHEADER              AS PMSANNOTATIONS_BRWHEADER OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PMSANNOTATIONS_ARRAYOFBRWHEADER
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PMSANNOTATIONS_ARRAYOFBRWHEADER
	::oWSBRWHEADER         := {} // Array Of  PMSANNOTATIONS_BRWHEADER():New()
Return

WSMETHOD CLONE WSCLIENT PMSANNOTATIONS_ARRAYOFBRWHEADER
	Local oClone := PMSANNOTATIONS_ARRAYOFBRWHEADER():NEW()
	oClone:oWSBRWHEADER := NIL
	If ::oWSBRWHEADER <> NIL 
		oClone:oWSBRWHEADER := {}
		aEval( ::oWSBRWHEADER , { |x| aadd( oClone:oWSBRWHEADER , x:Clone() ) } )
	Endif 
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PMSANNOTATIONS_ARRAYOFBRWHEADER
	Local nRElem1, oNodes1, nTElem1
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNodes1 :=  WSAdvValue( oResponse,"_BRWHEADER","BRWHEADER",{},NIL,.T.,"O",NIL,NIL) 
	nTElem1 := len(oNodes1)
	For nRElem1 := 1 to nTElem1 
		If !WSIsNilNode( oNodes1[nRElem1] )
			aadd(::oWSBRWHEADER , PMSANNOTATIONS_BRWHEADER():New() )
			::oWSBRWHEADER[len(::oWSBRWHEADER)]:SoapRecv(oNodes1[nRElem1])
		Endif
	Next
Return

// WSDL Data Structure ARRAYOFBRWHEADERPMS

WSSTRUCT PMSANNOTATIONS_ARRAYOFBRWHEADERPMS
	WSDATA   oWSBRWHEADERPMS           AS PMSANNOTATIONS_BRWHEADERPMS OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PMSANNOTATIONS_ARRAYOFBRWHEADERPMS
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PMSANNOTATIONS_ARRAYOFBRWHEADERPMS
	::oWSBRWHEADERPMS      := {} // Array Of  PMSANNOTATIONS_BRWHEADERPMS():New()
Return

WSMETHOD CLONE WSCLIENT PMSANNOTATIONS_ARRAYOFBRWHEADERPMS
	Local oClone := PMSANNOTATIONS_ARRAYOFBRWHEADERPMS():NEW()
	oClone:oWSBRWHEADERPMS := NIL
	If ::oWSBRWHEADERPMS <> NIL 
		oClone:oWSBRWHEADERPMS := {}
		aEval( ::oWSBRWHEADERPMS , { |x| aadd( oClone:oWSBRWHEADERPMS , x:Clone() ) } )
	Endif 
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PMSANNOTATIONS_ARRAYOFBRWHEADERPMS
	Local nRElem1, oNodes1, nTElem1
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNodes1 :=  WSAdvValue( oResponse,"_BRWHEADERPMS","BRWHEADERPMS",{},NIL,.T.,"O",NIL,NIL) 
	nTElem1 := len(oNodes1)
	For nRElem1 := 1 to nTElem1 
		If !WSIsNilNode( oNodes1[nRElem1] )
			aadd(::oWSBRWHEADERPMS , PMSANNOTATIONS_BRWHEADERPMS():New() )
			::oWSBRWHEADERPMS[len(::oWSBRWHEADERPMS)]:SoapRecv(oNodes1[nRElem1])
		Endif
	Next
Return

// WSDL Data Structure MESSAGEVIEW

WSSTRUCT PMSANNOTATIONS_MESSAGEVIEW
	WSDATA   cMESSAGETEXT              AS string
	WSDATA   nMESSAGETYPE              AS float
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PMSANNOTATIONS_MESSAGEVIEW
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PMSANNOTATIONS_MESSAGEVIEW
Return

WSMETHOD CLONE WSCLIENT PMSANNOTATIONS_MESSAGEVIEW
	Local oClone := PMSANNOTATIONS_MESSAGEVIEW():NEW()
	oClone:cMESSAGETEXT         := ::cMESSAGETEXT
	oClone:nMESSAGETYPE         := ::nMESSAGETYPE
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PMSANNOTATIONS_MESSAGEVIEW
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::cMESSAGETEXT       :=  WSAdvValue( oResponse,"_MESSAGETEXT","string",NIL,"Property cMESSAGETEXT as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::nMESSAGETYPE       :=  WSAdvValue( oResponse,"_MESSAGETYPE","float",NIL,"Property nMESSAGETYPE as s:float on SOAP Response not found.",NIL,"N",NIL,NIL) 
Return

// WSDL Data Structure ANNOTATIONVIEW

WSSTRUCT PMSANNOTATIONS_ANNOTATIONVIEW
	WSDATA   nANNOTATIONCOST1          AS float OPTIONAL
	WSDATA   dANNOTATIONDATE           AS date OPTIONAL
	WSDATA   nDBRECORD                 AS integer OPTIONAL
	WSDATA   cEXECUTEDINITIALHOUR      AS string OPTIONAL
	WSDATA   cFINALHOUREXECUTED        AS string OPTIONAL
	WSDATA   oWSNOTES                  AS PMSANNOTATIONS_ARRAYOFNOTESVIEW OPTIONAL
	WSDATA   nNUMBEROFHOURS            AS float OPTIONAL
	WSDATA   cOBS                      AS string OPTIONAL
	WSDATA   cPRODUCTCODE              AS string OPTIONAL
	WSDATA   cPROJECTCODE              AS string OPTIONAL
	WSDATA   cPROJECTTASK              AS string OPTIONAL
	WSDATA   cPROJECTVERSION           AS string OPTIONAL
	WSDATA   cRESOURCECODE             AS string OPTIONAL
	WSDATA   cREVISIONCONTROL          AS string OPTIONAL
	WSDATA   cSEQUENTIALNUMBER         AS string OPTIONAL
	WSDATA   oWSUSERFIELDS             AS PMSANNOTATIONS_ARRAYOFUSERFIELD OPTIONAL
	WSDATA   cWAREHOUSECODE            AS string OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPSEND
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PMSANNOTATIONS_ANNOTATIONVIEW
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PMSANNOTATIONS_ANNOTATIONVIEW
Return

WSMETHOD CLONE WSCLIENT PMSANNOTATIONS_ANNOTATIONVIEW
	Local oClone := PMSANNOTATIONS_ANNOTATIONVIEW():NEW()
	oClone:nANNOTATIONCOST1     := ::nANNOTATIONCOST1
	oClone:dANNOTATIONDATE      := ::dANNOTATIONDATE
	oClone:nDBRECORD            := ::nDBRECORD
	oClone:cEXECUTEDINITIALHOUR := ::cEXECUTEDINITIALHOUR
	oClone:cFINALHOUREXECUTED   := ::cFINALHOUREXECUTED
	oClone:oWSNOTES             := IIF(::oWSNOTES = NIL , NIL , ::oWSNOTES:Clone() )
	oClone:nNUMBEROFHOURS       := ::nNUMBEROFHOURS
	oClone:cOBS                 := ::cOBS
	oClone:cPRODUCTCODE         := ::cPRODUCTCODE
	oClone:cPROJECTCODE         := ::cPROJECTCODE
	oClone:cPROJECTTASK         := ::cPROJECTTASK
	oClone:cPROJECTVERSION      := ::cPROJECTVERSION
	oClone:cRESOURCECODE        := ::cRESOURCECODE
	oClone:cREVISIONCONTROL     := ::cREVISIONCONTROL
	oClone:cSEQUENTIALNUMBER    := ::cSEQUENTIALNUMBER
	oClone:oWSUSERFIELDS        := IIF(::oWSUSERFIELDS = NIL , NIL , ::oWSUSERFIELDS:Clone() )
	oClone:cWAREHOUSECODE       := ::cWAREHOUSECODE
Return oClone

WSMETHOD SOAPSEND WSCLIENT PMSANNOTATIONS_ANNOTATIONVIEW
	Local cSoap := ""
	cSoap += WSSoapValue("ANNOTATIONCOST1", ::nANNOTATIONCOST1, ::nANNOTATIONCOST1 , "float", .F. , .F., 0 , NIL, .F.,.F.) 
	cSoap += WSSoapValue("ANNOTATIONDATE", ::dANNOTATIONDATE, ::dANNOTATIONDATE , "date", .F. , .F., 0 , NIL, .F.,.F.) 
	cSoap += WSSoapValue("DBRECORD", ::nDBRECORD, ::nDBRECORD , "integer", .F. , .F., 0 , NIL, .F.,.F.) 
	cSoap += WSSoapValue("EXECUTEDINITIALHOUR", ::cEXECUTEDINITIALHOUR, ::cEXECUTEDINITIALHOUR , "string", .F. , .F., 0 , NIL, .F.,.F.) 
	cSoap += WSSoapValue("FINALHOUREXECUTED", ::cFINALHOUREXECUTED, ::cFINALHOUREXECUTED , "string", .F. , .F., 0 , NIL, .F.,.F.) 
	cSoap += WSSoapValue("NOTES", ::oWSNOTES, ::oWSNOTES , "ARRAYOFNOTESVIEW", .F. , .F., 0 , NIL, .F.,.F.) 
	cSoap += WSSoapValue("NUMBEROFHOURS", ::nNUMBEROFHOURS, ::nNUMBEROFHOURS , "float", .F. , .F., 0 , NIL, .F.,.F.) 
	cSoap += WSSoapValue("OBS", ::cOBS, ::cOBS , "string", .F. , .F., 0 , NIL, .F.,.F.) 
	cSoap += WSSoapValue("PRODUCTCODE", ::cPRODUCTCODE, ::cPRODUCTCODE , "string", .F. , .F., 0 , NIL, .F.,.F.) 
	cSoap += WSSoapValue("PROJECTCODE", ::cPROJECTCODE, ::cPROJECTCODE , "string", .F. , .F., 0 , NIL, .F.,.F.) 
	cSoap += WSSoapValue("PROJECTTASK", ::cPROJECTTASK, ::cPROJECTTASK , "string", .F. , .F., 0 , NIL, .F.,.F.) 
	cSoap += WSSoapValue("PROJECTVERSION", ::cPROJECTVERSION, ::cPROJECTVERSION , "string", .F. , .F., 0 , NIL, .F.,.F.) 
	cSoap += WSSoapValue("RESOURCECODE", ::cRESOURCECODE, ::cRESOURCECODE , "string", .F. , .F., 0 , NIL, .F.,.F.) 
	cSoap += WSSoapValue("REVISIONCONTROL", ::cREVISIONCONTROL, ::cREVISIONCONTROL , "string", .F. , .F., 0 , NIL, .F.,.F.) 
	cSoap += WSSoapValue("SEQUENTIALNUMBER", ::cSEQUENTIALNUMBER, ::cSEQUENTIALNUMBER , "string", .F. , .F., 0 , NIL, .F.,.F.) 
	cSoap += WSSoapValue("USERFIELDS", ::oWSUSERFIELDS, ::oWSUSERFIELDS , "ARRAYOFUSERFIELD", .F. , .F., 0 , NIL, .F.,.F.) 
	cSoap += WSSoapValue("WAREHOUSECODE", ::cWAREHOUSECODE, ::cWAREHOUSECODE , "string", .F. , .F., 0 , NIL, .F.,.F.) 
Return cSoap

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PMSANNOTATIONS_ANNOTATIONVIEW
	Local oNode6
	Local oNode16
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::nANNOTATIONCOST1   :=  WSAdvValue( oResponse,"_ANNOTATIONCOST1","float",NIL,NIL,NIL,"N",NIL,NIL) 
	::dANNOTATIONDATE    :=  WSAdvValue( oResponse,"_ANNOTATIONDATE","date",NIL,NIL,NIL,"D",NIL,NIL) 
	::nDBRECORD          :=  WSAdvValue( oResponse,"_DBRECORD","integer",NIL,NIL,NIL,"N",NIL,NIL) 
	::cEXECUTEDINITIALHOUR :=  WSAdvValue( oResponse,"_EXECUTEDINITIALHOUR","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cFINALHOUREXECUTED :=  WSAdvValue( oResponse,"_FINALHOUREXECUTED","string",NIL,NIL,NIL,"S",NIL,NIL) 
	oNode6 :=  WSAdvValue( oResponse,"_NOTES","ARRAYOFNOTESVIEW",NIL,NIL,NIL,"O",NIL,NIL) 
	If oNode6 != NIL
		::oWSNOTES := PMSANNOTATIONS_ARRAYOFNOTESVIEW():New()
		::oWSNOTES:SoapRecv(oNode6)
	EndIf
	::nNUMBEROFHOURS     :=  WSAdvValue( oResponse,"_NUMBEROFHOURS","float",NIL,NIL,NIL,"N",NIL,NIL) 
	::cOBS               :=  WSAdvValue( oResponse,"_OBS","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cPRODUCTCODE       :=  WSAdvValue( oResponse,"_PRODUCTCODE","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cPROJECTCODE       :=  WSAdvValue( oResponse,"_PROJECTCODE","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cPROJECTTASK       :=  WSAdvValue( oResponse,"_PROJECTTASK","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cPROJECTVERSION    :=  WSAdvValue( oResponse,"_PROJECTVERSION","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cRESOURCECODE      :=  WSAdvValue( oResponse,"_RESOURCECODE","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cREVISIONCONTROL   :=  WSAdvValue( oResponse,"_REVISIONCONTROL","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cSEQUENTIALNUMBER  :=  WSAdvValue( oResponse,"_SEQUENTIALNUMBER","string",NIL,NIL,NIL,"S",NIL,NIL) 
	oNode16 :=  WSAdvValue( oResponse,"_USERFIELDS","ARRAYOFUSERFIELD",NIL,NIL,NIL,"O",NIL,NIL) 
	If oNode16 != NIL
		::oWSUSERFIELDS := PMSANNOTATIONS_ARRAYOFUSERFIELD():New()
		::oWSUSERFIELDS:SoapRecv(oNode16)
	EndIf
	::cWAREHOUSECODE     :=  WSAdvValue( oResponse,"_WAREHOUSECODE","string",NIL,NIL,NIL,"S",NIL,NIL) 
Return

// WSDL Data Structure ANNOTATIONSLISTVIEW

WSSTRUCT PMSANNOTATIONS_ANNOTATIONSLISTVIEW
	WSDATA   dANNOTATIONDATE           AS date OPTIONAL
	WSDATA   nDBRECORD                 AS integer OPTIONAL
	WSDATA   cDOCUMENTCODE             AS string OPTIONAL
	WSDATA   cDOCUMENTITEM             AS string OPTIONAL
	WSDATA   cEXECUTEDINITIALHOUR      AS string OPTIONAL
	WSDATA   cFINALHOUREXECUTED        AS string OPTIONAL
	WSDATA   nNUMBEROFHOURS            AS float OPTIONAL
	WSDATA   cPROJECTCODE              AS string OPTIONAL
	WSDATA   cPROJECTTASK              AS string OPTIONAL
	WSDATA   cRESOURCECODE             AS string OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PMSANNOTATIONS_ANNOTATIONSLISTVIEW
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PMSANNOTATIONS_ANNOTATIONSLISTVIEW
Return

WSMETHOD CLONE WSCLIENT PMSANNOTATIONS_ANNOTATIONSLISTVIEW
	Local oClone := PMSANNOTATIONS_ANNOTATIONSLISTVIEW():NEW()
	oClone:dANNOTATIONDATE      := ::dANNOTATIONDATE
	oClone:nDBRECORD            := ::nDBRECORD
	oClone:cDOCUMENTCODE        := ::cDOCUMENTCODE
	oClone:cDOCUMENTITEM        := ::cDOCUMENTITEM
	oClone:cEXECUTEDINITIALHOUR := ::cEXECUTEDINITIALHOUR
	oClone:cFINALHOUREXECUTED   := ::cFINALHOUREXECUTED
	oClone:nNUMBEROFHOURS       := ::nNUMBEROFHOURS
	oClone:cPROJECTCODE         := ::cPROJECTCODE
	oClone:cPROJECTTASK         := ::cPROJECTTASK
	oClone:cRESOURCECODE        := ::cRESOURCECODE
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PMSANNOTATIONS_ANNOTATIONSLISTVIEW
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::dANNOTATIONDATE    :=  WSAdvValue( oResponse,"_ANNOTATIONDATE","date",NIL,NIL,NIL,"D",NIL,NIL) 
	::nDBRECORD          :=  WSAdvValue( oResponse,"_DBRECORD","integer",NIL,NIL,NIL,"N",NIL,NIL) 
	::cDOCUMENTCODE      :=  WSAdvValue( oResponse,"_DOCUMENTCODE","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cDOCUMENTITEM      :=  WSAdvValue( oResponse,"_DOCUMENTITEM","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cEXECUTEDINITIALHOUR :=  WSAdvValue( oResponse,"_EXECUTEDINITIALHOUR","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cFINALHOUREXECUTED :=  WSAdvValue( oResponse,"_FINALHOUREXECUTED","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::nNUMBEROFHOURS     :=  WSAdvValue( oResponse,"_NUMBEROFHOURS","float",NIL,NIL,NIL,"N",NIL,NIL) 
	::cPROJECTCODE       :=  WSAdvValue( oResponse,"_PROJECTCODE","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cPROJECTTASK       :=  WSAdvValue( oResponse,"_PROJECTTASK","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cRESOURCECODE      :=  WSAdvValue( oResponse,"_RESOURCECODE","string",NIL,NIL,NIL,"S",NIL,NIL) 
Return

// WSDL Data Structure BRWHEADER

WSSTRUCT PMSANNOTATIONS_BRWHEADER
	WSDATA   cHEADERCOMBOBOX           AS string OPTIONAL
	WSDATA   nHEADERDEC                AS integer
	WSDATA   cHEADERF3                 AS string OPTIONAL
	WSDATA   cHEADERFIELD              AS string
	WSDATA   lHEADEROBLIG              AS boolean OPTIONAL
	WSDATA   cHEADERPICTURE            AS string
	WSDATA   nHEADERSIZE               AS integer
	WSDATA   cHEADERTITLE              AS string
	WSDATA   cHEADERTYPE               AS string
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PMSANNOTATIONS_BRWHEADER
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PMSANNOTATIONS_BRWHEADER
Return

WSMETHOD CLONE WSCLIENT PMSANNOTATIONS_BRWHEADER
	Local oClone := PMSANNOTATIONS_BRWHEADER():NEW()
	oClone:cHEADERCOMBOBOX      := ::cHEADERCOMBOBOX
	oClone:nHEADERDEC           := ::nHEADERDEC
	oClone:cHEADERF3            := ::cHEADERF3
	oClone:cHEADERFIELD         := ::cHEADERFIELD
	oClone:lHEADEROBLIG         := ::lHEADEROBLIG
	oClone:cHEADERPICTURE       := ::cHEADERPICTURE
	oClone:nHEADERSIZE          := ::nHEADERSIZE
	oClone:cHEADERTITLE         := ::cHEADERTITLE
	oClone:cHEADERTYPE          := ::cHEADERTYPE
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PMSANNOTATIONS_BRWHEADER
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::cHEADERCOMBOBOX    :=  WSAdvValue( oResponse,"_HEADERCOMBOBOX","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::nHEADERDEC         :=  WSAdvValue( oResponse,"_HEADERDEC","integer",NIL,"Property nHEADERDEC as s:integer on SOAP Response not found.",NIL,"N",NIL,NIL) 
	::cHEADERF3          :=  WSAdvValue( oResponse,"_HEADERF3","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cHEADERFIELD       :=  WSAdvValue( oResponse,"_HEADERFIELD","string",NIL,"Property cHEADERFIELD as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::lHEADEROBLIG       :=  WSAdvValue( oResponse,"_HEADEROBLIG","boolean",NIL,NIL,NIL,"L",NIL,NIL) 
	::cHEADERPICTURE     :=  WSAdvValue( oResponse,"_HEADERPICTURE","string",NIL,"Property cHEADERPICTURE as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::nHEADERSIZE        :=  WSAdvValue( oResponse,"_HEADERSIZE","integer",NIL,"Property nHEADERSIZE as s:integer on SOAP Response not found.",NIL,"N",NIL,NIL) 
	::cHEADERTITLE       :=  WSAdvValue( oResponse,"_HEADERTITLE","string",NIL,"Property cHEADERTITLE as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cHEADERTYPE        :=  WSAdvValue( oResponse,"_HEADERTYPE","string",NIL,"Property cHEADERTYPE as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
Return

// WSDL Data Structure BRWHEADERPMS

WSSTRUCT PMSANNOTATIONS_BRWHEADERPMS
	WSDATA   cEDITABLE                 AS string OPTIONAL
	WSDATA   cHEADERCOMBOBOX           AS string OPTIONAL
	WSDATA   nHEADERDEC                AS integer OPTIONAL
	WSDATA   cHEADERF3                 AS string OPTIONAL
	WSDATA   cHEADERFIELD              AS string OPTIONAL
	WSDATA   cHEADERFOLDER             AS string OPTIONAL
	WSDATA   lHEADEROBLIG              AS boolean OPTIONAL
	WSDATA   cHEADERORDER              AS string OPTIONAL
	WSDATA   cHEADERPICTURE            AS string OPTIONAL
	WSDATA   nHEADERSIZE               AS integer OPTIONAL
	WSDATA   cHEADERTITLE              AS string OPTIONAL
	WSDATA   cHEADERTYPE               AS string OPTIONAL
	WSDATA   cHEADERTYPE2              AS string OPTIONAL
	WSDATA   cINITIALVALUE             AS string OPTIONAL
	WSDATA   cPROPRIETYNAME            AS string OPTIONAL
	WSDATA   lUSERFIELD                AS boolean OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PMSANNOTATIONS_BRWHEADERPMS
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PMSANNOTATIONS_BRWHEADERPMS
Return

WSMETHOD CLONE WSCLIENT PMSANNOTATIONS_BRWHEADERPMS
	Local oClone := PMSANNOTATIONS_BRWHEADERPMS():NEW()
	oClone:cEDITABLE            := ::cEDITABLE
	oClone:cHEADERCOMBOBOX      := ::cHEADERCOMBOBOX
	oClone:nHEADERDEC           := ::nHEADERDEC
	oClone:cHEADERF3            := ::cHEADERF3
	oClone:cHEADERFIELD         := ::cHEADERFIELD
	oClone:cHEADERFOLDER        := ::cHEADERFOLDER
	oClone:lHEADEROBLIG         := ::lHEADEROBLIG
	oClone:cHEADERORDER         := ::cHEADERORDER
	oClone:cHEADERPICTURE       := ::cHEADERPICTURE
	oClone:nHEADERSIZE          := ::nHEADERSIZE
	oClone:cHEADERTITLE         := ::cHEADERTITLE
	oClone:cHEADERTYPE          := ::cHEADERTYPE
	oClone:cHEADERTYPE2         := ::cHEADERTYPE2
	oClone:cINITIALVALUE        := ::cINITIALVALUE
	oClone:cPROPRIETYNAME       := ::cPROPRIETYNAME
	oClone:lUSERFIELD           := ::lUSERFIELD
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PMSANNOTATIONS_BRWHEADERPMS
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::cEDITABLE          :=  WSAdvValue( oResponse,"_EDITABLE","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cHEADERCOMBOBOX    :=  WSAdvValue( oResponse,"_HEADERCOMBOBOX","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::nHEADERDEC         :=  WSAdvValue( oResponse,"_HEADERDEC","integer",NIL,NIL,NIL,"N",NIL,NIL) 
	::cHEADERF3          :=  WSAdvValue( oResponse,"_HEADERF3","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cHEADERFIELD       :=  WSAdvValue( oResponse,"_HEADERFIELD","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cHEADERFOLDER      :=  WSAdvValue( oResponse,"_HEADERFOLDER","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::lHEADEROBLIG       :=  WSAdvValue( oResponse,"_HEADEROBLIG","boolean",NIL,NIL,NIL,"L",NIL,NIL) 
	::cHEADERORDER       :=  WSAdvValue( oResponse,"_HEADERORDER","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cHEADERPICTURE     :=  WSAdvValue( oResponse,"_HEADERPICTURE","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::nHEADERSIZE        :=  WSAdvValue( oResponse,"_HEADERSIZE","integer",NIL,NIL,NIL,"N",NIL,NIL) 
	::cHEADERTITLE       :=  WSAdvValue( oResponse,"_HEADERTITLE","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cHEADERTYPE        :=  WSAdvValue( oResponse,"_HEADERTYPE","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cHEADERTYPE2       :=  WSAdvValue( oResponse,"_HEADERTYPE2","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cINITIALVALUE      :=  WSAdvValue( oResponse,"_INITIALVALUE","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cPROPRIETYNAME     :=  WSAdvValue( oResponse,"_PROPRIETYNAME","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::lUSERFIELD         :=  WSAdvValue( oResponse,"_USERFIELD","boolean",NIL,NIL,NIL,"L",NIL,NIL) 
Return

// WSDL Data Structure ARRAYOFNOTESVIEW

WSSTRUCT PMSANNOTATIONS_ARRAYOFNOTESVIEW
	WSDATA   oWSNOTESVIEW              AS PMSANNOTATIONS_NOTESVIEW OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPSEND
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PMSANNOTATIONS_ARRAYOFNOTESVIEW
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PMSANNOTATIONS_ARRAYOFNOTESVIEW
	::oWSNOTESVIEW         := {} // Array Of  PMSANNOTATIONS_NOTESVIEW():New()
Return

WSMETHOD CLONE WSCLIENT PMSANNOTATIONS_ARRAYOFNOTESVIEW
	Local oClone := PMSANNOTATIONS_ARRAYOFNOTESVIEW():NEW()
	oClone:oWSNOTESVIEW := NIL
	If ::oWSNOTESVIEW <> NIL 
		oClone:oWSNOTESVIEW := {}
		aEval( ::oWSNOTESVIEW , { |x| aadd( oClone:oWSNOTESVIEW , x:Clone() ) } )
	Endif 
Return oClone

WSMETHOD SOAPSEND WSCLIENT PMSANNOTATIONS_ARRAYOFNOTESVIEW
	Local cSoap := ""
	aEval( ::oWSNOTESVIEW , {|x| cSoap := cSoap  +  WSSoapValue("NOTESVIEW", x , x , "NOTESVIEW", .F. , .F., 0 , NIL, .F.,.F.)  } ) 
Return cSoap

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PMSANNOTATIONS_ARRAYOFNOTESVIEW
	Local nRElem1, oNodes1, nTElem1
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNodes1 :=  WSAdvValue( oResponse,"_NOTESVIEW","NOTESVIEW",{},NIL,.T.,"O",NIL,NIL) 
	nTElem1 := len(oNodes1)
	For nRElem1 := 1 to nTElem1 
		If !WSIsNilNode( oNodes1[nRElem1] )
			aadd(::oWSNOTESVIEW , PMSANNOTATIONS_NOTESVIEW():New() )
			::oWSNOTESVIEW[len(::oWSNOTESVIEW)]:SoapRecv(oNodes1[nRElem1])
		Endif
	Next
Return

// WSDL Data Structure ARRAYOFUSERFIELD

WSSTRUCT PMSANNOTATIONS_ARRAYOFUSERFIELD
	WSDATA   oWSUSERFIELD              AS PMSANNOTATIONS_USERFIELD OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPSEND
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PMSANNOTATIONS_ARRAYOFUSERFIELD
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PMSANNOTATIONS_ARRAYOFUSERFIELD
	::oWSUSERFIELD         := {} // Array Of  PMSANNOTATIONS_USERFIELD():New()
Return

WSMETHOD CLONE WSCLIENT PMSANNOTATIONS_ARRAYOFUSERFIELD
	Local oClone := PMSANNOTATIONS_ARRAYOFUSERFIELD():NEW()
	oClone:oWSUSERFIELD := NIL
	If ::oWSUSERFIELD <> NIL 
		oClone:oWSUSERFIELD := {}
		aEval( ::oWSUSERFIELD , { |x| aadd( oClone:oWSUSERFIELD , x:Clone() ) } )
	Endif 
Return oClone

WSMETHOD SOAPSEND WSCLIENT PMSANNOTATIONS_ARRAYOFUSERFIELD
	Local cSoap := ""
	aEval( ::oWSUSERFIELD , {|x| cSoap := cSoap  +  WSSoapValue("USERFIELD", x , x , "USERFIELD", .F. , .F., 0 , NIL, .F.,.F.)  } ) 
Return cSoap

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PMSANNOTATIONS_ARRAYOFUSERFIELD
	Local nRElem1, oNodes1, nTElem1
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNodes1 :=  WSAdvValue( oResponse,"_USERFIELD","USERFIELD",{},NIL,.T.,"O",NIL,NIL) 
	nTElem1 := len(oNodes1)
	For nRElem1 := 1 to nTElem1 
		If !WSIsNilNode( oNodes1[nRElem1] )
			aadd(::oWSUSERFIELD , PMSANNOTATIONS_USERFIELD():New() )
			::oWSUSERFIELD[len(::oWSUSERFIELD)]:SoapRecv(oNodes1[nRElem1])
		Endif
	Next
Return

// WSDL Data Structure NOTESVIEW

WSSTRUCT PMSANNOTATIONS_NOTESVIEW
	WSDATA   cNOTES                    AS string OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPSEND
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PMSANNOTATIONS_NOTESVIEW
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PMSANNOTATIONS_NOTESVIEW
Return

WSMETHOD CLONE WSCLIENT PMSANNOTATIONS_NOTESVIEW
	Local oClone := PMSANNOTATIONS_NOTESVIEW():NEW()
	oClone:cNOTES               := ::cNOTES
Return oClone

WSMETHOD SOAPSEND WSCLIENT PMSANNOTATIONS_NOTESVIEW
	Local cSoap := ""
	cSoap += WSSoapValue("NOTES", ::cNOTES, ::cNOTES , "string", .F. , .F., 0 , NIL, .F.,.F.) 
Return cSoap

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PMSANNOTATIONS_NOTESVIEW
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::cNOTES             :=  WSAdvValue( oResponse,"_NOTES","string",NIL,NIL,NIL,"S",NIL,NIL) 
Return

// WSDL Data Structure USERFIELD

WSSTRUCT PMSANNOTATIONS_USERFIELD
	WSDATA   cUSERCOMBOBOX             AS string OPTIONAL
	WSDATA   nUSERDEC                  AS integer OPTIONAL
	WSDATA   cUSERF3                   AS string OPTIONAL
	WSDATA   cUSERNAME                 AS string
	WSDATA   lUSEROBLIG                AS boolean OPTIONAL
	WSDATA   cUSERPICTURE              AS string OPTIONAL
	WSDATA   nUSERSIZE                 AS integer OPTIONAL
	WSDATA   cUSERTAG                  AS string OPTIONAL
	WSDATA   cUSERTITLE                AS string OPTIONAL
	WSDATA   cUSERTYPE                 AS string
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPSEND
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT PMSANNOTATIONS_USERFIELD
	::Init()
Return Self

WSMETHOD INIT WSCLIENT PMSANNOTATIONS_USERFIELD
Return

WSMETHOD CLONE WSCLIENT PMSANNOTATIONS_USERFIELD
	Local oClone := PMSANNOTATIONS_USERFIELD():NEW()
	oClone:cUSERCOMBOBOX        := ::cUSERCOMBOBOX
	oClone:nUSERDEC             := ::nUSERDEC
	oClone:cUSERF3              := ::cUSERF3
	oClone:cUSERNAME            := ::cUSERNAME
	oClone:lUSEROBLIG           := ::lUSEROBLIG
	oClone:cUSERPICTURE         := ::cUSERPICTURE
	oClone:nUSERSIZE            := ::nUSERSIZE
	oClone:cUSERTAG             := ::cUSERTAG
	oClone:cUSERTITLE           := ::cUSERTITLE
	oClone:cUSERTYPE            := ::cUSERTYPE
Return oClone

WSMETHOD SOAPSEND WSCLIENT PMSANNOTATIONS_USERFIELD
	Local cSoap := ""
	cSoap += WSSoapValue("USERCOMBOBOX", ::cUSERCOMBOBOX, ::cUSERCOMBOBOX , "string", .F. , .F., 0 , NIL, .F.,.F.) 
	cSoap += WSSoapValue("USERDEC", ::nUSERDEC, ::nUSERDEC , "integer", .F. , .F., 0 , NIL, .F.,.F.) 
	cSoap += WSSoapValue("USERF3", ::cUSERF3, ::cUSERF3 , "string", .F. , .F., 0 , NIL, .F.,.F.) 
	cSoap += WSSoapValue("USERNAME", ::cUSERNAME, ::cUSERNAME , "string", .T. , .F., 0 , NIL, .F.,.F.) 
	cSoap += WSSoapValue("USEROBLIG", ::lUSEROBLIG, ::lUSEROBLIG , "boolean", .F. , .F., 0 , NIL, .F.,.F.) 
	cSoap += WSSoapValue("USERPICTURE", ::cUSERPICTURE, ::cUSERPICTURE , "string", .F. , .F., 0 , NIL, .F.,.F.) 
	cSoap += WSSoapValue("USERSIZE", ::nUSERSIZE, ::nUSERSIZE , "integer", .F. , .F., 0 , NIL, .F.,.F.) 
	cSoap += WSSoapValue("USERTAG", ::cUSERTAG, ::cUSERTAG , "string", .F. , .F., 0 , NIL, .F.,.F.) 
	cSoap += WSSoapValue("USERTITLE", ::cUSERTITLE, ::cUSERTITLE , "string", .F. , .F., 0 , NIL, .F.,.F.) 
	cSoap += WSSoapValue("USERTYPE", ::cUSERTYPE, ::cUSERTYPE , "string", .T. , .F., 0 , NIL, .F.,.F.) 
Return cSoap

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT PMSANNOTATIONS_USERFIELD
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::cUSERCOMBOBOX      :=  WSAdvValue( oResponse,"_USERCOMBOBOX","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::nUSERDEC           :=  WSAdvValue( oResponse,"_USERDEC","integer",NIL,NIL,NIL,"N",NIL,NIL) 
	::cUSERF3            :=  WSAdvValue( oResponse,"_USERF3","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cUSERNAME          :=  WSAdvValue( oResponse,"_USERNAME","string",NIL,"Property cUSERNAME as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::lUSEROBLIG         :=  WSAdvValue( oResponse,"_USEROBLIG","boolean",NIL,NIL,NIL,"L",NIL,NIL) 
	::cUSERPICTURE       :=  WSAdvValue( oResponse,"_USERPICTURE","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::nUSERSIZE          :=  WSAdvValue( oResponse,"_USERSIZE","integer",NIL,NIL,NIL,"N",NIL,NIL) 
	::cUSERTAG           :=  WSAdvValue( oResponse,"_USERTAG","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cUSERTITLE         :=  WSAdvValue( oResponse,"_USERTITLE","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cUSERTYPE          :=  WSAdvValue( oResponse,"_USERTYPE","string",NIL,"Property cUSERTYPE as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
Return


