#define AUDITO_ENDPOINT 1
#define COPART_ENDPOINT 2
#define FATURA_ENDPOINT 3
#define HEALTHCHECK_ENDPOINT 4
#define INTERCHANGE_ENDPOINT 5
#define INTERCHANGECANCEL_ENDPOINT 6
#define CODIGOTRANSACAOIE "00600"
#define NUMEROVERSAOPTU "070"

//
