#include "protheus.ch"

/*/-----------------------------------------------------------
{Protheus.doc} OMSA060SM 
Realiza a chamada do aplicativo de Cadastro de Veículos Via Smart X
via Menu
Documentação técnica SMART X 
https://tdn.totvs.com/pages/releaseview.action?pageId=900448160

@author Rafael Souza
@since 11/02/2025
@version 1.0
-----------------------------------------------------------/*/ 
function OMSA060SM()
    oLauncher := totvs.framework.application.smartx.launcher():new()
    oLauncher:setInterface("totvs.protheus.supply.veiculo.interface.omsa060")
    oLauncher:open()
Return 
