#INCLUDE "PROTHEUS.CH" 
#INCLUDE "FWMVCDEF.CH" 
#INCLUDE "TAFA227.CH" 

//-------------------------------------------------------------------
/*/{Protheus.doc} TAFA227
Cadastro MVC de Situação Geradora do Acidente de Trabalho - Tabela 16


@author Anderson Costa
@since 09/08/2013
@version 1.0

/*/ 
//-------------------------------------------------------------------
Function TAFA227()

	Local   oBrw        :=  FWmBrowse():New()

	oBrw:SetDescription(STR0001)    //"Cadastro de Situação Geradora do Acidente de Trabalho"
	oBrw:SetAlias( 'C8L')
	oBrw:SetMenuDef( 'TAFA227' )
	oBrw:Activate()

Return
//-------------------------------------------------------------------
/*/{Protheus.doc} MenuDef
Funcao generica MVC com as opcoes de menu

@author Anderson Costa
@since 09/08/2013
@version 1.0
/*/
//-------------------------------------------------------------------
Static Function MenuDef()
Return XFUNMnuTAF( "TAFA227" )
//-------------------------------------------------------------------
/*/{Protheus.doc} ModelDef
Funcao generica MVC do model

@return oModel - Objeto do Modelo MVC

@author Anderson Costa
@since 09/08/2013
@version 1.0
/*/
//-------------------------------------------------------------------
Static Function ModelDef()

	Local oStruC8L  :=  FWFormStruct( 1, 'C8L' )
	Local oModel    :=  MPFormModel():New( 'TAFA227' )

	oModel:AddFields('MODEL_C8L', /*cOwner*/, oStruC8L)
	oModel:GetModel('MODEL_C8L'):SetPrimaryKey({'C8L_FILIAL', 'C8L_ID'})

Return oModel
//-------------------------------------------------------------------
/*/{Protheus.doc} ViewDef
Funcao generica MVC do View

@return oView - Objeto da View MVC

@author Anderson Costa
@since 09/08/2013
@version 1.0
/*/
//-------------------------------------------------------------------
Static Function ViewDef()

	Local   oModel      :=  FWLoadModel( 'TAFA227' )
	Local   oStruC8L    :=  FWFormStruct( 2, 'C8L' )
	Local   oView       :=  FWFormView():New()

	oView:SetModel( oModel )
	oView:AddField( 'VIEW_C8L', oStruC8L, 'MODEL_C8L' )

	oView:EnableTitleView( 'VIEW_C8L', STR0001 )    //"Cadastro de Situação Geradora do Acidente de Trabalho"
	oView:CreateHorizontalBox( 'FIELDSC8L', 100 )
	oView:SetOwnerView( 'VIEW_C8L', 'FIELDSC8L' )

Return oView

//-------------------------------------------------------------------
/*/{Protheus.doc} FAtuCont

Rotina para carga e atualização da tabela autocontida.

@Param		nVerEmp	-	Versão corrente na empresa
			nVerAtu	-	Versão atual ( passado como referência )

@Return	aRet		-	Array com estrutura de campos e conteúdo da tabela

@Author	Felipe de Carvalho Seolin
@Since		24/11/2015
@Version	1.0
/*/
//-------------------------------------------------------------------
Static Function FAtuCont( nVerEmp, nVerAtu )

	Local aHeader	:=	{}
	Local aBody		:=	{}
	Local aRet		:=	{}

	If TAFColumnPos("C8L_APLICA")

		nVerAtu := 1032.01
	
		If nVerEmp < nVerAtu

			aAdd( aHeader, "C8L_FILIAL" )
			aAdd( aHeader, "C8L_ID" 	)
			aAdd( aHeader, "C8L_CODIGO" )
			aAdd( aHeader, "C8L_DESCRI" )
			aAdd( aHeader, "C8L_APLICA" )
			aAdd( aHeader, "C8L_VALIDA" )

			aAdd( aBody, { "", "000001", "200004300", "IMPACTO DE PESSOA CONTRA OBJETO PARADO", "APLICA-SE A CASOS EM QUE A LESÃO FOI PRODUZIDA POR IMPACTO DA PESSOA ACIDENTADA CONTRA A FONTE DA LESÃO, TENDO SIDO O MOVIMENTO QUE PRODUZIU O CONTATO  ORIGINALMENTE O DA PESSOA, E NÃO O DA FONTE DA LESÃO, EXCETO QUANDO O MOVIMENTO DO ACIDENTADO TIVER SIDO PROVOCADO POR QUEDA. INCLUI CASOS DE ALGUÉM CHOCAR-SE CONTRA ALGUMA COISA, TROPEÇAR EM ALGUMA COISA, SER EMPURRADO OU PROJETADO CONTRA ALGUMA COISA, ETC. NÃO INCLUI CASOS DE SALTO PARA NÍVEL INFERIOR."										, "" } )
			aAdd( aBody, { "", "000002", "200004600", "IMPACTO DE PESSOA CONTRA OBJETO EM MOVIMENTO", "APLICA-SE A CASOS EM QUE A LESÃO FOI PRODUZIDA POR IMPACTO DA PESSOA ACIDENTADA CONTRA A FONTE DA LESÃO, TENDO SIDO O MOVIMENTO QUE PRODUZIU O CONTATO ORIGINALMENTE O DA PESSOA, E NÃO O DA FONTE DA LESÃO, EXCETO QUANDO O MOVIMENTO DO ACIDENTADO TIVER SIDO PROVOCADO POR QUEDA. INCLUI CASOS DE ALGUÉM CHOCAR-SE CONTRA ALGUMA COISA, TROPEÇAR EM ALGUMA COISA, SER EMPURRADO OU PROJETADO CONTRA ALGUMA COISA, ETC. NÃO INCLUI CASOS DE SALTO PARA NÍVEL INFERIOR."								, "" } )
			aAdd( aBody, { "", "000003", "200008300", "IMPACTO SOFRIDO POR PESSOA, DE OBJETO QUE CAI", "APLICA-SE A CASOS EM QUE A LESÃO FOI PRODUZIDA POR IMPACTO ENTRE O ACIDENTADO E A FONTE DA LESÃO, TENDO SIDO DA FONTE DA LESÃO, E NÃO DO ACIDENTADO, O MOVIMENTO QUE ORIGINOU O CONTATO."																																																																												, "" } )
			aAdd( aBody, { "", "000004", "200008600", "IMPACTO SOFRIDO POR PESSOA, DE OBJETO PROJETADO", "APLICA-SE A CASOS EM QUE A LESÃO FOI PRODUZIDA POR IMPACTO ENTRE O ACIDENTADO E A FONTE DA LESÃO, TENDO SIDO DA FONTE DA LESÃO, E NÃO DO ACIDENTADO, O MOVIMENTO QUE ORIGINOU O CONTATO."																																																																												, "" } )
			aAdd( aBody, { "", "000005", "200008900", "IMPACTO SOFRIDO POR PESSOA, NIC", "APLICA-SE A CASOS EM QUE A LESÃO FOI PRODUZIDA POR IMPACTO ENTRE O ACIDENTADO E A FONTE DA LESÃO, TENDO SIDO DA FONTE DA LESÃO, E NÃO DO ACIDENTADO, O MOVIMENTO QUE ORIGINOU O CONTATO."																																																																																, "" } )
			aAdd( aBody, { "", "000006", "200012200", "QUEDA DE PESSOA COM DIFERENÇA DE NÍVEL DE ANDAIME, PASSAGEM, PLATAFORMA, ETC", "APLICA-SE A CASOS EM QUE A LESÃO FOI PRODUZIDA POR IMPACTO ENTRE O ACIDENTADO E A FONTE DA LESÃO, TENDO SIDO DO ACIDENTADO O MOVIMENTO QUE PRODUZIU O CONTATO, NAS SEGUINTES CIRCUNSTÂNCIAS: 1) O MOVIMENTO DO ACIDENTADO FOI DEVIDO À AÇÃO DA GRAVIDADE. 2) O PONTO DE CONTATO COM A FONTE DA LESÃO ESTAVA ABAIXO DA SUPERFÍCIE QUE SUPORTAVA O ACIDENTADO NO INÍCIO DA QUEDA. INCLUI SALTO PARA NÍVEL INFERIOR."														, "" } )
			aAdd( aBody, { "", "000007", "200012300", "QUEDA DE PESSOA COM DIFERENÇA DE NÍVEL DE ESCADA MÓVEL OU FIXADA CUJOS DEGRAUS NÃO PERMITEM O APOIO INTEGRAL DO PÉ", "APLICA-SE A CASOS EM QUE A LESÃO FOI PRODUZIDA POR IMPACTO ENTRE O ACIDENTADO E A FONTE DA LESÃO, TENDO SIDO DO ACIDENTADO O MOVIMENTO QUE PRODUZIU O CONTATO, NAS SEGUINTES CIRCUNSTÂNCIAS: 1) O MOVIMENTO DO ACIDENTADO FOI DEVIDO À AÇÃO DA GRAVIDADE. 2) O PONTO DE CONTATO COM A FONTE DA LESÃO ESTAVA ABAIXO DA SUPERFÍCIE QUE SUPORTAVA O ACIDENTADO NO INÍCIO DA QUEDA. INCLUI SALTO PARA NÍVEL INFERIOR."					, "" } )
			aAdd( aBody, { "", "000008", "200012400", "QUEDA DE PESSOA COM DIFERENÇA DE NÍVEL DE MATERIAL EMPILHADO", "APLICA-SE A CASOS EM QUE A LESÃO FOI PRODUZIDA POR IMPACTO ENTRE O ACIDENTADO E A FONTE DA LESÃO, TENDO SIDO DO ACIDENTADO O MOVIMENTO QUE PRODUZIU O CONTATO, NAS SEGUINTES CIRCUNSTÂNCIAS: 1) O MOVIMENTO DO ACIDENTADO FOI DEVIDO À AÇÃO DA GRAVIDADE. 2) O PONTO DE CONTATO COM A FONTE DA LESÃO ESTAVA ABAIXO DA SUPERFÍCIE QUE SUPORTAVA O ACIDENTADO NO INÍCIO DA QUEDA. INCLUI SALTO PARA NÍVEL INFERIOR."																		, "" } )
			aAdd( aBody, { "", "000009", "200012500", "QUEDA DE PESSOA COM DIFERENÇA DE NÍVEL DE VEÍCULO", "APLICA-SE A CASOS EM QUE A LESÃO FOI PRODUZIDA POR IMPACTO ENTRE O ACIDENTADO E A FONTE DA LESÃO, TENDO SIDO DO ACIDENTADO O MOVIMENTO QUE PRODUZIU O CONTATO, NAS SEGUINTES CIRCUNSTÂNCIAS: 1) O MOVIMENTO DO ACIDENTADO FOI DEVIDO À AÇÃO DA GRAVIDADE. 2) O PONTO DE CONTATO COM A FONTE DA LESÃO ESTAVA ABAIXO DA SUPERFÍCIE QUE SUPORTAVA O ACIDENTADO NO INÍCIO DA QUEDA. INCLUI SALTO PARA NÍVEL INFERIOR."																					, "" } )
			aAdd( aBody, { "", "000010", "200012600", "QUEDA DE PESSOA COM DIFERENÇA DE NÍVEL EM ESCADA PERMANENTE CUJOS DEGRAUS PERMITEM APOIO INTEGRAL DO PÉ", "APLICA-SE A CASOS EM QUE A LESÃO FOI PRODUZIDA POR IMPACTO ENTRE O ACIDENTADO E A FONTE DA LESÃO, TENDO SIDO DO ACIDENTADO O MOVIMENTO QUE PRODUZIU O CONTATO, NAS SEGUINTES CIRCUNSTÂNCIAS: 1) O MOVIMENTO DO ACIDENTADO FOI DEVIDO À AÇÃO DA GRAVIDADE. 2) O PONTO DE CONTATO COM A FONTE DA LESÃO ESTAVA ABAIXO DA SUPERFÍCIE QUE SUPORTAVA O ACIDENTADO NO INÍCIO DA QUEDA. INCLUI SALTO PARA NÍVEL INFERIOR."							, "" } )
			aAdd( aBody, { "", "000011", "200012700", "QUEDA DE PESSOA COM DIFERENÇA DE NÍVEL EM POÇO, ESCAVAÇÃO, ABERTURA NO PISO, ETC. (DA BORDA DA ABERTURA)", "APLICA-SE A CASOS EM QUE A LESÃO FOI PRODUZIDA POR IMPACTO ENTRE O ACIDENTADO E A FONTE DA LESÃO, TENDO SIDO DO ACIDENTADO O MOVIMENTO QUE PRODUZIU O CONTATO, NAS SEGUINTES CIRCUNSTÂNCIAS: 1) O MOVIMENTO DO ACIDENTADO FOI DEVIDO À AÇÃO DA GRAVIDADE. 2) O PONTO DE CONTATO COM A FONTE DA LESÃO ESTAVA ABAIXO DA SUPERFÍCIE QUE SUPORTAVA O ACIDENTADO NO INÍCIO DA QUEDA. INCLUI SALTO PARA NÍVEL INFERIOR."							, "" } )
			aAdd( aBody, { "", "000012", "200012900", "QUEDA DE PESSOA COM DIFERENÇA DE NÍVEL, NIC", "APLICA-SE A CASOS EM QUE A LESÃO FOI PRODUZIDA POR IMPACTO ENTRE O ACIDENTADO E A FONTE DA LESÃO, TENDO SIDO DO ACIDENTADO O MOVIMENTO QUE PRODUZIU O CONTATO, NAS SEGUINTES CIRCUNSTÂNCIAS: 1) O MOVIMENTO DO ACIDENTADO FOI DEVIDO À AÇÃO DA GRAVIDADE. 2) O PONTO DE CONTATO COM A FONTE DA LESÃO ESTAVA ABAIXO DA SUPERFÍCIE QUE SUPORTAVA O ACIDENTADO NO INÍCIO DA QUEDA. INCLUI SALTO PARA NÍVEL INFERIOR."																						, "" } )
			aAdd( aBody, { "", "000013", "200016300", "QUEDA DE PESSOA EM MESMO NÍVEL EM PASSAGEM OU SUPERFÍCIE DE SUSTENTAÇÃO", "APLIAPLICA-SE A CASOS EM QUE A LESÃO FOI PRODUZIDA POR IMPACTO ENTRE O ACIDENTADO E UM OBJETO EXTERNO, TENDO SIDO DO ACIDENTADO O MOVIMENTO QUE PRODUZIU O CONTATO, NAS SEGUINTES CIRCUNSTÂNCIAS: 1) O MOVIMENTO DO ACIDENTADO FOI DEVIDO À AÇÃO DA GRAVIDADE, COM PERDA DO EQUILÍBRIO E IMPOSSIBILIDADE DE MANTER-SE DE PÉ. 2) O PONTO DE CONTATO COM A FONTE DA LESÃO ESTAVA, NO MOMENTO DO INÍCIO DA QUEDA, AO NÍVEL OU ACIMA DA SUPERFÍCIE QUE SUPORTAVA O ACIDENTADO."	, "" } )
			aAdd( aBody, { "", "000014", "200016600", "QUEDA DE PESSOA EM MESMO NÍVEL SOBRE OU CONTRA ALGUMA COISA", "APLICA-SE A CASOS EM QUE A LESÃO FOI PRODUZIDA POR IMPACTO ENTRE O ACIDENTADO E UM OBJETO EXTERNO, TENDO SIDO DO ACIDENTADO O MOVIMENTO QUE PRODUZIU O CONTATO, NAS SEGUINTES CIRCUNSTÂNCIAS: 1) O MOVIMENTO DO ACIDENTADO FOI DEVIDO À AÇÃO DA GRAVIDADE, COM PERDA DO EQUILÍBRIO E IMPOSSIBILIDADE DE MANTER-SE DE PÉ. 2) O PONTO DE CONTATO COM A FONTE DA LESÃO ESTAVA, NO MOMENTO DO INÍCIO DA QUEDA, AO NÍVEL OU ACIMA DA SUPERFÍCIE QUE SUPORTAVA O ACIDENTADO."					, "" } )
			aAdd( aBody, { "", "000015", "200016900", "QUEDA DE PESSOA EM MESMO NÍVEL, NIC", "APLICA-SE A CASOS EM QUE A LESÃO FOI PRODUZIDA POR IMPACTO ENTRE O ACIDENTADO E UM OBJETO EXTERNO, TENDO SIDO DO ACIDENTADO O MOVIMENTO QUE PRODUZIU O CONTATO, NAS SEGUINTES CIRCUNSTÂNCIAS: 1) O MOVIMENTO DO ACIDENTADO FOI DEVIDO À AÇÃO DA GRAVIDADE, COM PERDA DO EQUILÍBRIO E IMPOSSIBILIDADE DE MANTER-SE DE PÉ. 2) O PONTO DE CONTATO COM A FONTE DA LESÃO ESTAVA, NO MOMENTO DO INÍCIO DA QUEDA, AO NÍVEL OU ACIMA DA SUPERFÍCIE QUE SUPORTAVA O ACIDENTADO."											, "" } )
			aAdd( aBody, { "", "000016", "200020100", "APRISIONAMENTO EM, SOB OU ENTRE OBJETOS EM MOVIMENTO CONVERGENTE (CALANDRA) OU DE ENCAIXE", "APLICA-SE A CASOS, SEM IMPACTO, EM QUE A LESÃO FOI PRODUZIDA POR COMPRESSÃO, PINÇAMENTO OU ESMAGAMENTO ENTRE UM OBJETO EM MOVIMENTO E OUTRO PARADO, ENTRE DOIS OBJETOS EM MOVIMENTO OU ENTRE PARTES DE UM MESMO OBJETO. NÃO SE APLICA QUANDO A FONTE DA LESÃO FOR UM OBJETO LIVREMENTE PROJETADO OU EM QUEDA LIVRE."																																		, "" } )
			aAdd( aBody, { "", "000017", "200020300", "APRISIONAMENTO EM, SOB OU ENTRE UM OBJETO PARADO E OUTRO EM MOVIMENTO ", "APLICA-SE A CASOS, SEM IMPACTO, EM QUE A LESÃO FOI PRODUZIDA POR COMPRESSÃO, PINÇAMENTO OU ESMAGAMENTO ENTRE UM OBJETO EM MOVIMENTO E OUTRO PARADO, ENTRE DOIS OBJETOS EM MOVIMENTO OU ENTRE PARTES DE UM MESMO OBJETO. NÃO SE APLICA QUANDO A FONTE DA LESÃO FOR UM OBJETO LIVREMENTE PROJETADO OU EM QUEDA LIVRE."																																							, "" } )
			aAdd( aBody, { "", "000018", "200020500", "APRISIONAMENTO EM, SOB OU ENTRE DOIS OU MAIS OBJETOS EM  MOVIMENTO (SEM ENCAIXE)", "APLICA-SE A CASOS, SEM IMPACTO, EM QUE A LESÃO FOI PRODUZIDA POR COMPRESSÃO, PINÇAMENTO OU ESMAGAMENTO ENTRE UM OBJETO EM MOVIMENTO E OUTRO PARADO, ENTRE DOIS OBJETOS EM MOVIMENTO OU ENTRE PARTES DE UM MESMO OBJETO. NÃO SE APLICA QUANDO A FONTE DA LESÃO FOR UM OBJETO LIVREMENTE PROJETADO OU EM QUEDA LIVRE."																																					, "" } )
			aAdd( aBody, { "", "000019", "200020700", "APRISIONAMENTO EM, SOB OU ENTRE DESABAMENTO OU DESMORONAMENTO DE EDIFICAÇÃO, BARREIRA, ETC", "APLICA-SE A CASOS, SEM IMPACTO, EM QUE A LESÃO FOI PRODUZIDA POR COMPRESSÃO, PINÇAMENTO OU ESMAGAMENTO ENTRE UM OBJETO EM MOVIMENTO E OUTRO PARADO, ENTRE DOIS OBJETOS EM MOVIMENTO OU ENTRE PARTES DE UM MESMO OBJETO. NÃO SE APLICA QUANDO A FONTE DA LESÃO FOR UM OBJETO LIVREMENTE PROJETADO OU EM QUEDA LIVRE."																																		, "" } )
			aAdd( aBody, { "", "000020", "200020900", "APRISIONAMENTO EM, SOB OU ENTRE, NIC", "APLICA-SE A CASOS, SEM IMPACTO, EM QUE A LESÃO FOI PRODUZIDA POR COMPRESSÃO, PINÇAMENTO OU ESMAGAMENTO ENTRE UM OBJETO EM MOVIMENTO E OUTRO PARADO, ENTRE DOIS OBJETOS EM MOVIMENTO OU ENTRE PARTES DE UM MESMO OBJETO. NÃO SE APLICA QUANDO A FONTE DA LESÃO FOR UM OBJETO LIVREMENTE PROJETADO OU EM QUEDA LIVRE."																																																, "" } )
			aAdd( aBody, { "", "000021", "200024300", "ATRITO OU ABRASÃO POR ENCOSTAR, PISAR, AJOELHAR OU SENTAR EM OBJETO (NÃO EM VIBRAÇÃO)", "APLICA-SE A CASOS, SEM IMPACTO, EM QUE A LESÃO FOI PRODUZIDA POR PRESSÃO, VIBRAÇÃO OU ATRITO ENTRE O ACIDENTADO E A FONTE DA LESÃO."																																																																															, "" } )
			aAdd( aBody, { "", "000022", "200024400", "ATRITO OU ABRASÃO POR MANUSEAR OBJETO (NÃO EM VIBRAÇÃO)", "APLICA-SE A CASOS, SEM IMPACTO, EM QUE A LESÃO FOI PRODUZIDA POR PRESSÃO, VIBRAÇÃO OU ATRITO ENTRE O ACIDENTADO E A FONTE DA LESÃO."																																																																																							, "" } )
			aAdd( aBody, { "", "000023", "200024500", "ATRITO OU ABRASÃO POR OBJETO EM VIBRAÇÃO", "APLICA-SE A CASOS, SEM IMPACTO, EM QUE A LESÃO FOI PRODUZIDA POR PRESSÃO, VIBRAÇÃO OU ATRITO ENTRE O ACIDENTADO E A FONTE DA LESÃO."																																																																																											, "" } )
			aAdd( aBody, { "", "000024", "200024600", "ATRITO OU ABRASÃO POR CORPO ESTRANHO NO OLHO", "APLICA-SE A CASOS, SEM IMPACTO, EM QUE A LESAO FOI PRODUZIDA POR PRESSAO, VIBRACAO OU ATRITO ENTRE O ACIDENTADO E A FONTE DA LESÃO"																																																																																										, "" } )
			aAdd( aBody, { "", "000025", "200024700", "ATRITO OU ABRASÃO POR COMPRESSÃO REPETITIVA", "APLICA-SE A CASOS, SEM IMPACTO, EM QUE A LESÃO FOI PRODUZIDA POR PRESSÃO, VIBRAÇÃO OU ATRITO ENTRE O ACIDENTADO E A FONTE DA LESÃO."																																																																																										, "" } )
			aAdd( aBody, { "", "000026", "200024900", "ATRITO OU ABRASÃO, NIC", "APLICA-SE A CASOS, SEM IMPACTO, EM QUE A LESÃO FOI PRODUZIDA POR PRESSÃO, VIBRAÇÃO OU ATRITO ENTRE O ACIDENTADO E A FONTE DA LESÃO."																																																																																															, "" } )
			aAdd( aBody, { "", "000027", "200028300", "REAÇÃO DO CORPO A SEUS MOVIMENTOS - MOVIMENTO INVOLUNTÁRIO (ESCORREGÃO SEM QUEDA, ETC.)", "APLICA-SE A CASOS, SEM IMPACTO, EM QUE A LESÃO FOI CAUSADA EXCLUSIVAMENTE POR MOVIMENTO LIVRE DO CORPO HUMANO QUE CAUSOU TENSÃO OU TORÇÃO EM ALGUMA PARTE DO CORPO. GERALMENTE APLICA-SE À OCORRÊNCIA DE TORÇÕES, DISTENSÕES, RUPTURAS OU OUTRAS LESÕES INTERNAS, RESULTANTES DA ADOÇÃO DE UMA POSIÇÃO FORÇADA OU DE MOVIMENTOS INVOLUNTÁRIOS PROVOCADOS POR SUSTOS OU SFORÇOS DE RECUPERAÇÃO DA POSIÇÃO NORMAL EM CASOS DE ESCORREGÃO OU PERDA DE EQUILÍBRIO. INCLUI CASOS DE LESÃO MUSCULAR OU INTERNA RESULTANTES DE MOVIMENTOS INDIVIDUAIS COMO ANDAR, SUBIR, CORRER, TENTAR ALCANÇAR ALGO, VOLTAR-SE, CURVAR-SE, ETC., QUANDO TAIS MOVIMENTOS FOREM A PRÓPRIA FONTE DA LESÃO. NÃO SE APLICA A ESFORÇO EXCESSIVO AO ERGUER, PUXAR OU EMPURRAR OBJETOS OU A CASOS EM QUE O MOVIMENTO DO CORPO, VOLUNTÁRIO OU INVOLUNTÁRIO, TENHA TIDO POR RESULTADO CONTATO VIOLENTO COM ALGUM OBJETO.", "" } )
			aAdd( aBody, { "", "000028", "200028600", "REAÇÃO DO CORPO A SEUS MOVIMENTOS - MOVIMENTO VOLUNTARIO", "APLICA-SE A CASOS, SEM IMPACTO, EM QUE A LESÃO FOI CAUSADA EXCLUSIVAMENTE POR MOVIMENTO LIVRE DO CORPO HUMANO QUE CAUSOU TENSÃO OU TORÇÃO EM ALGUMA PARTE DO CORPO. GERALMENTE APLICA-SE À OCORRÊNCIA DE TORÇÕES, DISTENSÕES, RUPTURAS OU OUTRAS LESÕES INTERNAS, RESULTANTES DA ADOÇÃO DE UMA POSIÇÃO FORÇADA OU DE MOVIMENTOS INVOLUNTÁRIOS PROVOCADOS POR SUSTOS OU SFORÇOS DE RECUPERAÇÃO DA POSIÇÃO NORMAL EM CASOS DE ESCORREGÃO OU PERDA DE EQUILÍBRIO. INCLUI CASOS DE LESÃO MUSCULAR OU INTERNA RESULTANTES DE MOVIMENTOS INDIVIDUAIS COMO ANDAR, SUBIR, CORRER, TENTAR ALCANÇAR ALGO, VOLTAR-SE, CURVAR-SE, ETC., QUANDO TAIS MOVIMENTOS FOREM A PRÓPRIA FONTE DA LESÃO. NÃO SE APLICA A ESFORÇO EXCESSIVO AO ERGUER, PUXAR OU EMPURRAR OBJETOS OU A CASOS EM QUE O MOVIMENTO DO CORPO, VOLUNTÁRIO OU INVOLUNTÁRIO, TENHA TIDO POR RESULTADO CONTATO VIOLENTO COM ALGUM OBJETO.", "" } )
			aAdd( aBody, { "", "000029", "200032200", "ESFORCO EXCESSIVO AO ERGUER OBJETO", "VER EXPLICAÇÕES DO CÓDIGO 200028600."																																																																																																																				, "" } )
			aAdd( aBody, { "", "000030", "200032400", "ESFORCO EXCESSIVO AO EMPURRAR OU PUXAR OBJETO", "VER EXPLICAÇÕES DO CÓDIGO 200028600."																																																																																																																	, "" } )
			aAdd( aBody, { "", "000031", "200032600", "ESFORCO EXCESSIVO AO MANEJAR, SACUDIR OU ARREMESSAR OBJETO",  "VER EXPLICAÇÕES DO CÓDIGO 200028600."																																																																																																														, "" } )
			aAdd( aBody, { "", "000032", "200032900", "ESFORCO EXCESSIVO, NIC", "VER EXPLICAÇÕES DO CÓDIGO 200028600."																																																																																																																							, "" } )
			aAdd( aBody, { "", "000033", "200036000", "EXPOSIÇÃO À ENERGIA ELÉTRICA", "APLICA-SE SOMENTE A CASOS SEM IMPACTO, EM QUE A LESÃO CONSISTE EM CHOQUE ELÉTRICO, QUEIMADURA OU ELETROPLESSÃO (ELETROCUSSÃO)."																																																																																															, "" } )
			aAdd( aBody, { "", "000034", "200040300", "CONTATO COM OBJETO OU SUSBSTÂNCIA A TEMPERATURA MUITO ALTA", "APLICA-SE SOMENTE A CASOS, SEM IMPACTO, EM QUE A LESÃO CONSISTE EM QUEIMADURA, GELADURA, ETC., RESULTANTE QUEIMADURA, GELADURA, ETC., RESULTANTE DE CONTATO COM OBJETOS, AR, GASES, VAPORES OU LÍQUIDOS QUENTES OU FRIOS. NÃO SE APLICA A CASOS EM QUE A LESÃO FOI PROVOCADA PELAS CARACTERÍSTICAS TÓXICAS OU CÁUSTICAS DE PRODUTOS QUÍMICOS OU A QUEIMADURA POR DESCARGA ELÉTRICA."																										, "" } )
			aAdd( aBody, { "", "000035", "200040600", "CONTATO COM OBJETO OU SUSBSTÂNCIA A TEMPERATURA MUITO BAIXA", "APLICA-SE SOMENTE A CASOS, SEM IMPACTO, EM QUE A LESÃO CONSISTE EM QUEIMADURA, GELADURA, ETC., RESULTANTE QUEIMADURA, GELADURA, ETC., RESULTANTE DE CONTATO COM OBJETOS, AR, GASES, VAPORES OU LÍQUIDOS QUENTES OU FRIOS. NÃO SE APLICA A CASOS EM QUE A LESÃO FOI PROVOCADA PELAS CARACTERÍSTICAS TÓXICAS OU CÁUSTICAS DE PRODUTOS QUÍMICOS OU A QUEIMADURA POR DESCARGA ELÉTRICA."																										, "" } )
			aAdd( aBody, { "", "000036", "200044300", "EXPOSIÇÃO À TEMPERATURA AMBIENTE ELEVADA", "NÃO SE APLICA AOS CASOS DE LESÃO PROVENIENTE DE EXPOSIÇÃO À RADIAÇÃO SOLAR OU OUTRAS RADIAÇÕES. TAMBÉM NÃO SE APLICA A CASOS DE QUEIMADURA OU GELADURA PROVOCADA POR CONTATO COM OBJETO OU SUBSTÂNCIA A TEMPERATURAS EXTREMAS OU QUEIMADURA DEVIDA À ENERGIA ELÉTRICA."																																																										, "" } )
			aAdd( aBody, { "", "000037", "200044600", "EXPOSIÇÃO À TEMPERATURA AMBIENTE BAIXA", "NÃO SE APLICA AOS CASOS DE LESÃO PROVENIENTE DE EXPOSIÇÃO À RADIAÇÃO SOLAR OU OUTRAS RADIAÇÕES. TAMBÉM NÃO SE APLICA A CASOS DE QUEIMADURA OU GELADURA PROVOCADA POR CONTATO COM OBJETO OU SUBSTÂNCIA A TEMPERATURAS EXTREMAS OU QUEIMADURA DEVIDA À ENERGIA ELÉTRICA."																																																										, "" } )
			aAdd( aBody, { "", "000038", "200048200", "INALAÇÃO DE SUBSTÂNCIA CÁUSTICA, TÓXICA OU NOCIVA", "APLICA-SE SOMENTE A CASOS, SEM IMPACTO, EM QUE A LESÃO FOI PROVOCADA POR INALAÇÃO, ABSORÇÃO OU INGESTÃO DE SUBSTÂNCIAS NOCIVAS. GERALMENTE REFERE-SE A INTOXICAÇÕES, ENVENENAMENTOS, QUEIMADURAS, IRRITAÇÕES OU REAÇÕES ALÉRGICAS POR PRODUTOS QUÍMICOS"																																																											, "" } )
			aAdd( aBody, { "", "000039", "200048400", "INGESTÃO DE SUBSTÂNCIA CÁUSTICA, TÓXICA OU NOCIVA", "APLICA-SE SOMENTE A CASOS, SEM IMPACTO, EM QUE A LESÃO FOI PROVOCADA POR INALAÇÃO, ABSORÇÃO OU INGESTÃO DE SUBSTÂNCIAS NOCIVAS. GERALMENTE REFERE-SE A INTOXICAÇÕES, ENVENENAMENTOS, QUEIMADURAS, IRRITAÇÕES OU REAÇÕES ALÉRGICAS POR PRODUTOS QUÍMICOS"																																																											, "" } )
			aAdd( aBody, { "", "000040", "200048600", "ABSORÇÃO (POR CONTATO) DE SUBSTÂNCIA CÁUSTICA, TÓXICA OU NOCIVA", "APLICA-SE SOMENTE A CASOS, SEM IMPACTO, EM QUE A LESÃO FOI PROVOCADA POR INALAÇÃO, ABSORÇÃO OU INGESTÃO DE SUBSTÂNCIAS NOCIVAS. GERALMENTE REFERE-SE A INTOXICAÇÕES, ENVENENAMENTOS, QUEIMADURAS, IRRITAÇÕES OU REAÇÕES ALÉRGICAS POR PRODUTOS QUÍMICOS"																																																								, "" } )
			aAdd( aBody, { "", "000041", "200048900", "INALAÇÃO, INGESTÃO E ABSORCÃO, NIC", "APLICA-SE SOMENTE A CASOS, SEM IMPACTO, EM QUE A LESÃO FOI PROVOCADA POR INALAÇÃO, ABSORÇÃO OU INGESTÃO DE SUBSTÂNCIAS NOCIVAS. GERALMENTE REFERE-SE A INTOXICAÇÕES, ENVENENAMENTOS, QUEIMADURAS, IRRITAÇÕES OU REAÇÕES ALÉRGICAS POR PRODUTOS QUÍMICOS"																																																															, "" } )
			aAdd( aBody, { "", "000042", "200052000", "IMERSÃO", "APLICA-SE AOS ACIDENTES QUE TÊM POR CONSEQUÊNCIA O AFOGAMENTO."																																																																																																																				, "" } )
			aAdd( aBody, { "", "000043", "200056000", "EXPOSIÇÃO À RADIAÇÃO NÃO IONIZANTE", "APLICA-SE A CASOS EM QUE AS LESÕES SÃO PROVOCADAS POR EXPOSIÇÃO À RADIAÇÃO SOLAR OU OUTRAS RADIAÇÕES NÃO IONIZANTES (POR EXEMPLO, ULTRAVIOLETA E INFRAVERMELHO)."																																																																																					, "" } )
			aAdd( aBody, { "", "000044", "200060000", "EXPOSIÇÃO À RADIACÃO IONIZANTE", ""																																																																																																																														, "" } )
			aAdd( aBody, { "", "000045", "200064000", "EXPOSICÃO AO RUIDO", ""																																																																																																																																	, "" } )
			aAdd( aBody, { "", "000046", "200068000", "EXPOSIÇÃO À VIBRAÇÃO", ""																																																																																																																																, "" } )
			aAdd( aBody, { "", "000047", "200072300", "EXPOSIÇÃO À PRESSÃO AMBIENTE ELEVADA", ""																																																																																																																												, "" } )
			aAdd( aBody, { "", "000048", "200072600", "EXPOSIÇÃO À PRESSÃO AMBIENTE BAIXA", ""																																																																																																																													, "" } )
			aAdd( aBody, { "", "000049", "200076200", "EXPOSIÇÃO À POLUIÇÃO DA ÁGUA", ""																																																																																																																														, "" } )
			aAdd( aBody, { "", "000050", "200076400", "EXPOSIÇÃO À POLUIÇÃO DO AR", ""																																																																																																																															, "" } )
			aAdd( aBody, { "", "000051", "200076600", "EXPOSIÇÃO À POLUIÇÃO DO SOLO", ""																																																																																																																														, "" } )
			aAdd( aBody, { "", "000052", "200076900", "EXPOSIÇÃO À POLUIÇÃO, NIC", ""																																																																																																																															, "" } )
			aAdd( aBody, { "", "000053", "200080200", "ATAQUE DE SER VIVO POR MORDEDURA, PICADA, CHIFRADA, COICE, ETC", "NÃO SE APLICA AO CASO DE HAVER PEÇONHA OU TRANSMISSÃO DE DOENÇA"																																																																																																						, "" } )
			aAdd( aBody, { "", "000054", "200080400", "ATAQUE DE SER VIVO COM PEÇONHA", ""																																																																																																																														, "" } )
			aAdd( aBody, { "", "000055", "200080600", "ATAQUE DE SER VIVO COM TRANSMISSÃO DE DOENÇA", ""																																																																																																																										, "" } )
			aAdd( aBody, { "", "000056", "200080900", "ATAQUE DE SER VIVO (INCLUSIVE DO HOMEM), NIC", ""																																																																																																																										, "" } )
			aAdd( aBody, { "", "000057", "200080901", "CONTATO COM PESSOAS DOENTES OU MATERIAL INFECTOCONTAGIANTE - AGENTES BIOLÓGICOS", ""																																																																																																																		, "" } )
			aAdd( aBody, { "", "000058", "209000000", "TIPO, NIC", ""																																																																																																																																			, "" } )
			aAdd( aBody, { "", "000059", "209500000", "TIPO INEXISTENTE", ""																																																																																																																																	, "" } )

			//Simplificação

			//Alterações
			aAdd( aBody, { "", "000060", "200032200", "ESFORÇO EXCESSIVO AO ERGUER OBJETO. VER EXPLICAÇÕES DO CÓDIGO 200028600", ""																																																																																																																				, "20210509" } )
			aAdd( aBody, { "", "000061", "200032400", "ESFORÇO EXCESSIVO AO EMPURRAR OU PUXAR OBJETO. VER EXPLICAÇÕES DO CÓDIGO 200028600", ""																																																																																																																	, "20210509" } )
			aAdd( aBody, { "", "000062", "200032600", "ESFORÇO EXCESSIVO AO MANEJAR, SACUDIR OU ARREMESSAR OBJETO. VER EXPLICAÇÕES DO CÓDIGO 200028600", ""																																																																																																														, "20210509" } )
			aAdd( aBody, { "", "000063", "200032900", "ESFORÇO EXCESSIVO, NIC. VER EXPLICAÇÕES DO CÓDIGO 200028600", ""																																																																																																																							, "20210509" } )

			//NT 03/2021
			aAdd( aBody, { "", "000064", "200072000", "EXPOSICAO A PRESSAO AMBIENTE", ""																																																																																																																														, "" } )

			aAdd( aRet, { aHeader, aBody } )

		EndIf
	
	Else
	
		nVerAtu := 1032.01
	
		If nVerEmp < nVerAtu

			aAdd( aHeader, "C8L_FILIAL" )
			aAdd( aHeader, "C8L_ID" 	)
			aAdd( aHeader, "C8L_CODIGO" )
			aAdd( aHeader, "C8L_DESCRI" )
			aAdd( aHeader, "C8L_VALIDA" )

			aAdd( aBody, { "", "000001", "200004300", "IMPACTO DE PESSOA CONTRA OBJETO PARADO. APLICA-SE A CASOS EM QUE A LESAO FOI PRODUZIDA POR IMPACTO DA PESSOA ACIDENTADA CONTRA A FONTE"	, "" } )
			aAdd( aBody, { "", "000002", "200004600", "IMPACTO DE PESSOA CONTRA OBJETO EM MOVIMENTO. APLICA-SE A CASOS EM QUE A LESAO FOI PRODUZIDA POR IMPACTO DA PESSOA ACIDENTADA CONTRA A"	, "" } )
			aAdd( aBody, { "", "000003", "200008300", "IMPACTO SOFRIDO POR PESSOA, DE OBJETO QUE CAI. APLICA-SE A CASOS EM QUE A LESAO FOI PRODUZIDA POR IMPACTO ENTRE O ACIDENTADO E A FONTE"	, "" } )
			aAdd( aBody, { "", "000004", "200008600", "IMPACTO SOFRIDO POR PESSOA, DE OBJETO PROJETADO. APLICA-SE A CASOS EM QUE A LESAO FOI PRODUZIDA POR IMPACTO ENTRE O ACIDENTADO E A FONT"	, "" } )
			aAdd( aBody, { "", "000005", "200008900", "IMPACTO SOFRIDO POR PESSOA, NIC. APLICA-SE A CASOS EM QUE A LESAO FOI PRODUZIDA POR IMPACTO ENTRE O ACIDENTADO E A FONTE DA LESAO, TEND"	, "" } )
			aAdd( aBody, { "", "000006", "200012200", "QUEDA DE PESSOA COM DIFERENCA DE NIVEL DE ANDAIME, PASSAGEM, PLATAFORMA, ETC. APLICA-SE A CASOS EM QUE A LESAO FOI PRODUZIDA POR IMPACT"	, "" } )
			aAdd( aBody, { "", "000007", "200012300", "QUEDA DE PESSOA COM DIFERENCA DE NIVEL DE ESCADA MOVEL OU FIXADA CUJOS DEGRAUS NAO PERMITEM O APOIO INTEGRAL DO PE. APLICA-SE A CASOS E"	, "" } )
			aAdd( aBody, { "", "000008", "200012400", "QUEDA DE PESSOA COM DIFERENCA DE NIVEL DE MATERIAL EMPILHADO. APLICA-SE A CASOS EM QUE A LESAO FOI PRODUZIDA POR IMPACTO ENTRE O ACIDEN"	, "" } )
			aAdd( aBody, { "", "000009", "200012500", "QUEDA DE PESSOA COM DIFERENCA DE NIVEL DE VEICULO. APLICA-SE A CASOS EM QUE A LESAO FOI PRODUZIDA POR IMPACTO ENTRE O ACIDENTADO E A FO"	, "" } )
			aAdd( aBody, { "", "000010", "200012600", "QUEDA DE PESSOA COM DIFERENCA DE NIVEL EM ESCADA PERMANENTE CUJOS DEGRAUS PERMITEM APOIO INTEGRAL DO PE. APLICA-SE A CASOS EM QUE A LES"	, "" } )
			aAdd( aBody, { "", "000011", "200012700", "QUEDA DE PESSOA COM DIFERENCA DE NIVEL EM POCO, ESCAVACAO, ABERTURA NO PISO, ETC, (DA BORDA DO ABERTURA). APLICA-SE A CASOS EM QUE A LE"	, "" } )
			aAdd( aBody, { "", "000012", "200012900", "QUEDA DE PESSOA COM DIFERENCA DE NIVEL, NIC. APLICA-SE A CASOS EM QUE A LESAO FOI PRODUZIDA POR IMPACTO ENTRE O ACIDENTADO E A FONTE DA"	, "" } )
			aAdd( aBody, { "", "000013", "200016300", "QUEDA DE PESSOA EM MESMO NIVEL EM PASSAGEM OU SUPERFICIE DE SUSTENTACAO APLICA-SE A CASOS EM QUE A LESAO FOI PRODUZIDA POR IMPACTO ENTR"	, "" } )
			aAdd( aBody, { "", "000014", "200016600", "QUEDA DE PESSOA EM MESMO NIVEL SOBRE OU CONTRA ALGUMA COISA. APLICA-SE A CASOS EM QUE A LESAO FOI PRODUZIDA POR IMPACTO ENTRE O ACIDENT"	, "" } )
			aAdd( aBody, { "", "000015", "200016900", "QUEDA DE PESSOA EM MESMO NIVEL, NIC. APLICA-SE A CASOS EM QUE A LESAO FOI PRODUZIDA POR IMPACTO ENTRE O ACIDENTADO E UM OBJETO EXTERNO,"	, "" } )
			aAdd( aBody, { "", "000016", "200020100", "APRISIONAMENTO EM, SOB OU ENTRE OBJETOS EM MOVIMENTO CONVERGENTE (CALANDRA) OU DE ENCAIXE. APLICA-SE A CASOS, SEM IMPACTO, EM QUE A LES"	, "" } )
			aAdd( aBody, { "", "000017", "200020300", "APRISIONAMENTO EM, SOB OU ENTRE UM OBJETO PARADO E OUTRO EM MOVIMENTO. APLICA-SE A CASOS, SEM IMPACTO, EM QUE A LESAO FOI PRODUZIDA POR"	, "" } )
			aAdd( aBody, { "", "000018", "200020500", "APRISIONAMENTO EM, SOB OU ENTRE DOIS OU MAIS OBJETOS EM MOVIMENTO (SEM ENCAIXE). APLICA-SE A CASOS, SEM IMPACTO, EM QUE A LESAO FOI PRO"	, "" } )
			aAdd( aBody, { "", "000019", "200020700", "APRISIONAMENTO EM, SOB OU ENTRE DESABAMENTO OU DESMORONAMENTO DE EDIFICACAO, BARREIRA, ETC. APLICA-SE A CASOS, SEM IMPACTO, EM QUE A LE"	, "" } )
			aAdd( aBody, { "", "000020", "200020900", "APRISIONAMENTO EM, SOB OU ENTRE, NIC. APLICA-SE A CASOS, SEM IMPACTO, EM QUE A LESAO FOI PRODUZIDA POR COMPRESSAO, PINCAMENTO OU ESMAGA"	, "" } )
			aAdd( aBody, { "", "000021", "200024300", "ATRITO OU ABRASAO POR ENCOSTAR, PISAR, AJOELHAR OU SENTAR EM OBJETO (NAO EM VIBRACAO). (APLICA-SE A CASOS, SEM IMPACTO, EM QUE A LESAO"	, "" } )
			aAdd( aBody, { "", "000022", "200024400", "ATRITO OU ABRASAO POR MANUSEAR OBJETO (NAO EM VIBRACAO) - APLICA-SE A CASOS, SEM IMPACTO, EM QUE A LESAO FOI PRODUZIDA POR PRESSAO, VIB"	, "" } )
			aAdd( aBody, { "", "000023", "200024500", "ATRITO OU ABRASAO POR OBJETO EM VIBRACAO - APLICA-SE A CASOS, SEM IMPACTO, EM QUE A LESAO FOI PRODUZIDA POR PRESSAO, VIBRACAO OU ATRITO"	, "" } )
			aAdd( aBody, { "", "000024", "200024600", "ATRITO OU ABRASAO POR CORPO ESTRANHO NO OLHO - APLICA-SE A CASOS, SEM IMPACTO, EM QUE A LESAO FOI PRODUZIDA POR PRESSAO, VIBRACAO OU AT"	, "" } )
			aAdd( aBody, { "", "000025", "200024700", "ATRITO OU ABRASAO POR COMPRESSAO REPETITIVA - APLICA-SE A CASOS, SEM IMPACTO, EM QUE A LESAO FOI PRODUZIDA POR PRESSAO, VIBRACAO OU ATR"	, "" } )
			aAdd( aBody, { "", "000026", "200024900", "ATRITO OU ABRASAO, NIC - APLICA-SE A CASOS, SEM IMPACTO, EM QUE A LESAO FOI PRODUZIDA POR PRESSAO, VIBRACAO OU ATRITO ENTRE O ACIDENTAD"	, "" } )
			aAdd( aBody, { "", "000027", "200028300", "REACAO DO CORPO A SEUS MOVIMENTOS - MOVIMENTO INVOLUNTARIO (ESCORREGAO SEM QUEDA, ETC.) - (APLICA-SE A CASOS, SEM IMPACTO, EM QUE A LES"	, "" } )
			aAdd( aBody, { "", "000028", "200028600", "REACAO DO CORPO A SEUS MOVIMENTOS - MOVIMENTO VOLUNTARIO - (APLICA-SE A CASOS, SEM IMPACTO, EM QUE A LESAO FOI CAUSADA EXCLUSIVAMENTE P"	, "" } )
			aAdd( aBody, { "", "000029", "200032200", "ESFORCO EXCESSIVO AO ERGUER OBJETO - VER EXPLICACOES DA CLASSIFICACAO ANTERIOR (200028000)"												, "20210509" } )
			aAdd( aBody, { "", "000030", "200032400", "ESFORCO EXCESSIVO AO EMPURRAR OU PUXAR OBJETO - VER EXPLICACOES DA CLASSIFICACAO ANTERIOR (200028000)"									, "20210509" } )
			aAdd( aBody, { "", "000031", "200032600", "ESFORCO EXCESSIVO AO MANEJAR, SACUDIR OU ARREMESSAR OBJETO - VER EXPLICACOES DA CLASSIFICACAO ANTERIOR (200028000)"						, "20210509" } )
			aAdd( aBody, { "", "000032", "200032900", "ESFORCO EXCESSIVO, NIC - VER EXPLICACOES DA CLASSIFICACAO ANTERIOR (200028000)"															, "20210509" } )
			aAdd( aBody, { "", "000033", "200036000", "EXPOSICAO A ENERGIA ELETRICA - APLICA-SE SOMENTE A CASOS SEM IMPACTO, EM QUE A LESAO CONSISTE EM CHOQUE ELETRICO, QUEIMADURA OU ELETROP"	, "" } )
			aAdd( aBody, { "", "000034", "200040300", "CONTATO COM OBJETO OU SUSBSTANCIA A TEMPERATURA MUITO ALTA - (APLICA-SE SOMENTE A CASOS, SEM IMPACTO, EM QUE A LESAO CONSISTE EM QUEIMA"	, "" } )
			aAdd( aBody, { "", "000035", "200040600", "CONTATO COM OBJETO OU SUSBSTANCIA A TEMPERATURA MUITO BAIXA - (APLICA-SE SOMENTE A CASOS, SEM IMPACTO, EM QUE A LESAO CONSISTE EM QUEIM"	, "" } )
			aAdd( aBody, { "", "000036", "200044300", "EXPOSICAO A TEMPERATURA AMBIENTE ELEVADA - (NAO SE APLICA-SE AOS CASOS DE LESAO PROVENIENTE DE EXPOSICAO A RADIACAO SOLAR OU OUTRAS RAD"	, "" } )
			aAdd( aBody, { "", "000037", "200044600", "EXPOSICAO A TEMPERATURA AMBIENTE BAIXA - (NAO SE APLICA-SE AOS CASOS DE LESAO PROVENIENTE DE EXPOSICAO A RADIACAO SOLAR OU OUTRAS RADIA"	, "" } )
			aAdd( aBody, { "", "000038", "200048200", "INALACAO DE SUBSTANCIA CAUSTICA, TOXICA OU NOCIVA - (APLICA-SE SOMENTE A CASOS, SEM IMPACTO, EM QUE A LESAO FOI PROVOCADA POR INALACAO,"	, "" } )
			aAdd( aBody, { "", "000039", "200048400", "INGESTAO DE SUBSTANCIA CAUSTICA, TOXICA OU NOCIVA - (APLICA-SE SOMENTE A CASOS, SEM IMPACTO, EM QUE A LESAO FOI PROVOCADA POR INALACAO,"	, "" } )
			aAdd( aBody, { "", "000040", "200048600", "ABSORCAO(POR CONTATO) DE SUBSTANCIA CAUSTICA, TOXICA OU NOCIVA - (APLICA-SE SOMENTE A CASOS, SEM IMPACTO, EM QUE A LESAO FOI PROVOCADA"	, "" } )
			aAdd( aBody, { "", "000041", "200048900", "INALACAO, INGESTAO E ABSORCAO, NIC - (APLICA-SE SOMENTE A CASOS, SEM IMPACTO, EM QUE A LESAO FOI PROVOCADA POR INALACAO, ABSORCAO OU IN"	, "" } )
			aAdd( aBody, { "", "000042", "200052000", "IMERSAO - APLICA-SE AOS ACIDENTES QUE TEM POR CONSEQUENCIA O AFOGAMENTO."																, "" } )
			aAdd( aBody, { "", "000043", "200056000", "EXPOSICAO A RADIACAO NAO IONIZANTE - APLICA-SE A CASOS EM QUE AS LESOES SAO PROVOCADAS POR EXPOSICAO A RADIACAO SOLAR OU OUTRAS RADIACO"	, "" } )
			aAdd( aBody, { "", "000044", "200060000", "EXPOSICAO A RADIACAO IONIZANTE"																											, "" } )
			aAdd( aBody, { "", "000045", "200064000", "EXPOSICAO AO RUIDO"																														, "" } )
			aAdd( aBody, { "", "000046", "200068000", "EXPOSICAO A VIBRACAO"																													, "" } )
			aAdd( aBody, { "", "000047", "200072300", "EXPOSICAO A PRESSAO AMBIENTE ELEVADA"																									, "" } )
			aAdd( aBody, { "", "000048", "200072600", "EXPOSICAO A PRESSAO AMBIENTE BAIXA"																										, "" } )
			aAdd( aBody, { "", "000049", "200076200", "EXPOSICAO A POLUICAO DA AGUA"																											, "" } )
			aAdd( aBody, { "", "000050", "200076400", "EXPOSICAO A POLUICAO DO AR"																												, "" } )
			aAdd( aBody, { "", "000051", "200076600", "EXPOSICAO A POLUICAO DO SOLO"																											, "" } )
			aAdd( aBody, { "", "000052", "200076900", "EXPOSICAO A POLUICAO, NIC"																												, "" } )
			aAdd( aBody, { "", "000053", "200080200", "ATAQUE DE SER VIVO POR MORDEDURA, PICADA, CHIFRADA, COICE, ETC., NAO SE APLICANDO NO CASO DE HAVER PECONHA OU TRANSMISSAO DE DOENCA"		, "" } )
			aAdd( aBody, { "", "000054", "200080400", "ATAQUE DE SER VIVO COM PECONHA"																											, "" } )
			aAdd( aBody, { "", "000055", "200080600", "ATAQUE DE SER VIVO COM TRANSMISSAO DE DOENCA"																							, "" } )
			aAdd( aBody, { "", "000056", "200080900", "ATAQUE DE SER VIVO (INCLUSIVE DO HOMEM), NIC"																							, "" } )
			aAdd( aBody, { "", "000057", "200080901", "CONTATO COM PESSOAS DOENTES OU MATERIAL INFECTO CONTAGIANTE AGENTES BIOLOGICOS"															, "" } )
			aAdd( aBody, { "", "000058", "209000000", "TIPO, NIC"																																, "" } )
			aAdd( aBody, { "", "000059", "209500000", "TIPO INEXISTENTE"																														, "" } )

			//Simplificação

			//Alterações
			aAdd( aBody, { "", "000060", "200032200", "ESFORÇO EXCESSIVO AO ERGUER OBJETO. VER EXPLICAÇÕES DO CÓDIGO 200028600"																	, "" } )
			aAdd( aBody, { "", "000061", "200032400", "ESFORÇO EXCESSIVO AO EMPURRAR OU PUXAR OBJETO. VER EXPLICAÇÕES DO CÓDIGO 200028600"														, "" } )
			aAdd( aBody, { "", "000062", "200032600", "ESFORÇO EXCESSIVO AO MANEJAR, SACUDIR OU ARREMESSAR OBJETO. VER EXPLICAÇÕES DO CÓDIGO 200028600"											, "" } )
			aAdd( aBody, { "", "000063", "200032900", "ESFORÇO EXCESSIVO, NIC. VER EXPLICAÇÕES DO CÓDIGO 200028600"																				, "" } )

			//NT 03/2021
			aAdd( aBody, { "", "000064", "200072000", "EXPOSICAO A PRESSAO AMBIENTE"																											, "" } )

			aAdd( aRet, { aHeader, aBody } )

		EndIf
	
	EndIf

Return( aRet )
