#INCLUDE "PROTHEUS.CH" 
#INCLUDE "FWMVCDEF.CH"
#INCLUDE "TAFA517.CH"

//-------------------------------------------------------------------
/*/{Protheus.doc} TAFA517

@author Karyna R M Martins
@since 14/11/2018
@version 1.0
/*/
//-------------------------------------------------------------------
Function TAFA517()

	Local   oBrw :=  FWmBrowse():New()

	oBrw:SetDescription(STR0001)    //"Atividades Perigosas, Insalubres e/ou Especiais"
	oBrw:SetAlias( 'V2L')
	oBrw:SetMenuDef('TAFA517')
	oBrw:Activate()

Return Nil

//-------------------------------------------------------------------
/*/{Protheus.doc} MenuDef
Funcao generica MVC com as opcoes de menu

@author Karyna R M Martins
@since 14/11/2018
@version 1.0
/*/
//-------------------------------------------------------------------
Static Function MenuDef()
Return XFUNMnuTAF( "TAFA517" )


//-------------------------------------------------------------------
/*/{Protheus.doc} ModelDef
Funcao generica MVC do model

@return oModel - Objeto do Modelo MVC

@author Karyna R M Martins
@since 14/11/2018
@version 1.0
/*/
//-------------------------------------------------------------------
Static Function ModelDef()
Local oStruV2L:= FwFormStruct( 1, "V2L" )
Local oModel   := MpFormModel():New( "TAFA517" )

oModel:AddFields( "MODEL_V2L", /*cOwner*/, oStruV2L )
oModel:GetModel ( "MODEL_V2L" ):SetPrimaryKey( { "V2L_FILIAL", "V2L_ID" } )

Return oModel


//-------------------------------------------------------------------
/*/{Protheus.doc} ViewDef
Funcao generica MVC do View

@return oView - Objeto da View MVC

@author Karyna R M Martins
@since 14/11/2018
@version 1.0
/*/
//-------------------------------------------------------------------
Static Function ViewDef()
Local   oModel      :=  FWLoadModel( 'TAFA517' )
Local   oStruV2L    :=  FWFormStruct( 2, 'V2L' )
Local   oView       :=  FWFormView():New()

oView:SetModel( oModel )
oView:AddField( 'VIEW_V2L', oStruV2L, 'MODEL_V2L' )

oView:EnableTitleView( 'VIEW_V2L', STR0001 )    //"Atividades Perigosas, Insalubres e/ou Especiais"
oView:CreateHorizontalBox( 'FIELDSV2L', 100 )
oView:SetOwnerView( 'VIEW_V2L', 'FIELDSV2L' )

Return oView

//-------------------------------------------------------------------
/*/{Protheus.doc} FAtuCont

Rotina para carga e atualização da tabela autocontida.

@Param		nVerEmp	-	Versão corrente na empresa
			nVerAtu	-	Versão atual ( passado como referência )

@Return	aRet		-	Array com estrutura de campos e conteúdo da tabela

@author Karyna R M Martins
@since 14/11/2018
@version 1.0
/*/
//-------------------------------------------------------------------
Static Function FAtuCont( nVerEmp, nVerAtu )

	Local aHeader	:=	{}
	Local aBody	:=	{}
	Local aRet		:=	{}

	nVerAtu := 1024.52

	If nVerEmp < nVerAtu
	
		aAdd( aHeader, "V2L_FILIAL" )
		aAdd( aHeader, "V2L_ID" )
		aAdd( aHeader, "V2L_CODIGO" )
		aAdd( aHeader, "V2L_DESCRI" )
		aAdd( aHeader, "V2L_VALIDA" )
		
		// ATIVIDADES COM EXPOSIÇÃO A RISCOS BIOLÓGICOS
		aAdd( aBody, { "", "000001 " , "01.001 " , "TRABALHO OU OPERAÇÕES, EM CONTATO PERMANENTE COM PACIENTES EM ISOLAMENTO POR DOENÇAS INFECTO-CONTAGIOSAS, BEM COMO OBJETOS DE SEU USO, NÃO PREVIAMENTE ESTERILIZADOS." , ""} )
		aAdd( aBody, { "", "000002 " , "01.002 " , "TRABALHO OU OPERAÇÕES, EM CONTATO PERMANENTE COM CARNES, GLÂNDULAS, VÍSCERAS, SANGUE, OSSOS, COUROS, PELOS E DEJEÇÕES DE ANIMAIS PORTADORES DE DOENÇAS INFECTO-CONTAGIOSAS(CARBUNCULOSE, BRUCELOSE, TUBERCULOSE)." , ""} )
		aAdd( aBody, { "", "000003 " , "01.003 " , "TRABALHO OU OPERAÇÕES, EM CONTATO PERMANENTE COM ESGOTOS (GALERIAS, FOSSAS E TANQUES)." , ""} )
		aAdd( aBody, { "", "000004 " , "01.004 " , "TRABALHO OU OPERAÇÕES, EM CONTATO PERMANENTE COM LIXO URBANO (COLETA E INDUSTRIALIZAÇÃO)." , ""} )
		aAdd( aBody, { "", "000005 " , "01.005 " , "TRABALHOS  E  OPERAÇÕES  EM  CONTATO  PERMANENTE  COM  PACIENTES,  ANIMAIS  OU  COM  MATERIAL INFECTO-CONTAGIANTE,  EM  HOSPITAIS,  SERVIÇOS  DE  EMERGÊNCIA,  ENFERMARIAS,  AMBULATÓRIOS, POSTOS DE VACINAÇÃO E " , ""} )
		aAdd( aBody, { "", "000006 " , "01.006 " , "TRABALHOS  E  OPERAÇÕES  EM  CONTATO  PERMANENTE  COM  PACIENTES,  ANIMAIS  OU  COM  MATERIAL INFECTO-CONTAGIANTE,    EM    HOSPITAIS,    AMBULATÓRIOS,    POSTOS    DE    VACINAÇÃO    E    OUTROS	ESTABELECIMENTOS." , ""} )
		aAdd( aBody, { "", "000007 " , "01.007 " , "TRABALHOS  E  OPERAÇÕES  EM  CONTATO  PERMANENTE  COM  PACIENTES,  ANIMAIS  OU  COM  MATERIAL INFECTO-CONTAGIANTE,  EM  CONTATO  EM  LABORATÓRIOS,  COM  ANIMAIS  DESTINADOS  AO  PREPARO  DE SORO, VACINAS E OUTROS " , ""} )
		aAdd( aBody, { "", "000008 " , "01.008 " , "TRABALHOS  E  OPERAÇÕES  EM  CONTATO  PERMANENTE  COM  PACIENTES,  ANIMAIS  OU  COM  MATERIAL INFECTO-CONTAGIANTE, EM LABORATÓRIOS DE ANÁLISE CLÍNICA E HISTOPATOLOGIA. INCLUI OS TRABALHOS EM LABORATÓRIOS DE AUTÓPSIA," , ""} )
		aAdd( aBody, { "", "000009 " , "01.009 " , "TRABALHOS  E  OPERAÇÕES  EM  CONTATO  PERMANENTE  COM  PACIENTES,  ANIMAIS  OU  COM  MATERIAL INFECTO-CONTAGIANTE,  EM  GABINETES  DE  AUTÓPSIAS,  DE  ANATOMIA  E  HISTOANATOMOPATOLOGIA (APLICA-SE SOMENTE AO PESSOAL" , ""} )
		aAdd( aBody, { "", "000010 " , "01.010 " , "TRABALHOS  E  OPERAÇÕES  EM  CONTATO  PERMANENTE  COM  PACIENTES,  ANIMAIS  OU  COM  MATERIAL INFECTO-CONTAGIANTE, EM CEMITÉRIOS (EXUMAÇÃO DE CORPOS)." , ""} )
		aAdd( aBody, { "", "000011 " , "01.011 " , "TRABALHOS  E  OPERAÇÕES  EM  CONTATO  PERMANENTE  COM  PACIENTES,  ANIMAIS  OU  COM  MATERIAL INFECTO-CONTAGIANTE, EM ESTÁBULOS E CAVALARIÇAS." , ""} )
		aAdd( aBody, { "", "000012 " , "01.012 " , "TRABALHOS  E  OPERAÇÕES  EM  CONTATO  PERMANENTE  COM  PACIENTES,  ANIMAIS  OU  COM  MATERIAL INFECTO-CONTAGIANTE, EM RESÍDUOS DE ANIMAIS DETERIORADOS." , ""} )
		aAdd( aBody, { "", "000013 " , "01.013 " , "TRABALHO DE EXUMAÇÃO DE CORPOS E MANIPULAÇÃO DE RESÍDUOS DE ANIMAIS DETERIORADOS." , ""} )
		aAdd( aBody, { "", "000014 " , "01.014 " , "ESVAZIAMENTO DE BIODIGESTORES." , ""} )
		
		// ATIVIDADES COM EXPOSIÇÃO A RISCOS QUÍMICOS
		aAdd( aBody, { "", "000015 " , "02.001 " , "EXTRAÇÃO E MANIPULAÇÃO DE ARSÊNICO E PREPARAÇÃO DE SEUS COMPOSTOS." , ""} )
		aAdd( aBody, { "", "000016 " , "02.002 " , "FABRICAÇÃO E PREPARAÇÃO DE TINTAS À BASE DE ARSÊNICO." , ""} )
		aAdd( aBody, { "", "000017 " , "02.003 " , "FABRICAÇÃO  DE  PRODUTOS   PARASITICIDAS,  INSETICIDAS  E   RATICIDAS   CONTENDO   COMPOSTOS  DE ARSÊNICO." , ""} )
		aAdd( aBody, { "", "000018 " , "02.004 " , "PINTURA  A  PISTOLA  COM  PIGMENTOS  DE  COMPOSTOS  DE  ARSÊNICO,  EM  RECINTOS  LIMITADOS  OU FECHADOS." , ""} )
		aAdd( aBody, { "", "000019 " , "02.005 " , "PREPARAÇÃO DO SECRET." , ""} )
		aAdd( aBody, { "", "000020 " , "02.006 " , "PRODUÇÃO DE TRIÓXIDO DE ARSÊNICO." , ""} )
		aAdd( aBody, { "", "000021 " , "02.007 " , "BRONZEAMENTO EM NEGRO E VERDE COM COMPOSTOS DE ARSÊNICO." , ""} )
		aAdd( aBody, { "", "000022 " , "02.008 " , "CONSERVAÇÃO E PELES E PLUMAS; DEPILAÇÃO DE PELES À BASE DE COMPOSTOS DE ARSÊNICO." , ""} )
		aAdd( aBody, { "", "000023 " , "02.009 " , "DESCOLORAÇÃO DE VIDROS E CRISTAIS À BASE DE COMPOSTOS DE ARSÊNICO." , ""} )
		aAdd( aBody, { "", "000024 " , "02.010 " , "EMPREGO DE PRODUTOS PARASITICIDAS, INSETICIDAS E RATICIDAS À BASE DE COMPOSTOS DE ARSÊNICO." , ""} )
		aAdd( aBody, { "", "000025 " , "02.011 " , "FABRICAÇÃO DE CARTAS DE JOGAR, PAPÉIS PINTADOS E FLORES ARTIFICIAIS À BASE DE COMPOSTOS DE ARSÊNICO." , ""} )
		aAdd( aBody, { "", "000026 " , "02.012 " , "METALURGIA DE MINÉRIOS ARSENICAIS (OURO, PRATA, CHUMBO, ZINCO, NÍQUEL, ANTIMÔNIO, COBALTO E FERRO)." , ""} )
		aAdd( aBody, { "", "000027 " , "02.013 " , "OPERAÇÕES DE GALVANOTÉCNICA À BASE DE COMPOSTOS DE ARSÊNICO." , ""} )
		aAdd( aBody, { "", "000028 " , "02.014 " , "PINTURA  MANUAL  (PINCEL,  ROLO  E  ESCOVA)  COM  PIGMENTOS  DE  COMPOSTOS  DE  ARSÊNICO  EM RECINTOS LIMITADOS OU FECHADOS, EXCETO COM PINCEL CAPILAR." , ""} )
		aAdd( aBody, { "", "000029 " , "02.015 " , "EMPALHAMENTO DE ANIMAIS À BASE DE COMPOSTOS DE ARSÊNICO." , ""} )
		aAdd( aBody, { "", "000030 " , "02.016 " , "FABRICAÇÃO DE TAFETÁ “SIRE”." , ""} )
		aAdd( aBody, { "", "000031 " , "02.017 " , "PINTURA A PISTOLA OU MANUAL COM PIGMENTOS DE COMPOSTOS DE ARSÊNICO AO AR LIVRE." , ""} )
		aAdd( aBody, { "", "000032 " , "02.018 " , "TRABALHO PERMANENTE COM CARVÃO NO SUBSOLO EM OPERAÇÕES DE CORTE, FURAÇÃO E DESMONTE, DE  CARREGAMENTO  NO  LOCAL  DE  DESMONTE,  EM  ATIVIDADES  DE  MANOBRA,  NOS  PONTOS  DE TRANSFERÊNCIA DE CARGA E DE VIRADORES." , ""} )
		aAdd( aBody, { "", "000033 " , "02.019 " , "ATIVIDADES  PERMANENTES  COM  CARVÃO  DO  SUBSOLO  COMPREENDENDO  SERVIÇOS,  TAIS  COMO: OPERAÇÕES  DE  LOCOMOTIVA,  CONDUTORES,  ENGATADORES,  BOMBEIROS,  MADEIREIROS,  TRILHEIROS  E ELETRICISTAS." , ""} )
		aAdd( aBody, { "", "000034 " , "02.020 " , "ATIVIDADES  PERMANENTES  DE  SUPERFÍCIE  COM  CARVÃO  NAS  OPERAÇÕES  A  SECO,  COM  BRITADORES, PENEIRAS,  CLASSIFICADORES,  CARGA  E  DESCARGA  DE  SILOS,  DE  TRANSPORTADORES  DE  CORREIA  E  DE 	TELEFÉRREOS." , ""} )
		aAdd( aBody, { "", "000035 " , "02.021 " , "FABRICAÇÃO  DE  COMPOSTOS  DE  CHUMBO,  CARBONATO,  ARSENIATO,  CROMATO  MÍNIO,  LITARGÍRIO  E OUTROS." , ""} )
		aAdd( aBody, { "", "000036 " , "02.022 " , "FABRICAÇÃO  DE  ESMALTES,  VERNIZES,  CORES,  PIGMENTOS,  TINTAS,  UNGUENTOS,  ÓLEOS,  PASTAS, LÍQUIDOS E PÓS À BASE DE COMPOSTOS DE CHUMBO." , ""} )
		aAdd( aBody, { "", "000037 " , "02.023 " , "FABRICAÇÃO E RESTAURAÇÃO DE ACUMULADORES, PILHAS E BATERIAS ELÉTRICAS CONTENDO COMPOSTOS DE CHUMBO." , ""} )
		aAdd( aBody, { "", "000038 " , "02.024 " , "FABRICAÇÃO E EMPREGO DE CHUMBO TETRAETILA E CHUMBO TETRAMETILA." , ""} )
		aAdd( aBody, { "", "000039 " , "02.025 " , "FUNDIÇÃO E LAMINAÇÃO DE CHUMBO, DE ZINCO VELHO COBRE E LATÃO." , ""} )
		aAdd( aBody, { "", "000040 " , "02.026 " , "LIMPEZA, RASPAGEM E REPARAÇÃO DE TANQUES DE MISTURA, ARMAZENAMENTO E DEMAIS TRABALHOS COM GASOLINA CONTENDO CHUMBO TETRAETILA." , ""} )
		aAdd( aBody, { "", "000041 " , "02.027 " , "PINTURA  A  PISTOLA  COM  PIGMENTOS  DE  COMPOSTOS  DE  CHUMBO  EM  RECINTOS  LIMITADOS  OU FECHADOS." , ""} )
		aAdd( aBody, { "", "000042 " , "02.028 " , "VULCANIZAÇÃO DE BORRACHA PELO LITARGÍRIO OU OUTROS COMPOSTOS DE CHUMBO." , ""} )
		aAdd( aBody, { "", "000043 " , "02.029 " , "APLICAÇÃO   E   EMPREGO DE   ESMALTES,   VERNIZES,   CORES, PIGMENTOS, TINTAS, UNGUENTOS, ÓLEOS, PASTAS, LÍQUIDOS E PÓS À BASE DE COMPOSTOS DE CHUMBO." , ""} )
		aAdd( aBody, { "", "000044 " , "02.030 " , "FABRICAÇÃO DE PORCELANA COM ESMALTES DE COMPOSTOS DE CHUMBO." , ""} )
		aAdd( aBody, { "", "000045 " , "02.031 " , "PINTURA  E  DECORAÇÃO  MANUAL  (PINCEL,  ROLO  E  ESCOVA)  COM  PIGMENTOS  DE  COMPOSTOS  DE CHUMBO (EXCETO PINCEL CAPILAR), EM RECINTOS LIMITADOS OU FECHADOS." , ""} )
		aAdd( aBody, { "", "000046 " , "02.032 " , "TINTURARIA E ESTAMPARIA COM PIGMENTOS À BASE DE COMPOSTOS DE CHUMBO." , ""} )
		aAdd( aBody, { "", "000047 " , "02.033 " , "PINTURA A PISTOLA OU MANUAL COM PIGMENTOS DE COMPOSTOS DE CHUMBO AO AR LIVRE." , ""} )
		aAdd( aBody, { "", "000048 " , "02.034 " , "FABRICAÇÃO DE CROMATOS E BICROMATOS." , ""} )
		aAdd( aBody, { "", "000049 " , "02.035 " , "PINTURA  A  PISTOLA  COM  PIGMENTOS  DE  COMPOSTOS  DE  CROMO,  EM  RECINTOS  LIMITADOS  OU FECHADOS." , ""} )
		aAdd( aBody, { "", "000050 " , "02.036 " , "CROMAGEM ELETROLÍTICA DOS METAIS." , ""} )
		aAdd( aBody, { "", "000051 " , "02.037 " , "FABRICAÇÃO  DE  PALITOS  FOSFÓRICOS  À  BASE  DE  COMPOSTOS  DE  CROMO  (PREPARAÇÃO  DA  PASTA  E TRABALHO NOS SECADORES)." , ""} )
		aAdd( aBody, { "", "000052 " , "02.038 " , "MANIPULAÇÃO DE CROMATOS E BICROMATOS." , ""} )
		aAdd( aBody, { "", "000053 " , "02.039 " , "PINTURA MANUAL COM PIGMENTOS DE COMPOSTOS DE CROMO EM RECINTOS LIMITADOS OU FECHADOS (EXCETO PINCEL CAPILAR)." , ""} )
		aAdd( aBody, { "", "000054 " , "02.040 " , "PREPARAÇÃO POR PROCESSOS FOTOMECÂNICOS DE CLICHÊS PARA IMPRESSÃO À BASE DE COMPOSTOS DE CROMO." , ""} )
		aAdd( aBody, { "", "000055 " , "02.041 " , "TANAGEM A CROMO." , ""} )
		aAdd( aBody, { "", "000056 " , "02.042 " , "EXTRAÇÃO E PREPARAÇÃO DE FÓSFORO BRANCO E SEUS COMPOSTOS." , ""} )
		aAdd( aBody, { "", "000057 " , "02.043 " , "FABRICAÇÃO DE DEFENSIVOS FOSFORADOS E ORGANOFOSFORADOS." , ""} )
		aAdd( aBody, { "", "000058 " , "02.044 " , "FABRICAÇÃO  DE  PROJÉTEIS  INCENDIÁRIOS,  EXPLOSIVOS  E  GASES  ASFIXIANTES  À  BASE  DE  FÓSFORO BRANCO." , ""} )
		aAdd( aBody, { "", "000059 " , "02.045 " , "EMPREGO DE DEFENSIVOS ORGANOFOSFORADOS." , ""} )
		aAdd( aBody, { "", "000060 " , "02.046 " , "FABRICAÇÃO DE BRONZE FOSFORADO." , ""} )
		aAdd( aBody, { "", "000061 " , "02.047 " , "FABRICAÇÃO DE MECHAS FOSFORADAS PARA LÂMPADAS DE MINEIROS." , ""} )
		aAdd( aBody, { "", "000062 " , "02.048 " , "DESTILAÇÃO DO ALCATRÃO DA HULHA." , ""} )
		aAdd( aBody, { "", "000063 " , "02.049 " , "DESTILAÇÃO DO PETRÓLEO." , ""} )
		aAdd( aBody, { "", "000064 " , "02.050 " , "MANIPULAÇÃO DE ALCATRÃO, BREU, BETUME, ANTRACENO, ÓLEOS MINERAIS, ÓLEO QUEIMADO, PARAFINA OU OUTRAS SUBSTÂNCIAS CANCERÍGENAS AFINS." , ""} )
		aAdd( aBody, { "", "000065 " , "02.051 " , "FABRICAÇÃO   DE   FENÓIS,   CRESÓIS,   NAFTÓIS,   NITRODERIVADOS,   AMINODERIVADOS,   DERIVADOS HALOGENADOS E OUTRAS SUBSTÂNCIAS TÓXICAS DERIVADAS DE HIDROCARBONETOS CÍCLICOS." , ""} )
		aAdd( aBody, { "", "000066 " , "02.052 " , "PINTURA  A  PISTOLA  COM  ESMALTES,  TINTAS,  VERNIZES  E  SOLVENTES  CONTENDO  HIDROCARBONETOS AROMÁTICOS." , ""} )
		aAdd( aBody, { "", "000067 " , "02.053 " , "EMPREGO    DE    DEFENSIVOS    ORGANOCLORADOS:    DDT    (DICLORODIFENILTRICLORETANO),    DDD (DICLORODIFENILDICLORETANO),  METOXICLORO  (DIMETOXIDIFENILTRICLORETANO),  BHC  (HEXACLORETO DE BENZENO) E SEUS COMPOSTOS" , ""} )
		aAdd( aBody, { "", "000068 " , "02.054 " , "EMPREGO DE DEFENSIVOS DERIVADOS DO ÁCIDO CARBÔNICO." , ""} )
		aAdd( aBody, { "", "000069 " , "02.055 " , "EMPREGO DE AMINODERIVADOS DE HIDROCARBONETOS AROMÁTICOS (HOMÓLOGOS DA ANILINA)." , ""} )
		aAdd( aBody, { "", "000070 " , "02.056 " , "EMPREGO DE CRESOL, NAFTALENO E DERIVADOS TÓXICOS." , ""} )
		aAdd( aBody, { "", "000071 " , "02.057 " , "EMPREGO  DE  ISOCIANATOS  NA  FORMAÇÃO  DE  POLIURETANAS  (LACAS  DE  DESMOLDAGEM,  LACAS  DE DUPLA  COMPOSIÇÃO,  LACAS  PROTETORAS  DE  MADEIRA  E  METAIS,  ADESIVOS  ESPECIAIS  E  OUTROS PRODUTOS À BASE DE POLIISOCIANETOS E POLIURETANAS)." , ""} )
		aAdd( aBody, { "", "000072 " , "02.058 " , "EMPREGO DE PRODUTOS CONTENDO HIDROCARBONETOS AROMÁTICOS COMO SOLVENTES OU EM LIMPEZA DE PEÇAS." , ""} )
		aAdd( aBody, { "", "000073 " , "02.059 " , "FABRICAÇÃO  DE  ARTIGOS  DE  BORRACHA,  DE  PRODUTOS  PARA  IMPERMEABILIZAÇÃO  E  DE  TECIDOS IMPERMEÁVEIS À BASE DE HIDROCARBONETOS." , ""} )
		aAdd( aBody, { "", "000074 " , "02.060 " , "FABRICAÇÃO  DE  LINÓLEOS,  CELULOIDES,  LACAS,  TINTAS,  ESMALTES,  VERNIZES,  SOLVENTES,  COLAS, ARTEFATOS DE EBONITE, GUTA-PERCHA, CHAPÉUS DE PALHA E OUTROS À BASE DE HIDROCARBONETOS." , ""} )
		aAdd( aBody, { "", "000075 " , "02.061 " , "LIMPEZA DE PEÇAS OU MOTORES COM ÓLEO DIESEL APLICADO SOB PRESSÃO (NEBULIZAÇÃO)." , ""} )
		aAdd( aBody, { "", "000076 " , "02.062 " , "PINTURA  A  PINCEL  COM  ESMALTES,  TINTAS  E  VERNIZES  EM  SOLVENTE  CONTENDO  HIDROCARBONETOS AROMÁTICOS." , ""} )
		aAdd( aBody, { "", "000077 " , "02.063 " , "FABRICAÇÃO E MANIPULAÇÃO DE COMPOSTOS ORGÂNICOS DE MERCÚRIO." , ""} )
		aAdd( aBody, { "", "000078 " , "02.064 " , "OPERAÇÕES QUE DESPRENDAM POEIRA DE SILICATOS EM TRABALHOS PERMANENTES NO SUBSOLO, EM MINAS E TÚNEIS (OPERAÇÕES DE CORTE, FURAÇÃO, DESMONTE, CARREGAMENTOS E OUTRAS ATIVIDADES EXERCIDAS NO LOCAL DO DESMONTE E BRITAGEM NO SUBSOLO)." , ""} )
		aAdd( aBody, { "", "000079 " , "02.065 " , "OPERAÇÕES DE EXTRAÇÃO, TRITURAÇÃO E MOAGEM DE TALCO." , ""} )
		aAdd( aBody, { "", "000080 " , "02.066 " , "FABRICAÇÃO  DE  MATERIAL  REFRATÁRIO,  COMO  REFRATÁRIOS  PARA  FÔRMAS,  CHAMINÉS  E  CADINHOS; RECUPERAÇÃO DE RESÍDUOS." , ""} )
		aAdd( aBody, { "", "000081 " , "02.067 " , "EXPOSIÇÃO OU CONTATO, POR QUALQUER VIA COM 4-AMINO DIFENIL (P-XENILAMINA)." , ""} )
		aAdd( aBody, { "", "000082 " , "02.068 " , "PRODUÇÃO DE BENZIDINA." , ""} )
		aAdd( aBody, { "", "000083 " , "02.069 " , "EXPOSIÇÃO OU CONTATO, POR QUALQUER VIA COM BETANAFTILAMINA." , ""} )
		aAdd( aBody, { "", "000084 " , "02.070 " , "EXPOSIÇÃO OU CONTATO, POR QUALQUER VIA COM 4-NITRODIFENIL." , ""} )
		aAdd( aBody, { "", "000085 " , "02.071 " , "OPERAÇÕES COM ÉTER BIS (CLORO-METÍLICO)." , ""} )
		aAdd( aBody, { "", "000086 " , "02.072 " , "OPERAÇÕES COM BENZOPIRENO." , ""} )
		aAdd( aBody, { "", "000087 " , "02.073 " , "OPERAÇÕES COM BERÍLIO." , ""} )
		aAdd( aBody, { "", "000088 " , "02.074 " , "OPERAÇÕES COM CLORETO DE DIMETIL-CARBAMILA." , ""} )
		aAdd( aBody, { "", "000089 " , "02.075 " , "OPERAÇÕES COM 3,3'-DICLORO-BENZIDINA." , ""} )
		aAdd( aBody, { "", "000090 " , "02.076 " , "OPERAÇÕES COM DIÓXIDO DE VINIL CICLOHEXANO." , ""} )
		aAdd( aBody, { "", "000091 " , "02.077 " , "OPERAÇÕES COM EPICLORIDRINA." , ""} )
		aAdd( aBody, { "", "000092 " , "02.078 " , "OPERAÇÕES COM HEXAMETILFOSFORAMIDA." , ""} )
		aAdd( aBody, { "", "000093 " , "02.079 " , "OPERAÇÕES COM 4,4'-METILENO BIS (2-CLORO ANILINA)." , ""} )
		aAdd( aBody, { "", "000094 " , "02.080 " , "OPERAÇÕES COM 4,4'-METILENO DIANILINA." , ""} )
		aAdd( aBody, { "", "000095 " , "02.081 " , "OPERAÇÕES COM NITROSAMINAS." , ""} )
		aAdd( aBody, { "", "000096 " , "02.082 " , "OPERAÇÕES COM PROPANO SULTONE." , ""} )
		aAdd( aBody, { "", "000097 " , "02.083 " , "OPERAÇÕES COM BETAPROPIOLACTONA." , ""} )
		aAdd( aBody, { "", "000098 " , "02.084 " , "OPERAÇÕES COM TÁLIO." , ""} )
		aAdd( aBody, { "", "000099 " , "02.085 " , "PRODUÇÃO DE TRIÓXIDO DE AMÔNIO." , ""} )
		aAdd( aBody, { "", "000100 " , "02.086 " , "USTULAÇÃO DE SULFETO DE NÍQUEL." , ""} )
		aAdd( aBody, { "", "000101 " , "02.087 " , "APLICAÇÃO A PISTOLA DE TINTAS DE ALUMÍNIO." , ""} )
		aAdd( aBody, { "", "000102 " , "02.088 " , "FABRICAÇÃO DE PÓS DE ALUMÍNIO (TRITURAÇÃO E MOAGEM)." , ""} )
		aAdd( aBody, { "", "000103 " , "02.089 " , "FABRICAÇÃO DE EMETINA E PULVERIZAÇÃO DE IPECA." , ""} )
		aAdd( aBody, { "", "000104 " , "02.090 " , "FABRICAÇÃO  E  MANIPULAÇÃO  DE  ÁCIDO  OXÁLICO,  NÍTRICO  SULFÚRICO,  BROMÍDRICO,  FOSFÓRICO, PÍCRICO." , ""} )
		aAdd( aBody, { "", "000105 " , "02.091 " , "METALIZAÇÃO A PISTOLA." , ""} )
		aAdd( aBody, { "", "000106 " , "02.092 " , "OPERAÇÕES COM O TIMBÓ." , ""} )
		aAdd( aBody, { "", "000107 " , "02.093 " , "OPERAÇÕES COM BAGAÇO DE CANA NAS FASES DE GRANDE EXPOSIÇÃO À POEIRA." , ""} )
		aAdd( aBody, { "", "000108 " , "02.094 " , "OPERAÇÕES  DE  GALVANOPLASTIA:  DOURAÇÃO,  PRATEAÇÃO,  NIQUELAGEM,  CROMAGEM,  ZINCAGEM, COBREAGEM, ANODIZAÇÃO DE ALUMÍNIO." , ""} )
		aAdd( aBody, { "", "000109 " , "02.095 " , "TELEGRAFIA E RADIOTELEGRAFIA, MANIPULAÇÃO EM APARELHOS DO TIPO MORSE E RECEPÇÃO DE SINAIS EM FONES." , ""} )
		aAdd( aBody, { "", "000110 " , "02.096 " , "TRABALHOS COM ESCÓRIAS DE THOMÁS: REMOÇÃO, TRITURAÇÃO, MOAGEM E ACONDICIONAMENTO." , ""} )
		aAdd( aBody, { "", "000111 " , "02.097 " , "TRABALHO DE RETIRADA, RASPAGEM A SECO E QUEIMA DE PINTURAS." , ""} )
		aAdd( aBody, { "", "000112 " , "02.098 " , "TRABALHOS NA EXTRAÇÃO DE SAL (SALINAS)." , ""} )
		aAdd( aBody, { "", "000113 " , "02.099 " , "FABRICAÇÃO E MANUSEIO DE ÁLCALIS CÁUSTICOS." , ""} )
		aAdd( aBody, { "", "000114 " , "02.100 " , "FABRICAÇÃO E TRANSPORTE DE CAL E CIMENTO NAS FASES DE GRANDE EXPOSIÇÃO A POEIRAS." , ""} )
		aAdd( aBody, { "", "000115 " , "02.101 " , "TRABALHOS DE CARREGAMENTO, DESCARREGAMENTO OU REMOÇÃO DE ENXOFRE OU SULFITOS EM GERAL, EM SACOS OU A GRANEL." , ""} )
		aAdd( aBody, { "", "000116 " , "02.102 " , "TRABALHOS NO SUBSOLO COM EXPOSIÇÃO A MANGANÊS." , ""} )
		aAdd( aBody, { "", "000117 " , "02.103 " , "TRABALHOS NA SUPERFÍCIE COM EXPOSIÇÃO A MANGANÊS." , ""} )
		
		// ATIVIDADES E OPERAÇÕES PERIGOSAS COM EXPLOSIVOS
		aAdd( aBody, { "", "000118 " , "03.001 " , "ARMAZENAMENTO DE EXPLOSIVOS." , ""} )
		aAdd( aBody, { "", "000119 " , "03.002 " , "TRANSPORTE DE EXPLOSIVOS." , ""} )
		aAdd( aBody, { "", "000120 " , "03.003 " , "OPERAÇÃO DE ESCORVA DOS CARTUCHOS DE EXPLOSIVOS." , ""} )
		aAdd( aBody, { "", "000121 " , "03.004 " , "OPERAÇÃO DE CARREGAMENTO DE EXPLOSIVOS." , ""} )
		aAdd( aBody, { "", "000122 " , "03.005 " , "DETONAÇÃO DE EXPLOSIVOS." , ""} )
		aAdd( aBody, { "", "000123 " , "03.006 " , "VERIFICAÇÃO DE DETONAÇÕES DE EXPLOSIVOS FALHADAS." , ""} )
		aAdd( aBody, { "", "000124 " , "03.007 " , "QUEIMA E DESTRUIÇÃO DE EXPLOSIVOS DETERIORADOS." , ""} )
		aAdd( aBody, { "", "000125 " , "03.008 " , "OPERAÇÕES DE MANUSEIO DE EXPLOSIVOS." , ""} )
		
		// ATIVIDADES E OPERAÇÕES PERIGOSAS COM INFLAMÁVEIS
		aAdd( aBody, { "", "000126 " , "04.001 " , "PRODUÇÃO, TRANSPORTE, PROCESSAMENTO E ARMAZENAMENTO DE GÁS LIQUEFEITO." , ""} )
		aAdd( aBody, { "", "000127 " , "04.002 " , "TRANSPORTE E ARMAZENAGEM DE INFLAMÁVEIS LÍQUIDOS E GASOSOS LIQUEFEITOS E DE VASILHAMES VAZIOS NÃO-DESGASEIFICADOS OU DECANTADOS (TODOS OS TRABALHADORES DA ÁREA DE OPERAÇÃO)." , ""} )
		aAdd( aBody, { "", "000128 " , "04.003 " , "REABASTECIMENTO DE AERONAVES (TODOS OS TRABALHADORES NESSAS ATIVIDADES OU QUE OPERAM NA ÁREA DE RISCO)." , ""} )
		aAdd( aBody, { "", "000129 " , "04.004 " , "OPERAÇÕES  NOS  LOCAIS  DE  CARREGAMENTO  DE  NAVIOS-TANQUES,  VAGÕES-TANQUES  E  CAMINHÕES- TANQUES  E  ENCHIMENTO  DE  VASILHAMES,  COM  INFLAMÁVEIS  LÍQUIDOS  OU  GASOSOS  LIQUEFEITOS (TODOS OS TRABALHADORES NESSAS ATIVIDADES OU QUE OPERAM NA ÁREA DE RISCO)." , ""} )
		aAdd( aBody, { "", "000130 " , "04.005 " , "OPERAÇÕES NOS LOCAIS DE DESCARGA DE NAVIOS-TANQUES, VAGÕES-TANQUES E CAMINHÕES-TANQUES COM   INFLAMÁVEIS   LÍQUIDOS   OU   GASOSOS   LIQUEFEITOS   OU   DE   VASILHAMES   VAZIOS   NÃO- DESGASEIFICADOS OU DECANTADOS (TODOS OS TRABALHADORES NESSAS ATIVIDADES OU QUE OPERAM NA ÁREA DE RISCO)." , ""} )
		aAdd( aBody, { "", "000131 " , "04.006 " , "SERVIÇOS   DE   OPERAÇÕES   E   MANUTENÇÃO   DE   NAVIOS-TANQUE,   VAGÕES-TANQUES,   CAMINHÕES- TANQUES, BOMBAS E VASILHAMES, COM INFLAMÁVEIS LÍQUIDOS OU GASOSOS LIQUEFEITOS, OU VAZIOS NÃO-DESGASEIFICADOS  OU  DECANTADOS  (TODOS  OS  TRABALHADORES  NESSAS  ATIVIDADES  OU  QUE OPERAM NA ÁREA DE RISCO)." , ""} )
		aAdd( aBody, { "", "000132 " , "04.007 " , "OPERAÇÕES  DE  DESGASEIFICAÇÃO,  DECANTAÇÃO  E  REPAROS  DE  VASILHAMES  DE  INFLAMÁVEIS  NÃO- DESGASEIFICADOS OU DECANTADOS (TODOS OS TRABALHADORES NESSAS ATIVIDADES OU QUE OPERAM NA ÁREA DE RISCO)." , ""} )
		aAdd( aBody, { "", "000133 " , "04.008 " , "OPERAÇÕES  DE  TESTES  DE  APARELHOS  DE  CONSUMO  DO  GÁS  E  SEUS  EQUIPAMENTOS  (TODOS  OS TRABALHADORES NESSAS ATIVIDADES OU QUE OPERAM NA ÁREA DE RISCO)." , ""} )
		aAdd( aBody, { "", "000134 " , "04.009 " , "TRANSPORTE DE INFLAMÁVEIS LÍQUIDOS E GASOSOS LIQUEFEITOS EM CAMINHÃO-TANQUE (MOTORISTA E AJUDANTES)." , ""} )
		aAdd( aBody, { "", "000135 " , "04.010 " , "TRANSPORTE  DE  VASILHAMES  (EM  CAMINHÕES  DE  CARGA),  CONTENDO  INFLAMÁVEL  LÍQUIDO,  EM QUANTIDADE TOTAL IGUAL OU SUPERIOR A 200 LITROS (MOTORISTA E AJUDANTES)." , ""} )
		aAdd( aBody, { "", "000136 " , "04.011 " , "TRANSPORTE DE VASILHAMES (EM CARRETA OU CAMINHÃO DE CARGA), CONTENDO INFLAMÁVEL GASOSOS E LÍQUIDO, EM QUANTIDADE TOTAL IGUAL OU SUPERIOR A 135 QUILOS (MOTORISTA E AJUDANTES)." , ""} )
		aAdd( aBody, { "", "000137 " , "04.012 " , "OPERAÇÃO  EM  POSTOS  DE  SERVIÇO  E  BOMBAS  DE  ABASTECIMENTO  DE  INFLAMÁVEIS  LÍQUIDOS (OPERADOR DE BOMBA E TRABALHADORES QUE OPERAM NA ÁREA DE RISCO)." , ""} )
		aAdd( aBody, { "", "000138 " , "04.013 " , "TRABALHO  EM  POÇOS  DE  PETRÓLEO  EM  PRODUÇÃO  DE  GÁS  (CÍRCULO  COM  RAIO  DE  30  METROS,  NO MÍNIMO, COM CENTRO NA BOCA DO POÇO)." , ""} )
		aAdd( aBody, { "", "000139 " , "04.014 " , "TRABALHO EM UNIDADE DE PROCESSAMENTO DAS REFINARIAS (FAIXA DE 30 METROS DE LARGURA, NO MÍNIMO, CONTORNANDO A ÁREA DE OPERAÇÃO)." , ""} )
		aAdd( aBody, { "", "000140 " , "04.015 " , "OPERAÇÕES  COM INFLAMÁVEIS EM REFINARIA, EM  ESTADO DE VOLATILIZAÇÃO OU  POSSIBILIDADE DE VOLATILIZAÇÃO DECORRENTE DE FALHA OU DEFEITO DOS SISTEMAS DE SEGURANÇA E FECHAMENTO DAS VÁLVULAS (FAIXA DE 15 METROS DE LARGURA, NO MÍNIMO, CONTORNANDO A ÁREA DE OPERAÇÃO)." , ""} )
		aAdd( aBody, { "", "000141 " , "04.016 " , "OPERAÇÕES EM TANQUES DE INFLAMÁVEIS LÍQUIDOS (TODA A BACIA DE SEGURANÇA)." , ""} )
		aAdd( aBody, { "", "000142 " , "04.017 " , "OPERAÇÕES EM TANQUES ELEVADOS DE INFLAMÁVEIS GASOSOS (CÍRCULO COM RAIO DE 3 METROS COM CENTRO NOS PONTOS DE VAZAMENTO EVENTUAL (VÁLVULA REGISTROS, DISPOSITIVOS DE MEDIÇÃO POR ESCAPAMENTO, GAXETAS))." , ""} )
		aAdd( aBody, { "", "000143 " , "04.018 " , "CARGA   E   DESCARGA   DE   INFLAMÁVEIS   LÍQUIDOS   CONTIDOS   EM   NAVIOS,   CHATAS   E   BATELÕES (AFASTAMENTO   DE   15   METROS   DA   BEIRA   DO   CAIS,   DURANTE   A   OPERAÇÃO,   COM   EXTENSÃO CORRESPONDENTE AO COMPRIMENTO DA EMBARCAÇÃO)." , ""} )
		aAdd( aBody, { "", "000144 " , "04.019 " , "ABASTECIMENTO DE AERONAVES (TODA A ÁREA DE OPERAÇÃO)." , ""} )
		aAdd( aBody, { "", "000145 " , "04.020 " , "ENCHIMENTO DE VAGÕES - TANQUES E CAMINHÕES - TANQUES COM INFLAMÁVEIS LÍQUIDOS (CÍRCULO COM RAIO DE 15 METROS COM CENTRO NAS BOCAS DE ENCHIMENTO DOS TANQUES)." , ""} )
		aAdd( aBody, { "", "000146 " , "04.021 " , "ENCHIMENTO   DE   VAGÕES-TANQUES   E   CAMINHÕES-TANQUES   INFLAMÁVEIS   GASOSOS   LIQUEFEITOS (CÍRCULO COM 7,5 METROS CENTRO NOS PONTOS DE VAZAMENTO EVENTUAL (VÁLVULA E REGISTROS))." , ""} )
		aAdd( aBody, { "", "000147 " , "04.022 " , "ENCHIMENTO DE VASILHAMES COM INFLAMÁVEIS GASOSOS LIQUEFEITOS (CÍRCULOS COM RAIO DE 15 METROS COM CENTRO NOS BICOS DE ENCHIMENTOS)." , ""} )
		aAdd( aBody, { "", "000148 " , "04.023 " , "ENCHIMENTO DE VASILHAMES COM INFLAMÁVEIS LÍQUIDOS, EM LOCAIS ABERTOS (CÍRCULO COM RAIO DE 7,5 METROS COM CENTRO NOS BICOS DE ENCHIMENTO)." , ""} )
		aAdd( aBody, { "", "000149 " , "04.024 " , "ENCHIMENTO  DE  VASILHAMES  COM  INFLAMÁVEIS  LÍQUIDOS,  EM  RECINTO  FECHADO  (TODA  A  ÁREA INTERNA DO RECINTO)." , ""} )
		aAdd( aBody, { "", "000150 " , "04.025 " , "MANUTENÇÃO DE VIATURAS-TANQUES, BOMBAS E VASILHAMES QUE CONTINHAM INFLAMÁVEL LÍQUIDO (LOCAL DE OPERAÇÃO, ACRESCIDO DE FAIXA DE 7,5 METROS DE LARGURA EM TORNO DOS SEUS PONTOS EXTERNOS)." , ""} )
		aAdd( aBody, { "", "000151 " , "04.026 " , "DESGASEIFICAÇÃO, DECANTAÇÃO E REPAROS DE VASILHAMES NÃO DESGASEIFICADOS OU DECANTADOS, UTILIZADOS  NO  TRANSPORTE  DE  INFLAMÁVEIS  (LOCAL  DA  OPERAÇÃO,  ACRESCIDO  DE  FAIXA  DE  7,5 METROS DE LARGURA EM TORNO DOS SEUS PONTOS EXTERNOS)." , ""} )
		aAdd( aBody, { "", "000152 " , "04.027 " , "TESTES EM APARELHOS DE CONSUMO DE GÁS E SEUS EQUIPAMENTOS (LOCAL DA OPERAÇÃO, ACRESCIDO DE FAIXA DE 7,5 METROS DE LARGURA EM TORNO DOS SEUS PONTOS EXTREMOS)." , ""} )
		aAdd( aBody, { "", "000153 " , "04.028 " , "ABASTECIMENTO DE INFLAMÁVEIS (TODA A ÁREA DE OPERAÇÃO, ABRANGENDO, NO MÍNIMO, CÍRCULO COM RAIO DE 7,5 METROS COM CENTRO NO PONTO DE ABASTECIMENTO E O CÍRCULO COM RAIO DE 7,5 METROS COM CENTRO NA BOMBA DE ABASTECIMENTO DA VIATURA E FAIXA DE 7,5 METROS DE LARGURA PARA AMBOS OS LADOS DA MÁQUINA)." , ""} )
		aAdd( aBody, { "", "000154 " , "04.029 " , "ARMAZENAMENTO   DE   VASILHAMES   QUE   CONTENHAM   INFLAMÁVEIS   LÍQUIDOS   OU   VAZIOS   NÃO DESGASEIFICADOS OU DECANTADOS, EM LOCAIS ABERTOS (FAIXA DE 3 METROS DE LARGURA EM TORNO DOS SEUS PONTOS EXTERNOS)." , ""} )
		aAdd( aBody, { "", "000155 " , "04.030 " , "ARMAZENAMENTO   DE   VASILHAMES   QUE   CONTENHAM   INFLAMÁVEIS   LÍQUIDOS   OU   VAZIOS   NÃO DESGASEIFICADOS, OU DECANTADOS, EM RECINTO FECHADO (TODA A ÁREA INTERNA DO RECINTO)." , ""} )
		aAdd( aBody, { "", "000156 " , "04.031 " , "CARGA E DESCARGA DE VASILHAMES CONTENDO INFLAMÁVEIS LÍQUIDOS OU VASILHAMES VAZIOS NÃO DESGASEIFICADOS OU DECANTADOS, TRANSPORTADOS PÔR NAVIOS, CHATAS OU BATELÕES (AFASTAMENTO DE  3  METROS  DA  BEIRA  DO  CAIS,  DURANTE  A  OPERAÇÃO,  COM  EXTENSÃO  CORRESPONDENTE  AO COMPRIMENTO DA EMBARCAÇÃO)." , ""} )
		
		// ATIVIDADES E OPERAÇÕES PERIGOSAS COM RADIAÇÕES IONIZANTES OU SUBSTÂNCIAS RADIOATIVAS
		aAdd( aBody, { "", "000157 " , "05.001 " , "PRODUÇÃO,   UTILIZAÇÃO,   PROCESSAMENTO,   TRANSPORTE,   GUARDA,   ESTOCAGEM,   E   MANUSEIO   DE MATERIAIS RADIOATIVOS, SELADOS E NÃO SELADOS, DE ESTADO FÍSICO E FORMA QUÍMICA QUAISQUER, NATURAIS OU ARTIFICIAIS (MINAS E DEPÓSITOS DE MATERIAIS RADIOATIVOS. PLANTAS-PILOTO E USINAS DE BENEFICIAMENTO DE MINERAIS RADIOATIVOS. OUTRAS ÁREAS SUJEITAS A RISCO POTENCIAL DEVIDO ÀS RADIAÇÕES IONIZANTES)", ""} )				
		aAdd( aBody, { "", "000158 " , "05.002 " , "ATIVIDADES  DE  OPERAÇÃO   E  MANUTENÇÃO   DE  REATORES  NUCLEARES  (EDIFÍCIOS  DE   REATORES; EDIFÍCIOS              DE              ESTOCAGEM              DE              COMBUSTÍVEL)", ""} )
		aAdd( aBody, { "", "000159 " , "05.003 " , "ATIVIDADES DE OPERAÇÃO E MANUTENÇÃO DE ACELERADORES DE PARTÍCULAS (ÁREAS DE IRRADIAÇÃO DE ALVOS)", ""} )
		aAdd( aBody, { "", "000160 " , "05.004 " , "ATIVIDADES  DE  OPERAÇÃO  COM  APARELHOS  DE  RAIOS-X,  COM  IRRADIADORES  DE  RADIAÇÃO  GAMA, RADIAÇÃO BETA OU RADIAÇÃO DE NÊUTRONS (SALAS DE IRRADIAÇÃO E DE OPERAÇÃO DE APARELHOS DE RAIOS-X E DE IRRADIADORES GAMA, BETA OU NÊUTRONS)", ""} )
		aAdd( aBody, { "", "000161 " , "05.005 " , "ATIVIDADES DE MEDICINA NUCLEAR (SALAS DE DIAGNÓSTICO E TERAPIA COM MEDICINA NUCLEAR)." , ""} )
		aAdd( aBody, { "", "000162 " , "05.006 " , "MANUSEIO E APLICAÇÃO DE RADIOISÓTOPOS PARA DIAGNÓSTICO MÉDICO E TERAPIA (ENFERMARIA DE PACIENTES, SOB TREINAMENTO COM RADIOISÓTOPOS. ENFERMARIA DE PACIENTES CONTAMINADOS COM RADIOISÓTOPOS EM OBSERVAÇÃO E SOB TRATAMENTO DE DESCONTAMINAÇÃO)." , ""} )
		aAdd( aBody, { "", "000163 " , "05.007 " , "ATIVIDADES   DE   MEDICINA   NUCLEAR:   MANUSEIO   DE   FONTES   SELADAS   PARA   APLICAÇÃO   EM BRAQUITERAPIA (ÁREA DE TRATAMENTO E ESTOCAGEM DE REJEITOS RADIOATIVOS)." , ""} )
		aAdd( aBody, { "", "000164 " , "05.008 " , "ATIVIDADES   DE   MEDICINA   NUCLEAR:   OBTENÇÃO   DE   DADOS   BIOLÓGICOS   DE   PACIENTES   COM RADIOISÓTOPOS INCORPORADOS (MANUSEIO DE MATERIAIS BIOLÓGICOS CONTENDO RADIOISÓTOPOS OU MOLÉCULAS MARCADAS)." , ""} )
		aAdd( aBody, { "", "000165 " , "05.009 " , "ATIVIDADES  DE  MEDICINA  NUCLEAR:  SEGREGAÇÃO,  MANUSEIO,  TRATAMENTO,  ACONDICIONAMENTO  E ESTOCAGEM     DE     REJEITOS     RADIOATIVOS     EM     MEDICINA     NUCLEAR     (LABORATÓRIOS     PARA DESCONTAMINAÇÃO E COLETA DE REJEITOS RADIOATIVOS)." , ""} )
		aAdd( aBody, { "", "000166 " , "05.010 " , "DESCOMISSIONAMENTO DE INSTALAÇÕES NUCLEARES E RADIOATIVAS (ÁREAS DE INSTALAÇÕES NUCLEARES E RADIOATIVAS CONTAMINADAS E COM REJEITOS) QUE INCLUI:", ""} )
		aAdd( aBody, { "", "000167 " , "05.011 " , "DESCOMISSIONAMENTO  DE  MINAS,  MOINHOS  E  USINAS  DE  TRATAMENTO  DE  MINERAIS  RADIOATIVOS (TRATAMENTO DE REJEITOS MINERAIS. REPOSITÓRIO DE REJEITOS NATURAIS (BACIA  DE CONTENÇÃO DE RÁDIO E OUTROS RADIOISÓTOPOS). DEPOSIÇÃO DE GANGAS E REJEITOS DE MINERAÇÃO)." , ""} )
		
		// ATIVIDADES E OPERAÇÕES PERIGOSAS COM EXPOSIÇÃO A ROUBOS OU OUTRAS ESPÉCIES DE VIOLÊNCIA FÍSICA NAS ATIVIDADES PROFISSIONAIS DE SEGURANÇA PESSOAL OU PATRIMONIAL		
		aAdd( aBody, { "", "000168 " , "06.001 " , "VIGILÂNCIA PATRIMONIAL: SEGURANÇA PATRIMONIAL E/OU PESSOAL NA PRESERVAÇÃO DO PATRIMÔNIO EM ESTABELECIMENTOS PÚBLICOS OU PRIVADOS E DA INCOLUMIDADE FÍSICA DE PESSOAS." , ""} )
		aAdd( aBody, { "", "000169 " , "06.002 " , "SEGURANÇA  DE  EVENTOS:  SEGURANÇA  PATRIMONIAL  E/OU  PESSOAL  EM  ESPAÇOS   PÚBLICOS  OU PRIVADOS, DE USO COMUM DO POVO." , ""} )
		aAdd( aBody, { "", "000170 " , "06.003 " , "SEGURANÇA  NOS  TRANSPORTES  COLETIVOS:  SEGURANÇA  PATRIMONIAL  E/OU  PESSOAL  NOS  TRANSPORTES COLETIVOS E EM SUAS RESPECTIVAS INSTALAÇÕES." , ""} )
		aAdd( aBody, { "", "000171 " , "06.004 " , "SEGURANÇA   AMBIENTAL   E   FLORESTAL:   SEGURANÇA   PATRIMONIAL   E/OU   PESSOAL   EM   ÁREAS   DE CONSERVAÇÃO DE FAUNA, FLORA NATURAL E DE REFLORESTAMENTO." , ""} )
		aAdd( aBody, { "", "000172 " , "06.005 " , "TRANSPORTE DE VALORES: SEGURANÇA NA EXECUÇÃO DO SERVIÇO DE TRANSPORTE DE VALORES." , ""} )
		aAdd( aBody, { "", "000173 " , "06.006 " , "ESCOLTA ARMADA: SEGURANÇA NO ACOMPANHAMENTO DE QUALQUER TIPO DE CARGA OU DE VALORES." , ""} )
		aAdd( aBody, { "", "000174 " , "06.007 " , "SEGURANÇA  PESSOAL:  ACOMPANHAMENTO  E  PROTEÇÃO  DA  INTEGRIDADE  FÍSICA  DE  PESSOA  OU  DE GRUPOS." , ""} )
		aAdd( aBody, { "", "000175 " , "06.008 " , "SUPERVISÃO/FISCALIZAÇÃO  OPERACIONAL:  SUPERVISÃO  E/OU  FISCALIZAÇÃO  DIRETA  DOS  LOCAIS  DE TRABALHO PARA ACOMPANHAMENTO E ORIENTAÇÃO DOS VIGILANTES." , ""} )
		aAdd( aBody, { "", "000176 " , "06.009 " , "TELEMONITORAMENTO/TELECONTROLE:  EXECUÇÃO  DE  CONTROLE  E/OU  MONITORAMENTO  DE  LOCAIS, ATRAVÉS DE SISTEMAS ELETRÔNICOS DE SEGURANÇA." , ""} )
		
		// ATIVIDADES E OPERAÇÕES PERIGOSAS COM ENERGIA ELÉTRICA
		aAdd( aBody, { "", "000177 " , "07.001 " , "ATIVIDADES  OU  OPERAÇÕES  EM  INSTALAÇÕES  OU  EQUIPAMENTOS  ELÉTRICOS  ENERGIZADOS  EM  ALTA TENSÃO." , ""} )
		aAdd( aBody, { "", "000178 " , "07.002 " , "ATIVIDADES  OU  OPERAÇÕES  COM  TRABALHO  EM  PROXIMIDADE  DE  INSTALAÇÕES  OU  EQUIPAMENTOS ELÉTRICOS ENERGIZADOS EM ALTA TENSÃO." , ""} )
		aAdd( aBody, { "", "000179 " , "07.003 " , "ATIVIDADES OU OPERAÇÕES EM INSTALAÇÕES OU EQUIPAMENTOS ELÉTRICOS ENERGIZADOS EM BAIXA TENSÃO NO SISTEMA ELÉTRICO DE CONSUMO - SEC." , ""} )
		aAdd( aBody, { "", "000180 " , "07.004 " , "ATIVIDADES,  CONSTANTES  NO  ITEM  4.1  DA  NR  16,  DE  CONSTRUÇÃO,  OPERAÇÃO  E  MANUTENÇÃO  DE REDES  DE  LINHAS  AÉREAS  OU  SUBTERRÂNEAS  DE  ALTA  E  BAIXA  TENSÃO  INTEGRANTES  DO  SEP, ENERGIZADOS  OU  DESENERGIZADOS,  MAS  COM  POSSIBILIDADE  DE  ENERGIZAÇÃO  ACIDENTAL  OU  POR FALHA OPERACIONAL." , ""} )
		aAdd( aBody, { "", "000181 " , "07.005 " , "ATIVIDADES, CONSTANTES NO ITEM 4.2 DA NR 16, DE CONSTRUÇÃO, OPERAÇÃO E MANUTENÇÃO NAS USINAS,   UNIDADES   GERADORAS,   SUBESTAÇÕES   E   CABINAS   DE   DISTRIBUIÇÃO   EM   OPERAÇÕES, INTEGRANTES DO SEP, ENERGIZADOS OU DESENERGIZADOS, MAS COM POSSIBILIDADE DE ENERGIZAÇÃO ACIDENTAL OU POR FALHA OPERACIONAL." , ""} )
		aAdd( aBody, { "", "000182 " , "07.006 " , "ATIVIDADES DE INSPEÇÃO, TESTES, ENSAIOS, CALIBRAÇÃO, MEDIÇÃO E REPAROS EM EQUIPAMENTOS E MATERIAIS  ELÉTRICOS,  ELETRÔNICOS,  ELETROMECÂNICOS  E  DE  SEGURANÇA  INDIVIDUAL  E  COLETIVA  EM SISTEMAS ELÉTRICOS DE POTÊNCIA DE ALTA E BAIXA TENSÃO." , ""} )
		aAdd( aBody, { "", "000183 " , "07.007 " , "ATIVIDADES   DE   TREINAMENTO   EM   EQUIPAMENTOS   OU   INSTALAÇÕES   INTEGRANTES   DO   SEP, ENERGIZADAS  OU  DESENERGIZADAS,  MAS  COM  POSSIBILIDADE  DE  ENERGIZAÇÃO  ACIDENTAL  OU  POR FALHA OPERACIONAL." , ""} )
		
		// ATIVIDADES PERIGOSAS EM MOTOCICLETA
		aAdd( aBody, { "", "000184 " , "08.001 " , "ATIVIDADES  LABORAIS  COM  UTILIZAÇÃO  DE  MOTOCICLETA  OU  MOTONETA  NO  DESLOCAMENTO  DE TRABALHADOR EM VIAS PÚBLICAS." , ""} )
		
		// ATIVIDADES ESPECIAIS POR EXPOSIÇÃO A AGENTES FÍSICOS
		aAdd( aBody, { "", "000185 " , "09.001 " , "TRABALHOS COM PERFURATRIZES E MARTELETES PNEUMÁTICOS." , ""} )
		aAdd( aBody, { "", "000186 " , "09.002 " , "EXTRAÇÃO E BENEFICIAMENTO DE MINERAIS RADIOATIVOS." , ""} )
		aAdd( aBody, { "", "000187 " , "09.003 " , "ATIVIDADES EM MINERAÇÕES COM EXPOSIÇÃO AO RADÔNIO." , ""} )
		aAdd( aBody, { "", "000188 " , "09.004 " , "REALIZAÇÃO   DE   MANUTENÇÃO   E   SUPERVISÃO   EM   UNIDADES   DE   EXTRAÇÃO,   TRATAMENTO   E BENEFICIAMENTO DE MINERAIS RADIOATIVOS COM EXPOSIÇÃO ÀS RADIAÇÕES IONIZANTES." , ""} )
		aAdd( aBody, { "", "000189 " , "09.005 " , "OPERAÇÕES COM REATORES NUCLEARES OU COM FONTES RADIOATIVAS." , ""} )
		aAdd( aBody, { "", "000190 " , "09.006 " , "TRABALHOS  REALIZADOS  COM  EXPOSIÇÃO  AOS  RAIOS  ALFA,  BETA,  GAMA  E  X,  AOS  NÊUTRONS  E  ÀS SUBSTÂNCIAS RADIOATIVAS PARA FINS INDUSTRIAIS, TERAPÊUTICOS E DIAGNÓSTICOS." , ""} )
		aAdd( aBody, { "", "000191 " , "09.007 " , "FABRICAÇÃO E MANIPULAÇÃO DE PRODUTOS RADIOATIVOS." , ""} )
		aAdd( aBody, { "", "000192 " , "09.008 " , "PESQUISAS E ESTUDOS COM RADIAÇÕES IONIZANTES EM LABORATÓRIOS." , ""} )
		aAdd( aBody, { "", "000193 " , "09.009 " , "TRABALHOS EM CAIXÕES OU CÂMARAS HIPERBÁRICAS." , ""} )
		aAdd( aBody, { "", "000194 " , "09.010 " , "TRABALHOS EM TUBULÕES OU TÚNEIS SOB AR COMPRIMIDO." , ""} )
		aAdd( aBody, { "", "000195 " , "09.011 " , "OPERAÇÕES DE MERGULHO COM O USO DE ESCAFANDROS OU OUTROS EQUIPAMENTOS." , ""} )
		
		// OUTRAS ATIVIDADES
		aAdd( aBody, { "", "000196 " , "10.001 " , "OPERAÇÕES EM ATMOSFERA IPVS." , ""} )
		aAdd( aBody, { "", "000197 " , "10.002 " , "OPERAÇÕES EM ESPAÇO CONFINADO." , ""} )
		aAdd( aBody, { "", "000198 " , "10.003 " , "OPERAÇÕES EM ÁREAS CLASSIFICADAS." , ""} )
		aAdd( aBody, { "", "000199 " , "10.005 " , "ATIVIDADE SOB AR COMPRIMIDO." , ""} )
		aAdd( aBody, { "", "000200 " , "10.006 " , "ATIVIDADE SUBMERSA." , ""} )
		aAdd( aBody, { "", "000201 " , "10.007 " , "BOMBEIRO CIVIL." , ""} )
		aAdd( aBody, { "", "000202 " , "10.008 " , "ATIVIDADE PORTUÁRIA CONFORME LEI Nº 4.860/1965." , ""} )
		aAdd( aBody, { "", "000203 " , "10.009 " , "ATIVIDADES EXECUTADAS EM LOCAIS ALAGADOS OU ENCHARCADOS, COM UMIDADE EXCESSIVA." , ""} )
		
		// AUSÊNCIA DE CORRESPONDÊNCIA
		aAdd( aBody, { "", "000204 " , "99.999 " , "AUSÊNCIA DE CORRESPONDÊNCIA." , ""} )
		
		// ATIVIDADES ESPECIAIS POR EXPOSIÇÃO A AGENTES FÍSICOS - Layout 2.5
		aAdd( aBody, { "", "000205 " , "11.001 " , "MINERAÇÃO SUBTERRÂNEA CUJAS ATIVIDADES SEJAM EXERCIDAS AFASTADAS DAS FRENTES DE PRODUÇÃO." , ""} )
		aAdd( aBody, { "", "000206 " , "11.002 " , "TRABALHOS EM ATIVIDADES PERMANENTES NO SUBSOLO DE MINERAÇÕES SUBTERRÂNEAS EM FRENTE DE PRODUÇÃO." , ""} )
		

			
		
		aAdd( aRet, { aHeader, aBody } )
	EndIf

Return( aRet )
