#INCLUDE "PROTHEUS.CH"
#INCLUDE "QUICKSEARCH.CH"
#INCLUDE "TECQ008.CH"

QSSTRUCT TECQ008 DESCRIPTION STR0001 MODULE 28 // "Realizado de Apontamentos de Materiais de Implantação" 

QSMETHOD INIT QSSTRUCT TECQ008
Local cWhere := ""
	
	QSTABLE "TFS" JOIN "TFL" ON "TFL.TFL_CODIGO = TFS.TFS_CODTFL"
	QSTABLE "TFS" JOIN "TFG" ON "TFG.TFG_COD = TFS.TFS_CODTFG" 
	QSTABLE "TFL" JOIN "CN9" ON "CN9.CN9_NUMERO = TFL.TFL_CONTRT AND CN9_REVISA = TFL.TFL_CONREV"
	QSTABLE "TFS" LEFT JOIN "SB1" ON "SB1.B1_COD = TFS.TFS_PRODUT"
	
	// campos do SX3 e indices do SIX
	QSPARENTFIELD "TFL_CONTRT" INDEX ORDER 4 
	QSPARENTFIELD "B1_DESC" INDEX ORDER 3 LABEL STR0007 // "Desc. Produto"
	
	// campos do SX3
	QSFIELD "TFL_CONTRT","TFS_PRODUT","B1_DESC","TFS_DTAPON","TFS_QUANT"

	QSFIELD "VLRTOT" EXPRESSION "(TFS_QUANT * TFG_PRCVEN)" LABEL STR0007 ; // "Valor Total"
	FIELDS "TFS_QUANT", "TFG_PRCVEN" TYPE "N" SIZE 14 DECIMAL 2 PICTURE "@E 99,999,999,999.99"
	
	cWhere := "CN9.CN9_SITUAC = '05' AND TFS.TFS_DTAPON >= '{1}' AND TFS.TFS_DTAPON <= '" + DTOS(Date()) + "'"
	
	QSFILTER STR0003 WHERE StrTran(cWhere, "{1}", DTOS(Date())) // "Hoje" 
	QSFILTER STR0004 WHERE StrTran(cWhere, "{1}", DTOS(Date() - 7)) // "Últimos 7 dias" 
	QSFILTER STR0005 WHERE StrTran(cWhere, "{1}", DTOS(Date() - 30)) // "Últimos 30 dias" 
	QSFILTER STR0006 WHERE StrTran(cWhere, "{1}", DTOS(Date() - 60)) // "Últimos 60 dias" 
Return
