#Include "agrobusiness.agd.sv.business.ch"
#include "protheus.ch"
#include "totvs.framework.treports.integratedprovider.th"

namespace totvs.protheus.agrobusiness.agd//.sv.business
@TotvsFrameworkTReportsIntegratedProvider(active=.T., team="SIGAAGD", tables="NEA",customTables="NEA",name="Lista de Negociações Barter", country="BRA")

/*/{Protheus.doc} BusinessSmartViewBusinessObject:new()
Classe do objeto de negócio do Relatório de Negociação Barter.
@type Class
@version 12.1.2510
@author lindembergson.pacheco
@since 16/03/2026
/*/
Class BusinessSmartViewBusinessObject From totvs.framework.treports.integratedprovider.IntegratedProvider

	Public Method new() 				as object
	Public Method getData() 			as object
	Public Method getSchema() 			as object

	Protected Method BuildFilterJson() 	as object
	Protected Method getType()			as character
	Protected Method NormalizeValue() 	as character

EndClass

/*{Protheus.doc} new
Método de instância da classe
@return object: self
@version 12.1.2510
@author lindembergson.pacheco
@since 16/03/2026
*/ 
Method new() Class BusinessSmartViewBusinessObject

	_Super:new()

	//Define a Área
	self:appendArea( STR0001 )

	//Define o nome do Objeto de Negócio
	self:setDisplayName( STR0002 )

	//Define a descrição do Objeto de Negócio
	self:setDescription( STR0002 )


Return self

/*{Protheus.doc} getData
Retorna os dados do objeto de negócio
@param nPage, numérico, indica a página atual do relatório
@param oFilter, objeto, contém o filtro do SmartView
@return object: self:oData
@version 12.1.2510
@author lindembergson.pacheco
@since 16/03/2026
*/
Method getData( nPage as Numeric, oFilter as object) as object Class BusinessSmartViewBusinessObject

	Local oJsonQryParam 		:= Nil
	Local nX, nY, nZ			:= 0
	Local aInsumos				:= {}
	Local aContratos			:= {}
	Local aItens				:= {}
	Local aFields 				:= {}
	Local aItensInsumos			:= {}
	Local aFieldsInsumos		:= {}
	Local aItensContratos		:= {}
	Local aFieldsContratos		:= {}
	Local oRepository			As Object
	Local oRepositoryInsumo 	As Object
	Local oRepositoryContrato 	As Object


	oJsonQryParam := self:BuildFilterJson(oFilter:GetParameters())

	//buscando negociacao
	oRepository := BusinessRepository():New()
	aFields := oRepository:getFields()
	oRepository:find(nPage, self:getPageSize(), oJsonQryParam)
	aItens := oRepository:getResponse()['items']

	If Len(aItens) > 0

		For nX := 1 To Len(aItens)
			AEval(aFields, {|aField| ;
				IIf(aItens[nX]:HasProperty(aField[1]) .And. aField[3] == 'D', ;
				aItens[nX][aField[1]] := IIf(!Empty(aItens[nX][aField[1]]), ;
				totvs.framework.treports.date.dateToTimeStamp(StoD(strtran(aItens[nX][aField[1]],'-',''))), ; //tratando campo data vindo de API
			totvs.framework.treports.date.stringToTimeStamp(aItens[nX][aField[1]])), ;
				Nil) ;
				})
			//buscando insumos
			oRepositoryInsumo := BusinessItemRepository():New()
			aFieldsInsumos := oRepositoryInsumo:getFields(.T.)
			oRepositoryInsumo:find(nPage, self:getPageSize(), {'filial':aItens[nX]['filial'], 'codigo':aItens[nX]['codigo'], 'versao':aItens[nX]['versao']})
			aItensInsumos := oRepositoryInsumo:getResponse()['items']
			aInsumos := {}
			If Len(aItensInsumos) > 0
				For nY := 1 To Len(aItensInsumos)
					AEval(aFieldsInsumos, {|aField| ;
						IIf(aItensInsumos[nY]:HasProperty(aField[1]) .And. aField[3] == 'D', ;
						aItensInsumos[nY][aField[1]] := IIf(!Empty(aItensInsumos[nY][aField[1]]), ;
						totvs.framework.treports.date.dateToTimeStamp(StoD(strtran(aItensInsumos[nY][aField[1]],'-',''))), ; //tratando campo data vindo de API
					totvs.framework.treports.date.stringToTimeStamp(aItensInsumos[nY][aField[1]])), ;
						Nil) ;
						})
					aAdd(aInsumos, aItensInsumos[nY])
				Next
			EndIf
			//setando insumos
			aItens[nX]['Insumos'] := aInsumos

			//buscando contratos
			oRepositoryContrato := BusinessDataContractRepository():New()
			aFieldsContratos := oRepositoryContrato:getFields(.T.)
			oRepositoryContrato:find(nPage, self:getPageSize(), {'filial':aItens[nX]['filial'], 'codigo':aItens[nX]['codigo'], 'versao':aItens[nX]['versao']})
			aItensContratos := oRepositoryContrato:getResponse()['items']
			aContratos := {}

			If Len(aItensContratos) > 0
				For nZ := 1 To Len(aItensContratos)
					AEval(aFieldsContratos, {|aField| ;
						IIf(aItensContratos[nZ]:HasProperty(aField[1]) .And. aField[3] == 'D', ;
						aItensContratos[nZ][aField[1]] := IIf(!Empty(aItensContratos[nZ][aField[1]]), ;
						totvs.framework.treports.date.dateToTimeStamp(StoD(strtran(aItensContratos[nZ][aField[1]],'-',''))), ; //tratando campo data vindo de API
					totvs.framework.treports.date.stringToTimeStamp(aItensContratos[nZ][aField[1]])), ;
						Nil) ;
						})
					aAdd(aContratos, aItensContratos[nZ])
				Next
			EndIf
			//setando contratos
			aItens[nX]['Contratos'] := aContratos
			//apendando registros
			self:oData:appendData(aItens[nX])
		Next
	EndIf


	FreeObj(oRepository)


Return self:oData

/*{Protheus.doc} getSchema
Retorna a estrutura dos campos
@return object: self:oSchema
@version 12.1.2510
@author lindembergson.pacheco
@since 16/03/2026
*/
method getSchema() as object class BusinessSmartViewBusinessObject

	Local oRepository As Object
	Local oRepositoryInsumo As Object
	Local oRepositoryContrato As Object
	Local aFields  As Array // Campos das propriedades aninhadas

	oRepository := BusinessRepository():New()
	AEval(oRepository:getFields(),{|field| self:addProperty(field[1], field[1], self:getType(field[3]), field[1], field[2]) })
	self:addProperty("Insumos"		, "Insumos"		, "array", "Insumos"	, "Insumos"		)
	self:addProperty("Contratos"	, "Contratos"	, "array", "Contratos"	, "Contratos"	)

	self:addParameter("dataEmissaoDe"		, "Emissão de"			, "date"  , .F., "", .F., .F., "", "MV_PAR01", "Emissão de"			, .F.)
	self:addParameter("dataEmissaoAte"		, "Emissão até"			, "date"  , .F., "", .F., .F., "", "MV_PAR02", "Emissão até"		, .F.)
	self:addParameter("status"				, "Status Negociação"	, "string", .F., "", .F., .F., "", "MV_PAR03", "Status Negociação" 	, .F.)
	self:addParameter("statusAutorizacao"	, "Status Autorizacao"	, "string", .F., "", .F., .F., "", "MV_PAR04", "Status Autorizacao"	, .F.)

	self:addParameter("codigoClienteDe"		, "Cliente de"			, "string", .F., "", .F., .F., "", "MV_PAR05")
	self:addParameter("codigoClienteAte"	, "Cliente até"			, "string", .F., "", .F., .F., "", "MV_PAR06")
	self:addParameter("codigoProdutoDe"		, "Produto de"			, "string", .F., "", .F., .F., "", "MV_PAR07")
	self:addParameter("codigoProdutoAte"	, "Produto até"			, "string", .F., "", .F., .F., "", "MV_PAR08")
	self:addParameter("codigoVendedorDe"	, "Vendedor de"			, "string", .F., "", .F., .F., "", "MV_PAR09")
	self:addParameter("codigoVendedorAte"	, "Vendedor até"		, "string", .F., "", .F., .F., "", "MV_PAR10")
	self:addParameter("codigoSafra"			, "Codigo Safra"		, "string", .F., "", .F., .F., "", "MV_PAR11")

	// self:addParameter("printInsumos"		, "Detalhes de Insumos?"			, "boolean"  , .F., "", .F., .F., "", "MV_PAR01", "Detalhes de Insumos?"			, .F.)
	// self:addParameter("printContratos"		, "Detalhes de Contratos?"			, "boolean"  , .F., "", .F., .F., "", "MV_PAR01", "Detalhes de Contratos?"			, .F.)

	self:setCustomURL("status"				, "/api/agd/v1/smartview/option/AGDA010/status"				,  1) //1 - Combox; 2 - Lookup
	self:setCustomURL("statusAutorizacao"	, "/api/agd/v1/smartview/option/AGDA010/statusAutorizacao"	,  1)
	self:setCustomURL("codigoClienteDe"		, "/api/framework/v1/genericLookupService/smartview/SA1"	,  2)
	self:setCustomURL("codigoClienteAte"	, "/api/framework/v1/genericLookupService/smartview/SA1"	,  2)
	self:setCustomURL("codigoProdutoDe"		, "/api/framework/v1/genericLookupService/smartview/SB1"	,  2)
	self:setCustomURL("codigoProdutoAte"	, "/api/framework/v1/genericLookupService/smartview/SB1"	,  2)
	self:setCustomURL("codigoVendedorDe"	, "/api/framework/v1/genericLookupService/smartview/SA3"	,  2)
	self:setCustomURL("codigoVendedorAte"	, "/api/framework/v1/genericLookupService/smartview/SA3"	,  2)
	self:setCustomURL("codigoSafra"			, "/api/framework/v1/genericLookupService/smartview/NJU"	,  2)


	// Adiciona a nested property Insumos
	aFields := {}
	oRepositoryInsumo := BusinessItemRepository():New()
	AEval(oRepositoryInsumo:getFields(.T.),{|field| AAdd(aFields, {field[1], field[1], self:getType(field[3]), field[1]}) })
	self:transformInNested("Insumos", NIL, aFields)

	// Adiciona a nested property Contratos
	aFields := {}
	oRepositoryContrato := BusinessDataContractRepository():New()
	AEval(oRepositoryContrato:getFields(.T.),{|field| AAdd(aFields, {field[1], field[1], self:getType(field[3]), field[1]}) })
	self:transformInNested("Contratos", NIL, aFields)

return self:oSchema

/*/{Protheus.doc} BuildFilterJson
Formatacao de filtro para uso no repository
@type method
@return variant, json
@param oJsonIn, object, json de parametros do SmartView
@version 12.1.2510
@author lindembergson.pacheco
@since 16/03/2026
/*/
method BuildFilterJson(oJsonIn) as object class BusinessSmartViewBusinessObject

	Local oJsonOut := JsonObject():New()
	Local aKeys    := oJsonIn:GetNames()
	Local cFilter  := ""
	Local cField   := ""
	Local cValue   := ""
	Local cBase    := ""
	Local cOp      := ""
	Local nI       := 0

	For nI := 1 To Len(aKeys)

		cField := aKeys[nI]
		cValue := oJsonIn[cField][1]

		cValue := ::NormalizeValue(cValue)

		If !Empty(cValue)

			cBase := cField
			cOp   := "eq"

			// detecta sufixos
			If Right(cField,2) == "De"
				cBase := SubStr(cField,1,Len(cField)-2)
				cOp   := "ge"
			ElseIf Right(cField,3) == "Ate"
				cBase := SubStr(cField,1,Len(cField)-3)
				cOp   := "le"
			EndIf

			If !Empty(cFilter)
				cFilter += " and "
			EndIf

			cFilter += cBase + " " + cOp + " '" + cValue + "'"

		EndIf

	Next

	cFilter := cFilter + " and status ne '6' "

	oJsonOut["filter"] := cFilter

Return oJsonOut


/*/{Protheus.doc} getType
Formatacao de filtro para uso no repository
@type method
@return variant, string de tipo no formato esparado para SmartView
@param cType, character, tipo de campo da SX3
@version 12.1.2510
@author lindembergson.pacheco
@since 16/03/2026
/*/
method getType(cType) as character class BusinessSmartViewBusinessObject

	Local cRet := ""

	if cType == "M"
		cRet := "memo"
	elseif cType == "D"
		cRet := "date"
	elseif cType == "N"
		cRet := "number"
	else
		cRet := "string"
	endif

return cRet

/*/{Protheus.doc} NormalizeValue
Normalizacao de valores 
@type method
@return variant, string de valor normalizada
@param cValue, character, string de valor recebida
@version 12.1.2510
@author lindembergson.pacheco
@since 16/03/2026
/*/
method NormalizeValue(cValue) as character class BusinessSmartViewBusinessObject

	If ValType(cValue) == "C"

		// timestamp SmartView
		If "T00:00" $ cValue
			cValue := StrTran(SubStr(cValue,1,10),"-","")
		EndIf

		// índice combobox sem filtro
		If cValue == "-1"
			cValue := ""
		EndIf

	EndIf

Return cValue
