#INCLUDE "protheus.ch"
#INCLUDE "quicksearch.ch"
#INCLUDE "MATQ122.ch" 

QSSTRUCT MATQ12201 DESCRIPTION STR0001 MODULE 2	//-- Autorizações de entrega em aberto por fornecedores

QSMETHOD INIT QSSTRUCT MATQ12201

//-- Tabelas envolvidas na consulta e seus relacionamentos
QSTABLE "SC7" JOIN "SA2" ON "A2_COD = C7_FORNECE AND A2_LOJA = C7_LOJA"

//-- Campos/índices utilizados para a pesquisa
QSPARENTFIELD "A2_COD" INDEX ORDER 1 SET RELATION TO "C7_FORNECE","C7_LOJA" WITH "A2_COD","A2_LOJA" LABEL STR0002	//-- Código do Fornecedor
QSPARENTFIELD "A2_NOME" INDEX ORDER 2 SET RELATION TO "C7_FORNECE","C7_LOJA" WITH "A2_COD","A2_LOJA" LABEL STR0003	//-- Nome do Fornecedor
QSPARENTFIELD "A2_CGC" INDEX ORDER 3 SET RELATION TO "C7_FORNECE","C7_LOJA" WITH "A2_COD","A2_LOJA" LABEL STR0004	//-- CNPJ/CPF do Fornecedor

//-- Opcoes de filtro
QSFILTER STR0005 WHERE "C7_TIPO = 2 AND C7_QUJE < C7_QUANT AND C7_RESIDUO <> 'S' AND C7_EMISSAO >= '" +DToS(Date() - 30) +"'"	//-- Últimos 30 dias
QSFILTER STR0006 WHERE "C7_TIPO = 2 AND C7_QUJE < C7_QUANT AND C7_RESIDUO <> 'S' AND C7_EMISSAO >= '" +DToS(Date() - 60) +"'"	//-- Últimos 60 dias
QSFILTER STR0007 WHERE "C7_TIPO = 2 AND C7_QUJE < C7_QUANT AND C7_RESIDUO <> 'S' AND C7_EMISSAO >= '" +DToS(Date() - 90) +"'"	//-- Últimos 90 dias
QSFILTER STR0008 WHERE "C7_TIPO = 2 AND C7_QUJE < C7_QUANT AND C7_RESIDUO <> 'S' AND C7_EMISSAO >= '" +DToS(Date() - 120) +"'"	//-- Últimos 120 dias
QSFILTER STR0009 WHERE "C7_TIPO = 2 AND C7_QUJE < C7_QUANT AND C7_RESIDUO <> 'S' AND C7_EMISSAO >= '" +DToS(Date() - 360) +"'"	//-- Últimos 360 dias
QSFILTER STR0010 WHERE "C7_TIPO = 2 AND C7_QUJE < C7_QUANT AND C7_RESIDUO <> 'S'"	//-- Todos

//-- Campos da consulta rapida
QSFIELD "C7_FILIAL" LABEL STR0011	//-- Empresa
QSFIELD "C7_NUM" LABEL STR0012		//-- Número da Autorização
QSFIELD "C7_FORNECE" LABEL STR0002	//-- Código do Fornecedor
QSFIELD "C7_LOJA" LABEL STR0014		//-- Loja do Fornecedor
QSFIELD "A2_NOME" LABEL STR0003		//-- Nome do Fornecedor
QSFIELD "A2_CGC" LABEL STR0004		//-- CNPJ/CPF do Fornecedor
QSFIELD "MOEDA" BLOCK {|| SuperGetMV("MV_MOEDA"+AllTrim(Str(C7_MOEDA)),.F.,"")} FIELDS "C7_MOEDA" LABEL STR0013 TYPE "C" SIZE 15	//-- Moeda
QSFIELD "VLCART" EXPRESSION "SUM((C7_QUANT - C7_QUJE) * C7_PRECO)" LABEL STR0015 FIELDS "C7_QUANT","C7_QUJE","C7_PRECO" GROUP BY TYPE "N" SIZE TamSX3("C7_TOTAL")[1] DECIMAL TamSX3("C7_TOTAL")[2] PICTURE PesqPict("SC7","C7_TOTAL")	//-- Valor em Carteira
QSFIELD "VLCARTMC" BLOCK {|| xMoeda(VLCART,C7_MOEDA,1)} FIELDS "C7_MOEDA" LABEL STR0015+STR0016	TYPE "N" SIZE TamSX3("C7_TOTAL")[1] DECIMAL TamSX3("C7_TOTAL")[2] PICTURE PesqPict("SC7","C7_TOTAL")	//-- Valor em Carteira (Moeda Corrente)
QSFIELD "C7_EMISSAO" LABEL STR0017	//-- Data de Emissão

//-- Acoes relacionadas
QSACTION MENUDEF "MATA122" OPERATION 2 LABEL STR0018	//-- Detalhes da Autorização
QSACTION MENUDEF "MATA020" OPERATION 2 LABEL STR0019	//-- Detalhes do Fornecedor

Return

QSSTRUCT MATQ12202 DESCRIPTION STR0020 MODULE 2	//-- Autorizações de entrega em aberto por produtos

QSMETHOD INIT QSSTRUCT MATQ12202

//-- Tabelas envolvidas na consulta e seus relacionamentos
QSTABLE "SC7" JOIN "SA2" ON "A2_COD = C7_FORNECE AND A2_LOJA = C7_LOJA"
QSTABLE "SC7" JOIN "SB1" ON "B1_COD = C7_PRODUTO"
QSTABLE "SC7" LEFT JOIN "SB5" ON "B5_COD = C7_PRODUTO"
QSTABLE "SC7" LEFT JOIN "SC3" ON "C3_NUM= C7_NUMSC AND C3_ITEM = C7_ITEMSC"

//-- Campos/índices utilizados para a pesquisa
QSPARENTFIELD "C7_PRODUTO" INDEX ORDER 2 LABEL STR0021	//-- Código do Produto
QSPARENTFIELD "C7_NUM" INDEX ORDER 1 LABEL STR0012		//-- Número da Autorização
QSPARENTFIELD "B1_DESC" INDEX ORDER 3 SET RELATION TO "C7_PRODUTO" WITH "B1_COD" LABEL STR0022	//-- Descrição do Produto
QSPARENTFIELD "C3_NUM" INDEX ORDER 1 SET RELATION TO "C7_NUMSC","C7_ITEMSC" WITH "C3_NUM","C3_ITEM" LABEL STR0023	//-- Número do Contrato
QSPARENTFIELD "B5_CEME" INDEX ORDER 7 SET RELATION TO "C7_PRODUTO" WITH "B5_COD" LABEL STR0024	//-- Descrição Complementar do Produto

//-- Opcoes de filtro
QSFILTER STR0005 WHERE "C7_TIPO = 2 AND C7_QUJE < C7_QUANT AND C7_RESIDUO <> 'S' AND C7_EMISSAO >= '" +DToS(Date() - 30) +"'"	//-- Últimos 30 dias
QSFILTER STR0006 WHERE "C7_TIPO = 2 AND C7_QUJE < C7_QUANT AND C7_RESIDUO <> 'S' AND C7_EMISSAO >= '" +DToS(Date() - 60) +"'"	//-- Últimos 60 dias
QSFILTER STR0007 WHERE "C7_TIPO = 2 AND C7_QUJE < C7_QUANT AND C7_RESIDUO <> 'S' AND C7_EMISSAO >= '" +DToS(Date() - 90) +"'"	//-- Últimos 90 dias
QSFILTER STR0008 WHERE "C7_TIPO = 2 AND C7_QUJE < C7_QUANT AND C7_RESIDUO <> 'S' AND C7_EMISSAO >= '" +DToS(Date() - 120) +"'"	//-- Últimos 120 dias
QSFILTER STR0009 WHERE "C7_TIPO = 2 AND C7_QUJE < C7_QUANT AND C7_RESIDUO <> 'S' AND C7_EMISSAO >= '" +DToS(Date() - 360) +"'"	//-- Últimos 360 dias
QSFILTER STR0010 WHERE "C7_TIPO = 2 AND C7_QUJE < C7_QUANT AND C7_RESIDUO <> 'S'"	//-- Todos

//-- Campos da consulta rapida
QSFIELD "C7_FILIAL" LABEL STR0011	//-- Empresa
QSFIELD "C7_NUM" LABEL STR0012		//-- Número da Autorização
QSFIELD "A2_NOME" LABEL STR0003		//-- Nome do Fornecedor
QSFIELD "A2_CGC" LABEL STR0004		//-- CNPJ/CPF
QSFIELD "C7_PRODUTO" LABEL STR0021	//-- Código do Produto
QSFIELD "B1_DESC" LABEL STR0022		//-- Descrição do Produto
QSFIELD "SALDO" EXPRESSION "C7_QUANT - C7_QUJE" LABEL STR0025 FIELDS "C7_QUANT","C7_QUJE" TYPE "N" SIZE TamSX3("C7_QUANT")[1] DECIMAL TamSX3("C7_QUANT")[2] PICTURE PesqPict("SC7","C7_QUANT")	//-- Quantidade a Receber
QSFIELD "C7_EMISSAO" LABEL STR0026	//-- Data de Emissão

//-- Acoes relacionadas
QSACTION MENUDEF "MATA120" OPERATION 2 LABEL STR0018	//-- Detalhes da Autorização
QSACTION MENUDEF "MATA010" OPERATION 2 LABEL STR0027	//-- Detalhes do Produto
QSACTION MENUDEF "MATA020" OPERATION 2 LABEL STR0019	//-- Detalhes do Fornecedor

Return
