#include 'totvs.ch'
#include 'tlpp-core.th'
#include 'tlpp-rest.th'
#define PATH_URL '/api/agd/v2/negociacoes/rateios-entregas'
#define PATH_URL_ID '/api/agd/v2/negociacoes/:idNegocio/:idInsumo/rateios-entregas'

namespace totvs.protheus.agrobusiness.agd



/*/{Protheus.doc} BusinessApportionmentController
API Rest de Rateio de Entrega da Negociação
@type class
@version 12
@author jc.maldonado
@since 26/05/2025
/*/
class BusinessApportionmentController
	public data nPage     as integer
	public data nPageSize as integer

	public method new()

	@Get(PATH_URL)
	public method listar() as logical

	@Post(PATH_URL_ID)
	public method registrar() as logical

	@Put(PATH_URL_ID)
	public method atualizar() as logical

	@Delete(PATH_URL_ID)
	public method deletar() as logical
endClass

/*/{Protheus.doc} BusinessApportionmentController::new
Construtor
@type method
@version 12
@author jc.maldonado
@since 26/05/2025
@return object, self
/*/
method new() class BusinessApportionmentController
return self

/*/{Protheus.doc} BusinessApportionmentController::listar
Lista Rateio Entrega Negociação
@type method
@version 12
@author jc.maldonado
@since 26/05/2025
@return logical, always true
/*/
method listar() as logical class BusinessApportionmentController
	local oRateioNegociacaoService as object
	local oRestService            as object
	local jQueryParam              as json

	oRestService := RestService():New()
	oRateioNegociacaoService := BusinessApportionmentService():New()

	oRestService:getPageAndPageSize(@::nPage, @::nPageSize)
	jQueryParam := oRestService:getQueryParams()

	oRateioNegociacaoService:listar(::nPage, ::nPageSize, jQueryParam)

	oRestService:setAPIResponse(oRest, oRateioNegociacaoService)

	FWFreeObj(oRateioNegociacaoService)
	FWFreeObj(oRestService)
return .T.

/*/{Protheus.doc} BusinessApportionmentController::registrar
Registra Rateio Entrega Negociação
@type method
@version 12
@author jc.maldonado
@since 26/05/2025
@return logical, always true
/*/
method registrar() as logical class BusinessApportionmentController
	local oRateioNegociacaoService as object
	local oRestService            as object
    Local jPathParams              As Json
    Local cIdNegocio               As Character
    Local cIdInsumo                As Character
    Local oJPayload                As Object

	oRestService := RestService():New()

	oRateioNegociacaoService := BusinessApportionmentService():New()
 	
	// Path params
    jPathParams  := oRest:getPathParamsRequest()
    cIdNegocio   := jPathParams["idNegocio"]
    cIdInsumo    := jPathParams["idInsumo"]

	oJPayload := oRateioNegociacaoService:convertEntregasPayload(oRestService:getRequestBody(),cIdNegocio, cIdInsumo)
	
	oRateioNegociacaoService:registrar(oJPayload)

	oRestService:setAPIResponse(oRest, oRateioNegociacaoService)

	FreeObj(oRateioNegociacaoService)
	FreeObj(oRestService)
return .t.

/*/{Protheus.doc} BusinessApportionmentController::atualizar
Atualiza a quantidade do Rateio
@type method
@version P12
@author scheronlini.martins
@since 02/07/2025
@return logical, true
/*/
method atualizar() as logical class BusinessApportionmentController
	local oRateioNegociacaoService as object
	local oRestService            as object
    Local jPathParams              As Json
    Local cIdNegocio               As Character
    Local cIdInsumo                As Character
    Local oJPayload                As Object

	oRestService := RestService():New()

	oRateioNegociacaoService := BusinessApportionmentService():New()

    // Path params
    jPathParams  := oRest:getPathParamsRequest()
    cIdNegocio   := jPathParams["idNegocio"]
    cIdInsumo    := jPathParams["idInsumo"]


	oJPayload := oRateioNegociacaoService:convertEntregasPayload(oRestService:getRequestBody(),cIdNegocio ,cIdInsumo)

	oRateioNegociacaoService:updateRateioEntregas(oJPayload)

	oRestService:setAPIResponse(oRest, oRateioNegociacaoService)

	FreeObj(oRateioNegociacaoService)
	FreeObj(oRestService)
return .t.

/*/{Protheus.doc} BusinessApportionmentController::deletar
Deleta o Rateio
@type method
@version P12
@author scheronlini.martins
@since 02/07/2025
@return logical, true
/*/
method deletar() as logical class BusinessApportionmentController
	Local oRateioNegociacaoService As Object
    Local oRestService            As Object
    Local jPathParams              As Json
    Local cIdNegocio               As Character
    Local cIdInsumo                As Character
    Local oJPayload                As Object

    oRestService := RestService():New()
    oRateioNegociacaoService := BusinessApportionmentService():New()

    // Path params
    jPathParams  := oRest:getPathParamsRequest()
    cIdNegocio   := jPathParams["idNegocio"]
    cIdInsumo    := jPathParams["idInsumo"]

	oJPayload := oRateioNegociacaoService:convertEntregasPayload(,cIdNegocio ,cIdInsumo)

    // Chamada do service já com payload correto
    oRateioNegociacaoService:deleteRateioEntregas(oJPayload)

    oRestService:setAPIResponse(oRest, oRateioNegociacaoService)

    FreeObj(oRateioNegociacaoService)
    FreeObj(oRestService)

RETURN .T.
