#include "msobject.ch"
#include "TOTVS.ch"
#include "totvs.framework.treports.integratedprovider.th"

/*/{PROTHEUS.DOC} sigaloc.sv.loc.gestaodevolucao.tlpp
ITUP BUSINESS - TOTVS RENTAL
Relatório de Gestão de Devolução
@AUTHOR LEONARDO PACHECO FUGA
@SINCE 02/12/2025
/*/

namespace totvs.protheus.rental.manutencao.integratedprovider

@totvsFrameworkTReportsIntegratedProvider(active=.T., team="SIGALOC", tables="FQW,FQX,SB1,ST9", name="Rental", country="ALL", initialRelease="12.1.2210")
class gestaodevolucao from totvs.framework.treports.integratedprovider.integratedprovider

public method new() as object
public method getData() as object
public method getSchema() as object 
public method PrintDevolucao() as logical

endclass

/*/{PROTHEUS.DOC} gestaodevolucao
ITUP BUSINESS - TOTVS RENTAL
Declaração dos métodos
@AUTHOR LEONARDO PACHECO FUGA
@SINCE 02/12/2025
/*/

method new() class gestaodevolucao
	_Super:new()

	self:appendArea("Rental")

	self:setDisplayName("Gestao de Devolucao")

	self:setDescription("Gestao de Devolucao")
return self

/*/{PROTHEUS.DOC} getData
ITUP BUSINESS - TOTVS RENTAL
Processamento do relatório
@AUTHOR LEONARDO PACHECO FUGA
@SINCE 02/12/2025
/*/

method getData(nPage as numeric, oFilter as object) as object class gestaodevolucao
Local cQuery as character
Local aBind       := {}

	self:setPageSize(20)

	jParams := oFilter:getParameters() //metodo para retorno do json dos parâmetros

	If type("jParams['01'][1]") <> "C" .or. file("\SYSTEM\LOCSV025.TXT")
		jParams['01'][1] := space(TamSx3("FQW_NUM")[1])
	EndIf
	If empty(jParams['01'][1])
		jParams['01'][1] := space(TamSx3("FQW_NUM")[1])
	EndIf

	cQuery := " SELECT "
	cQuery += " FQW.FQW_NUM, FQW.FQW_PROJET, FQW.FQW_OBRA, FQW.FQW_CLIENT, FQW.FQW_LOJA, FQW.FQW_NOMCLI, FQW.FQW_ENDDEV, FQW.FQW_MUNDEV, FQW.FQW_CEPDEV, "
	cQuery += " FQX.FQX_ITEM, FQX.FQX_PROD, SB1.B1_DESC, SB1.B1_LOCPAD, SB1.B1_UM, FQW.FQW_CLIDEV, FQW.FQW_LOJDEV, FQW.FQW_NOMDEV, FQW.FQW_BAIDEV, FQW.FQW_ESTDEV, "
	cQuery += " COALESCE(ST9.T9_CODBEM, 'SEM BEM') T9_CODBEM, "
	cQuery += " COALESCE(ST9.T9_NOME, 'SEM BEM') T9_NOME, "
	cQuery += " FQX.FQX_UNID, FQX.FQX_QTD "
	cQuery += " FROM "+RetSqlName("FQW")+" FQW "
	cQuery += " INNER JOIN "+RetSqlName("FQX")+" FQX ON "
	cQuery += " FQX.FQX_FILIAL = '"+xFilial("FQX")+"' AND "
	cQuery += " FQX.FQX_NUM = FQW.FQW_NUM AND "
	cQuery += " FQX.D_E_L_E_T_ = ' ' "
	cQuery += " LEFT JOIN "+RetSqlName("SB1")+" SB1 ON "
	cQuery += " SB1.B1_FILIAL = '"+xFilial("SB1")+"' AND "
	cQuery += " SB1.B1_COD = FQX.FQX_PROD AND "
	cQuery += " SB1.D_E_L_E_T_ = ' ' "
	cQuery += " LEFT JOIN "+RetSqlName("ST9")+" ST9 ON "
	cQuery += " ST9.T9_FILIAL = '"+xFilial("ST9")+"' AND "
	cQuery += " ST9.T9_CODBEM = FQX.FQX_CODBEM AND "
	cQuery += " ST9.D_E_L_E_T_ = ' ' "
	cQuery += " WHERE FQW.FQW_FILIAL = '"+xFilial("FQW")+"' AND "
	cQuery += " FQW.FQW_NUM = ? AND "
	AAdd(aBind, {jParams['01'][1], "S"})
	cQuery += " FQW.D_E_L_E_T_ = ' ' "

	cQuery := CHANGEQUERY(cQuery)
	cQuery := JurTRepBin(cQuery, aBind)
	self:setOrder("FQX.FQX_ITEM")
	self:setQuery(cQuery)

return self:oData

/*/{PROTHEUS.DOC} getSchema()
ITUP BUSINESS - TOTVS RENTAL
Declaração dos parâmetros
@AUTHOR LEONARDO PACHECO FUGA
@SINCE 02/12/2025
/*/

method getSchema() as object class gestaodevolucao

	self:addProperty("Projeto",         "Projeto",               "string", "Projeto",               "FQW_PROJET")
	self:addProperty("Obra",            "Obra",                  "string", "Obra",                  "FQW_OBRA")
	self:addProperty("Romaneio",        "Romaneio",              "string", "Romaneio",              "FQW_NUM")
	self:addProperty("Item",            "Item",                  "string", "Item",                  "FQX_ITEM")
	self:addProperty("ClienteProj",     "Cliente Proj",          "string", "Cliente Proj",          "FQW_CLIENT")
	self:addProperty("LojaCliente",     "Loja Cliente",          "string", "Loja Cliente",          "FQW_LOJA")
	self:addProperty("NomeCliente",     "Nome Cliente",          "string", "Nome Cliente",          "FQW_NOMCLI")
	self:addProperty("ClienteDest",     "Cliente Dest",          "string", "Cliente Dest",          "FQW_CLIDEV")
	self:addProperty("LojaDestino",     "Loja Destino",          "string", "Loja Destino",          "FQW_LOJDEV")
	self:addProperty("NomeDestino",     "Nome Destino",          "string", "Nome Destino",          "FQW_NOMDEV")
	self:addProperty("Endereço",        "Endereço",              "string", "Endereço",              "FQW_ENDDEV")
	self:addProperty("Bairro",          "Bairro",                "string", "Bairro",                "FQW_BAIDEV")
	self:addProperty("Municipio",       "Municipio",             "string", "Municipio",             "FQW_MUNDEV")
	self:addProperty("UFDestino",       "UF Destino",            "string", "UF Destino",            "FQW_ESTDEV")
	self:addProperty("CEPDestino",      "CEP Destino",           "string", "CEP Destino",           "FQW_CEPDEV")
	self:addProperty("Produto",         "Produto",               "string", "Produto",               "FQX_PROD")
	self:addProperty("DescProdut",      "Desc. Produt",          "string", "Desc. Produt",          "B1_DESC")
	self:addProperty("Armazem",         "Armazem",               "string", "Armazem",               "B1_LOCPAD")
	self:addProperty("Equipamento",     "Equipamento",           "string", "Equipamento",           "T9_CODBEM")
	self:addProperty("NomeEquipamento", "Nome Equip.",           "string", "Nome Equip.",           "T9_NOME")
	self:addProperty("UnidadeMedida",   "Unidade de medida",     "string", "Unidade de medida",     "B1_UM")
	self:addProperty("Quantidade",      "Quantidade",            "number", "Quantidade",            "FQX_QTD")

	self:addParameter("01", "Romaneio", "string", .F., "", .F., .F., "", "MV_PAR01")

return self:oSchema


/*/{Protheus.doc} printReceipt
Gera a impressão do Romaneio Posicionado 
@author Leonardo Pacheco Fuga
@since 02/12/2025
@version 25.10
*/
method printDevolucao(cRomaneio as character) as logical class gestaodevolucao
Local lSuccess := .F. as logical
Local jPrintInfo as json
Local cSmartViewId := "sigaloc.sv.loc.gestaodevolucao.default.rep"
Local aReportType := {"report", "data-grid", "pivot-table"} as array
Local cDefaultPath := GetTempPath() as character
Local oSmartView As Object
Local cMsg := "" As Character
  
    jPrintInfo := JsonObject():New() 
    jPrintInfo['name'] := "Romaneio_" + FwTimeStamp()
    jPrintInfo['extension'] := "pdf"
    jPrintInfo['path'] := cDefaultPath
    
    oSmartView := totvs.framework.smartview.callSmartView():new(cSmartViewId,aReportType[1])
	oSmartView:setOpenFile(.T.)
    oSmartView:setNoInterface(.F.)
    oSmartView:setParam("01", cRomaneio, "Disabled")
    oSmartView:setForceParams(.T.)
    oSmartView:setPrintInfo(jPrintInfo)
    lSuccess := oSmartView:executeSmartView(.T.)

    If !lSuccess .or. file("\SYSTEM\LOCSV026.TXT")
        cMsg := oSmartView:getError()
    EndIf

    oSmartView:Destroy()

    If oSmartView != Nil   
        FreeObj(oSmartView)
    EndIf

return lSuccess

