#include 'tlpp-core.th'
#include 'totvs.ch'

namespace totvs.protheus.agrobusiness.agd

/*/{Protheus.doc} EngineersRepository
Repositório de Engenheiros - Tabela NP8
@type class
@version 12
@author jc.maldonado
@since 13/05/2026
/*/
class EngineersRepository from UtilsRepository
	public data cChaveIDRepository as character

	public method new()

	private method getFields() as array

	static method getEngineerIfOnlyOne() as character
endclass

/*/{Protheus.doc} EngineersRepository::new
Construtor
@type method
@version 12
@author jc.maldonado
@since 13/05/2026
@param cChaveIDRepository, character, 
@return object, Instância da classe
/*/
method new(cChaveIDRepository as character) class EngineersRepository
	::cChaveIDRepository := cChaveIDRepository

	_Super:New('NP8', ::getFields())
return Self

/*/{Protheus.doc} EngineersRepository::getFields
Obtem os campos do repositório
@type method
@version 12
@author jc.maldonado
@since 13/05/2026
@return array, {{cCampoJson, cCampoProtheus, cTipoCampo, lMostraCampoConsulta}, ...}
/*/
method getFields() as array class EngineersRepository
	local aFields as array

	aFields := {;
		{'filial'         , 'NP8_FILIAL', 'C', .F.},;
		{'codigo'         , 'NP8_CODIGO', 'C', .T.},;
		{'nome'           , 'NP8_NOME'  , 'C', .T.},;
		{'crea'           , 'NP8_CREA'  , 'C', .T.},;
		{'cpf'            , 'NP8_CPF'   , 'C', .T.},;
		{'renasem'        , 'NP8_RENASE', 'C', .T.},;
		{'telefone'       , 'NP8_NUMTEL', 'C', .T.},;
		{'endereco'       , 'NP8_ENDER' , 'C', .T.},;
		{'estado'         , 'NP8_EST'   , 'C', .T.},;
		{'codigoMunicipio', 'NP8_CODMUN', 'C', .T.},;
		{'cep'            , 'NP8_CEP'   , 'C', .T.},;
		{'email'          , 'NP8_EMAIL' , 'C', .T.};
		}
return aFields

/*/{Protheus.doc} EngineersRepository::getEngineerIfOnlyOne
Retorna o código do engenheiro se houver apenas um cadastro na tabela NP8
@type method
@version 12
@author jc.maldonado
@since 13/05/2026
@return character, Código do engenheiro
/*/
method getEngineerIfOnlyOne() as character class EngineersRepository
	Local cQuery         as character
	Local aBindQry := {} as array

	cQuery := "SELECT"
	cQuery += " 	CASE"
	cQuery += " 		WHEN COUNT(*) = 1 THEN MAX(NP8_CODIGO)"
	cQuery += " 		ELSE ''"
	cQuery += " 	END AS NP8_CODIGO"
	cQuery += " FROM "
	cQuery +=       RetSQLName("NP8")
	cQuery += " WHERE"
	cQuery += " 	NP8_FILIAL = ?" ; aAdd(aBindQry, FwXFilial("NP8"))
	cQuery += " 	AND D_E_L_E_T_ = ' '"

	cQuery := ChangeQuery(cQuery)
Return MPSysExecScalar(cQuery, 'NP8_CODIGO', aBindQry)
