#include "TOTVS.CH"

Class PLSMprBi3 from CenMapper

    Method New() Constructor

EndClass

Method New() Class PLSMprBi3
    _Super:new()

    aAdd(self:aFields,{"BI3_ALLRED" ,"allRda"})
    aAdd(self:aFields,{"BI3_ALLCRE" ,"allAccredited"})
    aAdd(self:aFields,{"BI3_ALLUSR" ,"allUsers"})
    aAdd(self:aFields,{"BI3_VERSAO" ,"version"})
    aAdd(self:aFields,{"BI3_CODINT" ,"operator"})
    aAdd(self:aFields,{"BI3_CODIGO" ,"productCode"})
    aAdd(self:aFields,{"BI3_DESCRI" ,"productDescription"})
    aAdd(self:aFields,{"BI3_NREDUZ" ,"summarDescript"})
    aAdd(self:aFields,{"BI3_GRUPO" ,"productGroup"})
    aAdd(self:aFields,{"BI3_TIPPLA" ,"planOwner"})
    aAdd(self:aFields,{"BI3_TIPO" ,"planType"})
    aAdd(self:aFields,{"BI3_DATINC" ,"inclusionDate"})
    aAdd(self:aFields,{"BI3_CODANT" ,"oldCode"})
    aAdd(self:aFields,{"BI3_STATUS" ,"planStatus"})
    aAdd(self:aFields,{"BI3_DATBLO" ,"blockDate"})
    aAdd(self:aFields,{"BI3_DESCAR" ,"cardDescription"})
    aAdd(self:aFields,{"BI3_TAXDIA" ,"dailyInterest"})
    aAdd(self:aFields,{"BI3_COBJUR" ,"chargeInterestSameMont"})
    aAdd(self:aFields,{"BI3_JURDIA" ,"dailyInterestValue"})
    aAdd(self:aFields,{"BI3_NATURE" ,"class"})
    aAdd(self:aFields,{"BI3_TIPTIT" ,"billType"})
    aAdd(self:aFields,{"BI3_COBRAT" ,"calcProRataCollection"})
    aAdd(self:aFields,{"BI3_RATMAI" ,"pRataExitFMajority"})
    aAdd(self:aFields,{"BI3_TODOS" ,"considerProcStandard"})
    aAdd(self:aFields,{"BI3_RATSAI" ,"chargeProRataOnOutflo"})
    aAdd(self:aFields,{"BI3_SUSEP" ,"ansRegistrationNumber"})
    aAdd(self:aFields,{"BI3_CODSEG" ,"segment"})
    aAdd(self:aFields,{"BI3_MODPAG" ,"paymentMode"})
    aAdd(self:aFields,{"BI3_APOSRG" ,"ruled"})
    aAdd(self:aFields,{"BI3_CODACO" ,"accommodationCode"})
    aAdd(self:aFields,{"BI3_CPFM" ,"coParticipation"})
    aAdd(self:aFields,{"BI3_ABRANG" ,"scope"})
    aAdd(self:aFields,{"BI3_DTRGPR" ,"productRegistrDate"})
    aAdd(self:aFields,{"BI3_DTAPPR" ,"productApprovDate"})
    aAdd(self:aFields,{"BI3_ALLOPE" ,"allOperators"})
    aAdd(self:aFields,{"BI3_TIPCON" ,"contractType"})
    aAdd(self:aFields,{"BI3_MUDFAI" ,"changeRange"})
    aAdd(self:aFields,{"BI3_ANOMES" ,"yearMonth"})
    aAdd(self:aFields,{"BI3_INFCOB" ,"informCoverage"})
    aAdd(self:aFields,{"BI3_INFGCB" ,"informCoverageGroup"})
    aAdd(self:aFields,{"BI3_INFCBU" ,"enterSpCovUser"})
    aAdd(self:aFields,{"BI3_LIMTXA" ,"adTxLimValue"})
    aAdd(self:aFields,{"BI3_PADSAU" ,"comfortStandard"})
    aAdd(self:aFields,{"BI3_MODCON" ,"contractModel"})
    aAdd(self:aFields,{"BI3_VL2BOL" ,"valueOfDupliOfDocket"})
    aAdd(self:aFields,{"BI3_CODPTU" ,"ediCode"})
    aAdd(self:aFields,{"BI3_CONTA" ,"ledgerAccount"})
    aAdd(self:aFields,{"BI3_CC" ,"costCenter"})
    aAdd(self:aFields,{"BI3_NATJCO" ,"contractLegalClass"})
    aAdd(self:aFields,{"BI3_IDECAR" ,"identCrMagneticStrip"})
    aAdd(self:aFields,{"BI3_HSPPLA" ,"hspPlanCode"})
    aAdd(self:aFields,{"BI3_FATMUL" ,"accommodationMultFactor"})
    aAdd(self:aFields,{"BI3_RISCO" ,"highRiskProduct"})
    aAdd(self:aFields,{"BI3_GRUCOM" ,"commissionGroup"})
    aAdd(self:aFields,{"BI3_DESMEN" ,"monthlyFeeDiscount"})
    aAdd(self:aFields,{"BI3_COBCPF" ,"individualCollectMode"})
    aAdd(self:aFields,{"BI3_FORFAT" ,"billingMethod"})
    aAdd(self:aFields,{"BI3_REEMB" ,"allowRefund"})
    aAdd(self:aFields,{"BI3_CODSB1" ,"erpProductCode"})
    aAdd(self:aFields,{"BI3_CODTES" ,"invoiceOutflowType"})
    aAdd(self:aFields,{"BI3_SCPA" ,"scpaCode"})
    aAdd(self:aFields,{"BI3_PORTAL" ,"showInPortal"})
    aAdd(self:aFields,{"BI3_QTDUS" ,"numberOfUs"})
    aAdd(self:aFields,{"BI3_REDEDI" ,"ediServiceNetwork"})
    aAdd(self:aFields,{"BI3_QTDPUS" ,"period"})
    aAdd(self:aFields,{"BI3_UNIPUS" ,"unit"})
    aAdd(self:aFields,{"BI3_CONRPC" ,"considerSendingToRpc"})
    aAdd(self:aFields,{"BI3_TPCONT" ,"contractYearType"})
    aAdd(self:aFields,{"BI3_TPBEN" ,"beneficiaryType"})
    aAdd(self:aFields,{"BI3_ABRCAR" ,"scopeInCard"})
    aAdd(self:aFields,{"BI3_SITANS" ,"situationAtAns"})
    aAdd(self:aFields,{"BI3_CLAPLS" ,"planClassification"})
    aAdd(self:aFields,{"BI3_REDREF" ,"referencedNetwork"})
    aAdd(self:aFields,{"BI3_GUIMED" ,"medicalForm"})
    aAdd(self:aFields,{"BI3_TPFORN" ,"supplierType"})
    aAdd(self:aFields,{"BI3_INFANS" ,"considerAns"})
    aAdd(self:aFields,{"BI3_TPREDI" ,"typeOfProductForEdi"})
    aAdd(self:aFields,{"BI3_MXDRMB" ,"noDaysTolerance"})
    aAdd(self:aFields,{"BI3_VMIRMB" ,"minValuReimbAccum"})
    aAdd(self:aFields,{"BI3_TABCOP" ,"coParticipationTablePo"})
    aAdd(self:aFields,{"BI3_RRFDES" ,"descReferencedNetwork"})
    aAdd(self:aFields,{"BI3_LATEDI" ,"eduServiceLocationCode"})
    aAdd(self:aFields,{"BI3_CLASSE" ,"productClassification"})
    aAdd(self:aFields,{"BI3_MOTDOC" ,"documentReason"})
    aAdd(self:aFields,{"BI3_DROGAR" ,"userDrugstoreTempl"})
    aAdd(self:aFields,{"BI3_TIPRED" ,"netTypeA1300"})
    aAdd(self:aFields,{"BI3_EMPIND" ,"individualEntrepreneur"})


Return self
