#include "protheus.ch"
#include "quicksearch.ch"
#include "tmsq25004.ch"

QSSTRUCT TMSQ25004 DESCRIPTION STR0001 MODULE 43 //CONTRATOS QUITADOS
 
QSMETHOD INIT QSSTRUCT TMSQ25004 

Local dData := Date()	
QSTABLE "DTY" LEFT JOIN "SA2" ON "DTY_CODFOR = A2_COD AND DTY_LOJFOR = A2_LOJA"// baseado no SX9	
	
// campos do SX3 e indices do SIX
QSPARENTFIELD "DTY_NUMCTC"					INDEX ORDER 1	//Número do contrato
QSPARENTFIELD "DTY_FILORI","DTY_VIAGEM"	INDEX ORDER 2	//Filial de origem+Viagem
QSPARENTFIELD "DTY_CODFOR","DTY_LOJFOR"	INDEX ORDER 3	//Fornecedor+Loja
QSPARENTFIELD "DTY_FILORI","DTY_NUMCTC"	INDEX ORDER 4 //Filial de origem+Número do contrato

// campos do SX3
QSFIELD "DTY_FILORI" 	LABEL STR0002 //"Filial Origem"
QSFIELD "DTY_NUMCTC" 	LABEL STR0003 //"Contrato"
QSFIELD "DTY_DATCTC"	LABEL STR0004 //"Data"
QSFIELD "A2_NOME"		LABEL STR0005 //"Nome"
		
QSACTION MENUDEF "TMSA250"			OPERATION 2 LABEL STR0007	   //" Visualizar"
	
QSFILTER STR0008 WHERE "DTY_STATUS IN(4,5) AND DTY.DTY_DATCTC = '"+DTOS(dData)		+"'" //"Ultimo dia" 
QSFILTER STR0009 WHERE "DTY_STATUS IN(4,5) AND DTY.DTY_DATCTC > '"+DTOS(dData-7)  	+"'" //"Ultimos 7 dias"
QSFILTER STR0010 WHERE "DTY_STATUS IN(4,5) AND DTY.DTY_DATCTC > '"+DTOS(dData-30)	+"'" //"Ultimos 30 dias"
QSFILTER STR0011 WHERE "DTY_STATUS IN(4,5) AND DTY.DTY_DATCTC > '"+DTOS(dData-365)	+"'	" //"Ultimos 365 dias"
		
Return