#INCLUDE "PROTHEUS.CH" 
#INCLUDE "APWEBSRV.CH" 

/* ===============================================================================
WSDL Location    http://localhost:8080/MANIFESTACAODESTINATARIO.apw?WSDL
Gerado em        06/05/12 15:10:09
Observações      Código-Fonte gerado por ADVPL WSDL Client 1.111215
                 Alterações neste arquivo podem causar funcionamento incorreto
                 e serão perdidas caso o código-fonte seja gerado novamente.
================================================================================ */

User Function _JJTTCVJ ; Return  // "dummy" function - Internal Use 

/* -------------------------------------------------------------------------------
WSDL Service WSMANIFESTACAODESTINATARIO
------------------------------------------------------------------------------- */

WSCLIENT WSMANIFESTACAODESTINATARIO

	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD RESET
	WSMETHOD CLONE
	WSMETHOD BAIXARXMLDOCUMENTOS
	WSMETHOD CONFIGURARPARAMETROS
	WSMETHOD MONITORARDOCUMENTOS
	WSMETHOD PESQUISARDOCUMENTOS
	WSMETHOD RETORNARDOCUMENTO
	WSMETHOD SINCRONIZARDOCUMENTOS

	WSDATA   _URL                      AS String
	WSDATA   _HEADOUT                  AS Array of String
	WSDATA   _COOKIES                  AS Array of String
	WSDATA   cUSERTOKEN                AS string
	WSDATA   cIDENT                    AS string
	WSDATA   cAMBIENTE                 AS string
	WSDATA   oWSDOCUMENTOS             AS MANIFESTACAODESTINATARIO_BAIXARDOCUMENTOS
	WSDATA   oWSBAIXARXMLDOCUMENTOSRESULT AS MANIFESTACAODESTINATARIO_BAIXARDOCUMENTOSRET
	WSDATA   cVERSAO                   AS string
	WSDATA   cULTNSU                   AS string
	WSDATA   oWSCONFIGURARPARAMETROSRESULT AS MANIFESTACAODESTINATARIO_CONFIGURARPARAMETROSRET
	WSDATA   oWSMONDADOS               AS MANIFESTACAODESTINATARIO_MONITORARDOCUMENTOSDADOS
	WSDATA   oWSMONITORARDOCUMENTOSRESULT AS MANIFESTACAODESTINATARIO_MONITORARDOCUMENTOSRET
	WSDATA   oWSPESQUISARDOCUMENTOSRESULT AS MANIFESTACAODESTINATARIO_PESQUISARDOCUMENTOSRET
	WSDATA   cCHAVE                    AS string
	WSDATA   oWSRETORNARDOCUMENTORESULT AS MANIFESTACAODESTINATARIO_RETORNARDOCUMENTORET
	WSDATA   cINDNFE                   AS string
	WSDATA   cINDEMI                   AS string
	WSDATA   oWSSINCRONIZARDOCUMENTOSRESULT AS MANIFESTACAODESTINATARIO_SINCRONIZARDOCUMENTOSRET

	// Estruturas mantidas por compatibilidade - NÃO USAR
	WSDATA   oWSBAIXARDOCUMENTOS       AS MANIFESTACAODESTINATARIO_BAIXARDOCUMENTOS
	WSDATA   oWSMONITORARDOCUMENTOSDADOS AS MANIFESTACAODESTINATARIO_MONITORARDOCUMENTOSDADOS

ENDWSCLIENT

WSMETHOD NEW WSCLIENT WSMANIFESTACAODESTINATARIO
::Init()
If !FindFunction("XMLCHILDEX")
	UserException("O Código-Fonte Client atual requer os executáveis do Protheus Build [7.00.111010P-20120314] ou superior. Atualize o Protheus ou gere o Código-Fonte novamente utilizando o Build atual.")
EndIf
Return Self

WSMETHOD INIT WSCLIENT WSMANIFESTACAODESTINATARIO
	::oWSDOCUMENTOS      := MANIFESTACAODESTINATARIO_BAIXARDOCUMENTOS():New()
	::oWSBAIXARXMLDOCUMENTOSRESULT := MANIFESTACAODESTINATARIO_BAIXARDOCUMENTOSRET():New()
	::oWSCONFIGURARPARAMETROSRESULT := MANIFESTACAODESTINATARIO_CONFIGURARPARAMETROSRET():New()
	::oWSMONDADOS        := MANIFESTACAODESTINATARIO_MONITORARDOCUMENTOSDADOS():New()
	::oWSMONITORARDOCUMENTOSRESULT := MANIFESTACAODESTINATARIO_MONITORARDOCUMENTOSRET():New()
	::oWSPESQUISARDOCUMENTOSRESULT := MANIFESTACAODESTINATARIO_PESQUISARDOCUMENTOSRET():New()
	::oWSRETORNARDOCUMENTORESULT := MANIFESTACAODESTINATARIO_RETORNARDOCUMENTORET():New()
	::oWSSINCRONIZARDOCUMENTOSRESULT := MANIFESTACAODESTINATARIO_SINCRONIZARDOCUMENTOSRET():New()

	// Estruturas mantidas por compatibilidade - NÃO USAR
	::oWSBAIXARDOCUMENTOS := ::oWSDOCUMENTOS
	::oWSMONITORARDOCUMENTOSDADOS := ::oWSMONDADOS
Return

WSMETHOD RESET WSCLIENT WSMANIFESTACAODESTINATARIO
	::cUSERTOKEN         := NIL 
	::cIDENT             := NIL 
	::cAMBIENTE          := NIL 
	::oWSDOCUMENTOS      := NIL 
	::oWSBAIXARXMLDOCUMENTOSRESULT := NIL 
	::cVERSAO            := NIL 
	::cULTNSU            := NIL
	::oWSCONFIGURARPARAMETROSRESULT := NIL 
	::oWSMONDADOS        := NIL 
	::oWSMONITORARDOCUMENTOSRESULT := NIL 
	::oWSPESQUISARDOCUMENTOSRESULT := NIL 
	::cCHAVE             := NIL 
	::oWSRETORNARDOCUMENTORESULT := NIL 
	::cINDNFE            := NIL 
	::cINDEMI            := NIL 
	::oWSSINCRONIZARDOCUMENTOSRESULT := NIL 

	// Estruturas mantidas por compatibilidade - NÃO USAR
	::oWSBAIXARDOCUMENTOS := NIL
	::oWSMONITORARDOCUMENTOSDADOS := NIL
	::Init()
Return

WSMETHOD CLONE WSCLIENT WSMANIFESTACAODESTINATARIO
Local oClone := WSMANIFESTACAODESTINATARIO():New()
	oClone:_URL          := ::_URL 
	oClone:cUSERTOKEN    := ::cUSERTOKEN
	oClone:cIDENT        := ::cIDENT
	oClone:cAMBIENTE     := ::cAMBIENTE
	oClone:oWSDOCUMENTOS :=  IIF(::oWSDOCUMENTOS = NIL , NIL ,::oWSDOCUMENTOS:Clone() )
	oClone:oWSBAIXARXMLDOCUMENTOSRESULT :=  IIF(::oWSBAIXARXMLDOCUMENTOSRESULT = NIL , NIL ,::oWSBAIXARXMLDOCUMENTOSRESULT:Clone() )
	oClone:cVERSAO       := ::cVERSAO
	oClone:cULTNSU       := ::cULTNSU
	oClone:oWSCONFIGURARPARAMETROSRESULT :=  IIF(::oWSCONFIGURARPARAMETROSRESULT = NIL , NIL ,::oWSCONFIGURARPARAMETROSRESULT:Clone() )
	oClone:oWSMONDADOS   :=  IIF(::oWSMONDADOS = NIL , NIL ,::oWSMONDADOS:Clone() )
	oClone:oWSMONITORARDOCUMENTOSRESULT :=  IIF(::oWSMONITORARDOCUMENTOSRESULT = NIL , NIL ,::oWSMONITORARDOCUMENTOSRESULT:Clone() )
	oClone:oWSPESQUISARDOCUMENTOSRESULT :=  IIF(::oWSPESQUISARDOCUMENTOSRESULT = NIL , NIL ,::oWSPESQUISARDOCUMENTOSRESULT:Clone() )
	oClone:cCHAVE        := ::cCHAVE
	oClone:oWSRETORNARDOCUMENTORESULT :=  IIF(::oWSRETORNARDOCUMENTORESULT = NIL , NIL ,::oWSRETORNARDOCUMENTORESULT:Clone() )
	oClone:cINDNFE       := ::cINDNFE
	oClone:cINDEMI       := ::cINDEMI
	oClone:oWSSINCRONIZARDOCUMENTOSRESULT :=  IIF(::oWSSINCRONIZARDOCUMENTOSRESULT = NIL , NIL ,::oWSSINCRONIZARDOCUMENTOSRESULT:Clone() )

	// Estruturas mantidas por compatibilidade - NÃO USAR
	oClone:oWSBAIXARDOCUMENTOS := oClone:oWSDOCUMENTOS
	oClone:oWSMONITORARDOCUMENTOSDADOS := oClone:oWSMONDADOS
Return oClone

// WSDL Method BAIXARXMLDOCUMENTOS of Service WSMANIFESTACAODESTINATARIO

WSMETHOD BAIXARXMLDOCUMENTOS WSSEND cUSERTOKEN,cIDENT,cAMBIENTE,oWSDOCUMENTOS WSRECEIVE oWSBAIXARXMLDOCUMENTOSRESULT WSCLIENT WSMANIFESTACAODESTINATARIO
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<BAIXARXMLDOCUMENTOS xmlns="http://localhost:8080/">'
cSoap += WSSoapValue("USERTOKEN", ::cUSERTOKEN, cUSERTOKEN , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("IDENT", ::cIDENT, cIDENT , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("AMBIENTE", ::cAMBIENTE, cAMBIENTE , "string", .F. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("DOCUMENTOS", ::oWSDOCUMENTOS, oWSDOCUMENTOS , "BAIXARDOCUMENTOS", .T. , .F., 0 , NIL, .F.) 
cSoap += "</BAIXARXMLDOCUMENTOS>"

oXmlRet := SvcSoapCall(	ObjSelf(Self),cSoap,; 
	"http://localhost:8080/BAIXARXMLDOCUMENTOS",; 
	"DOCUMENT","http://localhost:8080/",,"1.031217",; 
	"http://localhost:8080/MANIFESTACAODESTINATARIO.apw")

::Init()
::oWSBAIXARXMLDOCUMENTOSRESULT:SoapRecv( WSAdvValue( oXmlRet,"_BAIXARXMLDOCUMENTOSRESPONSE:_BAIXARXMLDOCUMENTOSRESULT","BAIXARDOCUMENTOSRET",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.

// WSDL Method CONFIGURARPARAMETROS of Service WSMANIFESTACAODESTINATARIO

WSMETHOD CONFIGURARPARAMETROS WSSEND cUSERTOKEN,cIDENT,cAMBIENTE,cVERSAO,cULTNSU WSRECEIVE oWSCONFIGURARPARAMETROSRESULT WSCLIENT WSMANIFESTACAODESTINATARIO
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<CONFIGURARPARAMETROS xmlns="http://localhost:8080/">'
cSoap += WSSoapValue("USERTOKEN", ::cUSERTOKEN, cUSERTOKEN , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("IDENT", ::cIDENT, cIDENT , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("AMBIENTE", ::cAMBIENTE, cAMBIENTE , "string", .F. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("VERSAO", ::cVERSAO, cVERSAO , "string", .F. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("ULTNSU", ::cULTNSU, cULTNSU , "string", .F. , .F., 0 , NIL, .F.) 
cSoap += "</CONFIGURARPARAMETROS>"

oXmlRet := SvcSoapCall(	ObjSelf(Self),cSoap,; 
	"http://localhost:8080/CONFIGURARPARAMETROS",; 
	"DOCUMENT","http://localhost:8080/",,"1.031217",; 
	"http://localhost:8080/MANIFESTACAODESTINATARIO.apw")

::Init()
::oWSCONFIGURARPARAMETROSRESULT:SoapRecv( WSAdvValue( oXmlRet,"_CONFIGURARPARAMETROSRESPONSE:_CONFIGURARPARAMETROSRESULT","CONFIGURARPARAMETROSRET",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.

// WSDL Method MONITORARDOCUMENTOS of Service WSMANIFESTACAODESTINATARIO

WSMETHOD MONITORARDOCUMENTOS WSSEND cUSERTOKEN,cIDENT,cAMBIENTE,oWSMONDADOS WSRECEIVE oWSMONITORARDOCUMENTOSRESULT WSCLIENT WSMANIFESTACAODESTINATARIO
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<MONITORARDOCUMENTOS xmlns="http://localhost:8080/">'
cSoap += WSSoapValue("USERTOKEN", ::cUSERTOKEN, cUSERTOKEN , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("IDENT", ::cIDENT, cIDENT , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("AMBIENTE", ::cAMBIENTE, cAMBIENTE , "string", .F. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("MONDADOS", ::oWSMONDADOS, oWSMONDADOS , "MONITORARDOCUMENTOSDADOS", .T. , .F., 0 , NIL, .F.) 
cSoap += "</MONITORARDOCUMENTOS>"

oXmlRet := SvcSoapCall(	ObjSelf(Self),cSoap,; 
	"http://localhost:8080/MONITORARDOCUMENTOS",; 
	"DOCUMENT","http://localhost:8080/",,"1.031217",; 
	"http://localhost:8080/MANIFESTACAODESTINATARIO.apw")

::Init()
::oWSMONITORARDOCUMENTOSRESULT:SoapRecv( WSAdvValue( oXmlRet,"_MONITORARDOCUMENTOSRESPONSE:_MONITORARDOCUMENTOSRESULT","MONITORARDOCUMENTOSRET",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.

// WSDL Method PESQUISARDOCUMENTOS of Service WSMANIFESTACAODESTINATARIO

WSMETHOD PESQUISARDOCUMENTOS WSSEND cUSERTOKEN,cIDENT,cAMBIENTE WSRECEIVE oWSPESQUISARDOCUMENTOSRESULT WSCLIENT WSMANIFESTACAODESTINATARIO
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<PESQUISARDOCUMENTOS xmlns="http://localhost:8080/">'
cSoap += WSSoapValue("USERTOKEN", ::cUSERTOKEN, cUSERTOKEN , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("IDENT", ::cIDENT, cIDENT , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("AMBIENTE", ::cAMBIENTE, cAMBIENTE , "string", .F. , .F., 0 , NIL, .F.) 
cSoap += "</PESQUISARDOCUMENTOS>"

oXmlRet := SvcSoapCall(	ObjSelf(Self),cSoap,; 
	"http://localhost:8080/PESQUISARDOCUMENTOS",; 
	"DOCUMENT","http://localhost:8080/",,"1.031217",; 
	"http://localhost:8080/MANIFESTACAODESTINATARIO.apw")

::Init()
::oWSPESQUISARDOCUMENTOSRESULT:SoapRecv( WSAdvValue( oXmlRet,"_PESQUISARDOCUMENTOSRESPONSE:_PESQUISARDOCUMENTOSRESULT","PESQUISARDOCUMENTOSRET",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.

// WSDL Method RETORNARDOCUMENTO of Service WSMANIFESTACAODESTINATARIO

WSMETHOD RETORNARDOCUMENTO WSSEND cUSERTOKEN,cIDENT,cAMBIENTE,cCHAVE WSRECEIVE oWSRETORNARDOCUMENTORESULT WSCLIENT WSMANIFESTACAODESTINATARIO
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<RETORNARDOCUMENTO xmlns="http://localhost:8080/">'
cSoap += WSSoapValue("USERTOKEN", ::cUSERTOKEN, cUSERTOKEN , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("IDENT", ::cIDENT, cIDENT , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("AMBIENTE", ::cAMBIENTE, cAMBIENTE , "string", .F. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("CHAVE", ::cCHAVE, cCHAVE , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += "</RETORNARDOCUMENTO>"

oXmlRet := SvcSoapCall(	ObjSelf(Self),cSoap,; 
	"http://localhost:8080/RETORNARDOCUMENTO",; 
	"DOCUMENT","http://localhost:8080/",,"1.031217",; 
	"http://localhost:8080/MANIFESTACAODESTINATARIO.apw")

::Init()
::oWSRETORNARDOCUMENTORESULT:SoapRecv( WSAdvValue( oXmlRet,"_RETORNARDOCUMENTORESPONSE:_RETORNARDOCUMENTORESULT","RETORNARDOCUMENTORET",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.

// WSDL Method SINCRONIZARDOCUMENTOS of Service WSMANIFESTACAODESTINATARIO

WSMETHOD SINCRONIZARDOCUMENTOS WSSEND cUSERTOKEN,cIDENT,cINDNFE,cINDEMI WSRECEIVE oWSSINCRONIZARDOCUMENTOSRESULT WSCLIENT WSMANIFESTACAODESTINATARIO
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<SINCRONIZARDOCUMENTOS xmlns="http://localhost:8080/">'
cSoap += WSSoapValue("USERTOKEN", ::cUSERTOKEN, cUSERTOKEN , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("IDENT", ::cIDENT, cIDENT , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("INDNFE", ::cINDNFE, cINDNFE , "string", .F. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("INDEMI", ::cINDEMI, cINDEMI , "string", .F. , .F., 0 , NIL, .F.) 
cSoap += "</SINCRONIZARDOCUMENTOS>"

oXmlRet := SvcSoapCall(	ObjSelf(Self),cSoap,; 
	"http://localhost:8080/SINCRONIZARDOCUMENTOS",; 
	"DOCUMENT","http://localhost:8080/",,"1.031217",; 
	"http://localhost:8080/MANIFESTACAODESTINATARIO.apw")

::Init()
::oWSSINCRONIZARDOCUMENTOSRESULT:SoapRecv( WSAdvValue( oXmlRet,"_SINCRONIZARDOCUMENTOSRESPONSE:_SINCRONIZARDOCUMENTOSRESULT","SINCRONIZARDOCUMENTOSRET",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.


// WSDL Data Structure BAIXARDOCUMENTOS

WSSTRUCT MANIFESTACAODESTINATARIO_BAIXARDOCUMENTOS
	WSDATA   oWSDOCUMENTO              AS MANIFESTACAODESTINATARIO_ARRAYOFBAIXARDOCUMENTO
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPSEND
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT MANIFESTACAODESTINATARIO_BAIXARDOCUMENTOS
	::Init()
Return Self

WSMETHOD INIT WSCLIENT MANIFESTACAODESTINATARIO_BAIXARDOCUMENTOS
Return

WSMETHOD CLONE WSCLIENT MANIFESTACAODESTINATARIO_BAIXARDOCUMENTOS
	Local oClone := MANIFESTACAODESTINATARIO_BAIXARDOCUMENTOS():NEW()
	oClone:oWSDOCUMENTO         := IIF(::oWSDOCUMENTO = NIL , NIL , ::oWSDOCUMENTO:Clone() )
Return oClone

WSMETHOD SOAPSEND WSCLIENT MANIFESTACAODESTINATARIO_BAIXARDOCUMENTOS
	Local cSoap := ""
	cSoap += WSSoapValue("DOCUMENTO", ::oWSDOCUMENTO, ::oWSDOCUMENTO , "ARRAYOFBAIXARDOCUMENTO", .T. , .F., 0 , NIL, .F.) 
Return cSoap

// WSDL Data Structure BAIXARDOCUMENTOSRET

WSSTRUCT MANIFESTACAODESTINATARIO_BAIXARDOCUMENTOSRET
	WSDATA   oWSDOCUMENTORET           AS MANIFESTACAODESTINATARIO_ARRAYOFBAIXARDOCUMENTORET
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT MANIFESTACAODESTINATARIO_BAIXARDOCUMENTOSRET
	::Init()
Return Self

WSMETHOD INIT WSCLIENT MANIFESTACAODESTINATARIO_BAIXARDOCUMENTOSRET
Return

WSMETHOD CLONE WSCLIENT MANIFESTACAODESTINATARIO_BAIXARDOCUMENTOSRET
	Local oClone := MANIFESTACAODESTINATARIO_BAIXARDOCUMENTOSRET():NEW()
	oClone:oWSDOCUMENTORET      := IIF(::oWSDOCUMENTORET = NIL , NIL , ::oWSDOCUMENTORET:Clone() )
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT MANIFESTACAODESTINATARIO_BAIXARDOCUMENTOSRET
	Local oNode1
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNode1 :=  WSAdvValue( oResponse,"_DOCUMENTORET","ARRAYOFBAIXARDOCUMENTORET",NIL,"Property oWSDOCUMENTORET as s0:ARRAYOFBAIXARDOCUMENTORET on SOAP Response not found.",NIL,"O",NIL,NIL) 
	If oNode1 != NIL
		::oWSDOCUMENTORET := MANIFESTACAODESTINATARIO_ARRAYOFBAIXARDOCUMENTORET():New()
		::oWSDOCUMENTORET:SoapRecv(oNode1)
	EndIf
Return

// WSDL Data Structure CONFIGURARPARAMETROSRET

WSSTRUCT MANIFESTACAODESTINATARIO_CONFIGURARPARAMETROSRET
	WSDATA   cAMBIENTE                 AS string
	WSDATA   cIDENT                    AS string
	WSDATA   cVERSAO                   AS string
	WSDATA   cULTNSU                   AS string OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT MANIFESTACAODESTINATARIO_CONFIGURARPARAMETROSRET
	::Init()
Return Self

WSMETHOD INIT WSCLIENT MANIFESTACAODESTINATARIO_CONFIGURARPARAMETROSRET
Return

WSMETHOD CLONE WSCLIENT MANIFESTACAODESTINATARIO_CONFIGURARPARAMETROSRET
	Local oClone := MANIFESTACAODESTINATARIO_CONFIGURARPARAMETROSRET():NEW()
	oClone:cAMBIENTE            := ::cAMBIENTE
	oClone:cIDENT               := ::cIDENT
	oClone:cVERSAO              := ::cVERSAO
	oClone:cULTNSU              := ::cULTNSU
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT MANIFESTACAODESTINATARIO_CONFIGURARPARAMETROSRET
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::cAMBIENTE          :=  WSAdvValue( oResponse,"_AMBIENTE","string",NIL,"Property cAMBIENTE as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cIDENT             :=  WSAdvValue( oResponse,"_IDENT","string",NIL,"Property cIDENT as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cVERSAO            :=  WSAdvValue( oResponse,"_VERSAO","string",NIL,"Property cVERSAO as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cULTNSU            :=  WSAdvValue( oResponse,"_ULTNSU","string",NIL,"Property cULTNSU as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
Return

// WSDL Data Structure MONITORARDOCUMENTOSDADOS

WSSTRUCT MANIFESTACAODESTINATARIO_MONITORARDOCUMENTOSDADOS
	WSDATA   oWSDOCUMENTOS             AS MANIFESTACAODESTINATARIO_ARRAYOFMONDOCUMENTO
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPSEND
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT MANIFESTACAODESTINATARIO_MONITORARDOCUMENTOSDADOS
	::Init()
Return Self

WSMETHOD INIT WSCLIENT MANIFESTACAODESTINATARIO_MONITORARDOCUMENTOSDADOS
Return

WSMETHOD CLONE WSCLIENT MANIFESTACAODESTINATARIO_MONITORARDOCUMENTOSDADOS
	Local oClone := MANIFESTACAODESTINATARIO_MONITORARDOCUMENTOSDADOS():NEW()
	oClone:oWSDOCUMENTOS        := IIF(::oWSDOCUMENTOS = NIL , NIL , ::oWSDOCUMENTOS:Clone() )
Return oClone

WSMETHOD SOAPSEND WSCLIENT MANIFESTACAODESTINATARIO_MONITORARDOCUMENTOSDADOS
	Local cSoap := ""
	cSoap += WSSoapValue("DOCUMENTOS", ::oWSDOCUMENTOS, ::oWSDOCUMENTOS , "ARRAYOFMONDOCUMENTO", .T. , .F., 0 , NIL, .F.) 
Return cSoap

// WSDL Data Structure MONITORARDOCUMENTOSRET

WSSTRUCT MANIFESTACAODESTINATARIO_MONITORARDOCUMENTOSRET
	WSDATA   cAMBIENTE                 AS string
	WSDATA   oWSDOCUMENTOS             AS MANIFESTACAODESTINATARIO_ARRAYOFMONDOCUMENTORET OPTIONAL
	WSDATA   cIDENT                    AS string
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT MANIFESTACAODESTINATARIO_MONITORARDOCUMENTOSRET
	::Init()
Return Self

WSMETHOD INIT WSCLIENT MANIFESTACAODESTINATARIO_MONITORARDOCUMENTOSRET
Return

WSMETHOD CLONE WSCLIENT MANIFESTACAODESTINATARIO_MONITORARDOCUMENTOSRET
	Local oClone := MANIFESTACAODESTINATARIO_MONITORARDOCUMENTOSRET():NEW()
	oClone:cAMBIENTE            := ::cAMBIENTE
	oClone:oWSDOCUMENTOS        := IIF(::oWSDOCUMENTOS = NIL , NIL , ::oWSDOCUMENTOS:Clone() )
	oClone:cIDENT               := ::cIDENT
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT MANIFESTACAODESTINATARIO_MONITORARDOCUMENTOSRET
	Local oNode2
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::cAMBIENTE          :=  WSAdvValue( oResponse,"_AMBIENTE","string",NIL,"Property cAMBIENTE as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	oNode2 :=  WSAdvValue( oResponse,"_DOCUMENTOS","ARRAYOFMONDOCUMENTORET",NIL,NIL,NIL,"O",NIL,NIL) 
	If oNode2 != NIL
		::oWSDOCUMENTOS := MANIFESTACAODESTINATARIO_ARRAYOFMONDOCUMENTORET():New()
		::oWSDOCUMENTOS:SoapRecv(oNode2)
	EndIf
	::cIDENT             :=  WSAdvValue( oResponse,"_IDENT","string",NIL,"Property cIDENT as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
Return

// WSDL Data Structure PESQUISARDOCUMENTOSRET

WSSTRUCT MANIFESTACAODESTINATARIO_PESQUISARDOCUMENTOSRET
	WSDATA   cAMBIENTE                 AS string
	WSDATA   oWSDOCUMENTOS             AS MANIFESTACAODESTINATARIO_RETORNADOCUMENTOS OPTIONAL
	WSDATA   cIDENT                    AS string
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT MANIFESTACAODESTINATARIO_PESQUISARDOCUMENTOSRET
	::Init()
Return Self

WSMETHOD INIT WSCLIENT MANIFESTACAODESTINATARIO_PESQUISARDOCUMENTOSRET
Return

WSMETHOD CLONE WSCLIENT MANIFESTACAODESTINATARIO_PESQUISARDOCUMENTOSRET
	Local oClone := MANIFESTACAODESTINATARIO_PESQUISARDOCUMENTOSRET():NEW()
	oClone:cAMBIENTE            := ::cAMBIENTE
	oClone:oWSDOCUMENTOS        := IIF(::oWSDOCUMENTOS = NIL , NIL , ::oWSDOCUMENTOS:Clone() )
	oClone:cIDENT               := ::cIDENT
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT MANIFESTACAODESTINATARIO_PESQUISARDOCUMENTOSRET
	Local oNode2
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::cAMBIENTE          :=  WSAdvValue( oResponse,"_AMBIENTE","string",NIL,"Property cAMBIENTE as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	oNode2 :=  WSAdvValue( oResponse,"_DOCUMENTOS","RETORNADOCUMENTOS",NIL,NIL,NIL,"O",NIL,NIL) 
	If oNode2 != NIL
		::oWSDOCUMENTOS := MANIFESTACAODESTINATARIO_RETORNADOCUMENTOS():New()
		::oWSDOCUMENTOS:SoapRecv(oNode2)
	EndIf
	::cIDENT             :=  WSAdvValue( oResponse,"_IDENT","string",NIL,"Property cIDENT as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
Return

// WSDL Data Structure RETORNARDOCUMENTORET

WSSTRUCT MANIFESTACAODESTINATARIO_RETORNARDOCUMENTORET
	WSDATA   cAMBIENTE                 AS string
	WSDATA   oWSDOCUMENTO              AS MANIFESTACAODESTINATARIO_RETORNADADOSDOCUMENTO OPTIONAL
	WSDATA   cIDENT                    AS string
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT MANIFESTACAODESTINATARIO_RETORNARDOCUMENTORET
	::Init()
Return Self

WSMETHOD INIT WSCLIENT MANIFESTACAODESTINATARIO_RETORNARDOCUMENTORET
Return

WSMETHOD CLONE WSCLIENT MANIFESTACAODESTINATARIO_RETORNARDOCUMENTORET
	Local oClone := MANIFESTACAODESTINATARIO_RETORNARDOCUMENTORET():NEW()
	oClone:cAMBIENTE            := ::cAMBIENTE
	oClone:oWSDOCUMENTO         := IIF(::oWSDOCUMENTO = NIL , NIL , ::oWSDOCUMENTO:Clone() )
	oClone:cIDENT               := ::cIDENT
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT MANIFESTACAODESTINATARIO_RETORNARDOCUMENTORET
	Local oNode2
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::cAMBIENTE          :=  WSAdvValue( oResponse,"_AMBIENTE","string",NIL,"Property cAMBIENTE as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	oNode2 :=  WSAdvValue( oResponse,"_DOCUMENTO","RETORNADADOSDOCUMENTO",NIL,NIL,NIL,"O",NIL,NIL) 
	If oNode2 != NIL
		::oWSDOCUMENTO := MANIFESTACAODESTINATARIO_RETORNADADOSDOCUMENTO():New()
		::oWSDOCUMENTO:SoapRecv(oNode2)
	EndIf
	::cIDENT             :=  WSAdvValue( oResponse,"_IDENT","string",NIL,"Property cIDENT as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
Return

// WSDL Data Structure SINCRONIZARDOCUMENTOSRET

WSSTRUCT MANIFESTACAODESTINATARIO_SINCRONIZARDOCUMENTOSRET
	WSDATA   cAMBIENTE                 AS string
	WSDATA   oWSDOCUMENTOS             AS MANIFESTACAODESTINATARIO_ARRAYOFSINCDOCUMENTOINFO OPTIONAL
	WSDATA   cIDENT                    AS string
	WSDATA   cINDCONT                  AS string OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT MANIFESTACAODESTINATARIO_SINCRONIZARDOCUMENTOSRET
	::Init()
Return Self

WSMETHOD INIT WSCLIENT MANIFESTACAODESTINATARIO_SINCRONIZARDOCUMENTOSRET
Return

WSMETHOD CLONE WSCLIENT MANIFESTACAODESTINATARIO_SINCRONIZARDOCUMENTOSRET
	Local oClone := MANIFESTACAODESTINATARIO_SINCRONIZARDOCUMENTOSRET():NEW()
	oClone:cAMBIENTE            := ::cAMBIENTE
	oClone:oWSDOCUMENTOS        := IIF(::oWSDOCUMENTOS = NIL , NIL , ::oWSDOCUMENTOS:Clone() )
	oClone:cIDENT               := ::cIDENT
	oClone:cINDCONT             := ::cINDCONT
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT MANIFESTACAODESTINATARIO_SINCRONIZARDOCUMENTOSRET
	Local oNode2
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::cAMBIENTE          :=  WSAdvValue( oResponse,"_AMBIENTE","string",NIL,"Property cAMBIENTE as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	oNode2 :=  WSAdvValue( oResponse,"_DOCUMENTOS","ARRAYOFSINCDOCUMENTOINFO",NIL,NIL,NIL,"O",NIL,NIL) 
	If oNode2 != NIL
		::oWSDOCUMENTOS := MANIFESTACAODESTINATARIO_ARRAYOFSINCDOCUMENTOINFO():New()
		::oWSDOCUMENTOS:SoapRecv(oNode2)
	EndIf
	::cIDENT             :=  WSAdvValue( oResponse,"_IDENT","string",NIL,"Property cIDENT as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cINDCONT           :=  WSAdvValue( oResponse,"_INDCONT","string",NIL,NIL,NIL,"S",NIL,NIL) 
Return

// WSDL Data Structure ARRAYOFBAIXARDOCUMENTO

WSSTRUCT MANIFESTACAODESTINATARIO_ARRAYOFBAIXARDOCUMENTO
	WSDATA   oWSBAIXARDOCUMENTO        AS MANIFESTACAODESTINATARIO_BAIXARDOCUMENTO OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPSEND
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT MANIFESTACAODESTINATARIO_ARRAYOFBAIXARDOCUMENTO
	::Init()
Return Self

WSMETHOD INIT WSCLIENT MANIFESTACAODESTINATARIO_ARRAYOFBAIXARDOCUMENTO
	::oWSBAIXARDOCUMENTO   := {} // Array Of  MANIFESTACAODESTINATARIO_BAIXARDOCUMENTO():New()
Return

WSMETHOD CLONE WSCLIENT MANIFESTACAODESTINATARIO_ARRAYOFBAIXARDOCUMENTO
	Local oClone := MANIFESTACAODESTINATARIO_ARRAYOFBAIXARDOCUMENTO():NEW()
	oClone:oWSBAIXARDOCUMENTO := NIL
	If ::oWSBAIXARDOCUMENTO <> NIL 
		oClone:oWSBAIXARDOCUMENTO := {}
		aEval( ::oWSBAIXARDOCUMENTO , { |x| aadd( oClone:oWSBAIXARDOCUMENTO , x:Clone() ) } )
	Endif 
Return oClone

WSMETHOD SOAPSEND WSCLIENT MANIFESTACAODESTINATARIO_ARRAYOFBAIXARDOCUMENTO
	Local cSoap := ""
	aEval( ::oWSBAIXARDOCUMENTO , {|x| cSoap := cSoap  +  WSSoapValue("BAIXARDOCUMENTO", x , x , "BAIXARDOCUMENTO", .F. , .F., 0 , NIL, .F.)  } ) 
Return cSoap

// WSDL Data Structure ARRAYOFBAIXARDOCUMENTORET

WSSTRUCT MANIFESTACAODESTINATARIO_ARRAYOFBAIXARDOCUMENTORET
	WSDATA   oWSBAIXARDOCUMENTORET     AS MANIFESTACAODESTINATARIO_BAIXARDOCUMENTORET OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT MANIFESTACAODESTINATARIO_ARRAYOFBAIXARDOCUMENTORET
	::Init()
Return Self

WSMETHOD INIT WSCLIENT MANIFESTACAODESTINATARIO_ARRAYOFBAIXARDOCUMENTORET
	::oWSBAIXARDOCUMENTORET := {} // Array Of  MANIFESTACAODESTINATARIO_BAIXARDOCUMENTORET():New()
Return

WSMETHOD CLONE WSCLIENT MANIFESTACAODESTINATARIO_ARRAYOFBAIXARDOCUMENTORET
	Local oClone := MANIFESTACAODESTINATARIO_ARRAYOFBAIXARDOCUMENTORET():NEW()
	oClone:oWSBAIXARDOCUMENTORET := NIL
	If ::oWSBAIXARDOCUMENTORET <> NIL 
		oClone:oWSBAIXARDOCUMENTORET := {}
		aEval( ::oWSBAIXARDOCUMENTORET , { |x| aadd( oClone:oWSBAIXARDOCUMENTORET , x:Clone() ) } )
	Endif 
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT MANIFESTACAODESTINATARIO_ARRAYOFBAIXARDOCUMENTORET
	Local nRElem1, oNodes1, nTElem1
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNodes1 :=  WSAdvValue( oResponse,"_BAIXARDOCUMENTORET","BAIXARDOCUMENTORET",{},NIL,.T.,"O",NIL,NIL) 
	nTElem1 := len(oNodes1)
	For nRElem1 := 1 to nTElem1 
		If !WSIsNilNode( oNodes1[nRElem1] )
			aadd(::oWSBAIXARDOCUMENTORET , MANIFESTACAODESTINATARIO_BAIXARDOCUMENTORET():New() )
			::oWSBAIXARDOCUMENTORET[len(::oWSBAIXARDOCUMENTORET)]:SoapRecv(oNodes1[nRElem1])
		Endif
	Next
Return

// WSDL Data Structure ARRAYOFMONDOCUMENTO

WSSTRUCT MANIFESTACAODESTINATARIO_ARRAYOFMONDOCUMENTO
	WSDATA   oWSMONDOCUMENTO           AS MANIFESTACAODESTINATARIO_MONDOCUMENTO OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPSEND
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT MANIFESTACAODESTINATARIO_ARRAYOFMONDOCUMENTO
	::Init()
Return Self

WSMETHOD INIT WSCLIENT MANIFESTACAODESTINATARIO_ARRAYOFMONDOCUMENTO
	::oWSMONDOCUMENTO      := {} // Array Of  MANIFESTACAODESTINATARIO_MONDOCUMENTO():New()
Return

WSMETHOD CLONE WSCLIENT MANIFESTACAODESTINATARIO_ARRAYOFMONDOCUMENTO
	Local oClone := MANIFESTACAODESTINATARIO_ARRAYOFMONDOCUMENTO():NEW()
	oClone:oWSMONDOCUMENTO := NIL
	If ::oWSMONDOCUMENTO <> NIL 
		oClone:oWSMONDOCUMENTO := {}
		aEval( ::oWSMONDOCUMENTO , { |x| aadd( oClone:oWSMONDOCUMENTO , x:Clone() ) } )
	Endif 
Return oClone

WSMETHOD SOAPSEND WSCLIENT MANIFESTACAODESTINATARIO_ARRAYOFMONDOCUMENTO
	Local cSoap := ""
	aEval( ::oWSMONDOCUMENTO , {|x| cSoap := cSoap  +  WSSoapValue("MONDOCUMENTO", x , x , "MONDOCUMENTO", .F. , .F., 0 , NIL, .F.)  } ) 
Return cSoap

// WSDL Data Structure ARRAYOFMONDOCUMENTORET

WSSTRUCT MANIFESTACAODESTINATARIO_ARRAYOFMONDOCUMENTORET
	WSDATA   oWSMONDOCUMENTORET        AS MANIFESTACAODESTINATARIO_MONDOCUMENTORET OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT MANIFESTACAODESTINATARIO_ARRAYOFMONDOCUMENTORET
	::Init()
Return Self

WSMETHOD INIT WSCLIENT MANIFESTACAODESTINATARIO_ARRAYOFMONDOCUMENTORET
	::oWSMONDOCUMENTORET   := {} // Array Of  MANIFESTACAODESTINATARIO_MONDOCUMENTORET():New()
Return

WSMETHOD CLONE WSCLIENT MANIFESTACAODESTINATARIO_ARRAYOFMONDOCUMENTORET
	Local oClone := MANIFESTACAODESTINATARIO_ARRAYOFMONDOCUMENTORET():NEW()
	oClone:oWSMONDOCUMENTORET := NIL
	If ::oWSMONDOCUMENTORET <> NIL 
		oClone:oWSMONDOCUMENTORET := {}
		aEval( ::oWSMONDOCUMENTORET , { |x| aadd( oClone:oWSMONDOCUMENTORET , x:Clone() ) } )
	Endif 
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT MANIFESTACAODESTINATARIO_ARRAYOFMONDOCUMENTORET
	Local nRElem1, oNodes1, nTElem1
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNodes1 :=  WSAdvValue( oResponse,"_MONDOCUMENTORET","MONDOCUMENTORET",{},NIL,.T.,"O",NIL,NIL) 
	nTElem1 := len(oNodes1)
	For nRElem1 := 1 to nTElem1 
		If !WSIsNilNode( oNodes1[nRElem1] )
			aadd(::oWSMONDOCUMENTORET , MANIFESTACAODESTINATARIO_MONDOCUMENTORET():New() )
			::oWSMONDOCUMENTORET[len(::oWSMONDOCUMENTORET)]:SoapRecv(oNodes1[nRElem1])
		Endif
	Next
Return

// WSDL Data Structure RETORNADOCUMENTOS

WSSTRUCT MANIFESTACAODESTINATARIO_RETORNADOCUMENTOS
	WSDATA   oWSDOCUMENTO              AS MANIFESTACAODESTINATARIO_ARRAYOFRETORNACHAVES OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT MANIFESTACAODESTINATARIO_RETORNADOCUMENTOS
	::Init()
Return Self

WSMETHOD INIT WSCLIENT MANIFESTACAODESTINATARIO_RETORNADOCUMENTOS
Return

WSMETHOD CLONE WSCLIENT MANIFESTACAODESTINATARIO_RETORNADOCUMENTOS
	Local oClone := MANIFESTACAODESTINATARIO_RETORNADOCUMENTOS():NEW()
	oClone:oWSDOCUMENTO         := IIF(::oWSDOCUMENTO = NIL , NIL , ::oWSDOCUMENTO:Clone() )
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT MANIFESTACAODESTINATARIO_RETORNADOCUMENTOS
	Local oNode1
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNode1 :=  WSAdvValue( oResponse,"_DOCUMENTO","ARRAYOFRETORNACHAVES",NIL,NIL,NIL,"O",NIL,NIL) 
	If oNode1 != NIL
		::oWSDOCUMENTO := MANIFESTACAODESTINATARIO_ARRAYOFRETORNACHAVES():New()
		::oWSDOCUMENTO:SoapRecv(oNode1)
	EndIf
Return

// WSDL Data Structure RETORNADADOSDOCUMENTO

WSSTRUCT MANIFESTACAODESTINATARIO_RETORNADADOSDOCUMENTO
	WSDATA   oWSCANCELAMENTO           AS MANIFESTACAODESTINATARIO_RETORNADADOSCANCELAMENTO OPTIONAL
	WSDATA   oWSCCE                    AS MANIFESTACAODESTINATARIO_RETORNADADOSCCE OPTIONAL
	WSDATA   cCHAVE                    AS string OPTIONAL
	WSDATA   cDATAAUTORIZACAO          AS string OPTIONAL
	WSDATA   cDATAEMISSAO              AS string OPTIONAL
	WSDATA   oWSEMITENTE               AS MANIFESTACAODESTINATARIO_RETORNADADOSEMITENTE OPTIONAL
	WSDATA   cNSU                      AS string OPTIONAL
	WSDATA   oWSRESPOSTA               AS MANIFESTACAODESTINATARIO_RETORNADADOSRESPOSTA OPTIONAL
	WSDATA   cSITUACAO                 AS string OPTIONAL
	WSDATA   cSITUACAOCONFIRMACAO      AS string OPTIONAL
	WSDATA   cTIPOOPERACAO             AS string OPTIONAL
	WSDATA   nVALORTOTAL               AS integer OPTIONAL
	WSDATA   cXMLSEFAZ                 AS base64Binary OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT MANIFESTACAODESTINATARIO_RETORNADADOSDOCUMENTO
	::Init()
Return Self

WSMETHOD INIT WSCLIENT MANIFESTACAODESTINATARIO_RETORNADADOSDOCUMENTO
Return

WSMETHOD CLONE WSCLIENT MANIFESTACAODESTINATARIO_RETORNADADOSDOCUMENTO
	Local oClone := MANIFESTACAODESTINATARIO_RETORNADADOSDOCUMENTO():NEW()
	oClone:oWSCANCELAMENTO      := IIF(::oWSCANCELAMENTO = NIL , NIL , ::oWSCANCELAMENTO:Clone() )
	oClone:oWSCCE               := IIF(::oWSCCE = NIL , NIL , ::oWSCCE:Clone() )
	oClone:cCHAVE               := ::cCHAVE
	oClone:cDATAAUTORIZACAO     := ::cDATAAUTORIZACAO
	oClone:cDATAEMISSAO         := ::cDATAEMISSAO
	oClone:oWSEMITENTE          := IIF(::oWSEMITENTE = NIL , NIL , ::oWSEMITENTE:Clone() )
	oClone:cNSU                 := ::cNSU
	oClone:oWSRESPOSTA          := IIF(::oWSRESPOSTA = NIL , NIL , ::oWSRESPOSTA:Clone() )
	oClone:cSITUACAO            := ::cSITUACAO
	oClone:cSITUACAOCONFIRMACAO := ::cSITUACAOCONFIRMACAO
	oClone:cTIPOOPERACAO        := ::cTIPOOPERACAO
	oClone:nVALORTOTAL          := ::nVALORTOTAL
	oClone:cXMLSEFAZ            := ::cXMLSEFAZ
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT MANIFESTACAODESTINATARIO_RETORNADADOSDOCUMENTO
	Local oNode1
	Local oNode2
	Local oNode6
	Local oNode8
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNode1 :=  WSAdvValue( oResponse,"_CANCELAMENTO","RETORNADADOSCANCELAMENTO",NIL,NIL,NIL,"O",NIL,NIL) 
	If oNode1 != NIL
		::oWSCANCELAMENTO := MANIFESTACAODESTINATARIO_RETORNADADOSCANCELAMENTO():New()
		::oWSCANCELAMENTO:SoapRecv(oNode1)
	EndIf
	oNode2 :=  WSAdvValue( oResponse,"_CCE","RETORNADADOSCCE",NIL,NIL,NIL,"O",NIL,NIL) 
	If oNode2 != NIL
		::oWSCCE := MANIFESTACAODESTINATARIO_RETORNADADOSCCE():New()
		::oWSCCE:SoapRecv(oNode2)
	EndIf
	::cCHAVE             :=  WSAdvValue( oResponse,"_CHAVE","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cDATAAUTORIZACAO   :=  WSAdvValue( oResponse,"_DATAAUTORIZACAO","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cDATAEMISSAO       :=  WSAdvValue( oResponse,"_DATAEMISSAO","string",NIL,NIL,NIL,"S",NIL,NIL) 
	oNode6 :=  WSAdvValue( oResponse,"_EMITENTE","RETORNADADOSEMITENTE",NIL,NIL,NIL,"O",NIL,NIL) 
	If oNode6 != NIL
		::oWSEMITENTE := MANIFESTACAODESTINATARIO_RETORNADADOSEMITENTE():New()
		::oWSEMITENTE:SoapRecv(oNode6)
	EndIf
	::cNSU               :=  WSAdvValue( oResponse,"_NSU","string",NIL,NIL,NIL,"S",NIL,NIL) 
	oNode8 :=  WSAdvValue( oResponse,"_RESPOSTA","RETORNADADOSRESPOSTA",NIL,NIL,NIL,"O",NIL,NIL) 
	If oNode8 != NIL
		::oWSRESPOSTA := MANIFESTACAODESTINATARIO_RETORNADADOSRESPOSTA():New()
		::oWSRESPOSTA:SoapRecv(oNode8)
	EndIf
	::cSITUACAO          :=  WSAdvValue( oResponse,"_SITUACAO","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cSITUACAOCONFIRMACAO :=  WSAdvValue( oResponse,"_SITUACAOCONFIRMACAO","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cTIPOOPERACAO      :=  WSAdvValue( oResponse,"_TIPOOPERACAO","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::nVALORTOTAL        :=  WSAdvValue( oResponse,"_VALORTOTAL","integer",NIL,NIL,NIL,"N",NIL,NIL) 
	::cXMLSEFAZ          :=  WSAdvValue( oResponse,"_XMLSEFAZ","base64Binary",NIL,NIL,NIL,"SB",NIL,NIL) 
Return

// WSDL Data Structure ARRAYOFSINCDOCUMENTOINFO

WSSTRUCT MANIFESTACAODESTINATARIO_ARRAYOFSINCDOCUMENTOINFO
	WSDATA   oWSSINCDOCUMENTOINFO      AS MANIFESTACAODESTINATARIO_SINCDOCUMENTOINFO OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT MANIFESTACAODESTINATARIO_ARRAYOFSINCDOCUMENTOINFO
	::Init()
Return Self

WSMETHOD INIT WSCLIENT MANIFESTACAODESTINATARIO_ARRAYOFSINCDOCUMENTOINFO
	::oWSSINCDOCUMENTOINFO := {} // Array Of  MANIFESTACAODESTINATARIO_SINCDOCUMENTOINFO():New()
Return

WSMETHOD CLONE WSCLIENT MANIFESTACAODESTINATARIO_ARRAYOFSINCDOCUMENTOINFO
	Local oClone := MANIFESTACAODESTINATARIO_ARRAYOFSINCDOCUMENTOINFO():NEW()
	oClone:oWSSINCDOCUMENTOINFO := NIL
	If ::oWSSINCDOCUMENTOINFO <> NIL 
		oClone:oWSSINCDOCUMENTOINFO := {}
		aEval( ::oWSSINCDOCUMENTOINFO , { |x| aadd( oClone:oWSSINCDOCUMENTOINFO , x:Clone() ) } )
	Endif 
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT MANIFESTACAODESTINATARIO_ARRAYOFSINCDOCUMENTOINFO
	Local nRElem1, oNodes1, nTElem1
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNodes1 :=  WSAdvValue( oResponse,"_SINCDOCUMENTOINFO","SINCDOCUMENTOINFO",{},NIL,.T.,"O",NIL,NIL) 
	nTElem1 := len(oNodes1)
	For nRElem1 := 1 to nTElem1 
		If !WSIsNilNode( oNodes1[nRElem1] )
			aadd(::oWSSINCDOCUMENTOINFO , MANIFESTACAODESTINATARIO_SINCDOCUMENTOINFO():New() )
			::oWSSINCDOCUMENTOINFO[len(::oWSSINCDOCUMENTOINFO)]:SoapRecv(oNodes1[nRElem1])
		Endif
	Next
Return

// WSDL Data Structure BAIXARDOCUMENTO

WSSTRUCT MANIFESTACAODESTINATARIO_BAIXARDOCUMENTO
	WSDATA   cCHAVE                    AS string
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPSEND
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT MANIFESTACAODESTINATARIO_BAIXARDOCUMENTO
	::Init()
Return Self

WSMETHOD INIT WSCLIENT MANIFESTACAODESTINATARIO_BAIXARDOCUMENTO
Return

WSMETHOD CLONE WSCLIENT MANIFESTACAODESTINATARIO_BAIXARDOCUMENTO
	Local oClone := MANIFESTACAODESTINATARIO_BAIXARDOCUMENTO():NEW()
	oClone:cCHAVE               := ::cCHAVE
Return oClone

WSMETHOD SOAPSEND WSCLIENT MANIFESTACAODESTINATARIO_BAIXARDOCUMENTO
	Local cSoap := ""
	cSoap += WSSoapValue("CHAVE", ::cCHAVE, ::cCHAVE , "string", .T. , .F., 0 , NIL, .F.) 
Return cSoap

// WSDL Data Structure BAIXARDOCUMENTORET

WSSTRUCT MANIFESTACAODESTINATARIO_BAIXARDOCUMENTORET
	WSDATA   cCHAVE                    AS string
	WSDATA   cCHVDESC                  AS string
	WSDATA   cCHVSTATUS                AS string
	WSDATA   cDESCRICAO                AS string
	WSDATA   cDHPROC                   AS string
	WSDATA   cNFEPROCZIP               AS base64Binary
	WSDATA   cNFEPROTZIP               AS base64Binary
	WSDATA   cNFEZIP                   AS base64Binary
	WSDATA   cSTATUS                   AS string
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT MANIFESTACAODESTINATARIO_BAIXARDOCUMENTORET
	::Init()
Return Self

WSMETHOD INIT WSCLIENT MANIFESTACAODESTINATARIO_BAIXARDOCUMENTORET
Return

WSMETHOD CLONE WSCLIENT MANIFESTACAODESTINATARIO_BAIXARDOCUMENTORET
	Local oClone := MANIFESTACAODESTINATARIO_BAIXARDOCUMENTORET():NEW()
	oClone:cCHAVE               := ::cCHAVE
	oClone:cCHVDESC             := ::cCHVDESC
	oClone:cCHVSTATUS           := ::cCHVSTATUS
	oClone:cDESCRICAO           := ::cDESCRICAO
	oClone:cDHPROC              := ::cDHPROC
	oClone:cNFEPROCZIP          := ::cNFEPROCZIP
	oClone:cNFEPROTZIP          := ::cNFEPROTZIP
	oClone:cNFEZIP              := ::cNFEZIP
	oClone:cSTATUS              := ::cSTATUS
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT MANIFESTACAODESTINATARIO_BAIXARDOCUMENTORET
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::cCHAVE             :=  WSAdvValue( oResponse,"_CHAVE","string",NIL,"Property cCHAVE as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCHVDESC           :=  WSAdvValue( oResponse,"_CHVDESC","string",NIL,"Property cCHVDESC as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCHVSTATUS         :=  WSAdvValue( oResponse,"_CHVSTATUS","string",NIL,"Property cCHVSTATUS as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cDESCRICAO         :=  WSAdvValue( oResponse,"_DESCRICAO","string",NIL,"Property cDESCRICAO as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cDHPROC            :=  WSAdvValue( oResponse,"_DHPROC","string",NIL,"Property cDHPROC as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cNFEPROCZIP        :=  WSAdvValue( oResponse,"_NFEPROCZIP","base64Binary",NIL,"Property cNFEPROCZIP as s:base64Binary on SOAP Response not found.",NIL,"SB",NIL,NIL) 
	::cNFEPROTZIP        :=  WSAdvValue( oResponse,"_NFEPROTZIP","base64Binary",NIL,"Property cNFEPROTZIP as s:base64Binary on SOAP Response not found.",NIL,"SB",NIL,NIL) 
	::cNFEZIP            :=  WSAdvValue( oResponse,"_NFEZIP","base64Binary",NIL,"Property cNFEZIP as s:base64Binary on SOAP Response not found.",NIL,"SB",NIL,NIL) 
	::cSTATUS            :=  WSAdvValue( oResponse,"_STATUS","string",NIL,"Property cSTATUS as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
Return

// WSDL Data Structure MONDOCUMENTO

WSSTRUCT MANIFESTACAODESTINATARIO_MONDOCUMENTO
	WSDATA   cCHAVE                    AS string
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPSEND
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT MANIFESTACAODESTINATARIO_MONDOCUMENTO
	::Init()
Return Self

WSMETHOD INIT WSCLIENT MANIFESTACAODESTINATARIO_MONDOCUMENTO
Return

WSMETHOD CLONE WSCLIENT MANIFESTACAODESTINATARIO_MONDOCUMENTO
	Local oClone := MANIFESTACAODESTINATARIO_MONDOCUMENTO():NEW()
	oClone:cCHAVE               := ::cCHAVE
Return oClone

WSMETHOD SOAPSEND WSCLIENT MANIFESTACAODESTINATARIO_MONDOCUMENTO
	Local cSoap := ""
	cSoap += WSSoapValue("CHAVE", ::cCHAVE, ::cCHAVE , "string", .T. , .F., 0 , NIL, .F.) 
Return cSoap

// WSDL Data Structure MONDOCUMENTORET

WSSTRUCT MANIFESTACAODESTINATARIO_MONDOCUMENTORET
	WSDATA   cCHAVE                    AS string
	WSDATA   cDATAAUTORIZACAO          AS string
	WSDATA   cDATAEMISSAO              AS string
	WSDATA   cEMITENTECNPJ             AS string
	WSDATA   cEMITENTECPF              AS string
	WSDATA   cEMITENTEIE               AS string
	WSDATA   cEMITENTENOME             AS string
	WSDATA   cRESPOSTADESCRICAO        AS string
	WSDATA   cRESPOSTASTATUS           AS string
	WSDATA   cSITUACAO                 AS string
	WSDATA   cSITUACAOCONFIRMACAO      AS string
	WSDATA   cTIPOOPERACAO             AS string
	WSDATA   nVALORTOTAL               AS integer
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT MANIFESTACAODESTINATARIO_MONDOCUMENTORET
	::Init()
Return Self

WSMETHOD INIT WSCLIENT MANIFESTACAODESTINATARIO_MONDOCUMENTORET
Return

WSMETHOD CLONE WSCLIENT MANIFESTACAODESTINATARIO_MONDOCUMENTORET
	Local oClone := MANIFESTACAODESTINATARIO_MONDOCUMENTORET():NEW()
	oClone:cCHAVE               := ::cCHAVE
	oClone:cDATAAUTORIZACAO     := ::cDATAAUTORIZACAO
	oClone:cDATAEMISSAO         := ::cDATAEMISSAO
	oClone:cEMITENTECNPJ        := ::cEMITENTECNPJ
	oClone:cEMITENTECPF         := ::cEMITENTECPF
	oClone:cEMITENTEIE          := ::cEMITENTEIE
	oClone:cEMITENTENOME        := ::cEMITENTENOME
	oClone:cRESPOSTADESCRICAO   := ::cRESPOSTADESCRICAO
	oClone:cRESPOSTASTATUS      := ::cRESPOSTASTATUS
	oClone:cSITUACAO            := ::cSITUACAO
	oClone:cSITUACAOCONFIRMACAO := ::cSITUACAOCONFIRMACAO
	oClone:cTIPOOPERACAO        := ::cTIPOOPERACAO
	oClone:nVALORTOTAL          := ::nVALORTOTAL
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT MANIFESTACAODESTINATARIO_MONDOCUMENTORET
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::cCHAVE             :=  WSAdvValue( oResponse,"_CHAVE","string",NIL,"Property cCHAVE as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cDATAAUTORIZACAO   :=  WSAdvValue( oResponse,"_DATAAUTORIZACAO","string",NIL,"Property cDATAAUTORIZACAO as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cDATAEMISSAO       :=  WSAdvValue( oResponse,"_DATAEMISSAO","string",NIL,"Property cDATAEMISSAO as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cEMITENTECNPJ      :=  WSAdvValue( oResponse,"_EMITENTECNPJ","string",NIL,"Property cEMITENTECNPJ as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cEMITENTECPF       :=  WSAdvValue( oResponse,"_EMITENTECPF","string",NIL,"Property cEMITENTECPF as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cEMITENTEIE        :=  WSAdvValue( oResponse,"_EMITENTEIE","string",NIL,"Property cEMITENTEIE as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cEMITENTENOME      :=  WSAdvValue( oResponse,"_EMITENTENOME","string",NIL,"Property cEMITENTENOME as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cRESPOSTADESCRICAO :=  WSAdvValue( oResponse,"_RESPOSTADESCRICAO","string",NIL,"Property cRESPOSTADESCRICAO as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cRESPOSTASTATUS    :=  WSAdvValue( oResponse,"_RESPOSTASTATUS","string",NIL,"Property cRESPOSTASTATUS as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cSITUACAO          :=  WSAdvValue( oResponse,"_SITUACAO","string",NIL,"Property cSITUACAO as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cSITUACAOCONFIRMACAO :=  WSAdvValue( oResponse,"_SITUACAOCONFIRMACAO","string",NIL,"Property cSITUACAOCONFIRMACAO as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cTIPOOPERACAO      :=  WSAdvValue( oResponse,"_TIPOOPERACAO","string",NIL,"Property cTIPOOPERACAO as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::nVALORTOTAL        :=  WSAdvValue( oResponse,"_VALORTOTAL","integer",NIL,"Property nVALORTOTAL as s:integer on SOAP Response not found.",NIL,"N",NIL,NIL) 
Return

// WSDL Data Structure ARRAYOFRETORNACHAVES

WSSTRUCT MANIFESTACAODESTINATARIO_ARRAYOFRETORNACHAVES
	WSDATA   oWSRETORNACHAVES          AS MANIFESTACAODESTINATARIO_RETORNACHAVES OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT MANIFESTACAODESTINATARIO_ARRAYOFRETORNACHAVES
	::Init()
Return Self

WSMETHOD INIT WSCLIENT MANIFESTACAODESTINATARIO_ARRAYOFRETORNACHAVES
	::oWSRETORNACHAVES     := {} // Array Of  MANIFESTACAODESTINATARIO_RETORNACHAVES():New()
Return

WSMETHOD CLONE WSCLIENT MANIFESTACAODESTINATARIO_ARRAYOFRETORNACHAVES
	Local oClone := MANIFESTACAODESTINATARIO_ARRAYOFRETORNACHAVES():NEW()
	oClone:oWSRETORNACHAVES := NIL
	If ::oWSRETORNACHAVES <> NIL 
		oClone:oWSRETORNACHAVES := {}
		aEval( ::oWSRETORNACHAVES , { |x| aadd( oClone:oWSRETORNACHAVES , x:Clone() ) } )
	Endif 
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT MANIFESTACAODESTINATARIO_ARRAYOFRETORNACHAVES
	Local nRElem1, oNodes1, nTElem1
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNodes1 :=  WSAdvValue( oResponse,"_RETORNACHAVES","RETORNACHAVES",{},NIL,.T.,"O",NIL,NIL) 
	nTElem1 := len(oNodes1)
	For nRElem1 := 1 to nTElem1 
		If !WSIsNilNode( oNodes1[nRElem1] )
			aadd(::oWSRETORNACHAVES , MANIFESTACAODESTINATARIO_RETORNACHAVES():New() )
			::oWSRETORNACHAVES[len(::oWSRETORNACHAVES)]:SoapRecv(oNodes1[nRElem1])
		Endif
	Next
Return

// WSDL Data Structure RETORNADADOSCANCELAMENTO

WSSTRUCT MANIFESTACAODESTINATARIO_RETORNADADOSCANCELAMENTO
	WSDATA   cCANCNSU                  AS string OPTIONAL
	WSDATA   cCANCXMLRET               AS base64Binary OPTIONAL
	WSDATA   cDATAAUTORIZACAO          AS string OPTIONAL
	WSDATA   cDATAEMISSAO              AS string OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT MANIFESTACAODESTINATARIO_RETORNADADOSCANCELAMENTO
	::Init()
Return Self

WSMETHOD INIT WSCLIENT MANIFESTACAODESTINATARIO_RETORNADADOSCANCELAMENTO
Return

WSMETHOD CLONE WSCLIENT MANIFESTACAODESTINATARIO_RETORNADADOSCANCELAMENTO
	Local oClone := MANIFESTACAODESTINATARIO_RETORNADADOSCANCELAMENTO():NEW()
	oClone:cCANCNSU             := ::cCANCNSU
	oClone:cCANCXMLRET          := ::cCANCXMLRET
	oClone:cDATAAUTORIZACAO     := ::cDATAAUTORIZACAO
	oClone:cDATAEMISSAO         := ::cDATAEMISSAO
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT MANIFESTACAODESTINATARIO_RETORNADADOSCANCELAMENTO
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::cCANCNSU           :=  WSAdvValue( oResponse,"_CANCNSU","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cCANCXMLRET        :=  WSAdvValue( oResponse,"_CANCXMLRET","base64Binary",NIL,NIL,NIL,"SB",NIL,NIL) 
	::cDATAAUTORIZACAO   :=  WSAdvValue( oResponse,"_DATAAUTORIZACAO","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cDATAEMISSAO       :=  WSAdvValue( oResponse,"_DATAEMISSAO","string",NIL,NIL,NIL,"S",NIL,NIL) 
Return

// WSDL Data Structure RETORNADADOSCCE

WSSTRUCT MANIFESTACAODESTINATARIO_RETORNADADOSCCE
	WSDATA   cCCENSU                   AS string OPTIONAL
	WSDATA   cCCEXMLRET                AS base64Binary OPTIONAL
	WSDATA   cCORRECAO                 AS string OPTIONAL
	WSDATA   cDATAAUTORIZACAO          AS string OPTIONAL
	WSDATA   cDATAEMISSAO              AS string OPTIONAL
	WSDATA   cHORAEMISSAO              AS string OPTIONAL
	WSDATA   cTZD                      AS string OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT MANIFESTACAODESTINATARIO_RETORNADADOSCCE
	::Init()
Return Self

WSMETHOD INIT WSCLIENT MANIFESTACAODESTINATARIO_RETORNADADOSCCE
Return

WSMETHOD CLONE WSCLIENT MANIFESTACAODESTINATARIO_RETORNADADOSCCE
	Local oClone := MANIFESTACAODESTINATARIO_RETORNADADOSCCE():NEW()
	oClone:cCCENSU              := ::cCCENSU
	oClone:cCCEXMLRET           := ::cCCEXMLRET
	oClone:cCORRECAO            := ::cCORRECAO
	oClone:cDATAAUTORIZACAO     := ::cDATAAUTORIZACAO
	oClone:cDATAEMISSAO         := ::cDATAEMISSAO
	oClone:cHORAEMISSAO         := ::cHORAEMISSAO
	oClone:cTZD                 := ::cTZD
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT MANIFESTACAODESTINATARIO_RETORNADADOSCCE
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::cCCENSU            :=  WSAdvValue( oResponse,"_CCENSU","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cCCEXMLRET         :=  WSAdvValue( oResponse,"_CCEXMLRET","base64Binary",NIL,NIL,NIL,"SB",NIL,NIL) 
	::cCORRECAO          :=  WSAdvValue( oResponse,"_CORRECAO","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cDATAAUTORIZACAO   :=  WSAdvValue( oResponse,"_DATAAUTORIZACAO","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cDATAEMISSAO       :=  WSAdvValue( oResponse,"_DATAEMISSAO","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cHORAEMISSAO       :=  WSAdvValue( oResponse,"_HORAEMISSAO","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cTZD               :=  WSAdvValue( oResponse,"_TZD","string",NIL,NIL,NIL,"S",NIL,NIL) 
Return

// WSDL Data Structure RETORNADADOSEMITENTE

WSSTRUCT MANIFESTACAODESTINATARIO_RETORNADADOSEMITENTE
	WSDATA   cCNPJ                     AS string OPTIONAL
	WSDATA   cCPF                      AS string OPTIONAL
	WSDATA   cIE                       AS string OPTIONAL
	WSDATA   cNOME                     AS string OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT MANIFESTACAODESTINATARIO_RETORNADADOSEMITENTE
	::Init()
Return Self

WSMETHOD INIT WSCLIENT MANIFESTACAODESTINATARIO_RETORNADADOSEMITENTE
Return

WSMETHOD CLONE WSCLIENT MANIFESTACAODESTINATARIO_RETORNADADOSEMITENTE
	Local oClone := MANIFESTACAODESTINATARIO_RETORNADADOSEMITENTE():NEW()
	oClone:cCNPJ                := ::cCNPJ
	oClone:cCPF                 := ::cCPF
	oClone:cIE                  := ::cIE
	oClone:cNOME                := ::cNOME
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT MANIFESTACAODESTINATARIO_RETORNADADOSEMITENTE
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::cCNPJ              :=  WSAdvValue( oResponse,"_CNPJ","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cCPF               :=  WSAdvValue( oResponse,"_CPF","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cIE                :=  WSAdvValue( oResponse,"_IE","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cNOME              :=  WSAdvValue( oResponse,"_NOME","string",NIL,NIL,NIL,"S",NIL,NIL) 
Return

// WSDL Data Structure RETORNADADOSRESPOSTA

WSSTRUCT MANIFESTACAODESTINATARIO_RETORNADADOSRESPOSTA
	WSDATA   cDESCRICAO                AS string OPTIONAL
	WSDATA   cSTATUS                   AS string OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT MANIFESTACAODESTINATARIO_RETORNADADOSRESPOSTA
	::Init()
Return Self

WSMETHOD INIT WSCLIENT MANIFESTACAODESTINATARIO_RETORNADADOSRESPOSTA
Return

WSMETHOD CLONE WSCLIENT MANIFESTACAODESTINATARIO_RETORNADADOSRESPOSTA
	Local oClone := MANIFESTACAODESTINATARIO_RETORNADADOSRESPOSTA():NEW()
	oClone:cDESCRICAO           := ::cDESCRICAO
	oClone:cSTATUS              := ::cSTATUS
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT MANIFESTACAODESTINATARIO_RETORNADADOSRESPOSTA
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::cDESCRICAO         :=  WSAdvValue( oResponse,"_DESCRICAO","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cSTATUS            :=  WSAdvValue( oResponse,"_STATUS","string",NIL,NIL,NIL,"S",NIL,NIL) 
Return

// WSDL Data Structure SINCDOCUMENTOINFO

WSSTRUCT MANIFESTACAODESTINATARIO_SINCDOCUMENTOINFO
	WSDATA   cCHAVE                    AS string
	WSDATA   cSITCONF                  AS string
	WSDATA   cCANCNSU                  AS string
	WSDATA   cCODEVENTO                AS string OPTIONAL 
	WSDATA   cDESTCNPJ                 AS string OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT MANIFESTACAODESTINATARIO_SINCDOCUMENTOINFO
	::Init()
Return Self

WSMETHOD INIT WSCLIENT MANIFESTACAODESTINATARIO_SINCDOCUMENTOINFO
Return

WSMETHOD CLONE WSCLIENT MANIFESTACAODESTINATARIO_SINCDOCUMENTOINFO
	Local oClone := MANIFESTACAODESTINATARIO_SINCDOCUMENTOINFO():NEW()
	oClone:cCHAVE               := ::cCHAVE
	oClone:cSITCONF             := ::cSITCONF
	oClone:cCANCNSU             := ::cCANCNSU
	oClone:cCODEVENTO           := ::cCODEVENTO
	oClone:cDESTCNPJ            := ::cDESTCNPJ
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT MANIFESTACAODESTINATARIO_SINCDOCUMENTOINFO
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::cCHAVE             :=  WSAdvValue( oResponse,"_CHAVE","string",NIL,"Property cCHAVE as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cSITCONF           :=  WSAdvValue( oResponse,"_SITCONF","string",NIL,"Property cSITCONF as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCANCNSU           :=  WSAdvValue( oResponse,"_CANCNSU","string",NIL,"Property cCANCNSU as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cCODEVENTO			:=  WSAdvValue( oResponse,"_CODEVENTO","string",NIL,"Property cCODEVENTO as s:string on SOAP Response not found.",NIL,"S",NIL,NIL)
	::cDESTCNPJ          :=  WSAdvValue( oResponse,"_DESTCNPJ","string",NIL,NIL,NIL,"S",NIL,NIL) 
Return

// WSDL Data Structure RETORNACHAVES

WSSTRUCT MANIFESTACAODESTINATARIO_RETORNACHAVES
	WSDATA   cCHAVE                    AS string OPTIONAL
	WSDATA   cSITCONF                  AS string OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT MANIFESTACAODESTINATARIO_RETORNACHAVES
	::Init()
Return Self

WSMETHOD INIT WSCLIENT MANIFESTACAODESTINATARIO_RETORNACHAVES
Return

WSMETHOD CLONE WSCLIENT MANIFESTACAODESTINATARIO_RETORNACHAVES
	Local oClone := MANIFESTACAODESTINATARIO_RETORNACHAVES():NEW()
	oClone:cCHAVE               := ::cCHAVE
	oClone:cSITCONF             := ::cSITCONF
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT MANIFESTACAODESTINATARIO_RETORNACHAVES
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::cCHAVE             :=  WSAdvValue( oResponse,"_CHAVE","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cSITCONF           :=  WSAdvValue( oResponse,"_SITCONF","string",NIL,NIL,NIL,"S",NIL,NIL) 
Return


