#INCLUDE "PROTHEUS.CH"

//-------------------------------------------------------------------
/*/{Protheus.doc} GFEI001
Integração de Nota Fiscal de Saída

@author Israel A. Possoli
@since 20/02/2012
@version 1.0
/*/
//-------------------------------------------------------------------
Function GFEI001()
	Help( ,, 'HELP',, "Este programe evoluiu para integração via WebService. Entre em contato com o atendimento solicitando apoio na configuração do ambiente para utilização da nova integração.", 1, 0)
Return
