#INCLUDE "PROTHEUS.CH"
#INCLUDE "APWEBSRV.CH" 

/* ===============================================================================
WSDL Location    http://172.16.33.49:8070/WSFEV1.apw?WSDL
Generado en        08/10/11 14:28:44
Observaciones      Codigo Fuente generado por ADVPL WSDL Client 1.110425
                 Modificaciones en este archivo pueden causar funcionamiento incorrecto
                 y se perderan en caso de que se genere nuevamente el codigo fuente.
=============================================================================== */

User Function _ZOQMXNQ ; Return  // "dummy" function - Internal Use 

/* -------------------------------------------------------------------------------
WSDL Service WSWSFEV1
------------------------------------------------------------------------------- */

WSCLIENT WSWSFEV1

	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD RESET
	WSMETHOD CLONE
	WSMETHOD DUMMYARGWSFEV1
	WSMETHOD MONITORLOC
	WSMETHOD REMESSAWSFE
	WSMETHOD WSFEV1FECAEACONSULTAR
	WSMETHOD WSFEV1FECAEAINFORMARCOMPROBANTE
	WSMETHOD WSFEV1FECAEAREGINFORMATIVO
	WSMETHOD WSFEV1FECAEASINMOVIMIENTOCONSULTAR
	WSMETHOD WSFEV1FECAEASINMOVIMIENTOINFORMAR
	WSMETHOD WSFEV1FECAEASOLICITAR
	WSMETHOD WSFEV1FECOMPCONSULTAR
	WSMETHOD WSFEV1FECOMPTOTXREQUEST
	WSMETHOD WSFEV1FECOMPULTIMOAUTORIZADO
	WSMETHOD WSFEV1FECONSULTARPTOSVENCAEA
	WSMETHOD WSFEV1FEPARAMGETCOTIZACION
	WSMETHOD WSFEV1FEPARAMGETPTOSVENTA
	WSMETHOD WSFEV1FEPARAMGETTIPOSCBTE
	WSMETHOD WSFEV1FEPARAMGETTIPOSCONCEPTO
	WSMETHOD WSFEV1FEPARAMGETTIPOSDOC
	WSMETHOD WSFEV1FEPARAMGETTIPOSIVA
	WSMETHOD WSFEV1FEPARAMGETTIPOSMONEDAS
	WSMETHOD WSFEV1FEPARAMGETTIPOSOPCIONAL
	WSMETHOD WSFEV1FEPARAMGETTIPOSTRIBUTOS
	WSMETHOD WSMTXCAEACONSULTAR
	WSMETHOD WSMTXCAEASOLICITAR

	WSDATA   _URL                      AS String
	WSDATA   _HEADOUT                  AS Array of String
	WSDATA   _COOKIES                  AS Array of String
	WSDATA   cUSERTOKEN                AS string
	WSDATA   cID_ENT                   AS string
	WSDATA   cMODELOWS                 AS string
	WSDATA   oWSDUMMYARGWSFEV1RESULT   AS WSFEV1_DUMMYWSFE
	WSDATA   cIDINICIAL                AS string
	WSDATA   cIDFINAL                  AS string
	WSDATA   oWSMONITORLOCRESULT       AS WSFEV1_MONITORWSFE
	WSDATA   cMODELO                   AS string
	WSDATA   nPTOVTA                   AS integer
	WSDATA   nCBTETIPO                 AS integer
	WSDATA   oWSNFEARG                 AS WSFEV1_ARRNOTASARG
	WSDATA   oWSREMESSAWSFERESULT      AS WSFEV1_IDARG
	WSDATA   nPERIODO                  AS integer
	WSDATA   nORDEN                    AS integer
	WSDATA   oWSWSFEV1FECAEACONSULTARRESULT AS WSFEV1_FEVCAEASOLIC
	WSDATA   oWSWSFEV1FECAEAINFORMARCOMPROBANTERESULT AS WSFEV1_IDARG
	WSDATA   oWSWSFEV1FECAEAREGINFORMATIVORESULT AS WSFEV1_IDARG
	WSDATA   cCAEA                     AS string
	WSDATA   oWSWSFEV1FECAEASINMOVIMIENTOCONSULTARRESULT AS WSFEV1_FEVSINMOVCONSRESULT
	WSDATA   oWSWSFEV1FECAEASINMOVIMIENTOINFORMARRESULT AS WSFEV1_FEVSINMOVINFRESULT
	WSDATA   oWSWSFEV1FECAEASOLICITARRESULT AS WSFEV1_FEVCAEASOLIC
	WSDATA   oWSGETCMP                 AS WSFEV1_GETCMP
	WSDATA   oWSWSFEV1FECOMPCONSULTARRESULT AS WSFEV1_RESULTCOMPCONS
	WSDATA   oWSWSFEV1FECOMPTOTXREQUESTRESULT AS WSFEV1_FEVCOMPTOTXREQUEST
	WSDATA   oWSWSFEV1FECOMPULTIMOAUTORIZADORESULT AS WSFEV1_LASTCOMPWSFE
	WSDATA   oWSWSFEV1FECONSULTARPTOSVENCAEARESULT AS WSFEV1_IDARG
	WSDATA   cMONID                    AS string
	WSDATA   cFchCotiz                  AS string
	WSDATA   oWSWSFEV1FEPARAMGETCOTIZACIONRESULT AS WSFEV1_FEVPARAMCTZ
	WSDATA   oWSWSFEV1FEPARAMGETPTOSVENTARESULT AS WSFEV1_FEVGETPTOVENTA
	WSDATA   oWSWSFEV1FEPARAMGETTIPOSCBTERESULT AS WSFEV1_GETTIPO
	WSDATA   oWSWSFEV1FEPARAMGETTIPOSCONCEPTORESULT AS WSFEV1_GETTIPO
	WSDATA   oWSWSFEV1FEPARAMGETTIPOSDOCRESULT AS WSFEV1_GETTIPO
	WSDATA   oWSWSFEV1FEPARAMGETTIPOSIVARESULT AS WSFEV1_GETTIPO
	WSDATA   oWSWSFEV1FEPARAMGETTIPOSMONEDASRESULT AS WSFEV1_GETTIPO
	WSDATA   oWSWSFEV1FEPARAMGETTIPOSOPCIONALRESULT AS WSFEV1_GETTIPO
	WSDATA   oWSWSFEV1FEPARAMGETTIPOSTRIBUTOSRESULT AS WSFEV1_GETTIPO
	WSDATA   dDATADESDE                AS date
	WSDATA   dDATAATE                  AS date
	WSDATA   oWSWSMTXCAEACONSULTARRESULT AS WSFEV1_FEVCAEASOLIC
	WSDATA   oWSWSMTXCAEASOLICITARRESULT AS WSFEV1_FEVCAEASOLIC

	// Estruturas mantidas por compatibilidade - NÃO USAR
	WSDATA   oWSARRNOTASARG            AS WSFEV1_ARRNOTASARG
   //	WSDATA   oWSGETCMP                 AS WSFEV1_GETCMP

ENDWSCLIENT

WSMETHOD NEW WSCLIENT WSWSFEV1
::Init()
If !FindFunction("XMLCHILDEX")
	UserException("O Código-Fonte Client atual requer os executáveis do Protheus Build [7.00.090818P-20100401] ou superior. Atualize o Protheus ou gere o Código-Fonte novamente utilizando o Build atual.")
EndIf
Return Self

WSMETHOD INIT WSCLIENT WSWSFEV1
	::oWSDUMMYARGWSFEV1RESULT := WSFEV1_DUMMYWSFE():New()
	::oWSMONITORLOCRESULT := WSFEV1_MONITORWSFE():New()
	::oWSNFEARG          := WSFEV1_ARRNOTASARG():New()
	::oWSREMESSAWSFERESULT := WSFEV1_IDARG():New()
	::oWSWSFEV1FECAEACONSULTARRESULT := WSFEV1_FEVCAEASOLIC():New()
	::oWSWSFEV1FECAEAINFORMARCOMPROBANTERESULT := WSFEV1_IDARG():New()
	::oWSWSFEV1FECAEAREGINFORMATIVORESULT := WSFEV1_IDARG():New()
	::oWSWSFEV1FECAEASINMOVIMIENTOCONSULTARRESULT := WSFEV1_FEVSINMOVCONSRESULT():New()
	::oWSWSFEV1FECAEASINMOVIMIENTOINFORMARRESULT := WSFEV1_FEVSINMOVINFRESULT():New()
	::oWSWSFEV1FECAEASOLICITARRESULT := WSFEV1_FEVCAEASOLIC():New()
	::oWSGETCMP          := WSFEV1_GETCMP():New()
	::oWSWSFEV1FECOMPCONSULTARRESULT := WSFEV1_RESULTCOMPCONS():New()
	::oWSWSFEV1FECOMPTOTXREQUESTRESULT := WSFEV1_FEVCOMPTOTXREQUEST():New()
	::oWSWSFEV1FECOMPULTIMOAUTORIZADORESULT := WSFEV1_LASTCOMPWSFE():New()
	::oWSWSFEV1FECONSULTARPTOSVENCAEARESULT := WSFEV1_IDARG():New()
	::oWSWSFEV1FEPARAMGETCOTIZACIONRESULT := WSFEV1_FEVPARAMCTZ():New()
	::oWSWSFEV1FEPARAMGETPTOSVENTARESULT := WSFEV1_FEVGETPTOVENTA():New()
	::oWSWSFEV1FEPARAMGETTIPOSCBTERESULT := WSFEV1_GETTIPO():New()
	::oWSWSFEV1FEPARAMGETTIPOSCONCEPTORESULT := WSFEV1_GETTIPO():New()
	::oWSWSFEV1FEPARAMGETTIPOSDOCRESULT := WSFEV1_GETTIPO():New()
	::oWSWSFEV1FEPARAMGETTIPOSIVARESULT := WSFEV1_GETTIPO():New()
	::oWSWSFEV1FEPARAMGETTIPOSMONEDASRESULT := WSFEV1_GETTIPO():New()
	::oWSWSFEV1FEPARAMGETTIPOSOPCIONALRESULT := WSFEV1_GETTIPO():New()
	::oWSWSFEV1FEPARAMGETTIPOSTRIBUTOSRESULT := WSFEV1_GETTIPO():New()
	::oWSWSMTXCAEACONSULTARRESULT := WSFEV1_FEVCAEASOLIC():New()
	::oWSWSMTXCAEASOLICITARRESULT := WSFEV1_FEVCAEASOLIC():New()

	// Estruturas mantidas por compatibilidade - NÃO USAR
	::oWSARRNOTASARG     := ::oWSNFEARG
	::oWSGETCMP          := ::oWSGETCMP
Return

WSMETHOD RESET WSCLIENT WSWSFEV1
	::cUSERTOKEN         := NIL 
	::cID_ENT            := NIL 
	::cMODELOWS          := NIL 
	::oWSDUMMYARGWSFEV1RESULT := NIL 
	::cIDINICIAL         := NIL 
	::cIDFINAL           := NIL 
	::oWSMONITORLOCRESULT := NIL 
	::cMODELO            := NIL 
	::nPTOVTA            := NIL 
	::nCBTETIPO          := NIL 
	::oWSNFEARG          := NIL 
	::oWSREMESSAWSFERESULT := NIL 
	::nPERIODO           := NIL 
	::nORDEN             := NIL 
	::oWSWSFEV1FECAEACONSULTARRESULT := NIL 
	::oWSWSFEV1FECAEAINFORMARCOMPROBANTERESULT := NIL 
	::oWSWSFEV1FECAEAREGINFORMATIVORESULT := NIL 
	::cCAEA              := NIL 
	::oWSWSFEV1FECAEASINMOVIMIENTOCONSULTARRESULT := NIL 
	::oWSWSFEV1FECAEASINMOVIMIENTOINFORMARRESULT := NIL 
	::oWSWSFEV1FECAEASOLICITARRESULT := NIL 
	::oWSGETCMP          := NIL 
	::oWSWSFEV1FECOMPCONSULTARRESULT := NIL 
	::oWSWSFEV1FECOMPTOTXREQUESTRESULT := NIL 
	::oWSWSFEV1FECOMPULTIMOAUTORIZADORESULT := NIL 
	::oWSWSFEV1FECONSULTARPTOSVENCAEARESULT := NIL 
	::cMONID             := NIL 
	::oWSWSFEV1FEPARAMGETCOTIZACIONRESULT := NIL 
	::oWSWSFEV1FEPARAMGETPTOSVENTARESULT := NIL 
	::oWSWSFEV1FEPARAMGETTIPOSCBTERESULT := NIL 
	::oWSWSFEV1FEPARAMGETTIPOSCONCEPTORESULT := NIL 
	::oWSWSFEV1FEPARAMGETTIPOSDOCRESULT := NIL 
	::oWSWSFEV1FEPARAMGETTIPOSIVARESULT := NIL 
	::oWSWSFEV1FEPARAMGETTIPOSMONEDASRESULT := NIL 
	::oWSWSFEV1FEPARAMGETTIPOSOPCIONALRESULT := NIL 
	::oWSWSFEV1FEPARAMGETTIPOSTRIBUTOSRESULT := NIL 
	::dDATADESDE         := NIL 
	::dDATAATE           := NIL 
	::oWSWSMTXCAEACONSULTARRESULT := NIL 
	::oWSWSMTXCAEASOLICITARRESULT := NIL 

	// Estruturas mantidas por compatibilidade - NÃO USAR
	::oWSARRNOTASARG     := NIL
	::oWSGETCMP          := NIL
	::Init()
Return

WSMETHOD CLONE WSCLIENT WSWSFEV1
Local oClone := WSWSFEV1():New()
	oClone:_URL          := ::_URL 
	oClone:cUSERTOKEN    := ::cUSERTOKEN
	oClone:cID_ENT       := ::cID_ENT
	oClone:cMODELOWS     := ::cMODELOWS
	oClone:oWSDUMMYARGWSFEV1RESULT :=  IIF(::oWSDUMMYARGWSFEV1RESULT = NIL , NIL ,::oWSDUMMYARGWSFEV1RESULT:Clone() )
	oClone:cIDINICIAL    := ::cIDINICIAL
	oClone:cIDFINAL      := ::cIDFINAL
	oClone:oWSMONITORLOCRESULT :=  IIF(::oWSMONITORLOCRESULT = NIL , NIL ,::oWSMONITORLOCRESULT:Clone() )
	oClone:cMODELO       := ::cMODELO
	oClone:nPTOVTA       := ::nPTOVTA
	oClone:nCBTETIPO     := ::nCBTETIPO
	oClone:oWSNFEARG     :=  IIF(::oWSNFEARG = NIL , NIL ,::oWSNFEARG:Clone() )
	oClone:oWSREMESSAWSFERESULT :=  IIF(::oWSREMESSAWSFERESULT = NIL , NIL ,::oWSREMESSAWSFERESULT:Clone() )
	oClone:nPERIODO      := ::nPERIODO
	oClone:nORDEN        := ::nORDEN
	oClone:oWSWSFEV1FECAEACONSULTARRESULT :=  IIF(::oWSWSFEV1FECAEACONSULTARRESULT = NIL , NIL ,::oWSWSFEV1FECAEACONSULTARRESULT:Clone() )
	oClone:oWSWSFEV1FECAEAINFORMARCOMPROBANTERESULT :=  IIF(::oWSWSFEV1FECAEAINFORMARCOMPROBANTERESULT = NIL , NIL ,::oWSWSFEV1FECAEAINFORMARCOMPROBANTERESULT:Clone() )
	oClone:oWSWSFEV1FECAEAREGINFORMATIVORESULT :=  IIF(::oWSWSFEV1FECAEAREGINFORMATIVORESULT = NIL , NIL ,::oWSWSFEV1FECAEAREGINFORMATIVORESULT:Clone() )
	oClone:cCAEA         := ::cCAEA
	oClone:oWSWSFEV1FECAEASINMOVIMIENTOCONSULTARRESULT :=  IIF(::oWSWSFEV1FECAEASINMOVIMIENTOCONSULTARRESULT = NIL , NIL ,::oWSWSFEV1FECAEASINMOVIMIENTOCONSULTARRESULT:Clone() )
	oClone:oWSWSFEV1FECAEASINMOVIMIENTOINFORMARRESULT :=  IIF(::oWSWSFEV1FECAEASINMOVIMIENTOINFORMARRESULT = NIL , NIL ,::oWSWSFEV1FECAEASINMOVIMIENTOINFORMARRESULT:Clone() )
	oClone:oWSWSFEV1FECAEASOLICITARRESULT :=  IIF(::oWSWSFEV1FECAEASOLICITARRESULT = NIL , NIL ,::oWSWSFEV1FECAEASOLICITARRESULT:Clone() )
	oClone:oWSGETCMP     :=  IIF(::oWSGETCMP = NIL , NIL ,::oWSGETCMP:Clone() )
	oClone:oWSWSFEV1FECOMPCONSULTARRESULT :=  IIF(::oWSWSFEV1FECOMPCONSULTARRESULT = NIL , NIL ,::oWSWSFEV1FECOMPCONSULTARRESULT:Clone() )
	oClone:oWSWSFEV1FECOMPTOTXREQUESTRESULT :=  IIF(::oWSWSFEV1FECOMPTOTXREQUESTRESULT = NIL , NIL ,::oWSWSFEV1FECOMPTOTXREQUESTRESULT:Clone() )
	oClone:oWSWSFEV1FECOMPULTIMOAUTORIZADORESULT :=  IIF(::oWSWSFEV1FECOMPULTIMOAUTORIZADORESULT = NIL , NIL ,::oWSWSFEV1FECOMPULTIMOAUTORIZADORESULT:Clone() )
	oClone:oWSWSFEV1FECONSULTARPTOSVENCAEARESULT :=  IIF(::oWSWSFEV1FECONSULTARPTOSVENCAEARESULT = NIL , NIL ,::oWSWSFEV1FECONSULTARPTOSVENCAEARESULT:Clone() )
	oClone:cMONID        := ::cMONID
	oClone:oWSWSFEV1FEPARAMGETCOTIZACIONRESULT :=  IIF(::oWSWSFEV1FEPARAMGETCOTIZACIONRESULT = NIL , NIL ,::oWSWSFEV1FEPARAMGETCOTIZACIONRESULT:Clone() )
	oClone:oWSWSFEV1FEPARAMGETPTOSVENTARESULT :=  IIF(::oWSWSFEV1FEPARAMGETPTOSVENTARESULT = NIL , NIL ,::oWSWSFEV1FEPARAMGETPTOSVENTARESULT:Clone() )
	oClone:oWSWSFEV1FEPARAMGETTIPOSCBTERESULT :=  IIF(::oWSWSFEV1FEPARAMGETTIPOSCBTERESULT = NIL , NIL ,::oWSWSFEV1FEPARAMGETTIPOSCBTERESULT:Clone() )
	oClone:oWSWSFEV1FEPARAMGETTIPOSCONCEPTORESULT :=  IIF(::oWSWSFEV1FEPARAMGETTIPOSCONCEPTORESULT = NIL , NIL ,::oWSWSFEV1FEPARAMGETTIPOSCONCEPTORESULT:Clone() )
	oClone:oWSWSFEV1FEPARAMGETTIPOSDOCRESULT :=  IIF(::oWSWSFEV1FEPARAMGETTIPOSDOCRESULT = NIL , NIL ,::oWSWSFEV1FEPARAMGETTIPOSDOCRESULT:Clone() )
	oClone:oWSWSFEV1FEPARAMGETTIPOSIVARESULT :=  IIF(::oWSWSFEV1FEPARAMGETTIPOSIVARESULT = NIL , NIL ,::oWSWSFEV1FEPARAMGETTIPOSIVARESULT:Clone() )
	oClone:oWSWSFEV1FEPARAMGETTIPOSMONEDASRESULT :=  IIF(::oWSWSFEV1FEPARAMGETTIPOSMONEDASRESULT = NIL , NIL ,::oWSWSFEV1FEPARAMGETTIPOSMONEDASRESULT:Clone() )
	oClone:oWSWSFEV1FEPARAMGETTIPOSOPCIONALRESULT :=  IIF(::oWSWSFEV1FEPARAMGETTIPOSOPCIONALRESULT = NIL , NIL ,::oWSWSFEV1FEPARAMGETTIPOSOPCIONALRESULT:Clone() )
	oClone:oWSWSFEV1FEPARAMGETTIPOSTRIBUTOSRESULT :=  IIF(::oWSWSFEV1FEPARAMGETTIPOSTRIBUTOSRESULT = NIL , NIL ,::oWSWSFEV1FEPARAMGETTIPOSTRIBUTOSRESULT:Clone() )
	oClone:dDATADESDE    := ::dDATADESDE
	oClone:dDATAATE      := ::dDATAATE
	oClone:oWSWSMTXCAEACONSULTARRESULT :=  IIF(::oWSWSMTXCAEACONSULTARRESULT = NIL , NIL ,::oWSWSMTXCAEACONSULTARRESULT:Clone() )
	oClone:oWSWSMTXCAEASOLICITARRESULT :=  IIF(::oWSWSMTXCAEASOLICITARRESULT = NIL , NIL ,::oWSWSMTXCAEASOLICITARRESULT:Clone() )

	// Estruturas mantidas por compatibilidade - NÃO USAR
	oClone:oWSARRNOTASARG := oClone:oWSNFEARG
	oClone:oWSGETCMP     := oClone:oWSGETCMP
Return oClone

// WSDL Method DUMMYARGWSFEV1 of Service WSWSFEV1

WSMETHOD DUMMYARGWSFEV1 WSSEND cUSERTOKEN,cID_ENT,cMODELOWS WSRECEIVE oWSDUMMYARGWSFEV1RESULT WSCLIENT WSWSFEV1
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<DUMMYARGWSFEV1 xmlns="http://172.16.33.49:8070/">'
cSoap += WSSoapValue("USERTOKEN", ::cUSERTOKEN, cUSERTOKEN , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("ID_ENT", ::cID_ENT, cID_ENT , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("MODELOWS", ::cMODELOWS, cMODELOWS , "string", .F. , .F., 0 , NIL, .F.,.F.) 
cSoap += "</DUMMYARGWSFEV1>"

oXmlRet := SvcSoapCall(	ObjSelf(Self),cSoap,; 
	"http://172.16.33.49:8070/DUMMYARGWSFEV1",; 
	"DOCUMENT","http://172.16.33.49:8070/",,"1.031217",; 
	"http://172.16.33.49:8070/WSFEV1.apw")

::Init()
::oWSDUMMYARGWSFEV1RESULT:SoapRecv( WSAdvValue( oXmlRet,"_DUMMYARGWSFEV1RESPONSE:_DUMMYARGWSFEV1RESULT","DUMMYWSFE",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.

// WSDL Method MONITORLOC of Service WSWSFEV1

WSMETHOD MONITORLOC WSSEND cUSERTOKEN,cID_ENT,cIDINICIAL,cIDFINAL WSRECEIVE oWSMONITORLOCRESULT WSCLIENT WSWSFEV1
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<MONITORLOC xmlns="http://172.16.33.49:8070/">'
cSoap += WSSoapValue("USERTOKEN", ::cUSERTOKEN, cUSERTOKEN , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("ID_ENT", ::cID_ENT, cID_ENT , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("IDINICIAL", ::cIDINICIAL, cIDINICIAL , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("IDFINAL", ::cIDFINAL, cIDFINAL , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += "</MONITORLOC>"

oXmlRet := SvcSoapCall(	ObjSelf(Self),cSoap,; 
	"http://172.16.33.49:8070/MONITORLOC",; 
	"DOCUMENT","http://172.16.33.49:8070/",,"1.031217",; 
	"http://172.16.33.49:8070/WSFEV1.apw")

::Init()
::oWSMONITORLOCRESULT:SoapRecv( WSAdvValue( oXmlRet,"_MONITORLOCRESPONSE:_MONITORLOCRESULT","MONITORWSFE",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.

// WSDL Method REMESSAWSFE of Service WSWSFEV1

WSMETHOD REMESSAWSFE WSSEND cUSERTOKEN,cID_ENT,cMODELO,nPTOVTA,nCBTETIPO,oWSNFEARG WSRECEIVE oWSREMESSAWSFERESULT WSCLIENT WSWSFEV1
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<REMESSAWSFE xmlns="http://172.16.33.49:8070/">'
cSoap += WSSoapValue("USERTOKEN", ::cUSERTOKEN, cUSERTOKEN , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("ID_ENT", ::cID_ENT, cID_ENT , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("MODELO", ::cMODELO, cMODELO , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("PTOVTA", ::nPTOVTA, nPTOVTA , "integer", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("CBTETIPO", ::nCBTETIPO, nCBTETIPO , "integer", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("NFEARG", ::oWSNFEARG, oWSNFEARG , "ARRNOTASARG", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += "</REMESSAWSFE>"

oXmlRet := SvcSoapCall(	ObjSelf(Self),cSoap,; 
	"http://172.16.33.49:8070/REMESSAWSFE",; 
	"DOCUMENT","http://172.16.33.49:8070/",,"1.031217",; 
	"http://172.16.33.49:8070/WSFEV1.apw")

::Init()
::oWSREMESSAWSFERESULT:SoapRecv( WSAdvValue( oXmlRet,"_REMESSAWSFERESPONSE:_REMESSAWSFERESULT","IDARG",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.

// WSDL Method WSFEV1FECAEACONSULTAR of Service WSWSFEV1

WSMETHOD WSFEV1FECAEACONSULTAR WSSEND cUSERTOKEN,cID_ENT,nPERIODO,nORDEN WSRECEIVE oWSWSFEV1FECAEACONSULTARRESULT WSCLIENT WSWSFEV1
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<WSFEV1FECAEACONSULTAR xmlns="http://172.16.33.49:8070/">'
cSoap += WSSoapValue("USERTOKEN", ::cUSERTOKEN, cUSERTOKEN , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("ID_ENT", ::cID_ENT, cID_ENT , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("PERIODO", ::nPERIODO, nPERIODO , "integer", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("ORDEN", ::nORDEN, nORDEN , "integer", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += "</WSFEV1FECAEACONSULTAR>"

oXmlRet := SvcSoapCall(	ObjSelf(Self),cSoap,; 
	"http://172.16.33.49:8070/WSFEV1FECAEACONSULTAR",; 
	"DOCUMENT","http://172.16.33.49:8070/",,"1.031217",; 
	"http://172.16.33.49:8070/WSFEV1.apw")

::Init()
::oWSWSFEV1FECAEACONSULTARRESULT:SoapRecv( WSAdvValue( oXmlRet,"_WSFEV1FECAEACONSULTARRESPONSE:_WSFEV1FECAEACONSULTARRESULT","FEVCAEASOLIC",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.

// WSDL Method WSFEV1FECAEAINFORMARCOMPROBANTE of Service WSWSFEV1

WSMETHOD WSFEV1FECAEAINFORMARCOMPROBANTE WSSEND cUSERTOKEN,cID_ENT,cMODELO,nPTOVTA,nCBTETIPO,oWSNFEARG WSRECEIVE oWSWSFEV1FECAEAINFORMARCOMPROBANTERESULT WSCLIENT WSWSFEV1
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<WSFEV1FECAEAINFORMARCOMPROBANTE xmlns="http://172.16.33.49:8070/">'
cSoap += WSSoapValue("USERTOKEN", ::cUSERTOKEN, cUSERTOKEN , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("ID_ENT", ::cID_ENT, cID_ENT , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("MODELO", ::cMODELO, cMODELO , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("PTOVTA", ::nPTOVTA, nPTOVTA , "integer", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("CBTETIPO", ::nCBTETIPO, nCBTETIPO , "integer", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("NFEARG", ::oWSNFEARG, oWSNFEARG , "ARRNOTASARG", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += "</WSFEV1FECAEAINFORMARCOMPROBANTE>"

oXmlRet := SvcSoapCall(ObjSelf(Self),cSoap,; 
	"http://172.16.33.49:8070/WSFEV1FECAEAINFORMARCOMPROBANTE",; 
	"DOCUMENT","http://172.16.33.49:8070/",,"1.031217",; 
	"http://172.16.33.49:8070/WSFEV1.apw")

::Init()
::oWSWSFEV1FECAEAINFORMARCOMPROBANTERESULT:SoapRecv( WSAdvValue( oXmlRet,"_WSFEV1FECAEAINFORMARCOMPROBANTERESPONSE:_WSFEV1FECAEAINFORMARCOMPROBANTERESULT","IDARG",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.

// WSDL Method WSFEV1FECAEAREGINFORMATIVO of Service WSWSFEV1

WSMETHOD WSFEV1FECAEAREGINFORMATIVO WSSEND cUSERTOKEN,cID_ENT,cMODELO,nPTOVTA,nCBTETIPO,oWSNFEARG WSRECEIVE oWSWSFEV1FECAEAREGINFORMATIVORESULT WSCLIENT WSWSFEV1
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<WSFEV1FECAEAREGINFORMATIVO xmlns="http://172.16.33.49:8070/">'
cSoap += WSSoapValue("USERTOKEN", ::cUSERTOKEN, cUSERTOKEN , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("ID_ENT", ::cID_ENT, cID_ENT , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("MODELO", ::cMODELO, cMODELO , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("PTOVTA", ::nPTOVTA, nPTOVTA , "integer", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("CBTETIPO", ::nCBTETIPO, nCBTETIPO , "integer", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("NFEARG", ::oWSNFEARG, oWSNFEARG , "ARRNOTASARG", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += "</WSFEV1FECAEAREGINFORMATIVO>"

oXmlRet := SvcSoapCall(	ObjSelf(Self),cSoap,; 
	"http://172.16.33.49:8070/WSFEV1FECAEAREGINFORMATIVO",; 
	"DOCUMENT","http://172.16.33.49:8070/",,"1.031217",; 
	"http://172.16.33.49:8070/WSFEV1.apw")

::Init()
::oWSWSFEV1FECAEAREGINFORMATIVORESULT:SoapRecv( WSAdvValue( oXmlRet,"_WSFEV1FECAEAREGINFORMATIVORESPONSE:_WSFEV1FECAEAREGINFORMATIVORESULT","IDARG",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.

// WSDL Method WSFEV1FECAEASINMOVIMIENTOCONSULTAR of Service WSWSFEV1

WSMETHOD WSFEV1FECAEASINMOVIMIENTOCONSULTAR WSSEND cUSERTOKEN,cID_ENT,cCAEA,nPTOVTA WSRECEIVE oWSWSFEV1FECAEASINMOVIMIENTOCONSULTARRESULT WSCLIENT WSWSFEV1
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<WSFEV1FECAEASINMOVIMIENTOCONSULTAR xmlns="http://172.16.33.49:8070/">'
cSoap += WSSoapValue("USERTOKEN", ::cUSERTOKEN, cUSERTOKEN , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("ID_ENT", ::cID_ENT, cID_ENT , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("CAEA", ::cCAEA, cCAEA , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("PTOVTA", ::nPTOVTA, nPTOVTA , "integer", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += "</WSFEV1FECAEASINMOVIMIENTOCONSULTAR>"

oXmlRet := SvcSoapCall(	ObjSelf(Self),cSoap,; 
	"http://172.16.33.49:8070/WSFEV1FECAEASINMOVIMIENTOCONSULTAR",; 
	"DOCUMENT","http://172.16.33.49:8070/",,"1.031217",; 
	"http://172.16.33.49:8070/WSFEV1.apw")

::Init()
::oWSWSFEV1FECAEASINMOVIMIENTOCONSULTARRESULT:SoapRecv( WSAdvValue( oXmlRet,"_WSFEV1FECAEASINMOVIMIENTOCONSULTARRESPONSE:_WSFEV1FECAEASINMOVIMIENTOCONSULTARRESULT","FEVSINMOVCONSRESULT",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.

// WSDL Method WSFEV1FECAEASINMOVIMIENTOINFORMAR of Service WSWSFEV1

WSMETHOD WSFEV1FECAEASINMOVIMIENTOINFORMAR WSSEND cUSERTOKEN,cID_ENT,cCAEA,nPTOVTA WSRECEIVE oWSWSFEV1FECAEASINMOVIMIENTOINFORMARRESULT WSCLIENT WSWSFEV1
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<WSFEV1FECAEASINMOVIMIENTOINFORMAR xmlns="http://172.16.33.49:8070/">'
cSoap += WSSoapValue("USERTOKEN", ::cUSERTOKEN, cUSERTOKEN , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("ID_ENT", ::cID_ENT, cID_ENT , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("CAEA", ::cCAEA, cCAEA , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("PTOVTA", ::nPTOVTA, nPTOVTA , "integer", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += "</WSFEV1FECAEASINMOVIMIENTOINFORMAR>"

oXmlRet := SvcSoapCall(	ObjSelf(Self),cSoap,; 
	"http://172.16.33.49:8070/WSFEV1FECAEASINMOVIMIENTOINFORMAR",; 
	"DOCUMENT","http://172.16.33.49:8070/",,"1.031217",; 
	"http://172.16.33.49:8070/WSFEV1.apw")

::Init()
::oWSWSFEV1FECAEASINMOVIMIENTOINFORMARRESULT:SoapRecv( WSAdvValue( oXmlRet,"_WSFEV1FECAEASINMOVIMIENTOINFORMARRESPONSE:_WSFEV1FECAEASINMOVIMIENTOINFORMARRESULT","FEVSINMOVINFRESULT",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.

// WSDL Method WSFEV1FECAEASOLICITAR of Service WSWSFEV1

WSMETHOD WSFEV1FECAEASOLICITAR WSSEND cUSERTOKEN,cID_ENT,nPERIODO,nORDEN WSRECEIVE oWSWSFEV1FECAEASOLICITARRESULT WSCLIENT WSWSFEV1
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<WSFEV1FECAEASOLICITAR xmlns="http://172.16.33.49:8070/">'
cSoap += WSSoapValue("USERTOKEN", ::cUSERTOKEN, cUSERTOKEN , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("ID_ENT", ::cID_ENT, cID_ENT , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("PERIODO", ::nPERIODO, nPERIODO , "integer", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("ORDEN", ::nORDEN, nORDEN , "integer", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += "</WSFEV1FECAEASOLICITAR>"

oXmlRet := SvcSoapCall(	ObjSelf(Self),cSoap,; 
	"http://172.16.33.49:8070/WSFEV1FECAEASOLICITAR",; 
	"DOCUMENT","http://172.16.33.49:8070/",,"1.031217",; 
	"http://172.16.33.49:8070/WSFEV1.apw")

::Init()
::oWSWSFEV1FECAEASOLICITARRESULT:SoapRecv( WSAdvValue( oXmlRet,"_WSFEV1FECAEASOLICITARRESPONSE:_WSFEV1FECAEASOLICITARRESULT","FEVCAEASOLIC",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.

// WSDL Method WSFEV1FECOMPCONSULTAR of Service WSWSFEV1

WSMETHOD WSFEV1FECOMPCONSULTAR WSSEND cUSERTOKEN,cID_ENT,oWSGETCMP,cMODELOWS WSRECEIVE oWSWSFEV1FECOMPCONSULTARRESULT WSCLIENT WSWSFEV1
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<WSFEV1FECOMPCONSULTAR xmlns="http://172.16.33.49:8070/">'
cSoap += WSSoapValue("USERTOKEN", ::cUSERTOKEN, cUSERTOKEN , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("ID_ENT", ::cID_ENT, cID_ENT , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("GETCMP", ::oWSGETCMP, oWSGETCMP , "GETCMP", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("MODELOWS", ::cMODELOWS, cMODELOWS , "string", .F. , .F., 0 , NIL, .F.,.F.) 
cSoap += "</WSFEV1FECOMPCONSULTAR>"

oXmlRet := SvcSoapCall(	ObjSelf(Self),cSoap,; 
	"http://172.16.33.49:8070/WSFEV1FECOMPCONSULTAR",; 
	"DOCUMENT","http://172.16.33.49:8070/",,"1.031217",; 
	"http://172.16.33.49:8070/WSFEV1.apw")

::Init()
::oWSWSFEV1FECOMPCONSULTARRESULT:SoapRecv( WSAdvValue( oXmlRet,"_WSFEV1FECOMPCONSULTARRESPONSE:_WSFEV1FECOMPCONSULTARRESULT","RESULTCOMPCONS",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.

// WSDL Method WSFEV1FECOMPTOTXREQUEST of Service WSWSFEV1

WSMETHOD WSFEV1FECOMPTOTXREQUEST WSSEND cUSERTOKEN,cID_ENT WSRECEIVE oWSWSFEV1FECOMPTOTXREQUESTRESULT WSCLIENT WSWSFEV1
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<WSFEV1FECOMPTOTXREQUEST xmlns="http://172.16.33.49:8070/">'
cSoap += WSSoapValue("USERTOKEN", ::cUSERTOKEN, cUSERTOKEN , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("ID_ENT", ::cID_ENT, cID_ENT , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += "</WSFEV1FECOMPTOTXREQUEST>"

oXmlRet := SvcSoapCall(	ObjSelf(Self),cSoap,; 
	"http://172.16.33.49:8070/WSFEV1FECOMPTOTXREQUEST",; 
	"DOCUMENT","http://172.16.33.49:8070/",,"1.031217",; 
	"http://172.16.33.49:8070/WSFEV1.apw")

::Init()
::oWSWSFEV1FECOMPTOTXREQUESTRESULT:SoapRecv( WSAdvValue( oXmlRet,"_WSFEV1FECOMPTOTXREQUESTRESPONSE:_WSFEV1FECOMPTOTXREQUESTRESULT","FEVCOMPTOTXREQUEST",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.

// WSDL Method WSFEV1FECOMPULTIMOAUTORIZADO of Service WSWSFEV1

WSMETHOD WSFEV1FECOMPULTIMOAUTORIZADO WSSEND cUSERTOKEN,cID_ENT,nPTOVTA,nCBTETIPO,cMODELOWS WSRECEIVE oWSWSFEV1FECOMPULTIMOAUTORIZADORESULT WSCLIENT WSWSFEV1
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<WSFEV1FECOMPULTIMOAUTORIZADO xmlns="http://172.16.33.49:8070/">'
cSoap += WSSoapValue("USERTOKEN", ::cUSERTOKEN, cUSERTOKEN , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("ID_ENT", ::cID_ENT, cID_ENT , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("PTOVTA", ::nPTOVTA, nPTOVTA , "integer", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("CBTETIPO", ::nCBTETIPO, nCBTETIPO , "integer", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("MODELOWS", ::cMODELOWS, cMODELOWS , "string", .F. , .F., 0 , NIL, .F.,.F.) 
cSoap += "</WSFEV1FECOMPULTIMOAUTORIZADO>"

oXmlRet := SvcSoapCall(	ObjSelf(Self),cSoap,; 
	"http://172.16.33.49:8070/WSFEV1FECOMPULTIMOAUTORIZADO",; 
	"DOCUMENT","http://172.16.33.49:8070/",,"1.031217",; 
	"http://172.16.33.49:8070/WSFEV1.apw")

::Init()
::oWSWSFEV1FECOMPULTIMOAUTORIZADORESULT:SoapRecv( WSAdvValue( oXmlRet,"_WSFEV1FECOMPULTIMOAUTORIZADORESPONSE:_WSFEV1FECOMPULTIMOAUTORIZADORESULT","LASTCOMPWSFE",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.

// WSDL Method WSFEV1FECONSULTARPTOSVENCAEA of Service WSWSFEV1

WSMETHOD WSFEV1FECONSULTARPTOSVENCAEA WSSEND cUSERTOKEN,cID_ENT,nPTOVTA WSRECEIVE oWSWSFEV1FECONSULTARPTOSVENCAEARESULT WSCLIENT WSWSFEV1
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<WSFEV1FECONSULTARPTOSVENCAEA xmlns="http://172.16.33.49:8070/">'
cSoap += WSSoapValue("USERTOKEN", ::cUSERTOKEN, cUSERTOKEN , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("ID_ENT", ::cID_ENT, cID_ENT , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("PTOVTA", ::nPTOVTA, nPTOVTA , "integer", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += "</WSFEV1FECONSULTARPTOSVENCAEA>"

oXmlRet := SvcSoapCall( ObjSelf(Self),cSoap,; 
	"http://172.16.33.49:8070/WSFEV1FECONSULTARPTOSVENCAEA",; 
	"DOCUMENT","http://172.16.33.49:8070/",,"1.031217",; 
	"http://172.16.33.49:8070/WSFEV1.apw")

::Init()
::oWSWSFEV1FECONSULTARPTOSVENCAEARESULT:SoapRecv( WSAdvValue( oXmlRet,"_WSFEV1FECONSULTARPTOSVENCAEARESPONSE:_WSFEV1FECONSULTARPTOSVENCAEARESULT","IDARG",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.

// WSDL Method WSFEV1FEPARAMGETCOTIZACION of Service WSWSFEV1

WSMETHOD WSFEV1FEPARAMGETCOTIZACION WSSEND cUSERTOKEN,cID_ENT,cMONID,cFchCotiz WSRECEIVE oWSWSFEV1FEPARAMGETCOTIZACIONRESULT WSCLIENT WSWSFEV1
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<WSFEV1FEPARAMGETCOTIZACION xmlns="http://172.16.33.49:8070/">'
cSoap += WSSoapValue("USERTOKEN", ::cUSERTOKEN, cUSERTOKEN , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("ID_ENT", ::cID_ENT, cID_ENT , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("MONID", ::cMONID, cMONID , "string", .T. , .F., 0 , NIL, .F.,.F.)
cSoap += WSSoapValue("FCHCOTIZ", ::cFchCotiz, cFchCotiz , "string", .T. , .F., 0 , NIL, .F.,.F.)  
cSoap += "</WSFEV1FEPARAMGETCOTIZACION>"

oXmlRet := SvcSoapCall(ObjSelf(Self),cSoap,; 
	"http://localhost:8087/WSFEV1FEPARAMGETCOTIZACION",; 
	"DOCUMENT","http://localhost:8087/",,"1.031217",; 
	"http://localhost:8087/WSFEV1.apw")

::Init()
::oWSWSFEV1FEPARAMGETCOTIZACIONRESULT:SoapRecv( WSAdvValue( oXmlRet,"_WSFEV1FEPARAMGETCOTIZACIONRESPONSE:_WSFEV1FEPARAMGETCOTIZACIONRESULT","FEVPARAMCTZ",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.

// WSDL Method WSFEV1FEPARAMGETPTOSVENTA of Service WSWSFEV1

WSMETHOD WSFEV1FEPARAMGETPTOSVENTA WSSEND cUSERTOKEN,cID_ENT WSRECEIVE oWSWSFEV1FEPARAMGETPTOSVENTARESULT WSCLIENT WSWSFEV1
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<WSFEV1FEPARAMGETPTOSVENTA xmlns="http://172.16.33.49:8070/">'
cSoap += WSSoapValue("USERTOKEN", ::cUSERTOKEN, cUSERTOKEN , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("ID_ENT", ::cID_ENT, cID_ENT , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += "</WSFEV1FEPARAMGETPTOSVENTA>"

oXmlRet := SvcSoapCall(	ObjSelf(Self),cSoap,; 
	"http://172.16.33.49:8070/WSFEV1FEPARAMGETPTOSVENTA",; 
	"DOCUMENT","http://172.16.33.49:8070/",,"1.031217",; 
	"http://172.16.33.49:8070/WSFEV1.apw")

::Init()
::oWSWSFEV1FEPARAMGETPTOSVENTARESULT:SoapRecv( WSAdvValue( oXmlRet,"_WSFEV1FEPARAMGETPTOSVENTARESPONSE:_WSFEV1FEPARAMGETPTOSVENTARESULT","FEVGETPTOVENTA",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.

// WSDL Method WSFEV1FEPARAMGETTIPOSCBTE of Service WSWSFEV1

WSMETHOD WSFEV1FEPARAMGETTIPOSCBTE WSSEND cUSERTOKEN,cID_ENT WSRECEIVE oWSWSFEV1FEPARAMGETTIPOSCBTERESULT WSCLIENT WSWSFEV1
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<WSFEV1FEPARAMGETTIPOSCBTE xmlns="http://172.16.33.49:8070/">'
cSoap += WSSoapValue("USERTOKEN", ::cUSERTOKEN, cUSERTOKEN , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("ID_ENT", ::cID_ENT, cID_ENT , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += "</WSFEV1FEPARAMGETTIPOSCBTE>"

oXmlRet := SvcSoapCall(	ObjSelf(Self),cSoap,; 
	"http://172.16.33.49:8070/WSFEV1FEPARAMGETTIPOSCBTE",; 
	"DOCUMENT","http://172.16.33.49:8070/",,"1.031217",; 
	"http://172.16.33.49:8070/WSFEV1.apw")

::Init()
::oWSWSFEV1FEPARAMGETTIPOSCBTERESULT:SoapRecv( WSAdvValue( oXmlRet,"_WSFEV1FEPARAMGETTIPOSCBTERESPONSE:_WSFEV1FEPARAMGETTIPOSCBTERESULT","GETTIPO",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.

// WSDL Method WSFEV1FEPARAMGETTIPOSCONCEPTO of Service WSWSFEV1

WSMETHOD WSFEV1FEPARAMGETTIPOSCONCEPTO WSSEND cUSERTOKEN,cID_ENT WSRECEIVE oWSWSFEV1FEPARAMGETTIPOSCONCEPTORESULT WSCLIENT WSWSFEV1
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<WSFEV1FEPARAMGETTIPOSCONCEPTO xmlns="http://172.16.33.49:8070/">'
cSoap += WSSoapValue("USERTOKEN", ::cUSERTOKEN, cUSERTOKEN , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("ID_ENT", ::cID_ENT, cID_ENT , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += "</WSFEV1FEPARAMGETTIPOSCONCEPTO>"

oXmlRet := SvcSoapCall(	ObjSelf(Self),cSoap,; 
	"http://172.16.33.49:8070/WSFEV1FEPARAMGETTIPOSCONCEPTO",; 
	"DOCUMENT","http://172.16.33.49:8070/",,"1.031217",; 
	"http://172.16.33.49:8070/WSFEV1.apw")

::Init()
::oWSWSFEV1FEPARAMGETTIPOSCONCEPTORESULT:SoapRecv( WSAdvValue( oXmlRet,"_WSFEV1FEPARAMGETTIPOSCONCEPTORESPONSE:_WSFEV1FEPARAMGETTIPOSCONCEPTORESULT","GETTIPO",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.

// WSDL Method WSFEV1FEPARAMGETTIPOSDOC of Service WSWSFEV1

WSMETHOD WSFEV1FEPARAMGETTIPOSDOC WSSEND cUSERTOKEN,cID_ENT WSRECEIVE oWSWSFEV1FEPARAMGETTIPOSDOCRESULT WSCLIENT WSWSFEV1
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<WSFEV1FEPARAMGETTIPOSDOC xmlns="http://172.16.33.49:8070/">'
cSoap += WSSoapValue("USERTOKEN", ::cUSERTOKEN, cUSERTOKEN , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("ID_ENT", ::cID_ENT, cID_ENT , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += "</WSFEV1FEPARAMGETTIPOSDOC>"

oXmlRet := SvcSoapCall(	ObjSelf(Self),cSoap,; 
	"http://172.16.33.49:8070/WSFEV1FEPARAMGETTIPOSDOC",; 
	"DOCUMENT","http://172.16.33.49:8070/",,"1.031217",; 
	"http://172.16.33.49:8070/WSFEV1.apw")

::Init()
::oWSWSFEV1FEPARAMGETTIPOSDOCRESULT:SoapRecv( WSAdvValue( oXmlRet,"_WSFEV1FEPARAMGETTIPOSDOCRESPONSE:_WSFEV1FEPARAMGETTIPOSDOCRESULT","GETTIPO",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.

// WSDL Method WSFEV1FEPARAMGETTIPOSIVA of Service WSWSFEV1

WSMETHOD WSFEV1FEPARAMGETTIPOSIVA WSSEND cUSERTOKEN,cID_ENT WSRECEIVE oWSWSFEV1FEPARAMGETTIPOSIVARESULT WSCLIENT WSWSFEV1
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<WSFEV1FEPARAMGETTIPOSIVA xmlns="http://172.16.33.49:8070/">'
cSoap += WSSoapValue("USERTOKEN", ::cUSERTOKEN, cUSERTOKEN , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("ID_ENT", ::cID_ENT, cID_ENT , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += "</WSFEV1FEPARAMGETTIPOSIVA>"

oXmlRet := SvcSoapCall(	ObjSelf(Self),cSoap,; 
	"http://172.16.33.49:8070/WSFEV1FEPARAMGETTIPOSIVA",; 
	"DOCUMENT","http://172.16.33.49:8070/",,"1.031217",; 
	"http://172.16.33.49:8070/WSFEV1.apw")

::Init()
::oWSWSFEV1FEPARAMGETTIPOSIVARESULT:SoapRecv( WSAdvValue( oXmlRet,"_WSFEV1FEPARAMGETTIPOSIVARESPONSE:_WSFEV1FEPARAMGETTIPOSIVARESULT","GETTIPO",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.

// WSDL Method WSFEV1FEPARAMGETTIPOSMONEDAS of Service WSWSFEV1

WSMETHOD WSFEV1FEPARAMGETTIPOSMONEDAS WSSEND cUSERTOKEN,cID_ENT WSRECEIVE oWSWSFEV1FEPARAMGETTIPOSMONEDASRESULT WSCLIENT WSWSFEV1
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<WSFEV1FEPARAMGETTIPOSMONEDAS xmlns="http://172.16.33.49:8070/">'
cSoap += WSSoapValue("USERTOKEN", ::cUSERTOKEN, cUSERTOKEN , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("ID_ENT", ::cID_ENT, cID_ENT , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += "</WSFEV1FEPARAMGETTIPOSMONEDAS>"

oXmlRet := SvcSoapCall(	ObjSelf(Self),cSoap,; 
	"http://172.16.33.49:8070/WSFEV1FEPARAMGETTIPOSMONEDAS",; 
	"DOCUMENT","http://172.16.33.49:8070/",,"1.031217",; 
	"http://172.16.33.49:8070/WSFEV1.apw")

::Init()
::oWSWSFEV1FEPARAMGETTIPOSMONEDASRESULT:SoapRecv( WSAdvValue( oXmlRet,"_WSFEV1FEPARAMGETTIPOSMONEDASRESPONSE:_WSFEV1FEPARAMGETTIPOSMONEDASRESULT","GETTIPO",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.

// WSDL Method WSFEV1FEPARAMGETTIPOSOPCIONAL of Service WSWSFEV1

WSMETHOD WSFEV1FEPARAMGETTIPOSOPCIONAL WSSEND cUSERTOKEN,cID_ENT WSRECEIVE oWSWSFEV1FEPARAMGETTIPOSOPCIONALRESULT WSCLIENT WSWSFEV1
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<WSFEV1FEPARAMGETTIPOSOPCIONAL xmlns="http://172.16.33.49:8070/">'
cSoap += WSSoapValue("USERTOKEN", ::cUSERTOKEN, cUSERTOKEN , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("ID_ENT", ::cID_ENT, cID_ENT , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += "</WSFEV1FEPARAMGETTIPOSOPCIONAL>"

oXmlRet := SvcSoapCall(	ObjSelf(Self),cSoap,; 
	"http://172.16.33.49:8070/WSFEV1FEPARAMGETTIPOSOPCIONAL",; 
	"DOCUMENT","http://172.16.33.49:8070/",,"1.031217",; 
	"http://172.16.33.49:8070/WSFEV1.apw")

::Init()
::oWSWSFEV1FEPARAMGETTIPOSOPCIONALRESULT:SoapRecv( WSAdvValue( oXmlRet,"_WSFEV1FEPARAMGETTIPOSOPCIONALRESPONSE:_WSFEV1FEPARAMGETTIPOSOPCIONALRESULT","GETTIPO",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.

// WSDL Method WSFEV1FEPARAMGETTIPOSTRIBUTOS of Service WSWSFEV1

WSMETHOD WSFEV1FEPARAMGETTIPOSTRIBUTOS WSSEND cUSERTOKEN,cID_ENT WSRECEIVE oWSWSFEV1FEPARAMGETTIPOSTRIBUTOSRESULT WSCLIENT WSWSFEV1
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<WSFEV1FEPARAMGETTIPOSTRIBUTOS xmlns="http://172.16.33.49:8070/">'
cSoap += WSSoapValue("USERTOKEN", ::cUSERTOKEN, cUSERTOKEN , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("ID_ENT", ::cID_ENT, cID_ENT , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += "</WSFEV1FEPARAMGETTIPOSTRIBUTOS>"

oXmlRet := SvcSoapCall(	ObjSelf(Self),cSoap,; 
	"http://172.16.33.49:8070/WSFEV1FEPARAMGETTIPOSTRIBUTOS",; 
	"DOCUMENT","http://172.16.33.49:8070/",,"1.031217",; 
	"http://172.16.33.49:8070/WSFEV1.apw")

::Init()
::oWSWSFEV1FEPARAMGETTIPOSTRIBUTOSRESULT:SoapRecv( WSAdvValue( oXmlRet,"_WSFEV1FEPARAMGETTIPOSTRIBUTOSRESPONSE:_WSFEV1FEPARAMGETTIPOSTRIBUTOSRESULT","GETTIPO",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.

// WSDL Method WSMTXCAEACONSULTAR of Service WSWSFEV1

WSMETHOD WSMTXCAEACONSULTAR WSSEND cUSERTOKEN,cID_ENT,dDATADESDE,dDATAATE WSRECEIVE oWSWSMTXCAEACONSULTARRESULT WSCLIENT WSWSFEV1
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<WSMTXCAEACONSULTAR xmlns="http://172.16.33.49:8070/">'
cSoap += WSSoapValue("USERTOKEN", ::cUSERTOKEN, cUSERTOKEN , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("ID_ENT", ::cID_ENT, cID_ENT , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("DATADESDE", ::dDATADESDE, dDATADESDE , "date", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("DATAATE", ::dDATAATE, dDATAATE , "date", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += "</WSMTXCAEACONSULTAR>"

oXmlRet := SvcSoapCall( ObjSelf(Self),cSoap,; 
	"http://172.16.33.49:8070/WSMTXCAEACONSULTAR",; 
	"DOCUMENT","http://172.16.33.49:8070/",,"1.031217",; 
	"http://172.16.33.49:8070/WSFEV1.apw")

::Init()
::oWSWSMTXCAEACONSULTARRESULT:SoapRecv( WSAdvValue( oXmlRet,"_WSMTXCAEACONSULTARRESPONSE:_WSMTXCAEACONSULTARRESULT","FEVCAEASOLIC",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.

// WSDL Method WSMTXCAEASOLICITAR of Service WSWSFEV1

WSMETHOD WSMTXCAEASOLICITAR WSSEND cUSERTOKEN,cID_ENT,nPERIODO,nORDEN WSRECEIVE oWSWSMTXCAEASOLICITARRESULT WSCLIENT WSWSFEV1
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<WSMTXCAEASOLICITAR xmlns="http://172.16.33.49:8070/">'
cSoap += WSSoapValue("USERTOKEN", ::cUSERTOKEN, cUSERTOKEN , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("ID_ENT", ::cID_ENT, cID_ENT , "string", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("PERIODO", ::nPERIODO, nPERIODO , "integer", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += WSSoapValue("ORDEN", ::nORDEN, nORDEN , "integer", .T. , .F., 0 , NIL, .F.,.F.) 
cSoap += "</WSMTXCAEASOLICITAR>"

oXmlRet := SvcSoapCall( ObjSelf(Self),cSoap,; 
	"http://172.16.33.49:8070/WSMTXCAEASOLICITAR",; 
	"DOCUMENT","http://172.16.33.49:8070/",,"1.031217",; 
	"http://172.16.33.49:8070/WSFEV1.apw")

::Init()
::oWSWSMTXCAEASOLICITARRESULT:SoapRecv( WSAdvValue( oXmlRet,"_WSMTXCAEASOLICITARRESPONSE:_WSMTXCAEASOLICITARRESULT","FEVCAEASOLIC",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.


// WSDL Data Structure DUMMYWSFE

WSSTRUCT WSFEV1_DUMMYWSFE
	WSDATA   cAPPSERVER                AS string OPTIONAL
	WSDATA   cAUTHSERVER               AS string OPTIONAL
	WSDATA   cDBSERVER                 AS string OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT WSFEV1_DUMMYWSFE
	::Init()
Return Self

WSMETHOD INIT WSCLIENT WSFEV1_DUMMYWSFE
Return

WSMETHOD CLONE WSCLIENT WSFEV1_DUMMYWSFE
	Local oClone := WSFEV1_DUMMYWSFE():NEW()
	oClone:cAPPSERVER           := ::cAPPSERVER
	oClone:cAUTHSERVER          := ::cAUTHSERVER
	oClone:cDBSERVER            := ::cDBSERVER
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT WSFEV1_DUMMYWSFE
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::cAPPSERVER         :=  WSAdvValue( oResponse,"_APPSERVER","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cAUTHSERVER        :=  WSAdvValue( oResponse,"_AUTHSERVER","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cDBSERVER          :=  WSAdvValue( oResponse,"_DBSERVER","string",NIL,NIL,NIL,"S",NIL,NIL) 
Return

// WSDL Data Structure MONITORWSFE

WSSTRUCT WSFEV1_MONITORWSFE
	WSDATA   oWSMONITOR                AS WSFEV1_ARRAYOFRETCOMP OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT WSFEV1_MONITORWSFE
	::Init()
Return Self

WSMETHOD INIT WSCLIENT WSFEV1_MONITORWSFE
Return

WSMETHOD CLONE WSCLIENT WSFEV1_MONITORWSFE
	Local oClone := WSFEV1_MONITORWSFE():NEW()
	oClone:oWSMONITOR           := IIF(::oWSMONITOR = NIL , NIL , ::oWSMONITOR:Clone() )
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT WSFEV1_MONITORWSFE
	Local oNode1
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNode1 :=  WSAdvValue( oResponse,"_MONITOR","ARRAYOFRETCOMP",NIL,NIL,NIL,"O",NIL,NIL) 
	If oNode1 != NIL
		::oWSMONITOR := WSFEV1_ARRAYOFRETCOMP():New()
		::oWSMONITOR:SoapRecv(oNode1)
	EndIf
Return

// WSDL Data Structure ARRNOTASARG

WSSTRUCT WSFEV1_ARRNOTASARG
	WSDATA   oWSNOTASLOC               AS WSFEV1_ARRAYOFNFESARG
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPSEND
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT WSFEV1_ARRNOTASARG
	::Init()
Return Self

WSMETHOD INIT WSCLIENT WSFEV1_ARRNOTASARG
Return

WSMETHOD CLONE WSCLIENT WSFEV1_ARRNOTASARG
	Local oClone := WSFEV1_ARRNOTASARG():NEW()
	oClone:oWSNOTASLOC          := IIF(::oWSNOTASLOC = NIL , NIL , ::oWSNOTASLOC:Clone() )
Return oClone

WSMETHOD SOAPSEND WSCLIENT WSFEV1_ARRNOTASARG
	Local cSoap := ""
	cSoap += WSSoapValue("NOTASLOC", ::oWSNOTASLOC, ::oWSNOTASLOC , "ARRAYOFNFESARG", .T. , .F., 0 , NIL, .F.,.F.) 
Return cSoap

// WSDL Data Structure IDARG

WSSTRUCT WSFEV1_IDARG
	WSDATA   oWSID                     AS WSFEV1_ARRAYOFSTRING OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT WSFEV1_IDARG
	::Init()
Return Self

WSMETHOD INIT WSCLIENT WSFEV1_IDARG
Return

WSMETHOD CLONE WSCLIENT WSFEV1_IDARG
	Local oClone := WSFEV1_IDARG():NEW()
	oClone:oWSID                := IIF(::oWSID = NIL , NIL , ::oWSID:Clone() )
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT WSFEV1_IDARG
	Local oNode1
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNode1 :=  WSAdvValue( oResponse,"_ID","ARRAYOFSTRING",NIL,NIL,NIL,"O",NIL,NIL) 
	If oNode1 != NIL
		::oWSID := WSFEV1_ARRAYOFSTRING():New()
		::oWSID:SoapRecv(oNode1)
	EndIf
Return

// WSDL Data Structure FEVCAEASOLIC

WSSTRUCT WSFEV1_FEVCAEASOLIC
	WSDATA   oWSERRORS                 AS WSFEV1_ARRAYOFERRORS OPTIONAL
	WSDATA   oWSEVENTS                 AS WSFEV1_ARRAYOFEVENTS OPTIONAL
	WSDATA   oWSRESULTGET              AS WSFEV1_RESULTGET OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT WSFEV1_FEVCAEASOLIC
	::Init()
Return Self

WSMETHOD INIT WSCLIENT WSFEV1_FEVCAEASOLIC
Return

WSMETHOD CLONE WSCLIENT WSFEV1_FEVCAEASOLIC
	Local oClone := WSFEV1_FEVCAEASOLIC():NEW()
	oClone:oWSERRORS            := IIF(::oWSERRORS = NIL , NIL , ::oWSERRORS:Clone() )
	oClone:oWSEVENTS            := IIF(::oWSEVENTS = NIL , NIL , ::oWSEVENTS:Clone() )
	oClone:oWSRESULTGET         := IIF(::oWSRESULTGET = NIL , NIL , ::oWSRESULTGET:Clone() )
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT WSFEV1_FEVCAEASOLIC
	Local oNode1
	Local oNode2
	Local oNode3
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNode1 :=  WSAdvValue( oResponse,"_ERRORS","ARRAYOFERRORS",NIL,NIL,NIL,"O",NIL,NIL) 
	If oNode1 != NIL
		::oWSERRORS := WSFEV1_ARRAYOFERRORS():New()
		::oWSERRORS:SoapRecv(oNode1)
	EndIf
	oNode2 :=  WSAdvValue( oResponse,"_EVENTS","ARRAYOFEVENTS",NIL,NIL,NIL,"O",NIL,NIL) 
	If oNode2 != NIL
		::oWSEVENTS := WSFEV1_ARRAYOFEVENTS():New()
		::oWSEVENTS:SoapRecv(oNode2)
	EndIf
	oNode3 :=  WSAdvValue( oResponse,"_RESULTGET","RESULTGET",NIL,NIL,NIL,"O",NIL,NIL) 
	If oNode3 != NIL
		::oWSRESULTGET := WSFEV1_RESULTGET():New()
		::oWSRESULTGET:SoapRecv(oNode3)
	EndIf
Return

// WSDL Data Structure FEVSINMOVCONSRESULT

WSSTRUCT WSFEV1_FEVSINMOVCONSRESULT
	WSDATA   oWSERRORS                 AS WSFEV1_ARRAYOFERRORS OPTIONAL
	WSDATA   oWSEVENTS                 AS WSFEV1_ARRAYOFEVENTS OPTIONAL
	WSDATA   oWSRESULTSINMOV           AS WSFEV1_ARRAYOFFECAEASINMOV OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT WSFEV1_FEVSINMOVCONSRESULT
	::Init()
Return Self

WSMETHOD INIT WSCLIENT WSFEV1_FEVSINMOVCONSRESULT
Return

WSMETHOD CLONE WSCLIENT WSFEV1_FEVSINMOVCONSRESULT
	Local oClone := WSFEV1_FEVSINMOVCONSRESULT():NEW()
	oClone:oWSERRORS            := IIF(::oWSERRORS = NIL , NIL , ::oWSERRORS:Clone() )
	oClone:oWSEVENTS            := IIF(::oWSEVENTS = NIL , NIL , ::oWSEVENTS:Clone() )
	oClone:oWSRESULTSINMOV      := IIF(::oWSRESULTSINMOV = NIL , NIL , ::oWSRESULTSINMOV:Clone() )
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT WSFEV1_FEVSINMOVCONSRESULT
	Local oNode1
	Local oNode2
	Local oNode3
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNode1 :=  WSAdvValue( oResponse,"_ERRORS","ARRAYOFERRORS",NIL,NIL,NIL,"O",NIL,NIL) 
	If oNode1 != NIL
		::oWSERRORS := WSFEV1_ARRAYOFERRORS():New()
		::oWSERRORS:SoapRecv(oNode1)
	EndIf
	oNode2 :=  WSAdvValue( oResponse,"_EVENTS","ARRAYOFEVENTS",NIL,NIL,NIL,"O",NIL,NIL) 
	If oNode2 != NIL
		::oWSEVENTS := WSFEV1_ARRAYOFEVENTS():New()
		::oWSEVENTS:SoapRecv(oNode2)
	EndIf
	oNode3 :=  WSAdvValue( oResponse,"_RESULTSINMOV","ARRAYOFFECAEASINMOV",NIL,NIL,NIL,"O",NIL,NIL) 
	If oNode3 != NIL
		::oWSRESULTSINMOV := WSFEV1_ARRAYOFFECAEASINMOV():New()
		::oWSRESULTSINMOV:SoapRecv(oNode3)
	EndIf
Return

// WSDL Data Structure FEVSINMOVINFRESULT

WSSTRUCT WSFEV1_FEVSINMOVINFRESULT
	WSDATA   cCCAEA                    AS string OPTIONAL
	WSDATA   cCFCHPROCESO              AS string OPTIONAL
	WSDATA   cCPTOVTA                  AS string OPTIONAL
	WSDATA   cCRESULTADO               AS string OPTIONAL
	WSDATA   oWSERRORS                 AS WSFEV1_ARRAYOFERRORS OPTIONAL
	WSDATA   oWSEVENTS                 AS WSFEV1_ARRAYOFEVENTS OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT WSFEV1_FEVSINMOVINFRESULT
	::Init()
Return Self

WSMETHOD INIT WSCLIENT WSFEV1_FEVSINMOVINFRESULT
Return

WSMETHOD CLONE WSCLIENT WSFEV1_FEVSINMOVINFRESULT
	Local oClone := WSFEV1_FEVSINMOVINFRESULT():NEW()
	oClone:cCCAEA               := ::cCCAEA
	oClone:cCFCHPROCESO         := ::cCFCHPROCESO
	oClone:cCPTOVTA             := ::cCPTOVTA
	oClone:cCRESULTADO          := ::cCRESULTADO
	oClone:oWSERRORS            := IIF(::oWSERRORS = NIL , NIL , ::oWSERRORS:Clone() )
	oClone:oWSEVENTS            := IIF(::oWSEVENTS = NIL , NIL , ::oWSEVENTS:Clone() )
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT WSFEV1_FEVSINMOVINFRESULT
	Local oNode5
	Local oNode6
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::cCCAEA             :=  WSAdvValue( oResponse,"_CCAEA","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cCFCHPROCESO       :=  WSAdvValue( oResponse,"_CFCHPROCESO","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cCPTOVTA           :=  WSAdvValue( oResponse,"_CPTOVTA","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cCRESULTADO        :=  WSAdvValue( oResponse,"_CRESULTADO","string",NIL,NIL,NIL,"S",NIL,NIL) 
	oNode5 :=  WSAdvValue( oResponse,"_ERRORS","ARRAYOFERRORS",NIL,NIL,NIL,"O",NIL,NIL) 
	If oNode5 != NIL
		::oWSERRORS := WSFEV1_ARRAYOFERRORS():New()
		::oWSERRORS:SoapRecv(oNode5)
	EndIf
	oNode6 :=  WSAdvValue( oResponse,"_EVENTS","ARRAYOFEVENTS",NIL,NIL,NIL,"O",NIL,NIL) 
	If oNode6 != NIL
		::oWSEVENTS := WSFEV1_ARRAYOFEVENTS():New()
		::oWSEVENTS:SoapRecv(oNode6)
	EndIf
Return

// WSDL Data Structure GETCMP

WSSTRUCT WSFEV1_GETCMP
	WSDATA   nCBTE_NRO                 AS integer
	WSDATA   nPUNTO_VTA                AS integer
	WSDATA   nTIPO_CBTE                AS integer
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPSEND
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT WSFEV1_GETCMP
	::Init()
Return Self

WSMETHOD INIT WSCLIENT WSFEV1_GETCMP
Return

WSMETHOD CLONE WSCLIENT WSFEV1_GETCMP
	Local oClone := WSFEV1_GETCMP():NEW()
	oClone:nCBTE_NRO            := ::nCBTE_NRO
	oClone:nPUNTO_VTA           := ::nPUNTO_VTA
	oClone:nTIPO_CBTE           := ::nTIPO_CBTE
Return oClone

WSMETHOD SOAPSEND WSCLIENT WSFEV1_GETCMP
	Local cSoap := ""
	cSoap += WSSoapValue("CBTE_NRO", ::nCBTE_NRO, ::nCBTE_NRO , "integer", .T. , .F., 0 , NIL, .F.,.F.) 
	cSoap += WSSoapValue("PUNTO_VTA", ::nPUNTO_VTA, ::nPUNTO_VTA , "integer", .T. , .F., 0 , NIL, .F.,.F.) 
	cSoap += WSSoapValue("TIPO_CBTE", ::nTIPO_CBTE, ::nTIPO_CBTE , "integer", .T. , .F., 0 , NIL, .F.,.F.) 
Return cSoap

// WSDL Data Structure RESULTCOMPCONS

WSSTRUCT WSFEV1_RESULTCOMPCONS
	WSDATA   cCOMPROVANTE              AS base64Binary OPTIONAL
	WSDATA   cERRORS                   AS base64Binary OPTIONAL
	WSDATA   cEVENTS                   AS base64Binary OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT WSFEV1_RESULTCOMPCONS
	::Init()
Return Self

WSMETHOD INIT WSCLIENT WSFEV1_RESULTCOMPCONS
Return

WSMETHOD CLONE WSCLIENT WSFEV1_RESULTCOMPCONS
	Local oClone := WSFEV1_RESULTCOMPCONS():NEW()
	oClone:cCOMPROVANTE         := ::cCOMPROVANTE
	oClone:cERRORS              := ::cERRORS
	oClone:cEVENTS              := ::cEVENTS
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT WSFEV1_RESULTCOMPCONS
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::cCOMPROVANTE       :=  WSAdvValue( oResponse,"_COMPROVANTE","base64Binary",NIL,NIL,NIL,"SB",NIL,NIL) 
	::cERRORS            :=  WSAdvValue( oResponse,"_ERRORS","base64Binary",NIL,NIL,NIL,"SB",NIL,NIL) 
	::cEVENTS            :=  WSAdvValue( oResponse,"_EVENTS","base64Binary",NIL,NIL,NIL,"SB",NIL,NIL) 
Return

// WSDL Data Structure FEVCOMPTOTXREQUEST

WSSTRUCT WSFEV1_FEVCOMPTOTXREQUEST
	WSDATA   oWSERRORS                 AS WSFEV1_ARRAYOFERRORS OPTIONAL
	WSDATA   oWSEVENTS                 AS WSFEV1_ARRAYOFEVENTS OPTIONAL
	WSDATA   nREGXREQ                  AS integer OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT WSFEV1_FEVCOMPTOTXREQUEST
	::Init()
Return Self

WSMETHOD INIT WSCLIENT WSFEV1_FEVCOMPTOTXREQUEST
Return

WSMETHOD CLONE WSCLIENT WSFEV1_FEVCOMPTOTXREQUEST
	Local oClone := WSFEV1_FEVCOMPTOTXREQUEST():NEW()
	oClone:oWSERRORS            := IIF(::oWSERRORS = NIL , NIL , ::oWSERRORS:Clone() )
	oClone:oWSEVENTS            := IIF(::oWSEVENTS = NIL , NIL , ::oWSEVENTS:Clone() )
	oClone:nREGXREQ             := ::nREGXREQ
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT WSFEV1_FEVCOMPTOTXREQUEST
	Local oNode1
	Local oNode2
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNode1 :=  WSAdvValue( oResponse,"_ERRORS","ARRAYOFERRORS",NIL,NIL,NIL,"O",NIL,NIL) 
	If oNode1 != NIL
		::oWSERRORS := WSFEV1_ARRAYOFERRORS():New()
		::oWSERRORS:SoapRecv(oNode1)
	EndIf
	oNode2 :=  WSAdvValue( oResponse,"_EVENTS","ARRAYOFEVENTS",NIL,NIL,NIL,"O",NIL,NIL) 
	If oNode2 != NIL
		::oWSEVENTS := WSFEV1_ARRAYOFEVENTS():New()
		::oWSEVENTS:SoapRecv(oNode2)
	EndIf
	::nREGXREQ           :=  WSAdvValue( oResponse,"_REGXREQ","integer",NIL,NIL,NIL,"N",NIL,NIL) 
Return

// WSDL Data Structure LASTCOMPWSFE

WSSTRUCT WSFEV1_LASTCOMPWSFE
	WSDATA   nCBTENRO                  AS integer OPTIONAL
	WSDATA   nCBTETIPO                 AS integer OPTIONAL
	WSDATA   oWSERRORS                 AS WSFEV1_ARRAYOFERRORS OPTIONAL
	WSDATA   oWSEVENTS                 AS WSFEV1_ARRAYOFEVENTS OPTIONAL
	WSDATA   nPTOVTA                   AS integer OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT WSFEV1_LASTCOMPWSFE
	::Init()
Return Self

WSMETHOD INIT WSCLIENT WSFEV1_LASTCOMPWSFE
Return

WSMETHOD CLONE WSCLIENT WSFEV1_LASTCOMPWSFE
	Local oClone := WSFEV1_LASTCOMPWSFE():NEW()
	oClone:nCBTENRO             := ::nCBTENRO
	oClone:nCBTETIPO            := ::nCBTETIPO
	oClone:oWSERRORS            := IIF(::oWSERRORS = NIL , NIL , ::oWSERRORS:Clone() )
	oClone:oWSEVENTS            := IIF(::oWSEVENTS = NIL , NIL , ::oWSEVENTS:Clone() )
	oClone:nPTOVTA              := ::nPTOVTA
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT WSFEV1_LASTCOMPWSFE
	Local oNode3
	Local oNode4
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::nCBTENRO           :=  WSAdvValue( oResponse,"_CBTENRO","integer",NIL,NIL,NIL,"N",NIL,NIL) 
	::nCBTETIPO          :=  WSAdvValue( oResponse,"_CBTETIPO","integer",NIL,NIL,NIL,"N",NIL,NIL) 
	oNode3 :=  WSAdvValue( oResponse,"_ERRORS","ARRAYOFERRORS",NIL,NIL,NIL,"O",NIL,NIL) 
	If oNode3 != NIL
		::oWSERRORS := WSFEV1_ARRAYOFERRORS():New()
		::oWSERRORS:SoapRecv(oNode3)
	EndIf
	oNode4 :=  WSAdvValue( oResponse,"_EVENTS","ARRAYOFEVENTS",NIL,NIL,NIL,"O",NIL,NIL) 
	If oNode4 != NIL
		::oWSEVENTS := WSFEV1_ARRAYOFEVENTS():New()
		::oWSEVENTS:SoapRecv(oNode4)
	EndIf
	::nPTOVTA            :=  WSAdvValue( oResponse,"_PTOVTA","integer",NIL,NIL,NIL,"N",NIL,NIL) 
Return

// WSDL Data Structure FEVPARAMCTZ

WSSTRUCT WSFEV1_FEVPARAMCTZ
	WSDATA   oWSERRORS                 AS WSFEV1_ARRAYOFERRORS OPTIONAL
	WSDATA   oWSEVENTS                 AS WSFEV1_ARRAYOFEVENTS OPTIONAL
	WSDATA   cFCHCOTIZ                 AS string OPTIONAL
	WSDATA   nMONCOTIZ                 AS double OPTIONAL
	WSDATA   cMONID                    AS string OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT WSFEV1_FEVPARAMCTZ
	::Init()
Return Self

WSMETHOD INIT WSCLIENT WSFEV1_FEVPARAMCTZ
Return

WSMETHOD CLONE WSCLIENT WSFEV1_FEVPARAMCTZ
	Local oClone := WSFEV1_FEVPARAMCTZ():NEW()
	oClone:oWSERRORS            := IIF(::oWSERRORS = NIL , NIL , ::oWSERRORS:Clone() )
	oClone:oWSEVENTS            := IIF(::oWSEVENTS = NIL , NIL , ::oWSEVENTS:Clone() )
	oClone:cFCHCOTIZ            := ::cFCHCOTIZ
	oClone:nMONCOTIZ            := ::nMONCOTIZ
	oClone:cMONID               := ::cMONID
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT WSFEV1_FEVPARAMCTZ
	Local oNode1
	Local oNode2
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNode1 :=  WSAdvValue( oResponse,"_ERRORS","ARRAYOFERRORS",NIL,NIL,NIL,"O",NIL,NIL) 
	If oNode1 != NIL
		::oWSERRORS := WSFEV1_ARRAYOFERRORS():New()
		::oWSERRORS:SoapRecv(oNode1)
	EndIf
	oNode2 :=  WSAdvValue( oResponse,"_EVENTS","ARRAYOFEVENTS",NIL,NIL,NIL,"O",NIL,NIL) 
	If oNode2 != NIL
		::oWSEVENTS := WSFEV1_ARRAYOFEVENTS():New()
		::oWSEVENTS:SoapRecv(oNode2)
	EndIf
	::cFCHCOTIZ          :=  WSAdvValue( oResponse,"_FCHCOTIZ","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::nMONCOTIZ          :=  WSAdvValue( oResponse,"_MONCOTIZ","integer",NIL,NIL,NIL,"N",NIL,NIL) 
	::cMONID             :=  WSAdvValue( oResponse,"_MONID","string",NIL,NIL,NIL,"S",NIL,NIL) 
Return

// WSDL Data Structure FEVGETPTOVENTA

WSSTRUCT WSFEV1_FEVGETPTOVENTA
	WSDATA   oWSERRORS                 AS WSFEV1_ARRAYOFERRORS OPTIONAL
	WSDATA   oWSEVENTS                 AS WSFEV1_ARRAYOFEVENTS OPTIONAL
	WSDATA   oWSFEVARRPVE              AS WSFEV1_ARRAYOFFEVRESVENTAS OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT WSFEV1_FEVGETPTOVENTA
	::Init()
Return Self

WSMETHOD INIT WSCLIENT WSFEV1_FEVGETPTOVENTA
Return

WSMETHOD CLONE WSCLIENT WSFEV1_FEVGETPTOVENTA
	Local oClone := WSFEV1_FEVGETPTOVENTA():NEW()
	oClone:oWSERRORS            := IIF(::oWSERRORS = NIL , NIL , ::oWSERRORS:Clone() )
	oClone:oWSEVENTS            := IIF(::oWSEVENTS = NIL , NIL , ::oWSEVENTS:Clone() )
	oClone:oWSFEVARRPVE         := IIF(::oWSFEVARRPVE = NIL , NIL , ::oWSFEVARRPVE:Clone() )
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT WSFEV1_FEVGETPTOVENTA
	Local oNode1
	Local oNode2
	Local oNode3
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNode1 :=  WSAdvValue( oResponse,"_ERRORS","ARRAYOFERRORS",NIL,NIL,NIL,"O",NIL,NIL) 
	If oNode1 != NIL
		::oWSERRORS := WSFEV1_ARRAYOFERRORS():New()
		::oWSERRORS:SoapRecv(oNode1)
	EndIf
	oNode2 :=  WSAdvValue( oResponse,"_EVENTS","ARRAYOFEVENTS",NIL,NIL,NIL,"O",NIL,NIL) 
	If oNode2 != NIL
		::oWSEVENTS := WSFEV1_ARRAYOFEVENTS():New()
		::oWSEVENTS:SoapRecv(oNode2)
	EndIf
	oNode3 :=  WSAdvValue( oResponse,"_FEVARRPVE","ARRAYOFFEVRESVENTAS",NIL,NIL,NIL,"O",NIL,NIL) 
	If oNode3 != NIL
		::oWSFEVARRPVE := WSFEV1_ARRAYOFFEVRESVENTAS():New()
		::oWSFEVARRPVE:SoapRecv(oNode3)
	EndIf
Return

// WSDL Data Structure GETTIPO

WSSTRUCT WSFEV1_GETTIPO
	WSDATA   oWSARRTIPO                AS WSFEV1_ARRAYOFTIPOS OPTIONAL
	WSDATA   oWSERRORS                 AS WSFEV1_ARRAYOFERRORS OPTIONAL
	WSDATA   oWSEVENTS                 AS WSFEV1_ARRAYOFEVENTS OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT WSFEV1_GETTIPO
	::Init()
Return Self

WSMETHOD INIT WSCLIENT WSFEV1_GETTIPO
Return

WSMETHOD CLONE WSCLIENT WSFEV1_GETTIPO
	Local oClone := WSFEV1_GETTIPO():NEW()
	oClone:oWSARRTIPO           := IIF(::oWSARRTIPO = NIL , NIL , ::oWSARRTIPO:Clone() )
	oClone:oWSERRORS            := IIF(::oWSERRORS = NIL , NIL , ::oWSERRORS:Clone() )
	oClone:oWSEVENTS            := IIF(::oWSEVENTS = NIL , NIL , ::oWSEVENTS:Clone() )
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT WSFEV1_GETTIPO
	Local oNode1
	Local oNode2
	Local oNode3
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNode1 :=  WSAdvValue( oResponse,"_ARRTIPO","ARRAYOFTIPOS",NIL,NIL,NIL,"O",NIL,NIL) 
	If oNode1 != NIL
		::oWSARRTIPO := WSFEV1_ARRAYOFTIPOS():New()
		::oWSARRTIPO:SoapRecv(oNode1)
	EndIf
	oNode2 :=  WSAdvValue( oResponse,"_ERRORS","ARRAYOFERRORS",NIL,NIL,NIL,"O",NIL,NIL) 
	If oNode2 != NIL
		::oWSERRORS := WSFEV1_ARRAYOFERRORS():New()
		::oWSERRORS:SoapRecv(oNode2)
	EndIf
	oNode3 :=  WSAdvValue( oResponse,"_EVENTS","ARRAYOFEVENTS",NIL,NIL,NIL,"O",NIL,NIL) 
	If oNode3 != NIL
		::oWSEVENTS := WSFEV1_ARRAYOFEVENTS():New()
		::oWSEVENTS:SoapRecv(oNode3)
	EndIf
Return

// WSDL Data Structure ARRAYOFRETCOMP

WSSTRUCT WSFEV1_ARRAYOFRETCOMP
	WSDATA   oWSRETCOMP                AS WSFEV1_RETCOMP OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT WSFEV1_ARRAYOFRETCOMP
	::Init()
Return Self

WSMETHOD INIT WSCLIENT WSFEV1_ARRAYOFRETCOMP
	::oWSRETCOMP           := {} // Array Of  WSFEV1_RETCOMP():New()
Return

WSMETHOD CLONE WSCLIENT WSFEV1_ARRAYOFRETCOMP
	Local oClone := WSFEV1_ARRAYOFRETCOMP():NEW()
	oClone:oWSRETCOMP := NIL
	If ::oWSRETCOMP <> NIL 
		oClone:oWSRETCOMP := {}
		aEval( ::oWSRETCOMP , { |x| aadd( oClone:oWSRETCOMP , x:Clone() ) } )
	Endif 
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT WSFEV1_ARRAYOFRETCOMP
	Local nRElem1, oNodes1, nTElem1
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNodes1 :=  WSAdvValue( oResponse,"_RETCOMP","RETCOMP",{},NIL,.T.,"O",NIL,NIL) 
	nTElem1 := len(oNodes1)
	For nRElem1 := 1 to nTElem1 
		If !WSIsNilNode( oNodes1[nRElem1] )
			aadd(::oWSRETCOMP , WSFEV1_RETCOMP():New() )
			::oWSRETCOMP[len(::oWSRETCOMP)]:SoapRecv(oNodes1[nRElem1])
		Endif
	Next
Return

// WSDL Data Structure ARRAYOFNFESARG

WSSTRUCT WSFEV1_ARRAYOFNFESARG
	WSDATA   oWSNFESARG                AS WSFEV1_NFESARG OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPSEND
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT WSFEV1_ARRAYOFNFESARG
	::Init()
Return Self

WSMETHOD INIT WSCLIENT WSFEV1_ARRAYOFNFESARG
	::oWSNFESARG           := {} // Array Of  WSFEV1_NFESARG():New()
Return

WSMETHOD CLONE WSCLIENT WSFEV1_ARRAYOFNFESARG
	Local oClone := WSFEV1_ARRAYOFNFESARG():NEW()
	oClone:oWSNFESARG := NIL
	If ::oWSNFESARG <> NIL 
		oClone:oWSNFESARG := {}
		aEval( ::oWSNFESARG , { |x| aadd( oClone:oWSNFESARG , x:Clone() ) } )
	Endif 
Return oClone

WSMETHOD SOAPSEND WSCLIENT WSFEV1_ARRAYOFNFESARG
	Local cSoap := ""
	aEval( ::oWSNFESARG , {|x| cSoap := cSoap  +  WSSoapValue("NFESARG", x , x , "NFESARG", .F. , .F., 0 , NIL, .F.,.F.)  } ) 
Return cSoap

// WSDL Data Structure ARRAYOFSTRING

WSSTRUCT WSFEV1_ARRAYOFSTRING
	WSDATA   cSTRING                   AS string OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT WSFEV1_ARRAYOFSTRING
	::Init()
Return Self

WSMETHOD INIT WSCLIENT WSFEV1_ARRAYOFSTRING
	::cSTRING              := {} // Array Of  ""
Return

WSMETHOD CLONE WSCLIENT WSFEV1_ARRAYOFSTRING
	Local oClone := WSFEV1_ARRAYOFSTRING():NEW()
	oClone:cSTRING              := IIf(::cSTRING <> NIL , aClone(::cSTRING) , NIL )
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT WSFEV1_ARRAYOFSTRING
	Local oNodes1 :=  WSAdvValue( oResponse,"_STRING","string",{},NIL,.T.,"S",NIL,"a") 
	::Init()
	If oResponse = NIL ; Return ; Endif 
	aEval(oNodes1 , { |x| aadd(::cSTRING ,  x:TEXT  ) } )
Return

// WSDL Data Structure ARRAYOFERRORS

WSSTRUCT WSFEV1_ARRAYOFERRORS
	WSDATA   oWSERRORS                 AS WSFEV1_ERRORS OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT WSFEV1_ARRAYOFERRORS
	::Init()
Return Self

WSMETHOD INIT WSCLIENT WSFEV1_ARRAYOFERRORS
	::oWSERRORS            := {} // Array Of  WSFEV1_ERRORS():New()
Return

WSMETHOD CLONE WSCLIENT WSFEV1_ARRAYOFERRORS
	Local oClone := WSFEV1_ARRAYOFERRORS():NEW()
	oClone:oWSERRORS := NIL
	If ::oWSERRORS <> NIL 
		oClone:oWSERRORS := {}
		aEval( ::oWSERRORS , { |x| aadd( oClone:oWSERRORS , x:Clone() ) } )
	Endif 
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT WSFEV1_ARRAYOFERRORS
	Local nRElem1, oNodes1, nTElem1
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNodes1 :=  WSAdvValue( oResponse,"_ERRORS","ERRORS",{},NIL,.T.,"O",NIL,NIL) 
	nTElem1 := len(oNodes1)
	For nRElem1 := 1 to nTElem1 
		If !WSIsNilNode( oNodes1[nRElem1] )
			aadd(::oWSERRORS , WSFEV1_ERRORS():New() )
			::oWSERRORS[len(::oWSERRORS)]:SoapRecv(oNodes1[nRElem1])
		Endif
	Next
Return

// WSDL Data Structure ARRAYOFEVENTS

WSSTRUCT WSFEV1_ARRAYOFEVENTS
	WSDATA   oWSEVENTS                 AS WSFEV1_EVENTS OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT WSFEV1_ARRAYOFEVENTS
	::Init()
Return Self

WSMETHOD INIT WSCLIENT WSFEV1_ARRAYOFEVENTS
	::oWSEVENTS            := {} // Array Of  WSFEV1_EVENTS():New()
Return

WSMETHOD CLONE WSCLIENT WSFEV1_ARRAYOFEVENTS
	Local oClone := WSFEV1_ARRAYOFEVENTS():NEW()
	oClone:oWSEVENTS := NIL
	If ::oWSEVENTS <> NIL 
		oClone:oWSEVENTS := {}
		aEval( ::oWSEVENTS , { |x| aadd( oClone:oWSEVENTS , x:Clone() ) } )
	Endif 
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT WSFEV1_ARRAYOFEVENTS
	Local nRElem1, oNodes1, nTElem1
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNodes1 :=  WSAdvValue( oResponse,"_EVENTS","EVENTS",{},NIL,.T.,"O",NIL,NIL) 
	nTElem1 := len(oNodes1)
	For nRElem1 := 1 to nTElem1 
		If !WSIsNilNode( oNodes1[nRElem1] )
			aadd(::oWSEVENTS , WSFEV1_EVENTS():New() )
			::oWSEVENTS[len(::oWSEVENTS)]:SoapRecv(oNodes1[nRElem1])
		Endif
	Next
Return

// WSDL Data Structure RESULTGET

WSSTRUCT WSFEV1_RESULTGET
	WSDATA   cCCAEA                    AS string OPTIONAL
	WSDATA   cCFCHPROCESO              AS string OPTIONAL
	WSDATA   cCFCHTOPEINF              AS string OPTIONAL
	WSDATA   cCFCHVIGDESDE             AS string OPTIONAL
	WSDATA   cCFCHVIGHASTA             AS string OPTIONAL
	WSDATA   nNORDEN                   AS integer OPTIONAL
	WSDATA   nNPERIODO                 AS integer OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT WSFEV1_RESULTGET
	::Init()
Return Self

WSMETHOD INIT WSCLIENT WSFEV1_RESULTGET
Return

WSMETHOD CLONE WSCLIENT WSFEV1_RESULTGET
	Local oClone := WSFEV1_RESULTGET():NEW()
	oClone:cCCAEA               := ::cCCAEA
	oClone:cCFCHPROCESO         := ::cCFCHPROCESO
	oClone:cCFCHTOPEINF         := ::cCFCHTOPEINF
	oClone:cCFCHVIGDESDE        := ::cCFCHVIGDESDE
	oClone:cCFCHVIGHASTA        := ::cCFCHVIGHASTA
	oClone:nNORDEN              := ::nNORDEN
	oClone:nNPERIODO            := ::nNPERIODO
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT WSFEV1_RESULTGET
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::cCCAEA             :=  WSAdvValue( oResponse,"_CCAEA","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cCFCHPROCESO       :=  WSAdvValue( oResponse,"_CFCHPROCESO","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cCFCHTOPEINF       :=  WSAdvValue( oResponse,"_CFCHTOPEINF","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cCFCHVIGDESDE      :=  WSAdvValue( oResponse,"_CFCHVIGDESDE","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cCFCHVIGHASTA      :=  WSAdvValue( oResponse,"_CFCHVIGHASTA","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::nNORDEN            :=  WSAdvValue( oResponse,"_NORDEN","integer",NIL,NIL,NIL,"N",NIL,NIL) 
	::nNPERIODO          :=  WSAdvValue( oResponse,"_NPERIODO","integer",NIL,NIL,NIL,"N",NIL,NIL) 
Return

// WSDL Data Structure ARRAYOFFECAEASINMOV

WSSTRUCT WSFEV1_ARRAYOFFECAEASINMOV
	WSDATA   oWSFECAEASINMOV           AS WSFEV1_FECAEASINMOV OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT WSFEV1_ARRAYOFFECAEASINMOV
	::Init()
Return Self

WSMETHOD INIT WSCLIENT WSFEV1_ARRAYOFFECAEASINMOV
	::oWSFECAEASINMOV      := {} // Array Of  WSFEV1_FECAEASINMOV():New()
Return

WSMETHOD CLONE WSCLIENT WSFEV1_ARRAYOFFECAEASINMOV
	Local oClone := WSFEV1_ARRAYOFFECAEASINMOV():NEW()
	oClone:oWSFECAEASINMOV := NIL
	If ::oWSFECAEASINMOV <> NIL 
		oClone:oWSFECAEASINMOV := {}
		aEval( ::oWSFECAEASINMOV , { |x| aadd( oClone:oWSFECAEASINMOV , x:Clone() ) } )
	Endif 
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT WSFEV1_ARRAYOFFECAEASINMOV
	Local nRElem1, oNodes1, nTElem1
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNodes1 :=  WSAdvValue( oResponse,"_FECAEASINMOV","FECAEASINMOV",{},NIL,.T.,"O",NIL,NIL) 
	nTElem1 := len(oNodes1)
	For nRElem1 := 1 to nTElem1 
		If !WSIsNilNode( oNodes1[nRElem1] )
			aadd(::oWSFECAEASINMOV , WSFEV1_FECAEASINMOV():New() )
			::oWSFECAEASINMOV[len(::oWSFECAEASINMOV)]:SoapRecv(oNodes1[nRElem1])
		Endif
	Next
Return

// WSDL Data Structure ARRAYOFFEVRESVENTAS

WSSTRUCT WSFEV1_ARRAYOFFEVRESVENTAS
	WSDATA   oWSFEVRESVENTAS           AS WSFEV1_FEVRESVENTAS OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT WSFEV1_ARRAYOFFEVRESVENTAS
	::Init()
Return Self

WSMETHOD INIT WSCLIENT WSFEV1_ARRAYOFFEVRESVENTAS
	::oWSFEVRESVENTAS      := {} // Array Of  WSFEV1_FEVRESVENTAS():New()
Return

WSMETHOD CLONE WSCLIENT WSFEV1_ARRAYOFFEVRESVENTAS
	Local oClone := WSFEV1_ARRAYOFFEVRESVENTAS():NEW()
	oClone:oWSFEVRESVENTAS := NIL
	If ::oWSFEVRESVENTAS <> NIL 
		oClone:oWSFEVRESVENTAS := {}
		aEval( ::oWSFEVRESVENTAS , { |x| aadd( oClone:oWSFEVRESVENTAS , x:Clone() ) } )
	Endif 
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT WSFEV1_ARRAYOFFEVRESVENTAS
	Local nRElem1, oNodes1, nTElem1
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNodes1 :=  WSAdvValue( oResponse,"_FEVRESVENTAS","FEVRESVENTAS",{},NIL,.T.,"O",NIL,NIL) 
	nTElem1 := len(oNodes1)
	For nRElem1 := 1 to nTElem1 
		If !WSIsNilNode( oNodes1[nRElem1] )
			aadd(::oWSFEVRESVENTAS , WSFEV1_FEVRESVENTAS():New() )
			::oWSFEVRESVENTAS[len(::oWSFEVRESVENTAS)]:SoapRecv(oNodes1[nRElem1])
		Endif
	Next
Return

// WSDL Data Structure ARRAYOFTIPOS

WSSTRUCT WSFEV1_ARRAYOFTIPOS
	WSDATA   oWSTIPOS                  AS WSFEV1_TIPOS OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT WSFEV1_ARRAYOFTIPOS
	::Init()
Return Self

WSMETHOD INIT WSCLIENT WSFEV1_ARRAYOFTIPOS
	::oWSTIPOS             := {} // Array Of  WSFEV1_TIPOS():New()
Return

WSMETHOD CLONE WSCLIENT WSFEV1_ARRAYOFTIPOS
	Local oClone := WSFEV1_ARRAYOFTIPOS():NEW()
	oClone:oWSTIPOS := NIL
	If ::oWSTIPOS <> NIL 
		oClone:oWSTIPOS := {}
		aEval( ::oWSTIPOS , { |x| aadd( oClone:oWSTIPOS , x:Clone() ) } )
	Endif 
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT WSFEV1_ARRAYOFTIPOS
	Local nRElem1, oNodes1, nTElem1
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNodes1 :=  WSAdvValue( oResponse,"_TIPOS","TIPOS",{},NIL,.T.,"O",NIL,NIL) 
	nTElem1 := len(oNodes1)
	For nRElem1 := 1 to nTElem1 
		If !WSIsNilNode( oNodes1[nRElem1] )
			aadd(::oWSTIPOS , WSFEV1_TIPOS():New() )
			::oWSTIPOS[len(::oWSTIPOS)]:SoapRecv(oNodes1[nRElem1])
		Endif
	Next
Return

// WSDL Data Structure RETCOMP

WSSTRUCT WSFEV1_RETCOMP
	WSDATA   nAMBIENTE                 AS integer OPTIONAL
	WSDATA   cCAE                      AS string OPTIONAL
	WSDATA   dCAEFCHVTO                AS date OPTIONAL
	WSDATA   dDT_LOTE                  AS date OPTIONAL
	WSDATA   cERRO                     AS base64Binary OPTIONAL
	WSDATA   cEVENTS                   AS base64Binary OPTIONAL
	WSDATA   cID                       AS string OPTIONAL
	WSDATA   nLOTE                     AS integer OPTIONAL
	WSDATA   cOBSERVACOES              AS base64Binary OPTIONAL
	WSDATA   cRECOMENDACAO             AS string OPTIONAL
	WSDATA   cRESULTADO                AS string OPTIONAL
	WSDATA   cXML                      AS base64Binary OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT WSFEV1_RETCOMP
	::Init()
Return Self

WSMETHOD INIT WSCLIENT WSFEV1_RETCOMP
Return

WSMETHOD CLONE WSCLIENT WSFEV1_RETCOMP
	Local oClone := WSFEV1_RETCOMP():NEW()
	oClone:nAMBIENTE            := ::nAMBIENTE
	oClone:cCAE                 := ::cCAE
	oClone:dCAEFCHVTO           := ::dCAEFCHVTO
	oClone:dDT_LOTE             := ::dDT_LOTE
	oClone:cERRO                := ::cERRO
	oClone:cEVENTS              := ::cEVENTS
	oClone:cID                  := ::cID
	oClone:nLOTE                := ::nLOTE
	oClone:cOBSERVACOES         := ::cOBSERVACOES
	oClone:cRECOMENDACAO        := ::cRECOMENDACAO
	oClone:cRESULTADO           := ::cRESULTADO
	oClone:cXML                 := ::cXML
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT WSFEV1_RETCOMP
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::nAMBIENTE          :=  WSAdvValue( oResponse,"_AMBIENTE","integer",NIL,NIL,NIL,"N",NIL,NIL) 
	::cCAE               :=  WSAdvValue( oResponse,"_CAE","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::dCAEFCHVTO         :=  WSAdvValue( oResponse,"_CAEFCHVTO","date",NIL,NIL,NIL,"D",NIL,NIL) 
	::dDT_LOTE           :=  WSAdvValue( oResponse,"_DT_LOTE","date",NIL,NIL,NIL,"D",NIL,NIL) 
	::cERRO              :=  WSAdvValue( oResponse,"_ERRO","base64Binary",NIL,NIL,NIL,"SB",NIL,NIL) 
	::cEVENTS            :=  WSAdvValue( oResponse,"_EVENTS","base64Binary",NIL,NIL,NIL,"SB",NIL,NIL) 
	::cID                :=  WSAdvValue( oResponse,"_ID","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::nLOTE              :=  WSAdvValue( oResponse,"_LOTE","integer",NIL,NIL,NIL,"N",NIL,NIL) 
	::cOBSERVACOES       :=  WSAdvValue( oResponse,"_OBSERVACOES","base64Binary",NIL,NIL,NIL,"SB",NIL,NIL) 
	::cRECOMENDACAO      :=  WSAdvValue( oResponse,"_RECOMENDACAO","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cRESULTADO         :=  WSAdvValue( oResponse,"_RESULTADO","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cXML               :=  WSAdvValue( oResponse,"_XML","base64Binary",NIL,NIL,NIL,"SB",NIL,NIL) 
Return

// WSDL Data Structure NFESARG

WSSTRUCT WSFEV1_NFESARG
	WSDATA   cID                       AS string
	WSDATA   cXML                      AS base64Binary
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPSEND
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT WSFEV1_NFESARG
	::Init()
Return Self

WSMETHOD INIT WSCLIENT WSFEV1_NFESARG
Return

WSMETHOD CLONE WSCLIENT WSFEV1_NFESARG
	Local oClone := WSFEV1_NFESARG():NEW()
	oClone:cID                  := ::cID
	oClone:cXML                 := ::cXML
Return oClone

WSMETHOD SOAPSEND WSCLIENT WSFEV1_NFESARG
	Local cSoap := ""
	cSoap += WSSoapValue("ID", ::cID, ::cID , "string", .T. , .F., 0 , NIL, .F.,.F.) 
	cSoap += WSSoapValue("XML", ::cXML, ::cXML , "base64Binary", .T. , .F., 0 , NIL, .F.,.F.) 
Return cSoap

// WSDL Data Structure ERRORS

WSSTRUCT WSFEV1_ERRORS
	WSDATA   cCERRMSG                  AS string OPTIONAL
	WSDATA   nNERRCODE                 AS integer OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT WSFEV1_ERRORS
	::Init()
Return Self

WSMETHOD INIT WSCLIENT WSFEV1_ERRORS
Return

WSMETHOD CLONE WSCLIENT WSFEV1_ERRORS
	Local oClone := WSFEV1_ERRORS():NEW()
	oClone:cCERRMSG             := ::cCERRMSG
	oClone:nNERRCODE            := ::nNERRCODE
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT WSFEV1_ERRORS
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::cCERRMSG           :=  WSAdvValue( oResponse,"_CERRMSG","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::nNERRCODE          :=  WSAdvValue( oResponse,"_NERRCODE","integer",NIL,NIL,NIL,"N",NIL,NIL) 
Return

// WSDL Data Structure EVENTS

WSSTRUCT WSFEV1_EVENTS
	WSDATA   cCEVENTMSG                AS string OPTIONAL
	WSDATA   nNEVENTCODE               AS integer OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT WSFEV1_EVENTS
	::Init()
Return Self

WSMETHOD INIT WSCLIENT WSFEV1_EVENTS
Return

WSMETHOD CLONE WSCLIENT WSFEV1_EVENTS
	Local oClone := WSFEV1_EVENTS():NEW()
	oClone:cCEVENTMSG           := ::cCEVENTMSG
	oClone:nNEVENTCODE          := ::nNEVENTCODE
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT WSFEV1_EVENTS
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::cCEVENTMSG         :=  WSAdvValue( oResponse,"_CEVENTMSG","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::nNEVENTCODE        :=  WSAdvValue( oResponse,"_NEVENTCODE","integer",NIL,NIL,NIL,"N",NIL,NIL) 
Return

// WSDL Data Structure FECAEASINMOV

WSSTRUCT WSFEV1_FECAEASINMOV
	WSDATA   cCCAEA                    AS string OPTIONAL
	WSDATA   cCFCHPROCESO              AS string OPTIONAL
	WSDATA   cCRESULTADO               AS string OPTIONAL
	WSDATA   nNPTOVTA                  AS integer OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT WSFEV1_FECAEASINMOV
	::Init()
Return Self

WSMETHOD INIT WSCLIENT WSFEV1_FECAEASINMOV
Return

WSMETHOD CLONE WSCLIENT WSFEV1_FECAEASINMOV
	Local oClone := WSFEV1_FECAEASINMOV():NEW()
	oClone:cCCAEA               := ::cCCAEA
	oClone:cCFCHPROCESO         := ::cCFCHPROCESO
	oClone:cCRESULTADO          := ::cCRESULTADO
	oClone:nNPTOVTA             := ::nNPTOVTA
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT WSFEV1_FECAEASINMOV
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::cCCAEA             :=  WSAdvValue( oResponse,"_CCAEA","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cCFCHPROCESO       :=  WSAdvValue( oResponse,"_CFCHPROCESO","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cCRESULTADO        :=  WSAdvValue( oResponse,"_CRESULTADO","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::nNPTOVTA           :=  WSAdvValue( oResponse,"_NPTOVTA","integer",NIL,NIL,NIL,"N",NIL,NIL) 
Return

// WSDL Data Structure FEVRESVENTAS

WSSTRUCT WSFEV1_FEVRESVENTAS
	WSDATA   cBLOQUEADO                AS string OPTIONAL
	WSDATA   cEMISIONTIPO              AS string OPTIONAL
	WSDATA   cFCHBAJA                  AS string OPTIONAL
	WSDATA   nNRO                      AS integer OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT WSFEV1_FEVRESVENTAS
	::Init()
Return Self

WSMETHOD INIT WSCLIENT WSFEV1_FEVRESVENTAS
Return

WSMETHOD CLONE WSCLIENT WSFEV1_FEVRESVENTAS
	Local oClone := WSFEV1_FEVRESVENTAS():NEW()
	oClone:cBLOQUEADO           := ::cBLOQUEADO
	oClone:cEMISIONTIPO         := ::cEMISIONTIPO
	oClone:cFCHBAJA             := ::cFCHBAJA
	oClone:nNRO                 := ::nNRO
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT WSFEV1_FEVRESVENTAS
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::cBLOQUEADO         :=  WSAdvValue( oResponse,"_BLOQUEADO","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cEMISIONTIPO       :=  WSAdvValue( oResponse,"_EMISIONTIPO","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cFCHBAJA           :=  WSAdvValue( oResponse,"_FCHBAJA","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::nNRO               :=  WSAdvValue( oResponse,"_NRO","integer",NIL,NIL,NIL,"N",NIL,NIL) 
Return

// WSDL Data Structure TIPOS

WSSTRUCT WSFEV1_TIPOS
	WSDATA   cDESC                     AS string OPTIONAL
	WSDATA   cFCHDESDE                 AS string OPTIONAL
	WSDATA   cFCHHASTA                 AS string OPTIONAL
	WSDATA   cID                       AS string OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT WSFEV1_TIPOS
	::Init()
Return Self

WSMETHOD INIT WSCLIENT WSFEV1_TIPOS
Return

WSMETHOD CLONE WSCLIENT WSFEV1_TIPOS
	Local oClone := WSFEV1_TIPOS():NEW()
	oClone:cDESC                := ::cDESC
	oClone:cFCHDESDE            := ::cFCHDESDE
	oClone:cFCHHASTA            := ::cFCHHASTA
	oClone:cID                  := ::cID
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT WSFEV1_TIPOS
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::cDESC              :=  WSAdvValue( oResponse,"_DESC","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cFCHDESDE          :=  WSAdvValue( oResponse,"_FCHDESDE","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cFCHHASTA          :=  WSAdvValue( oResponse,"_FCHHASTA","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cID                :=  WSAdvValue( oResponse,"_ID","string",NIL,NIL,NIL,"S",NIL,NIL) 
Return


