#include "tlpp-core.th"
#include "tlpp-rest.th"
#include "backoffice.revitalization.entityfieldinfo.service.ch"

namespace totvs.protheus.backoffice.revitalization.applyfromto
using namespace totvs.protheus.backoffice.reconciliation.util

//-------------------------------------------------------------------
/*/{Protheus.doc} ApplyFromToService
Classe de serviço, realizada instância e chamada de métodos de serviços

@author Totvs
/*/
//-------------------------------------------------------------------
class ApplyFromToService
    public method new()
    public method getInstance()
    public method applyFromTo()
endclass

//-------------------------------------------------------------------
/*/{Protheus.doc} ApplyFromToService
Metodo construtor

@author Totvs
/*/
//-------------------------------------------------------------------
method new() class ApplyFromToService
return

//-------------------------------------------------------------------
/*/{Protheus.doc} getInstance
Responsável por instanciar a classe controller

@author Totvs
/*/
//-------------------------------------------------------------------
method getInstance() class ApplyFromToService
    static __instance As Object

    If ValType(__instance) == "U"
        __instance := ApplyFromToService():new()
    EndIf
return
//-------------------------------------------------------------------
/*/{Protheus.doc} getEntityData
Responsável por chamar a consulta e parsear o retorno no formato JSON

@author Totvs
/*/
//-------------------------------------------------------------------
method applyFromTo(ojBody as json) class ApplyFromToService
    Local oData := ApplyFromToData():getInstance() As Object
    Local ojResponse := JsonObject():new() As Json

    ojResponse :=  oData:getApplyFromTo(ojBody)

    freeObj(oData)
return ojResponse
