#include "TOTVS.CH"

Class PLSMprBa0 from CenMapper

    Method New() Constructor

EndClass

Method New() Class PLSMprBa0
    _Super:new()

    aAdd(self:aFields,{"BA0_CODIDE" ,"companyIdentCode"})
    aAdd(self:aFields,{"BA0_CODINT" ,"operatorCode"})
    aAdd(self:aFields,{"BA0_NOMINT" ,"operatorName"})
    aAdd(self:aFields,{"BA0_CLAINT" ,"operatorClass"})
    aAdd(self:aFields,{"BA0_GRUOPE" ,"operatorGroup"})
    aAdd(self:aFields,{"BA0_CAMCOM" ,"clearingHouse"})
    aAdd(self:aFields,{"BA0_SUSEP" ,"ansRegistrationNumber"})
    aAdd(self:aFields,{"BA0_CGC" ,"cnpj"})
    aAdd(self:aFields,{"BA0_INCEST" ,"stateRegistration"})
    aAdd(self:aFields,{"BA0_EMAIL" ,"eMail"})
    aAdd(self:aFields,{"BA0_SITE" ,"homePageInInternet"})
    aAdd(self:aFields,{"BA0_DATFUN" ,"foundationDate"})
    aAdd(self:aFields,{"BA0_CEP" ,"zip"})
    aAdd(self:aFields,{"BA0_END" ,"address"})
    aAdd(self:aFields,{"BA0_NUMEND" ,"number"})
    aAdd(self:aFields,{"BA0_COMPEN" ,"complement"})
    aAdd(self:aFields,{"BA0_BAIRRO" ,"district"})
    aAdd(self:aFields,{"BA0_CODMUN" ,"cityCode"})
    aAdd(self:aFields,{"BA0_CIDADE" ,"city"})
    aAdd(self:aFields,{"BA0_EST" ,"state"})
    aAdd(self:aFields,{"BA0_TELEF1" ,"phone01"})
    aAdd(self:aFields,{"BA0_TELEF2" ,"phone02"})
    aAdd(self:aFields,{"BA0_TELEF3" ,"phone03"})
    aAdd(self:aFields,{"BA0_FAX1" ,"fax01"})
    aAdd(self:aFields,{"BA0_FAX2" ,"fax02"})
    aAdd(self:aFields,{"BA0_FAX3" ,"fax03"})
    aAdd(self:aFields,{"BA0_MATFIL" ,"headquarterOrBranch"})
    aAdd(self:aFields,{"BA0_MODOPE" ,"operModality"})
    aAdd(self:aFields,{"BA0_CODFOR" ,"supplierCode"})
    aAdd(self:aFields,{"BA0_LOJA" ,"unit"})
    aAdd(self:aFields,{"BA0_TBRFRE" ,"reinmbTable"})
    aAdd(self:aFields,{"BA0_CODTAB" ,"rdaPaymTable"})
    aAdd(self:aFields,{"BA0_CODCLI" ,"customerCode"})
    aAdd(self:aFields,{"BA0_LOJCLI" ,"customerUnit"})
    aAdd(self:aFields,{"BA0_NATURE" ,"finClssCode"})
    aAdd(self:aFields,{"BA0_TIPOPE" ,"relationship"})
    aAdd(self:aFields,{"BA0_EXPIDE" ,"rdmakeExpFImpExp"})
    aAdd(self:aFields,{"BA0_NOMCAR" ,"userIdentName"})
    aAdd(self:aFields,{"BA0_VL2BOL" ,"slip2NdCopyValue"})
    aAdd(self:aFields,{"BA0_VLCSOP" ,"oprCostStd"})
    aAdd(self:aFields,{"BA0_VENCTO" ,"dueDate"})
    aAdd(self:aFields,{"BA0_TIPVEN" ,"typeOfDueDate"})
    aAdd(self:aFields,{"BA0_VENCUS" ,"oprCostDueDate"})
    aAdd(self:aFields,{"BA0_TIPCUS" ,"tpOpCostDueDate"})
    aAdd(self:aFields,{"BA0_ENVPTU" ,"ediSendVersion"})
    aAdd(self:aFields,{"BA0_RECPTU" ,"ediRecVersion"})
    aAdd(self:aFields,{"BA0_EMAPTU" ,"ediEMail"})
    aAdd(self:aFields,{"BA0_RESPTU" ,"personRespEdi"})
    aAdd(self:aFields,{"BA0_CODRDA" ,"rdaCode"})
    aAdd(self:aFields,{"BA0_ONLINE" ,"onLineOperCia"})
    aAdd(self:aFields,{"BA0_DIARET" ,"retroacLimitDay"})
    aAdd(self:aFields,{"BA0_A100" ,"seqControlA100"})
    aAdd(self:aFields,{"BA0_A300" ,"seqControlA300"})
    aAdd(self:aFields,{"BA0_A600" ,"seqControlA600"})
    aAdd(self:aFields,{"BA0_A700" ,"seqControlA700"})
    aAdd(self:aFields,{"BA0_LIMCH" ,"interAuthLimit"})
    aAdd(self:aFields,{"BA0_TIPLIM" ,"typeOfAuthLimit"})
    aAdd(self:aFields,{"BA0_NIVVAL" ,"validLevel"})
    aAdd(self:aFields,{"BA0_GNT" ,"gnt"})
    aAdd(self:aFields,{"BA0_BLOINO" ,"blockConfinement"})
    aAdd(self:aFields,{"BA0_TIPPAG" ,"paymentMode"})
    aAdd(self:aFields,{"BA0_BCOCLI" ,"customerBank"})
    aAdd(self:aFields,{"BA0_AGECLI" ,"customerBranch"})
    aAdd(self:aFields,{"BA0_CTACLI" ,"customerAccount"})
    aAdd(self:aFields,{"BA0_PORTAD" ,"bankOfCarrier"})
    aAdd(self:aFields,{"BA0_AGEDEP" ,"branchOfCarrier"})
    aAdd(self:aFields,{"BA0_CTACOR" ,"accountOfCarrier"})
    aAdd(self:aFields,{"BA0_EMPORI" ,"sourceCompany"})
    aAdd(self:aFields,{"BA0_BASCOP" ,"baseForCopartnership"})
    aAdd(self:aFields,{"BA0_ABRANG" ,"scope"})
    aAdd(self:aFields,{"BA0_DDD" ,"ddd"})
    aAdd(self:aFields,{"BA0_NATJUR" ,"legalClass"})
    aAdd(self:aFields,{"BA0_MODALI" ,"modality"})
    aAdd(self:aFields,{"BA0_SEGMEN" ,"segmentation"})
    aAdd(self:aFields,{"BA0_CODREG" ,"area"})
    aAdd(self:aFields,{"BA0_ACOPUL" ,"pulvActions"})
    aAdd(self:aFields,{"BA0_TOTACO" ,"totalActions"})
    aAdd(self:aFields,{"BA0_RAMAL1" ,"extension1"})
    aAdd(self:aFields,{"BA0_RAMAL2" ,"extension2"})
    aAdd(self:aFields,{"BA0_RAMAL3" ,"extension3"})
    aAdd(self:aFields,{"BA0_SENQUI" ,"genPswrdForChemoAtchm"})
    aAdd(self:aFields,{"BA0_MAXRG" ,"disallowanceRecMax"})
    aAdd(self:aFields,{"BA0_SENRAD" ,"genPswrdForRadtnAtach"})
    aAdd(self:aFields,{"BA0_TPOPED" ,"tpOperadoraEdi"})
    aAdd(self:aFields,{"BA0_TISVER" ,"tissVersion"})
    aAdd(self:aFields,{"BA0_SENOPM" ,"genPswrdForOpmeAttach"})
    aAdd(self:aFields,{"BA0_PRZREC" ,"disallowanceResTerm"})
    aAdd(self:aFields,{"BA0_TPPAG" ,"exchangePaymentTerm"})
    aAdd(self:aFields,{"BA0_CRIPRZ" ,"disallowTermResource"})
    aAdd(self:aFields,{"BA0_TABPRZ" ,"termDisallowTable"})
    aAdd(self:aFields,{"BA0_CRILIM" ,"disallowForResorLim"})
    aAdd(self:aFields,{"BA0_TABLIM" ,"limitDisallowTable"})
    aAdd(self:aFields,{"BA0_AUTGES" ,"operatorSelfmanaged"})
    aAdd(self:aFields,{"BA0_DIGANE" ,"requestClinicalAttachm"})
    aAdd(self:aFields,{"BA0_VLRAPR" ,"displayedValue"})
    aAdd(self:aFields,{"BA0_ENDPOI" ,"endpointAuditAuthori"})


Return self
