#include "TOTVS.CH"

Class PLSMprBts from CenMapper

    Method New() Constructor

EndClass

Method New() Class PLSMprBts
    _Super:new()

    aAdd(self:aFields,{"BTS_MATVID" ,"lifeRegistration"})
    aAdd(self:aFields,{"BTS_NOMUSR" ,"name"})
    aAdd(self:aFields,{"BTS_SOBRN" ,"nickname"})
    aAdd(self:aFields,{"BTS_NOMCAR" ,"nameForBadge"})
    aAdd(self:aFields,{"BTS_DATNAS" ,"dateOfBirth"})
    aAdd(self:aFields,{"BTS_SEXO" ,"sex"})
    aAdd(self:aFields,{"BTS_ESTCIV" ,"maritalStatus"})
    aAdd(self:aFields,{"BTS_CPFUSR" ,"cpfCnpj"})
    aAdd(self:aFields,{"BTS_PISPAS" ,"pisPasedNumber"})
    aAdd(self:aFields,{"BTS_DRGUSR" ,"userRg"})
    aAdd(self:aFields,{"BTS_ORGEM" ,"issuedBy"})
    aAdd(self:aFields,{"BTS_RGEST" ,"stateIssuingDoc"})
    aAdd(self:aFields,{"BTS_NRCRNA" ,"healthNationalCardNbr"})
    aAdd(self:aFields,{"BTS_ORIEND" ,"originOfAddress"})
    aAdd(self:aFields,{"BTS_RELAOP" ,"relationWithOperator"})
    aAdd(self:aFields,{"BTS_CEPUSR" ,"userZipCode"})
    aAdd(self:aFields,{"BTS_ENDERE" ,"userAddress"})
    aAdd(self:aFields,{"BTS_NR_END" ,"addressNumber"})
    aAdd(self:aFields,{"BTS_COMEND" ,"addressComplement"})
    aAdd(self:aFields,{"BTS_BAIRRO" ,"userDistrict"})
    aAdd(self:aFields,{"BTS_CODMUN" ,"cityCode"})
    aAdd(self:aFields,{"BTS_MUNICI" ,"userSCity"})
    aAdd(self:aFields,{"BTS_ESTADO" ,"userState"})
    aAdd(self:aFields,{"BTS_DDD" ,"codeArea"})
    aAdd(self:aFields,{"BTS_TELEFO" ,"telephone"})
    aAdd(self:aFields,{"BTS_UNIVER" ,"univStudAndUser"})
    aAdd(self:aFields,{"BTS_INTERD" ,"confinedPatient"})
    aAdd(self:aFields,{"BTS_CORNAT" ,"skinColor"})
    aAdd(self:aFields,{"BTS_SANGUE" ,"bloodType"})
    aAdd(self:aFields,{"BTS_BITMAP" ,"photo"})
    aAdd(self:aFields,{"BTS_CODFUN" ,"functionCode"})
    aAdd(self:aFields,{"BTS_INSALU" ,"unhealthy"})
    aAdd(self:aFields,{"BTS_CODSET" ,"section"})
    aAdd(self:aFields,{"BTS_PESO" ,"weightGr"})
    aAdd(self:aFields,{"BTS_ALTURA" ,"heightCm"})
    aAdd(self:aFields,{"BTS_OBESO" ,"obesity"})
    aAdd(self:aFields,{"BTS_EMAIL" ,"eMail"})
    aAdd(self:aFields,{"BTS_CODREL" ,"religionCode"})
    aAdd(self:aFields,{"BTS_TUTELA" ,"ward"})
    aAdd(self:aFields,{"BTS_DEFFIS" ,"physicallyDisabled"})
    aAdd(self:aFields,{"BTS_INVALI" ,"invalid"})
    aAdd(self:aFields,{"BTS_DATOBI" ,"dateOfDeath"})
    aAdd(self:aFields,{"BTS_DATMAE" ,"motherBirthdate"})
    aAdd(self:aFields,{"BTS_MAE" ,"nameOfMother"})
    aAdd(self:aFields,{"BTS_CPFMAE" ,"motherCpf"})
    aAdd(self:aFields,{"BTS_PAI" ,"fatherName"})
    aAdd(self:aFields,{"BTS_DATPAI" ,"fatherBirthdate"})
    aAdd(self:aFields,{"BTS_CPFPAI" ,"fatherCpf"})
    aAdd(self:aFields,{"BTS_NOMPRE" ,"employeeName"})
    aAdd(self:aFields,{"BTS_DATCPT" ,"cptDate"})
    aAdd(self:aFields,{"BTS_CPFPRE" ,"employeeCpf"})
    aAdd(self:aFields,{"BTS_DOADOR" ,"donor"})
    aAdd(self:aFields,{"BTS_NACION" ,"employeeSNationality"})
    aAdd(self:aFields,{"BTS_CDIDEN" ,"ediIdentityCode"})
    aAdd(self:aFields,{"BTS_CDPAIS" ,"cdOfEdiIssuerCountry"})
    aAdd(self:aFields,{"BTS_NMPAIS" ,"nameEdiIssuerCountry"})
    aAdd(self:aFields,{"BTS_ORGEMI" ,"ediIssuerAgency"})
    aAdd(self:aFields,{"BTS_NOMRED" ,"reducedName"})
    aAdd(self:aFields,{"BTS_DENAVI" ,"statementOfLiveBirth"})
    aAdd(self:aFields,{"BTS_TIPPES" ,"typeOfPerson"})
    aAdd(self:aFields,{"BTS_NOMFAN" ,"tradeName"})
    aAdd(self:aFields,{"BTS_INSCES" ,"stateRegistration"})
    aAdd(self:aFields,{"BTS_NUMFAX" ,"faxNumber"})
    aAdd(self:aFields,{"BTS_DTINC" ,"isertionDate"})
    aAdd(self:aFields,{"BTS_INSCMU" ,"cityRegistration"})
    aAdd(self:aFields,{"BTS_PAGWEB" ,"webPage"})
    aAdd(self:aFields,{"BTS_CNESPE" ,"cnes"})
    aAdd(self:aFields,{"BTS_SIGLCR" ,"stateBoardAcronym"})
    aAdd(self:aFields,{"BTS_SIGCR2" ,"acronymOfSecStBoard"})
    aAdd(self:aFields,{"BTS_ESTACR" ,"stateBoardLocation"})
    aAdd(self:aFields,{"BTS_ESTCR2" ,"stateOfSecStBoard"})
    aAdd(self:aFields,{"BTS_NUMECR" ,"stateBoardNumber"})
    aAdd(self:aFields,{"BTS_DTINSC" ,"stateBoardRegDate"})
    aAdd(self:aFields,{"BTS_NUMCR2" ,"numberOfSecStBoard"})
    aAdd(self:aFields,{"BTS_DTINS2" ,"dateOfSecStBoardReg"})
    aAdd(self:aFields,{"BTS_RGIDCV" ,"civilIdRegistration"})
    aAdd(self:aFields,{"BTS_TITELE" ,"voterId"})
    aAdd(self:aFields,{"BTS_COMUNI" ,"communicationPreference"})
    aAdd(self:aFields,{"BTS_CDMNAS" ,"birthCityCode"})
    aAdd(self:aFields,{"BTS_MUNNAS" ,"birthCity"})
    aAdd(self:aFields,{"BTS_ESTNAS" ,"birthState"})
    aAdd(self:aFields,{"BTS_BANCO" ,"bankCode"})
    aAdd(self:aFields,{"BTS_TIPEND" ,"addressType"})
    aAdd(self:aFields,{"BTS_MUNRES" ,"residenceCiyCode"})
    aAdd(self:aFields,{"BTS_AGENC" ,"branch"})
    aAdd(self:aFields,{"BTS_RESEXT" ,"livesAbroad"})
    aAdd(self:aFields,{"BTS_CONTA" ,"accountNumber"})
    aAdd(self:aFields,{"BTS_DATADT" ,"adoptionDate"})
    aAdd(self:aFields,{"BTS_DATSOC" ,"dateOfSocialName"})
    aAdd(self:aFields,{"BTS_NOMSOC" ,"socialName"})
    aAdd(self:aFields,{"BTS_USASOC" ,"useOfSocialName"})
    aAdd(self:aFields,{"BTS_TIPTEL" ,"phoneType"})
    aAdd(self:aFields,{"BTS_GENSOC" ,"genderOfBeneficiary"})


Return self
