#include "protheus.ch"
#include "quicksearch.ch"
#include "tmsq20001.ch"

QSSTRUCT TMSQ20001 DESCRIPTION STR0001 MODULE 43 //DOCS EMITIDOS
 
QSMETHOD INIT QSSTRUCT TMSQ20001

Local dData := Date()	

QSTABLE "DT6" LEFT JOIN "DUD" ON "DUD_FILDOC = DT6_FILDOC AND DUD_DOC = DT6_DOC"
QSTABLE "DT6" LEFT JOIN "SA1" ON "A1_COD = DT6_CLIDEV AND A1_LOJA = DT6_LOJDEV"	
		 
// campos do SX3 e indices do SIX	
QSPARENTFIELD "A1_NOME" INDEX ORDER 2 SET RELATION TO "DT6_CLIDEV","DT6_LOJDEV" WITH "A1_COD","A1_LOJA" LABEL STR0014 //"Nome Devedor"
	 
// campos do SX3 e indices do SIX
QSPARENTFIELD "DT6_FILDOC","DT6_DOC"	INDEX ORDER 1 LABEL STR0013 //"Fil.Docto+Docto"
QSPARENTFIELD "DT6_CLIREM"				INDEX ORDER 6		//Remetente
QSPARENTFIELD "DT6_CLIDES"				INDEX ORDER 7		//Destinatário	
QSPARENTFIELD "DT6_CLIDEV"				INDEX ORDER 10	//Devedor
		
// campos do SX3
QSFIELD "DT6_FILDOC "			LABEL STR0002 //"Fil.Docto. "
QSFIELD "DT6_DOC "				LABEL STR0003 //"Num.Docto. "
QSFIELD "DT6_SERIE" 			LABEL STR0004 //"Serie"
QSFIELD "DT6_DATEMI"			LABEL STR0005 //"Data de Emissao"
QSFIELD "DT6_NUM"				LABEL STR0006 //"Num. Titulo"
QSFIELD "DT6_STATUS"			LABEL STR0007 //"Status"	

QSACTION MENUDEF "TMSA500" OPERATION 2 LABEL STR0008 //"Visualizar"
		
QSFILTER STR0009 WHERE "DT6_SERTMS <> '1' AND DT6_DATEMI = '"+DTOS(dData)		+"'" //"Ultimo dia" 
QSFILTER STR0010 WHERE "DT6_SERTMS <> '1' AND DT6_DATEMI > '"+DTOS(dData-7)  	+"'" //"Ultimos 7 dias"
QSFILTER STR0011 WHERE "DT6_SERTMS <> '1' AND DT6_DATEMI > '"+DTOS(dData-30)	+"'" //"Ultimos 30 dias" 
QSFILTER STR0012 WHERE "DT6_SERTMS <> '1' AND DT6_DATEMI > '"+DTOS(dData-360)	+"'" //"Ultimos 365 dias"
			
Return