CREATE PROCEDURE FISA08_##(
    @IN_FILIAL      CHAR('F3_FILIAL'),	
	@TIPOMOV        CHAR(1),
    @ENTRADA_DE     CHAR(8),
    @ENTRADA_ATE    CHAR(8),
    @CFOP           CHAR(1),
    @OUT_RESULT     CHAR(1) OUTPUT
) AS
/*---------------------------------------------------------------------------------------------------------------------
    Versão      -  <v> Protheus P12 </v>
    Assinatura  -  <a> 001 </a>
    Programa    -  <s> FISA008 </s>
    Descricao   -  <d> EFD Contribuições - Arquivo </d>
    Entrada     -  <ri> @IN_FILIAL - Filial que será processada
                        @TIPOMOV - Tipo de movimento, definirá se é Entrada ou Saída
                        @ENTRADA_DE - Entrada De
                        @ENTRADA_ATE - Entrada Até
                        @CFOP - CFOP que definira se a operação será Entrada ou Saída
    Saida       -  <ro> @OUT_RESULT - Indica o termino da execução da procedure: 0 - Falha; 1 - Sucesso </ro>
    Responsavel :  <r> Matheus Bispo </r>
    Data        :  <dt> 10/09/2024 </dt>
----------------------------------------------------------------------------------------------------------------------*/
DECLARE @SF3        CHAR(3)
DECLARE @SFT        CHAR(3)
DECLARE @FILIAL_SF3 VARCHAR('F3_FILIAL')
DECLARE @FILIAL_SFT VARCHAR('FT_FILIAL')

BEGIN
    
    SELECT @SF3 = 'SF3'
    SELECT @SFT = 'SFT'
    SELECT @OUT_RESULT = '0'

    EXEC XFILIAL_## @SF3, @IN_FILIAL, @FILIAL_SF3 OUTPUT
    EXEC XFILIAL_## @SFT, @IN_FILIAL, @FILIAL_SFT OUTPUT
    
    ##IF_001({|| cPaisLoc == 'BRA'})

        IF @TIPOMOV = 'E'
        BEGIN
            INSERT INTO TEF### (
                FT_FILIAL, FT_TIPOMOV, FT_ENTRADA, FT_SERIE, FT_NFISCAL, FT_CLIEFOR, FT_LOJA, FT_ITEM, FT_PRODUTO, FT_CFOP,
                FT_ESPECIE, FT_ALIQPIS, FT_ALIQCOF, FT_ALIQCF3, FT_ALIQPS3, FT_CSTPIS, FT_CSTCOF, FT_PAUTPIS, FT_PAUTCOF, FT_TNATREC,
                FT_CNATREC, FT_GRUPONC, FT_DTFIMNT, FT_CODBCC, FT_QUANT, FT_EMISSAO, FT_VALPIS, FT_VALCOF, FT_VALCONT, FT_TOTAL,
                FT_BASEPIS, FT_BASECOF, FT_BASECF3, FT_BASEPS3, FT_VALPS3, FT_VALCF3, FT_MVALCOF, FT_MALQCOF, FT_MVALPIS, FT_MALQPIS,
                FT_NFELETR, FT_FORMUL, FT_CHVNFE, FT_DTCANC, FT_TIPO, FT_DESCONT, FT_CONTA, FT_VRETPIS, FT_VRETCOF, FT_VALICM, FT_OUTRICM,
                FT_OUTRRET, FT_ISENICM, FT_ISENRET, FT_INDNTFR, FT_BASEICM, FT_DESPESA, FT_SEGURO, FT_FRETE, FT_BASERET, FT_OBSERV,
                FT_DESCZFR, FT_ALIQICM, FT_ALIQSOL, FT_BASEIPI, FT_ALIQIPI, FT_VALIPI, FT_DESCICM, FT_POSIPI, FT_CREDST, FT_ESTADO,
                FT_ICMSRET, FT_ANTICMS, FT_OBSSOL, FT_SOLTRIB, FT_CODNFE, FT_NORESP, FT_RGESPST, FT_PDV, FT_CTIPI, FT_CLASFIS,
                FT_NATOPER, FT_CLIDVMC, FT_LOJDVMC, FT_SERSAT, F3_CODRSEF, F3_CLASCO, SF3RECNO, SFTRECNO
                )
            SELECT SFT.FT_FILIAL, SFT.FT_TIPOMOV, SFT.FT_ENTRADA, #SERIENFID# FT_SERIE, SFT.FT_NFISCAL, SFT.FT_CLIEFOR, SFT.FT_LOJA, SFT.FT_ITEM, SFT.FT_PRODUTO, SFT.FT_CFOP,
                SFT.FT_ESPECIE, SFT.FT_ALIQPIS, SFT.FT_ALIQCOF, SFT.FT_ALIQCF3, SFT.FT_ALIQPS3, SFT.FT_CSTPIS, SFT.FT_CSTCOF, SFT.FT_PAUTPIS, SFT.FT_PAUTCOF, SFT.FT_TNATREC,
                SFT.FT_CNATREC, SFT.FT_GRUPONC, SFT.FT_DTFIMNT, SFT.FT_CODBCC, SFT.FT_QUANT, SFT.FT_EMISSAO, SFT.FT_VALPIS, SFT.FT_VALCOF, SFT.FT_VALCONT, SFT.FT_TOTAL,
                SFT.FT_BASEPIS, SFT.FT_BASECOF, SFT.FT_BASECF3, SFT.FT_BASEPS3, SFT.FT_VALPS3, SFT.FT_VALCF3, SFT.FT_MVALCOF, SFT.FT_MALQCOF, SFT.FT_MVALPIS, SFT.FT_MALQPIS,
                SFT.FT_NFELETR, SFT.FT_FORMUL, SFT.FT_CHVNFE, SFT.FT_DTCANC, SFT.FT_TIPO, SFT.FT_DESCONT, SFT.FT_CONTA, SFT.FT_VRETPIS, SFT.FT_VRETCOF, SFT.FT_VALICM, SFT.FT_OUTRICM,
                SFT.FT_OUTRRET, SFT.FT_ISENICM, SFT.FT_ISENRET, SFT.FT_INDNTFR, SFT.FT_BASEICM, SFT.FT_DESPESA, SFT.FT_SEGURO, SFT.FT_FRETE, SFT.FT_BASERET, SFT.FT_OBSERV,
                SFT.FT_DESCZFR, SFT.FT_ALIQICM, SFT.FT_ALIQSOL, SFT.FT_BASEIPI, SFT.FT_ALIQIPI, SFT.FT_VALIPI, SFT.FT_DESCICM, SFT.FT_POSIPI, SFT.FT_CREDST, SFT.FT_ESTADO,
                SFT.FT_ICMSRET, SFT.FT_ANTICMS, SFT.FT_OBSSOL, SFT.FT_SOLTRIB, SFT.FT_CODNFE, SFT.FT_NORESP, SFT.FT_RGESPST, SFT.FT_PDV, SFT.FT_CTIPI, SFT.FT_CLASFIS,
                SFT.FT_NATOPER, SFT.FT_CLIDVMC, SFT.FT_LOJDVMC, SFT.FT_SERSAT,  SF3.F3_CODRSEF, SF3.F3_CLASCO, SF3.R_E_C_N_O_ SF3RECNO, SFT.R_E_C_N_O_ SFTRECNO
            FROM SF3### SF3 
            INNER JOIN SFT### SFT
                ON SFT.FT_FILIAL = @FILIAL_SFT
                    AND SFT.FT_TIPOMOV = @TIPOMOV
                    AND SFT.FT_CLIEFOR = SF3.F3_CLIEFOR
                    AND SFT.FT_LOJA = SF3.F3_LOJA
                    AND SFT.FT_SERIE = SF3.F3_SERIE
                    AND SFT.FT_NFISCAL = SF3.F3_NFISCAL
                    AND SFT.FT_IDENTF3 = SF3.F3_IDENTFT
                    AND SFT.FT_ENTRADA = SF3.F3_ENTRADA
                    ##IF_002({ || GetNewPar('MV_NFCOMPL', .T.) == .F.})
                        AND SFT.FT_TIPO NOT IN ('I', 'P')
                    ##ENDIF_002
                    AND SFT.D_E_L_E_T_ = ' '
            WHERE SF3.F3_FILIAL = @FILIAL_SF3
                AND SF3.F3_ENTRADA >= @ENTRADA_DE
                AND SF3.F3_ENTRADA <= @ENTRADA_ATE
                AND SF3.F3_CFO < @CFOP
                AND SF3.D_E_L_E_T_ = ' '
                
            SELECT @OUT_RESULT = '1'
        END
        ELSE IF @TIPOMOV = 'S'
        BEGIN
            INSERT INTO TEF### (
                FT_FILIAL, FT_TIPOMOV, FT_ENTRADA, FT_SERIE, FT_NFISCAL, FT_CLIEFOR, FT_LOJA, FT_ITEM, FT_PRODUTO, FT_CFOP,
                FT_ESPECIE, FT_ALIQPIS, FT_ALIQCOF, FT_ALIQCF3, FT_ALIQPS3, FT_CSTPIS, FT_CSTCOF, FT_PAUTPIS, FT_PAUTCOF, FT_TNATREC,
                FT_CNATREC, FT_GRUPONC, FT_DTFIMNT, FT_CODBCC, FT_QUANT, FT_EMISSAO, FT_VALPIS, FT_VALCOF, FT_VALCONT, FT_TOTAL,
                FT_BASEPIS, FT_BASECOF, FT_BASECF3, FT_BASEPS3, FT_VALPS3, FT_VALCF3, FT_MVALCOF, FT_MALQCOF, FT_MVALPIS, FT_MALQPIS,
                FT_NFELETR, FT_FORMUL, FT_CHVNFE, FT_DTCANC, FT_TIPO, FT_DESCONT, FT_CONTA, FT_VRETPIS, FT_VRETCOF, FT_VALICM, FT_OUTRICM,
                FT_OUTRRET, FT_ISENICM, FT_ISENRET, FT_INDNTFR, FT_BASEICM, FT_DESPESA, FT_SEGURO, FT_FRETE, FT_BASERET, FT_OBSERV,
                FT_DESCZFR, FT_ALIQICM, FT_ALIQSOL, FT_BASEIPI, FT_ALIQIPI, FT_VALIPI, FT_DESCICM, FT_POSIPI, FT_CREDST, FT_ESTADO,
                FT_ICMSRET, FT_ANTICMS, FT_OBSSOL, FT_SOLTRIB, FT_CODNFE, FT_NORESP, FT_RGESPST, FT_PDV, FT_CTIPI, FT_CLASFIS,
                FT_NATOPER, FT_CLIDVMC, FT_LOJDVMC, FT_SERSAT, F3_CODRSEF, F3_CLASCO, SF3RECNO, SFTRECNO
                )
            SELECT SFT.FT_FILIAL, SFT.FT_TIPOMOV, SFT.FT_ENTRADA, #SERIENFID# FT_SERIE, SFT.FT_NFISCAL, SFT.FT_CLIEFOR, SFT.FT_LOJA, SFT.FT_ITEM, SFT.FT_PRODUTO, SFT.FT_CFOP,
                SFT.FT_ESPECIE, SFT.FT_ALIQPIS, SFT.FT_ALIQCOF, SFT.FT_ALIQCF3, SFT.FT_ALIQPS3, SFT.FT_CSTPIS, SFT.FT_CSTCOF, SFT.FT_PAUTPIS, SFT.FT_PAUTCOF, SFT.FT_TNATREC,
                SFT.FT_CNATREC, SFT.FT_GRUPONC, SFT.FT_DTFIMNT, SFT.FT_CODBCC, SFT.FT_QUANT, SFT.FT_EMISSAO, SFT.FT_VALPIS, SFT.FT_VALCOF, SFT.FT_VALCONT, SFT.FT_TOTAL,
                SFT.FT_BASEPIS, SFT.FT_BASECOF, SFT.FT_BASECF3, SFT.FT_BASEPS3, SFT.FT_VALPS3, SFT.FT_VALCF3, SFT.FT_MVALCOF, SFT.FT_MALQCOF, SFT.FT_MVALPIS, SFT.FT_MALQPIS,
                SFT.FT_NFELETR, SFT.FT_FORMUL, SFT.FT_CHVNFE, SFT.FT_DTCANC, SFT.FT_TIPO, SFT.FT_DESCONT, SFT.FT_CONTA, SFT.FT_VRETPIS, SFT.FT_VRETCOF, SFT.FT_VALICM, SFT.FT_OUTRICM,
                SFT.FT_OUTRRET, SFT.FT_ISENICM, SFT.FT_ISENRET, SFT.FT_INDNTFR, SFT.FT_BASEICM, SFT.FT_DESPESA, SFT.FT_SEGURO, SFT.FT_FRETE, SFT.FT_BASERET, SFT.FT_OBSERV,
                SFT.FT_DESCZFR, SFT.FT_ALIQICM, SFT.FT_ALIQSOL, SFT.FT_BASEIPI, SFT.FT_ALIQIPI, SFT.FT_VALIPI, SFT.FT_DESCICM, SFT.FT_POSIPI, SFT.FT_CREDST, SFT.FT_ESTADO,
                SFT.FT_ICMSRET, SFT.FT_ANTICMS, SFT.FT_OBSSOL, SFT.FT_SOLTRIB, SFT.FT_CODNFE, SFT.FT_NORESP, SFT.FT_RGESPST, SFT.FT_PDV, SFT.FT_CTIPI, SFT.FT_CLASFIS,
                SFT.FT_NATOPER, SFT.FT_CLIDVMC, SFT.FT_LOJDVMC, SFT.FT_SERSAT,  SF3.F3_CODRSEF, SF3.F3_CLASCO, SF3.R_E_C_N_O_ SF3RECNO, SFT.R_E_C_N_O_ SFTRECNO
            FROM SF3### SF3 
            INNER JOIN SFT### SFT
                ON SFT.FT_FILIAL = @FILIAL_SFT
                    AND SFT.FT_TIPOMOV = @TIPOMOV
                    AND SFT.FT_CLIEFOR = SF3.F3_CLIEFOR
                    AND SFT.FT_LOJA = SF3.F3_LOJA
                    AND SFT.FT_SERIE = SF3.F3_SERIE
                    AND SFT.FT_NFISCAL = SF3.F3_NFISCAL
                    AND SFT.FT_IDENTF3 = SF3.F3_IDENTFT
                    AND SFT.FT_ENTRADA = SF3.F3_ENTRADA
                    ##IF_003({ || GetNewPar('MV_NFCOMPL', .T.) == .F.})
                        AND SFT.FT_TIPO NOT IN ('I', 'P')
                    ##ENDIF_003
                    AND SFT.D_E_L_E_T_ = ' '
            WHERE SF3.F3_FILIAL = @FILIAL_SF3
                AND SF3.F3_ENTRADA >= @ENTRADA_DE
                AND SF3.F3_ENTRADA <= @ENTRADA_ATE
                AND SF3.F3_CFO > @CFOP
                AND SF3.D_E_L_E_T_ = ' '

            SELECT @OUT_RESULT = '1'        
        END
    ##ENDIF_001
END