#INCLUDE "PROTHEUS.CH"
#INCLUDE "QUICKSEARCH.CH"
#INCLUDE "TECQ001.CH"

QSSTRUCT TECQ001 DESCRIPTION STR0001 MODULE 28 // "Alocação por Cliente" 

QSMETHOD INIT QSSTRUCT TECQ001
Local cWhere := ""
	
	QSTABLE "CN9" JOIN "ABQ" ON "ABQ.ABQ_CONTRT = CN9.CN9_NUMERO"
	QSTABLE "CN9" JOIN "CNC" ON "CNC.CNC_NUMERO = CN9.CN9_NUMERO AND CNC.CNC_REVISA = CN9.CN9_REVISA"
	QSTABLE "CN9" LEFT JOIN "ABB" ON "ABB.ABB_IDCFAL = CN9.CN9_NUMERO || ABQ.ABQ_ITEM || 'CN9' AND ABB.ABB_ATIVO = '1'"
	QSTABLE "ABB" LEFT JOIN "ABS" ON "ABS.ABS_LOCAL = ABB.ABB_LOCAL"
	QSTABLE "ABB" LEFT JOIN "AA1" ON "AA1.AA1_CODTEC = ABB.ABB_CODTEC"
	QSTABLE "CNC" JOIN "SA1" ON "SA1.A1_COD = CNC.CNC_CLIENT AND SA1.A1_LOJA = CNC.CNC_LOJACL"
	
	// campos do SX3 e indices do SIX
	QSPARENTFIELD "A1_COD" INDEX ORDER 1 
	QSPARENTFIELD "ABB_CODTEC" INDEX ORDER 1 
	
	// campos do SX3
	QSFIELD "ABB_DTINI","ABB_CODTEC","AA1_NOMTEC","CNC_CLIENT","ABS_DESCRI"
	
	QSACTION MENUDEF "TECA020" OPERATION 1 LABEL STR0002 // "Visualizar Atendente"
	
	cWhere := "CN9.CN9_SITUAC = '05' AND ABB.ABB_DTINI BETWEEN '{1}' AND '{2}'"
	
	QSFILTER STR0003 WHERE StrTran( StrTran(cWhere, "{1}", DTOS(Date())), "{2}", DTOS(Date()) ) // "Hoje" 
	
	QSFILTER STR0004 WHERE StrTran( StrTran(cWhere, "{1}", DTOS(Date() - 7)), "{2}", DTOS(Date()) ) // "Últimos 7 dias" 
	QSFILTER STR0005 WHERE StrTran( StrTran(cWhere, "{1}", DTOS(Date() - 15)), "{2}", DTOS(Date())) // "Últimos 15 dias" 
	
	QSFILTER STR0006 WHERE StrTran( StrTran(cWhere, "{1}", DTOS(Date())), "{2}", DTOS(Date() + 7)) // "Próximos 7 dias"
	QSFILTER STR0007 WHERE StrTran( StrTran(cWhere, "{1}", DTOS(Date())), "{2}", DTOS(Date() + 15)) // "Próximos 15 dias" 
Return
