#INCLUDE "loca030.ch" 
#INCLUDE "RWMAKE.CH"                                            
#INCLUDE "PROTHEUS.CH"
#INCLUDE "TOPCONN.CH"                                             

/*/{PROTHEUS.DOC} LOCA030.PRW
ITUP BUSINESS - TOTVS RENTAL
AUTORIZACAO DE SERVICO DE FROTA
@TYPE FUNCTION
@AUTHOR FRANK ZWARG FUGA
@SINCE 03/12/2020
@VERSION P12
@HISTORY 03/12/2020, FRANK ZWARG FUGA, FONTE PRODUTIZADO.
/*/

FUNCTION LOCA030(_CNRAS,_CFILEPDF)
LOCAL AALIAS 	 	:= GETAREA()
LOCAL AAREAZA0   	:= FP0->(GETAREA())
LOCAL AAREADTQ   	:= FQ5->(GETAREA())
LOCAL LGERAPDF		:= SUPERGETMV("MV_LOCX213",,.T.)   //LEANDRO 
Local CQUERY

PRIVATE CCABEC   	:= ""
PRIVATE CPERG    	:= "LOCP059" //CRIAR PERGUNTA
PRIVATE CLJCLIE  	:="" 
PRIVATE CINCR    	:=""
PRIVATE COBSG    	:= ""
PRIVATE OLBXITENS 
PRIVATE LPDF     	:= .F.
PRIVATE CNRASORI

DEFAULT _CNRAS	 	:= ""
DEFAULT _CFILEPDF 	:= ""

	// GERA PDF DA FQ5_AS 
	IF !LGERAPDF
		RETURN NIL
	ENDIF
	
	IF !EMPTY(_CFILEPDF)
		LPDF := .T.
	ENDIF

	IF EMPTY(_CNRAS)
		//VALIDPERG()
		IF ! PERGUNTE(CPERG,.T.)
			RETURN NIL
		ENDIF
		CRET := MV_PAR01
	ELSE
		CRET := _CNRAS
	ENDIF

	IF EMPTY(CRET)
		RESTAREA(AAREAZA0)
		RESTAREA(AAREADTQ)
		RESTAREA(AALIAS)
		RETURN(NIL)
	ENDIF         

	// PREENCHE COM OS DADOS DA PROPOSTA
	// DTQ DE FRETE
	DBSELECTAREA( "FQ5" )
	DBSETORDER(9)
	DBSEEK( XFILIAL("FQ5") + CRET )
	X_PROJETO 	:= FQ5->FQ5_SOT										// PROJETO ORIGINAL
	X_VIAGEM  	:= FQ5->FQ5_VIAGEM									// VIAGEM
	X_OBRA    	:= FQ5->FQ5_OBRA   									// OBRA
	X_ASF     	:= TRANSFORM(FQ5->FQ5_AS,"@R XX-XXXXX-XXX-XX-XX") 	// NUMERO AS
	NPOSVREA 	:= FQ5->(RECNO()) 									// POSICAO DO POINTER PARA A AS REAL

	// DADOS DO PROJETO
	DBSELECTAREA( "FP0" )
	DBSETORDER(1)
	DBSEEK(XFILIAL( "FP0" ) + X_PROJETO)

	CCODCLI  	:= FP0->FP0_CLI
	CLJCLIE  	:= FP0->FP0_LOJA

	CINCR    	:= FP0->FP0_CLIINS
	CGC      	:= FP0->FP0_CLICGC
	CENDERE  	:= FP0->FP0_CLIEND
	CBAIRRO  	:= FP0->FP0_CLIBAI
	CMUNICI  	:= FP0->FP0_CLIMUN
	CESTADO  	:= FP0->FP0_CLIEST
	CCEP     	:= FP0->FP0_CLICEP

	CCONTATO 	:= ALLTRIM(FP0->FP0_CLICON)
	CTEL     	:= "( "+FP0->FP0_CLIDDD+" )" + " "+ FP0->FP0_CLITEL

	CENDCOB 	:= FP0->FP0_CLIEND
	CBAICOB 	:= FP0->FP0_CLIBAI
	CMUNCOB 	:= FP0->FP0_CLIMUN
	CESTCOB 	:= FP0->FP0_CLIEST
	CCEPCOB 	:= FP0->FP0_CLICEP

	CENDCAR 	:= ""
	CBAICAR 	:= ""
	CMUNCAR 	:= ""
	CUFCAR  	:= ""
	CENDDES 	:= ""
	CBAIDES 	:= ""
	CMUNDES 	:= ""
	CUFDES 		:= ""
	DDESLIMITE 	:= ""
				
	DBSELECTAREA("FQ5")
	DBSETORDER(1)

	// POSICIONA CONJUNTO TRANSPORTADORES
	IF SELECT("TRAB_VIAORI") > 0
		TRAB_VIAORI->(DBCLOSEAREA())
	ENDIF

	/*
	+ FQ5->FQ5_VIAGEM +
	*/

	CQUERY := " SELECT ZLW.R_E_C_N_O_ FPS_RECNO , DTQ.R_E_C_N_O_ FQ5_RECNO "
	CQUERY += " FROM " + RETSQLNAME('FPS') + " ZLW "
	CQUERY +=        " JOIN " + RETSQLNAME('FQ5') + " DTQ ON FPS_VIAORI = FQ5_VIAGEM"
	CQUERY += " WHERE  ZLW.D_E_L_E_T_ = '' AND DTQ.D_E_L_E_T_ = ''" 
	CQUERY +=   " AND  ZLW.FPS_VIAGEM = ? "
	CQUERY := CHANGEQUERY(CQUERY) 
	aBindParam := {FQ5->FQ5_VIAGEM}
	MPSysOpenQuery(cQuery,"TRAB_VIAORI",,,aBindParam)
	//DBUSEAREA(.T.,"TOPCONN", TCGENQRY(,,CQUERY),"TRAB_VIAORI", .F., .T.)

	FPS->(DBGOTO( TRAB_VIAORI->FPS_RECNO ))
	FQ5->(DBGOTO( TRAB_VIAORI->FQ5_RECNO ))

	IF SELECT("TRAB_VIAORI") > 0
		TRAB_VIAORI->(DBCLOSEAREA())
	ENDIF

	// POSICIONA CONJUNTO TRANSPORTADORES ZUC
	IF SELECT("TRAB_VIAORI") > 0
		TRAB_VIAORI->(DBCLOSEAREA())
	ENDIF

	/*
	+ FQ5->FQ5_VIAGEM +
	*/

	CQUERY := " SELECT ZUC.R_E_C_N_O_ FQ7_RECNO , DTQ.R_E_C_N_O_ FQ5_RECNO "
	CQUERY += " FROM " + RETSQLNAME('FQ7') + " ZUC"
	//CQUERY+=       " JOIN " + RETSQLNAME('FQ5') + " DTQ ON FPS_VIAORI = FQ5_VIAGEM"
	CQUERY +=        " JOIN " + RETSQLNAME('FQ5') + " DTQ ON FQ7_VIAORI = FQ5_VIAGEM"
	CQUERY += " WHERE  ZUC.D_E_L_E_T_ = '' AND DTQ.D_E_L_E_T_ = ''"
	CQUERY +=   " AND  FQ7_VIAGEM = ? "
	CQUERY := CHANGEQUERY(CQUERY) 
	aBindParam := {FQ5->FQ5_VIAGEM}
	MPSysOpenQuery(cQuery,"TRAB_VIAORI",,,aBindParam)
	//DBUSEAREA(.T.,"TOPCONN", TCGENQRY(,,CQUERY),"TRAB_VIAORI", .F., .T.)

	FQ7->(DBGOTO( TRAB_VIAORI->FQ7_RECNO ))
	FQ5->(DBGOTO( TRAB_VIAORI->FQ5_RECNO ))

	IF SELECT("TRAB_VIAORI") > 0
		TRAB_VIAORI->(DBCLOSEAREA())
	ENDIF

	DBSELECTAREA("FP1")
	DBSETORDER(1)
	DBSEEK(XFILIAL("FP1")+X_PROJETO+X_OBRA)

	CLOCCAR    := FP1->FP1_NOMORI
	DCARPREV   := FQ5->FQ5_DTINI
	CENDCAR    := FPS->FPS_ENDORI
	CBAICAR    := FPS->FPS_BRRORI
	CMUNCAR    := FPS->FPS_MUNORI+ " - " + FPS->FPS_CIDORI
	CUFCAR     := FPS->FPS_UFORI
	CENDDES    := FPS->FPS_ENDEST
	CBAIDES    := FPS->FPS_BRRDES
	CMUNDES    := FPS->FPS_MUNDES + " - " + FPS->FPS_CIDEST
	CUFDES 	   := FPS->FPS_UFDEST
	DDESLIMITE := FPS->FPS_DTLIM

	IF EMPTY(CENDCAR)
		CENDCAR    := FQ7->FQ7_ENDORI
		CBAICAR    := FQ7->FQ7_BRRORI
		CMUNCAR    := FQ7->FQ7_MUNORI//+ " - " + FPS->FPS_CIDORI
		CUFCAR     := FQ7->FQ7_UFORI
		CENDDES    := FQ7->FQ7_ENDEST
		CBAIDES    := FQ7->FQ7_BRRDES
		CMUNDES    := FQ7->FQ7_MUNDES// + " - " + FPS->FPS_CIDEST
		CUFDES 	   := FQ7->FQ7_UFDEST
		DDESLIMITE := FQ7->FQ7_DTLIM
	ENDIF

	IF EMPTY(CENDCAR)
		CENDCAR    := FP1->FP1_ENDORI
		CBAICAR    := FP1->FP1_BAIORI
		CMUNCAR    := FP1->FP1_MUNORI
		CUFCAR     := FP1->FP1_ESTORI
		CENDDES    := FP1->FP1_ENDDES
		CBAIDES    := FP1->FP1_BAIDES
		CMUNDES    := FP1->FP1_MUNDES
		CUFDES 	   := FP1->FP1_ESTDES
	ENDIF 

	CTELCAR    := FP1->FP1_TELORI
	CCONCAR    := FP1->FP1_CONORI
	CLOCDES    := FP1->FP1_DESTIN
	CDESPREV   := FQ5->FQ5_DTFIM
	CTELDES    := FP1->FP1_TELDES
	CCONDES    := FP1->FP1_CONDES

	//DBSELECTAREA("FQ5")
	//DBSETORDER(1)
	//DBSEEK(XFILIAL("FQ5")+X_VIAGEM_ORIGEM, .T.)

	CNRASORI := TRANSFORM(FQ5->FQ5_AS,"@R XX-XXXXX-XXX-XX-XX") 	// NUMERO DO PROJETO QUE DISPAROU A ASF
	NPOSVORI := FQ5->(RECNO()) // POINTER DO PROJETO QUE DISPAROU A ASF

	IF !EMPTY(FP0->FP0_CLI) .AND. !EMPTY(FP0->FP0_LOJA) 
		AAREASA1 := SA1->( GETAREA() )
		DBSELECTAREA("SA1")
		DBSETORDER(1)
		IF MSSEEK(XFILIAL("SA1") + FP0->FP0_CLI + FP0->FP0_LOJA )
			//DADOS CADASTRAIS
			CCODCLI := SA1->A1_COD
			CLJCLIE := SA1->A1_LOJA
			CINCR   := FP0->FP0_CLIINS
			CGC     := FP0->FP0_CLICGC
			CENDERE := FP0->FP0_CLIEND
			CBAIRRO := FP0->FP0_CLIBAI
			CMUNICI := FP0->FP0_CLIMUN
			CESTADO := FP0->FP0_CLIEST
			CCEP    := FP0->FP0_CLICEP
				
			IF !EMPTY(SA1->A1_ENDCOB)
				CENDCOB := SA1->A1_ENDCOB
				CBAICOB := SA1->A1_BAIRROC
				CMUNCOB := SA1->A1_MUNC
				CESTCOB := SA1->A1_ESTC
				CCEPCOB := SA1->A1_CEPC
			ELSE
				CENDCOB := SA1->A1_END
				CBAICOB := SA1->A1_BAIRRO
				CMUNCOB := SA1->A1_MUN
				CESTCOB := SA1->A1_EST
				CCEPCOB := SA1->A1_CEP
			ENDIF
			CTEL     := "( "+SA1->A1_DDD+" )" + " "+ SA1->A1_TEL
				
			CCONTATO := SA1->A1_CONTATO
			IF EMPTY(CCONTATO)
				CCONTATO := ALLTRIM(FP0->FP0_CLICON)       
			ENDIF      
		ENDIF
		RESTAREA(AAREASA1)
	ENDIF

	// --> SELECAO DA IMPRESSORA. 
	IF ! LPDF
		OOBJPRINT:= TMSPRINTER():NEW(CCABEC)
		OOBJPRINT:SETSIZE( 210, 297 )
	ELSE
		OOBJPRINT := FWMSPRINTER():NEW(_CFILEPDF,6,.F.,,.T.)
		OOBJPRINT:SETRESOLUTION(290)
		OOBJPRINT:SETPORTRAIT()
		OOBJPRINT:SETPAPERSIZE(2)			// A4
		OOBJPRINT:SETMARGIN(60,60,60,60) 	// NESQUERDA, NSUPERIOR, NDIREITA, NINFERIOR 
		OOBJPRINT:CPATHPDF := ALLTRIM(GETTEMPPATH())
	ENDIF

	LJMSGRUN(STR0001,,{|| IMP_TRANF() }) //"POR FAVOR AGUARDE, AUTORIZAÇÃO DE SERVIÇO..."

	// --> MOSTRA RELATORIO PARA IMPRIMIR.
	IF ! LPDF
		OOBJPRINT:PREVIEW()
	ELSE
		OOBJPRINT:PREVIEW("PDF")
	//	OOBJPRINT:PRINT("PDF")
	ENDIF

	RESTAREA(AAREAZA0)
	RESTAREA(AAREADTQ)
	RESTAREA(AALIAS)

RETURN(NIL)



/*
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
±±ÉÍÍÍÍÍÍÍÍÍÍÑÍÍÍÍÍÍÍÍÍÍÍËÍÍÍÍÍÍÍÑÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍËÍÍÍÍÍÍÑÍÍÍÍÍÍÍÍÍÍÍÍ»±±
±±ºPROGRAMA  ³ IMP_TRAN  º AUTOR ³ IT UP BUSINESS     º DATA ³ 30/06/2007 º±±
±±ÌÍÍÍÍÍÍÍÍÍÍØÍÍÍÍÍÍÍÍÍÍÍÊÍÍÍÍÍÍÍÏÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÊÍÍÍÍÍÍÏÍÍÍÍÍÍÍÍÍÍÍÍ¹±±
±±ºDESCRICAO ³IMPRESSAO DA AUTORIZACAO DE TRANSPORTE.                     º±±
±±ÈÍÍÍÍÍÍÍÍÍÍÏÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ¼±±
±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
ßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßß
*/
STATIC FUNCTION IMP_TRANF

LOCAL 	AAREA       := GETAREA()

PRIVATE OFONTE01	:= NIL
PRIVATE OFONTE02	:= NIL
PRIVATE OFONTE03	:= NIL
PRIVATE OFONTE04	:= NIL
PRIVATE OFONTE05	:= NIL
PRIVATE OFONTE06	:= NIL
PRIVATE OFONTE07	:= NIL
PRIVATE OFONTE08    := NIL

// --> INICIALIZA OBJETOS DA CLASSE TMSPRINTER.
PRIVATE OFONT1  := TFONT():NEW("ARIAL"     ,11,IIF(LPDF,10,11),,.F.,,,,,.F.)   // NORMAL
PRIVATE OFONT2  := TFONT():NEW("ARIAL"     ,18,IIF(LPDF,17,18),,.T.,,,,,.F.)   // NEGRITO
PRIVATE OFONT3  := TFONT():NEW("ARIAL"     ,11,IIF(LPDF,10,11),,.T.,,,,,.T.)   // NEGRITO / SUBLINHADO
PRIVATE OFONT4  := TFONT():NEW("ARIAL"     ,10,IIF(LPDF,09,10),,.F.,,,,,.F.)   // NORMAL
PRIVATE OFONT5  := TFONT():NEW("ARIAL"     ,10,IIF(LPDF,09,10),,.T.,,,,,.F.)   // NEGRITO
PRIVATE OFONT6  := TFONT():NEW("ARIAL"     ,10,IIF(LPDF,09,10),,.T.,,,,,.T.)   // NEGRITO / SUBLINHADO
PRIVATE OFONT7  := TFONT():NEW("VENDANA"   ,07,IIF(LPDF,06,07),,.F.,,,,,.F.)   // NORMAL
PRIVATE OFONT8  := TFONT():NEW("VENDANA"   ,07,IIF(LPDF,06,07),,.F.,,,,,.T.)   // SUBLINHADO
PRIVATE OFONT9  := TFONT():NEW("ARIAL"     ,08,IIF(LPDF,07,08),,.F.,,,,,.F.)   // NORMAL
PRIVATE OFONT10 := TFONT():NEW("ARIAL"     ,08,IIF(LPDF,07,08),,.T.,,,,,.F.)   // NEGRITO
PRIVATE OFONT11 := TFONT():NEW("ARIAL"     ,07,IIF(LPDF,06,07),,.F.,,,,,.F.)   // NORMAL
PRIVATE OFONT12 := TFONT():NEW("ARIAL"     ,07,IIF(LPDF,06,07),,.T.,,,,,.F.)   // NORMAL

	// --> CRIA AS TABELAS TEMPORARIA PARA GERACAO DO RELATORIO. 
	AAREA := GETAREA() // CONTRATOS

	IMPRELF()

	RESTAREA(AAREA)

RETURN(NIL)



/*
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
±±ÉÍÍÍÍÍÍÍÍÍÍÑÍÍÍÍÍÍÍÍÍÍÍËÍÍÍÍÍÍÍÑÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍËÍÍÍÍÍÍÑÍÍÍÍÍÍÍÍÍÍÍÍ»±±
±±ºPROGRAMA  ³IMPFREL    º AUTOR ³ IT UP BUSINESS     º DATA ³ 30/06/2007 º±±
±±ÌÍÍÍÍÍÍÍÍÍÍØÍÍÍÍÍÍÍÍÍÍÍÊÍÍÍÍÍÍÍÏÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÊÍÍÍÍÍÍÏÍÍÍÍÍÍÍÍÍÍÍÍ¹±±
±±ºDESCRICAO ³ IMPRESSAO DA AUTORIZACAO DE TRANSPORTE                     º±±
±±ÌÍÍÍÍÍÍÍÍÍÍØÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ¹±±
±±ºUSO       ³ ESPECIFICO GPO                                             º±±
±±ÈÍÍÍÍÍÍÍÍÍÍÏÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ¼±±
±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
ßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßß
*/
STATIC FUNCTION IMPRELF()

LOCAL NLIN 		:= 400   
LOCAL ATRANSP  	:= {}
LOCAL LQUEBRA	:= .F.
LOCAL LINICIOPG	:= .T. 
LOCAL NPBCARGA  := 0
Local CQRY

	DBSELECTAREA("FQ5")
	DBSETORDER(8)
	DBSEEK( XFILIAL("FQ5") + X_PROJETO + X_OBRA )

	WHILE FQ5->(!EOF()) .AND. FQ5->FQ5_SOT == FP0->FP0_PROJET

		NLINFIM := 0
	//	NLIN    := 400
		NLIN    := 500   
		NFRETE  := 0
	
		IF CRET <> "TODAS" .AND. ALLTRIM(CRET) <> ALLTRIM(FQ5->FQ5_AS) .OR. FQ5->FQ5_TPAS # 'F'
		FQ5->(DBSKIP())
		LOOP
		ENDIF
		
		CLOCCAR 	:= FP1->FP1_NOMORI
		DCARPREV 	:= FQ5->FQ5_DTINI
		CTELCAR 	:= FP1->FP1_TELORI
		CCONCAR 	:= FP1->FP1_CONORI
		CENDCAR 	:= FPS->FPS_ENDORI
		CBAICAR 	:= FPS->FPS_BRRORI
		CMUNCAR 	:= FPS->FPS_MUNORI+ " - " + FPS->FPS_CIDORI
		CUFCAR  	:= FPS->FPS_UFORI
		CENDDES 	:= FPS->FPS_ENDEST
		CBAIDES 	:= FPS->FPS_BRRDES
		CMUNDES 	:= FPS->FPS_MUNDES + " - " + FPS->FPS_CIDEST
		CUFDES 		:= FPS->FPS_UFDEST
		DDESLIMITE 	:= FPS->FPS_DTLIM
	
		IF EMPTY(FPS->FPS_ENDORI)
			CENDCAR 	:= FQ7->FQ7_ENDORI
			CBAICAR 	:= FQ7->FQ7_BRRORI
			CMUNCAR 	:= FQ7->FQ7_MUNORI+ " - " + FPS->FPS_CIDORI
			CUFCAR  	:= FQ7->FQ7_UFORI
			CENDDES 	:= FQ7->FQ7_ENDEST
			CBAIDES 	:= FQ7->FQ7_BRRDES
			CMUNDES 	:= FQ7->FQ7_MUNDES + " - " + FPS->FPS_CIDEST
			CUFDES 		:= FQ7->FQ7_UFDEST
			DDESLIMITE 	:= FQ7->FQ7_DTLIM
		ENDIF

		CLODDES 	:= FP1->FP1_DESTIN
		CDESPREV 	:= FQ5->FQ5_DTFIM
		CTELDES 	:= FP1->FP1_TELDES
		CCONDES 	:= FP1->FP1_CONDES
		
		IF ! EMPTY( ALLTRIM( COBSG ) )
			DBSELECTAREA("FQ5")
			RECLOCK("FQ5",.F.)
			FQ5->FQ5_OBSCOM := COBSG
			MSUNLOCK()
		ENDIF
				
	//	OOBJPRINT:STARTPAGE()

		ATRANSP		:=	{}
		NPESOBRU	:=	0
		
		// CONJUNTO TRANSPORTADOS
		IF SELECT("TRASF") # 0 
			DBSELECTAREA("TRASF") 
			DBCLOSEAREA() 
		ENDIF

		/*
		+FQ5->FQ5_PACLIS+
		+ X_VIAGEM  +
		*/

		CQRY := "SELECT FPS_X5COD  AS CARRO , FPS_VIAGEM AS VIAGEM, FPS_ENDORI AS ENDCAR, FPS_BRRORI AS BAICAR, FPS_CEPORI AS CEPCAR, FPS_CEPDES AS CEPDES, FPO_QTACES,"
		CQRY += "       FPS_CIDORI AS MUNCAR, FPS_UFORI  AS UFCAR , FPS_ENDEST AS ENDDES, FPS_BRRDES AS BAIDES, FPO_COMPR, FPO_LARGUR, FPO_PESO, FPO_ALTURA, FPO_STATUS,"
		//CQRY += "       FPS_CIDEST AS MUNDES, FPS_UFDEST AS UFDES , ISNULL(FPO_CODBEM,'         ') AS CODBEM, FPO_FROTA, FPO_CARRET, "
		//CARD 1055 - ALTERAÇÃO DE ISNULL PARA COALESCE - DENNIS - 13/12/23
		CQRY += "       FPS_CIDEST AS MUNDES, FPS_UFDEST AS UFDES , COALESCE(FPO_CODBEM, '') AS CODBEM, FPO_FROTA, FPO_CARRET, "
		CQRY += "       FPS_DTLIM  AS DATLIM, FPS_PRECUS AS VALOR , FPS_LOCCAR, FPS_LOCDES "
		CQRY += " FROM " + RETSQLNAME("FPS")+" AS ZLW "
		CQRY +=        " LEFT JOIN "+ RETSQLNAME("FPO")+ " AS ZLG ON ZLG.D_E_L_E_T_ = '' AND FPO_VIAGEM = FPS_VIAORI AND FPO_CARRET = ? " 
		CQRY += " WHERE  ZLW.D_E_L_E_T_ = '' "
	//	CQRY +=   " AND  ZLW.FPS_PROJET = '" + X_PROJETO + "' "
	//	CQRY +=   " AND  ZLW.FPS_OBRA   = '" + X_OBRA    + "' "
		CQRY +=   " AND  ZLW.FPS_VIAGEM = ? "
	//	CQRY +=   " AND  FPO_STATUS NOT IN ('E','S','A') "
		CQRY += " ORDER BY FPS_PROJET, FPS_OBRA, FPS_ITEM "
		CQRY := CHANGEQUERY(CQRY) 
		aBindParam := {FQ5->FQ5_PACLIS,X_VIAGEM}
		MPSysOpenQuery(CQRY,"TRASF",,,aBindParam)

		//DBUSEAREA(.T.,"TOPCONN", TCGENQRY(,,CQRY),"TRASF", .F., .T.)

		TCSETFIELD("TRASF","FPL_DTLIM",   "D",8,0)
	//	TCSETFIELD("TRAB","FPL_DTFIM",   "D",8,0)
	
		// CONJUNTO TRANSPORTADOS
		IF SELECT("TRASF") # 0 
			DBSELECTAREA("TRASF") 
			DBCLOSEAREA() 
		ENDIF

		/*
		+ FQ5->FQ5_PACLIS +
		+ X_VIAGEM  +
		*/

		CQRY := "SELECT FQ7_X5COD  AS CARRO , FQ7_VIAGEM AS VIAGEM, FQ7_ENDORI AS ENDCAR, FQ7_BRRORI AS BAICAR, FQ7_CEPORI AS CEPCAR, FQ7_CEPDES AS CEPDES, FPO_QTACES,"
		CQRY += "       FQ7_CIDORI AS MUNCAR, FQ7_UFORI  AS UFCAR , FQ7_ENDEST AS ENDDES, FQ7_BRRDES AS BAIDES, FPO_COMPR, FPO_LARGUR, FPO_PESO, FPO_ALTURA, FPO_STATUS,"
		//CQRY += "       FQ7_CIDEST AS MUNDES, FQ7_UFDEST AS UFDES , ISNULL(FPO_CODBEM,'         ') AS CODBEM, FPO_FROTA, FPO_CARRET, "
		//CARD 1055 - ALTERAÇÃO DE ISNULL PARA COALESCE - DENNIS - 13/12/23
		CQRY += "       FQ7_CIDEST AS MUNDES, FQ7_UFDEST AS UFDES , COALESCE(FPO_CODBEM, '') AS CODBEM, FPO_FROTA, FPO_CARRET, "
		CQRY += "       FQ7_DTLIM  AS DATLIM, FQ7_PRECUS AS VALOR , FQ7_LOCCAR, FQ7_LOCDES,FPS_LOCCAR,FPS_LOCDES "
		CQRY += " FROM " + RETSQLNAME("FPS")+" AS ZLW "
		CQRY += " LEFT JOIN "+ RETSQLNAME("FPO")+ " AS ZLG ON ZLG.D_E_L_E_T_ = '' AND FPO_VIAGEM = FPS_VIAORI "   
		CQRY += " LEFT JOIN "+ RETSQLNAME("FQ7")+ " AS ZUC ON ZUC.D_E_L_E_T_ = '' AND FQ7_VIAGEM = FPS_VIAORI "   
		CQRY += " AND FPO_CARRET     = ? "
		CQRY += " WHERE ZUC.D_E_L_E_T_ = '' "
	//	CQRY += " AND ZLW.FPS_PROJET = '" + X_PROJETO + "' "
	//	CQRY += " AND ZLW.FPS_OBRA   = '" + X_OBRA    + "' "
		CQRY += " AND ZUC.FQ7_VIAGEM = ? "
	//	CQRY += " AND FPO_STATUS NOT IN ('E','S','A') "
		CQRY += " ORDER BY FQ7_PROJET, FQ7_OBRA, FQ7_ITEM "
		CQRY := CHANGEQUERY(CQRY) 
		aBindParam := {FQ5->FQ5_PACLIS, X_VIAGEM }
		MPSysOpenQuery(CQRY,"TRASF",,,aBindParam)
		
		//DBUSEAREA(.T.,"TOPCONN", TCGENQRY(,,CQRY),"TRASF", .F., .T.)
		TCSETFIELD("TRASF" , "FPL_DTLIM" , "D",8,0)
	//	TCSETFIELD("TRAB"  , "FPL_DTFIM" , "D",8,0)

		CEMAILCLI := FP0->FP0_CLIEMA
		CEMAILCON := FP0->FP0_CLIEMA
		
		IF !EMPTY(TRASF->FPO_STATUS) .AND. TRASF->FPO_STATUS $ 'E|S|A'
			TRASF->(DBSKIP())	
		ENDIF
		
		// CARREGAMENTO
		CLOCCAR 	:= TRASF->FPS_LOCCAR	// FP1->FP1_NOMORI
		IF EMPTY(CLOCCAR)
			CLOCCAR := TRASF->FQ7_LOCCAR	// FP1->FP1_NOMORI
		ENDIF
		
		DCARPREV 	:= DTOC(FQ5->FQ5_DTINI)
		CENDCAR 	:= TRASF->ENDCAR
		CBAICAR 	:= TRASF->BAICAR
		CMUNCAR 	:= TRASF->MUNCAR
		CUFCAR  	:= TRASF->UFCAR
		CTELCAR 	:= FP1->FP1_TELORI
	//	CCONCAR 	:= FP1->FP1_CONORI
		CCONCAR 	:= TRASF->CEPCAR

		// DESCARREGAMENTO
		CLOCDES 	:= TRASF->FPS_LOCDES	// FP1->FP1_DESTIN
		IF EMPTY(CLOCDES)
		CLOCDES 	:= TRASF->FQ7_LOCDES	// FP1->FP1_DESTIN
		ENDIF    	
			
		DDESPREV 	:= DTOC(FQ5->FQ5_DTFIM)
		CENDDES 	:= TRASF->ENDDES
		CBAIDES 	:= TRASF->BAIDES
		CMUNDES 	:= TRASF->MUNDES
		CUFDES 		:= TRASF->UFDES
		CTELDES 	:= FP1->FP1_TELDES
	//	CCONDES 	:= FP1->FP1_CONDES
		CCONDES 	:= TRASF->CEPDES
		DDESLIMITE 	:= DTOC(STOD(TRASF->DATLIM))

		IF EMPTY(CENDCAR)
			CLOCCAR := FP1->FP1_NOMORI
			CLOCDES := FP1->FP1_NOMDES
			CENDCAR := FP1->FP1_ENDORI
			CBAICAR := FP1->FP1_BAIORI
			CMUNCAR := FP1->FP1_MUNORI
			CUFCAR  := FP1->FP1_ESTORI
			CENDDES := FP1->FP1_ENDDES
			CBAIDES := FP1->FP1_BAIDES
			CMUNDES := FP1->FP1_MUNDES
			CUFDES 	:= FP1->FP1_ESTDES
		ENDIF

		_CDESC := STR0002 //"FRETE"

		IF LQUEBRA .OR. LINICIOPG
			FASFCAB()
			LINICIOPG := .F.
		ENDIF

	// BOX INICIAL - VER POSICAO INICIAL PARA AJUSTAR OS INICIOS DE BOX
		OOBJPRINT:BOX( 0030 + NLIN , 0030, 150 + NLIN, 2370)
		OOBJPRINT:SAY( 0050 + NLIN , 0040 ,  STR0003		+DTOC(DDATABASE)+STR0004+TIME()											, OFONT10   , 100 ) //"EMITIDA EM: "###" AS "
		OOBJPRINT:SAY( 0050 + NLIN , 0600 ,  STR0005		+ALLTRIM(FP0->FP0_PROJET) + STR0006+FP0->FP0_REVISA 				, OFONT10   , 100 ) //"NÚMERO SOT: "###" - REVISÃO: "
		OOBJPRINT:SAY( 0050 + NLIN , 1400 ,  STR0007	+FQ5->FQ5_OBRA                  										, OFONT10   , 100 ) //"NÚMERO OBRA: "
		OOBJPRINT:SAY( 0050 + NLIN , 1800 ,  STR0008	+FQ5->FQ5_VIAGEM	               										, OFONT10   , 100 ) //"NÚMERO VIAGEM:"
		OOBJPRINT:SAY( 0100 + NLIN , 0040 ,  STR0009         		                          											, OFONT10   , 100 ) //"GESTOR:"
		OOBJPRINT:SAY( 0100 + NLIN , 0240 ,  FP0->FP0_VENDED+" - "+POSICIONE("SA3",1,XFILIAL("SA3") + FP0->FP0_VENDED , "A3_NOME" )	  	, OFONT10   , 100 )

	// SEGUNDO BOX - CLIENTE                                                                                    
		OOBJPRINT:BOX( 0150 + NLIN , 0030, 0210 + NLIN, 2370)
		OOBJPRINT:SAY( 0160 + NLIN , 0950 ,  STR0010																	, OFONT5   	, 100 ) //"INFORMAÇÕES DO CLIENTE"
		OOBJPRINT:BOX( 0210 + NLIN , 0030, 0610 + NLIN, 2370)
		OOBJPRINT:SAY( 0230 + NLIN , 0040 ,  STR0011	+	CCODCLI+"/"+CLJCLIE+" - "+ALLTRIM(FP0->FP0_CLINOM)						, OFONT10   , 100 ) //"CLIENTE: "
		OOBJPRINT:SAY( 0230 + NLIN , 1200 ,  "I.E: " 		+ 	TRANSFORM(CINCR,"@R 999.999.999-999") 									, OFONT10   , 100 )
		OOBJPRINT:SAY( 0260 + NLIN , 0040 ,  STR0012 + TRANSFORM(CGC,"@!R NN.NNN.NNN/NNNN-99")										, OFONT10   , 100 ) //"C.N.P.J:"
		OOBJPRINT:SAY( 0290 + NLIN , 0040 ,  STR0013 + CENDERE																, OFONT10   , 100 ) //"END. COMERCIAL:"
		OOBJPRINT:SAY( 0380 + NLIN , 0040 ,  ALLTRIM(CBAIRRO) +" - "+ALLTRIM(CMUNICI)+" - "+ALLTRIM(CESTADO)+" - "+ALLTRIM(CCEP) 		, OFONT10   , 100 )
		OOBJPRINT:SAY( 0290 + NLIN , 1200 ,  STR0014  + CENDCOB																, OFONT10   , 100 ) //"END. COBRANÇA:"
		OOBJPRINT:SAY( 0380 + NLIN , 1200 ,  ALLTRIM(CBAICOB) +" - "+ALLTRIM(CMUNCOB)+" - "+ALLTRIM(CESTCOB)+" - "+ALLTRIM(CCEPCOB) 	, OFONT10   , 100 )
		OOBJPRINT:SAY( 0420 + NLIN , 0040 ,  STR0015  + CTEL    																	, OFONT10   , 100 ) //"TELEFONE: "
		OOBJPRINT:SAY( 0470 + NLIN , 0040 ,  STR0016  + CCONTATO                                     								, OFONT10   , 100 ) //"CONTATO : "
		OOBJPRINT:SAY( 0420 + NLIN , 1200 ,  STR0015  + CTEL    									                                , OFONT10   , 100 ) //"TELEFONE: "
		OOBJPRINT:SAY( 0470 + NLIN , 1200 ,  STR0016  + CCONTATO                                  									, OFONT10   , 100 ) //"CONTATO : "
		OOBJPRINT:SAY( 0520 + NLIN , 0040 ,  STR0017  + CEMAILCLI         															, OFONT10   , 100 ) //"E-MAIL  : "
		OOBJPRINT:SAY( 0520 + NLIN , 1200 ,  STR0017  + CEMAILCON                                     								, OFONT10   , 100 ) //"E-MAIL  : "
		
	// TERCEIRO BOX - CARREGAMENTO / DESCARREGAMENTO    
		OOBJPRINT:BOX( 0610 + NLIN , 0030, 0670 + NLIN, 2370)
		OOBJPRINT:SAY( 0630 + NLIN , 0700 ,  STR0018   											, OFONT5   	, 100 ) //"INFORMAÇÕES DE CARREGAMENTO E DESCARREGAMENTO"
		OOBJPRINT:BOX( 0670 + NLIN , 0030, 1000 + NLIN, 2370)

		OOBJPRINT:SAY( 0690 + NLIN , 0040 ,  STR0019                                   											, OFONT10  	, 100 ) //"CARREGAMENTO"
		OOBJPRINT:SAY( 0750 + NLIN , 0040 ,  STR0020 +  CLOCCAR					                                       				, OFONT10  	, 100 ) //"LOCAL: "

	//  OOBJPRINT:SAY( 0750 + NLIN , 1200 ,  "PRAZO EXEC: "                                    , OFONT10   , 100 )
	//  OOBJPRINT:SAY( 0750 + NLIN , 1330 ,  STR(_PRAZEXEC)                                    , OFONT10   , 100 )                            

		OOBJPRINT:SAY( 0750 + NLIN , 1700 ,  STR0021 + DCARPREV					   , OFONT10   , 100 ) //"DATA PREVISTA: "
	//  OOBJPRINT:SAY( 0750 + NLIN , 1900 ,  DTOC(ZA7->ZA7_DTCAR)							   , OFONT10   , 100 )

	//  OOBJPRINT:SAY( 0750 + NLIN , 2050 ,  "HORA: "                                          , OFONT10   , 100 )
	//  OOBJPRINT:SAY( 0750 + NLIN , 2150 ,  TRANSFORM(ZA7->ZA7_HRCAR,"@R 99:99")              , OFONT10   , 100 )

		OOBJPRINT:SAY( 0800 + NLIN , 0040 ,  STR0022 + CENDCAR						       , OFONT10   , 100 ) //"ENDEREÇO: "
	//  OOBJPRINT:SAY( 0800 + NLIN , 0190 ,  ZA6->ZA6_ENDORI                                   , OFONT10   , 100 )

		OOBJPRINT:SAY( 0850 + NLIN , 0040 ,  STR0023  + CBAICAR							   , OFONT10   , 100 ) //"BAIRRO: "
	//  OOBJPRINT:SAY( 0850 + NLIN , 0150 ,  ZA6->ZA6_BAIORI                                   , OFONT10   , 100 )

		OOBJPRINT:SAY( 0850 + NLIN , 0700 ,  STR0024 + CMUNCAR							   , OFONT10   , 100 ) //"CIDADE: "
	//  OOBJPRINT:SAY( 0850 + NLIN , 0830 ,  ZA6->ZA6_MUNORI                                   , OFONT10   , 100 )

		OOBJPRINT:SAY( 0850 + NLIN , 1200 ,  STR0025 + CUFCAR							   , OFONT10   , 100 ) //"ESTADO: "
	//  OOBJPRINT:SAY( 0850 + NLIN , 1330 ,  ZA6->ZA6_ESTORI                                   , OFONT10   , 100 )

	//  OOBJPRINT:SAY( 0900 + NLIN , 0040 ,  "TELEFONE: " + CTELCAR							   , OFONT10   , 100 )
	//  OOBJPRINT:SAY( 0900 + NLIN , 0180 ,  ZA6->ZA6_TELORI                                   , OFONT10   , 100 )

		OOBJPRINT:SAY( 0900 + NLIN , 0700 ,  STR0026  + CCONCAR								   , OFONT10   , 100 ) //"CEP: "
	//  OOBJPRINT:SAY( 0900 + NLIN , 0830 ,  ZA6->ZA6_CONORI                                   , OFONT10   , 100 )

	//  OOBJPRINT:SAY( 0900 + NLIN , 1400 ,  "CARENCIA: "                                      , OFONT10   , 100 )
	//  OOBJPRINT:SAY( 0900 + NLIN , 1550 ,  ALLTRIM(STR(ZA7->ZA7_CARENC))+" "+CTIPOCAR        , OFONT10   , 100 )

		OOBJPRINT:BOX( 1000 + NLIN , 0030, 1330 + NLIN, 2370)
		OOBJPRINT:SAY( 1020 + NLIN , 0040 ,  STR0027                 				   , OFONT10   , 100 ) //"DESCARREGAMENTO"

		OOBJPRINT:SAY( 1080 + NLIN , 0040 ,  STR0028 + CLOCDES								   , OFONT10   , 100 ) //"LOCAL:"
	//  OOBJPRINT:SAY( 1080 + NLIN , 0140 ,  ALLTRIM(ZA6->ZA6_NOMDES)                          , OFONT10   , 100 )                                

	//  OOBJPRINT:SAY( 1080 + NLIN , 1200 ,  "PRAZO EXECUÇÃO:"                                 , OFONT10   , 100 )                            
	//  OOBJPRINT:SAY( 1080 + NLIN , 1350 ,  STR(_PRAZEXEC)                                    , OFONT10   , 100 )                            

		OOBJPRINT:SAY( 1080 + NLIN , 1700 ,  STR0029								   , OFONT10   , 100 ) //"DATA PREVISTA:"
		OOBJPRINT:SAY( 1080 + NLIN , 1900 ,  DDESPREV										   , OFONT10   , 100 )

	//  OOBJPRINT:SAY( 1080 + NLIN , 2050 ,  "HORA:"                                           , OFONT10   , 100 )
	//  OOBJPRINT:SAY( 1080 + NLIN , 2150 ,  TRANSFORM(ZA7->ZA7_HRDES,"@R 99:99")              , OFONT10   , 100 )
			
		OOBJPRINT:SAY( 1130 + NLIN , 0040 ,  STR0030                                       , OFONT10   , 100 ) //"ENDEREÇO:"
		OOBJPRINT:SAY( 1130 + NLIN , 0190 ,  CENDDES										   , OFONT10   , 100 )
			
		OOBJPRINT:SAY( 1180 + NLIN , 0040 ,  STR0031                                         , OFONT10   , 100 ) //"BAIRRO:"
		OOBJPRINT:SAY( 1180 + NLIN , 0150 ,  CBAIDES                                  		   , OFONT10   , 100 )
			
		OOBJPRINT:SAY( 1180 + NLIN , 0700 ,  STR0032                                         , OFONT10   , 100 ) //"CIDADE:"
		OOBJPRINT:SAY( 1180 + NLIN , 0830 ,  CMUNDES                                  		   , OFONT10   , 100 )
			
		OOBJPRINT:SAY( 1180 + NLIN , 1200 ,  STR0033                                         , OFONT10   , 100 ) //"ESTADO:"
		OOBJPRINT:SAY( 1180 + NLIN , 1330 ,  CUFDES                                  		   , OFONT10   , 100 )
			
	//  OOBJPRINT:SAY( 1230 + NLIN , 0040 , "TELEFONE:"                                        , OFONT10   , 100 )
	//  OOBJPRINT:SAY( 1230 + NLIN , 0180 , CTELDES                                  		   , OFONT10   , 100 )
			
		OOBJPRINT:SAY( 1230 + NLIN , 0700 ,  STR0034                                            , OFONT10   , 100 ) //"CEP:"
		OOBJPRINT:SAY( 1230 + NLIN , 0830 ,  CCONDES                                  		   , OFONT10   , 100 )
			
		OOBJPRINT:SAY( 1230 + NLIN , 1400 ,  STR0035                                    , OFONT10   , 100 ) //"DATA LIMITE:"
		OOBJPRINT:SAY( 1230 + NLIN , 1550 ,  DDESLIMITE										   , OFONT10   , 100 )
		
		OOBJPRINT:BOX( 1330 + NLIN , 0030, 1390 + NLIN, 2370)   	
		OOBJPRINT:SAY( 1350 + NLIN , 1050 ,  STR0036 + FQ5->FQ5_PACLIS   , OFONT5   , 100 ) //"LISTAGEM DO PACK LIST - Nº "

		NPAGINA := 1
			
		NLINFIM := NLIN + (050 * LEN(ATRANSP))
		DBSELECTAREA("TRASF")
		WHILE .NOT. EOF() 
			NLINFIM := 0
			IF NLIN > 1500 // 1790
				OOBJPRINT:SAY(1340 + NLIN, 2100, STR0037, OFONT10, 100) //"CONTINUA..."
				OOBJPRINT:ENDPAGE()
				
				FASFCAB()
				
				NLIN := -800
				NPAGINA++
				OOBJPRINT:BOX(1330 + NLIN, 0030, 1390 + NLIN, 2370)   	
				OOBJPRINT:SAY(1350 + NLIN, 850 , STR0038+ALLTRIM(STR(NPAGINA))+STR0039 + FQ5->FQ5_PACLIS, OFONT5, 100) //"CONTINUAÇÃO PÁG.:"###" - LISTAGEM DO PACK LIST - Nº "
			ENDIF
			
			IF !EMPTY(TRASF->CODBEM)
				CDESCARGA := POSICIONE("ST9",1,XFILIAL("ST9")+TRASF->CODBEM,"T9_NOME")  
				NQDCARGA  := TRASF->FPO_QTACES
			ELSE
				NQDCARGA  := 1
				CDESCARGA := POSICIONE("ST9",1,XFILIAL("ST9")+TRASF->FPO_FROTA,"T9_NOME")
			ENDIF
			
			NVLSEG    := TRASF->VALOR
			
			IF EMPTY(TRASF->FPO_CARRET) 
				NCMCARGA  := 0
				NLGCARGA  := 0
				NALCARGA  := 0
				NPSCARGA  := 0
				NQDCARGA  := 0
				CDESCARGA := ""		
			ELSE
				NCMCARGA  := TRASF->FPO_COMPR
				NLGCARGA  := TRASF->FPO_LARGUR
				NALCARGA  := TRASF->FPO_ALTURA
				NPSCARGA  := TRASF->FPO_PESO 
			ENDIF

			NDICARGA   := 0.00
			NPBCARGA   += (NPSCARGA * NQDCARGA)		// --> COMPUTAR NA VARIAVEL O VALOR MUTIPLICADO PELA QUANTIDADE. 
			CTPCAR     :=""
			CTPCAR     := FPS->FPS_DESCRI 
			IF EMPTY(CTPCAR)            
				CTPCAR := FQ7->FQ7_DESCRI 	
			ENDIF
			
			OOBJPRINT:BOX( 1390 + NLIN , 0030, 1600 + NLIN, 2370)
			OOBJPRINT:SAY( 1410 + NLIN , 0040 ,  STR0040                                            , OFONT10   , 100 ) //"DIMENSÕES"

			OOBJPRINT:SAY( 1460 + NLIN , 0040 ,  STR0041                                           , OFONT10   , 100 ) //"DESCRIÇÃO:"
			OOBJPRINT:SAY( 1460 + NLIN , 0200 ,  CDESCARGA		                                        , OFONT10   , 100 )

			OOBJPRINT:SAY( 1460 + NLIN , 1450 ,  STR0042                                    	    , OFONT10   , 100 ) //"QUANTIDADE:"
			OOBJPRINT:SAY( 1460 + NLIN , 1600 ,  TRANSFORM(NQDCARGA,"@E 999,999,999")       			, OFONT10   , 100 )

			OOBJPRINT:SAY( 1510 + NLIN , 0040 ,  STR0043                                         , OFONT10   , 100 ) //"COMPRIMENTO:"
			OOBJPRINT:SAY( 1510 + NLIN , 0200 ,  TRANSFORM(NCMCARGA  ,"@E 999,999,999.99" )            , OFONT10   , 100 )
			OOBJPRINT:SAY( 1510 + NLIN , 0400 ,  STR0044                                                   , OFONT10   , 100 ) //"MT"

			OOBJPRINT:SAY( 1510 + NLIN , 0750 ,  STR0045                                             , OFONT10   , 100 ) //"LARGURA:"
			OOBJPRINT:SAY( 1510 + NLIN , 0900 ,  TRANSFORM(NLGCARGA  ,"@E 999,999.99" )                , OFONT10   , 100 )
			OOBJPRINT:SAY( 1510 + NLIN , 1060 ,  STR0044                                                   , OFONT10   , 100 ) //"MT"

			OOBJPRINT:SAY( 1510 + NLIN , 1450 ,  STR0046                                              , OFONT10   , 100 ) //"ALTURA:"
			OOBJPRINT:SAY( 1510 + NLIN , 1600 ,  TRANSFORM(NALCARGA  ,"@E 999,999.99" )                , OFONT10   , 100 )
			OOBJPRINT:SAY( 1510 + NLIN , 1755 ,  STR0044                                                   , OFONT10   , 100 ) //"MT"

			OOBJPRINT:SAY( 1560 + NLIN , 0040 ,  STR0047                                      	, OFONT10   , 100 ) //"PESO UNITARIO:"
			OOBJPRINT:SAY( 1560 + NLIN , 0200 ,  TRANSFORM(NPSCARGA  ,"@E 999,999,999.99" )         	, OFONT10   , 100 )
			OOBJPRINT:SAY( 1560 + NLIN , 0400 ,  STR0048                                                  , OFONT10   , 100 ) //"KG"

			NLINFIM := NLIN + (050 * LEN(ATRANSP))
			OOBJPRINT:BOX( 1600 + NLIN , 0030, 1660 + NLINFIM, 2370)
			OOBJPRINT:SAY( 1610 + NLIN , 0040 ,  STR0049                                    , OFONT10   , 100 ) //"TIPO DE CARRETA :"
			OOBJPRINT:SAY( 1610 + NLIN , 0300 ,  CTPCAR                                                 , OFONT10   , 100 )
			NLIN:= NLIN + 270
			
	//		NFRETE += TRASF->VALOR
			NFRETE := TRASF->VALOR  				// --> O VALOR DE FRETE DEVE APRESENTAR SOMENTE O VALOR TOTAL NÃO O VALOR MULTIPLICADO PELA QUANTIDADE DE ITENS
			DBSELECTAREA("TRASF") //"TRASF"
			DBSKIP()
		ENDDO

		NLIN:=NLINFIM
		OOBJPRINT:BOX( 1660 + NLIN , 0030, 1710 + NLIN, 2370)
		OOBJPRINT:SAY( 1670 + NLIN , 0040 ,  STR0051 + TRANSFORM(NFRETE  ,"@E 999,999,999.99")	, OFONT10   , 100 ) //"VALOR PREVISTO FRETE : "
		OOBJPRINT:BOX( 1710 + NLIN , 0030, 2000 + NLIN, 2370)

		OOBJPRINT:SAY( 1670 + NLIN , 1900 ,  STR0052                                                		, OFONT10   , 100 ) //"PBT:"
		OOBJPRINT:SAY( 1670 + NLIN , 2100 ,  TRANSFORM(NPBCARGA  ,"@E 999,999,999.999" )          		, OFONT10   , 100 )
		OOBJPRINT:SAY( 1670 + NLIN , 2285 ,  STR0048                                                 		, OFONT10   , 100 ) //"KG"

		FQ5->(DBSKIP())
		OOBJPRINT:ENDPAGE()
	ENDDO

	IF SELECT("TRASF") # 0  //"TRASF"
		DBSELECTAREA("TRASF")  //"TRASF"
		DBCLOSEAREA() 
	ENDIF

RETURN



// ======================================================================= \\
STATIC FUNCTION FASFCAB()
// ======================================================================= \\
// --> CABEÇALHO 
	OOBJPRINT:STARTPAGE()

	IF CEMPANT == "07"
		OOBJPRINT:SAYBITMAP( 0055, 020,"LGJSM.BMP" , 790, 0380 ) 	// 553 X 224
	ELSE
		OOBJPRINT:SAYBITMAP( 0055, 020,"LOGO.BMP"  , 790, 0380 ) 	// 553 X 224
	ENDIF

	OOBJPRINT:SAY( 0050 , 0850 , STR0053	+ _CDESC             				, OFONT2   , 100 ) //"AUTORIZAÇÃO DE SERVIÇO: "

	// INSERIR NUMERO DA ASG VINCULADO
	OOBJPRINT:SAY( 0150 , 0850 ,  STR0054 				+ CNRASORI                      	, OFONT2   , 100 ) //"NO. AS  :"
	OOBJPRINT:SAY( 0250 , 0850 ,  STR0055 				+ X_ASF                       		, OFONT2   , 100 ) //"NO. ASF :"
	OOBJPRINT:SAY( 0350 , 0850 ,  STR0056			+ ALLTRIM(X_PROJETO)+; //"NO. PROJETO: "
								STR0006 			+ ALLTRIM(FP0->FP0_REVISAO)      	, OFONT2   , 100 ) //" - REVISÃO: "
	OOBJPRINT:SAY( 0450 , 0850 ,  STR0057   			+ ALLTRIM(X_OBRA)+; //"NO. OBRA: "
								STR0058											, OFONT2   , 100 ) //" - REVISÃO DA AS: "

	LINICIOPG := .F.

RETURN  


// ======================================================================= \\
STATIC FUNCTION VALIDPERG()
// ======================================================================= \\
/*
LOCAL AAREA := GETAREA()

CPERG := PADR(CPERG,10)
PUTSX1(CPERG 	,"01"		,STR0059	,STR0059	,STR0059  ,"MV_CH1"	,"C"	,27			,00			,00			,"G"	,""		,"DTQAS"  	,""			,""		,"MV_PAR01"	,""     			,""			,""			,""		,""    			,""			,""			,""     			,""			,""			,""		,""			,""			,""		,""			,""			, 			,  			,  			,""		) //"NUMERO AS     ?"###"NUMERO AS     ?"###"NUMERO AS     ?"

RESTAREA(AAREA)
*/
RETURN


