//-------------------------------------------------------------------
/*/{Protheus.doc} GPERSV450

Chamada do objeto de negócios rh.treports.gper450 e relatório no Smart View pela função totvs.framework.treports.callTReports  

@author  caio.kretzer
@since   11/12/2024
@version 1.0
/*/

Function GPERSV450()

    // Declaração das variáveis locais
	local lSuccess      As Logical
    local oSmartView    As Object

    // Inicialização das variáveis
    oSmartView := NIL
    
    // Valida a release do Protheus
    If GetRpoRelease() > "12.1.2210"
        // Instancia a classe callSmartView()
        oSmartView := totvs.framework.smartview.callSmartView():new("rh.sv.gpe.gper450")
        oSmartView:setShowWizard(.T.)
        lSuccess := oSmartView:executeSmartView(.T.)

        // Verifica se ocorreu algum erro na execução do artefato do Smart View
        If !lSuccess
            Conout(oSmartView:getError())
        EndIf  

        // Destrói o objeto e o libera da memória
        oSmartView:destroy()
        FwFreeObj(oSmartView)
    EndIf

Return
