#include 'tlpp-core.th'
#include 'tlpp-object.th'

namespace backoffice.fiscal.configurator.profile.lookup

/*/{Protheus.doc} FisLookup
    Cria tela de Consulta F3 com base no SXB especifico tipo 2
    @author Ricardo Henrique de Mello Lima
    @since 13/03/2026
    @version 12.1.2510
    /*/
Class FisLookup

	Private Data cAliasQuery as character
	Private Data cAliasTable as character
	Private Data cNameTable as character
	Private Data aIndex as array
	Private Data cQuery as character
	Private Data oTmpTable as object
	Private Data oBrowse as object
	Private Data aColumns as array
	Private Data aSeek as array
    Private Data aReturn as array
    Private Data aRetFields as array
	Private Data cDescription as character

	Public Method New()
	Public Method SetDescription()
	Private Method BuildTempTable()
	Protected Method BuildInterface()
	Private Method AddRegTempTable()
	Private Method AddColumn(aStruct as array)
	Public Method SetIndex(aValue as array)
	Private Method SetSeek(cCampo as character)
	Public Method Show(cQuery as character, aBinds as array) as array
	Private Method Destroy()
	Private Method CloseTmpTable()
    Public Method SetGetFields(aFields as array)
    Private Method RetGetFields()

EndClass


/*/{Protheus.doc} New
    Metodo Incicializador da Classe
    @author Ricardo Henrique de Mello Lima
    @since 13/03/2026
    @version 12.1.2510
    /*/

Method New() class FisLookup

	::cAliasQuery := ""
	::cAliasTable := ""
	::cNameTable := ""
	::cQuery := ""
	::aIndex := {}
	::oTmpTable := nil
	::oBrowse := nil
	::aColumns := {}
	::aSeek := {}
    ::aReturn := {}
    ::aRetFields := {}
	::cDescription := "Consulta Padrão"

Return

/*/{Protheus.doc} Show
    Executa Query do browser
    @author Ricardo Henrique de Mello Lima
    @since 14/03/2026
    @version 12.1.2510
    @param cQuery para montagem da tabela temporaria obrigatorio utilizar ? para Bind da query
    @param aBinds valores para filtro da query array com tipo e valor {(C/N/D/A),valor}
    @return logico true ou false 
    /*/
Method Show(cQuery as character, aBinds as array) as array class FisLookup

	Local oStmt := nil as object
	Local nCount := 0 as numeric

	oStmt := FWExecStatement():New(cQuery)

	for nCount := 1 to Len(aBinds)

		if aBinds[nCount,1] == "C"
			oStmt:SetString(nCount,aBinds[nCount,2])
		elseif aBinds[nCount,1] == "D"
			oStmt:SetDate(nCount,aBinds[nCount,2])
		elseif aBinds[nCount,1] == "N"
			oStmt:SetNumeric(nCount,aBinds[nCount,2])
		elseif aBinds[nCount,1] == "A"
			oStmt:SetIn(nCount,aBinds[nCount,2])
		endif
	next

	::cAliasQuery := oStmt:OpenAlias()

	if !isBlind()
		::BuildTempTable()
	endif
	
	oStmt:Destroy()
	FreeObj(oStmt)

Return ::aReturn

/*/{Protheus.doc} BuildTempTable
    Cria a Tabela Temporaria 
    Query informada para geracao da tabela
    Parametro para o Bind na Query
    Indices informado para consulta da tabela temporaria
    Campos de Pesquisa informado para trabalhar com os Indices Criado
    @author Ricardo Henrique de Mello Lima
    @since 14/03/2026
    @version 12.1.2510
    /*/
Method BuildTempTable() class FisLookup

	Local aStrutAlias	:= (::cAliasQuery)->(dbStruct())
	Local aStrut := {} as array
	Local aStructFild := {} as array
	Local nCount := 0 as numeric
	Local cNameField := "" as character

	For nCount := 1 to (::cAliasQuery)->(FCount() )
		aStructFild := FWSX3Util():GetFieldStruct(aStrutAlias[nCount][1])
		cNameField := FWSX3Util():GetDescription(aStrutAlias[nCount][1])
		aAdd(aStrut,{aStructFild[1],aStructFild[2],aStructFild[3],aStructFild[4],cNameField})
		::AddColumn(aStrut[nCount])
	Next

	::oTmpTable := FWTemporaryTable():New(GetNextAlias())
	::oTmpTable:SetFields(aStrut)


	if !Empty(::aIndex)
		For nCount := 1 to len(::aIndex)
			::oTmpTable:AddIndex(cValToChar(StrZero(nCount,2)),{::aIndex[nCount,1]})
		Next
	endif

	::oTmpTable:Create()
	::cNameTable := ::oTmpTable:GetRealName()
	::cAliasTable := ::oTmpTable:GetAlias()

	::AddRegTempTable()

Return

/*/{Protheus.doc} SetIndex
    Seta o Indice da Tabela Temporaria
    @author Ricardo Henrique de Mello Lima
    @since 15/03/2026
    @version 12.1.2510
    /*/
Method SetIndex(aValue as array) class FisLookup

	Local nCount := 0 as numeric

	for nCount := 1 to Len(aValue)
		aAdd(::aIndex,{aValue[nCount]})
		::SetSeek(aValue[nCount])
	next

Return

/*/{Protheus.doc} AddRegTempTable
    (long_description)
    @author Ricardo Henrique de Mello Lima
    @since 15/03/2026
    @version 12.1.2510
 
    /*/
Method AddRegTempTable() class FisLookup

	Local nCount := 0 as numeric

	(::cAliasQuery)->(dbGoTop())

	While (::cAliasQuery)->(!EOF())

		RecLock(::cAliasTable,.T.)

		For nCount := 1 to (::cAliasQuery)->(FCount())
			(::cAliasTable)->(FieldPut(nCount,(::cAliasQuery)->(FieldGet(nCount))))
		Next

		(::cAliasTable)->(MsUnlock())
		(::cAliasQuery)->(dbSkip())
	EndDo

	(::cAliasTable)->(dbGoTop())
	(::cAliasQuery)->(dbCloseArea())

	
	::BuildInterface()
	
Return


/*/{Protheus.doc} BuildInterface
    Metodo que Constroi a Tela de Consulta F3
    @author Ricardo Henrique de Mello Lima
    @since 13/03/2026
    @version 12.1.2510
    /*/
Method BuildInterface() class FisLookup

	Local cTitulo := "Consulta Específica"
	Local oDlg := nil as object
	Local lOk := .F. as logical
    Local bOk := {|| (lOk := .T., oDlg:End()) } as codeblock
	Local bCancel := {|| oDlg:End() } as codeblock

	Local aCords := FWGetDialogSize( oMainWnd ) as array
	Local nWidth := 0
	Local nHeight := 0
	Local nCoordX := 0
	Local nCoordY := 0

	nCoordY := aCords[1]
	nCoordX := aCords[2]
	nWidth := aCords[4] /1.75
	nHeight := aCords[3] /1.75

	DEFINE MSDIALOG oDlg TITLE cTitulo FROM nCoordX, nCoordY TO nCoordX+nHeight,nCoordY+nWidth PIXEL OF oMainWnd

	::oBrowse := FWBrowse():New()
	::oBrowse:SetDescription(::cDescription)
	::oBrowse:SetDataTable()
	::oBrowse:SetAlias(::cAliasTable)
	::oBrowse:SetSeek(, ::aSeek)
	::oBrowse:SetOwner(oDlg)
	::oBrowse:SetColumns(::aColumns)
	::oBrowse:DisableReport()
	::oBrowse:DisableFilter()
	::oBrowse:DisableConfig()
	::oBrowse:DisableSaveConfig()
	::oBrowse:Activate()

	ACTIVATE MSDIALOG oDlg CENTERED On Init EnchoiceBar(oDlg, bOk, bCancel,,)

    If lOk
        ::RetGetFields()
        ::Destroy()
    endif

Return

/*/{Protheus.doc} AddColumn
    Metodo que adiciona as colunas do FWBrowser
    @author Ricardo Henrique de Mello Lima
    @since 15/03/2026
    @version 12.1.2510
    /*/
Method AddColumn(aStruct as array) class FisLookup

	AAdd( ::aColumns, FWBrwColumn():New() )

	::aColumns[Len(::aColumns)]:SetData( &("{ || " + aStruct[1] + " }") )
	::aColumns[Len(::aColumns)]:SetTitle( aStruct[5] )
	::aColumns[Len(::aColumns)]:SetSize( aStruct[3] )
	::aColumns[Len(::aColumns)]:SetID( aStruct[1] )


Return

/*/{Protheus.doc} SetSeek
    Metodo responsavel por criar os indices de Busca do browser
    @author Ricardo Henrique de Mello Lima
    @since 16/03/2026
    @version 12.1.2510

    /*/
Method SetSeek(cCampo as character) class FisLookup

	// [n,1] Título da pesquisa
	// [n,2,n,1] LookUp
	// [n,2,n,2] Tipo de dados
	// [n,2,n,3] Tamanho
	// [n,2,n,4] Decimal
	// [n,2,n,5] Título do campo
	// [n,2,n,6] Máscara
	// [n,2,n,7] Nome Físico do campo - Opcional - é ajustado no programa

	AAdd(::aSeek,{ GetSX3Cache(cCampo,"X3_TITULO"),;
		{{ cCampo,;
		GetSX3Cache(cCampo,"X3_TIPO"),;
		GetSX3Cache(cCampo,"X3_TAMANHO"),;
		GetSX3Cache(cCampo,"X3_DECIMAL"),;
		GetSX3Cache(cCampo,"X3_TITULO"),;
		GetSX3Cache(cCampo,"X3_PICTURE"),;
		}},;
		1})

Return

/*/{Protheus.doc} SetSelectedFields
    Metodo responsavel por receber os campos que deseja que seja retornados 
    apos selecao da linha do browser
    @author Ricardo Henrique de Mello Lima
    @since 16/03/2026
    @version 12.1.2510
    /*/
Method SetGetFields(aFields as array) class FisLookup
	::aRetFields := aFields
Return

/*/{Protheus.doc} RetGetFields
    Metodo que Indica os campos a serem retornados 
    @author Ricardo Henrique de Mello Lima
    @since 16/03/2026
    @version 12.1.2510
    /*/
Method RetGetFields() class FisLookup
    Local nCount := 0
	
	for nCount := 1 to len(::aRetFields)   
		If (::cAliasTable)->(FieldPos(::aRetFields[nCount])) > 0
			aAdd(::aReturn, (::cAliasTable)->(FieldGet(FieldPos(::aRetFields[nCount]))))	
		EndIf	
	Next
Return 

/*/{Protheus.doc} Destroy
    Metodo responsavel por destruir os objetos ao deixar a aplicacao
    @author Ricardo Hnerique de Mello Lima
    @since 16/03/2026
    @version 12.1.2510
    /*/
Method Destroy() class FisLookup
	::CloseTmpTable()
Return

/*/{Protheus.doc} CloseTmpTable
    Metodo que fecha a tabela temporaria para limpar resurdos de banco 
    @author Ricardo Henrique de Mello Lima
    @since 16/03/2026
    @version 12.1.2510

    /*/
Method CloseTmpTable() class FisLookup

	if select (::cAliasTable) > 0
		(::cAliasTable)->(dbCloseArea())
	endif

	If ValType(::oTmpTable ) == 'O'
		FreeObj(::oTmpTable )
	EndIf

	If ValType(::oBrowse ) == 'O'
		FreeObj(::oBrowse )
	EndIf

Return

/*/{Protheus.doc} SetDescription
	Ajusta A Descricao da Tela 
	@author Ricardo Henrique de Mello Lima
	@since 16/03/2026
	@version 12.1.2510
	/*/
Method SetDescription(cValue as character) class FisLookup
	if !Empty(Alltrim(cValue))
		::cDescription := cValue
	endif
Return 
