#include 'tlpp-core.th'
#include 'totvs.ch'

namespace totvs.protheus.agrobusiness.agd  

/*/{Protheus.doc} ShippingContractRepository
Repositório de romaneio dos contratos (NJJ)
@type class
@version 12
@author gilson.venturi
@since 18/05/2026
/*/
class ShippingContractRepository from UtilsRepository
	public method new()

	private method getFields() as array
	private method getJoins()  as array
endclass

/*/{Protheus.doc} new
Construtor
@type method
@version 12
@author gilson.venturi
@since 18/05/2026
@return object, Instância da classe
/*/
method new() class ShippingContractRepository
	_Super:New('NJJ', self:getFields(), self:getJoins())
return self

/*/{Protheus.doc} getFields
Obtem os campos do repositório
@type method
@version 12
@author gilson.venturi
@since 18/05/2026
@return array, {{cCampoJson, cCampoProtheus, cTipoCampo, lMostraCampoConsulta}, ...}
/*/
method getFields() as array class ShippingContractRepository
	local aFields as array

	aFields := {;
		{'filial'            , 'NJJ_FILIAL' , 'C', .F.},;
		{'numeroRomaneio'    , 'NJJ_CODROM' , 'C', .T.},;
		{'tipoRomaneio'      , 'NJJ_TIPO'   , 'C', .T.},;
		{'codigoContrato'    , 'NJJ_CODCTR' , 'C', .T.},;
		{'fornecedor'        , 'NJJ_CODENT' , 'C', .T.},;
		{'loja'              , 'NJJ_LOJENT' , 'C', .T.},;
		{'nome'              , 'NJ0_NOME'   , 'C', .T.},;
		{'numeroDocumento'   , 'NJJ_DOCNUM' , 'C', .T.},;
		{'serieDocumento'    , 'NJJ_DOCSER' , 'C', .T.},;
		{'dataEmissao'       , 'NJJ_DOCEMI' , 'D', .T.},;
		{'quantidade'        , 'NJJ_QTDFIS' , 'N', .T.},;
		{'valorUnitario'     , 'NJJ_VLRUNI' , 'N', .T.},;
		{'valorTotal'        , 'NJJ_VLRTOT' , 'N', .T.},;
		{'tipoFrete'         , 'NJJ_TPFRET' , 'C', .T.},;
		{'safra'             , 'NJJ_CODSAF' , 'C', .T.},;
		{'codProduto'        , 'NJJ_CODPRO' , 'C', .T.},;
		{'descricaoProduto'  , 'B1_DESC'    , 'C', .T.},;
		{'unidade'           , 'NJJ_UM1PRO' , 'C', .T.},;
		{'status'            , 'NJJ_STATUS' , 'C', .T.};
	}

return aFields

method getJoins() as array class ShippingContractRepository
	local aJoins := {} as array

	aAdd(aJoins, {'INNER', 'SB1', Self:getWhereDefault('SB1.B1_COD = NJJ.NJJ_CODPRO', 'SB1')})
	aAdd(aJoins, {'INNER', 'NJ0', Self:getWhereDefault('NJ0.NJ0_CODENT = NJJ.NJJ_CODENT AND NJ0.NJ0_LOJENT = NJJ.NJJ_LOJENT', 'NJ0')})

return aJoins
 
