/*/
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
±±ÚÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄ±±
±±³Fun‡„o    ?Matr930Def  ?Autor ³Rafael Oliveira ?Data 13/06/2021 ³±?
±±ÃÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄ´±±
±±³Descri‡„o ³Arquivo de DEFINEs utilizados pela MATR930.                  ³±?
±±ÀÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ±±
ßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßß
/*/

#DEFINE MV_ESTADO	1
#DEFINE MV_CFOZER	2
#DEFINE MV_CAT21	3
#DEFINE MV_LJLVFIS	4
#DEFINE MV_R930SAT	5
#DEFINE MV_IMPCSS	6
#DEFINE MV_CFTR930	7
#DEFINE MV_VLCTBZL	8
#DEFINE MV_LFMD2DT	9
#DEFINE MV_P1ICMST	10
#DEFINE MV_OBSCFO	11
#DEFINE MV_NFCTEUF	12
#DEFINE MV_FAUT930	13
#DEFINE MV_CTALFE	14
#DEFINE MV_CTALFS	15
#DEFINE MV_IMPSX1	16
#DEFINE MV_LIVRESP	17
#DEFINE MV_SALTPAG	18
#DEFINE MV_P2ABER	19
#DEFINE MV_P1ABER	20
#DEFINE MV_LSAIAB	21
#DEFINE MV_LENTAB	22
#DEFINE MV_LENTEN	23
#DEFINE MV_LSAIEN	24
#DEFINE MV_LFISORD	25
#DEFINE MV_IMPCABE	26
#DEFINE MV_IMPPAGI	27
#DEFINE MV_ESTCLI	28
#DEFINE MV_PERCRJ	29
#DEFINE MV_SPED55	30
#DEFINE MV_ALIQSTN	31
#DEFINE MV_IMPZNFC	32
#DEFINE MV_ECFNOTA	33
#DEFINE MV_SM0CONT  34



//Campos
#DEFINE FP_F3_MSFIL    1
#DEFINE FP_F3_DIFAL    2
#DEFINE FP_F3_VFCPDIF  3
#DEFINE FP_F3_BASNDES  4
#DEFINE FP_F3_ICMNDES  5
#DEFINE FP_F3_VL43080  6
#DEFINE FP_F3_VLINCMG  7
#DEFINE FP_F3_CREDST   8
#DEFINE FP_F3_NUMINI   9
#DEFINE FP_F3_NUMFIM   10
#DEFINE FP_F3_VALANTI  11
#DEFINE FP_F3_CLIDVMC  12
#DEFINE FP_F3_DS43080  13
#DEFINE FP_F3_SERSAT   14
#DEFINE FP_F3_CFO		15
#DEFINE FP_F3_ALIQICM	16
#DEFINE FP_F3_VALCONT	17
#DEFINE FP_F3_BASEICM	18
#DEFINE FP_F3_VALICM	19
#DEFINE FP_F3_ISENICM	20
#DEFINE FP_F3_OUTRICM	21
#DEFINE FP_F3_BASEIPI	22
#DEFINE FP_F3_VALIPI	23
#DEFINE FP_F3_ISENIPI	24
#DEFINE FP_F3_OUTRIPI	25
#DEFINE FP_F3_OBSERV	26
#DEFINE FP_F3_VALOBSE	27
#DEFINE FP_F3_ICMSRET	28
#DEFINE FP_F3_LANCAM	29
#DEFINE FP_F3_TIPO		30
#DEFINE FP_F3_ICMSCOM	31
#DEFINE FP_F3_CODISS	32
#DEFINE FP_F3_IPIOBS	33
#DEFINE FP_F3_NRLIVRO	34
#DEFINE FP_F3_ICMAUTO	35
#DEFINE FP_F3_BASERET	36
#DEFINE FP_F3_FORMUL	37
#DEFINE FP_F3_FORMULA	38
#DEFINE FP_F3_DESPESA	39
#DEFINE FP_F3_ICMSDIF	40
#DEFINE FP_F3_TRFICM	41

#DEFINE PF3_VALOBSE   1
#DEFINE PF3_DESCZFR   2
#DEFINE PF3_DS43080   3
#DEFINE PF3_BASNDES   4
#DEFINE PF3_ICMNDES   5
#DEFINE PFT_PRINCMG   6
#DEFINE PF3_BASEICM   7
#DEFINE PF3_VALFECP   8
#DEFINE PF3_VFECPST   9
#DEFINE PF3_IPIOBS   10
#DEFINE PF3_BASERET  11
#DEFINE PF3_ICMSRET  12
#DEFINE PF3_CRPRST   13
#DEFINE PF3_ICMSCOM  14
#DEFINE PF3_VALANTI  15
#DEFINE PF3_ICMAUTO  16
#DEFINE PF3_VALTST   17
#DEFINE PF3_OBSICM   18
#DEFINE PF3_OBSSOL   19
#DEFINE PF3_DIFAL    20
#DEFINE PF3_VFCPDIF  21
 