#include "TOTVS.CH"

/*/{Protheus.doc} 
    Classe concreta da Entidade PLSBqc - Subcontract
    @type  Class
    @author FrameworkApi 1.0
    @since 20190211
/*/
Class PLSBqc from CenEntity

    Method New()
  
    Method serialize(oJsonControl)
    Method destroy()

EndClass

Method New() Class PLSBqc
	_Super:New()
Return self

Method serialize(oJsonControl) Class PLSBqc

	Local oJson := JsonObject():New()
	Default oJsonControl := PLSJsonControl():New()


    oJsonControl:setProp(oJson,"code",self:getValue("BQC_CODIGO")) 
    oJsonControl:setProp(oJson,"groupCompanyGroup",self:getValue("BQC_NUMCON")) 
    oJsonControl:setProp(oJson,"contractVersion",self:getValue("BQC_VERCON")) 
    oJsonControl:setProp(oJson,"operator",self:getValue("BQC_CODINT")) 
    oJsonControl:setProp(oJson,"groupCompany",self:getValue("BQC_CODEMP")) 
    oJsonControl:setProp(oJson,"subContract",self:getValue("BQC_SUBCON")) 
    oJsonControl:setProp(oJson,"subContractVersion",self:getValue("BQC_VERSUB")) 
    oJsonControl:setProp(oJson,"subContractDate",self:getValue("BQC_DATCON")) 
    oJsonControl:setProp(oJson,"description",self:getValue("BQC_DESCRI")) 
    oJsonControl:setProp(oJson,"reducedName",self:getValue("BQC_NREDUZ")) 
    oJsonControl:setProp(oJson,"chargeThisLevel",self:getValue("BQC_COBNIV")) 
    oJsonControl:setProp(oJson,"customerCode",self:getValue("BQC_CODCLI")) 
    oJsonControl:setProp(oJson,"cnpj",self:getValue("BQC_CNPJ")) 
    oJsonControl:setProp(oJson,"store",self:getValue("BQC_LOJA")) 
    oJsonControl:setProp(oJson,"allowsRefund",self:getValue("BQC_PODREM")) 
    oJsonControl:setProp(oJson,"financialClassCode",self:getValue("BQC_NATURE")) 
    oJsonControl:setProp(oJson,"supplier",self:getValue("BQC_CODFOR")) 
    oJsonControl:setProp(oJson,"store",self:getValue("BQC_LOJFOR")) 
    oJsonControl:setProp(oJson,"discCont",self:getValue("BQC_PERCON")) 
    oJsonControl:setProp(oJson,"dueDateType",self:getValue("BQC_TPVCPP")) 
    oJsonControl:setProp(oJson,"dueDate",self:getValue("BQC_VENCTO")) 
    oJsonControl:setProp(oJson,"operCostDueDateType",self:getValue("BQC_TPVCCO")) 
    oJsonControl:setProp(oJson,"operationalCostMaturity",self:getValue("BQC_VENCCO")) 
    oJsonControl:setProp(oJson,"allowEditingDueDate",self:getValue("BQC_ALTVEN")) 
    oJsonControl:setProp(oJson,"noCharge",self:getValue("BQC_GRATUI")) 
    oJsonControl:setProp(oJson,"chargeRetroactive",self:getValue("BQC_COBRET")) 
    oJsonControl:setProp(oJson,"calculateProRataCollec",self:getValue("BQC_COBRAT")) 
    oJsonControl:setProp(oJson,"retroactLimitDay",self:getValue("BQC_DIARET")) 
    oJsonControl:setProp(oJson,"consideraCompetence",self:getValue("BQC_CONCON")) 
    oJsonControl:setProp(oJson,"lastCollectionDate",self:getValue("BQC_ULTCOB")) 
    oJsonControl:setProp(oJson,"collectionNumber",self:getValue("BQC_NUMCOB")) 
    oJsonControl:setProp(oJson,"sponsor",self:getValue("BQC_PATROC")) 
    oJsonControl:setProp(oJson,"blockType",self:getValue("BQC_TIPBLO")) 
    oJsonControl:setProp(oJson,"blockCode",self:getValue("BQC_CODBLO")) 
    oJsonControl:setProp(oJson,"blockDate",self:getValue("BQC_DATBLO")) 
    oJsonControl:setProp(oJson,"formerContractNumber",self:getValue("BQC_ANTCON")) 
    oJsonControl:setProp(oJson,"secondCopyOfSlip",self:getValue("BQC_VL2BOL")) 
    oJsonControl:setProp(oJson,"validity",self:getValue("BQC_VALID")) 
    oJsonControl:setProp(oJson,"adjustmentMonth",self:getValue("BQC_MESREA")) 
    oJsonControl:setProp(oJson,"adjustmentIndex",self:getValue("BQC_INDREA")) 
    oJsonControl:setProp(oJson,"adjustmentPeriodicity",self:getValue("BQC_PERREJ")) 
    oJsonControl:setProp(oJson,"ledgerAccount",self:getValue("BQC_CONTAC")) 
    oJsonControl:setProp(oJson,"addressType",self:getValue("BQC_TIPEND")) 
    oJsonControl:setProp(oJson,"zip",self:getValue("BQC_CEP")) 
    oJsonControl:setProp(oJson,"address",self:getValue("BQC_LOGRAD")) 
    oJsonControl:setProp(oJson,"number",self:getValue("BQC_NUMERO")) 
    oJsonControl:setProp(oJson,"complement",self:getValue("BQC_COMPLE")) 
    oJsonControl:setProp(oJson,"district",self:getValue("BQC_BAIRRO")) 
    oJsonControl:setProp(oJson,"cityCode",self:getValue("BQC_CODMUN")) 
    oJsonControl:setProp(oJson,"city",self:getValue("BQC_MUN")) 
    oJsonControl:setProp(oJson,"state",self:getValue("BQC_ESTADO")) 
    oJsonControl:setProp(oJson,"collectionLocation",self:getValue("BQC_ENDCOB")) 
    oJsonControl:setProp(oJson,"telephone",self:getValue("BQC_TEL")) 
    oJsonControl:setProp(oJson,"importedFile",self:getValue("BQC_IMPORT")) 
    oJsonControl:setProp(oJson,"notifyAns",self:getValue("BQC_INFANS")) 
    oJsonControl:setProp(oJson,"issueMagneticCard",self:getValue("BQC_EMICAR")) 
    oJsonControl:setProp(oJson,"familyCollLevelComp",self:getValue("BQC_OBRFAM")) 
    oJsonControl:setProp(oJson,"allowToBuyProced",self:getValue("BQC_PERCOM")) 
    oJsonControl:setProp(oJson,"collectionGroup",self:getValue("BQC_GRPCOB")) 
    oJsonControl:setProp(oJson,"admissionDateCompulsory",self:getValue("BQC_OBRDAD")) 
    oJsonControl:setProp(oJson,"team",self:getValue("BQC_EQUIPE")) 
    oJsonControl:setProp(oJson,"salesRepresentative",self:getValue("BQC_CODVEN")) 
    oJsonControl:setProp(oJson,"responsibleForPurchase",self:getValue("BQC_RESCOM")) 
    oJsonControl:setProp(oJson,"whenToCharge",self:getValue("BQC_QUACOB")) 
    oJsonControl:setProp(oJson,"periodOfRenewingWait",self:getValue("BQC_NPERRN")) 
    oJsonControl:setProp(oJson,"callQuestionnaire",self:getValue("BQC_ABRQUE")) 
    oJsonControl:setProp(oJson,"limitForIssueOfForm",self:getValue("BQC_CONSLI")) 
    oJsonControl:setProp(oJson,"chLimitInForm",self:getValue("BQC_LIMCH")) 
    oJsonControl:setProp(oJson,"respPrchsPformsPgImm",self:getValue("BQC_RPGPAT")) 
    oJsonControl:setProp(oJson,"nonProfit",self:getValue("BQC_ENTFIL")) 
    oJsonControl:setProp(oJson,"hadOtherEntries",self:getValue("BQC_OUTLAN")) 
    oJsonControl:setProp(oJson,"paymentModeCode",self:getValue("BQC_TIPPAG")) 
    oJsonControl:setProp(oJson,"checkFinancialRules",self:getValue("BQC_REGFIN")) 
    oJsonControl:setProp(oJson,"customerBank",self:getValue("BQC_BCOCLI")) 
    oJsonControl:setProp(oJson,"customerBranch",self:getValue("BQC_AGECLI")) 
    oJsonControl:setProp(oJson,"checkOperGrpRules",self:getValue("BQC_REGGOP")) 
    oJsonControl:setProp(oJson,"customerAccount",self:getValue("BQC_CTACLI")) 
    oJsonControl:setProp(oJson,"operatorBank",self:getValue("BQC_PORTAD")) 
    oJsonControl:setProp(oJson,"operatorGroup",self:getValue("BQC_GRUOPE")) 
    oJsonControl:setProp(oJson,"operatorBranch",self:getValue("BQC_AGEDEP")) 
    oJsonControl:setProp(oJson,"operatorAccount",self:getValue("BQC_CTACOR")) 
    oJsonControl:setProp(oJson,"chargeInterNextMonth",self:getValue("BQC_COBJUR")) 
    oJsonControl:setProp(oJson,"dailyInterestPercentage",self:getValue("BQC_TAXDIA")) 
    oJsonControl:setProp(oJson,"dailyInterestAmount",self:getValue("BQC_JURDIA")) 
    oJsonControl:setProp(oJson,"majority",self:getValue("BQC_MAIORI")) 
    oJsonControl:setProp(oJson,"generateFormViaPos",self:getValue("BQC_GUIPOS")) 
    oJsonControl:setProp(oJson,"classificationForInss",self:getValue("BQC_CLAINS")) 
    oJsonControl:setProp(oJson,"salesman2Code",self:getValue("BQC_CODVE2")) 
    oJsonControl:setProp(oJson,"criticDescription",self:getValue("BQC_CRGPOS")) 
    oJsonControl:setProp(oJson,"reasonForIndexation",self:getValue("BQC_MOTREA")) 
    oJsonControl:setProp(oJson,"indexationCharact",self:getValue("BQC_CARREA")) 
    oJsonControl:setProp(oJson,"lineIndexation",self:getValue("BQC_REALIN")) 
    oJsonControl:setProp(oJson,"namePrintedInCard",self:getValue("BQC_NOMCAR")) 
    oJsonControl:setProp(oJson,"cardInformation",self:getValue("BQC_INFCAR")) 
    oJsonControl:setProp(oJson,"doesItGrpInvNfsItems",self:getValue("BQC_AGLUT")) 
    oJsonControl:setProp(oJson,"invoiceOutflowType",self:getValue("BQC_CODTES")) 
    oJsonControl:setProp(oJson,"numberOfUs",self:getValue("BQC_QTDUS")) 
    oJsonControl:setProp(oJson,"period",self:getValue("BQC_QTDPUS")) 
    oJsonControl:setProp(oJson,"unit",self:getValue("BQC_UNIPUS")) 
    oJsonControl:setProp(oJson,"checkLimitOrNot",self:getValue("BQC_VERLIM")) 
    oJsonControl:setProp(oJson,"indicateInstallOrNot",self:getValue("BQC_PACOOK")) 
    oJsonControl:setProp(oJson,"settleDebit",self:getValue("BQC_LIQUID")) 
    oJsonControl:setProp(oJson,"monthsForSettlelm",self:getValue("BQC_MESLIQ")) 
    oJsonControl:setProp(oJson,"minimumValue",self:getValue("BQC_VLRMIN")) 
    oJsonControl:setProp(oJson,"minimumPercentage",self:getValue("BQC_PERMIN")) 
    oJsonControl:setProp(oJson,"installmentValue",self:getValue("BQC_VLRPAR")) 
    oJsonControl:setProp(oJson,"minInstallm",self:getValue("BQC_PERPAR")) 
    oJsonControl:setProp(oJson,"monthsNumber",self:getValue("BQC_QTSMES")) 
    oJsonControl:setProp(oJson,"sponsorship",self:getValue("BQC_PERPAT")) 
    oJsonControl:setProp(oJson,"patronalReimbrsmttblcode",self:getValue("BQC_CODPAT")) 
    oJsonControl:setProp(oJson,"collectionMethod",self:getValue("BQC_MDFTPT")) 
    oJsonControl:setProp(oJson,"nrOfDefaultDays",self:getValue("BQC_DIASIN")) 
    oJsonControl:setProp(oJson,"erpProductCode",self:getValue("BQC_CODSB1")) 
    oJsonControl:setProp(oJson,"tbCopartHospitalizCost",self:getValue("BQC_TABCOP")) 
    oJsonControl:setProp(oJson,"discardLegalAge",self:getValue("BQC_BQDEFI")) 
    oJsonControl:setProp(oJson,"specificInssRegister",self:getValue("BQC_CEINSS")) 
    oJsonControl:setProp(oJson,"reciprocityAnsRecord",self:getValue("BQC_RECANS")) 
    oJsonControl:setProp(oJson,"acknowledgedRn309",self:getValue("BQC_CIE309")) 
    oJsonControl:setProp(oJson,"benefAdm",self:getValue("BQC_SEASPL")) 
    oJsonControl:setProp(oJson,"benefitAdmCompName",self:getValue("BQC_RAZSBE")) 
    oJsonControl:setProp(oJson,"automaticCompensation",self:getValue("BQC_COMAUT")) 
    oJsonControl:setProp(oJson,"caepfNumber",self:getValue("BQC_CAEPF")) 
    oJsonControl:setProp(oJson,"einAdministrator",self:getValue("BQC_CNPADM")) 

Return oJson

Method destroy() Class PLSBqc
	_Super:destroy()
	DelClassIntF()
return