#include "TOTVS.CH"

/*/{Protheus.doc} 
    Classe concreta da Entidade PLSBa3 - User Families
    @type  Class
    @author FrameworkApi 1.0
    @since 20190211
/*/
Class PLSBa3 from CenEntity

    Method New()
  
    Method serialize(oJsonControl)
    Method destroy()

EndClass

Method New() Class PLSBa3
	_Super:New()
Return self

Method serialize(oJsonControl) Class PLSBa3

	Local oJson := JsonObject():New()
	Default oJsonControl := PLSJsonControl():New()


    oJsonControl:setProp(oJson,"operator",self:getValue("BA3_CODINT")) 
    oJsonControl:setProp(oJson,"groupCompany",self:getValue("BA3_CODEMP")) 
    oJsonControl:setProp(oJson,"companyContract",self:getValue("BA3_CONEMP")) 
    oJsonControl:setProp(oJson,"contractVersion",self:getValue("BA3_VERCON")) 
    oJsonControl:setProp(oJson,"subContract",self:getValue("BA3_SUBCON")) 
    oJsonControl:setProp(oJson,"subContractVersion",self:getValue("BA3_VERSUB")) 
    oJsonControl:setProp(oJson,"adhesionStatement",self:getValue("BA3_NUMCON")) 
    oJsonControl:setProp(oJson,"registration",self:getValue("BA3_MATRIC")) 
    oJsonControl:setProp(oJson,"registrationInCompany",self:getValue("BA3_MATEMP")) 
    oJsonControl:setProp(oJson,"formerRegistration",self:getValue("BA3_MATANT")) 
    oJsonControl:setProp(oJson,"contractTime",self:getValue("BA3_HORACN")) 
    oJsonControl:setProp(oJson,"chargeThisLevel",self:getValue("BA3_COBNIV")) 
    oJsonControl:setProp(oJson,"dueDate",self:getValue("BA3_VENCTO")) 
    oJsonControl:setProp(oJson,"additionDate",self:getValue("BA3_DATBAS")) 
    oJsonControl:setProp(oJson,"allowReimburs",self:getValue("BA3_PODREM")) 
    oJsonControl:setProp(oJson,"adjustmentDate",self:getValue("BA3_DATCIV")) 
    oJsonControl:setProp(oJson,"adjustmentMonth",self:getValue("BA3_MESREA")) 
    oJsonControl:setProp(oJson,"adjustmentIndex",self:getValue("BA3_INDREA")) 
    oJsonControl:setProp(oJson,"customerCode",self:getValue("BA3_CODCLI")) 
    oJsonControl:setProp(oJson,"storeCode",self:getValue("BA3_LOJA")) 
    oJsonControl:setProp(oJson,"contractType",self:getValue("BA3_TIPOUS")) 
    oJsonControl:setProp(oJson,"financialClassCode",self:getValue("BA3_NATURE")) 
    oJsonControl:setProp(oJson,"supplier",self:getValue("BA3_CODFOR")) 
    oJsonControl:setProp(oJson,"store",self:getValue("BA3_LOJFOR")) 
    oJsonControl:setProp(oJson,"reasonForBlock",self:getValue("BA3_MOTBLO")) 
    oJsonControl:setProp(oJson,"blockDate",self:getValue("BA3_DATBLO")) 
    oJsonControl:setProp(oJson,"planCode",self:getValue("BA3_CODPLA")) 
    oJsonControl:setProp(oJson,"version",self:getValue("BA3_VERSAO")) 
    oJsonControl:setProp(oJson,"paymentMode",self:getValue("BA3_FORPAG")) 
    oJsonControl:setProp(oJson,"typeContract",self:getValue("BA3_TIPCON")) 
    oJsonControl:setProp(oJson,"planSegment",self:getValue("BA3_SEGPLA")) 
    oJsonControl:setProp(oJson,"paymentMode",self:getValue("BA3_MODPAG")) 
    oJsonControl:setProp(oJson,"formOfCharAdmFee",self:getValue("BA3_FORCTX")) 
    oJsonControl:setProp(oJson,"chargeFeeImmediately",self:getValue("BA3_TXUSU")) 
    oJsonControl:setProp(oJson,"optionalCollectMode",self:getValue("BA3_FORCOP")) 
    oJsonControl:setProp(oJson,"payrollEmployeeRegistr",self:getValue("BA3_AGMTFU")) 
    oJsonControl:setProp(oJson,"regulated",self:getValue("BA3_APLEI")) 
    oJsonControl:setProp(oJson,"branchCode",self:getValue("BA3_AGFTFU")) 
    oJsonControl:setProp(oJson,"salary",self:getValue("BA3_VALSAL")) 
    oJsonControl:setProp(oJson,"salaryCalcRoutine",self:getValue("BA3_ROTSAL")) 
    oJsonControl:setProp(oJson,"team",self:getValue("BA3_EQUIPE")) 
    oJsonControl:setProp(oJson,"salesRepresentative",self:getValue("BA3_CODVEN")) 
    oJsonControl:setProp(oJson,"collectionLocation",self:getValue("BA3_ENDCOB")) 
    oJsonControl:setProp(oJson,"zip",self:getValue("BA3_CEP")) 
    oJsonControl:setProp(oJson,"address",self:getValue("BA3_END")) 
    oJsonControl:setProp(oJson,"number",self:getValue("BA3_NUMERO")) 
    oJsonControl:setProp(oJson,"complement",self:getValue("BA3_COMPLE")) 
    oJsonControl:setProp(oJson,"district",self:getValue("BA3_BAIRRO")) 
    oJsonControl:setProp(oJson,"cityCode",self:getValue("BA3_CODMUN")) 
    oJsonControl:setProp(oJson,"city",self:getValue("BA3_MUN")) 
    oJsonControl:setProp(oJson,"state",self:getValue("BA3_ESTADO")) 
    oJsonControl:setProp(oJson,"operatorUserCode",self:getValue("BA3_USUOPE")) 
    oJsonControl:setProp(oJson,"dateOfTyping",self:getValue("BA3_DATCON")) 
    oJsonControl:setProp(oJson,"timeOfTyping",self:getValue("BA3_HORCON")) 
    oJsonControl:setProp(oJson,"collectionGroup",self:getValue("BA3_GRPCOB")) 
    oJsonControl:setProp(oJson,"coParticipationTable",self:getValue("BA3_CODTDE")) 
    oJsonControl:setProp(oJson,"cityDescription",self:getValue("BA3_DESMUN")) 
    oJsonControl:setProp(oJson,"importedRecord",self:getValue("BA3_RGIMP")) 
    oJsonControl:setProp(oJson,"dismissed",self:getValue("BA3_DEMITI")) 
    oJsonControl:setProp(oJson,"dismissalDate",self:getValue("BA3_DATDEM")) 
    oJsonControl:setProp(oJson,"reasonForDismissal",self:getValue("BA3_MOTDEM")) 
    oJsonControl:setProp(oJson,"attendanceLimit",self:getValue("BA3_LIMATE")) 
    oJsonControl:setProp(oJson,"scope",self:getValue("BA3_ABRANG")) 
    oJsonControl:setProp(oJson,"informCoverage",self:getValue("BA3_INFCOB")) 
    oJsonControl:setProp(oJson,"informCoverageGroup",self:getValue("BA3_INFGCB")) 
    oJsonControl:setProp(oJson,"importedFile",self:getValue("BA3_IMPORT")) 
    oJsonControl:setProp(oJson,"formerSystemValue",self:getValue("BA3_VALANT")) 
    oJsonControl:setProp(oJson,"previousLetter",self:getValue("BA3_LETANT")) 
    oJsonControl:setProp(oJson,"dateOfLastChange",self:getValue("BA3_DATALT")) 
    oJsonControl:setProp(oJson,"calcProRataCollection",self:getValue("BA3_COBRAT")) 
    oJsonControl:setProp(oJson,"pRataExitFMajority",self:getValue("BA3_RATMAI")) 
    oJsonControl:setProp(oJson,"chargeRetroactive",self:getValue("BA3_COBRET")) 
    oJsonControl:setProp(oJson,"retroactiveLimitDay",self:getValue("BA3_DIARET")) 
    oJsonControl:setProp(oJson,"lastCollectDate",self:getValue("BA3_ULTCOB")) 
    oJsonControl:setProp(oJson,"chargeProRataOnOutflo",self:getValue("BA3_RATSAI")) 
    oJsonControl:setProp(oJson,"collectionNumber",self:getValue("BA3_NUMCOB")) 
    oJsonControl:setProp(oJson,"lastAdjYearMonth",self:getValue("BA3_ULREA")) 
    oJsonControl:setProp(oJson,"printBooklet",self:getValue("BA3_CARIMP")) 
    oJsonControl:setProp(oJson,"transactYearMonth",self:getValue("BA3_PERMOV")) 
    oJsonControl:setProp(oJson,"collectionModeLevel",self:getValue("BA3_NIVFOR")) 
    oJsonControl:setProp(oJson,"adhesionFeeModeLevel",self:getValue("BA3_NIVFTX")) 
    oJsonControl:setProp(oJson,"optionalFormLevel",self:getValue("BA3_NIVFOP")) 
    oJsonControl:setProp(oJson,"otherEntries",self:getValue("BA3_OUTLAN")) 
    oJsonControl:setProp(oJson,"blockedFamilyRegistr",self:getValue("BA3_MATFMB")) 
    oJsonControl:setProp(oJson,"accomodationCode",self:getValue("BA3_CODACO")) 
    oJsonControl:setProp(oJson,"transferOrigin",self:getValue("BA3_TRAORI")) 
    oJsonControl:setProp(oJson,"transferDestination",self:getValue("BA3_TRADES")) 
    oJsonControl:setProp(oJson,"calculationRoutine",self:getValue("BA3_ROTINA")) 
    oJsonControl:setProp(oJson,"validity",self:getValue("BA3_VALID")) 
    oJsonControl:setProp(oJson,"planLastModificDate",self:getValue("BA3_DATPLA")) 
    oJsonControl:setProp(oJson,"holderSeverance",self:getValue("BA3_DESLIG")) 
    oJsonControl:setProp(oJson,"holderSeveranceDate",self:getValue("BA3_DATDES")) 
    oJsonControl:setProp(oJson,"transferLotNumber",self:getValue("BA3_LOTTRA")) 
    oJsonControl:setProp(oJson,"blockBilling",self:getValue("BA3_BLOFAT")) 
    oJsonControl:setProp(oJson,"rdaFDescInMedProd",self:getValue("BA3_CODRDA")) 
    oJsonControl:setProp(oJson,"debitEntryCode",self:getValue("BA3_CODLAN")) 
    oJsonControl:setProp(oJson,"codeOfPaymentMode",self:getValue("BA3_TIPPAG")) 
    oJsonControl:setProp(oJson,"customerBank",self:getValue("BA3_BCOCLI")) 
    oJsonControl:setProp(oJson,"customerBranch",self:getValue("BA3_AGECLI")) 
    oJsonControl:setProp(oJson,"customerAccount",self:getValue("BA3_CTACLI")) 
    oJsonControl:setProp(oJson,"userDeadline",self:getValue("BA3_LIMITE")) 
    oJsonControl:setProp(oJson,"operatorBank",self:getValue("BA3_PORTAD")) 
    oJsonControl:setProp(oJson,"operatorBranch",self:getValue("BA3_AGEDEP")) 
    oJsonControl:setProp(oJson,"operatorAccount",self:getValue("BA3_CTACOR")) 
    oJsonControl:setProp(oJson,"monthlyFeeDiscount",self:getValue("BA3_DESMEN")) 
    oJsonControl:setProp(oJson,"salesRepresent2Code",self:getValue("BA3_CODVE2")) 
    oJsonControl:setProp(oJson,"considerBlock",self:getValue("BA3_CONSID")) 
    oJsonControl:setProp(oJson,"comfortStandard",self:getValue("BA3_PADSAU")) 
    oJsonControl:setProp(oJson,"portabilityOldPlan",self:getValue("BA3_PLPOR")) 
    oJsonControl:setProp(oJson,"groupItensInvNfs",self:getValue("BA3_AGLUT")) 
    oJsonControl:setProp(oJson,"indicateIfInstalOrNot",self:getValue("BA3_PACOOK")) 
    oJsonControl:setProp(oJson,"nrOfDefaultDays",self:getValue("BA3_DIASIN")) 
    oJsonControl:setProp(oJson,"invoiceOutflowType",self:getValue("BA3_CODTES")) 
    oJsonControl:setProp(oJson,"erpProductCode",self:getValue("BA3_CODSB1")) 
    oJsonControl:setProp(oJson,"solReimbPortalAsset",self:getValue("BA3_REEWEB")) 
    oJsonControl:setProp(oJson,"fieldTargetedToLink",self:getValue("BA3_GRPFAM")) 
    oJsonControl:setProp(oJson,"typePaymment",self:getValue("BA3_TIPPGO")) 
    oJsonControl:setProp(oJson,"organizationalUnit",self:getValue("BA3_UNDORG")) 
    oJsonControl:setProp(oJson,"notifyBeneficiary",self:getValue("BA3_NOTB")) 
    oJsonControl:setProp(oJson,"automaticCompensation",self:getValue("BA3_COMAUT")) 
    oJsonControl:setProp(oJson,"linkType",self:getValue("BA3_TIPVIN")) 
    oJsonControl:setProp(oJson,"familyTrackingCode",self:getValue("BA3_CODRAS")) 

Return oJson

Method destroy() Class PLSBa3
	_Super:destroy()
	DelClassIntF()
return