#Include "Protheus.ch"
#Include "RwMake.ch"
#Include "FwBrowse.ch"
#Include "FwMvcDef.ch"
#Include "TOPCONN.ch"
#INCLUDE "TBICONN.CH"
#include 'tlpp-core.th'
#include 'tlpp-rest.th'
#include 'classificadorfiscal.ch'

Using Namespace totvs.protheus.backoffice.fiscal.Classifier

Function classFis()

	Local lExtCJHCJF := AliasInDic("CJH") .And. AliasInDic("CJF")
	Local lExistCJE := AliasInDic("CJE")
	Local lExistCJK  := AliasInDic("CJK")
	Local jParam := Nil
	Local lAutomato := IsBlind()

	If lExtCJHCJF .And. lExistCJE .And. lExistCJK

		//Abertura das tabelas da classificação Tributária
		AbertTabela()

		//Importação dos parametros iniciais do classificador
		ParametrosClassifis(lAutomato)

		//Importação do De/Para de formulas de base de calculo
		ImpDeParaFormul()

		//Importação da natureza de operação e finalidade
		ImpNatOper(lAutomato)

		//Importação dos enquadramentos
		ImpEnquad()

		jParam := GetParamCJE()

		If &(jParam:INTEGRAREGRA) .And. !Empty(jParam:USERNAMEDEFAULT) .And. !Empty(jParam:SENHADEFAULT)
			//Importação das regras
			oGetRegra := FISRetornaRegra():new()

			Processa({|| oGetRegra:FISRetornaRegra()}, STR0213 + "...", STR0214) //"Aguarde" "Atualizando as Regras"

			oIntegrRegras := FISGetRegrasClassificador():new()

			Processa({|| oIntegrRegras:IntegrConfig()}, STR0213 + "...", STR0215) //"Aguarde" "Integrando as Regras"

		EndIf

		If !lAutomato
			//Abertura do classificador fiscal
			FwCallApp("clasfis")
		EndIf
	Else
		MsgAlert(STR0216) //"Dicionário desatualizado, favor baixar o último pacote!"
	EndIf

return

/*/{Protheus.doc ParametrosClassifis
	Função responsavel pela importação da tabela de parametros iniciais
	@type  Function
	@author Erich Buttner
	@since 23/11/2022
	@version version
	@param param_name, param_type, param_descr
	@return return_var, return_type, return_description
	@example
	(examples)
	@see (links_or_references)
    /*/
Function ParametrosClassifis(lAutomato)

	Local aParam    := {}
	Local aUser     := {"",""}

	Local cIntRegra := ".F."

	Default lAutomato := .F.

	If lAutomato
		aUser     := {"TESTE","1234"}
		cIntRegra := ".T."
	EndIf


	//Parametro   Conteudo
	aParam := { {"URLREGRA",            "https://api-gateway.systax.com.br"     },;
		{"USERNAMEDEFAULT",     aUser[1]                                },;
		{"SENHADEFAULT",        aUser[2]                                },;
		{"CODREGALIQ",          "001"                                   },;
		{"CODREGBASE",          "001"                                   },;
		{"CODREGREGRA",         "001"                                   },;
		{"URLPRINCIPAL",        "https://app.systax.com.br"             },;
		{"INTEGRAREGRA",        cIntRegra                               },;
		{"INTEGRANCM",          ".F."                                   },;
		{"CODPERFOPER",         "001"                                   },;
		{"CODREGCST",           "001"                                   },;
		{"URLREGRA2",           "https://wscockpit.systax.com.br/api"   },;
		{"GRVLOGENVPRODSYSTAX", ".T."                                   } }


	FISImportCarga():ImpParamClassif(aParam)

	FWFreeArray(aParam)

Return

/*/{Protheus.doc ImpDeParaFormul
	Função responsavel pela importação
	da tabela de De/Para de formulas de
	base de calculo do classificador e configurador
	@type  Function
	@author Erich Buttner
	@since 23/11/2022
	@version version
	@param param_name, param_type, param_descr
	@return return_var, return_type, return_description
	@example
	(examples)
	@see (links_or_references)
    /*/
Function ImpDeParaFormul()

	Local aDeParaForm := {}

	//Formula Systax     Formula Configurador
	aDeParaForm := { {"qTrib * vUnTrib",        "O:VAL_MERCADORIA"          },;
		{"vFrete",                 "O:FRETE"                   },;
		{"vSeg",                   "O:SEGURO"                  },;
		{"vDesc",                  "O:DESCONTO"                },;
		{"vOutros",                "O:DESPESAS"                },;
		{"vOutro",                 "O:DESPESAS"                },;
		{"qBCProd",                "O:QUANTIDADE"              },;
		{"p_red_bc",               "I:PERC_REDUCAO_BASE"       },;
		{"pRedBCST",               "I:PERC_REDUCAO_BASE"       },;
		{"pRedBC",                 "I:PERC_REDUCAO_BASE"       },;
		{"qTrib * valor_pauta",    "O:QUANTIDADE * I:PAUTA"    },;
		{"pMVAST",                 "I:MVA"                     },;
		{"valor_pauta * qTrib",    "O:QUANTIDADE * I:PAUTA"    },;
		{"qTrib x vUnTrib",        "O:VAL_MERCADORIA"          },;
		{"pRedBC",                 "I:PERC_REDUCAO_BASE"       },;
		{"qUnid",                  "O:QUANTIDADE"              },;
		{"qTrib*vProdUni",         "O:VAL_MERCADORIA"          },;
		{"qTrib*vUnTrib",          "O:VAL_MERCADORIA"          },;
		{"vIPI",                   "TRIBIPI"                   },;
		{"vPIS",                   "TRIBPIS"                   },;
		{"vCOFINS",                "TRIBCOFINS"                },;
		{"pICMS",                  "ALIQICMS"                  },;
		{"(1 - (pICMS / 100))",    "ALIQICMS"                  },;
		{"vAliqProd",              "ALIQTRIB"                  } }


	FISImportCarga():ImpDeParaFormul(aDeParaForm)

	FWFreeArray(aDeParaForm)

Return


/*/{Protheus.doc ImpNatOper
	Função responsavel pela importação
	da tabela de Natureza de Operação e Finalidade
	@type  Function
	@author Erich Buttner
	@since 23/11/2022
	@version version
	@param param_name, param_type, param_descr
	@return return_var, return_type, return_description
	@example
	(examples)
	@see (links_or_references)
    /*/
Function ImpNatOper(lAutomato)

	//"ID"  "Descrição"                                                                                                                                                                                                         "Grupo"                              "CFOP Intra"    "CFOP Inter"    "CFOP Ex"   "CFOP Intra ST" "CFOP Inter ST" "CFOP Intra ST Subs."   "CFOP Inter ST Subs."
	Local aNatOperFin := {;
		{"43" , "Compra de material para uso ou consumo",                                                                                                                                                                           "Compra",                            "1556",         "2556",         "3556",     "1407",         "2407",         "1407",                 "2407" },;
		{"174", "Recebimento em transferência para industrialização ou produção rural",                                                                                                                                             "Industrialização",                  "1151",         "2151",         "3949",     "1408",         "2408",         "1408",                 "2408" },;
		{"175", "Recebimento em transferência para comercialização",                                                                                                                                                                "Transferência",                     "1152",         "2152",         "3949",     "1409",         "2409",         "1409",                 "2409" },;
		{"188", "Entrada de mercadoria recebida para Depósito em Depósito fechado",                                                                                                                                                 "Armazenagem",                       "1905",         "2905",         "3949",     "1905",         "2905",         "1905",                 "2905" },;
		{"189", "Entrada de mercadoria recebida para Depósito em armazém geral",                                                                                                                                                    "Armazenagem",                       "1905",         "2905",         "3949",     "1905",         "2905",         "1905",                 "2905" },;
		{"197", "Entrada de amostra grátis",                                                                                                                                                                                        "Outras entradas",                   "1911",         "2911",         "3949",     "1911",         "2911",         "1911",                 "2911" },;
		{"198", "Entrada de mercadoria em demonstração",                                                                                                                                                                            "Outras entradas",                   "1912",         "2912",         "3949",     "1912",         "2912",         "1912",                 "2912" },;
		{"200", "Retorno de mercadoria remetida em exposição ou feira",                                                                                                                                                             "Retorno",                           "1914",         "2914",         "3949",     "1914",         "2914",         "1914",                 "2914" },;
		{"201", "Entrada de mercadoria ou bem recebido para conserto ou reparo",                                                                                                                                                    "Outras entradas",                   "1915",         "2915",         "3949",     "1915",         "2915",         "1915",                 "2915" },;
		{"202", "Compra para insumo",                                                                                                                                                                                               "Compra",                            "1101",         "2101",         "3101",     "1401",         "2401",         "1401",                 "2401" },;
		{"204", "Entrada de mercadoria recebida em consignação mercantil",                                                                                                                                                          "Outras entradas",                   "1917",         "2917",         "3949",     "1917",         "2917",         "1917",                 "2917" },;
		{"205", "Entrada de mercadoria recebida em consignação industrial",                                                                                                                                                         "Outras entradas",                   "1917",         "2917",         "3949",     "1917",         "2917",         "1917",                 "2917" },;
		{"220", "Compra de bem para o ativo imobilizado",                                                                                                                                                                           "Compra",                            "1551",         "2551",         "3551",     "1406",         "2406",         "1406",                 "2406" },;
		{"320", "Transferência de bem do ativo imobilizado",                                                                                                                                                                        "Transferência",                     "1552",         "2552",         "3949",     "1552",         "2552",         "1552",                 "2552" },;
		{"325", "Recebimento em transferência de material para uso ou consumo",                                                                                                                                                     "Transferência",                     "1557",         "2557",         "3949",     "1557",         "2557",         "1557",                 "2557" },;
		{"353", "Entrada de bonificação",                                                                                                                                                                                           "Outras entradas",                   "1910",         "2910",         "3949",     "1910",         "2910",         "1910",                 "2910" },;
		{"569", "Compra para comercialização",                                                                                                                                                                                      "Compra",                            "1102",         "2102",         "3102",     "1403",         "2403",         "1403",                 "2403" },;
		{"804", "Compra para uso na prestação de serviço sujeito ao ISS",                                                                                                                                                           "Compra",                            "1128",         "2128",         "3128",     "1403",         "2403",         "1403",                 "2403" },;
		{"101", "Remessa de mercadoria ou bem para exposição ou feira",                                                                                                                                                             "Remessa",                           "5914",         "6914",         "7949",     "5914",         "6914",         "5914",                 "6914" },;
		{"104", "Remessa de mercadoria para depósito fechado",                                                                                                                                                                      "Armazenagem",                       "5905",         "6905",         "7949",     "5905",         "6905",         "5905",                 "6905" },;
		{"105", "Remessa de mercadoria para armazém geral",                                                                                                                                                                         "Armazenagem",                       "5905",         "6905",         "7949",     "5905",         "6905",         "5905",                 "6905" },;
		{"107", "Saída em Transferência de produção do estabelecimento",                                                                                                                                                            "Transferência",                     "5151",         "6151",         "7949",     "5408",         "6408",         "5408",                 "6408" },;
		{"108", "Saída em Transferência de mercadoria adquirida ou recebida de terceiros",                                                                                                                                          "Transferência",                     "5152",         "6152",         "7949",     "5409",         "6409",         "5409",                 "6409" },;
		{"120", "Venda de produção do estabelecimento",                                                                                                                                                                             "Venda",                             "5101",         "6101",         "7101",     "5101",         "6401",         "5401",                 "6401" },;
		{"121", "Venda de mercadoria adquirida ou recebida de terceiros",                                                                                                                                                           "Venda",                             "5102",         "6102",         "7102",     "5405",         "6404",         "5403",                 "6403" },;
		{"145", "Saída em Transferência de bem do ativo imobilizado",                                                                                                                                                               "Transferência",                     "5552",         "6552",         "7949",     "5552",         "6552",         "5552",                 "6552" },;
		{"147", "Venda de bem do ativo imobilizado",                                                                                                                                                                                "Venda",                             "5551",         "6551",         "7551",     "5551",         "6551",         "5551",                 "6551" },;
		{"148", "Saída em Transferência de material de uso ou consumo",                                                                                                                                                             "Transferência",                     "5557",         "6557",         "7949",     "5557",         "6557",         "5557",                 "6557" },;
		{"159", "Remessa de mercadoria em amostra grátis",                                                                                                                                                                          "Outras saídas",                     "5911",         "6911",         "7949",     "5911",         "6911",         "5911",                 "6911" },;
		{"160", "Remessa de mercadoria em demonstração",                                                                                                                                                                            "Remessa",                           "5912",         "6912",         "7949",     "5405",         "6912",         "5912",                 "6912" },;
		{"162", "Remessa de mercadoria ou bem para conserto ou reparo",                                                                                                                                                             "Remessa",                           "5915",         "6915",         "7949",     "5915",         "6915",         "5915",                 "6915" },;
		{"537", "Remessa de mercadoria recebida de terceiros em bonificação",                                                                                                                                                       "Outras saídas",                     "5910",         "6910",         "7949",     "5910",         "6910",         "5910",                 "6910" },;
		{"547", "Remessa de mercadoria de produção própria em consignação mercantil",                                                                                                                                               "Remessa",                           "5917",         "6917",         "7949",     "5917",         "6917",         "5917",                 "6917" },;
		{"549", "Remessa de mercadoria em consignação industrial",                                                                                                                                                                  "Remessa",                           "5917",         "6917",         "7949",     "5917",         "6917",         "5917",                 "6917" },;
		{"793", "Aquisição de serviço de transporte iniciado em unidade da Federação diversa daquela onde inscrito o prestador",                                                                                                    "Entrada",                           "1932",         "2932",         "3949",     "1932",         "2932",         "1932",                 "2932" },;
		{"799", "Aquisição de serviço de transporte iniciado em unidade da Federação diversa daquela onde inscrito o prestador (CT-e Complementar)",                                                                                "Entrada",                           "1932",         "2932",         "3949",     "1949",         "2949",         "1949",                 "2949" },;
		{"800", "Aquisição de serviço de transporte iniciado em unidade da Federação diversa daquela onde inscrito o prestador (CT-e Substituto)",                                                                                  "Entrada",                           "1932",         "2932",         "3949",     "1949",         "2949",         "1949",                 "2949" },;
		{"801", "Aquisição de serviço de transporte para execução de serviço da mesma natureza",                                                                                                                                    "Entrada",                           "1351",         "2351",         "3351",     "1351",         "2351",         "1351",                 "2351" },;
		{"794", "Aquisição de serviço de transporte por contribuinte substituto em relação ao serviço de transporte.",                                                                                                              "Entrada",                           "1360",         "2949",         "3949",     "1360",         "2949",         "1360",                 "2949" },;
		{"797", "Aquisição de serviço de transporte por contribuinte substituto em relação ao serviço de transporte. (CT-e Complementar)",                                                                                          "Entrada",                           "1360",         "2949",         "3949",     "1360",         "2949",         "1360",                 "2949" },;
		{"798", "Aquisição de serviço de transporte por contribuinte substituto em relação ao serviço de transporte. (CT-e Substituto)",                                                                                            "Entrada",                           "1360",         "2949",         "3949",     "1360",         "2949",         "1949",                 "2949" },;
		{"792", "Aquisição de serviço de transporte por estabelecimento comercial",                                                                                                                                                 "Entrada",                           "1353",         "2353",         "3353",     "1949",         "2949",         "1949",                 "2949" },;
		{"795", "Aquisição de serviço de transporte por estabelecimento comercial (CT-e Complementar)",                                                                                                                             "Entrada",                           "1353",         "2353",         "3353",     "1949",         "2949",         "1949",                 "2949" },;
		{"796", "Aquisição de serviço de transporte por estabelecimento comercial (CT-e Substituto)",                                                                                                                               "Entrada",                           "1353",         "2353",         "3353",     "1949",         "2949",         "1949",                 "2949" },;
		{"791", "Aquisição de serviço de transporte por estabelecimento industrial",                                                                                                                                                "Entrada",                           "1352",         "2352",         "3352",     "1949",         "2949",         "1949",                 "2949" },;
		{"263", "Compra para utilização no serviço de transporte público ferroviário de passageiros",                                                                                                                               "Compra",                            "1126",         "2126",         "3126",     "1126",         "2126",         "1126",                 "2126" },;
		{"696", "Prestação de serviço de transporte a contribuinte substituto em relação ao serviço de transporte",                                                                                                                 "Prest. serv. transporte (ICMS)",    "5360",         "6360",         "7949",     "5360",         "6360",         "5360",                 "6360" },;
		{"756", "Prestação de serviço de transporte a contribuinte substituto em relação ao serviço de transporte - CT-e Complementar",                                                                                             "Prest. serv. transporte (ICMS)",    "5360",         "6360",         "7949",     "5360",         "6360",         "5360",                 "6360" },;
		{"758", "Prestação de serviço de transporte a contribuinte substituto em relação ao serviço de transporte - CT-e Globalizado",                                                                                              "Prest. serv. transporte (ICMS)",    "5360",         "6360",         "7949",     "5360",         "6360",         "5360",                 "6360" },;
		{"759", "Prestação de serviço de transporte a contribuinte substituto em relação ao serviço de transporte - CT-e OS",                                                                                                       "Prest. serv. transporte (ICMS)",    "5360",         "6360",         "7949",     "5360",         "6360",         "5360",                 "6360" },;
		{"757", "Prestação de serviço de transporte a contribuinte substituto em relação ao serviço de transporte - CT-e Substituto",                                                                                               "Prest. serv. transporte (ICMS)",    "5360",         "6360",         "7949",     "5360",         "6360",         "5360",                 "6360" },;
		{"693", "Prestação de serviço de transporte a estabelecimento comercial",                                                                                                                                                   "Prest. serv. transporte (ICMS)",    "5353",         "6353",         "7358",     "5353",         "6353",         "5353",                 "6353" },;
		{"752", "Prestação de serviço de transporte a estabelecimento comercial (CT-e Complementar)",                                                                                                                               "Prest. serv. transporte (ICMS)",    "5353",         "6353",         "7949",     "5353",         "6353",         "5353",                 "6353" },;
		{"755", "Prestação de serviço de transporte a estabelecimento comercial (CT-e Globalizado)",                                                                                                                                "Prest. serv. transporte (ICMS)",    "5353",         "6353",         "7949",     "5353",         "6353",         "5353",                 "6353" },;
		{"754", "Prestação de serviço de transporte a estabelecimento comercial (CT-e OS)",                                                                                                                                         "Prest. serv. transporte (ICMS)",    "5353",         "6353",         "7949",     "5353",         "6353",         "5353",                 "6353" },;
		{"753", "Prestação de serviço de transporte a estabelecimento comercial (CT-e Substituto)",                                                                                                                                 "Prest. serv. transporte (ICMS)",    "5353",         "6353",         "7949",     "5353",         "6353",         "5353",                 "6353" },;
		{"692", "Prestação de serviço de transporte a estabelecimento industrial",                                                                                                                                                  "Prest. serv. transporte (ICMS)",    "5352",         "6352",         "7949",     "5352",         "6352",         "5352",                 "6352" },;
		{"695", "Prestação de serviço de transporte a não contribuinte",                                                                                                                                                            "Prest. serv. transporte (ICMS)",    "5357",         "6357",         "",         "",             "",             "",                     ""     },;
		{"694", "Prestação de serviço de transporte iniciada em unidade da Federação diversa daquela onde inscrito o prestador",                                                                                                    "Prest. serv. transporte (ICMS)",    "5932",         "6932",         "7949",     "5932",         "6932",         "5932",                 "6932" },;
		{"762", "Prestação de serviço de transporte iniciada em unidade da Federação diversa daquela onde inscrito o prestador (CT-e Complementar)",                                                                                "Prest. serv. transporte (ICMS)",    "5932",         "6932",         "7949",     "5932",         "6932",         "5932",                 "6932" },;
		{"764", "Prestação de serviço de transporte iniciada em unidade da Federação diversa daquela onde inscrito o prestador (CT-e Globalizado)",                                                                                 "Prest. serv. transporte (ICMS)",    "5932",         "6932",         "7949",     "5932",         "6932",         "5932",                 "6932" },;
		{"763", "Prestação de serviço de transporte iniciada em unidade da Federação diversa daquela onde inscrito o prestador (CT-e Substituto)",                                                                                  "Prest. serv. transporte (ICMS)",    "5932",         "6932",         "7949",     "5932",         "6932",         "5932",                 "6932" },;
		{"776", "Prestação de serviço de transporte para execução de serviço da mesma natureza",                                                                                                                                    "Prest. serv. transporte (ICMS)",    "5351",         "6351",         "7949",     "5351",         "6351",         "5351",                 "6351" },;
		{"697", "Prestação de serviço de transporte realizado por transportador autônomo ou por transportador não inscrito na unidade da Federação onde iniciado o serviço na hipótese de aplicação da substituição tributária",    "Prest. serv. transporte (ICMS)",    "5931",         "6931",         "7949",     "5931",         "6931",         "5931",                 "6931" },;
		{"568", "Venda de mercadoria adquirida de terceiros para utilização no serviço de transporte público ferroviário de passageiros",                                                                                           "Venda",                             "5102",         "6102",         "7102",     "5405",         "6404",         "5403",                 "6403" },;
		{"264", "Venda de mercadoria de produção própria para utilização no serviço de transporte público ferroviário de passageiros",                                                                                              "Venda",                             "5101",         "6101",         "7101",     "5101",         "6101",         "5101",                 "6101" } }

	FISImportCarga():ImportNatOper(aNatOperFin, lAutomato)

	FWFreeArray(aNatOperFin)

Return

/*/{Protheus.doc ImpEnquad
	Função responsavel pela importação da tabela de Enquadramento
	@type  Function
	@author Erich Buttner
	@since 23/11/2022
	@version version
	@param param_name, param_type, param_descr
	@return return_var, return_type, return_description
	@example
	(examples)
	@see (links_or_references)
    /*/
Function ImpEnquad()

	Local aImpEnquad := {;
		{ "1", "Indústria", "1" },;
		{ "2,786", "Atacadista, Atacadista não equiparado a indústria", "1" },;
		{ "24", "Importador", "1" },;
		{ "3", "Varejista", "1" },;
		{ "2,725,24", "Atacadista, Atacadista equiparado a indústria (Lei nº 13.097/2015 Bebidas Frias e Lei nº 7.798/1989 Perfumes e Cosméticos), Importador", "1" },;
		{ "2,725", "Atacadista, Atacadista equiparado a indústria (Lei nº 13.097/2015 Bebidas Frias e Lei nº 7.798/1989 Perfumes e Cosméticos)", "1" },;
		{ "66,24,725", "Distribuidor, Importador, Atacadista equiparado a indústria (Lei nº 13.097/2015 Bebidas Frias e Lei nº 7.798/1989 Perfumes e Cosméticos)", "1" },;
		{ "2,24,725", "Atacadista, Importador, Atacadista equiparado a indústria (Lei nº 13.097/2015 Bebidas Frias e Lei nº 7.798/1989 Perfumes e Cosméticos)", "1" },;
		{ "2", "Atacadista", "1" },;
		{ "2,24", "Atacadista, Importador", "1" },;
		{ "66,24", "Distribuidor, Importador", "1" },;
		{ "24,140", "Importador, Contribuinte do ICMS", "1" },;
		{ "3,776", "Varejista, E-commerce", "1" },;
		{ "682", "Empresa estabelecida no exterior", "1" },;
		{ "66", "Distribuidor", "1" },;
		{ "6,622", "Armazém-geral, Optante pelo Simples Nacional - Regime de Competência", "1" },;
		{ "6", "Armazém-geral", "1" },;
		{ "1,370", "Indústria, Optante pelo Simples nacional - excesso sublimite receita bruta (ICMS - Apuração normal)", "1" },;
		{ "1,622", "Indústria, Optante pelo Simples Nacional - Regime de Competência", "1" },;
		{ "2,89", "Atacadista, Equiparado a industrial", "1" },;
		{ "60", "Não contribuinte ou pessoa não obrigada à emissão de documento fiscal", "1" },;
		{ "2,725,1312", "Atacadista, Atacadista equiparado a indústria (Lei nº 13.097/2015 Bebidas Frias e Lei nº 7.798/1989 Perfumes e Cosméticos), Equiparado a industrial - Países membros do GATT/OMC", "1" },;
		{ "2,89,1312", "Atacadista, Equiparado a industrial, Equiparado a industrial - Países membros do GATT/OMC", "1" },;
		{ "24,1108", "Importador, Importador - Países membros do GATT/OMC", "1" },;
		{ "2,89,795", "Atacadista, Equiparado a industrial, Atacadista (substituto tributário)", "1" },;
		{ "244", "Varejista que recebeu a mercadoria em transferência", "1" },;
		{ "2,622", "Atacadista, Optante pelo Simples Nacional - Regime de Competência", "1" },;
		{ "1,24", "Indústria, Importador", "1" },;
		{ "140", "Contribuinte do ICMS", "1" },;
		{ "7", "Depósito fechado", "1" },;
		{ "6,622,24", "Armazém-geral, Optante pelo Simples Nacional - Regime de Competência, Importador", "1" },;
		{ "6,24", "Armazém-geral, Importador", "1" },;
		{ "2,786,24", "Atacadista, Atacadista não equiparado a indústria, Importador", "1" },;
		{ "178", "Produtor rural", "1" },;
		{ "124", "Abatedor", "1" },;
		{ "1,781", "Indústria, Contribuinte de Regime Tributário Diferenciado do ICMS - Pará", "1" },;
		{ "2,1066", "Atacadista, Centro de Distribuição - Eletrônicos, eletroeletrônicos e eletrodomésticos, perfumaria, higiene pessoal e cosméticos - Decreto nº 29.482/2006 (PE)", "1" },;
		{ "2,227", "Atacadista, Distribuidor hospitalar", "1" },;
		{ "2,786,795", "Atacadista, Atacadista não equiparado a indústria, Atacadista (substituto tributário)", "1" },;
		{ "2,864", "Atacadista, Carga líquida - art. 546 a 548-J do RICMS/CE - Atacadistas - Farmacêuticos", "1" },;
		{ "24,1530", "Importador, AC 2024027", "1" },;
		{ "243", "Atacadista que recebeu a mercadoria em transferência", "1" },;
		{ "244,811", "Varejista que recebeu a mercadoria em transferência, Carga líquida - Decreto nº 29.560/2008 - Varejistas", "1" },;
		{ "3,1389", "Varejista, Substituto tributário - Protocolo SID nº 15.511.058-9 -  Art 14, do Anexo IX do RICMS/PR", "1" },;
		{ "3,24,1154", "Varejista, Importador, Varejista não equiparado a indústria", "1" },;
		{ "3,24,1544", "Varejista, Importador, AC 2024037", "1" },;
		{ "3,24", "Varejista, Importador", "1" },;
		{ "3,244", "Varejista, Varejista que recebeu a mercadoria em transferência", "1" },;
		{ "3,811", "Varejista, Carga líquida - Decreto nº 29.560/2008 - Varejistas", "1" },;
		{ "446,1064", "Atacadista/distribuidor (substituto tributário) Decreto nº 19.528/1996 (PE), Atacadista (substituto tributário) - Produtos eletrônicos, eletroeletrônicos e eletrodomésticos - Decreto nº 46.028/2018 (PE)", "1" },;
		{ "483,2", "Atacadista - Decreto Estadual nº 38.455/2012 (PE), Atacadista", "1" },;
		{ "807,1066", "Centro de Distribuição - Decreto nº 29.482/2006, Centro de Distribuição - Eletrônicos, eletroeletrônicos e eletrodomésticos, perfumaria, higiene pessoal e cosméticos - Decreto nº 29.482/2006 (PE)", "1" },;
		{ "807", "Centro de Distribuição - Decreto nº 29.482/2006", "1" },;
		{ "2,483", "Atacadista, Atacadista - Decreto Estadual nº 38.455/2012 (PE)", "1" },;
		{ "2,786,1242", "Atacadista, Atacadista não equiparado a indústria, Atacadista de medicamentos e drogas de uso humano	em operação com mercadorias adquiridas de outras Unidades da Federação", "1" },;
		{ "2,786,1438", "Atacadista, Atacadista não equiparado a indústria, Atacadista - Termo de Acordo - Art. 11, III do Anexo IX do RCTE (GO)", "1" },;
		{ "2,786,314", "Atacadista, Atacadista não equiparado a indústria, Distribuidor de produtos farmacêuticos", "1" },;
		{ "2,786,1066", "Atacadista, Atacadista não equiparado a indústria, Centro de Distribuição - Eletrônicos, eletroeletrônicos e eletrodomésticos, perfumaria, higiene pessoal e cosméticos - Decreto nº 29.482/2006 (PE)", "1" },;
		{ "2,786,243", "Atacadista, Atacadista não equiparado a indústria, Atacadista que recebeu a mercadoria em transferência", "1" },;
		{ "2,786,804", "Atacadista, Atacadista não equiparado a indústria, Atacadista de produtos farmacêuticos", "1" },;
		{ "2,786,860", "Atacadista, Atacadista não equiparado a indústria, Central de distribuição de farmácias ou drogarias", "1" },;
		{ "2,786,986", "Atacadista, Atacadista não equiparado a indústria, Comércio de Medicamentos e Produtos Farmacêuticos credenciados nos termos da Portaria SF nº 130/2010 - Decreto nº 28.247/2005 (PE) - MVA 22,94%", "1" },;
		{ "2,786,808", "Atacadista, Atacadista não equiparado a indústria, Carga líquida - Decreto nº 29.560/2008 - Atacadistas", "1" },;
		{ "78,2,786", "Distribuidor de combustível, Atacadista, Atacadista não equiparado a indústria", "1" },;
		{ "1,777", "Indústria, Indústria incentiva pela Lei nº 2.826/2003", "1" },;
		{ "124,932,968", "Abatedor, Estabelecimento sujeito ao sistema opcional de redução de base de cálculo, Industria sujeita ao sistema opcional de redução de base de cálculo", "1" },;
		{ "1,888", "Indústria, Industria que produz até 5.000.000 em litros de cervejas e chopes especiais, considerando a produção acumulada no ano-calendário anterior - Lei nº 13.097/2015", "1" },;
		{ "1,1108", "Indústria, Importador - Países membros do GATT/OMC", "1" },;
		{ "1,438,154", "Indústria, Indústria (CNAEs 1071-6/00, 1072-4/01 ou 1931-4/00), Indústria e importador optante pelo RECOB", "1" },;
		{ "1,438", "Indústria, Indústria (CNAEs 1071-6/00, 1072-4/01 ou 1931-4/00)", "1" },;
		{ "1,154,438", "Indústria, Indústria e importador optante pelo RECOB, Indústria (CNAEs 1071-6/00, 1072-4/01 ou 1931-4/00)", "1" },;
		{ "1,442", "Indústria, Contribuinte credenciado como substituto tributário no Estado de destino (MT)", "1" },;
		{ "1,622,1383", "Indústria, Optante pelo Simples Nacional - Regime de Competência, Contribuinte que dê saída de bem intermediário incentivado - Lei nº 3.182/2007 (AM)", "1" },;
		{ "1,1120", "Indústria, Contribuinte beneficiário do Decreto AM nº 33.084/2013", "1" },;
		{ "1,1383", "Indústria, Contribuinte que dê saída de bem intermediário incentivado - Lei nº 3.182/2007 (AM)", "1" },;
		{ "1,777,622", "Indústria, Indústria incentiva pela Lei nº 2.826/2003, Optante pelo Simples Nacional - Regime de Competência", "1" },;
		{ "102", "Refinaria de petróleo", "1" },;
		{ "480", "Destilaria/Usina de álcool", "1" },;
		{ "90", "Produtor rural (Pessoa física)", "1" },;
		{ "1,623", "Indústria, Optante pelo Simples Nacional - Regime de Caixa", "1" },;
		{ "1,2587", "Indústria, Indústria incentivada pela Lei nº 2.826/2003 (Art. 18 do Decreto nº 23.994/2003)", "1" },;
		{ "1,134", "Indústria, Regime Cumulativo", "1" },;
		{ "71", "Cooperativa rural", "1" },;
		{ "1,1114", "Indústria, Atacadista - CNAE secundário (Com CNAE principal  1020-1) - Art. 391 do RICMS/SP", "1" },;
		{ "1,1226", "Indústria, Contribuinte em situação irregular perante o Fisco", "1" },;
		{ "1,1286", "Indústria, Estabelecimento industrial optante pelo crédito presumido nas saídas de peixes, crustáceos e moluscos (Livro I, art. 32, LXXXI do RICMS/RS)", "1" },;
		{ "1,1437", "Indústria, Estabelecimento Fornecedor de arroz - operações interestaduais (condições específicas do Livro I, art. 23, LXXXVII, Nota 2 do RICMS/RS)", "1" },;
		{ "1,1468", "Indústria, Estabelecimento Produtor sujeito ao sistema opcional de crédito presumido", "1" },;
		{ "1,1530", "Indústria, AC 2024027", "1" },;
		{ "1,485", "Indústria, Indústria de produto de informática e automação, que esteja beneficiada com redução do IPI e que atenda ao disposto no artigo 4º, da Lei Federal nº 8.248/91 (Processo Produtivo Básico - PPB)", "1" },;
		{ "1,784", "Indústria, Indústria que não possui instalação de equipamentos contadores de produção - Decreto nº 8.442/2015", "1" },;
		{ "1,809", "Indústria, Carga líquida - Decreto nº 31.066/2012 - Fabricantes - Produtos de Informática", "1" },;
		{ "1,889", "Indústria, Industria que produz acima de 5.000.000 até 10.000.000 em litros de cervejas e chopes especiais, considerando a produção acumulada no ano-calendário anterior - Lei nº 13.097/2015", "1" },;
		{ "1,897", "Indústria, Industria do Decreto nº 43.771/2012", "1" },;
		{ "1,944", "Indústria, Estabelecimento Fornecedor de arroz - operações interestaduais (condições específicas do Livro I, art. 23, LXXVI, Nota 2 do RICMS/RS)", "1" },;
		{ "1,994", "Indústria, Indústria sujeita ao sistema opcional de crédito presumido", "1" },;
		{ "124,622", "Abatedor, Optante pelo Simples Nacional - Regime de Competência", "1" },;
		{ "178,622", "Produtor rural, Optante pelo Simples Nacional - Regime de Competência", "1" },;
		{ "276", "Frigorífico", "1" },;
		{ "320", "Estabelecimento de cooperativa de produtor rural", "1" },;
		{ "1,823", "Indústria, Filial atacadista equiparado a Industrial", "1" },;
		{ "1,154", "Indústria, Indústria e importador optante pelo RECOB", "1" },;
		{ "2,786,1407", "Atacadista, Atacadista não equiparado a indústria, Atacadista - Termo de Acordo - Art. 11, XXIII do Anexo IX do RCTE (GO)", "1" },;
		{ "2,786,227", "Atacadista, Atacadista não equiparado a indústria, Distribuidor hospitalar", "1" },;
		{ "2,786,755", "Atacadista, Atacadista não equiparado a indústria, Atacadista de medicamentos e drogas de uso humano", "1" },;
		{ "2,89,243", "Atacadista, Equiparado a industrial, Atacadista que recebeu a mercadoria em transferência", "1" },;
		{ "3,622", "Varejista, Optante pelo Simples Nacional - Regime de Competência", "1" },;
		{ "2,24,622", "Atacadista, Importador, Optante pelo Simples Nacional - Regime de Competência", "1" },;
		{ "2,725,243", "Atacadista, Atacadista equiparado a indústria (Lei nº 13.097/2015 Bebidas Frias e Lei nº 7.798/1989 Perfumes e Cosméticos), Atacadista que recebeu a mercadoria em transferência", "1" },;
		{ "24,134", "Importador, Regime Cumulativo", "1" },;
		{ "3,1154", "Varejista, Varejista não equiparado a indústria", "1" },;
		{ "3,623", "Varejista, Optante pelo Simples Nacional - Regime de Caixa", "1" },;
		{ "3,762", "Varejista, Varejista de mercadorias em geral, com predominância de produtos alimentícios - supermercados (CNAE 4711-3/02)", "1" },;
		{ "3,942", "Varejista, Comércio varejista de carnes - Açougues 4722-9/01", "1" },;
		{ "66,725", "Distribuidor, Atacadista equiparado a indústria (Lei nº 13.097/2015 Bebidas Frias e Lei nº 7.798/1989 Perfumes e Cosméticos)", "1" },;
		{ "66,786", "Distribuidor, Atacadista não equiparado a indústria", "1" },;
		{ "77", "Comércio (autor da encomenda)", "1" },;
		{ "776,3", "E-commerce, Varejista", "1" },;
		{ "2,149,725", "Atacadista, Regimes especiais - solicitações administrativas (com opção), Atacadista equiparado a indústria (Lei nº 13.097/2015 Bebidas Frias e Lei nº 7.798/1989 Perfumes e Cosméticos)", "1" },;
		{ "2,24,786", "Atacadista, Importador, Atacadista não equiparado a indústria", "1" },;
		{ "2,725,370", "Atacadista, Atacadista equiparado a indústria (Lei nº 13.097/2015 Bebidas Frias e Lei nº 7.798/1989 Perfumes e Cosméticos), Optante pelo Simples nacional - excesso sublimite receita bruta (ICMS - Apuração normal)", "1" },;
		{ "2,725,483", "Atacadista, Atacadista equiparado a indústria (Lei nº 13.097/2015 Bebidas Frias e Lei nº 7.798/1989 Perfumes e Cosméticos), Atacadista - Decreto Estadual nº 38.455/2012 (PE)", "1" },;
		{ "2,786,1481", "Atacadista, Atacadista não equiparado a indústria, Atacadista beneficiário de crédito presumido - Art. 7º do Anexo XVII do RICMS/MT", "1" },;
		{ "2,89,24", "Atacadista, Equiparado a industrial, Importador", "1" },;
		{ "3,1126", "Varejista, Varejista - Vendas exclusivamente por meio da Internet ou de telemarketing", "1" },;
		{ "3,1530", "Varejista, AC 2024027", "1" },;
		{ "3,620", "Varejista, Microempreendedor individual (MEI)", "1" },;
		{ "3,622,776", "Varejista, Optante pelo Simples Nacional - Regime de Competência, E-commerce", "1" },;
		{ "3,776,622", "Varejista, E-commerce, Optante pelo Simples Nacional - Regime de Competência", "1" },;
		{ "3,859", "Varejista, Varejista com atividade principal de farmácia e/ou drogaria, que também comercialize outras mercadorias", "1" },;
		{ "3,865", "Varejista, Carga líquida - art. 546 a 548-J do RICMS/CE - Varejistas - Farmacêuticos", "1" },;
		{ "66,725,24", "Distribuidor, Atacadista equiparado a indústria (Lei nº 13.097/2015 Bebidas Frias e Lei nº 7.798/1989 Perfumes e Cosméticos), Importador", "1" },;
		{ "761", "Varejista de mercadorias em geral, com predominância de produtos alimentícios - hipermercados (CNAE 4711-3/01)", "1" },;
		{ "776,2,725", "E-commerce, Atacadista, Atacadista equiparado a indústria (Lei nº 13.097/2015 Bebidas Frias e Lei nº 7.798/1989 Perfumes e Cosméticos)", "1" },;
		{ "776", "E-commerce", "1" },;
		{ "2,24,89", "Atacadista, Importador, Equiparado a industrial", "1" },;
		{ "3,779", "Varejista, Varejista que recebe produto de empresa incentivada pela Lei nº 2.826/2003", "1" },;
		{ "2,149,786", "Atacadista, Regimes especiais - solicitações administrativas (com opção), Atacadista não equiparado a indústria", "1" },;
		{ "2,243", "Atacadista, Atacadista que recebeu a mercadoria em transferência", "1" },;
		{ "2,370", "Atacadista, Optante pelo Simples nacional - excesso sublimite receita bruta (ICMS - Apuração normal)", "1" },;
		{ "2,795", "Atacadista, Atacadista (substituto tributário)", "1" },;
		{ "3,24,622", "Varejista, Importador, Optante pelo Simples Nacional - Regime de Competência", "1" },;
		{ "2,1312", "Atacadista, Equiparado a industrial - Países membros do GATT/OMC", "1" },;
		{ "2,1224", "Atacadista, Atacadista - Lei nº 9.025/2020 - RIOLOG (RJ)", "1" },;
		{ "2,1226", "Atacadista, Contribuinte em situação irregular perante o Fisco", "1" },;
		{ "2,149", "Atacadista, Regimes especiais - solicitações administrativas (com opção)", "1" },;
		{ "2,217", "Atacadista, Atacadista - Decreto nº 36.453/2004 - RIOLOG (RJ)", "1" },;
		{ "2,657", "Atacadista, Atacadista - Decreto nº 44.498/2013 RIOLOG (RJ)", "1" },;
		{ "2,786,1226", "Atacadista, Atacadista não equiparado a indústria, Contribuinte em situação irregular perante o Fisco", "1" },;
		{ "2,786,1395", "Atacadista, Atacadista não equiparado a indústria, Atacadista de papel localizado em outro Estado (para não aplicar a redução da BC específica do DF)", "1" },;
		{ "2,795,786", "Atacadista, Atacadista (substituto tributário), Atacadista não equiparado a indústria", "1" },;
		{ "2,808", "Atacadista, Carga líquida - Decreto nº 29.560/2008 - Atacadistas", "1" },;
		{ "24,1217", "Importador, Importador atacadista", "1" },;
		{ "314", "Distribuidor de produtos farmacêuticos", "1" },;
		{ "804", "Atacadista de produtos farmacêuticos", "1" },;
		{ "795", "Atacadista (substituto tributário)", "1" },;
		{ "2,795,1026,1147", "Atacadista, Atacadista (substituto tributário), Estabelecimento fabricante substituto tributário em relação a mesma mercadoria ou a outra mercadoria enquadrada na mesma modalidade de substituição, Indústria - Revenda de mercadorias", "1" },;
		{ "2,786,1537", "Atacadista, Atacadista não equiparado a indústria, AC 2024032", "1" },;
		{ "2,243,786", "Atacadista, Atacadista que recebeu a mercadoria em transferência, Atacadista não equiparado a indústria", "1" },;
		{ "2,622,786,1224", "Atacadista, Optante pelo Simples Nacional - Regime de Competência, Atacadista não equiparado a indústria, Atacadista - Lei nº 9.025/2020 - RIOLOG (RJ)", "1" },;
		{ "2,622,786", "Atacadista, Optante pelo Simples Nacional - Regime de Competência, Atacadista não equiparado a indústria", "1" },;
		{ "2,786,1224", "Atacadista, Atacadista não equiparado a indústria, Atacadista - Lei nº 9.025/2020 - RIOLOG (RJ)", "1" },;
		{ "2,786,622", "Atacadista, Atacadista não equiparado a indústria, Optante pelo Simples Nacional - Regime de Competência", "1" },;
		{ "2,89,1224", "Atacadista, Equiparado a industrial, Atacadista - Lei nº 9.025/2020 - RIOLOG (RJ)", "1" },;
		{ "2,89,622,1224", "Atacadista, Equiparado a industrial, Optante pelo Simples Nacional - Regime de Competência, Atacadista - Lei nº 9.025/2020 - RIOLOG (RJ)", "1" },;
		{ "2,89,622", "Atacadista, Equiparado a industrial, Optante pelo Simples Nacional - Regime de Competência", "1" },;
		{ "24,370", "Importador, Optante pelo Simples nacional - excesso sublimite receita bruta (ICMS - Apuração normal)", "1" },;
		{ "24,622", "Importador, Optante pelo Simples Nacional - Regime de Competência", "1" },;
		{ "2,786,1120", "Atacadista, Atacadista não equiparado a indústria, Contribuinte beneficiário do Decreto AM nº 33.084/2013", "1" },;
		{ "2,786,778", "Atacadista, Atacadista não equiparado a indústria, Atacadista que recebe produto de empresa incentivada pela Lei nº 2.826/2003", "1" },;
		{ "24,1120", "Importador, Contribuinte beneficiário do Decreto AM nº 33.084/2013", "1" },;
		{ "263", "Pessoa jurídica", "1" },;
		{ "278", "Pessoa física", "1" },;
		{ "2,89,778", "Atacadista, Equiparado a industrial, Atacadista que recebe produto de empresa incentivada pela Lei nº 2.826/2003", "1" },;
		{ "2,622,89", "Atacadista, Optante pelo Simples Nacional - Regime de Competência, Equiparado a industrial", "1" },;
		{ "2,786,134", "Atacadista, Atacadista não equiparado a indústria, Regime Cumulativo", "1" },;
		{ "24,1463", "Importador, Importador habilitado no Programa Rota 2030 - Decreto nº 9.557/2018 - NC (87-9)", "1" },;
		{ "3,134", "Varejista, Regime Cumulativo", "1" },;
		{ "2,725,795", "Atacadista, Atacadista equiparado a indústria (Lei nº 13.097/2015 Bebidas Frias e Lei nº 7.798/1989 Perfumes e Cosméticos), Atacadista (substituto tributário)", "1" },;
		{ "24,909", "Importador, Estabelecimento credenciado no Programa de Estímulo à Atividade Portuária II - (PE)", "1" },;
		{ "2,153", "Atacadista, Distribuidor optante pelo RECOB", "1" },;
		{ "2,243,657", "Atacadista, Atacadista que recebeu a mercadoria em transferência, Atacadista - Decreto nº 44.498/2013 RIOLOG (RJ)", "1" },;
		{ "2,243,823", "Atacadista, Atacadista que recebeu a mercadoria em transferência, Filial atacadista equiparado a Industrial", "1" },;
		{ "2,243,89", "Atacadista, Atacadista que recebeu a mercadoria em transferência, Equiparado a industrial", "1" },;
		{ "2,747", "Atacadista, Atacadista de produtos alimentícios em geral (CNAE 4639-7/01)", "1" },;
		{ "2,78,243", "Atacadista, Distribuidor de combustível, Atacadista que recebeu a mercadoria em transferência", "1" },;
		{ "2,78,786", "Atacadista, Distribuidor de combustível, Atacadista não equiparado a indústria", "1" },;
		{ "2,786,1079", "Atacadista, Atacadista não equiparado a indústria, Atacadista (substituto tributário) - Produtos de perfumaria e de higiene pessoal e cosméticos- Decreto nº 46.303/2018 (PE)", "1" },;
		{ "2,786,1114", "Atacadista, Atacadista não equiparado a indústria, Atacadista - CNAE secundário (Com CNAE principal  1020-1) - Art. 391 do RICMS/SP", "1" },;
		{ "2,786,1237", "Atacadista, Atacadista não equiparado a indústria, Entidade beneficente de assistência social com a finalidade de prestação de serviços nas áreas de assistência social, saúde ou educação", "1" },;
		{ "2,786,1402", "Atacadista, Atacadista não equiparado a indústria, Centro de distribuição - Decreto nº 45.631/2016 (RJ)", "1" },;
		{ "2,786,987", "Atacadista, Atacadista não equiparado a indústria, Comércio de Medicamentos e Produtos Farmacêuticos credenciados nos termos da Portaria SF nº 130/2010 - Decreto nº 28.247/2005 (PE) - MVA 17,65%", "1" },;
		{ "2,795,1237,991", "Atacadista, Atacadista (substituto tributário), Entidade beneficente de assistência social com a finalidade de prestação de serviços nas áreas de assistência social, saúde ou educação, Estabelecimento sujeito ao sistema opcional de crédito presumido", "1" },;
		{ "2,806", "Atacadista, Atacadista equiparado a Industria que não possui instalação de equipamentos contadores de produção - Decreto nº 8.442/2015", "1" },;
		{ "2,812", "Atacadista, Carga líquida - Decreto nº 31.066/2012 - Atacadistas - Produtos de Informática", "1" },;
		{ "2,823", "Atacadista, Filial atacadista equiparado a Industrial", "1" },;
		{ "2,888", "Atacadista, Industria que produz até 5.000.000 em litros de cervejas e chopes especiais, considerando a produção acumulada no ano-calendário anterior - Lei nº 13.097/2015", "1" },;
		{ "2,89,243,345", "Atacadista, Equiparado a industrial, Atacadista que recebeu a mercadoria em transferência, Estabelecimento distribuidor da mesma titularidade", "1" },;
		{ "2,934", "Atacadista, Contribuinte Credenciado nos termos do Decreto nº 7.799/2000 (BA)", "1" },;
		{ "24,1114", "Importador, Atacadista - CNAE secundário (Com CNAE principal  1020-1) - Art. 391 do RICMS/SP", "1" },;
		{ "24,1515", "Importador, Importador - mercadorias importadas ao abrigo do diferimento previsto no art. 53, VI, Livro I do RICMS/RS", "1" },;
		{ "24,623", "Importador, Optante pelo Simples Nacional - Regime de Caixa", "1" },;
		{ "24,784", "Importador, Indústria que não possui instalação de equipamentos contadores de produção - Decreto nº 8.442/2015", "1" },;
		{ "243,345,786", "Atacadista que recebeu a mercadoria em transferência, Estabelecimento distribuidor da mesma titularidade, Atacadista não equiparado a indústria", "1" },;
		{ "657,2", "Atacadista - Decreto nº 44.498/2013 RIOLOG (RJ), Atacadista", "1" },;
		{ "66,622", "Distribuidor, Optante pelo Simples Nacional - Regime de Competência", "1" },;
		{ "663", "Importador - Decreto nº 44.498/2013 RIOLOG (RJ)", "1" },;
		{ "986", "Comércio de Medicamentos e Produtos Farmacêuticos credenciados nos termos da Portaria SF nº 130/2010 - Decreto nº 28.247/2005 (PE) - MVA 22,94%", "1" },;
		{ "987", "Comércio de Medicamentos e Produtos Farmacêuticos credenciados nos termos da Portaria SF nº 130/2010 - Decreto nº 28.247/2005 (PE) - MVA 17,65%", "1" },;
		{ "3,349", "Varejista, Estabelecimento interdependente", "1" },;
		{ "2,786,864", "Atacadista, Atacadista não equiparado a indústria, Carga líquida - art. 546 a 548-J do RICMS/CE - Atacadistas - Farmacêuticos", "1" },;
		{ "2,622,808", "Atacadista, Optante pelo Simples Nacional - Regime de Competência, Carga líquida - Decreto nº 29.560/2008 - Atacadistas", "1" },;
		{ "2,89,808", "Atacadista, Equiparado a industrial, Carga líquida - Decreto nº 29.560/2008 - Atacadistas", "1" },;
		{ "757", "Atacadista de mercadorias em geral, com predominância de produtos alimentícios (CNAE 4691-5/00)", "1" },;
		{ "2,786,1530", "Atacadista, Atacadista não equiparado a indústria, AC 2024027", "1" },;
		{ "1,777,24", "Indústria, Indústria incentiva pela Lei nº 2.826/2003, Importador", "1" },;
		{ "2,1093", "Atacadista, Contribuinte que realiza venda fora do estabelecimento", "1" },;
		{ "3,550", "Varejista, Empresa de transporte aéreo de carga e passageiro", "1" },;
		{ "1,622,24", "Indústria, Optante pelo Simples Nacional - Regime de Competência, Importador", "1" },;
		{ "2,622,24", "Atacadista, Optante pelo Simples Nacional - Regime de Competência, Importador", "1" },;
		{ "24,66,725", "Importador, Distribuidor, Atacadista equiparado a indústria (Lei nº 13.097/2015 Bebidas Frias e Lei nº 7.798/1989 Perfumes e Cosméticos)", "1" },;
		;
		{ "2070", "Empresa estabelecida no exterior", "2" },;
		{ "7", "Armazém-geral", "2" },;
		{ "3", "Consumidor final contribuinte do ICMS", "2" },;
		{ "6", "Consumidor final não contribuinte do ICMS", "2" },;
		{ "138", "Atacadista", "2" },;
		{ "213", "Hospitais, clínicas e congêneres", "2" },;
		{ "232", "Distribuidor", "2" },;
		{ "140", "Varejista", "2" },;
		{ "54", "Importador", "2" },;
		{ "1,54", "Indústria, Importador", "2" },;
		{ "3,54", "Consumidor final contribuinte do ICMS, Importador", "2" },;
		{ "54,3", "Importador, Consumidor final contribuinte do ICMS", "2" },;
		{ "52", "Qualquer estabelecimento para armazenamento da mercadoria (exceto armazém-geral ou depósito fechado)", "2" },;
		{ "1", "Indústria", "2" },;
		{ "140,2420", "Varejista, Varejista - Vendas exclusivamente por meio da Internet ou de telemarketing", "2" },;
		{ "2,24,54", "Comércio, Armazém alfandegado, Importador", "2" },;
		{ "187", "Produtor rural", "2" },;
		{ "1,499", "Indústria, Optante pelo Simples Nacional", "2" },;
		{ "528", "Entidade beneficente ou de assistência social portadoras do Certificado de Entidade de Fins Filantrópicos", "2" },;
		{ "543", "Administração pública", "2" },;
		{ "585", "Entidade governamental", "2" },;
		{ "908", "Entidade governamental de assistência a vítimas de calamidade pública", "2" },;
		{ "3,4", "Consumidor final contribuinte do ICMS, Regime não-cumulativo (PIS/COFINS)", "2" },;
		{ "3,2622", "Consumidor final contribuinte do ICMS, Empresa da ZFM e ALC não cadastrados na Suframa", "2" },;
		{ "6,2622", "Consumidor final não contribuinte do ICMS, Empresa da ZFM e ALC não cadastrados na Suframa", "2" },;
		{ "138,1487", "Atacadista, Contribuinte (substituto tributário nas saídas que promover) - regime especial", "2" },;
		{ "138,54", "Atacadista, Importador", "2" },;
		{ "822", "Produtor agropecuário (neste compreendidas as atividades de pecuária, a apicultura, a aqüicultura, a avicultura, a cunicultura, a ranicultura e a sericicultura)", "2" },;
		{ "29", "Contribuinte do ICMS", "2" },;
		{ "54,138", "Importador, Atacadista", "2" },;
		{ "1,9", "Indústria, Depositante", "2" },;
		{ "138,1701", "Atacadista, Equiparado a industrial", "2" },;
		{ "8", "Depósito fechado", "2" },;
		{ "23", "Comercial exportadora (inclusive trading)", "2" },;
		{ "579", "Filial, exceto varejista", "2" },;
		{ "1626", "Filial (indústria) que receber mercadorias em transferência de estabelecimento industrial", "2" },;
		{ "1626,1489", "Filial (indústria) que receber mercadorias em transferência de estabelecimento industrial, Indústria para emprego em processo de industrialização como matéria-prima, produto intermediário ou material de embalagem (mercadorias sujeitas à substituição tributária e utilizadas como insumo pelo destinatário)", "2" },;
		{ "1626,2587,1489", "Filial (indústria) que receber mercadorias em transferência de estabelecimento industrial, Indústria incentivada pela Lei nº 2.826/2003 (Art. 18 do Decreto nº 23.994/2003), Indústria para emprego em processo de industrialização como matéria-prima, produto intermediário ou material de embalagem (mercadorias sujeitas à substituição tributária e utilizadas como insumo pelo destinatário)", "2" },;
		{ "578", "Filial varejista", "2" },;
		{ "1159", "Filial Atacadista", "2" },;
		{ "1521", "Filial, exceto varejista, que receber mercadorias em transferência de estabelecimento industrial", "2" },;
		{ "1159,1638", "Filial Atacadista, Atacadista (substituto tributário)", "2" },;
		{ "1159,1701", "Filial Atacadista, Equiparado a industrial", "2" },;
		{ "232,579", "Distribuidor, Filial, exceto varejista", "2" },;
		{ "1614", "Filial, exceto varejista, que receber mercadorias em transferência de estabelecimento importador", "2" },;
		{ "1,1614", "Indústria, Filial, exceto varejista, que receber mercadorias em transferência de estabelecimento importador", "2" },;
		{ "968", "Estabelecimento do mesmo titular", "2" },;
		{ "1640", "Filial varejista optante pelo Simples Nacional", "2" },;
		{ "2217", "Filial varejista com atividade principal de farmácia/drogaria e atividade secundária de comercialização de outras mercadorias", "2" },;
		{ "54,1159", "Importador, Filial Atacadista", "2" },;
		{ "578,499", "Filial varejista, Optante pelo Simples Nacional", "2" },;
		{ "579,499", "Filial, exceto varejista, Optante pelo Simples Nacional", "2" },;
		{ "1159,138", "Filial Atacadista, Atacadista", "2" },;
		{ "1159,812", "Filial Atacadista, Distribuidor hospitalar", "2" },;
		{ "140,205", "Varejista, Exportadora dos serviços relacionados na forma do art. 1º do Dec. Lei 1.633/ 1978", "2" },;
		{ "578,1095", "Filial varejista, Centro de Distribuição (substituto tributário) - Decreto nº 57.608/2011 (SP)", "2" },;
		{ "578,1096", "Filial varejista, Filial varejista do centro de distribuição - Decreto nº 57.608/2011 (SP)", "2" },;
		{ "578,1487", "Filial varejista, Contribuinte (substituto tributário nas saídas que promover) - regime especial", "2" },;
		{ "578,1599", "Filial varejista, Varejista com atividade principal de farmácia e/ou drogaria, que também comercialize outras mercadorias", "2" },;
		{ "578,1643", "Filial varejista, Filial varejista enquadrada no Regime de Estimativa Simplificado (MT)", "2" },;
		{ "578,2076", "Filial varejista, Estabelecimento com controle acionário da mesma pessoa jurídica do Centro de Distribuição - Decreto nº 29.482/2006", "2" },;
		{ "578,2077", "Filial varejista, Centro de Distribuição - Decreto nº 29.482/2006 (PE)", "2" },;
		{ "578,2083", "Filial varejista, Carga líquida - Decreto nº 31.066/2012 - Varejistas - Produtos de Informática", "2" },;
		{ "578,217", "Filial varejista, Empresa enquadrada na Lei nº 25.665/ 1999 (RJ) - Pólo Gás Químico", "2" },;
		{ "578,2335", "Filial varejista, Filial do Carga líquida - Decreto n° 29.560/2008 - Varejista (CE)", "2" },;
		{ "578,2346", "Filial varejista, Varejista de mercadorias em geral, com predominância de produtos alimentícios - supermercados", "2" },;
		{ "579,1487", "Filial, exceto varejista, Contribuinte (substituto tributário nas saídas que promover) - regime especial", "2" },;
		{ "579,1521", "Filial, exceto varejista, Filial, exceto varejista, que receber mercadorias em transferência de estabelecimento industrial", "2" },;
		{ "579,1526", "Filial, exceto varejista, Atacadista (substituto tributário) para Medicamentos e Produtos Farmacêuticos - Decretos nº 28.247/2005 e nº 19.528/1996 (PE)", "2" },;
		{ "579,1571", "Filial, exceto varejista, Estabelecimento substituto que seja fabricante da mesma mercadoria", "2" },;
		{ "579,1701", "Filial, exceto varejista, Equiparado a industrial", "2" },;
		{ "1159,1097", "Filial Atacadista, Filial Atacadista do centro de distribuição optante pelo Decreto nº 57.608/2011 (SP)", "2" },;
		{ "1159,1222", "Filial Atacadista, Atacadista de medicamentos e drogas de uso humano (CNAE 4644301)", "2" },;
		{ "1159,1487", "Filial Atacadista, Contribuinte (substituto tributário nas saídas que promover) - regime especial", "2" },;
		{ "1159,255", "Filial Atacadista, Transporte de passageiros por ônibus urbano e no do sistema hidroviário (aquaviário)", "2" },;
		{ "1159,2756", "Filial Atacadista, Atacadista - Termo de Acordo - Art. 11, III do Anexo IX do RCTE (GO)", "2" },;
		{ "138,1159", "Atacadista, Filial Atacadista", "2" },;
		{ "578,2217", "Filial varejista, Filial varejista com atividade principal de farmácia/drogaria e atividade secundária de comercialização de outras mercadorias", "2" },;
		{ "138,1159,1487,1501,2531", "Filial varejista, Filial varejista com atividade principal de farmácia/drogaria e atividade secundária de comercialização de outras mercadorias", "2" },;
		{ "156,1159", "Atacadista, Filial Atacadista, Contribuinte (substituto tributário nas saídas que promover) - regime especial, Contribuinte substituto da mesma mercadoria, Atacadista - Lei nº 9.025/2020 - RIOLOG (RJ)", "2" },;
		{ "140,1095", "Filial, exceto varejista", "2" },;
		{ "6,773", "Filial Atacadista", "2" },;
		{ "1487", "Filial, exceto varejista, que receber mercadorias em transferência de estabelecimento importador", "2" },;
		{ "155", "Distribuidor de combustível, Filial Atacadista", "2" },;
		{ "1,155", "Varejista, Centro de Distribuição (substituto tributário) - Decreto nº 57.608/2011 (SP)", "2" },;
		{ "809", "Consumidor final não contribuinte do ICMS, Clínica ou hospital", "2" },;
		{ "1610", "Contribuinte (substituto tributário nas saídas que promover) - regime especial", "2" },;
		{ "1,379", "Autor da encomenda", "2" },;
		{ "773,6", "Indústria, Autor da encomenda", "2" },;
		{ "138,4", "Administração Pública Direta Estadual", "2" },;
		{ "138,499", "Produtor rural pessoa física", "2" },;
		{ "138,812", "Empresa estabelecida no exterior", "2" },;
		{ "140,400", "Indústria, Estabelecimento que se dedique, preponderantemente, à elaboração de produtos classificados nos Capítulos 2 a 4, 7 a 12, 15 a 20, 23 (exceto códigos 2309.10.00 e 2309.90.30 e Ex 01 do código 2309.90.90), 28 a 31 e 64, no código 2209.00.00 e 2501.00, e nas posições 21.01 a 2105.00 da Tipi,  inclusive aqueles a que corresponde a notação NT (não-tributados)", "2" },;
		{ "140,499", "Clínica ou hospital, Consumidor final não contribuinte do ICMS", "2" },;
		{ "138,1115", "Atacadista, Regime não-cumulativo (PIS/COFINS)", "2" },;
		{ "138,114", "Atacadista, Optante pelo Simples Nacional", "2" },;
		{ "138,1548", "Atacadista, Distribuidor hospitalar", "2" },;
		{ "138,1641", "Varejista, Regime não-cumulativo (PIS/COFINS)", "2" },;
		{ "138,1984", "Varejista, Optante pelo Simples Nacional", "2" },;
		{ "138,1985", "Atacadista, Atacadista e varejista no regime não-cumulativo", "2" },;
		{ "138,2524", "Atacadista, Indústria de aeronave", "2" },;
		{ "138,2622", "Atacadista, Distribuidor de produtos farmacêuticos", "2" },;
		{ "138,263", "Atacadista, Atacadista enquadrado no Regime de Estimativa Simplificado (MT)", "2" },;
		{ "138,265", "Atacadista, Estabelecimento interdependente - aquele que por si, seus sócios ou acionistas, seja titular de pelo menos 50% do capital do outro", "2" },;
		{ "138,266", "Atacadista, Atacadista interdependente", "2" },;
		{ "138,267", "Atacadista, Reciclagem", "2" },;
		{ "138,268", "Atacadista, Empresa da ZFM e ALC não cadastrados na Suframa", "2" },;
		{ "138,269", "Atacadista, Indústria do setor de fabricação de linhas para costurar e bordar, CNAE 1314-6/00", "2" },;
		{ "138,27", "Atacadista, Indústria de artefatos de tapeçaria", "2" },;
		{ "138,271", "Atacadista, Indústria de artefatos de cordoaria, CNAE 1353-7/00", "2" },;
		{ "138,272", "Atacadista, Indústria do setor de fabricação de tecidos especiais, inclusive artefatos, CNAE 1354-5/00", "2" },;
		{ "138,286", "Atacadista, Indústria do setor de fabricação de outros produtos têxcteis não especificados anteriormente, CNAE 1359-6/00", "2" },;
		{ "140,1115", "Atacadista, Indústria do setor de confecção de roupas íntimas, CNAE 1411-8/01", "2" },;
		{ "140,114", "Atacadista, Aeronave de bandeira estrangeira aportada no país", "2" },;
		{ "140,1642", "Atacadista, Indústria do setor de confecção de peças do vestuário, exceto roupas íntimas e as confeccionadas sob medida, CNAE 1412-6/01", "2" },;
		{ "140,2622", "Atacadista, Indústria do setor de confecção, sob medida, de peças do vestuário, exceto roupas íntimas, CNAE 1412-6/02", "2" },;
		{ "140,263", "Atacadista, Indústria do setor de fabricação de embalagens de papel, CNAE 1731-1/00", "2" },;
		{ "140,264", "Varejista, Atacadista e varejista no regime não-cumulativo", "2" },;
		{ "1985,1701", "Varejista, Indústria de aeronave", "2" },;
		{ "557,548,555", "Varejista, Varejista enquadrado no Regime de Estimativa Simplificado (MT)", "2" },;
		{ "557,548,555", "Varejista, Empresa da ZFM e ALC não cadastrados na Suframa", "2" },;
		{ "138,400,1487", "Varejista, Indústria do setor de fabricação de linhas para costurar e bordar, CNAE 1314-6/00", "2" },;
		{ "138,499,2622", "Varejista, Indústria do setor de fabricação de artefatos têxteis para uso doméstico. CNAE 1351-1/00", "2" },;
		{ "140,499,2622", "Atacadista interdependente, Equiparado a industrial", "2" },;
		{ "3,2574", "Administração Pública Direta, Administração Pública Indireta, Fundação pública", "2" },;
		{ "3,2587", "Administração Pública Direta, Administração Pública Indireta, Fundação pública", "2" },;
		{ "3,2993", "Atacadista, Regime não-cumulativo (PIS/COFINS), Contribuinte (substituto tributário nas saídas que promover) - regime especial", "2" },;
		{ "156,138", "Atacadista, Optante pelo Simples Nacional, Empresa da ZFM e ALC não cadastrados na Suframa", "2" },;
		{ "613", "Varejista, Optante pelo Simples Nacional, Empresa da ZFM e ALC não cadastrados na Suframa", "2" },;
		{ "1489", "Consumidor final não contribuinte do ICMS", "2" },;
		{ "2040", "Varejista", "2" },;
		{ "1,168", "Consumidor final contribuinte do ICMS, Pessoa jurídica optante pelo direito a crédito nas aquisições para uso/consumo (PIS/COFINS)", "2" },;
		{ "1,2587", "Consumidor final contribuinte do ICMS, Indústria incentivada pela Lei nº 2.826/2003 (Art. 18 do Decreto nº 23.994/2003)", "2" },;
		{ "140,2296", "Consumidor final contribuinte do ICMS, AC 2024100", "2" },;
		{ "1489,379", "Distribuidor de combustível, Atacadista", "2" },;
		{ "2588", "Distribuidor de combustível, Atacadista", "2" },;
		{ "3,408", "Produtor rural", "2" },;
		{ "3,1701,408", "Produtor rural pecuarista", "2" },;
		{ "136", "Indústria para emprego em processo de industrialização como matéria-prima, produto intermediário ou material de embalagem (mercadorias sujeitas à substituição tributária e utilizadas como insumo pelo destinatário)", "2" },;
		{ "212", "Indústria para emprego em processo de industrialização como matéria-prima, produto intermediário ou material de embalagem (mercadorias sujeitas à substituição tributária e utilizadas como insumo pelo destinatário)", "2" },;
		{ "1095", "Padaria", "2" },;
		{ "1205", "Padaria", "2" },;
		{ "1408", "Indústria, Pessoas jurídicas preponderantemente exportadoras", "2" },;
		{ "1638", "Indústria, Indústria incentivada pela Lei nº 2.826/2003 (Art. 18 do Decreto nº 23.994/2003)", "2" },;
		{ "2077", "Varejista, Restaurante (preparação de refeição)", "2" },;
		{ "138,274", "Indústria para emprego em processo de industrialização como matéria-prima, produto intermediário ou material de embalagem (mercadorias sujeitas à substituição tributária e utilizadas como insumo pelo destinatário), Estabelecimento que se dedique, preponderantemente, à elaboração de produtos classificados nos Capítulos 2 a 4, 7 a 12, 15 a 20, 23 (exceto códigos 2309.10.00 e 2309.90.30 e Ex 01 do código 2309.90.90), 28 a 31 e 64, no código 2209.00.00 e 2501.00, e nas posições 21.01 a 2105.00 da Tipi,  inclusive aqueles a que corresponde a notação NT (não-tributados)", "2" },;
		{ "232,499", "Usuário final - Indústria - Exclusivamente para fins do disposto no Art. 4º, XI, do  RICMS/AM", "2" },;
		{ "958,138", "Usuário final - Indústria - Exclusivamente para fins do disposto no Art. 4º, XI, do  RICMS/AM", "2" },;
		{ "958,140", "Consumidor final contribuinte do ICMS, Pessoa jurídica habilitada ao RECAP", "2" },;
		{ "1222,138", "Consumidor final contribuinte do ICMS, Equiparado a industrial, Pessoa jurídica habilitada ao RECAP", "2" },;
		{ "1350,138", "Consumidor final contribuinte do ICMS, Equiparado a industrial, Pessoa jurídica habilitada ao RECAP", "2" },;
		{ "138,1095", "Produtor", "2" },;
		{ "138,1265", "Central de distribuição", "2" },;
		{ "138,135", "Centro de Distribuição (substituto tributário) - Decreto nº 57.608/2011 (SP)", "2" },;
		{ "138,1526", "Atacadista (substituto tributário) -  Decreto nº 19.528/1996 (PE)", "2" },;
		{ "138,1638", "Atacadista de café em grão", "2" },;
		{ "138,166", "Atacadista (substituto tributário)", "2" },;
		{ "138,2078", "Centro de Distribuição - Decreto nº 29.482/2006 (PE)", "2" },;
		{ "138,2082", "Atacadista, Indústria do setor de confecção de roupas profissionais, exceto sob medida, CNAE 1413-4/01", "2" },;
		{ "138,254", "Distribuidor, Optante pelo Simples Nacional", "2" },;
		{ "138,255", "Farmácia integrante do Programa Farmácia Popular do Brasil, Atacadista", "2" },;
		{ "138,2737", "Farmácia integrante do Programa Farmácia Popular do Brasil, Varejista", "2" },;
		{ "138,296", "Atacadista de medicamentos e drogas de uso humano (CNAE 4644301), Atacadista", "2" },;
		{ "138,298", "Atacadista - Decreto Estadual nº 38.455/2012 (PE), Atacadista", "2" },;
		{ "140,1066", "Atacadista, Centro de Distribuição (substituto tributário) - Decreto nº 57.608/2011 (SP)", "2" },;
		{ "140,1234", "Atacadista, Atacadista - regime especial - RIOLOG (RJ)", "2" },;
		{ "140,1487", "Atacadista, Atacadista - Decreto Estadual nº 38.455/2012 (PE)", "2" },;
		{ "140,163", "Atacadista, Atacadista (substituto tributário) para Medicamentos e Produtos Farmacêuticos - Decretos nº 28.247/2005 e nº 19.528/1996 (PE)", "2" },;
		{ "140,1641", "Atacadista, Atacadista (substituto tributário)", "2" },;
		{ "140,2077", "Atacadista, Distribuidor (substituto tributário) - Decreto nº 34.063/2012 (DF)", "2" },;
		{ "140,2081", "Atacadista, Carga líquida - Decreto nº 29.560/2008 - Atacadistas", "2" },;
		{ "140,217", "Atacadista, Carga líquida - Decreto nº 31.066/2012 - Atacadistas - Produtos de Informática", "2" },;
		{ "140,2346", "Atacadista, Indústria de autopropulsores", "2" },;
		{ "140,2420", "Atacadista, Transporte de passageiros por ônibus urbano e no do sistema hidroviário (aquaviário)", "2" },;
		{ "140,3032", "Atacadista, Atacadista - Termo de Acordo - Art. 11, XXIII do Anexo IX do RCTE (GO)", "2" },;
		{ "1642,140", "Atacadista, Indústria de artefatos de material plástico para usos industriais", "2" },;
		{ "1932,138", "Atacadista, Indústria de artefatos de material plástico para outros usos não especificados anteriormente, CNAE 2229-3/99", "2" },;
		{ "232,114", "Varejista, Atacadista ou varejista optante pelo Regime de Apuração Simplificado (SE)", "2" },;
		{ "2531,138", "Varejista, Varejista de produtos farmacêuticos sem manipulação de fórmula (CNAE 4771701)", "2" },;
		{ "138,1932", "Varejista, Contribuinte (substituto tributário nas saídas que promover) - regime especial", "2" },;
		{ "138,2540", "Varejista, Indústria exportadora", "2" },;
		{ "1487,163", "Varejista, Atacadista enquadrado no Regime de Estimativa Simplificado (MT)", "2" },;
		{ "1548,1638", "Varejista, Centro de Distribuição - Decreto nº 29.482/2006 (PE)", "2" },;
		{ "138,1487,1501", "Varejista, Carga líquida - Decreto nº 29.560/2008 - Varejistas", "2" },;
		{ "138,1487,1630", "Varejista, Empresa enquadrada na Lei nº 25.665/ 1999 (RJ) - Pólo Gás Químico", "2" },;
		{ "138,1499,1350", "Varejista, Varejista de mercadorias em geral, com predominância de produtos alimentícios - supermercados", "2" },;
		{ "138,2339,1350", "Varejista, Varejista - Vendas exclusivamente por meio da Internet ou de telemarketing", "2" },;
		{ "140,1630,1095", "Varejista, AC 2024131", "2" },;
		{ "140,1630,2077", "Varejista enquadrado no Regime de Estimativa Simplificado (MT), Varejista", "2" },;
		{ "1400,1638,1499", "Atacadista - Regime Especial - Decreto nº 44.498/2013 (RJ), Atacadista", "2" },;
		{ "138,1350,1487,1499", "Distribuidor, Indústria de aeronave", "2" },;
		{ "1400,1638,1499,1487", "Atacadista - Lei nº 9.025/2020 - RIOLOG (RJ), Atacadista", "2" },;
		{ "3", "Atacadista, Atacadista - Regime Especial - Decreto nº 44.498/2013 (RJ)", "2" },;
		{ "3,408", "Atacadista, Atacadista/distribuidor (substituto tributário) - regime especial - Medicamentos e Produtos Farmacêuticos - Decretos nº 11.872/2009 (BA)", "2" },;
		{ "3,408", "Contribuinte (substituto tributário nas saídas que promover) - regime especial, Indústria exportadora", "2" },;
		{ "3,1701,408", "Distribuidor de produtos farmacêuticos, Atacadista (substituto tributário)", "2" },;
		{ "6", "Atacadista, Contribuinte (substituto tributário nas saídas que promover) - regime especial, Contribuinte substituto da mesma mercadoria", "2" },;
		{ "29", "Atacadista, Contribuinte (substituto tributário nas saídas que promover) - regime especial, Pessoa jurídica optante pelo lucro real e que tenha sua receita, total ou parcialmente, excluída do regime não-cumulativo (PIS/COFINS)", "2" },;
		{ "46", "Atacadista, Atacadista (substituto tributário) para Cosméticos e Artigos de Perfumaria - Decretos nº 35.677/2010 e nº 19.528/1996 (PE), Atacadista - Decreto Estadual nº 38.455/2012 (PE)", "2" },;
		{ "138", "Atacadista, Atacadista (substituto tributário) para aparelho de barbear, lâmina de barbear, navalha e isqueiro - Decretos n° 23.317/2001 e n° 19.528/1996 (PE), Atacadista - Decreto Estadual nº 38.455/2012 (PE)", "2" },;
		{ "554", "Varejista, Pessoa jurídica optante pelo lucro real e que tenha sua receita, total ou parcialmente, excluída do regime não-cumulativo (PIS/COFINS), Centro de Distribuição (substituto tributário) - Decreto nº 57.608/2011 (SP)", "2" },;
		{ "557", "Varejista, Pessoa jurídica optante pelo lucro real e que tenha sua receita, total ou parcialmente, excluída do regime não-cumulativo (PIS/COFINS), Centro de Distribuição - Decreto nº 29.482/2006 (PE)", "2" },;
		{ "652", "Atacadista (substituto tributário) - produtos eletrônicos, eletroeletrônicos e eletrodomésticos - Decretos Estaduais nº 35.701/2010 e19.528/1996 (PE), Atacadista (substituto tributário), Atacadista (substituto tributário) para Cosméticos e Artigos de Perfumaria - Decretos nº 35.677/2010 e nº 19.528/1996 (PE)", "2" },;
		{ "654", "Atacadista, Atacadista - Decreto Estadual nº 38.455/2012 (PE), Contribuinte (substituto tributário nas saídas que promover) - regime especial, Atacadista (substituto tributário) para Cosméticos e Artigos de Perfumaria - Decretos nº 35.677/2010 e nº 19.528/1996 (PE)", "2" },;
		{ "773", "Atacadista (substituto tributário) - produtos eletrônicos, eletroeletrônicos e eletrodomésticos - Decretos Estaduais nº 35.701/2010 e19.528/1996 (PE), Atacadista (substituto tributário), Atacadista (substituto tributário) para Cosméticos e Artigos de Perfumaria - Decretos nº 35.677/2010 e nº 19.528/1996 (PE), Contribuinte (substituto tributário nas saídas que promover) - regime especial", "2" },;
		{ "802", "Consumidor final contribuinte do ICMS", "2" },;
		{ "803", "Consumidor final contribuinte do ICMS, Pessoa jurídica habilitada ao RECAP", "2" },;
		{ "804", "Consumidor final contribuinte do ICMS, Pessoa jurídica habilitada ao RECAP", "2" },;
		{ "808", "Consumidor final contribuinte do ICMS, Equiparado a industrial, Pessoa jurídica habilitada ao RECAP", "2" },;
		{ "810", "Consumidor final não contribuinte do ICMS", "2" },;
		{ "924", "Contribuinte do ICMS", "2" },;
		{ "1706", "Pessoa física", "2" },;
		{ "2572", "Pessoa física", "2" },;
		{ "213,6", "Atacadista", "2" },;
		{ "3,499", "Autarquia", "2" },;
		{ "6,133", "Administração Pública Direta", "2" },;
		{ "6,213", "Órgãos da União, dos Estados, do Distrito Federal e dos Municípios", "2" },;
		{ "6,808", "Produtor rural agricultor", "2" },;
		{ "6,809", "Clínica ou hospital", "2" },;
		{ "6,810", "Administração Pública Indireta Federal", "2" },;
		{ "809,6", "Administração Pública Indireta Estadual", "2" },;
		{ "811,6", "Administração Pública Indireta Municipal", "2" },;
		{ "1,114", "Administração Pública Direta Federal", "2" },;
		{ "1,146", "Administração Pública Direta Municipal", "2" },;
		{ "3,2046", "Revendedor não inscrito no cadastro de contribuintes do ICMS", "2" },;
		{ "140,400", "Posto revendedor de combustível (Posto de Gasolina)", "2" },;
		{ "187,822", "Transportador Revendedor Retalhista (TRR)", "2" },;
		{ "773,557", "Hospitais, clínicas e congêneres, Consumidor final não contribuinte do ICMS", "2" },;
		{ "138,1115", "Consumidor final contribuinte do ICMS, Optante pelo Simples Nacional", "2" },;
		{ "138,114", "Consumidor final contribuinte do ICMS, Optante pelo Simples Nacional", "2" },;
		{ "138,135", "Consumidor final não contribuinte do ICMS, Hospitais públicos, fundações públicas, postos de saúde e secretarias de saúde", "2" },;
		{ "138,146", "Consumidor final não contribuinte do ICMS, Hospitais, clínicas e congêneres", "2" },;
		{ "138,1487", "Consumidor final não contribuinte do ICMS, Clínica ou hospital", "2" },;
		{ "138,1526", "Consumidor final não contribuinte do ICMS, Administração Pública Direta Federal", "2" },;
		{ "138,1548", "Consumidor final não contribuinte do ICMS, Administração Pública Direta Estadual", "2" },;
		{ "138,1638", "Consumidor final não contribuinte do ICMS, Administração Pública Direta Municipal", "2" },;
		{ "138,1641", "Administração Pública Direta Estadual, Consumidor final não contribuinte do ICMS", "2" },;
		{ "138,2352", "Órgãos públicos, Consumidor final não contribuinte do ICMS", "2" },;
		{ "138,2531", "Indústria, Indústria de aeronave", "2" },;
		{ "140,1235", "Indústria, Federação de cooperativas de que fizer parte", "2" },;
		{ "140,146", "Consumidor final contribuinte do ICMS, Consumidor Final Contribuinte enquadrado no Regime de Estimativa Simplificado", "2" },;
		{ "140,1599", "Atacadista, Regime não-cumulativo (PIS/COFINS)", "2" },;
		{ "140,2420", "Atacadista, Optante pelo Simples Nacional", "2" },;
		{ "140,2622", "Atacadista, Distribuidor hospitalar", "2" },;
		{ "140,263", "Varejista, Regime não-cumulativo (PIS/COFINS)", "2" },;
		{ "140,264", "Varejista, Optante pelo Simples Nacional", "2" },;
		{ "773,213,6", "Produtor rural, Produtor agropecuário (neste compreendidas as atividades de pecuária, a apicultura, a aqüicultura, a avicultura, a cunicultura, a ranicultura e a sericicultura)", "2" },;
		{ "809,810,6", "Clínica ou hospital, Administração Pública Direta", "2" },;
		{ "140,499,2296", "Atacadista, Atacadista e varejista no regime não-cumulativo", "2" },;
		{ "811,652,2058,6", "Atacadista, Indústria de aeronave", "2" },;
		{ "140,499,2296,2484", "Atacadista, Atacadista - Decreto Estadual nº 38.455/2012 (PE)", "2" },;
		{ "1710", "Atacadista, Federação de cooperativas de que fizer parte", "2" },;
		{ "1,287", "Atacadista, Contribuinte (substituto tributário nas saídas que promover) - regime especial", "2" },;
		{ "794", "Atacadista, Atacadista (substituto tributário) para Medicamentos e Produtos Farmacêuticos - Decretos nº 28.247/2005 e nº 19.528/1996 (PE)", "2" },;
		{ "140,1706", "Atacadista, Distribuidor de produtos farmacêuticos", "2" },;
		{ "140,247", "Atacadista, Atacadista (substituto tributário)", "2" },;
		{ "140,3032", "Atacadista, Atacadista enquadrado no Regime de Estimativa Simplificado (MT)", "2" },;
		{ "138,2339,1350", "Atacadista, Atacadista de instrumentos e materiais para uso médico, cirúrgico, hospitalar e de laboratórios", "2" },;
		{ "2131", "Atacadista, Reciclagem", "2" },;
		{ "6,809", "Atacadista, Atacadista - Lei nº 9.025/2020 - RIOLOG (RJ)", "2" },;
		{ "159", "Atacadista, Empresa da ZFM e ALC não cadastrados na Suframa", "2" },;
		{ "1159,54", "Atacadista, Indústria do setor de fabricação de linhas para costurar e bordar, CNAE 1314-6/00", "2" },;
		{ "3,579", "Atacadista, Indústria de artefatos de tapeçaria", "2" },;
		{ "3,578", "Atacadista, Indústria de artefatos de cordoaria, CNAE 1353-7/00", "2" },;
		{ "3,1521", "Atacadista, Indústria do setor de fabricação de tecidos especiais, inclusive artefatos, CNAE 1354-5/00", "2" },;
		{ "443", "Atacadista, Indústria do setor de fabricação de outros produtos têxcteis não especificados anteriormente, CNAE 1359-6/00", "2" },;
		{ "54,379", "Atacadista, Indústria do setor de confecção de roupas íntimas, CNAE 1411-8/01", "2" },;
		{ "54,2587", "Atacadista, Aeronave de bandeira estrangeira aportada no país", "2" },;
		{ "54,2588", "Atacadista, Indústria do setor de confecção de peças do vestuário, exceto roupas íntimas e as confeccionadas sob medida, CNAE 1412-6/01", "2" },;
		{ "140,499", "Atacadista, Indústria do setor de confecção, sob medida, de peças do vestuário, exceto roupas íntimas, CNAE 1412-6/02", "2" },;
		{ "2,499", "Atacadista, Indústria do setor de fabricação de embalagens de papel, CNAE 1731-1/00", "2" },;
		{ "400,54", "Varejista, Centro de Distribuição (substituto tributário) - Decreto nº 57.608/2011 (SP)", "2" },;
		{ "54,140", "Varejista, Atacadista e varejista no regime não-cumulativo", "2" },;
		{ "54,893", "Varejista, Varejista de produtos farmacêuticos sem manipulação de fórmula (CNAE 4771701)", "2" },;
		{ "54,2151", "Varejista, Varejista de produtos farmacêuticos com manipulação de fórmulas (CNAE 4771702)", "2" },;
		{ "54,2414", "Varejista, Federação de cooperativas de que fizer parte", "2" },;
		{ "54,255", "Varejista, Contribuinte (substituto tributário nas saídas que promover) - regime especial", "2" },;
		{ "54,296", "Varejista, Varejista com atividade principal de farmácia e/ou drogaria, que também comercialize outras mercadorias", "2" },;
		{ "54,138,2176", "Varejista, Varejista enquadrado no Regime de Estimativa Simplificado (MT)", "2" },;
		{ "54,2339,1350", "Varejista, Centro de Distribuição - Decreto nº 29.482/2006 (PE)", "2" },;
		{ "79", "Varejista, Restaurante (preparação de refeição)", "2" },;
		{ "856", "Varejista, Varejista - Vendas exclusivamente por meio da Internet ou de telemarketing", "2" },;
		{ "1470", "Varejista, Empresa da ZFM e ALC não cadastrados na Suframa", "2" },;
		{ "2547", "Varejista, Indústria do setor de fabricação de linhas para costurar e bordar, CNAE 1314-6/00", "2" },;
		{ "2548", "Varejista, Indústria do setor de fabricação de artefatos têxteis para uso doméstico. CNAE 1351-1/00", "2" },;
		{ "2562", "Atacadista interdependente, Equiparado a industrial", "2" },;
		{ "2556", "Clínica ou hospital, Hospitais, clínicas e congêneres, Consumidor final não contribuinte do ICMS", "2" },;
		{ "2561", "Administração Pública Direta Estadual, Administração Pública Direta Municipal, Consumidor final não contribuinte do ICMS", "2" },;
		{ "2565", "Atacadista, Optante pelo Simples Nacional, Empresa da ZFM e ALC não cadastrados na Suframa", "2" },;
		{ "29,1638", "Varejista, Optante pelo Simples Nacional, Restaurante (preparação de refeição)", "2" },;
		{ "54,1638", "Varejista, Optante pelo Simples Nacional, Empresa da ZFM e ALC não cadastrados na Suframa", "2" },;
		{ "138,1638,1701", "Órgãos públicos, Órgãos da União, dos Estados, do Distrito Federal e dos Municípios, Hospitais pertencentes a órgãos, fundações ou autarquias da administração pública estadual., Consumidor final não contribuinte do ICMS", "2" },;
		{ "2763", "Varejista, Optante pelo Simples Nacional, Restaurante (preparação de refeição), Restaurante optante pelo Simples Nacional", "2" },;
		{ "1646", "Varejista", "2" },;
		{ "2576", "Produtor rural pecuarista", "2" },;
		{ "2577", "Atacadista, Importador", "2" },;
		{ "3,2577", "Indústria do Petróleo e do Etanol", "2" },;
		{ "499", "Indústria, Indústria do setor de fabricação de embalagens de cartolina e papel-cartão, 1732-0/00", "2" };
	}

	Local aRemove := {      { "1,6", "Indústria - Contribuinte - regime especial - sistema porta-a-porta", "1" },;
		{ "1,37", "Indústria - Optante pelo Simples nacional - excesso sublimite receita bruta (ICMS - Apuração normal)", "1" },;
		{ "1,112", "Indústria - Contribuinte beneficiário do Decreto AM nº 33.084/2013", "1" },;
		{ "2", "Atacadista", "1" },;
		{ "2,6", "Atacadista - Contribuinte - regime especial - sistema porta-a-porta", "1" },;
		{ "2,37", "Atacadista - Optante pelo Simples nacional - excesso sublimite receita bruta (ICMS - Apuração normal)", "1" },;
		{ "2,79", "Atacadista - Atacadista que recebeu a mercadoria em transferência com regime Especial", "1" },;
		{ "3,6", "Varejista - Contribuinte - regime especial - sistema porta-a-porta", "1" },;
		{ "3,37", "Varejista - Optante pelo Simples nacional - excesso sublimite receita bruta (ICMS - Apuração normal)", "1" },;
		{ "24,6", "Importador - Contribuinte - regime especial - sistema porta-a-porta", "1" },;
		{ "24,14", "Importador - Contribuinte do ICMS", "1" },;
		{ "24,112", "Importador - Contribuinte beneficiário do Decreto AM nº 33.084/2013", "1" },;
		;
		{ "1,146", "Indústria - Varejista de medicamentos veterinários (CNAE 4771-7/04)", "2" },;
		{ "3,4", "Consumidor final contribuinte do ICMS - Regime não-cumulativo (PIS/COFINS)", "2" },;
		{ "54,14", "Importador - Varejista", "2" },;
		{ "138,4", "Atacadista - Regime não-cumulativo (PIS/COFINS)", "2" },;
		{ "138,114", "Atacadista - Regime cumulativo (PIS/COFINS)", "2" },;
		{ "138,135", "Atacadista - Atacadista - Decreto Estadual nº 38.455/2012 (PE)", "2" },;
		{ "138,146", "Atacadista - Varejista de medicamentos veterinários (CNAE 4771-7/04)", "2" },;
		{ "138,166", "Atacadista - Distribuidor (substituto tributário) - Decreto nº 34.063/2012 (DF)", "2" },;
		{ "138,254", "Atacadista - Atacadista/distribuidor (substituto tributário) - regime especial - Medicamentos e Produtos Farmacêuticos - Decretos nº 11.872/2009 (BA)", "2" },;
		{ "140,4", "Varejista - Regime não-cumulativo (PIS/COFINS)", "2" },;
		{ "140,114", "Varejista - Regime cumulativo (PIS/COFINS)", "2" },;
		{ "140,146", "Varejista - Varejista de medicamentos veterinários (CNAE 4771-7/04)", "2" },;
		{ "140,242", "Varejista - Varejista - Vendas exclusivamente por meio da Internet ou de telemarketing", "2" },;
		{ "232,114", "Distribuidor - Regime cumulativo (PIS/COFINS)", "2" },;
		{ "958,14", "Farmácia integrante do Programa Farmácia Popular do Brasil - Varejista", "2" },;
		{ "1487,163", "Contribuinte (substituto tributário nas saídas que promover) - regime especial - Pessoa jurídica optante pelo lucro real e que tenha sua receita, total ou parcialmente, excluída do regime não-cumulativo (PIS/COFINS)", "2" } }

	FISImportCarga():ImportEnquad(aImpEnquad)
	FISImportCarga():RemoveEnquad(aRemove)

	FWFreeArray(aImpEnquad)
	FWFreeArray(aRemove)

Return

/*/{Protheus.doc GetParamCJE
	Função responsavel pela importação da tabela de Enquadramento
	@type  Function
	@author Erich Buttner
	@since 23/08/2023
	@version version
	@param param_name, param_type, param_descr
	@return return_var, return_type, return_description
	@example
	(examples)
	@see (links_or_references)
    /*/
Static Function GetParamCJE()

	Local aParam := {"INTEGRAREGRA","USERNAMEDEFAULT","SENHADEFAULT"}
	Local cParametro := GetConfigClassif(aParam)
	Local jParam := JsonObject():New()

	jParam:FromJson(cParametro)

	FWFreeArray(aParam)

Return jParam

/*/{Protheus.doc AbertTabela
	Função responsavel pela importação da tabela de Enquadramento
	@type  Function
	@author Erich Buttner
	@since 23/08/2023
	@version version
	@param param_name, param_type, param_descr
	@return return_var, return_type, return_description
	@example
	(examples)
	@see (links_or_references)
    /*/
Static Function AbertTabela()

	DbselectArea("CJB")
	CJB->(DbCloseArea())

	DbselectArea("CJC")
	CJC->(DbCloseArea())

	DbselectArea("CJD")
	CJD->(DbCloseArea())

	DbselectArea("CJE")
	CJE->(DbCloseArea())

	DbselectArea("CJF")
	CJF->(DbCloseArea())

	DbselectArea("CJG")
	CJG->(DbCloseArea())

	DbselectArea("CJH")
	CJH->(DbCloseArea())

	DbselectArea("CJI")
	CJI->(DbCloseArea())

	DbselectArea("CJK")
	CJK->(DbCloseArea())


Return
