Function PmsCorSX1()
Local i := 0
Local j := 0

Local aEstrut := {"X1_GRUPO","X1_ORDEM","X1_PERGUNT","X1_PERSPA","X1_PERENG","X1_VARIAVL","X1_TIPO","X1_TAMANHO","X1_DECIMAL","X1_PRESEL","X1_GSC","X1_VALID","X1_VAR01","X1_DEF01","X1_DEFSPA1","X1_DEFENG1","X1_CNT01","X1_VAR02","X1_DEF02","X1_DEFSPA2","X1_DEFENG2","X1_CNT02","X1_VAR03","X1_DEF03","X1_DEFSPA3","X1_DEFENG3","X1_CNT03","X1_VAR04","X1_DEF04","X1_DEFSPA4","X1_DEFENG4","X1_CNT04","X1_VAR05","X1_DEF05","X1_DEFSPA5","X1_DEFENG5","X1_CNT05","X1_F3","X1_PYME","X1_GRPSXG","X1_HELP"}
Local aWrite := {}

aAdd(aWrite,{"PMA100","01","Modo de exibicao do orcam. ?","¿Modo de exhibicion del presu?","Budget display mode ?","MV_CH1","N",1,0,2,"C","","MV_PAR01","Arvore","Arbol","Tree","","","Planilha","Planilla","Worksheet","","","","","","","","","","","","","","","","","","N","",""})
aAdd(aWrite,{"PMA200","01","Modo de Exibicao do Projeto ?","¿Modo de exhibicion del proye?","Project Display Mode ?","MV_CH1","N",1,0,2,"C","","MV_PAR01","Arvore","Arbol","Tree","","","Planilha","Planilla","Spreadsheet","","","","","","","","","","","","","","","","","","N","",""})
aAdd(aWrite,{"PMC100","01","Data referencia ?","¿Fecha referencia?","Reference Date ?","mv_ch1","D",8,0,0,"G","","mv_par01","","","","","","","","","","","","","","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMC100","02","Moeda Visualizacao ?","¿Moneda visualizac.?","Moeda visualizacao ?","mv_ch2","N",1,0,1,"C","","mv_par02","Moeda 1","Moneda 1","Currency 1","","","Moeda 2","Moneda 2","Currency 2","","","Moeda 3","Moneda 3","Currency 3","","","Moeda 4","Moneda 4","Currency 4","","","Moeda 5","Moneda 5","Currency 5","","","S","",""})
aAdd(aWrite,{"PMR010","01","Composicao de ?","¿De Composicion?","From Composition ?","mv_ch1","C",10,0,0,"G","","mv_par01","","","","","","","","","","","","","","","","","","","","","","","","","AE1","S","",""})
aAdd(aWrite,{"PMR010","02","Composicao ate ?","¿A  Composicion?","To Composition ?","mv_ch2","C",10,0,0,"G","","mv_par02","","","","ZZZZZZZZZZ","","","","","","","","","","","","","","","","","","","","","AE1","S","",""})
aAdd(aWrite,{"PMR010","03","Ult.atualizacao de ?","¿De Ult.Actualizac.?","From Last Update ?","mv_ch3","D",8,0,0,"G","","mv_par03","","","","01/01/2002","","","","","","","","","","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR010","04","Ult.atualizacao ate ?","¿A  Ult.Actualizac.?","To Last Update ?","mv_ch4","D",8,0,0,"G","","mv_par04","","","","31/12/2005","","","","","","","","","","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR030","01","Orcamento  de ?","¿De Presupuesto?","From Budget ?","mv_ch1","C",10,0,0,"G","","mv_par01","","","","","","","","","","","","","","","","","","","","","","","","","AF1","S","",""})
aAdd(aWrite,{"PMR030","02","Orcamento ate ?","¿A  Presupuesto?","To Budget ?","mv_ch2","C",10,0,0,"G","","mv_par02","","","","ZZZZZZZZZZ","","","","","","","","","","","","","","","","","","","","","AF1","S","",""})
aAdd(aWrite,{"PMR030","03","Data de valid. de ?","¿De Fecha?","From Due Date ?","mv_ch3","D",8,0,0,"G","","mv_par03","","","","01/01/2002","","","","","","","","","","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR030","04","Data de valid. ate ?","¿A  Fecha?","To Due Date ?","mv_ch4","D",8,0,0,"G","","mv_par04","","","","31/12/2005","","","","","","","","","","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR030","05","Filtrar niveis ?","¿Filtrar niveles?","Filter Levels ?","mv_ch5","C",20,0,0,"G","","mv_par05","","","","","","","","","","","","","","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR030","06","Filtrar fase ?","¿Filtrar fase?","Filter Phase ?","mv_ch6","C",20,0,0,"G","","mv_par06","","","","","","","","","","","","","","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR030","07","Produto de ?","¿De Producto?","From Product ?","mv_ch7","C",15,0,0,"G","","mv_par07","","","","","","","","","","","","","","","","","","","","","","","","","SB1","S","",""})
aAdd(aWrite,{"PMR030","08","Produto ate ?","¿A  Producto?","To Product ?","mv_ch8","C",15,0,0,"G","","mv_par08","","","","ZZZZZZZZZZZZZZZ","","","","","","","","","","","","","","","","","","","","","SB1","S","",""})
aAdd(aWrite,{"PMR030","09","Filtrar tipo prod. ?","¿Filtrar tipo prod.?","Filter Produc. Type ?","mv_ch9","C",20,0,0,"G","","mv_par09","","","","","","","","","","","","","","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR030","10","Tipo de despesa de ?","¿De Tipo de Gasto?","From Expense Type ?","mv_cha","C",4,0,0,"G","","mv_par10","","","","","","","","","","","","","","","","","","","","","","","","","FD","S","",""})
aAdd(aWrite,{"PMR030","11","Tipo de despesa ate ?","¿A  Tipo de Gasto?","To Expense Type ?","mv_chb","C",4,0,0,"G","","mv_par11","","","","ZZZZ","","","","","","","","","","","","","","","","","","","","","FD","S","",""})
aAdd(aWrite,{"PMR030","12","Cliente de ?","¿De Cliente?","From Customer ?","mv_chc","C",6,0,0,"G","","mv_par12","","","","","","","","","","","","","","","","","","","","","","","","","SA1","S","001",""})
aAdd(aWrite,{"PMR030","13","Loja de ?","¿De Tienda?","From Unit ?","mv_chd","C",2,0,0,"G","","mv_par13","","","","","","","","","","","","","","","","","","","","","","","","","","S","002",""})
aAdd(aWrite,{"PMR030","14","Cliente ate ?","¿A  Cliente?","To Customer ?","mv_che","C",6,0,0,"G","","mv_par14","","","","ZZZZZZ","","","","","","","","","","","","","","","","","","","","","SA1","S","001",""})
aAdd(aWrite,{"PMR030","15","Loja ate ?","¿A  Tienda?","To Unit ?","mv_chf","C",2,0,0,"G","","mv_par15","","","","ZZ","","","","","","","","","","","","","","","","","","","","","","S","002",""})
aAdd(aWrite,{"PMR040","01","Orcamento  de ?","¿De Presupuesto?","From Budget ?","mv_ch1","C",10,0,0,"G","","mv_par01","","","","","","","","","","","","","","","","","","","","","","","","","AF1","S","",""})
aAdd(aWrite,{"PMR040","02","Orcamento ate ?","¿A  Presupuesto?","To Budget ?","mv_ch2","C",10,0,0,"G","","mv_par02","","","","ZZZZZZZZZZ","","","","","","","","","","","","","","","","","","","","","AF1","S","",""})
aAdd(aWrite,{"PMR040","03","Data de valid. de ?","¿De Fecha validez?","From Due Date ?","mv_ch3","D",8,0,0,"G","","mv_par03","","","","01/01/2002","","","","","","","","","","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR040","04","Data de valid. ate ?","¿A  Fecha validez?","To Due Date ?","mv_ch4","D",8,0,0,"G","","mv_par04","","","","31/12/2005","","","","","","","","","","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR050","01","Orcamento  de ?","¿De Presupuesto?","From Budget ?","mv_ch1","C",10,0,0,"G","","mv_par01","","","","","","","","","","","","","","","","","","","","","","","","","AF1","S","",""})
aAdd(aWrite,{"PMR050","02","Orcamento ate ?","¿A  Presupuesto?","To Budget ?","mv_ch2","C",10,0,0,"G","","mv_par02","","","","ZZZZZZZZZZ","","","","","","","","","","","","","","","","","","","","","AF1","S","",""})
aAdd(aWrite,{"PMR050","03","Data de valid. de ?","¿De Fecha validez?","From Due Date ?","mv_ch3","D",8,0,0,"G","","mv_par03","","","","01/01/2002","","","","","","","","","","","","","","","","","","","","","","S","",""})

PmsCorSX1A(aWrite)
PmsCorSX1b(aWrite)


aAdd(aWrite,{"PMR140","03","Data do projeto de ?","¿De Fecha del proyecto?","From Project Date ?","mv_ch3","D",8,0,0,"G","","mv_par03","","","","01/01/2002","","","","","","","","","","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR140","04","Data do projeto ate ?","¿A Fecha del proyecto?","To Project Date ?","mv_ch4","D",8,0,0,"G","","mv_par04","","","","31/12/2005","","","","","","","","","","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR140","05","Versao ?","¿Version?","Version ?","mv_ch5","C",2,0,0,"G","","mv_par05","","","","","","","","","","","","","","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR150","01","Projeto de ?","¿De Proyecto?","From Project ?","mv_ch1","C",10,0,0,"G","","mv_par01","","","","PRJ-0002-6","","","","","","","","","","","","","","","","","","","","","AF8","S","",""})
aAdd(aWrite,{"PMR150","02","Projeto ate ?","¿A  Proyecto?","To Project ?","mv_ch2","C",10,0,0,"G","","mv_par02","","","","PRJ-0002-6","","","","","","","","","","","","","","","","","","","","","AF8","S","",""})
aAdd(aWrite,{"PMR150","03","Data do projeto de ?","¿De Fecha del Proyecto?","From Project Date ?","mv_ch3","D",8,0,0,"G","","mv_par03","","","","'01/01/02'","","","","","","","","","","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR150","04","Data do projeto ate ?","¿A Fecha del Proyecto?","To Project Date ?","mv_ch4","D",8,0,0,"G","","mv_par04","","","","'31/12/05'","","","","","","","","","","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR150","05","Versao ?","¿Version?","Version ?","mv_ch5","C",2,0,0,"G","","mv_par05","","","","","","","","","","","","","","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR160","01","Projeto de ?","¿De Proyecto?","From Project ?","mv_ch1","C",10,0,0,"G","","mv_par01","","","","","","","","","","","","","","","","","","","","","","","","","AF8","S","",""})
aAdd(aWrite,{"PMR160","02","Projeto ate ?","¿A  Proyecto?","To Project ?","mv_ch2","C",10,0,0,"G","","mv_par02","","","","ZZZZZZZZZZ","","","","","","","","","","","","","","","","","","","","","AF8","S","",""})
aAdd(aWrite,{"PMR160","03","Data do projeto de ?","¿De Fecha Proyecto?","From Project Date ?","mv_ch3","D",8,0,0,"G","","mv_par03","","","","'01/01/02'","","","","","","","","","","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR160","04","Data do projeto ate ?","¿A  Fecha Proyecto?","To Project Date ?","mv_ch4","D",8,0,0,"G","","mv_par04","","","","'31/12/05'","","","","","","","","","","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR160","05","Versao ?","¿Version?","Version ?","mv_ch5","C",2,0,0,"G","","mv_par05","","","","","","","","","","","","","","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR160","06","Filtrar nivel ?","¿Filtrar Nivel?","Level ?","mv_ch6","C",20,0,0,"G","","mv_par06","","","","","","","","","","","","","","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR160","07","Filtrar fase ?","¿Filtrar Fase?","Stage ?","mv_ch7","C",20,0,0,"G","","mv_par07","","","","","","","","","","","","","","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR160","08","Data de referencia ?","¿Fecha referencia?","Reference Date ?","mv_ch8","D",8,0,0,"G","","mv_par08","","","","'  /  /  '","","","","","","","","","","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR160","10","Cliente de ?","¿De Cliente?","From Customer ?","mv_cha","C",6,0,0,"G","","mv_par10","","","","","","","","","","","","","","","","","","","","","","","","","SA1","S","001",""})
aAdd(aWrite,{"PMR160","11","Loja de ?","¿De Tienda?","From Unit ?","mv_chb","C",2,0,0,"G","","mv_par11","","","","","","","","","","","","","","","","","","","","","","","","","","S","002",""})
aAdd(aWrite,{"PMR160","12","Cliente ate ?","¿A  Cliente?","To Customer ?","mv_chc","C",6,0,0,"G","","mv_par12","","","","ZZZZZZ","","","","","","","","","","","","","","","","","","","","","SA1","S","001",""})
aAdd(aWrite,{"PMR160","13","Loja ate ?","¿A  Tienda?","To Unit ?","mv_chd","C",2,0,0,"G","","mv_par13","","","","ZZ","","","","","","","","","","","","","","","","","","","","","","S","002",""})
aAdd(aWrite,{"PMR170","01","Projeto de ?","¿De Proyecto?","From Project ?","mv_ch1","C",10,0,0,"G","","mv_par01","","","","","","","","","","","","","","","","","","","","","","","","","AF8","S","",""})
aAdd(aWrite,{"PMR170","02","Projeto ate ?","¿A  Proyecto?","To Project ?","mv_ch2","C",10,0,0,"G","","mv_par02","","","","ZZZZZZZZZZ","","","","","","","","","","","","","","","","","","","","","AF8","S","",""})
aAdd(aWrite,{"PMR170","03","Data do projeto de ?","¿De Periodo?","From Project Date ?","mv_ch3","D",8,0,0,"G","","mv_par03","","","","01/01/2002","","","","","","","","","","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR170","04","Data do projeto ate ?","¿A  Periodo?","To Project Date ?","mv_ch4","D",8,0,0,"G","","mv_par04","","","","31/12/2005","","","","","","","","","","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR170","05","Versao ?","¿Version?","Version ?","mv_ch5","C",2,0,0,"G","","mv_par05","","","","","","","","","","","","","","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR180","01","Projeto de ?","¿De Proyecto?","From Project ?","mv_ch1","C",10,0,0,"G","","mv_par01","","","","PRJ-0002-6","","","","","","","","","","","","","","","","","","","","","AF8","S","",""})
aAdd(aWrite,{"PMR180","02","Projeto ate ?","¿A  Proyecto?","To Project ?","mv_ch2","C",10,0,0,"G","","mv_par02","","","","PRJ-0002-6","","","","","","","","","","","","","","","","","","","","","AF8","S","",""})
aAdd(aWrite,{"PMR180","03","Data do projeto de ?","¿De Fecha Proyecto?","From Project Date ?","mv_ch3","D",8,0,0,"G","","mv_par03","","","","'01/01/02'","","","","","","","","","","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR180","04","Data do projeto ate ?","¿A  Fecha Proyecto?","To Project Date ?","mv_ch4","D",8,0,0,"G","","mv_par04","","","","'31/12/05'","","","","","","","","","","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR180","05","Numero de Dias ?","¿Numero de Dias?","No of Days ?","MV_CH5","N",3,0,0,"G","","mv_par05","","","","60","","","","","","","","","","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR190","01","Orcamento de ?","¿De Presupuesto?","Budget from ?","mv_ch1","C",10,0,0,"G","","mv_par01","","","","","","","","","","","","","","","","","","","","","","","","","AF1","S","",""})
aAdd(aWrite,{"PMR190","02","Orcamento ate ?","¿A  Presupuesto?","Budget to ?","mv_ch2","C",10,0,0,"G","","mv_par02","","","","ZZZZZZZZZZ","","","","","","","","","","","","","","","","","","","","","AF1","S","",""})
aAdd(aWrite,{"PMR190","03","Filtrar niveis ?","¿Filtrar niveles?","Filter Levels ?","mv_ch3","C",20,0,0,"G","","mv_par03","","","","","","","","","","","","","","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR190","04","Produto de ?","¿De Producto?","From Product ?","mv_ch4","C",15,0,0,"G","","mv_par04","","","","","","","","","","","","","","","","","","","","","","","","","SB1","S","",""})
aAdd(aWrite,{"PMR190","05","Produto ate ?","¿A  Producto?","To Product ?","mv_ch5","C",15,0,0,"G","","mv_par05","","","","ZZZZZZZZZZZZZZZ","","","","","","","","","","","","","","","","","","","","","SB1","S","",""})
aAdd(aWrite,{"PMR190","06","Grupo de prod. de ?","¿De Grupo de prod.?","Prod. Group from ?","mv_ch6","C",4,0,0,"G","","mv_par06","","","","","","","","","","","","","","","","","","","","","","","","","SBM","S","",""})
aAdd(aWrite,{"PMR190","07","Grupo de prod. ate ?","¿A  Grupo de prod.?","Produc. Group to ?","mv_ch7","C",4,0,0,"G","","mv_par07","","","","ZZZZ","","","","","","","","","","","","","","","","","","","","","SBM","S","",""})
aAdd(aWrite,{"PMR190","08","Imprimir ?","¿Imprimir?","Print ?","mv_ch8","N",1,0,0,"C","","mv_par08","Todos","Todos","All","","","Com Custo","Con Costo","With Cost","","","Sem Custo","Sin Costo","Without Cost","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR190","09","Detalhar ?","¿Detallar?","Give Details ?","mv_ch9","N",1,0,0,"C","","mv_par09","Por Orcamento","Por Presupuesto","By Budget","","","Por Tarefa","Por Tarea","By Task","","","","","","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR210","01","Projeto de ?","¿De Proyecto?","Project from ?","mv_ch1","C",10,0,0,"G","","mv_par01","","","","PRJ-0002-6","","","","","","","","","","","","","","","","","","","","","AF8","S","",""})
aAdd(aWrite,{"PMR210","02","Projeto ate ?","¿A  Proyecto?","Project to ?","mv_ch2","C",10,0,0,"G","","mv_par02","","","","PRJ-0002-6","","","","","","","","","","","","","","","","","","","","","AF8","S","",""})
aAdd(aWrite,{"PMR210","03","Filtrar niveis ?","¿Filtrar niveles?","Filter Levels ?","mv_ch3","C",20,0,0,"G","","mv_par03","","","","","","","","","","","","","","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR210","04","Produto de ?","¿De Producto?","From Product ?","mv_ch4","C",15,0,0,"G","","mv_par04","","","","","","","","","","","","","","","","","","","","","","","","","SB1","S","",""})
aAdd(aWrite,{"PMR210","05","Produto ate ?","¿A  Producto?","To Product ?","mv_ch5","C",15,0,0,"G","","mv_par05","","","","ZZZZZZZZZZZZZZZ","","","","","","","","","","","","","","","","","","","","","SB1","S","",""})
aAdd(aWrite,{"PMR210","06","Grupo de prod. de ?","¿De Grupo de prod.?","Produc. Group from ?","mv_ch6","C",4,0,0,"G","","mv_par06","","","","","","","","","","","","","","","","","","","","","","","","","SBM","S","",""})
aAdd(aWrite,{"PMR210","07","Grupo de prod. ate ?","¿A  Grupo de prod.?","Produc. Group to ?","mv_ch7","C",4,0,0,"G","","mv_par07","","","","ZZZZ","","","","","","","","","","","","","","","","","","","","","SBM","S","",""})
aAdd(aWrite,{"PMR210","08","Imprimir ?","¿Imprimir?","Print ?","mv_ch8","N",1,0,1,"C","","mv_par08","Todos","Todos","All","","","Com Custo","Con Costo","With Cost","","","Sem Custo","Sin Costo","Without Cost","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR210","09","Detalhe ?","¿Detalle?","Details ?","mv_ch9","N",1,0,1,"C","","mv_par09","Por Projeto","Por Proyecto","By Project","","","Por Tarefa","Por Tarea","By Task","","","","","","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR211","01","Projeto ?","¿Proyecto?","Project ?","mv_ch1","C",10,0,0,"G","","mv_par01","","","","","","","","","","","","","","","","","","","","","","","","","AF8","S","",""})
aAdd(aWrite,{"PMR211","02","Comparar versao ?","¿Comparar version?","Compare Version ?","mv_ch2","C",2,0,0,"G","","mv_par02","","","","","","","","","","","","","","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR211","03","Com a versao ?","¿Con la version?","With the Version ?","mv_ch3","C",2,0,0,"G","","mv_par03","","","","","","","","","","","","","","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR220","01","Projeto de ?","¿De Proyecto?","Project from ?","mv_ch1","C",10,0,0,"G","","mv_par01","","","","PRJ-0002-6","","","","","","","","","","","","","","","","","","","","","AF8","S","",""})
aAdd(aWrite,{"PMR220","02","Projeto ate ?","¿A  Proyecto?","Project to ?","mv_ch2","C",10,0,0,"G","","mv_par02","","","","PRJ-0002-6","","","","","","","","","","","","","","","","","","","","","AF8","S","",""})
aAdd(aWrite,{"PMR220","03","Numero de Dias ?","¿Numero de dias?","Number of Days ?","MV_CH3","N",3,0,0,"G","","mv_par03","","","","60","","","","","","","","","","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR230","01","Projeto de ?","¿De Proyecto?","Project from ?","mv_ch1","C",10,0,0,"G","","mv_par01","","","","","","","","","","","","","","","","","","","","","","","","","AF8","S","",""})
aAdd(aWrite,{"PMR230","02","Projeto Ate ?","¿A  Proyecto?","Project to ?","mv_ch2","C",10,0,0,"G","","mv_par02","","","","ZZZZZZZZZZ","","","","","","","","","","","","","","","","","","","","","AF8","S","",""})
aAdd(aWrite,{"PMR230","03","Numero de Dias ?","¿Numero de dias?","Number of Days ?","MV_CH3","N",3,0,0,"G","","mv_par03","","","","60","","","","","","","","","","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR250","01","Projeto de ?","¿De Proyecto?","Project from ?","mv_ch1","C",10,0,0,"G","","mv_par01","","","","","","","","","","","","","","","","","","","","","","","","","AF8","S","",""})
aAdd(aWrite,{"PMR250","02","Projeto Ate ?","¿A  Proyecto?","Project to ?","mv_ch2","C",10,0,0,"G","","mv_par02","","","","ZZZZZZZZZZ","","","","","","","","","","","","","","","","","","","","","AF8","S","",""})
aAdd(aWrite,{"PMR250","03","Recurso de ?","¿De Recurso?","Resource from ?","mv_ch3","C",6,0,0,"G","","mv_par03","","","","","","","","","","","","","","","","","","","","","","","","","AE8","S","",""})
aAdd(aWrite,{"PMR250","04","Recurso Ate ?","¿A  Recurso?","Resource to ?","mv_ch4","C",6,0,0,"G","","mv_par04","","","","ZZZZZZ","","","","","","","","","","","","","","","","","","","","","AE8","S","",""})
aAdd(aWrite,{"PMR250","05","Data inicial ?","¿De Fecha?","Initial Date ?","mv_ch5","D",8,0,0,"G","","mv_par05","","","","","","","","","","","","","","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR250","06","Data final ?","¿A  Final?","Final Date ?","mv_ch6","D",8,0,0,"G","","mv_par06","","","","","","","","","","","","","","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR250","07","Quebrar por ?","¿Saltar por?","Break by ?","mv_ch7","N",1,0,1,"C","","mv_par07","Recurso","Recurso","Resource","","","Projeto","Proyecto","Project","","","","","","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR270","01","Projeto de ?","¿De proyecto?","Project from ?","MV_CH1","C",10,0,0,"G","","","","","","","","","","","","","","","","","","","","","","","","","","","AF8","S","",""})
aAdd(aWrite,{"PMR270","02","Projeto ate ?","¿A proyecto?","Project to ?","MV_CH2","C",10,0,0,"G","","","","","","ZZZZZZZZZZ","","","","","","","","","","","","","","","","","","","","","AF8","S","",""})
aAdd(aWrite,{"PMR270","03","Data do projeto de ?","¿De fecha del proyecto?","Project Date from ?","MV_CH3","D",8,0,0,"G","","","","","","01/01/2002","","","","","","","","","","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR270","04","Data do projeto ate ?","¿A fecha del proyecto?","Project Date to ?","MV_CH4","D",8,0,0,"G","","","","","","31/12/2005","","","","","","","","","","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR270","05","Filtrar niveis ?","¿Filtrar niveles?","Filter Levels ?","MV_CH5","C",20,0,0,"G","","","","","","","","","","","","","","","","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR270","06","Data inicial ?","¿De Fecha?","Initial Date ?","MV_CH6","D",8,0,0,"G","","","","","","","","","","","","","","","","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR270","07","Data final ?","¿A Fecha?","Final Date ?","MV_CH7","D",8,0,0,"G","","","","","","","","","","","","","","","","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR270","08","Periodo ?","¿Periodo?","Period ?","MV_CH8","C",1,0,1,"C","","","Diario","Diario","Daily","","","Semanal","Semanal","Weekly","","","Mensal","Mensual","Monthly","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR270","09","Projecao do valor ?","¿Proyeccion del valor?","Value Projection ?","MV_CH1","C",1,0,1,"C","","","Acumulado","Acumulado","Accumulated","","","Saldo","Saldo","Balance","","","","","","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR270","10","Versao ?","¿Version?","Version ?","MV_CHA","C",2,0,0,"G","","mv_par10","","","","","","","","","","","","","","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR280","01","Projeto De ? ?","¿?","From Project ? ?","MV_CH1","C",10,0,0,"G","","mv_par01","","","","","","","","","","","","","","","","","","","","","","","","","AF8","N","",""})
aAdd(aWrite,{"PMR280","02","Projeto Ate ? ?","¿?","To Project ? ?","MV_CH2","C",10,0,0,"G","","mv_par02","","","","","","","","","","","","","","","","","","","","","","","","","AF8","N","",""})
aAdd(aWrite,{"PMR280","03","Data do projeto de ? ?","¿?","From project date ? ?","MV_CH3","D",8,0,0,"G","","mv_par03","","","","","","","","","","","","","","","","","","","","","","","","","","N","",""})
aAdd(aWrite,{"PMR280","04","Data do projeto ate ? ?","¿?","To project date ? ?","MV_CH4","D",8,0,0,"G","","mv_par04","","","","","","","","","","","","","","","","","","","","","","","","","","N","",""})
aAdd(aWrite,{"PMR280","05","Versao  ? ?","¿?","Version ? ?","MV_CH5","C",2,0,0,"G","","mv_par05","","","","","","","","","","","","","","","","","","","","","","","","","","N","",""})
aAdd(aWrite,{"PMR280","06","Tipo do Periodo ? ?","¿?","Period Type ? ?","MV_CH6","N",1,0,1,"C","","mv_par06","Diario","","Daily","","","Semanal","","Weekly","","","Mensal","","Monthly","","","Anual","","Yearly","","","","","","","","N","",""})
aAdd(aWrite,{"PMR280","07","Data inicial da previsao ? ?","¿?","Initial forecast date ? ?","MV_CH7","D",8,0,0,"G","","mv_par07","","","","","","","","","","","","","","","","","","","","","","","","","","N","",""})
aAdd(aWrite,{"PMR280","08","Data final de previsao ? ?","¿?","Final forecast date ? ?","MV_CH8","D",8,0,0,"G","","mv_par08","","","","","","","","","","","","","","","","","","","","","","","","","","N","",""})
aAdd(aWrite,{"PMR90A","01","Projeto de ?","¿De Proyecto?","From Project ?","mv_ch1","C",10,0,0,"G","","mv_par01","","","","MOD_ERP","","","","","","","","","","","","","","","","","","","","","AF8","S","",""})
aAdd(aWrite,{"PMR90A","02","Projeto ate ?","¿A  Proyecto?","To Project ?","mv_ch2","C",10,0,0,"G","","mv_par02","","","","MOD_ERP","","","","","","","","","","","","","","","","","","","","","AF8","S","",""})
aAdd(aWrite,{"PMR90A","03","Data do projeto de ?","¿De Periodo?","From Project Date ?","mv_ch3","D",8,0,0,"G","","mv_par03","","","","'01/01/02'","","","","","","","","","","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR90A","04","Data do projeto ate ?","¿A  Periodo?","To Project Date ?","mv_ch4","D",8,0,0,"G","","mv_par04","","","","'31/12/05'","","","","","","","","","","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR90A","05","Versao ?","¿Version?","Version ?","mv_ch5","C",2,0,0,"G","","mv_par05","","","","","","","","","","","","","","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR90A","06","Filtrar fase ?","¿Filtrar fase?","Stage ?","mv_ch6","C",20,0,0,"G","","mv_par06","","","","","","","","","","","","","","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR90A","07","Recurso de ?","¿De Recurso?","From Resources ?","mv_ch7","C",15,0,0,"G","","mv_par07","","","","","","","","","","","","","","","","","","","","","","","","","AE8","S","",""})
aAdd(aWrite,{"PMR90A","08","Recurso ate ?","¿A  Recurso?","To Resources ?","mv_ch8","C",15,0,0,"G","","mv_par08","","","","ZZZZZZZZZZZZZZ","","","","","","","","","","","","","","","","","","","","","AE8","S","",""})
aAdd(aWrite,{"PMR90A","09","Dt. de Alocacao de ?","¿De Fch. de Asignacion?","Allocation Date from ?","mv_ch9","D",8,0,0,"G","","mv_par09","","","","'01/01/02'","","","","","","","","","","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR90A","10","Dt. de Alocacao ate ?","¿A Fch. de Asignacion?","Allocation Date to ?","mv_chA","D",8,0,0,"G","","mv_par10","","","","'31/12/05'","","","","","","","","","","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR220","04","Nivel              ?","¨Nivel             ?","Level              ?","mv_ch4","C",20,0,0,"G","","mv_par04","","","","","","","","","","","","","","","","","","","","","","","","","","N","",""})
aAdd(aWrite,{"PMR220","05","Fase               ?","¨Fase              ?","Phase              ?","mv_ch5","C",20,0,0,"G","","mv_par05","","","","","","","","","","","","","","","","","","","","","","","","","","N","",""})
aAdd(aWrite,{"PMR220","06","Detalhe            ?","¨Detalle           ?","Detail             ?","mv_ch6","N",1,0,1,"C","","mv_par06","Por Projeto","Por Proyecto","By Project","","","Por EDT/Tarefa","Por EDT/Tarea","By WBS/Task","","","","","","","","","","","","","","","","","","N","",""})
aAdd(aWrite,{"PMR220","07","Moeda              ?","¨Moneda            ?","Currency           ?","mv_ch7","N",1,0,1,"C","","mv_par07","Moeda 1","Moneda 1","Currency 1","","","Moeda 2","Moneda 2","Currency 2","","","Moeda 3","Moneda 3","Currency 3","","","Moeda 4","Moneda 4","Currency 4","","","Moeda 5","Moneda 5","Currency 5","","","N","",""})
aAdd(aWrite,{"PMR230","04","Nivel              ?","¨Nivel             ?","Level              ?","mv_ch4","C",20,0,0,"G","","mv_par04","","","","","","","","","","","","","","","","","","","","","","","","","","N","",""})
aAdd(aWrite,{"PMR230","05","Fase               ?","¨Fase              ?","Phase              ?","mv_ch5","C",20,0,0,"G","","mv_par05","","","","","","","","","","","","","","","","","","","","","","","","","","N","",""})
aAdd(aWrite,{"PMR230","06","Detalhe            ?","¨Detalle           ?","Detail             ?","mv_ch6","N",1,0,1,"C","","mv_par06","Por Projeto","Por Proyecto","By Project","","","Por Tarefa","Por Tarea","By Task","","","","","","","","","","","","","","","","","","N","",""})
aAdd(aWrite,{"PMR230","07","Moeda              ?","¨Moneda            ?","Currency           ?","mv_ch7","N",1,0,1,"C","","mv_par07","Moeda 1","Moneda 1","Currency 1","","","Moeda 2","Moneda 2","Currency 2","","","Moeda 3","Moneda 3","Currency 3","","","Moeda 4","Moneda 4","Currency 4","","","Moeda 5","Moneda 5","Currency 5","","","N","",""})


dbSelectArea("SX1")
dbSetOrder(1)
For i:= 1 To Len(aWrite)
	If !Empty(aWrite[i][1])
		While dbSeek(aWrite[i,1])
			RecLock("SX1",.F.,.T.)
			dbDelete()
			MsUnlock()
		End
	EndIf
Next


dbSelectArea("SX1")
dbSetOrder(1)
For i:= 1 To Len(aWrite)
	If !Empty(aWrite[i][1])
		If !dbSeek(aWrite[i,1]+aWrite[i,2])
			RecLock("SX1",.T.)
			For j:=1 To Len(aWrite[i])		
				If !Empty(FieldName(FieldPos(aEstrut[j])))
					FieldPut(FieldPos(aEstrut[j]),aWrite[i,j])
				EndIf
			Next j
	  
			dbCommit()        
			MsUnLock()
		EndIf
	EndIf
Next i



Return 