#include "tlpp-core.th"
#include "tlpp-rest.th"

namespace totvs.protheus.backoffice.apps.grr.integration.financial
using namespace totvs.protheus.backoffice.apps.grr.general

class FinancialIntegrationController from totvs.protheus.backoffice.apps.grr.general.ControllerBase
    public method new() as object

    @get('api/backoffice/apps/grr/integration/financial/receivable/status')
    public method getStatusList()

    @post('api/backoffice/apps/grr/integration/financial/receivable/resend')
    public method resendReceivable()

    @post('api/backoffice/apps/grr/integration/financial/receivable/set-error-resolved')
    public method setErrorResolved()
endClass

//------------------------------------------------------------------
/*/{Protheus.doc} new
    @type method
    @author guilherme.sordi@totvs.com.br
	@since 27/04/2026
    @version 12.1.2410
/*/
//-------------------------------------------------------------------
method new() as object class FinancialIntegrationController
return _Super:new()

//------------------------------------------------------------------
/*/{Protheus.doc} getStatusList
    @description Retorna a lista de status disponiveis para o reenvio e tratamento dos titulos.
    @type method
    @author guilherme.sordi@totvs.com.br
	@since 27/04/2026
    @version 12.1.2410
/*/
//-------------------------------------------------------------------
method getStatusList() class FinancialIntegrationController
    local jStatus := totvs.protheus.backoffice.apps.grr.integration.financial.FinancialIntegration():getStatusList() as json
    local aStatus := jStatus:getNames() as array
    local nX := 0 as numeric
    local aItems := {} as array
    local jItem as json

    for nX := 1 to len(aStatus)    
        jItem := JsonObject():new()
        jItem['value'] := aStatus[nX]
        jItem['label'] := jStatus[jItem['value']]
        aAdd(aItems, jItem)
    next

    oRest:setResponse({'items': aItems})
    oRest:setKeyHeaderResponse('Content-Type','application/json')
return

//------------------------------------------------------------------
/*/{Protheus.doc} resendReceivable
    @description Reenvia para processamento os titulos pendentes informados na requisicao.
    @type method
    @author guilherme.sordi@totvs.com.br
	@since 27/04/2026
    @version 12.1.2410
/*/
//-------------------------------------------------------------------
method resendReceivable() class FinancialIntegrationController
    local jBody := self:getBody() as json
    local oIntegration as object

    try
        self:checkMandatoryFields(jBody, {'list'})
    catch oError
        FlowControl():setRestError(oError)
        return 
    endTry
    
    oIntegration := totvs.protheus.backoffice.apps.grr.integration.financial.FinancialIntegration():new()
    oIntegration:resendReceivable(jBody['list']) 

    oRest:setResponse({'message': 'Pending receivables without errors have been resent successfully'})
    oRest:setKeyHeaderResponse('Content-Type','application/json')

    freeObj(oIntegration)
return

//------------------------------------------------------------------
/*/{Protheus.doc} setErrorResolved
    @description Marca como resolvidos os erros dos titulos recebidos na requisicao.
    @type method
    @author guilherme.sordi@totvs.com.br
	@since 27/04/2026
    @version 12.1.2410
/*/
//-------------------------------------------------------------------
method setErrorResolved() class FinancialIntegrationController
    local jBody := self:getBody() as json
    local oIntegration as object

    try
        self:checkMandatoryFields(jBody, {'list'})
    catch oError
        FlowControl():setRestError(oError)
        return 
    endTry
    
    oIntegration := totvs.protheus.backoffice.apps.grr.integration.financial.FinancialIntegration():new()
    oIntegration:setErrorResolved(jBody['list']) 

    oRest:setResponse({'message': 'Receivables with errors have been marked as resolved successfully'})
    oRest:setKeyHeaderResponse('Content-Type','application/json')

    if oIntegration != NIL
        freeObj(oIntegration)
    endIf
return
