#include "tlpp-core.th"

namespace totvs.protheus.backoffice.controlchecklist.balancetransfer

//-------------------------------------------------------------------
/*/{Protheus.doc} BalanceTransferService
Classe de serviço, realizada instância e chamada de métodos de serviços

@author Totvs
/*/
//-------------------------------------------------------------------
class BalanceTransferService
	Data jResponse  as Json

    public method new()
    public method getInstance()
    public method getAllBalanceTransfer()
endclass

//-------------------------------------------------------------------
/*/{Protheus.doc} BalanceTransferService
Metodo construtor

@author Totvs
/*/
//-------------------------------------------------------------------
method new() class BalanceTransferService
	::jResponse := JsonObject():New()
return

//-------------------------------------------------------------------
/*/{Protheus.doc} BalanceTransferService
Responsável por instanciar a classe controller

@author Totvs
/*/
//-------------------------------------------------------------------
method getInstance() class BalanceTransferService
    static __instance As Object
    
    If ValType(__instance) == "U"
        __instance := BalanceTransferService():new()
    EndIf
return

//-------------------------------------------------------------------
/*/{Protheus.doc} getAllBalanceTransfer
Responsável por chamar a consulta e parsear o retorno no formato JSON

@author Totvs
/*/
//-------------------------------------------------------------------
method getAllBalanceTransfer(nPage as Numeric, nPageSize as Numeric) class BalanceTransferService
    Local oSettings := BalanceTransferProtheusData():getData() As Object
    
    
    Default nPage       := 1
	Default nPageSize   := 10
    
    oSettings:getAll(nPage, nPageSize)

    If oSettings:lOk
        ::jResponse := oSettings:getJSONResponse()    
    EndIf

    oSettings:DeActivate()
    FreeObj(oSettings)
return ::jResponse
