#INCLUDE "loca027.ch" 
/*/{PROTHEUS.DOC} LOCA027.PRW 
ITUP BUSINESS - TOTVS RENTAL
VALIDA SE O CONTEÚDO EXISTE NO FPA_SEQGRU DO GRID
@TYPE FUNCTION
@AUTHOR FRANK ZWARG FUGA
@SINCE 03/12/2020
@VERSION P12
@HISTORY 03/12/2020, FRANK ZWARG FUGA, FONTE PRODUTIZADO.
/*/

#INCLUDE "TOTVS.CH"

FUNCTION LOCA027(_CCONTEUDO)
LOCAL   _LRET    := .F.
LOCAL   _CSEQATU := ODLGPLA:ACOLS[ODLGPLA:NAT][ASCAN(ODLGPLA:AHEADER,{|X|ALLTRIM(X[2])=="FPA_SEQGRU" })]
LOCAL   _NX

DEFAULT _CCONTEUDO := &(READVAR())

IF _CCONTEUDO == _CSEQATU
	MSGALERT(STR0001 , STR0002)  //"O EQUIPAMENTO NÃO PODE SER SUBSTITUÍDO POR ELE MESMO!"###"GPO LOC02801.PRW"
	_LRET := .F.
ELSE
	FOR _NX := 1 TO LEN(ODLGPLA:ACOLS)
		IF ALLTRIM(ODLGPLA:ACOLS[_NX][ASCAN(ODLGPLA:AHEADER,{|X|ALLTRIM(X[2])=="FPA_SEQGRU" })]) == _CCONTEUDO
			_LRET := .T.
			EXIT
		ENDIF
	NEXT
	
	IF !_LRET
		MSGALERT(STR0003 , STR0002)  //"EQUIPAMENTO NÃO ENCONTRADO NO GRID!"###"GPO LOC02801.PRW"
		_LRET := .F.
	ENDIF
ENDIF

RETURN _LRET 
