/*/{PROTHEUS.DOC} LOCA015.PRW 
ITUP BUSINESS - TOTVS RENTAL
VERIFICA SE O USUÁRIO POSSUI UM VENDEDOR RELACIONADO
@TYPE FUNCTION
@AUTHOR FRANK ZWARG FUGA
@SINCE 03/12/2020
@VERSION P12
@HISTORY 03/12/2020, FRANK ZWARG FUGA, FONTE PRODUTIZADO.
/*/

#INCLUDE "TOTVS.CH"
FUNCTION LOCA015()
LOCAL AREASA3	:= SA3->(GETAREA()) 
LOCAL LRET		:= .T.

//Verifica usuário
SA3->(DBSETORDER(7))	// A3_FILIAL + A3_CODUSR
LRET := SA3->( DBSEEK(XFILIAL("SA3")+__CUSERID) )

SA3->(RESTAREA(AREASA3)) 

RETURN LRET 
