/*/{PROTHEUS.DOC} LOCA017.PRW  
ITUP BUSINESS - TOTVS RENTAL
@TYPE FUNCTION
@AUTHOR FRANK ZWARG FUGA
@SINCE 03/12/2020
@VERSION P12
@HISTORY 03/12/2020, FRANK ZWARG FUGA, FONTE PRODUTIZADO.
/*/

#INCLUDE "RWMAKE.CH" 
#INCLUDE "TOTVS.CH"
#INCLUDE "TOPCONN.CH"

// PONTO DE ENTRADA LOGO APÓS A CRIAÇÃO DAS LINHAS NA ZAG PARA AUTOMATIZAR OS CAMPOS
// A CADA LINHA CRIADA FAREMOS O TRATAMENTO ESPECÍFICO DOS CAMPOS DA LINHA.
// FRANK ZWARG FUGA 02/09/2020
FUNCTION LOCA017()
LOCAL ODLGPLA    := PARAMIXB[1]
LOCAL NAT1       := PARAMIXB[2]

ODLGPLA:ACOLS[NAT1][ASCAN(ODLGPLA:AHEADER,{|X|ALLTRIM(X[2])=="FPA_TPGUIM"})] := SPACE(TAMSX3("FPA_TPGUIM")[1])
ODLGPLA:ACOLS[NAT1][ASCAN(ODLGPLA:AHEADER,{|X|ALLTRIM(X[2])=="FPA_TPGUID"})] := SPACE(TAMSX3("FPA_TPGUID")[1])
ODLGPLA:ACOLS[NAT1][ASCAN(ODLGPLA:AHEADER,{|X|ALLTRIM(X[2])=="FPA_DNFRET"})] := CTOD("")
ODLGPLA:ACOLS[NAT1][ASCAN(ODLGPLA:AHEADER,{|X|ALLTRIM(X[2])=="FPA_CONPAG"})] := SPACE(TAMSX3("FPA_CONPAG")[1])

ODLGPLA:REFRESH()

RETURN .T.
