/*/{PROTHEUS.DOC} LOCA025.PRW 
ITUP BUSINESS - TOTVS RENTAL
DIÁLOGO PARA PREENCHER ALGUNS CAMPOS DA TABELA FP0
@TYPE FUNCTION
@AUTHOR FRANK ZWARG FUGA
@SINCE 03/12/2020
@VERSION P12
@HISTORY 03/12/2020, FRANK ZWARG FUGA, FONTE PRODUTIZADO.
/*/

#INCLUDE "TOTVS.CH"

FUNCTION LOCA025( CALIAS , NREG , NOPC )
LOCAL   AAREA		:= GETAREA()
LOCAL   AAREASX3	:= (LOCXCONV(1))->( GETAREA() )
LOCAL   NI
LOCAL   ODLG
LOCAL   OENCH    
LOCAL   LMEMORIA	:= .T.       
LOCAL   LCREATE		:= .T.
LOCAL   APOS		:= {000,000,100 /*ALTURA*/,200 /*LARGURA*/}        //POSIÇÃO DA ENCHOICE NA TELA
//LOCAL   ACPOENCH	:= {"FQ2_PCOLETA", "FQ2_PENTREG", "FQ2_PAVARIA", "FQ2_PCOMUNI", "FQ2_TOTAL"}		//CAMPOS QUE SERÃO MOSTRADOS NA ENCHOICE
LOCAL   ACPOENCH	:= {"FQ2_PTCOL", "FQ2_PDTCOL", "FQ2_RDTCOL", "FQ2_AHRCOL", "FQ2_PTENT", "FQ2_PDTENT", "FQ2_RDTENT", "FQ2_AHRENT", "FQ2_AVARIA", "FQ2_COMUN", "FQ2_PCOLET", "FQ2_PENTRE", "FQ2_PAVARI", "FQ2_PCOMUN", "FQ2_TOTAL" }
LOCAL   AFIELD		:= {}     
LOCAL   AFOLDER		:= {}
LOCAL   LOK			:= .F.
//PRIVATE AALTERENCH	:= {"FQ2_PCOLETA", "FQ2_PENTREG", "FQ2_PAVARIA", "FQ2_PCOMUNI"}					//HABILITA ESTES CAMPOS PARA EDIÇÃO
PRIVATE AALTERENCH	:= {"FQ2_PTCOL", "FQ2_PDTCOL", "FQ2_RDTCOL", "FQ2_AHRCOL", "FQ2_PTENT", "FQ2_PDTENT", "FQ2_RDTENT", "FQ2_AHRENT", "FQ2_AVARIA", "FQ2_COMUNI"}
/*ESTRUTURA DO VETOR AFIELD	
[1] - TITULO	
[2] - CAMPO	
[3] - TIPO	
[4] - TAMANHO	
[5] - DECIMAL	
[6] - PICTURE	
[7] - VALID	
[8] - OBRIGAT	
[9] - NIVEL	
[10]- INICIALIZADOR PADRÃO	
[11]- F3         	
[12]- WHEN	
[13]- VISUAL	
[14]- CHAVE	
[15]- BOX	
[16]- FOLDER	
[17]- NAO ALTERAVEL	
[18]- PICTVAR	            	
[19]- GATILHO*/       

	(LOCXCONV(1))->( DBSETORDER(2) )

	FOR NI := 1 TO LEN( ACPOENCH )
		IF (LOCXCONV(1))->( DBSEEK( ACPOENCH[NI] ) )
			AADD(AFIELD, {	X3TITULO(),;
							GetSx3Cache(&(LOCXCONV(2)),"X3_CAMPO"),;         
							GetSx3Cache(&(LOCXCONV(2)),"X3_TIPO"),;          
							GetSx3Cache(&(LOCXCONV(2)),"X3_TAMANHO"),;       
							GetSx3Cache(&(LOCXCONV(2)),"X3_DECIMAL"),;       
							GetSx3Cache(&(LOCXCONV(2)),"X3_PICTURE"),;       
							GetSx3Cache(&(LOCXCONV(2)),"X3_VALID"),;         
							.F.,;
							GetSx3Cache(&(LOCXCONV(2)),"X3_NIVEL"),;         
							GetSx3Cache(&(LOCXCONV(2)),"X3_RELACAO"),;       
							GetSx3Cache(&(LOCXCONV(2)),"X3_F3"),;            
							GetSx3Cache(&(LOCXCONV(2)),"X3_WHEN"),;          
							.F.,;
							.F.,;
							GetSx3Cache(&(LOCXCONV(2)),"X3_CBOX"),;          
							VAL(GetSx3Cache(&(LOCXCONV(2)),"X3_FOLDER")),;   
							.F.,;
							GetSx3Cache(&(LOCXCONV(2)),"X3_PICTVAR"),;       
							GetSx3Cache(&(LOCXCONV(2)),"X3_TRIGGER") } )     
		ENDIF
	NEXT 
		
	//XTOTAL( ACPOENCH[NI], SX3->X3_VALID)
	(LOCXCONV(1))->( RESTAREA( AAREASX3 ) )

	DEFINE MSDIALOG ODLG TITLE CCADASTRO FROM 0,0 TO /*255,400*/ 460,400 PIXEL
	//	ODLG:LMAXIMIZED := .T.

		REGTOMEMORY( CALIAS, IF(NOPC==3,.T.,.F.))

		OENCH := MSMGET():NEW(,,NOPC,/*ACRA*/,/*CLETRAS*/,/*CTEXTO*/,ACPOENCH,APOS,AALTERENCH,/*NMODELO*/,;
									/*NCOLMENS*/,/*CMENSAGEM*/, /*CTUDOOK*/,ODLG,/*LF3*/,LMEMORIA,/*LCOLUMN*/,/*CATELA*/,;
									/*LNOFOLDER*/,/*LPROPERTY*/,AFIELD, AFOLDER, LCREATE,/*LNOMDISTRETCH*/,/*CTELA*/,.t.)

		OENCH:OBOX:ALIGN := CONTROL_ALIGN_ALLCLIENT
	ACTIVATE MSDIALOG ODLG CENTERED ON INIT ENCHOICEBAR(ODLG,{|| LOK := .T., ODLG:END()},{|| ODLG:END()})

	IF LOK
		RECLOCK( CALIAS , .F. )
		FOR NI := 1 TO LEN( ACPOENCH )
			FIELDPUT( FIELDPOS( ACPOENCH[NI] ), &( "M->" + ACPOENCH[NI] ) )
		NEXT
		MSUNLOCK()
	ENDIF

	RESTAREA( AAREA )

RETURN NIL



// ======================================================================= \\
STATIC FUNCTION XTOTAL( CCAMPO, CVALID)
// ======================================================================= \\

LOCAL CRETVAL := ALLTRIM( CVALID )

	IF CCAMPO != "FQ2_TOTAL"
		CRETVAL += IIF( !EMPTY(CRETVAL), ".AND.", "" ) + "LOCA02501()"
	ENDIF

RETURN &( "{|| "+ CRETVAL +" }" )



// ======================================================================= \\
FUNCTION LOCA02501()
// ======================================================================= \\

//LOCAL   NI
LOCAL   _nRet := 0
PRIVATE XVALOR

	//M->FQ2_TOTAL := 0

	/*
	FOR NI := 1 TO LEN( AALTERENCH )
		XVALOR := &( "M->" + AALTERENCH[NI] )
		IF VALTYPE( XVALOR ) == "N"
			M->FQ2_TOTAL += XVALOR
		ENDIF
	NEXT
	*/

	_nRet := M->FQ2_PCOLET + M->FQ2_PENTRE + M->FQ2_PAVARI + M->FQ2_PCOMUN

RETURN _nRet
