Function PmsCorSX1A(aWrite)

aAdd(aWrite,{"PMR050","04","Data de valid. ate ?","¿A  Fecha validez?","To Due Date ?","mv_ch4","D",8,0,0,"G","","mv_par04","","","","31/12/2005","","","","","","","","","","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR060","01","Projeto de ?","¿De Proyecto?","From Project ?","mv_ch1","C",10,0,0,"G","","mv_par01","","","","","","","","","","","","","","","","","","","","","","","","","AF8","S","",""})
aAdd(aWrite,{"PMR060","02","Projeto ate ?","¿A  Proyecto?","To Project ?","mv_ch2","C",10,0,0,"G","","mv_par02","","","","ZZZZZZZZZZ","","","","","","","","","","","","","","","","","","","","","AF8","S","",""})
aAdd(aWrite,{"PMR060","03","Data do projeto de ?","¿De Fecha Proyecto?","From Project Date ?","mv_ch3","D",8,0,0,"G","","mv_par03","","","","01/01/2002","","","","","","","","","","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR060","04","Data do projeto ate ?","¿A  Fecha Proyecto?","To Project Date ?","mv_ch4","D",8,0,0,"G","","mv_par04","","","","31/12/2005","","","","","","","","","","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR060","05","Versao ?","¿Version?","Version ?","mv_ch5","C",2,0,0,"G","","mv_par05","","","","","","","","","","","","","","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR060","06","Filtrar niveis ?","¿Filtrar niveles?","Filter Levels ?","mv_ch6","C",20,0,0,"G","","mv_par06","","","","","","","","","","","","","","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR060","07","Data de referencia ?","¿Fecha de referencia?","Reference Date ?","MV_CH7","D",8,0,0,"G","","mv_par07","","","","","","","","","","","","","","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR070","01","Projeto de ?","¿De Proyecto?","From Project ?","mv_ch1","C",10,0,0,"G","","mv_par01","","","","","","","","","","","","","","","","","","","","","","","","","AF8","S","",""})
aAdd(aWrite,{"PMR070","02","Projeto ate ?","¿A  Proyecto?","To Project ?","mv_ch2","C",10,0,0,"G","","mv_par02","","","","ZZZZZZZZZZ","","","","","","","","","","","","","","","","","","","","","AF8","S","",""})
aAdd(aWrite,{"PMR070","03","Data do projeto de ?","¿De Periodo?","From Project Date ?","mv_ch3","D",8,0,0,"G","","mv_par03","","","","01/01/2002","","","","","","","","","","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR070","04","Data do projeto ate ?","¿A  Periodo?","To Project Date ?","mv_ch4","D",8,0,0,"G","","mv_par04","","","","31/12/2005","","","","","","","","","","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR070","05","Versao ?","¿Version?","Version ?","mv_ch5","C",2,0,0,"G","","mv_par05","","","","","","","","","","","","","","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR070","06","Filtrar niveis ?","¿Filtrar niveles?","Filter Levels ?","mv_ch6","C",20,0,0,"G","","mv_par06","","","","","","","","","","","","","","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR070","07","Filtrar fase ?","¿Filtrar fase?","Filter Phase ?","mv_ch7","C",20,0,0,"G","","mv_par07","","","","","","","","","","","","","","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR070","08","Data inicial ?","¿De Fecha?","Initial Date ?","mv_ch8","D",8,0,0,"G","","mv_par08","","","","","","","","","","","","","","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR070","09","Data final ?","¿A  Fecha?","Final Date ?","mv_ch9","D",8,0,0,"G","","mv_par09","","","","","","","","","","","","","","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR070","10","Cliente de ?","¿De Cliente?","From Customer ?","mv_cha","C",6,0,0,"G","","mv_par10","","","","","","","","","","","","","","","","","","","","","","","","","SA1","S","001",""})
aAdd(aWrite,{"PMR070","11","Loja de ?","¿De Tienda?","From Unit ?","mv_chb","C",2,0,0,"G","","mv_par11","","","","","","","","","","","","","","","","","","","","","","","","","","S","002",""})
aAdd(aWrite,{"PMR070","12","Cliente ate ?","¿A  Cliente?","To Customer ?","mv_chc","C",6,0,0,"G","","mv_par12","","","","ZZZZZZ","","","","","","","","","","","","","","","","","","","","","SA1","S","001",""})
aAdd(aWrite,{"PMR070","13","Loja ate ?","¿A  Tienda?","To Unit ?","mv_chd","C",2,0,0,"G","","mv_par13","","","","ZZ","","","","","","","","","","","","","","","","","","","","","","S","002",""})
aAdd(aWrite,{"PMR080","01","Projeto de ?","¿De Proyecto?","From Project ?","mv_ch1","C",10,0,0,"G","","mv_par01","","","","","","","","","","","","","","","","","","","","","","","","","AF8","S","",""})
aAdd(aWrite,{"PMR080","02","Projeto ate ?","¿A  Proyecto?","To Project ?","mv_ch2","C",10,0,0,"G","","mv_par02","","","","ZZZZZZZZZZ","","","","","","","","","","","","","","","","","","","","","AF8","S","",""})
aAdd(aWrite,{"PMR080","03","Data do projeto de ?","¿De Periodo?","From Project Date ?","mv_ch3","D",8,0,0,"G","","mv_par03","","","","01/01/2002","","","","","","","","","","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR080","04","Data do projeto ate ?","¿A  Periodo?","To Project Date ?","mv_ch4","D",8,0,0,"G","","mv_par04","","","","31/12/2005","","","","","","","","","","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR080","05","Versao ?","¿Version?","Version ?","mv_ch5","C",2,0,0,"G","","mv_par05","","","","","","","","","","","","","","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR080","06","Filtrar niveis ?","¿Filtrar niveles?","Filter Levels ?","mv_ch6","C",20,0,0,"G","","mv_par06","","","","","","","","","","","","","","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR080","07","Data inicial ?","¿De Fecha?","Initial Date ?","MV_CH7","D",8,0,0,"G","","mv_par07","","","","","","","","","","","","","","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR080","08","Data final ?","¿A  Fecha?","Final Date ?","MV_CH9","D",8,0,0,"G","","mv_par08","","","","","","","","","","","","","","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR080","09","Periodo ?","¿Periodo?","Period ?","MV_CH9","N",1,0,1,"C","","mv_par09","Diario","Diario","Daily","","","Semanal","Semanal","Weekly","","","Mensal","Mensual","Monthly","","","","","","","","","","","","","S","",""})
aAdd(aWrite,{"PMR080","10","Projecao do valor ?","¿Proyeccion del valor?","Value Projection ?","MV_CHA","C",1,0,1,"C","","mv_par10","Acumulado","Acumulado","Accumulated","","","Saldo","Saldo","Balance","","","","","","","","","","","","","","","","","","N","",""})
aAdd(aWrite,{"PMR100","01","Projeto de ?","¿De Proyecto?","Project from ?","mv_ch1","C",10,0,0,"G","","mv_par01","","","","","","","","","","","","","","","","","","","","","","","","","AF8","S","",""})
aAdd(aWrite,{"PMR100","02","Projeto ate ?","¿A  Proyecto?","Project to ?","mv_ch2","C",10,0,0,"G","","mv_par02","","","","ZZZZZZZZZZ","","","","","","","","","","","","","","","","","","","","","AF8","S","",""})
aAdd(aWrite,{"PMR100","03","Data do projeto de ?","¿De Fecha Proyecto?","From Project Date ?","mv_ch3","D",8,0,0,"G","","mv_par03","","","","'01/01/02'","","","","","","","","","","","","","","","","","","","","","","S","",""})

