#INCLUDE "PROTHEUS.CH"
#INCLUDE "QUICKSEARCH.CH"
#INCLUDE "TECQ004.CH"

QSSTRUCT TECQ004 DESCRIPTION STR0001 MODULE 28 // "Previsão de Materias de Implantação" 

QSMETHOD INIT QSSTRUCT TECQ004
	
	QSTABLE "TFG" JOIN "TFF" ON "TFF.TFF_COD = TFG.TFG_CODPAI" 
	QSTABLE "TFF" JOIN "TFL" ON "TFL.TFL_CODIGO = TFF.TFF_CODPAI"
	QSTABLE "TFL" JOIN "CN9" ON "CN9.CN9_NUMERO = TFL.TFL_CONTRT AND CN9_REVISA = TFL.TFL_CONREV"
	QSTABLE "TFG" LEFT JOIN "SB1" ON "SB1.B1_COD = TFG.TFG_PRODUT"
	
	// campos do SX3 e indices do SIX
	QSPARENTFIELD "TFL_CONTRT" INDEX ORDER 4 
	QSPARENTFIELD "TFG_PRODUT" INDEX ORDER 4 
	
	// campos do SX3
	QSFIELD "TFL_CONTRT","TFG_PRODUT","B1_DESC","TFG_QTDVEN"

	QSFIELD "VLRTOT" EXPRESSION "((TFG_QTDVEN * TFG_PRCVEN) - TFG_VALDES)" LABEL STR0004 ; // "Valor Total"
	FIELDS "TFG_QTDVEN", "TFG_PRCVEN", "TFG_VALDES" TYPE "N" SIZE 14 DECIMAL 2 PICTURE "@E 99,999,999,999.99"
	
	QSFIELD "TFG_PERFIM"

	QSFILTER STR0003 WHERE "CN9.CN9_SITUAC = '05' AND '"+DTOS(Date())+"' BETWEEN TFG.TFG_PERINI AND TFG.TFG_PERFIM" // "Todos" 
Return
