#Include "protheus.ch"
#include "quicksearch.ch"

QSSTRUCT GFEQ519 DESCRIPTION "Veículos no pátio" MODULE 78 

QSMETHOD INIT QSSTRUCT GFEQ519
	QSTABLE "GX3" JOIN "GX6" ON "GX6_NRMOV = GX3_NRMOV"
	QSTABLE "GX3" JOIN "GU3" ON "GX3_CDEMIT = GU3_CDEMIT"
	QSTABLE "GX6" JOIN "GU8" ON "GU8_CDVEIC = GX6_CDVEIC"
	
	//-- campos do SX3 e indices do SIX
	QSPARENTFIELD 'GU8_PLACA' INDEX ORDER 2 LABEL 'Placa'
	QSPARENTFIELD 'GU3_NMEMIT' INDEX ORDER 2 LABEL 'Transportador'
	
	//-- campos do SX3
	QSFIELD 'GU8_PLACA'
	QSFIELD 'GX3_NRMOV'
	QSFIELD 'GX3_CDOPER' LABEL 'Operação'
	QSFIELD 'GU3_NMEMIT' LABEL 'Transportador'
	
	//-- acoes do menudef, MVC ou qualquer rotina
	//QSACTION MENUDEF "DLGA320VIS" OPERATION 2 LABEL "Visualizar"
	QSACTION MENUDEF "GFEC510" OPERATION 2 LABEL "Visualizar"
	QSFILTER "Em andamento"	WHERE "GX3_SIT != '5' AND GX3_SIT != '6'"
Return