#INCLUDE "PROTHEUS.CH"
#INCLUDE "FWMVCDEF.CH"
#INCLUDE "TAFA214.CH"
//-------------------------------------------------------------------
/*/{Protheus.doc} TAFA214
Cadastro MVC de Natureza das Rubricas da Folha de Pagamento 
Tabela 03

@author Anderson Costa
@since 06/08/2013
@version 1.0

/*/ 
//-------------------------------------------------------------------
Function TAFA214()

	Local oBrw := FWmBrowse():New()

	oBrw:SetDescription(STR0001)    //"Cadastro da Natureza das Rubricas da Folha de Pagamento"
	oBrw:SetAlias( 'C89')
	C89->(dbSetOrder(2))
	oBrw:SetMenuDef( 'TAFA214' )
	oBrw:Activate()

Return
//-------------------------------------------------------------------
/*/{Protheus.doc} MenuDef
Funcao generica MVC com as opcoes de menu

@author Anderson Costa
@since 06/08/2013
@version 1.0
/*/
//-------------------------------------------------------------------
Static Function MenuDef()

Return XFUNMnuTAF( "TAFA214" )

//-------------------------------------------------------------------
/*/{Protheus.doc} ModelDef
Funcao generica MVC do model

@return oModel - Objeto do Modelo MVC

@author Anderson Costa
@since 06/08/2013
@version 1.0
/*/
//-------------------------------------------------------------------
Static Function ModelDef()

	Local oStruC89 := FWFormStruct( 1, 'C89' )
	Local oModel   := MPFormModel():New('TAFA214' )

	oModel:AddFields('MODEL_C89', /*cOwner*/, oStruC89)
	oModel:GetModel('MODEL_C89'):SetPrimaryKey({'C89_FILIAL','C89_ID'})

Return oModel
//-------------------------------------------------------------------
/*/{Protheus.doc} ViewDef
Funcao generica MVC do View

@return oView - Objeto da View MVC

@author Anderson Costa
@since 06/08/2013
@version 1.0
/*/
//-------------------------------------------------------------------
Static Function ViewDef()

	Local oModel   := FWLoadModel( 'TAFA214' )
	Local oStruC89 := FWFormStruct( 2, 'C89' )
	Local oView    := FWFormView():New()

	oView:SetModel( oModel )
	oView:AddField( 'VIEW_C89', oStruC89, 'MODEL_C89' )

	oView:EnableTitleView( 'VIEW_C89', STR0001 )    //"Cadastro da Natureza das Rubricas da Folha de Pagamento"
	oView:CreateHorizontalBox( 'FIELDSC89', 100 )
	oView:SetOwnerView( 'VIEW_C89', 'FIELDSC89' )

Return oView

//-------------------------------------------------------------------
/*/{Protheus.doc} FAtuCont

Rotina para carga e atualização da tabela autocontida.

@Param		nVerEmp	-	Versão corrente na empresa
			nVerAtu	-	Versão atual ( passado como referência )

@Return	aRet		-	Array com estrutura de campos e conteúdo da tabela

@Author	Felipe de Carvalho Seolin
@Since		24/11/2015
@Version	1.0
/*/
//-------------------------------------------------------------------
Static Function FAtuCont( nVerEmp as numeric, nVerAtu as numeric )

	Local aBody   as array
	Local aHeader as array
	Local aRet    as array

	aBody   := {}
	aHeader := {}
	aRet    := {}
	nVerAtu := 1033.80

	If nVerEmp < nVerAtu

		aAdd( aHeader, "C89_FILIAL" )
		aAdd( aHeader, "C89_ID" 	)
		aAdd( aHeader, "C89_CODIGO" )
		aAdd( aHeader, "C89_NOMRUB" )
		aAdd( aHeader, "C89_DESCRI" )
		aAdd( aHeader, "C89_VALIDA" )
		aAdd( aHeader, "C89_ALTCON" )

		aAdd(aBody, { "", "000001", "1000", "SALÁRIO, VENCIMENTO, SOLDO OU SUBSÍDIO", "CORRESPONDE AO SALÁRIO BÁSICO CONTRATUAL DO EMPREGADO CONTRATADO DE ACORDO COM A CLT E O VENCIMENTO MENSAL DO SERVIDOR PÚBLICO E DO MILITAR", "20210509" } )
		aAdd(aBody, { "", "000002", "1002", "DESCANSO SEMANAL REMUNERADO - DSR", "VALOR CORRESPONDENTE A UM DIA DE TRABALHO INCIDENTE SOBRE AS VERBAS DE NATUREZA VARIÁVEL, TAIS COMO: HORAS EXTRAS, ADICIONAL NOTURNO, PRODUÇÃO, COMISSÃO, ETC", "20240422", 1033.45 } )
		aAdd(aBody, { "", "000003", "1003", "HORAS EXTRAORDINÁRIAS", "VALOR CORRESPONDENTE A HORA EXTRAORDINÁRIA DE TRABALHO, ACRESCIDO DE PERCENTUAL DE NO MÍNIMO 50%", "" } )
		aAdd(aBody, { "", "000004", "1004", "HORAS EXTRAORDINÁRIAS - INDENIZAÇÃO DE BANCO DE HORAS", "VALOR CORRESPONDENTE A PAGAMENTO DAS HORAS EXTRAORDINÁRIAS, INICIALMENTE DESTINADAS PARA O BANCO DE HORAS E QUE NÃO FORAM COMPENSADAS", "20230208", 1033.16 } )
		aAdd(aBody, { "", "000005", "1005", "DIREITO DE ARENA", "VALORES RELATIVOS A DIREITO DE ARENA DECORRENTE DO ESPETÁCULO, DEVIDOS AO ATLETA", "" } )
		aAdd(aBody, { "", "000006", "1007", "LUVAS E PREMIAÇÕES", "VALORES CORRESPONDENTES A PRÊMIOS E LUVAS, DEVIDOS AO ATLETA", "" } )
		aAdd(aBody, { "", "000007", "1009", "SALÁRIO-FAMÍLIA - COMPLEMENTO", "VALOR EXCEDENTE AO DO FIXADO PELA PREVIDÊNCIA SOCIAL PARA O SALÁRIO-FAMÍLIA", "" } )
		aAdd(aBody, { "", "000008", "1010", "SALÁRIO IN NATURA - PAGOS EM BENS OU SERVIÇOS", "SALÁRIO IN NATURA, TAMBÉM CONHECIDO POR SALÁRIO UTILIDADE, CORRESPONDENTE A REMUNERAÇÕES PAGAS EM BENS OU SERVIÇOS", "" } )
		aAdd(aBody, { "", "000009", "1011", "SOBREAVISO E PRONTIDÃO", "VALOR CORRESPONDENTE A UM PERCENTUAL DA HORA NORMAL DE TRABALHO", "" } )
		aAdd(aBody, { "", "000010", "1020", "FÉRIAS", "VALOR CORRESPONDENTE À REMUNERAÇÃO A QUE FAZ JUS NA ÉPOCA DA CONCESSÃO DAS FÉRIAS E O ADICIONAL CONSTITUCIONAL A QUE O TRABALHADOR ADQUIRIU DIREITO, INCLUSIVE O ADIANTAMENTO DE FÉRIAS, QUANDO PAGAS ANTECIPADAMENTE – NESSA OPÇÃO DEVE SER CLASSIFICADO TAMBÉM O VALOR PAGO MENSALMENTE AO TRABALHADOR AVULSO E AO EMPREGADO COM CONTRATO DE TRABALHO INTERMITENTE, A TÍTULO DE FÉRIAS", "20230430", 1033.16  } )
		aAdd(aBody, { "", "000011", "1021", "FÉRIAS - ABONO OU GRATIFICAÇÃO DE FÉRIAS SUPERIOR A 20 DIAS", "REMUNERAÇÃO A TÍTULO DE ABONO DE FÉRIAS, DESDE QUE EXCEDENTE A 20 (VINTE) DIAS DO SALÁRIO E CONCEDIDO EM VIRTUDE DE CLÁUSULA CONTRATUAL, DO REGULAMENTO DA EMPRESA", "20230430", 1033.16  } )
		aAdd(aBody, { "", "000012", "1022", "FÉRIAS - ABONO OU GRATIFICAÇÃO DE FÉRIAS NÃO EXCEDENTE A 20 DIAS", "REMUNERAÇÃO A TÍTULO DE ABONO DE FÉRIAS, DESDE QUE NÃO EXCEDENTE A 20 (VINTE) DIAS DO SALÁRIO E CONCEDIDO EM VIRTUDE DE CLÁUSULA CONTRATUAL, DO REGULAMENTO DA EMPRESA", "20230208", 1033.16  } )
		aAdd(aBody, { "", "000013", "1023", "FÉRIAS - ABONO PECUNIÁRIO", "VALOR CORRESPONDENTE A CONVERSÃO EM DINHEIRO DE PARTE DOS DIAS DE FÉRIAS A QUE O TRABALHADOR ADQUIRIU DIREITO, INCLUSIVE O ADICIONAL CONSTITUCIONAL", "" } )
		aAdd(aBody, { "", "000014", "1024", "FÉRIAS - O DOBRO NA VIGÊNCIA DO CONTRATO", "VALOR CORRESPONDENTE A REMUNERAÇÃO A QUE FAZ JUS NA ÉPOCA DA CONCESSÃO DAS FÉRIAS, CONCEDIDAS APÓS O PRAZO DE CONCESSÃO, INCLUSIVE O ADICIONAL CONSTITUCIONAL", "" } )
		aAdd(aBody, { "", "000015", "1040", "LICENÇA-PRÊMIO", "VALOR RELATIVO A LICENÇA-PRÊMIO, EM DECORRÊNCIA DE AFASTAMENTO DO TRABALHO", "" } )
		aAdd(aBody, { "", "000016", "1041", "LICENÇA-PRÊMIO INDENIZADA", "VALOR CORRESPONDENTE À CONVERSÃO EM DINHEIRO DA LICENÇA-PRÊMIO", "" } )
		aAdd(aBody, { "", "000017", "1099", "OUTRAS VERBAS SALARIAIS", "OUTRAS VERBAS SALARIAIS NÃO PREVISTAS NOS ITENS ANTERIORES", "20210509" } )
		aAdd(aBody, { "", "000018", "1201", "ADICIONAL DE FUNÇÃO / CARGO CONFIANÇA", "ADICIONAL OU GRATIFICAÇÃO CONCEDIDA EM VIRTUDE DE CARGO OU FUNÇÃO DE CONFIANÇA", "" } )
		aAdd(aBody, { "", "000019", "1202", "ADICIONAL DE INSALUBRIDADE", "ADICIONAL POR SERVIÇOS EM CONDIÇÕES DE INSALUBRIDADE", "" } )
		aAdd(aBody, { "", "000020", "1203", "ADICIONAL DE PERICULOSIDADE", "ADICIONAL POR SERVIÇOS EM CONDIÇÕES PERIGOSAS", "" } )
		aAdd(aBody, { "", "000021", "1204", "ADICIONAL DE TRANSFERÊNCIA", "ADICIONAL EM RAZÃO DE TRANSFERÊNCIA DE TRABALHADOR, ENQUANTO DURAR A TRANSFERÊNCIA", "" } )
		aAdd(aBody, { "", "000022", "1205", "ADICIONAL NOTURNO", "ADICIONAL POR TRABALHO EM HORÁRIO NOTURNO", "" } )
		aAdd(aBody, { "", "000023", "1206", "ADICIONAL POR TEMPO DE SERVIÇO", "ADICIONAL EM VIRTUDE DO TEMPO DE SERVIÇO (ANUÊNIO, QUINQUÊNIO, ETC.)", "" } )
		aAdd(aBody, { "", "000024", "1207", "COMISSÕES, PORCENTAGENS, PRODUÇÃO", "VALOR CORRESPONDENTE A CONTRAPRESTAÇÃO DE SERVIÇO, NORMALMENTE BASEADA EM UM PERCENTUAL SOBRE AS VENDAS TOTAIS DESSE TRABALHADOR", "" } )
		aAdd(aBody, { "", "000025", "1208", "GUELTAS OU GORJETAS - REPASSADAS POR FORNECEDORES OU CLIENTES", "VALORES PAGOS DIRETAMENTE POR FORNECEDORES A TRABALHADOR A TÍTULO DE INCENTIVOS DE VENDAS (GUELTAS) OU POR CLIENTES A TÍTULO DE RECOMPENSA POR BONS SERVIÇOS PRESTADOS (GORJETAS)", "" } )
		aAdd(aBody, { "", "000026", "1209", "GUELTAS OU GORJETAS - REPASSADAS PELO EMPREGADOR", "VALORES PAGOS RELATIVOS A GUELTAS OU GORJETAS, POR MEIO DE REPASSE AO EMPREGADOR", "" } )
		aAdd(aBody, { "", "000027", "1210", "GRATIFICAÇÃO POR ACORDO OU CONVENÇÃO COLETIVA", "VERBA ESTABELECIDA EM ACORDO OU CONVENÇÃO COLETIVA DE TRABALHO", "" } )
		aAdd(aBody, { "", "000028", "1211", "GRATIFICAÇÕES", "VERBA NÃO ESTABELECIDA EM ACORDO OU CONVENÇÃO COLETIVA, MAS PAGA PARA O EMPREGADO EM DECORRÊNCIA DE AJUSTE ENTRE AS PARTES OU POR LIBERALIDADE DO EMPREGADOR, COMO POR EXEMPLO PRODUTIVIDADE, ASSIDUIDADE, ETC.", "" } )
		aAdd(aBody, { "", "000029", "1213", "GRATIFICAÇÕES OU OUTRAS VERBAS DE NATUREZA TRANSITÓRIA", "ÓRGÃO PÚBLICO - PARCELAS REMUNERATÓRIAS VINCULADAS À ATIVIDADE CUJO RECEBIMENTO DEPENDA DE AVALIAÇÃO DE DESEMPENHO OU DETERMINADAS CONDIÇÕES", "" } )
		aAdd(aBody, { "", "000030", "1215", "ADICIONAL DE UNIDOCÊNCIA", "ADICIONAL DE UNIDOCÊNCIA PARA PROFESSORES DE 1ª A 4ª SÉRIE", "" } )
		aAdd(aBody, { "", "000031", "1230", "REMUNERAÇÃO DO DIRIGENTE SINDICAL", "REMUNERAÇÃO PAGA AO TRABALHADOR AFASTADO, DURANTE O EXERCÍCIO DA ATIVIDADE SINDICAL", "" } )
		aAdd(aBody, { "", "000032", "1299", "OUTROS ADICIONAIS", "VALORES RELATIVOS A OUTROS ADICIONAIS NÃO PREVISTOS NOS ITENS ANTERIORES", "20210509" } )
		aAdd(aBody, { "", "000033", "1300", "PLR - PARTICIPAÇÃO EM LUCROS OU RESULTADOS", "VALOR CORRESPONDENTE A PARTICIPAÇÃO EM LUCROS OU RESULTADOS DA EMPRESA, DE ACORDO COM LEI ESPECÍFICA", "" } )
		aAdd(aBody, { "", "000034", "1350", "BOLSA DE ESTUDO - ESTAGIÁRIO", "VALOR DEVIDO AO ESTAGIÁRIO EM ATIVIDADES PRÁTICAS DE COMPLEMENTAÇÃO DO CURRÍCULO ESCOLAR, INCLUSIVE OS VALORES PAGOS A TÍTULO DE RECESSO REMUNERADO - LEI Nº 11.788 DE 25/09/2008", "" } )
		aAdd(aBody, { "", "000035", "1351", "BOLSA DE ESTUDO - MÉDICO RESIDENTE", "BOLSA DE ESTUDO AO MÉDICO RESIDENTE", "" } )
		aAdd(aBody, { "", "000036", "1352", "BOLSA DE ESTUDO OU PESQUISA", "REMUNERAÇÃO A PROFESSORES, PESQUISADORES E DEMAIS PROFISSIONAIS COM A FINALIDADE DE ESTUDOS OU PESQUISA, EXCETO PAGAMENTOS A ESTAGIÁRIO E MÉDICO-RESIDENTE", "" } )
		aAdd(aBody, { "", "000037", "1401", "ABONO", "QUALQUER ABONO CONCEDIDO DE FORMA ESPONTÂNEA OU EM VIRTUDE DE ACORDO OU CONVENÇÃO COLETIVA, NORMA, ETC", "" } )
		aAdd(aBody, { "", "000038", "1402", "ABONO PIS / PASEP", "ABONO E/OU RENDIMENTO DO PIS / PASEP REPASSADO PELO EMPREGADOR OU ÓRGÃO PÚBLICO", "" } )
		aAdd(aBody, { "", "000039", "1403", "ABONO LEGAL", "AS IMPORTÂNCIAS RECEBIDAS A TÍTULO DE GANHOS EVENTUAIS E OS ABONOS EXPRESSAMENTE DESVINCULADOS DO SALÁRIO, POR FORÇA DA LEI", "" } )
		aAdd(aBody, { "", "000040", "1404", "AUXÍLIO BABÁ", "VALOR RELATIVO A REEMBOLSO DE DESPESAS COM BABÁ, LIMITADO AO MENOR SALÁRIO DE CONTRIBUIÇÃO MENSAL E CONDICIONADO À COMPROVAÇÃO DO REGISTRO NA CARTEIRA DE TRABALHO E PREVIDÊNCIA SOCIAL DA EMPREGADA", "" } )
		aAdd(aBody, { "", "000041", "1405", "ASSISTÊNCIA MÉDICA", "VALOR PAGO DIRETAMENTE AO TRABALHADOR A TÍTULO DE ASSISTÊNCIA MÉDICA OU ODONTOLÓGICA, INCLUSIVE O REEMBOLSO DE DESPESAS COM MEDICAMENTOS, ÓCULOS, APARELHOS ORTOPÉDICOS, DESPESAS MÉDICO-HOSPITALARES E OUTRAS SIMILARES", "" } )
		aAdd(aBody, { "", "000042", "1406", "AUXÍLIO-CRECHE", "O REEMBOLSO CRECHE PAGO EM CONFORMIDADE COM A LEGISLAÇÃO TRABALHISTA, OBSERVADO O LIMITE MÁXIMO DE 6 (SEIS) ANOS DE IDADE DA CRIANÇA, QUANDO DEVIDAMENTE COMPROVADAS AS DESPESAS REALIZADAS. CASO HAJA PREVISÃO EM ACORDO COLETIVO DA CATEGORIA", "" } )
		aAdd(aBody, { "", "000043", "1407", "AUXÍLIO-EDUCAÇÃO", "VALOR RELATIVO A PLANO EDUCACIONAL, OU BOLSA DE ESTUDO, QUE VISE À EDUCAÇÃO BÁSICA DE TRABALHADORES E SEUS DEPENDENTES E, DESDE QUE VINCULADA ÀS ATIVIDADES DESENVOLVIDAS PELA EMPRESA, À EDUCAÇÃO PROFISSIONAL E TECNOLÓGICA DE TRABALHADORES", "" } )
		aAdd(aBody, { "", "000044", "1409", "SALÁRIO-FAMÍLIA", "VALOR DO SALÁRIO-FAMÍLIA, CONFORME LIMITE LEGAL, EM VIRTUDE DO NÚMERO DE FILHOS MENORES DE 14 ANOS, OU INVÁLIDOS DE QUALQUER IDADE", "20240121", 1033.37 } )
		aAdd(aBody, { "", "000045", "1410", "AUXÍLIO - LOCAIS DE DIFÍCIL ACESSO", "VALOR CORRESPONDENTE A TRANSPORTE, HABITAÇÃO E ALIMENTAÇÃO FORNECIDO AO TRABALHADOR CONTRATADO PARA PRESTAR SERVIÇO EM LOCALIDADE DISTANTE DA SUA RESIDÊNCIA, EM CANTEIRO DE OBRAS OU LOCAL QUE, POR FORÇA DA ATIVIDADE, EXIJA DESLOCAMENTO E ESTADA", "" } )
		aAdd(aBody, { "", "000046", "1601", "AJUDA DE CUSTO - AERONAUTA", "ADICIONAL MENSAL RECEBIDOS PELO AERONAUTA NOS TERMOS DA LEI Nº 5.929, DE 30 DE OUTUBRO DE 1973", "" } )
		aAdd(aBody, { "", "000047", "1602", "AJUDA DE CUSTO DE TRANSFERÊNCIA", "AJUDA DE CUSTO EM PARCELA ÚNICA, EM RAZÃO DE TRANSFERÊNCIA DE LOCAL DE TRABALHO", "" } )
		aAdd(aBody, { "", "000048", "1620", "RESSARCIMENTO DE DESPESAS PELO USO DE VEÍCULO PRÓPRIO", "RESSARCIMENTO DE DESPESAS AO TRABALHADOR, PELA UTILIZAÇÃO DE VEÍCULO", "" } )
		aAdd(aBody, { "", "000049", "1621", "RESSARCIMENTO DE DESPESAS DE VIAGEM, EXCETO DESPESAS COM VEÍCULOS", "RESSARCIMENTO DE DESPESAS PAGAS COM RECURSOS DO TRABALHADOR EM VIAGENS A TRABALHO", "" } )
		aAdd(aBody, { "", "000050", "1629", "RESSARCIMENTO DE OUTRAS DESPESAS", "RESSARCIMENTO DE OUTRAS DESPESAS PAGAS PELO TRABALHADOR, NÃO PREVISTAS NOS ITENS ANTERIORES", "20210509" } )
		aAdd(aBody, { "", "000051", "1651", "DIÁRIAS DE VIAGEM - ATÉ 50% DO SALÁRIO", "DIÁRIAS DE VIAGEM AO TRABALHADOR, DESDE QUE NÃO EXCEDA A 50% DO SEU SALÁRIO-BASE MENSAL", "20180430" } ) // LAYOUT 2.4.02
		aAdd(aBody, { "", "000052", "1652", "DIÁRIAS DE VIAGEM - ACIMA DE 50% DO SALÁRIO", "DIÁRIAS DE VIAGEM SUPERIOR A 50% DO SALÁRIO-BASE MENSAL", "20180430" } ) // LAYOUT 2.4.02
		aAdd(aBody, { "", "000053", "1801", "ALIMENTAÇÃO", "AUXÍLIO-ALIMENTAÇÃO", "20210630" } )
		aAdd(aBody, { "", "000054", "1802", "ETAPAS (MARÍTIMOS)", "AUXÍLIO-ALIMENTAÇÃO AO TRABALHADOR MARÍTIMO", "" } )
		aAdd(aBody, { "", "000055", "1805", "MORADIA", "AUXÍLIO-MORADIA", "" } )
		aAdd(aBody, { "", "000056", "1810", "TRANSPORTE", "AUXÍLIO-TRANSPORTE", "20210718" } )
		aAdd(aBody, { "", "000057", "2501", "PRÊMIOS", "LIBERALIDADES CONCEDIDAS PELO EMPREGADOR EM FORMA DE BENS, SERVIÇOS OU VALOR EM DINHEIRO A EMPREGADO OU A GRUPO DE EMPREGADOS, EM RAZÃO DE DESEMPENHO SUPERIOR AO ORDINARIAMENTE ESPERADO NO EXERCÍCIO DE SUAS ATIVIDADES", "" } ) // LAYOUT 2.4.02 //NT 11/2019
		aAdd(aBody, { "", "000058", "2901", "EMPRÉSTIMOS", "EMPRÉSTIMOS AO TRABALHADOR PARA POSTERIOR DESCONTO", "" } )
		aAdd(aBody, { "", "000059", "2902", "VESTUÁRIO E EQUIPAMENTOS", "VALOR CORRESPONDENTE A VESTUÁRIOS, EQUIPAMENTOS E OUTROS ACESSÓRIOS FORNECIDOS AO TRABALHADOR E UTILIZADOS NO LOCAL DE TRABALHO PARA PRESTAÇÃO DOS RESPECTIVOS SERVIÇOS", "20210731" } )
		aAdd(aBody, { "", "000060", "2920", "REEMBOLSOS DIVERSOS", "VALOR RELATIVO A REEMBOLSOS DIVERSOS REFERENTES A DESCONTOS INDEVIDOS EFETUADOS EM COMPETÊNCIAS ANTERIORES", "20210731" } )
		aAdd(aBody, { "", "000061", "2930", "INSUFICIÊNCIA DE SALDO", "VALOR LANÇADO EM FOLHA DE PAGAMENTO PARA COBERTURA DE EXCESSO DE DESCONTOS EM RELAÇÃO A VENCIMENTOS, TANTO O VALOR DO VENCIMENTO NO MÊS EM QUE HOUVER A INSUFICIÊNCIA DE SALDO, COMO O RESPECTIVO DESCONTO NO(S) MÊS(ES) POSTERIORES", "" } )
		aAdd(aBody, { "", "000062", "3501", "REMUNERAÇÃO POR PRESTAÇÃO DE SERVIÇOS", "REMUNERAÇÃO (INCLUSIVE ADIANTAMENTOS) A CONTRIBUINTES INDIVIDUAIS, INCLUSIVE HONORÁRIOS, EM TRABALHOS DE NATUREZA EVENTUAL E SEM VÍNCULO TRABALHISTA", "" } )
		aAdd(aBody, { "", "000064", "3505", "RETIRADAS (PRÓ-LABORE) DE DIRETORES EMPREGADOS", "PRÓ-LABORE OU RETIRADA (REMUNERAÇÃO) A DIRETORES EMPREGADOS (CLT)", "" } )
		aAdd(aBody, { "", "000065", "3506", "RETIRADAS (PRÓ-LABORE) DE DIRETORES NÃO EMPREGADOS", "PRÓ-LABORE OU RETIRADA (REMUNERAÇÃO) A DIRETORES NÃO EMPREGADOS", "" } )
		aAdd(aBody, { "", "000066", "3508", "RETIRADAS (PRÓ-LABORE) DE PROPRIETÁRIOS OU SÓCIOS", "PRÓ-LABORE OU RETIRADA (REMUNERAÇÃO) A PROPRIETÁRIOS OU SÓCIOS DA EMPRESA", "" } )
		aAdd(aBody, { "", "000067", "3509", "HONORÁRIOS A CONSELHEIROS", "VALOR CORRESPONDENTE A HONORÁRIOS PAGOS A MEMBROS DE CONSELHO", "" } )
		aAdd(aBody, { "", "000068", "3520", "REMUNERAÇÃO DE COOPERADO", "REMUNERAÇÃO A COOPERADO VINCULADO A COOPERATIVA DE TRABALHO", "" } )
		aAdd(aBody, { "", "000069", "4010", "COMPLEMENTAÇÃO SALARIAL DE AUXÍLIO-DOENÇA", "COMPLEMENTAÇÃO SALARIAL DE AUXÍLIO-DOENÇA, EXTENSIVA À TOTALIDADE DOS TRABALHADORES", "" } )
		aAdd(aBody, { "", "000070", "4050", "SALÁRIO MATERNIDADE", "REMUNERAÇÃO MENSAL DA TRABALHADORA EMPREGADA DURANTE A LICENÇA MATERNIDADE, QUANDO PAGA PELO CONTRATANTE OU ÓRGÃO PÚBLICO", "" } )
		aAdd(aBody, { "", "000071", "4051", "SALÁRIO MATERNIDADE - 13° SALÁRIO", "VALOR CORRESPONDENTE AO 13° SALÁRIO PAGO PELO CONTRATANTE OU ÓRGÃO PÚBLICO, NO PERÍODO DE LICENÇA MATERNIDADE", "" } )
		aAdd(aBody, { "", "000072", "5001", "13º SALÁRIO", "VALOR RELATIVO AO 13° SALÁRIO DE TRABALHADOR, INCLUSIVE AS MÉDIAS DE 13° SALÁRIO (HORAS EXTRAS, ADICIONAL NOTURNO, ETC.), EXCETO SE RELATIVO À PRIMEIRA PARCELA OU SE PAGO EM RESCISÃO CONTRATUAL – NESSA OPÇÃO DEVE SER CLASSIFICADO TAMBÉM O VALOR PAGO MENSALMENTE AO TRABALHADOR AVULSO E AO EMPREGADO COM CONTRATO DE TRABALHO INTERMITENTE, A TÍTULO DE 13° SALÁRIO", "" } )
		aAdd(aBody, { "", "000073", "5005", "13° SALÁRIO COMPLEMENTAR", "VALOR DO 13° SALÁRIO COMPLEMENTAR RELATIVO A DIFERENÇAS APURADAS NÃO CONSIDERADAS NA FOLHA DE FECHAMENTO DO 13° SALÁRIO", "" } )
		aAdd(aBody, { "", "000074", "5501", "ADIANTAMENTO DE SALÁRIO", "VALOR RELATIVO A ADIANTAMENTO, ANTECIPAÇÃO OU PAGAMENTO PARCIAL DE FOLHA DE SALÁRIOS", "" } )
		aAdd(aBody, { "", "000075", "5504", "13º SALÁRIO - ADIANTAMENTO", "VALOR RELATIVO A ADIANTAMENTO DO 13° SALÁRIO", "" } )
		aAdd(aBody, { "", "000076", "5510", "ADIANTAMENTO DE BENEFÍCIOS PREVIDENCIÁRIOS", "VALOR RELATIVO A ADIANTAMENTO DE BENEFÍCIOS A SEREM PAGOS PELA PREVIDÊNCIA SOCIAL OFICIAL", "" } )
		aAdd(aBody, { "", "000077", "6000", "SALDO DE SALÁRIOS NA RESCISÃO CONTRATUAL", "VALOR CORRESPONDENTE AOS DIAS TRABALHADOS NO MÊS DA RESCISÃO CONTRATUAL", "" } )
		aAdd(aBody, { "", "000078", "6001", "13º SALÁRIO RELATIVO AO AVISO-PRÉVIO INDENIZADO", "VALOR CORRESPONDENTE AO 13° SALÁRIO INCIDENTE SOBRE O AVISO-PRÉVIO INDENIZADO", "" } )
		aAdd(aBody, { "", "000079", "6002", "13° SALÁRIO PROPORCIONAL NA RESCISÃO", "VALOR CORRESPONDENTE AO 13° SALÁRIO PROPORCIONAL PAGO NA RESCISÃO DO CONTRATO DE TRABALHO, EXCETO O PAGO SOBRE O AVISO-PRÉVIO INDENIZADO", "" } )
		aAdd(aBody, { "", "000080", "6003", "INDENIZAÇÃO COMPENSATÓRIA DO AVISO-PRÉVIO", "VALOR DA MAIOR REMUNERAÇÃO DO TRABALHADOR, CORRESPONDENTE AO NÚMERO DE DIAS RELATIVO AO AVISO PRÉVIO, CALCULADO DE ACORDO COM O TEMPO DE SERVIÇO DO EMPREGADO", "" } )
		aAdd(aBody, { "", "000081", "6004", "FÉRIAS - O DOBRO NA RESCISÃO", "VALOR CORRESPONDENTE A REMUNERAÇÃO A QUE FAZ JUS A ÉPOCA DA RESCISÃO CONTRATUAL, CORRESPONDENTE A FÉRIAS NÃO CONCEDIDAS NO PRAZO LEGAL, INCLUSIVE O ADICIONAL CONSTITUCIONAL", "" } )
		aAdd(aBody, { "", "000082", "6006", "FÉRIAS PROPORCIONAIS", "VALOR CORRESPONDENTE A 1/12 AVOS DA REMUNERAÇÃO A QUE FAZ JUS A ÉPOCA DA RESCISÃO CONTRATUAL, FRAÇÃO SUPERIOR A 14 DIAS POR MÊS DE TRABALHO E A PROJEÇÃO DO AVISO-PRÉVIO INDENIZADO, INCLUSIVE O ADICIONAL CONSTITUCIONAL", "" } )
		aAdd(aBody, { "", "000083", "6007", "FÉRIAS VENCIDAS NA RESCISÃO", "VALOR CORRESPONDENTE A REMUNERAÇÃO A QUE FAZ JUS A ÉPOCA DA RESCISÃO CONTRATUAL, CORRESPONDENTE A FÉRIAS VENCIDAS, MAS DENTRO DO PRAZO CONCESSIVO, INCLUSIVE O ADICIONAL CONSTITUCIONAL", "" } )
		aAdd(aBody, { "", "000084", "6101", "INDENIZAÇÃO COMPENSATÓRIA - MULTA RESCISÓRIA 20 OU 40% (CF/88)", "VALOR CORRESPONDENTE À INDENIZAÇÃO POR DEMISSÃO SEM JUSTA CAUSA, POR CULPA RECÍPROCA OU FORÇA MAIOR (AMBAS RECONHECIDAS PELA JUSTIÇA DO TRABALHO), POR ACORDO ENTRE EMPREGADO E EMPREGADOR OU POR EXTINÇÃO DO CONTRATO DE TRABALHO INTERMITENTE, QUANDO DA RESCISÃO DO CONTRATO DE TRABALHO", "20201123" } ) // LAYOUT 2.4.02
		aAdd(aBody, { "", "000085", "6102", "INDENIZAÇÃO DO ART. 9º LEI Nº 7.238/84", "VALOR CORRESPONDENTE A INDENIZAÇÃO QUANDO A DISPENSA OCORRER SEM JUSTA CAUSA DENTRO DOS TRINTA DIAS QUE ANTECEDEM A DATA BASE", "" } )
		aAdd(aBody, { "", "000086", "6103", "INDENIZAÇÃO DO ART. 14 DA LEI Nº 5.889, DE 8 DE JUNHO DE 1973", "VALOR CORRESPONDENTE A INDENIZAÇÃO DO TEMPO DE SERVIÇO AO SAFRISTA, IMPORTÂNCIA CORRESPONDENTE A 1/12 (UM DOZE AVOS) DO SALÁRIO MENSAL, POR MÊS DE SERVIÇO OU FRAÇÃO SUPERIOR A 14 (QUATORZE) DIAS", "" } )
		aAdd(aBody, { "", "000087", "6104", "INDENIZAÇÃO DO ART. 479 DA CLT", "VALOR CORRESPONDENTE A METADE DA REMUNERAÇÃO DEVIDA ATE O TERMINO DO CONTRATO A PRAZO DETERMINADO EM CASO DE RESCISÃO ANTECIPADA", "" } )
		aAdd(aBody, { "", "000088", "6105", "INDENIZAÇÃO RECEBIDA A TÍTULO DE INCENTIVO A DEMISSÃO", "VALOR CORRESPONDENTE A INCENTIVO A DEMISSÃO EM PROGRAMAS DE DEMISSÃO VOLUNTÁRIA - PDV", "" } )
		aAdd(aBody, { "", "000089", "6106", "MULTA DO ART. 477 DA CLT", "VALOR DEVIDO AO TRABALHADOR POR ATRASO NO PAGAMENTO DE RESCISÃO DO CONTRATO DE TRABALHO (ART. 477 DA CLT, § 8º)", "" } )
		aAdd(aBody, { "", "000090", "6107", "INDENIZAÇÃO POR QUEBRA DE ESTABILIDADE", "VALOR CORRESPONDENTE A INDENIZAÇÃO POR DESLIGAMENTO DURANTE PERÍODO DE ESTABILIDADE LEGAL, OU ESTABILIDADE DERIVADA DE ACORDO OU CONVENÇÃO COLETIVA DE TRABALHO", "" } )
		aAdd(aBody, { "", "000091", "6129", "OUTRAS INDENIZAÇÕES", "VALOR CORRESPONDENTE A OUTRAS INDENIZAÇÕES PREVISTAS EM LEIS OU EM INSTRUMENTOS COLETIVOS DE TRABALHO, EXCETO AS PREVISTAS NOS ITENS ANTERIORES", "20210509" } )
		aAdd(aBody, { "", "000092", "6901", "DESCONTO DO AVISO-PRÉVIO", "VALOR DESCONTADO DO TRABALHADOR QUE TENHA PEDIDO DEMISSÃO E NÃO CUMPRIU AVISO-PRÉVIO, TOTAL OU PARCIALMENTE", "" } )
		aAdd(aBody, { "", "000093", "6904", "MULTA PREVISTA NO ART. 480 DA CLT", "VALOR DESCONTADO DO EMPREGADO PELA RESCISÃO ANTECIPADA, POR INICIATIVA DO EMPREGADO, DO CONTRATO DE TRABALHO A TERMO", "" } )
		aAdd(aBody, { "", "000094", "7001", "PROVENTOS", "VALOR DOS PROVENTOS DE APOSENTADORIA A SERVIDOR PÚBLICO VINCULADO A REGIME PRÓPRIO DE PREVIDÊNCIA SOCIAL", "20210509" } )
		aAdd(aBody, { "", "000095", "9200", "DESCONTO DE ADIANTAMENTOS", "VALOR RELATIVO A DESCONTOS A TÍTULO DE ADIANTAMENTOS EM GERAL, COMO DE SALÁRIOS E OUTROS, EXCETO A 1ª PARCELA DO 13° SALÁRIO", "" } )
		aAdd(aBody, { "", "000096", "9201", "CONTRIBUIÇÃO PREVIDENCIÁRIA", "DESCONTO A TÍTULO DE CONTRIBUIÇÃO PREVIDENCIÁRIA", "" } )
		aAdd(aBody, { "", "000097", "9203", "IMPOSTO DE RENDA RETIDO NA FONTE", "DESCONTO A TÍTULO DE IMPOSTO DE RENDA RETIDO NA FONTE - IRRF", "" } )
		aAdd(aBody, { "", "000100", "9209", "FALTAS OU ATRASOS", "DESCONTO CORRESPONDENTE A FALTAS, ATRASOS NO INÍCIO DA JORNADA DE TRABALHO OU À SAÍDA ANTECIPADA DO TRABALHADOR", "" } )
		aAdd(aBody, { "", "000101", "9210", "DSR S/FALTAS E ATRASOS", "DESCONTO CORRESPONDENTE AO DESCANSO SEMANAL REMUNERADO - DSR, CALCULADO SOBRE FALTAS E ATRASOS DO TRABALHADOR", "" } )
		aAdd(aBody, { "", "000103", "9213", "PENSÃO ALIMENTÍCIA", "DESCONTO CORRESPONDENTE A PENSÃO ALIMENTÍCIA SOBRE O SALÁRIO MENSAL, 13° SALÁRIO, PLR E FÉRIAS", "" } )
		aAdd(aBody, { "", "000104", "9214", "13° SALÁRIO - DESCONTO DE ADIANTAMENTO", "DESCONTO DE ANTECIPAÇÃO DO 13° SALÁRIO", "" } )
		aAdd(aBody, { "", "000105", "9216", "DESCONTO DE VALE-TRANSPORTE", "DESCONTO DO VALE-TRANSPORTE REFERENTE A PARTICIPAÇÃO DO TRABALHADOR NO CUSTO OU EM VIRTUDE DE CONCESSÃO DO BENEFÍCIO EM VALOR MAIOR", "" } )
		aAdd(aBody, { "", "000106", "9217", "CONTRIBUIÇÃO A OUTRAS ENTIDADES E FUNDOS", "DESCONTO RELATIVO A CONTRIBUIÇÕES DESTINADAS A OUTRAS ENTIDADES E FUNDOS (TERCEIROS), COMO POR EXEMPLO, SEST, SENAT, ETC., DEVIDAS POR ALGUMAS CATEGORIAS DE CONTRIBUINTES INDIVIDUAIS", "" } )
		aAdd(aBody, { "", "000107", "9218", "RETENÇÕES JUDICIAIS", "DESCONTO RELATIVO A RETENÇÕES DE VERBAS DEVIDAS A TRABALHADORES POR ORDEM JUDICIAL, EXCETO PENSÃO ALIMENTÍCIA", "" } )
		aAdd(aBody, { "", "000108", "9219", "DESCONTO DE ASSISTÊNCIA MÉDICA OU ODONTOLÓGICA", "DESCONTO REFERENTE A PARTICIPAÇÃO DO TRABALHADOR NO CUSTO DE ASSISTÊNCIA MÉDICA OU ODONTOLÓGICA, OU EM VIRTUDE DE CONCESSÃO DO BENEFÍCIO EM VALOR MAIOR", "20250830" , 1033.79} )
		aAdd(aBody, { "", "000109", "9220", "ALIMENTAÇÃO - DESCONTO", "DESCONTO REFERENTE A PARTICIPAÇÃO DO TRABALHADOR NO CUSTO OU EM VIRTUDE DE CONCESSÃO DO BENEFÍCIO EM VALOR MAIOR", "20210630" } )
		aAdd(aBody, { "", "000110", "9221", "DESCONTO DE FÉRIAS", "VALOR CORRESPONDENTE A REMUNERAÇÃO (DIAS) DE FÉRIAS DO MÊS CORRENTE PAGO NO MÊS ANTERIOR OU ADIANTAMENTO DE FÉRIAS", "" } )
		aAdd(aBody, { "", "000111", "9222", "DESCONTO DE OUTROS IMPOSTOS E CONTRIBUIÇÕES", "DESCONTO DE OUTROS IMPOSTOS, TAXAS E CONTRIBUIÇÕES, EXCETO IMPOSTO DE RENDA RETIDO NA FONTE, CONTRIBUIÇÃO PREVIDENCIÁRIA E CONTRIBUIÇÕES DESTINADAS A OUTRAS ENTIDADES E FUNDOS (TERCEIROS)", "" } )
		aAdd(aBody, { "", "000112", "9223", "PREVIDÊNCIA COMPLEMENTAR - PARTE DO EMPREGADO", "DESCONTO REFERENTE A PARTICIPAÇÃO DO TRABALHADOR NO CUSTO OU EM VIRTUDE DE CONCESSÃO DO BENEFÍCIO EM VALOR MAIOR", "" } )
		aAdd(aBody, { "", "000113", "9224", "FAPI - PARTE DO EMPREGADO", "DESCONTO REFERENTE A PARTICIPAÇÃO DO TRABALHADOR NO CUSTO DE FUNDO DE APOSENTADORIA PROGRAMADA INDIVIDUAL - FAPI, OU EM VIRTUDE DE CONCESSÃO DO BENEFÍCIO EM VALOR MAIOR", "" } )
		aAdd(aBody, { "", "000114", "9225", "PREVIDÊNCIA COMPLEMENTAR - PARTE DO SERVIDOR", "DESCONTO REFERENTE A PARTICIPAÇÃO DO TRABALHADOR NO CUSTEIO DE PLANO DE PREVIDÊNCIA COMPLEMENTAR DO SERVIDOR PÚBLICO", "" } )
		aAdd(aBody, { "", "000115", "9230", "CONTRIBUIÇÃO SINDICAL - COMPULSÓRIA", "VALOR CORRESPONDENTE AO DESCONTO DA CONTRIBUIÇÃO LABORAL CORRESPONDENTE A UM DIA DE TRABALHO A TÍTULO DE CONTRIBUIÇÃO SINDICAL OBRIGATÓRIA", "20210509" } )
		aAdd(aBody, { "", "000116", "9231", "MENSALIDADE SINDICAL OU ASSOCIATIVA", "VALOR CORRESPONDENTE AO DESCONTO REFERENTE A MENSALIDADE SINDICAL OU ASSOCIATIVA DO TRABALHADOR", "" } )
		aAdd(aBody, { "", "000117", "9232", "CONTRIBUIÇÃO SINDICAL - ASSISTENCIAL", "VALOR CORRESPONDENTE AO DESCONTO DA CONTRIBUIÇÃO DESTINADA AO CUSTEIO DAS ATIVIDADES ASSISTENCIAIS DO SINDICATO", "" } )
		aAdd(aBody, { "", "000118", "9233", "CONTRIBUIÇÃO SINDICAL - CONFEDERATIVA", "VALOR CORRESPONDENTE AO DESCONTO DA CONTRIBUIÇÃO DESTINADA AO CUSTEIO DO SISTEMA CONFEDERATIVO", "" } )
		aAdd(aBody, { "", "000119", "9250", "SEGURO DE VIDA - DESCONTO", "DESCONTO REFERENTE A PARTICIPAÇÃO DO TRABALHADOR NO CUSTO OU EM VIRTUDE DE CONCESSÃO DO BENEFÍCIO EM VALOR MAIOR", "" } )
		aAdd(aBody, { "", "000120", "9254", "EMPRÉSTIMOS CONSIGNADOS - DESCONTO", "DESCONTO DE TRABALHADORES A TÍTULO DE EMPRÉSTIMOS CONSIGNADOS, PARA REPASSE A INSTITUIÇÃO FINANCEIRA CONSIGNATÁRIA", "" } )
		aAdd(aBody, { "", "000121", "9255", "EMPRÉSTIMOS DO EMPREGADOR - DESCONTO", "DESCONTO DE TRABALHADORES A TÍTULO DE EMPRÉSTIMOS EFETUADOS PELO EMPREGADOR AO TRABALHADOR", "" } )
		aAdd(aBody, { "", "000122", "9258", "CONVÊNIOS", "DESCONTO RELATIVOS A CONVÊNIOS DIVERSOS COM EMPRESAS PARA FORNECIMENTO DE PRODUTOS OU SERVIÇOS AO EMPREGADO, SEM PAGAMENTO IMEDIATO, MAS COM POSTERIOR DESCONTO EM FOLHA DE PAGAMENTO COMO FARMÁCIAS, SUPERMERCADOS, ETC.", "" } )
		aAdd(aBody, { "", "000123", "9270", "DANOS E PREJUÍZOS CAUSADOS PELO TRABALHADOR", "DESCONTO DO TRABALHADOR PARA REPARAR DANOS E PREJUÍZOS POR ELE CAUSADOS", "" } )
		aAdd(aBody, { "", "000124", "9290", "DESCONTO DE PAGAMENTO INDEVIDO EM MESES ANTERIORES", "VALOR CORRESPONDENTE A DESCONTO DE VERBAS PAGAS INDEVIDAMENTE AO TRABALHADOR EM MESES ANTERIORES E QUE ESTÃO SENDO DESCONTADAS NO MÊS DE REFERÊNCIA", "20210731" } )
		aAdd(aBody, { "", "000125", "9299", "OUTROS DESCONTOS", "OUTROS DESCONTOS NÃO PREVISTOS NOS ITENS ANTERIORES", "20210509" } )
		aAdd(aBody, { "", "000126", "9901", "BASE DE CÁLCULO DA CONTRIBUIÇÃO PREVIDENCIÁRIA", "VALOR TOTAL DA BASE DE CÁLCULO DA CONTRIBUIÇÃO PREVIDENCIÁRIA", "" } )
		aAdd(aBody, { "", "000127", "9902", "TOTAL DA BASE DE CÁLCULO DO FGTS", "VALOR TOTAL DA BASE DE CÁLCULO DO FGTS", "" } )
		aAdd(aBody, { "", "000128", "9903", "TOTAL DA BASE DE CÁLCULO DO IRRF", "VALOR TOTAL DA BASE DE CÁLCULO DO IMPOSTO DE RENDA RETIDO NA FONTE", "" } )
		aAdd(aBody, { "", "000129", "9904", "TOTAL DA BASE DE CÁLCULO DO FGTS RESCISÓRIO", "VALOR TOTAL DA BASE DE CÁLCULO DO FGTS RESCISÓRIO", "" } )
		aAdd(aBody, { "", "000130", "9905", "SERVIÇO MILITAR", "VALOR NÃO RELATIVO A VENCIMENTO OU DESCONTO, RELATIVO À REMUNERAÇÃO A QUE TERIA DIREITO, SE EM ATIVIDADE, O TRABALHADOR AFASTADO DO TRABALHO PARA PRESTAÇÃO DO SERVIÇO MILITAR OBRIGATÓRIO", "" } )
		aAdd(aBody, { "", "000131", "9910", "SEGUROS", "VALOR RELATIVO A PRÊMIO DE SEGURO DE VIDA EM GRUPO PAGO A EMPRESA DE SEGUROS COMO BENEFÍCIO DO TRABALHADOR", "" } )
		aAdd(aBody, { "", "000132", "9911", "ASSISTÊNCIA MÉDICA", "VALOR NÃO RELATIVO A VENCIMENTO OU DESCONTO, RELATIVO À ASSISTÊNCIA PRESTADA POR SERVIÇO MÉDICO OU ODONTOLÓGICO, PRÓPRIO DA EMPRESA OU POR ELA CONVENIADO, COMO BENEFÍCIO AO TRABALHADOR", "" } )
		aAdd(aBody, { "", "000133", "9930", "SALÁRIO MATERNIDADE PAGO PELA PREVIDÊNCIA SOCIAL", "VALOR CORRESPONDENTE A REMUNERAÇÃO MENSAL DO(A) TRABALHADOR(A) DURANTE A LICENÇA MATERNIDADE, QUANDO PAGA PELA PREVIDÊNCIA SOCIAL", "20210509" } )
		aAdd(aBody, { "", "000134", "9931", "13° SALÁRIO MATERNIDADE PAGO PELA PREVIDÊNCIA SOCIAL", "VALOR CORRESPONDENTE AO 13° SALÁRIO DO(A) TRABALHADOR(A) DURANTE A LICENÇA MATERNIDADE, QUANDO PAGO PELA PREVIDÊNCIA SOCIAL", "20210509" } )
		aAdd(aBody, { "", "000135", "9932", "AUXÍLIO-DOENÇA ACIDENTÁRIO", "VALOR RELATIVO A BASE DE CÁLCULO DO FGTS INCIDENTE SOBRE BENEFÍCIO PREVIDENCIÁRIO PAGO POR PREVIDÊNCIA SOCIAL OFICIAL A TRABALHADOR AFASTADO POR ACIDENTE DE TRABALHO", "20211006" } )
		aAdd(aBody, { "", "000136", "9938", "ISENÇÃO IRRF - 65 ANOS", "VALOR DA PARCELA ISENTA DOS RENDIMENTOS DE APOSENTADORIA E PENSÃO, TRANSFERÊNCIA PARA A RESERVA REMUNERADA OU REFORMA, PAGOS POR ÓRGÃO PÚBLICO DE PREVIDÊNCIA OFICIAL OU POR ENTIDADE DE PREVIDÊNCIA COMPLEMENTAR", "" } )
		aAdd(aBody, { "", "000137", "9939", "OUTROS VALORES TRIBUTÁVEIS", "VALOR NÃO RELATIVO A VENCIMENTO OU DESCONTO MAS CONSIDERADO COMO BASE DE CÁLCULO DO FGTS, E/OU DA CONTRIBUIÇÃO PREVIDENCIÁRIA E/OU DO IMPOSTO DE RENDA RETIDO NA FONTE INCLUSIVE SUAS DEDUÇÕES E ISENÇÕES", "" } )
		aAdd(aBody, { "", "000138", "9950", "HORAS EXTRAORDINÁRIAS - BANCO DE HORAS", "QUANTIDADE (EM NÚMERO DECIMAL COM DOIS DÍGITOS) DE HORAS EXTRAORDINÁRIAS INCORPORADAS AO BANCO DE HORAS", "20191031" } )
		aAdd(aBody, { "", "000139", "9951", "HORAS COMPENSADAS - BANCO DE HORAS", "QUANTIDADE (EM NÚMERO DECIMAL COM DOIS DÍGITOS) DE HORAS COMPENSADAS NO BANCO DE HORAS", "20191031" } )
		aAdd(aBody, { "", "000140", "9989", "OUTROS VALORES INFORMATIVOS", "OUTROS VALORES INFORMATIVOS, QUE NÃO SEJAM VENCIMENTOS NEM DESCONTOS", "" } )

		//Layout 2.2.3
		aAdd(aBody, { "", "000141", "1050", "REMUNERAÇÃO DE DIAS DE AFASTAMENTO", "REMUNERAÇÃO DE DIAS NOS QUAIS O TRABALHADOR ESTEJA AFASTADO DO TRABALHO SEM PREJUÍZO DE SUA REMUNERAÇÃO", "" } )
		aAdd(aBody, { "", "000142", "1080", "STOCK OPTION", "REMUNERAÇÃO PELO EXERCÍCIO DE OPÇÃO DE COMPRA DE AÇÕES DA EMPRESA", "" } )
		aAdd(aBody, { "", "000143", "1214", "ADICIONAL DE PENOSIDADE", "ADICIONAL PELA REALIZAÇÃO DE ATIVIDADE ÁRDUA QUE EXIJA DO TRABALHADOR ESFORÇO, ATENÇÃO OU VIGILÂNCIA ACIMA DO COMUM", "" } )
		aAdd(aBody, { "", "000144", "2510", "DIREITOS AUTORAIS E INTELECTUAIS", "VALOR CORRESPONDENTE A PARTICIPAÇÃO EM PRODUÇÃO CIENTÍFICA, INTELECTUAL OU ARTÍSTICA", "" } )
		aAdd(aBody, { "", "000145", "7002", "PROVENTOS - PENSÃO POR MORTE CIVIL", "VALOR DOS PROVENTOS POR MORTE A BENEFICIÁRIO DE SERVIDOR PÚBLICO VINCULADO A REGIME PRÓPRIO DE PREVIDÊNCIA SOCIAL", "20210509" } )
		aAdd(aBody, { "", "000146", "9906", "REMUNERAÇÃO NO EXTERIOR", "REMUNERAÇÃO RECEBIDA NO EXTERIOR POR TRABALHADOR EXPATRIADO SOBRE A QUAL INCIDA CONTRIBUIÇÃO PREVIDENCIÁRIA E/OU IRRF E/OU FGTS", "" } )

		//Layout 2.2
		aAdd(aBody, { "", "000147", "1006", "INTERVALOS INTRA E INTER JORNADAS NÃO CONCEDIDOS", "VALORES RELATIVOS A INTERVALOS NÃO CONCEDIDOS DE INTRAJORNADA OU INTERJORNADA", "" } )
		aAdd(aBody, { "", "000148", "1212", "GRATIFICAÇÕES OU OUTRAS VERBAS DE NATUREZA PERMANENTE", "ÓRGÃO PÚBLICO - PARCELAS REMUNERATÓRIAS RECONHECIDAMENTE INERENTES ÀS FUNÇÕES DO CARGO EFETIVO, CUJO VALOR INTEGRA A REMUNERAÇÃO DO CARGO EFETIVO", "" } )
		aAdd(aBody, { "", "000149", "1225", "QUEBRA DE CAIXA", "VALOR DESTINADO A COBRIR OS RISCOS ASSUMIDOS POR QUEM TRABALHA COM MANUSEIO DE VALORES, PARA COMPENSAR EVENTUAIS DESCONTOS OU DIFERENÇAS DE NUMERÁRIOS", "" } )
		aAdd(aBody, { "", "000150", "1623", "RESSARCIMENTO DE PROVISÃO", "RESSARCIMENTO DE DESCONTO EFETUADO EM RECIBOS DE FÉRIAS RELATIVO A PROVISÃO DE CONTRIBUIÇÃO PREVIDENCIÁRIA", "" } )
		aAdd(aBody, { "", "000151", "2801", "QUARENTENA REMUNERADA", "VALOR EQUIVALENTE A REMUNERAÇÃO SE EM EXERCÍCIO ESTIVESSE, DEVIDA AO TRABALHADOR DESLIGADO, EM PERÍODO DE QUARENTENA", "" } )
		aAdd(aBody, { "", "000152", "2999", "ARREDONDAMENTOS", "VALOR LANÇADO EM FOLHA DE PAGAMENTO, NÃO SUPERIOR A 99 CENTAVOS, RELATIVO A ARRENDAMENTOS", "" } )
		aAdd(aBody, { "", "000153", "7003", "PROVENTOS - RESERVA", "VALOR DOS PROVENTOS A MILITAR DA RESERVA REMUNERADA", "" } )
		aAdd(aBody, { "", "000154", "7004", "PROVENTOS - REFORMA", "VALOR DOS PROVENTOS A MILITAR REFORMADO", "" } )
		aAdd(aBody, { "", "000155", "7005", "PENSÃO MILITAR", "VALOR DA PENSÃO A BENEFICIÁRIO DE MILITAR", "" } )
		aAdd(aBody, { "", "000156", "9205", "PROVISÃO DE CONTRIBUIÇÃO PREVIDENCIÁRIA", "DESCONTO EFETUADO EM RECIBOS DE FÉRIAS RELATIVO A PROVISÃO DE CONTRIBUIÇÃO PREVIDENCIÁRIA", "" } )
		aAdd(aBody, { "", "000157", "9226", "DESCONTO DE FÉRIAS - ABONO", "DESCONTO CORRESPONDENTE AO ABONO DE FÉRIAS PAGO NO MÊS ANTERIOR OU ADIANTAMENTO DE FÉRIAS", "" } )
		aAdd(aBody, { "", "000158", "9908", "FGTS - DEPÓSITO", "VALOR DO DEPÓSITO DO FGTS", "" } )
		aAdd(aBody, { "", "000159", "9933", "AUXÍLIO-DOENÇA", "VALOR DE BENEFÍCIO PREVIDENCIÁRIO PAGO POR REGIME PRÓPRIO DE PREVIDÊNCIA SOCIAL OU VALOR DE AUXÍLIO DOENÇA DEDUCTÍVEL CONF. LEI Nº 13.982 (COVID-19)", "" } )

		// LAYOUT 2.4.02
		aAdd(aBody, { "", "000160", "1603", "AJUDA DE CUSTO", "AJUDA DE CUSTO PAGA AO TRABALHADOR", "" } )	//NT 11/2019
		aAdd(aBody, { "", "000161", "1604", "AJUDA DE CUSTO - ACIMA DE 50% DA REMUNERAÇÃO MENSAL", "AJUDA DE CUSTO PAGA AO TRABALHADOR, SUPERIOR A 50% DA SUA REMUNERAÇÃO MENSAL", "20190331" } ) //NT 11/2019
		aAdd(aBody, { "", "000162", "1650", "DIÁRIAS DE VIAGEM", "DIÁRIAS DE VIAGEM AO TRABALHADOR", "" } )
		aAdd(aBody, { "", "000163", "2502", "LIBERALIDADES CONCEDIDAS EM MAIS DE DUAS PARCELAS ANUAIS", "LIBERALIDADES CONCEDIDAS PELO EMPREGADOR EM FORMA DE BENS, SERVIÇOS OU VALOR EM DINHEIRO A EMPREGADO OU A GRUPO DE EMPREGADOS, EM RAZÃO DE DESEMPENHO SUPERIOR AO ORDINARIAMENTE ESPERADO NO EXERCÍCIO DE SUAS ATIVIDADES, EM MAIS DE DUAS PARCELAS ANUAIS ", "20190331" } )	//NT 11/2019
		aAdd(aBody, { "", "000164", "3525", "CÔNGRUAS, PREBENDAS E AFINS", "VALORES PAGOS A MINISTROS DE CONFISSÃO RELIGIOSA E QUE INDEPENDEM DE NATUREZA E DA QUANTIDADE DO TRABALHO EXECUTADO", "" } )
		aAdd(aBody, { "", "000165", "9260", "FIES - DESCONTO", "DESCONTO REFERENTE À AMORTIZAÇÃO DE FINANCIAMENTO DO FUNDO DE FINANCIAMENTO ESTUDANTIL (FIES), PARA REPASSE À INSTITUIÇÃO CONSIGNATÁRIA", "" } )

		//COVID-19
		aAdd(aBody, { "", "000166", "1619", "AJUDA COMPENSATÓRIA – MP 936", "AJUDA COMPENSATÓRIA PAGA PELO EMPREGADOR AO EMPREGADO DURANTE PERÍODO DE SUSPENSÃO DO CONTRATO DE TRABALHO OU REDUÇÃO PROPORCIONAL DE SALÁRIO E JORNADA.", "20201123" } )
		aAdd(aBody, { "", "000167", "6119", "INDENIZAÇÃO RESCISÓRIA – MP 936", "INDENIZAÇÃO PELA DISPENSA SEM JUSTA CAUSA QUE OCORRER DURANTE O PERÍODO DE GARANTIA PROVISÓRIA NO EMPREGO DE QUE TRATA O ART. 10 DA MP 936/2020", "20201123" } )

		//NT-19/2020																							
		aAdd(aBody, { "", "000168", "1619", "AJUDA COMPENSATÓRIA – LEI 14.020/2020 (CONVERSÃO DA MP 936/2020)", "AJUDA COMPENSATÓRIA PAGA PELO EMPREGADOR AO EMPREGADO DURANTE PERÍODO DE SUSPENSÃO DO CONTRATO DE TRABALHO OU REDUÇÃO PROPORCIONAL DE SALÁRIO E JORNADA.", "20210509" } )
		aAdd(aBody, { "", "000169", "6119", "INDENIZAÇÃO RESCISÓRIA – LEI 14.020/2020 (CONVERSÃO DA MP 936/2020)", "INDENIZAÇÃO PELA DISPENSA SEM JUSTA CAUSA QUE OCORRER DURANTE O PERÍODO DE GARANTIA PROVISÓRIA NO EMPREGO DE QUE TRATA O ART. 10 DA LEI 14.020/2020 (CONVERSÃO DA MP 936/2020)", "20210509" } )
		aAdd(aBody, { "", "000170", "6101", "INDENIZAÇÃO COMPENSATÓRIA - MULTA RESCISÓRIA 20 OU 40% (CF/88)", "VALOR CORRESPONDENTE À INDENIZAÇÃO POR DEMISSÃO SEM JUSTA CAUSA, POR CULPA RECÍPROCA OU FORÇA MAIOR (AMBAS RECONHECIDAS PELA JUSTIÇA DO TRABALHO) OU POR ACORDO ENTRE EMPREGADO E EMPREGADOR, QUANDO DA RESCISÃO DO CONTRATO DE TRABALHO; OU CORRESPONDENTE À ANTECIPAÇÃO DA MULTA RESCISÓRIA DO FGTS PAGA AO EMPREGADO COM CONTRATO VERDE E AMARELO ", "" } )

		//Simplificação do E-Solcial

		//Inclusões
		aAdd(aBody, { "", "000171", "1001", "SUBSIDIO" 														,"CORRESPONDE A REMUNERACAO PAGA NA FORMA DE SUBSIDIO", "" } )
		aAdd(aBody, { "", "000172", "1216", "ADICIONAL DE LOCALIDADE"										,"ADICIONAL PELA REALIZACAO DE ATIVIDADE EM LOCALIDADE TRANSFRONTEIRICOS", "" } )
		aAdd(aBody, { "", "000173", "1217", "GRATIFICACAO DE CURSO/CONCURSO"								,"VERBA DE NATUREZA REMUNERATORIA POR ATIVIDADE EXERCIDA EM CURSO/CONCURSO", "" } )
		aAdd(aBody, { "", "000174", "1411", "AUXILIO-NATALIDADE"											,"VALOR RELATIVO AO NASCIMENTO DO FILHO DE SERVIDOR PUBLICO, PREVISTO EM LEI", "" } )
		aAdd(aBody, { "", "000175", "1412", "ABONO PERMANENCIA"												,"VALOR RELATIVO AO ABONO DE PERMANENCIA, DE ACORDO COM A CF/1988 ", "" } )
		aAdd(aBody, { "", "000176", "1800", "ALIMENTACAO CONCEDIDA EM PECUNIA"								,"ALIMENTACAO CONCEDIDA SOB A FORMA DE PECUNIA", "20251231", 1033.80 } )
		aAdd(aBody, { "", "000177", "1806", "ALIMENTACAO EM TICKET OU CARTAO, VINCULADA AO PAT"				,"ALIMENTACAO CONCEDIDA SOB A FORMA DE TICKET OU CARTAO, POR EMPRESA VINCULADA AO PROGRAMA DE ALIMENTACAO DO TRABALHADOR PAT", "" } )
		aAdd(aBody, { "", "000178", "1807", "ALIMENTACAO EM TICKET OU CARTAO, NAO VINCULADA AO PAT"			,"ALIMENTAÇÃO CONCEDIDA SOB A FORMA DE TICKET OU CARTAO, POR EMPRESA NAO VINCULADA AO PAT", "" } )
		aAdd(aBody, { "", "000179", "1808", "CESTA BASICA OU REFEICAO, VINCULADA AO PAT"					,"ALIMENTACAO CONCEDIDA SOB A FORMA DE CESTA BASICA OU REFEICAO, POR EMPRESA VINCULADA AO PAT", "" } )
		aAdd(aBody, { "", "000180", "1809", "CESTA BASICA OU REFEICAO, NAO VINCULADA AO PAT"				,"ALIMENTACAO CONCEDIDA SOB A FORMA DE CESTA BASICA OU REFEICAO, POR EMPRESA NAO VINCULADA AO PAT", "" } )
		aAdd(aBody, { "", "000181", "1899", "OUTROS AUXILIOS" 												,"VALORES RELATIVOS A OUTROS AUXILIOS NAO PREVISTOS NOS DEMAIS ITENS", "" } )
		aAdd(aBody, { "", "000182", "3510", "GRATIFICACAO (JETON)"											,"VALOR CORRESPONDENTE A GRATIFICACAO (JETON) POR COMPARECIMENTO A SESSOES OU REUNIOES", "" } )
		aAdd(aBody, { "", "000183", "3511", "GRATIFICACAO ELEITORAL"										,"VALOR CORRESPONDENTE AO EXERCICIO DA ATIVIDADE PELO JUIZ ELEITORAL", "" } )
		aAdd(aBody, { "", "000184", "4011", "COMPLEMENTO DE SALARIO MINIMO - RPPS"							,"VALOR CORRESPONDENTE A DIFERENÇA ENTRE O SALARIO-MINIMO E O VALOR DO VENCIMENTO DO CARGO EFETIVO PAGO A SERVIDOR PUBLICO VINCULADO A REGIME PROPRIO DE PREVIDENCIA SOCIAL - RPPS", "" } )
		aAdd(aBody, { "", "000185", "7006", "AUXILIO-RECLUSAO"												,"VALOR DE AUXILIO-RECLUSAO PARA O SERVIDOR PUBLICO DE BAIXA RENDA", "" } )
		aAdd(aBody, { "", "000186", "7007", "PENSOES ESPECIAIS"												,"VALOR DAS PENSOES DE CARATER ESPECIAL DIFERENTES DE PENSAO POR MORTE", "" } )
		aAdd(aBody, { "", "000187", "7008", "COMPLEMENTACAO DE APOSENTADORIA/ PENSAO"						,"VALOR RELATIVO A COMPLEMENTACAO DE APOSENTADORIA/PENSAO VINCULADA AO REGIME GERAL DE PREVIDENCIA SOCIAL - RGPS", "" } )
		aAdd(aBody, { "", "000188", "9202", "CONTRIBUICAO MILITAR"											,"DESCONTO RELATIVO À SEGURIDADE DO MILITAR E SEUS DEPENDENTES", "" } )
		aAdd(aBody, { "", "000189", "9207", "FALTAS"														,"DESCONTO DECORRENTE DE AUSENCIA DE TRABALHO DURANTE TODO O DIA EM RAZAO DE, POR EXEMPLO, FALTA INJUSTIFICADA, SUSPENSAO DISCIPLINAR, GREVE", "" } )
		aAdd(aBody, { "", "000190", "9208", "ATRASOS"														,"DESCONTO DECORRENTE DE AUSENCIA DE TRABALHO EM RAZAO DE, POR EXEMPLO, ATRASOS NO INICIO DA JORNADA DE TRABALHO OU DE SAIDA ANTECIPADA DO TRABALHADOR", "" } )
		aAdd(aBody, { "", "000191", "9211", "DSR SOBRE FALTAS"												,"DESCONTO CORRESPONDENTE AO DESCANSO SEMANAL REMUNERADO - DSR, CALCULADO SOBRE FALTAS DO TRABALHADOR", "" } )
		aAdd(aBody, { "", "000192", "9212", "DSR SOBRE ATRASOS"												,"DESCONTO CORRESPONDENTE AO DESCANSO SEMANAL REMUNERADO - DSR, CALCULADO SOBRE ATRASOS DO TRABALHADOR", "" } )
		aAdd(aBody, { "", "000193", "9240", "ALIMENTACAO CONCEDIDA EM PECUNIA - DESCONTO"					,"DESCONTO REFERENTE A ALIMENTACAO CONCEDIDA SOB A FORMA DE PECUNIA", "" } )
		aAdd(aBody, { "", "000194", "9241", "ALIMENTACAO EM TICKET OU CARTAO, VINCULADA AO PAT DESCONTO"	,"DESCONTO REFERENTE A PARTICIPACAO DO TRABALHADOR NO CUSTO DE ALIMENTACAO CONCEDIDA SOB A FORMA DE TICKET OU CARTAO, POR EMPRESA VINCULADA AO PROGRAMA DE ALIMENTACAO DO TRABALHADOR - PAT", "" } )
		aAdd(aBody, { "", "000195", "9242", "ALIMENTACAO EM TICKET OU CARTAO, NAO VINCULADA AO PAT DESCONTO","DESCONTO REFERENTE A PARTICIPACAO DO TRABALHADOR NO CUSTO DE ALIMENTACAO CONCEDIDA SOB A FORMA DE TICKET OU CARTAO, POR EMPRESA NAO VINCULADA AO PAT", "" } )
		aAdd(aBody, { "", "000196", "9243", "CESTA BASICA OU REFEICAO, VINCULADA AO PAT - DESCONTO"			,"DESCONTO REFERENTE A PARTICIPAÇÃO DO TRABALHADOR NO CUSTO DE ALIMENTACAO CONCEDIDA SOB A FORMA DE CESTA BASICA OU REFEICAO, POR EMPRESA VINCULADA AO PAT", "" } )
		aAdd(aBody, { "", "000197", "9244", "CESTA BASICA OU REFEICAO, NAO VINCULADA AO PAT - DESCONTO"		,"DESCONTO REFERENTE A PARTICIPACAO DO TRABALHADOR NO CUSTO DE ALIMENTACAO CONCEDIDA SOB A FORMA DE CESTA BASICA OU REFEICAO, POR EMPRESA NAO VINCULADA AO PAT", "" } )
		aAdd(aBody, { "", "000198", "9291", "ABATE-TETO"													,"VALOR DEDUZIDO DA REMUNERACAO TOTAL DO SEGURADO QUE SUPERE O TETO REMUNERATORIO CONSTITUCIONAL", "" } )
		aAdd(aBody, { "", "000199", "9292", "RESSARCIMENTO AO ERARIO"										,"VALOR DEDUZIDO DA REMUNERACAO PARA PAGAMENTO DE RESSARCIMENTO OU DE PENALIDADE", "" } )
		aAdd(aBody, { "", "000200", "9293", "HONORARIOS ADVOCATICIOS"										,"VALOR DESCONTADO DO TRABALHADOR POR DETERMINACAO JUDICIAL A SER PAGO AO ADVOGADO/ESCRITORIO DE ADVOCACIA", "" } )
		aAdd(aBody, { "", "000201", "9294", "REDUTOR EC 41/03"												,"VALOR DESCONTADO DA REMUNERACAO DO INSTITUIDOR DA PENSAO (EMENDA CONSTITUCIONAL 41/2003)", "" } )
		aAdd(aBody, { "", "000202", "9907", "TOTAL DA CONTRIBUICAO DA PREVIDENCIARIA PATRONAL - RPPS"		,"VALOR TOTAL DA CONTRIBUICAO PREVIDENCIARIA PATRONAL PARA O RPPS (NORMAL, SUPLEMENTAR E APORTES)", "" } )

		//Alterações
		aAdd(aBody, { "", "000203", "1000", "SALARIO, VENCIMENTO, SOLDO"									,"CORRESPONDE AO SALARIO BASICO CONTRATUAL DO EMPREGADO CONTRATADO DE ACORDO COM A CLT E O VENCIMENTO MENSAL DO SERVIDOR PUBLICO E DO MILITAR", "" } )
		aAdd(aBody, { "", "000204", "1099", "OUTRAS VERBAS SALARIAIS"										,"OUTRAS VERBAS SALARIAIS NAO PREVISTAS NOS DEMAIS ITENS", "20250830" , 1033.79} )
		aAdd(aBody, { "", "000205", "1299", "OUTROS ADICIONAIS"												,"VALORES RELATIVOS A OUTROS ADICIONAIS NAO PREVISTOS NOS DEMAIS ITENS", "" } )
		aAdd(aBody, { "", "000206", "1619", "AJUDA COMPENSATORIA - LEI 14.020/2020"							,"AJUDA COMPENSATORIA PAGA PELO EMPREGADOR AO EMPREGADO DURANTE PERIODO DE SUSPENSAO DO CONTRATO DE TRABALHO OU REDUCAO PROPORCIONAL DE SALARIO E JORNADA, NOS TERMOS DA LEI 14.020/2020 (CONVERSAO DA MP 936/2020"	, "20210718" } )
		aAdd(aBody, { "", "000207", "1629", "RESSARCIMENTO DE OUTRAS DESPESAS"								,"RESSARCIMENTO DE OUTRAS DESPESAS PAGAS PELO TRABALHADOR, NAO PREVISTAS NOS DEMAIS ITENS", "" } )
		aAdd(aBody, { "", "000208", "6119", "INDENIZACAO RESCISORIA - LEI 14.020/2020"						,"INDENIZACAO PELA DISPENSA SEM JUSTA CAUSA QUE OCORRER DURANTE O PERIODO DE GARANTIA PROVISORIA NO EMPREGO DE QUE TRATA O ART. 10 DA LEI 14.020/2020 (CONVERSAO DA MP 936/2020)"									, "20210718" } )
		aAdd(aBody, { "", "000209", "6129", "OUTRAS MULTAS OU INDENIZAÇÕES"									,"VALOR CORRESPONDENTE A OUTRAS MULTAS OU INDENIZACOES PREVISTAS EM LEIS OU EM INSTRUMENTOS COLETIVOS DE TRABALHO, EXCETO AS PREVISTAS NOS DEMAIS ITENS", "20250830" , 1033.79} )
		aAdd(aBody, { "", "000210", "7001", "PROVENTOS"														,"VALOR DOS PROVENTOS DE APOSENTADORIA A SERVIDOR PUBLICO", "" } )
		aAdd(aBody, { "", "000211", "7002", "PROVENTOS - PENSAO POR MORTE CIVIL"							,"VALOR DOS PROVENTOS POR MORTE A BENEFICIARIO DE SERVIDOR PUBLICO", "" } )
		aAdd(aBody, { "", "000212", "9230", "CONTRIBUICAO SINDICAL LABORAL"									,"VALOR CORRESPONDENTE AO DESCONTO DA CONTRIBUIÇÃO LABORAL CORRESPONDENTE A UM DIA DE TRABALHO A TÍTULO DE CONTRIBUIÇÃO SINDICAL", "" } )
		aAdd(aBody, { "", "000213", "9299", "OUTROS DESCONTOS"												,"OUTROS DESCONTOS NAO PREVISTOS NOS DEMAIS ITENS" , "" } )
		aAdd(aBody, { "", "000214", "9930", "SALARIO-MATERNIDADE PAGO PELA PREVIDENCIA SOCIAL"				,"VALOR CORRESPONDENTE A REMUNERACAO MENSAL DO(A) TRABALHADOR(A) DURANTE A LICENÇA MATERNIDADE, QUANDO PAGA PELA PREVIDENCIA SOCIAL (RGPS OU PELA UNIDADE GESTORA DO RPPS)", "" } )
		aAdd(aBody, { "", "000215", "9931", "SALARIO-MATERNIDADE PAGO PELA PREVIDENCIA SOCIAL - 13° SALARIO","VALOR CORRESPONDENTE AO 13° SALARIO DO(A) TRABALHADOR(A) DURANTE A LICENCA MATERNIDADE, QUANDO PAGO PELA PREVIDÊNCIA SOCIAL (RGPS OU PELA UNIDADE GESTORA DO RPPS)", "" } )

		//NT 21/2021 - 2.5
		aAdd(aBody, { "", "000216", "6108",  "TEMPO DE ESPERA DO MOTORISTA PROFISSIONAL "  					,"VALOR CORRESPONDENTE AO TEMPO DE ESPERA DO MOTORISTA PROFISSIONAL", "" } )

		//NT - 02/202 - Leiaute S-1.0
		
		//incluidos
		aAdd(aBody, { "", "000217", "1901",  "JUROS E/OU ATUALIZAÇÃO MONETÁRIA "  																					,"JUROS E/OU ATUALIZAÇÃO MONETÁRIA DEVIDOS PELO ATRASO NO PAGAMENTO DE VALORES POR EXERCÍCIO DE EMPREGO, CARGO OU FUNÇÃO", "" } )
		aAdd(aBody, { "", "000218", "2903",  "VESTUÁRIO E EQUIPAMENTOS "  																							,"VALOR CORRESPONDENTE A VESTUÁRIOS, EQUIPAMENTOS E OUTROS ACESSÓRIOS QUANDO ESSES SE CONSTITUÍREM EM SALÁRIO UTILIDADE", "" } )

		//alterados  20210718
		aAdd(aBody, { "", "000219", "1619",  "AJUDA COMPENSATÓRIA - PROGRAMA EMERGENCIAL DE MANUTENÇÃO DO EMPREGO E DA RENDA "  									,"AJUDA COMPENSATÓRIA PAGA PELO EMPREGADOR AO EMPREGADO DURANTE PERÍODO DE SUSPENSÃO DO CONTRATO DE TRABALHO OU REDUÇÃO PROPORCIONAL DE SALÁRIO E JORNADA", "" } )
		aAdd(aBody, { "", "000220", "6119",  "INDENIZAÇÃO RESCISÓRIA - PROGRAMA EMERGENCIAL DE MANUTENÇÃO DO EMPREGO E DA RENDA "  									,"INDENIZAÇÃO PELA DISPENSA SEM JUSTA CAUSA QUE OCORRER DURANTE O PERÍODO DE GARANTIA PROVISÓRIA NO EMPREGO DE QUE TRATA O PROGRAMA EMERGENCIAL DE MANUTENÇÃO DO EMPREGO E DA RENDA", "" } )
		aAdd(aBody, { "", "000221", "1810",  "TRANSPORTE "  																										,"AUXÍLIO-TRANSPORTE OU VALE-TRANSPORTE", "20251231", 1033.80} )
       
	    //NT 22/2021
	    aAdd(aBody, { "", "000222", "9932", "AUXÍLIO-DOENÇA ACIDENTÁRIO", "VALOR RELATIVO A BASE DE CÁLCULO DO FGTS REFERENTE A AFASTAMENTO DECORRENTE DE ACIDENTE DE TRABALHO", "" } )
	 	aAdd( aRet, { aHeader, aBody } )

		//NT 01/2023 - S-1.1
		//Descrições alteradas
		aAdd( aBody, { "", "000223", "1004", "HORAS EXTRAORDINÁRIAS - BANCO DE HORAS", "VALOR CORRESPONDENTE A PAGAMENTO DAS HORAS EXTRAORDINÁRIAS, INICIALMENTE DESTINADAS PARA O BANCO DE HORAS E QUE NÃO FORAM COMPENSADAS"																																																				, "", 1033.16  } )
		aAdd( aBody, { "", "000224", "1022", "FÉRIAS - ABONO OU GRATIFICAÇÃO DE FÉRIAS NÃO EXCEDENTE A 20 DIAS", "REMUNERAÇÃO A TÍTULO DE ABONO DE FÉRIAS, INCLUÍDO O TERÇO CONSTITUCIONAL DE FÉRIAS, DESDE QUE NÃO EXCEDENTE A 20 (VINTE) DIAS DO SALÁRIO E CONCEDIDO EM VIRTUDE DE CLÁUSULA CONTRATUAL, DO REGULAMENTO DA EMPRESA, DE CONVENÇÃO OU ACORDO COLETIVO, COMO POR EXEMPLO O ART. 144 DA CLT"									, "", 1033.16  } )

		//Incluidos
		aAdd( aBody, { "", "000225", "1016", "FÉRIAS", "VALOR CORRESPONDENTE À REMUNERAÇÃO DEVIDA NA ÉPOCA DA CONCESSÃO DAS FÉRIAS, INCLUSIVE O ADIANTAMENTO DE FÉRIAS. NESSA NATUREZA DEVE SER CLASSIFICADO TAMBÉM O VALOR PAGO MENSALMENTE AO TRABALHADOR AVULSO E AO EMPREGADO COM CONTRATO DE TRABALHO INTERMITENTE, A TÍTULO DE FÉRIAS"																								, "20251231", 1033.80   } )
		aAdd( aBody, { "", "000226", "1017", "TERÇO CONSTITUCIONAL DE FÉRIAS", "VALOR CORRESPONDENTE AO TERÇO CONSTITUCIONAL DE FÉRIAS RELATIVO À REMUNERAÇÃO DEVIDA NA ÉPOCA DA CONCESSÃO DAS FÉRIAS, INCLUSIVE O ADIANTAMENTO DE FÉRIAS. NESSA NATUREZA DEVE SER CLASSIFICADO TAMBÉM O VALOR PAGO MENSALMENTE AO TRABALHADOR AVULSO E AO EMPREGADO COM CONTRATO DE TRABALHO INTERMITENTE, A TÍTULO DE TERÇO CONSTITUCIONAL DE FÉRIAS"		, "20251231", 1033.80  } )
		aAdd( aBody, { "", "000227", "1018", "FÉRIAS - ABONO OU GRATIFICAÇÃO DE FÉRIAS SUPERIOR A 20 DIAS", "REMUNERAÇÃO A TÍTULO DE ABONO DE FÉRIAS, DESDE QUE EXCEDENTE A 20 (VINTE) DIAS DO SALÁRIO E CONCEDIDO EM VIRTUDE DE CLÁUSULA CONTRATUAL, DO REGULAMENTO DA EMPRESA, DE CONVENÇÃO OU ACORDO COLETIVO, COMO POR EXEMPLO, O ART. 144 DA CLT"																						, "", 1033.16  } )
		aAdd( aBody, { "", "000228", "1019", "TERÇO CONSTITUCIONAL DE FÉRIAS - ABONO OU GRATIFICAÇÃO DE FÉRIAS SUPERIOR A 20 DIAS", "TERÇO CONSTITUCIONAL DE FÉRIAS INCIDENTE SOBRE REMUNERAÇÃO A TÍTULO DE ABONO DE FÉRIAS, DESDE QUE EXCEDENTE A 20 (VINTE) DIAS DO SALÁRIO E CONCEDIDO EM VIRTUDE DE CLÁUSULA CONTRATUAL, DO REGULAMENTO DA EMPRESA, DE CONVENÇÃO OU ACORDO COLETIVO, COMO POR EXEMPLO, O ART. 144 DA CLT"				, "", 1033.16  } )

		//Alterações - S-1.2  NT 02/2023
		aAdd(aBody, { "", "000229", "1409", "SALÁRIO-FAMÍLIA", "VALOR DO SALÁRIO-FAMÍLIA, CONFORME DEFINIÇÃO LEGAL APLICÁVEL"																																																																												, "", 1033.37 } )

		//NOTA TÉCNICA S-1.2 Nº 01/2023
		aAdd( aBody,{ "", "000230", "1012", "DESCANSO SEMANAL REMUNERADO - DSR E FERIADO", "VALORES CORRESPONDENTES A DSR E FERIADO: A) DEVIDOS A TRABALHADORES CUJA REMUNERAÇÃO NÃO INCLUA O PAGAMENTO DO DESCANSO SEMANAL REMUNERADO (HORISTAS, DIARISTAS, SEMANALISTAS ETC.) B) INCIDENTES SOBRE PARCELAS SALARIAIS DE NATUREZA VARIÁVEL, TAIS COMO TAREFA, HORAS EXTRAS, ADICIONAL NOTURNO, PRODUÇÃO, COMISSÃO ETC. C) DEVIDOS A TRABALHADORES QUE PRESTARAM 01/01/2014 - PÁGINA 7 DE 164 TABELA 03 - NATUREZA DAS RUBRICAS DA FOLHA DE PAGAMENTO CÓDIGO NOME DA NATUREZA DA RUBRICA DESCRIÇÃO DA NATUREZA DA RUBRICA INÍCIO TÉRMINO SERVIÇOS NOS DIAS DE REPOUSO SEMANAL E FERIADO ", "", 1033.42 } )

		//Alterações - S-1.2  NT 04/2024
		aAdd(aBody, { "", "000231", "9253", "EMPRÉSTIMOS ECONSIGNADO - DESCONTO", "DESCONTO DE TRABALHADORES A TÍTULO DE EMPRÉSTIMOS NA MODALIDADE ECONSIGNADO PARA REPASSE À INSTITUIÇÃO FINANCEIRA CONSIGNATÁRIA RECOLHIDO EM GUIA DO FGTS CONFORME LEGISLAÇÃO ESPECÍFICA"																																																																												, "", 1033.62 } )
		aAdd(aBody, { "", "000232", "9912", "DESCONTO DE ASSISTÊNCIA MÉDICA OU ODONTOLÓGICA", "DESCONTO DE ASSISTÊNCIA MÉDICA OU ODONTOLÓGICA (PLANO DIFERENTE DE COLETIVO EMPRESARIAL)", "20250830", 1033.75 } )
	
		//Alterações - S-1.3  NT 04/2025
		aAdd(aBody, { "", "000233", "6129", "OUTRAS VERBAS NÃO REMUNERATÓRIAS (INDENIZATÓRIAS OU MULTAS)"									,"VALOR CORRESPONDENTE A PARCELAS INDENIZATÓRIAS OU OUTRAS MULTAS PREVISTAS EM LEIS OU EM INSTRUMENTOS COLETIVOS DE TRABALHO, EXCETO AS PREVISTAS NOS DEMAIS ITENS"									, "", 1033.79 } )
		aAdd(aBody, { "", "000234", "9219", "DESCONTO DE ASSISTÊNCIA MÉDICA OU ODONTOLÓGICA - PLANO COLETIVO EMPRESARIAL"					,"DESCONTO REFERENTE A PARTICIPAÇÃO DO TRABALHADOR NO CUSTO DE ASSISTÊNCIA MÉDICA OU ODONTOLÓGICA, OU EM VIRTUDE DE CONCESSÃO DO BENEFÍCIO EM VALOR MAIOR, NOS CASOS DE PLANO COLETIVO EMPRESARIAL"	, "", 1033.79 } )
		aAdd(aBody, { "", "000235", "1099", "OUTRAS VERBAS SALARIAIS"																		,"OUTRAS VERBAS SALARIAIS/REMUNERATÓRIAS NÃO PREVISTAS NOS DEMAIS ITENS"																															, "", 1033.79 } )
		aAdd(aBody, { "", "000236", "9912", "DESCONTO DE ASSISTÊNCIA MÉDICA OU ODONTOLÓGICA - PLANO DIFERENTE DE COLETIVO EMPRESARIAL"		,"DESCONTO REFERENTE AOS CUSTOS DE ASSISTÊNCIA MÉDICA OU ODONTOLÓGICA, QUANDO NÃO SE TRATAR DE PLANO DE SAÚDE COLETIVO EMPRESARIAL (CÓDIGO [9219])"													, "", 1033.79 } )
		aAdd(aBody, { "", "000237", "1015", "ADIANTAMENTO DE FÉRIAS"																		,"VALOR CORRESPONDENTE AO PAGAMENTO DO ADIANTAMENTO DA REMUNERAÇÃO DE FÉRIAS, INCLUSIVE DO TERÇO CONSTITUCIONAL"																					, "", 1033.80 } )
		aAdd(aBody, { "", "000238", "1799", "ALIMENTAÇÃO CONCEDIDA EM PECÚNIA COM CARÁTER INDENIZATÓRIO"									,"AUXÍLIO-ALIMENTAÇÃO OU ALIMENTAÇÃO CONCEDIDA SOB A FORMA DE PECÚNIA COM NATUREZA INDENIZATÓRIA POR FORÇA DE LEI"																					, "", 1033.80 } )
		aAdd(aBody, { "", "000239", "1811", "AUXÍLIO-TRANSPORTE OU AUXÍLIO-COMBUSTÍVEL COM CARÁTER SALARIAL"								,"AUXÍLIO-TRANSPORTE, PAGO EM PECÚNIA OU DE OUTRA FORMA, COM NATUREZA SALARIAL"																														, "", 1033.80 } )
		aAdd(aBody, { "", "000240", "1800", "ALIMENTAÇÃO CONCEDIDA EM PECÚNIA COM CARÁTER SALARIAL"											,"ALIMENTAÇÃO CONCEDIDA SOB A FORMA DE PECÚNIA COM NATUREZA SALARIAL"																																, "", 1033.80 } )
		aAdd(aBody, { "", "000241", "1810", "VALE-TRANSPORTE OU AUXÍLIO-TRANSPORTE COM CARÁTER INDENIZATÓRIO"								,"VALE-TRANSPORTE OU AUXÍLIO-TRANSPORTE COM NATUREZA INDENIZATÓRIA POR FORÇA DE LEI"																												, "", 1033.80 } )
		aAdd(aBody, { "", "000242", "1016", "FÉRIAS"																						,"VALOR CORRESPONDENTE À REMUNERAÇÃO DEVIDA NA ÉPOCA DA CONCESSÃO DAS FÉRIAS. NESSA NATUREZA DEVE SER CLASSIFICADO TAMBÉM O VALOR PAGO MENSALMENTE AO TRABALHADOR AVULSO E AO EMPREGADO COM CONTRATO DE TRABALHO INTERMITENTE, A TÍTULO DE FÉRIAS"																				, "", 1033.80 } )
		aAdd(aBody, { "", "000243", "1017", "TERÇO CONSTITUCIONAL DE FÉRIAS"																,"VALOR CORRESPONDENTE AO TERÇO CONSTITUCIONAL DE FÉRIAS RELATIVO À REMUNERAÇÃO DEVIDA NA ÉPOCA DA CONCESSÃO DAS FÉRIAS. NESSA NATUREZA DEVE SER CLASSIFICADO TAMBÉM O VALOR PAGO MENSALMENTE AO TRABALHADOR AVULSO E AO EMPREGADO COM CONTRATO DE TRABALHO INTERMITENTE, A TÍTULO DE TERÇO CONSTITUCIONAL DE FÉRIAS"			, "", 1033.80 } )

	EndIf

Return( aRet )
