#include "TOTVS.CH"

/*/{Protheus.doc} 
    Classe concreta da Entidade PLSBa1 - Users
    @type  Class
    @author FrameworkApi 1.0
    @since 20190211
/*/
Class PLSBa1 from CenEntity

    Method New()
  
    Method serialize(oJsonControl)
    Method destroy()

EndClass

Method New() Class PLSBa1
	_Super:New()
Return self

Method serialize(oJsonControl) Class PLSBa1

	Local oJson := JsonObject():New()
	Default oJsonControl := PLSJsonControl():New()


    oJsonControl:setProp(oJson,"operator",self:getValue("BA1_CODINT")) 
    oJsonControl:setProp(oJson,"companyCode",self:getValue("BA1_CODEMP")) 
    oJsonControl:setProp(oJson,"beneficiaryRegistration",self:getValue("BA1_MATRIC")) 
    oJsonControl:setProp(oJson,"companyContract",self:getValue("BA1_CONEMP")) 
    oJsonControl:setProp(oJson,"contractVersion",self:getValue("BA1_VERCON")) 
    oJsonControl:setProp(oJson,"subContract",self:getValue("BA1_SUBCON")) 
    oJsonControl:setProp(oJson,"subContractVersion",self:getValue("BA1_VERSUB")) 
    oJsonControl:setProp(oJson,"noEnglishName",self:getValue("BA1_IMAGE")) 
    oJsonControl:setProp(oJson,"recordType",self:getValue("BA1_TIPREG")) 
    oJsonControl:setProp(oJson,"digit",self:getValue("BA1_DIGITO")) 
    oJsonControl:setProp(oJson,"beneficiaryCpf",self:getValue("BA1_CPFUSR")) 
    oJsonControl:setProp(oJson,"pisPasepNumber",self:getValue("BA1_PISPAS")) 
    oJsonControl:setProp(oJson,"beneficiaryId",self:getValue("BA1_DRGUSR")) 
    oJsonControl:setProp(oJson,"issuingEntity",self:getValue("BA1_ORGEM")) 
    oJsonControl:setProp(oJson,"lifeRegistration",self:getValue("BA1_MATVID")) 
    oJsonControl:setProp(oJson,"beneficiaryName",self:getValue("BA1_NOMUSR")) 
    oJsonControl:setProp(oJson,"shortName",self:getValue("BA1_NREDUZ")) 
    oJsonControl:setProp(oJson,"dateOfBirth",self:getValue("BA1_DATNAS")) 
    oJsonControl:setProp(oJson,"sex",self:getValue("BA1_SEXO")) 
    oJsonControl:setProp(oJson,"beneficiaryType",self:getValue("BA1_TIPUSU")) 
    oJsonControl:setProp(oJson,"maritalStatus",self:getValue("BA1_ESTCIV")) 
    oJsonControl:setProp(oJson,"kinshipDegree",self:getValue("BA1_GRAUPA")) 
    oJsonControl:setProp(oJson,"dateOfAdditionOfUser",self:getValue("BA1_DATINC")) 
    oJsonControl:setProp(oJson,"employeeName",self:getValue("BA1_NOMPRE")) 
    oJsonControl:setProp(oJson,"employeeCpf",self:getValue("BA1_CPFPRE")) 
    oJsonControl:setProp(oJson,"motherSName",self:getValue("BA1_MAE")) 
    oJsonControl:setProp(oJson,"admissionDate",self:getValue("BA1_DATADM")) 
    oJsonControl:setProp(oJson,"motherCpf",self:getValue("BA1_CPFMAE")) 
    oJsonControl:setProp(oJson,"newborn",self:getValue("BA1_RECNAS")) 
    oJsonControl:setProp(oJson,"planCode",self:getValue("BA1_CODPLA")) 
    oJsonControl:setProp(oJson,"planVersion",self:getValue("BA1_VERSAO")) 
    oJsonControl:setProp(oJson,"10YearsOfHealthPlan",self:getValue("BA1_10ANOS")) 
    oJsonControl:setProp(oJson,"issueCard",self:getValue("BA1_EMICAR")) 
    oJsonControl:setProp(oJson,"weddingDate",self:getValue("BA1_DATCAS")) 
    oJsonControl:setProp(oJson,"beneficiaryZipCode",self:getValue("BA1_CEPUSR")) 
    oJsonControl:setProp(oJson,"beneficiaryAddress",self:getValue("BA1_ENDERE")) 
    oJsonControl:setProp(oJson,"addressNumber",self:getValue("BA1_NR_END")) 
    oJsonControl:setProp(oJson,"addressComplement",self:getValue("BA1_COMEND")) 
    oJsonControl:setProp(oJson,"beneficiaryDistrict",self:getValue("BA1_BAIRRO")) 
    oJsonControl:setProp(oJson,"cityCode",self:getValue("BA1_CODMUN")) 
    oJsonControl:setProp(oJson,"beneficiaryCity",self:getValue("BA1_MUNICI")) 
    oJsonControl:setProp(oJson,"beneficiaryState",self:getValue("BA1_ESTADO")) 
    oJsonControl:setProp(oJson,"cityCode",self:getValue("BA1_DDD")) 
    oJsonControl:setProp(oJson,"telephone",self:getValue("BA1_TELEFO")) 
    oJsonControl:setProp(oJson,"professionCode",self:getValue("BA1_CODPRF")) 
    oJsonControl:setProp(oJson,"motherSBirthDate",self:getValue("BA1_DATMAE")) 
    oJsonControl:setProp(oJson,"fatherSName",self:getValue("BA1_PAI")) 
    oJsonControl:setProp(oJson,"fatherCpf",self:getValue("BA1_CPFPAI")) 
    oJsonControl:setProp(oJson,"fatherBirthdate",self:getValue("BA1_DATPAI")) 
    oJsonControl:setProp(oJson,"companyEmplRegistr",self:getValue("BA1_MATEMP")) 
    oJsonControl:setProp(oJson,"formerRegistration",self:getValue("BA1_MATANT")) 
    oJsonControl:setProp(oJson,"oldType",self:getValue("BA1_TIPANT")) 
    oJsonControl:setProp(oJson,"waitPeriodBaseDate",self:getValue("BA1_DATCAR")) 
    oJsonControl:setProp(oJson,"cptBaseDate",self:getValue("BA1_DATCPT")) 
    oJsonControl:setProp(oJson,"changeRange",self:getValue("BA1_MUDFAI")) 
    oJsonControl:setProp(oJson,"chargeRetroactive",self:getValue("BA1_COBRET")) 
    oJsonControl:setProp(oJson,"adjustmentMonth",self:getValue("BA1_MESREA")) 
    oJsonControl:setProp(oJson,"adjustmentIndex",self:getValue("BA1_INDREA")) 
    oJsonControl:setProp(oJson,"charge1StMonth",self:getValue("BA1_CB1AMS")) 
    oJsonControl:setProp(oJson,"benefAndUniversityStud",self:getValue("BA1_UNIVER")) 
    oJsonControl:setProp(oJson,"blockDate",self:getValue("BA1_DATBLO")) 
    oJsonControl:setProp(oJson,"reasonForBlocking",self:getValue("BA1_MOTBLO")) 
    oJsonControl:setProp(oJson,"considerBlocking",self:getValue("BA1_CONSID")) 
    oJsonControl:setProp(oJson,"hospitalizedPatient",self:getValue("BA1_INTERD")) 
    oJsonControl:setProp(oJson,"contractNumber",self:getValue("BA1_NUMCON")) 
    oJsonControl:setProp(oJson,"skinColor",self:getValue("BA1_CORNAT")) 
    oJsonControl:setProp(oJson,"bloodType",self:getValue("BA1_SANGUE")) 
    oJsonControl:setProp(oJson,"firstAppointment",self:getValue("BA1_PRICON")) 
    oJsonControl:setProp(oJson,"lastAppointment",self:getValue("BA1_ULTCON")) 
    oJsonControl:setProp(oJson,"nextAppointment",self:getValue("BA1_PROCON")) 
    oJsonControl:setProp(oJson,"numberOfIdCardCopy",self:getValue("BA1_VIACAR")) 
    oJsonControl:setProp(oJson,"roleCode",self:getValue("BA1_CODFUN")) 
    oJsonControl:setProp(oJson,"unhealthy",self:getValue("BA1_INSALU")) 
    oJsonControl:setProp(oJson,"sector",self:getValue("BA1_CODSET")) 
    oJsonControl:setProp(oJson,"weightGrams",self:getValue("BA1_PESO")) 
    oJsonControl:setProp(oJson,"heightCentimeters",self:getValue("BA1_ALTURA")) 
    oJsonControl:setProp(oJson,"obesity",self:getValue("BA1_OBESO")) 
    oJsonControl:setProp(oJson,"importedRecord",self:getValue("BA1_RGIMP")) 
    oJsonControl:setProp(oJson,"adhesionFeeCharged",self:getValue("BA1_CBTXAD")) 
    oJsonControl:setProp(oJson,"adhesionFeeAmount",self:getValue("BA1_VLTXAD")) 
    oJsonControl:setProp(oJson,"lastCollection",self:getValue("BA1_NUMCOB")) 
    oJsonControl:setProp(oJson,"charged",self:getValue("BA1_JACOBR")) 
    oJsonControl:setProp(oJson,"opcionalAdhFeeCharged",self:getValue("BA1_TXADOP")) 
    oJsonControl:setProp(oJson,"optionalAdhFeeAmount",self:getValue("BA1_VLTXOP")) 
    oJsonControl:setProp(oJson,"initialCollection",self:getValue("BA1_COBINI")) 
    oJsonControl:setProp(oJson,"initialYearMonth",self:getValue("BA1_ANOMES")) 
    oJsonControl:setProp(oJson,"informCoverage",self:getValue("BA1_INFCOB")) 
    oJsonControl:setProp(oJson,"informCoverageGroup",self:getValue("BA1_INFGCB")) 
    oJsonControl:setProp(oJson,"inforPreExistence",self:getValue("BA1_INFPRE")) 
    oJsonControl:setProp(oJson,"certificateNumber",self:getValue("BA1_NUMCER")) 
    oJsonControl:setProp(oJson,"cdExporIssueIdentif",self:getValue("BA1_CDIDEN")) 
    oJsonControl:setProp(oJson,"subInvoiceNumber",self:getValue("BA1_NSUBFT")) 
    oJsonControl:setProp(oJson,"vipBeneficiary",self:getValue("BA1_USRVIP")) 
    oJsonControl:setProp(oJson,"originOperator",self:getValue("BA1_OPEORI")) 
    oJsonControl:setProp(oJson,"destinationOperator",self:getValue("BA1_OPEDES")) 
    oJsonControl:setProp(oJson,"responsibleOperator",self:getValue("BA1_OPERES")) 
    oJsonControl:setProp(oJson,"serviceArea",self:getValue("BA1_LOCATE")) 
    oJsonControl:setProp(oJson,"collectionLocation",self:getValue("BA1_LOCCOB")) 
    oJsonControl:setProp(oJson,"badgeIssueLocation",self:getValue("BA1_LOCEMI")) 
    oJsonControl:setProp(oJson,"locationFAnsCollection",self:getValue("BA1_LOCANS")) 
    oJsonControl:setProp(oJson,"considerSib",self:getValue("BA1_INFSIB")) 
    oJsonControl:setProp(oJson,"considerAns",self:getValue("BA1_INFANS")) 
    oJsonControl:setProp(oJson,"ansStatus",self:getValue("BA1_LOCSIB")) 
    oJsonControl:setProp(oJson,"updateSib",self:getValue("BA1_ATUSIB")) 
    oJsonControl:setProp(oJson,"badgeValidityDate",self:getValue("BA1_DTVLCR")) 
    oJsonControl:setProp(oJson,"ok",self:getValue("BA1_OK")) 
    oJsonControl:setProp(oJson,"importedFile",self:getValue("BA1_IMPORT")) 
    oJsonControl:setProp(oJson,"transferDate",self:getValue("BA1_DATTRA")) 
    oJsonControl:setProp(oJson,"team",self:getValue("BA1_EQUIPE")) 
    oJsonControl:setProp(oJson,"salesRepresentative",self:getValue("BA1_CODVEN")) 
    oJsonControl:setProp(oJson,"salesRepresent2Code",self:getValue("BA1_CODVE2")) 
    oJsonControl:setProp(oJson,"collectionAmount",self:getValue("BA1_FXCOB")) 
    oJsonControl:setProp(oJson,"hadOtherEntries",self:getValue("BA1_OUTLAN")) 
    oJsonControl:setProp(oJson,"education",self:getValue("BA1_ESCOLA")) 
    oJsonControl:setProp(oJson,"originCode",self:getValue("BA1_CDORIG")) 
    oJsonControl:setProp(oJson,"originPost",self:getValue("BA1_PSORIG")) 
    oJsonControl:setProp(oJson,"lastName",self:getValue("BA1_SOBRN")) 
    oJsonControl:setProp(oJson,"ediImportFile",self:getValue("BA1_ARQEDI")) 
    oJsonControl:setProp(oJson,"note",self:getValue("BA1_OBSERV")) 
    oJsonControl:setProp(oJson,"qualifInterviewNumber",self:getValue("BA1_NUMENT")) 
    oJsonControl:setProp(oJson,"interchangePlan",self:getValue("BA1_PLAINT")) 
    oJsonControl:setProp(oJson,"transferDate",self:getValue("BA1_DATREP")) 
    oJsonControl:setProp(oJson,"blockBeneficiaryRegistr",self:getValue("BA1_MATUSB")) 
    oJsonControl:setProp(oJson,"ediStatus",self:getValue("BA1_STAEDI")) 
    oJsonControl:setProp(oJson,"dateOfFirstSend",self:getValue("BA1_PRIENV")) 
    oJsonControl:setProp(oJson,"dateOfLastSend",self:getValue("BA1_ULTENV")) 
    oJsonControl:setProp(oJson,"transmissionErrorCode",self:getValue("BA1_CODERR")) 
    oJsonControl:setProp(oJson,"lastModification",self:getValue("BA1_DATALT")) 
    oJsonControl:setProp(oJson,"collectionRange",self:getValue("BA1_FAICOB")) 
    oJsonControl:setProp(oJson,"typeOfInclusion",self:getValue("BA1_TIPINC")) 
    oJsonControl:setProp(oJson,"transferDestination",self:getValue("BA1_TRADES")) 
    oJsonControl:setProp(oJson,"transferOrigin",self:getValue("BA1_TRAORI")) 
    oJsonControl:setProp(oJson,"transferLotNumber",self:getValue("BA1_LOTTRA")) 
    oJsonControl:setProp(oJson,"blockBilling",self:getValue("BA1_BLOFAT")) 
    oJsonControl:setProp(oJson,"reasonForDeathForSip",self:getValue("BA1_OBTSIP")) 
    oJsonControl:setProp(oJson,"ediRegistration",self:getValue("BA1_MATEDI")) 
    oJsonControl:setProp(oJson,"ansSendDate",self:getValue("BA1_ENVANS")) 
    oJsonControl:setProp(oJson,"ansRegistrationDate",self:getValue("BA1_INCANS")) 
    oJsonControl:setProp(oJson,"dateOfExclusInAns",self:getValue("BA1_EXCANS")) 
    oJsonControl:setProp(oJson,"justificationOfTransfer",self:getValue("BA1_MOTTRA")) 
    oJsonControl:setProp(oJson,"collThisLevel",self:getValue("BA1_COBNIV")) 
    oJsonControl:setProp(oJson,"customerCode",self:getValue("BA1_CODCLI")) 
    oJsonControl:setProp(oJson,"storeCode",self:getValue("BA1_LOJA")) 
    oJsonControl:setProp(oJson,"dueDate",self:getValue("BA1_VENCTO")) 
    oJsonControl:setProp(oJson,"supplier",self:getValue("BA1_CODFOR")) 
    oJsonControl:setProp(oJson,"store",self:getValue("BA1_LOJFOR")) 
    oJsonControl:setProp(oJson,"nameOfPlanHolder",self:getValue("BA1_NOMTIT")) 
    oJsonControl:setProp(oJson,"originOfAddress",self:getValue("BA1_ORIEND")) 
    oJsonControl:setProp(oJson,"plsPortalPassword",self:getValue("BA1_SENHA")) 
    oJsonControl:setProp(oJson,"accessToPortal",self:getValue("BA1_CODACE")) 
    oJsonControl:setProp(oJson,"empCardValidityDate",self:getValue("BA1_DTVLCE")) 
    oJsonControl:setProp(oJson,"portabilityOldPlan",self:getValue("BA1_PLPOR")) 
    oJsonControl:setProp(oJson,"ccoCode",self:getValue("BA1_CODCCO")) 
    oJsonControl:setProp(oJson,"userEMail",self:getValue("BA1_EMAIL")) 
    oJsonControl:setProp(oJson,"dependantCode",self:getValue("BA1_CODDEP")) 
    oJsonControl:setProp(oJson,"indicIfInstallOrNot",self:getValue("BA1_PACOOK")) 
    oJsonControl:setProp(oJson,"typeOfRule",self:getValue("BA1_TREGRA")) 
    oJsonControl:setProp(oJson,"settlementMth",self:getValue("BA1_MESLIQ")) 
    oJsonControl:setProp(oJson,"settlemYear",self:getValue("BA1_ANOLIQ")) 
    oJsonControl:setProp(oJson,"installFixedValue",self:getValue("BA1_VLRFIX")) 
    oJsonControl:setProp(oJson,"adminProcedureNumber",self:getValue("BA1_NREPAD")) 
    oJsonControl:setProp(oJson,"invoiceOutflowType",self:getValue("BA1_CODTES")) 
    oJsonControl:setProp(oJson,"erpProductCode",self:getValue("BA1_CODSB1")) 
    oJsonControl:setProp(oJson,"collectionMessIssueDt",self:getValue("BA1_EMIAVC")) 
    oJsonControl:setProp(oJson,"collectionMessRecDt",self:getValue("BA1_RECAVC")) 
    oJsonControl:setProp(oJson,"birthCityCode",self:getValue("BA1_CDMNAS")) 
    oJsonControl:setProp(oJson,"birthCity",self:getValue("BA1_MUNNAS")) 
    oJsonControl:setProp(oJson,"birthState",self:getValue("BA1_ESTNAS")) 
    oJsonControl:setProp(oJson,"sibReturnDate",self:getValue("BA1_DTRSIB")) 
    oJsonControl:setProp(oJson,"pisPasepMother",self:getValue("BA1_PIPAMA")) 
    oJsonControl:setProp(oJson,"adaptationDate",self:getValue("BA1_DATADP")) 
    oJsonControl:setProp(oJson,"allowsPortalReimburse",self:getValue("BA1_REEWEB")) 
    oJsonControl:setProp(oJson,"addressType",self:getValue("BA1_TIPEND")) 
    oJsonControl:setProp(oJson,"residenceCityCode",self:getValue("BA1_MUNRES")) 
    oJsonControl:setProp(oJson,"livesInAbroad",self:getValue("BA1_RESEXT")) 
    oJsonControl:setProp(oJson,"responsibleForFamily",self:getValue("BA1_RESFAM")) 
    oJsonControl:setProp(oJson,"exemptBeneficiary",self:getValue("BA1_REMIDO")) 
    oJsonControl:setProp(oJson,"cooperativeBeneficiary",self:getValue("BA1_COOPER")) 
    oJsonControl:setProp(oJson,"socialName",self:getValue("BA1_NOMSOC")) 
    oJsonControl:setProp(oJson,"phoneType",self:getValue("BA1_TIPTEL")) 
    oJsonControl:setProp(oJson,"revBenefSName",self:getValue("BA1_CRINOM")) 
    oJsonControl:setProp(oJson,"reviewMotherSName",self:getValue("BA1_CRIMAE")) 
    oJsonControl:setProp(oJson,"natHealthCard",self:getValue("BA1_NRCRNA")) 

Return oJson

Method destroy() Class PLSBa1
	_Super:destroy()
	DelClassIntF()
return