#INCLUDE "PROTHEUS.CH"
#INCLUDE "QUICKSEARCH.CH"
#INCLUDE "TECQ014.CH"

QSSTRUCT TECQ014 DESCRIPTION STR0001 MODULE 28 // "Contratos a Vencer" 

QSMETHOD INIT QSSTRUCT TECQ014
Local cWhere := ""

	QSTABLE "CN9" JOIN "TFJ" ON "TFJ.TFJ_CONTRT = CN9.CN9_NUMERO AND TFJ.TFJ_CONREV = CN9.CN9_REVISA"
	QSTABLE "CN9" JOIN "CNC" ON "CNC.CNC_NUMERO = CN9.CN9_NUMERO AND CNC.CNC_REVISA = CN9.CN9_REVISA"
	QSTABLE "CN9" JOIN "CN1" ON "CN1.CN1_CODIGO = CN9.CN9_TPCTO"
	QSTABLE "CNC" JOIN "SA1" ON "SA1.A1_COD = CNC.CNC_CLIENT AND SA1.A1_LOJA = CNC.CNC_LOJACL"
	
	// campos do SX3 e indices do SIX
	QSPARENTFIELD "CN9_NUMERO" INDEX ORDER 1
	
	// campos do SX3
	QSFIELD "CN9_NUMERO","CN9_DTFIM","A1_NREDUZ","CN9_SALDO"
	
	cWhere := "CN9.CN9_SITUAC = '05' AND CN9.CN9_DTFIM BETWEEN '"+ DTOS(Date()) +"' AND '{1}'"
	
	QSFILTER STR0002 WHERE "CN9.CN9_SITUAC='05' AND CN9.CN9_DTFIM='"+ DTOS(Date()) +"'" // "Hoje" 
	QSFILTER STR0003 WHERE StrTran(cWhere, "{1}", DTOS(Date() + 7)) // "Próximos 7 dias" 
	QSFILTER STR0004 WHERE StrTran(cWhere, "{1}", DTOS(Date() + 30)) // "Próximos 30 dias" 
	QSFILTER STR0005 WHERE StrTran(cWhere, "{1}", DTOS(Date() + 60)) // "Próximos 60 dias"
Return
