#INCLUDE "PROTHEUS.CH"
#INCLUDE "QUICKSEARCH.CH"
#INCLUDE "TECQ012.CH"

QSSTRUCT TECQ012 DESCRIPTION STR0001 MODULE 28 // "Realizado de Locação de Equipamentos" 

QSMETHOD INIT QSSTRUCT TECQ012
Local cWhere := ""
	
	QSTABLE "TEW" JOIN "TFI" ON "TFI.TFI_COD = TEW.TEW_CODEQU"
	QSTABLE "TFI" JOIN "TFL" ON "TFL.TFL_CODIGO = TFI.TFI_CODPAI" 
	QSTABLE "TFL" JOIN "CN9" ON "CN9.CN9_NUMERO = TFL.TFL_CONTRT AND CN9_REVISA = TFL.TFL_CONREV"
	QSTABLE "TEW" LEFT JOIN "SB1" ON "SB1.B1_COD = TEW.TEW_PRODUT"
	
	// campos do SX3 e indices do SIX
	QSPARENTFIELD "TFL_CONTRT" INDEX ORDER 4 
	QSPARENTFIELD "B1_DESC" INDEX ORDER 3 LABEL STR0007 // "Desc. Produto"
	
	// campos do SX3
	QSFIELD "TFL_CONTRT","TEW_BAATD","TEW_DTRINI","TEW_DTRFIM","TEW_DTAMNT"

	cWhere := "TEW.TEW_TIPO = '1' AND CN9.CN9_SITUAC = '05' AND" +;
			" TEW.TEW_DTRINI <= '{1}' AND (LENGTH(RTRIM(LTRIM(TEW.TEW_DTRFIM))) = 0 OR TEW.TEW_DTRFIM >= '"+DTOS(Date())+"')"

	If 'MSSQL' $ TcGetDb()
		cWhere := StrTran(cWhere, 'LENGTH', 'LEN')
	EndIf
	
	QSFILTER STR0003 WHERE StrTran(cWhere, "{1}", DTOS(Date())) // "Hoje" 
	QSFILTER STR0004 WHERE StrTran(cWhere, "{1}", DTOS(Date() -  7)) // "Últimos 7 dias" 
	QSFILTER STR0005 WHERE StrTran(cWhere, "{1}", DTOS(Date() - 30)) // "Últimos 30 dias" 
	QSFILTER STR0006 WHERE StrTran(cWhere, "{1}", DTOS(Date() - 60)) // "Últimos 60 dias" 
Return
