#INCLUDE "PROTHEUS.CH"
#INCLUDE "QUICKSEARCH.CH"
#INCLUDE "TECQ006.CH"

QSSTRUCT TECQ006 DESCRIPTION STR0001 MODULE 28 // "Previsão de Locação de Equipamentos" 

QSMETHOD INIT QSSTRUCT TECQ006
	
	QSTABLE "TFI" JOIN "TFL" ON "TFL.TFL_CODIGO = TFI.TFI_CODPAI"
	QSTABLE "TFL" JOIN "CN9" ON "CN9.CN9_NUMERO = TFL.TFL_CONTRT AND CN9_REVISA = TFL.TFL_CONREV"
	QSTABLE "TFI" LEFT JOIN "SB1" ON "SB1.B1_COD = TFI.TFI_PRODUT"
	
	// campos do SX3 e indices do SIX
	QSPARENTFIELD "TFL_CONTRT" INDEX ORDER 4 
	QSPARENTFIELD "TFI_PRODUT" INDEX ORDER 4 
	
	// campos do SX3
	QSFIELD "TFL_CONTRT","B1_DESC","TFI_QTDVEN","TFI_TOTAL","TFI_PERINI","TFI_PERFIM"

	QSFILTER STR0003 WHERE "CN9.CN9_SITUAC = '05' AND '"+DTOS(Date())+"' BETWEEN TFI.TFI_PERINI AND TFI.TFI_PERFIM" // "Todos" 
Return
