#INCLUDE "BADEFINITION.ch"

NEW ENTITY COMPCONTINGENCIA

//-------------------------------------------------------------------
/*/{Protheus.doc} COMPCONTINGENCIA
Visualiza a comparação de contingências entre marcas

@since   30/04/2020
/*/
//-------------------------------------------------------------------
Class BACompContingencia from BAEntity
	Method Setup( ) CONSTRUCTOR
	Method BuildQuery( )
EndClass

//-------------------------------------------------------------------
/*/{Protheus.doc} Setup
Construtor padrão.

@since   30/04/2020
/*/
//-------------------------------------------------------------------
Method Setup( ) Class BACompContingencia
	_Super:Setup("AuditoriaCont", FACT, "O0F")

	//---------------------------------------------------------
	// Define que a extração da entidade será por mês
	//---------------------------------------------------------
	_Super:SetTpExtr( BYMONTH )
Return

//-------------------------------------------------------------------
/*/{Protheus.doc} BuildQuery
Constrói a query da entidade.

@return aQuery, array, Retorna as consultas da entidade por empresa.

@since   30/04/2020
/*/
//-------------------------------------------------------------------
Method BuildQuery( ) Class BACompContingencia
	Local cQuery     := ""
	Local cQrySelect := ""
	Local cQryFrom   := ""
	Local cQryWhere  := ""
	
	cQrySelect := "SELECT BK_FILIAL, "
	cQrySelect +=        "BK_PROCESSO_JUR, "
	cQrySelect +=        "BK_CLIENTE, "
	cQrySelect +=        "BK_AREA_JURIDICA, "
	cQrySelect +=        "<<KEY_O0E_M1.O0E_MARCA>> AS MARCA1, "
	cQrySelect +=        "<<KEY_O0E_M2.O0E_MARCA>> AS MARCA2, "
	cQrySelect +=        "O0F_VLPROV, "
	cQrySelect +=        "O0F_VAPROV, "
	cQrySelect +=        "O0F_VLPRPO, "
	cQrySelect +=        "O0F_VLPPOA, "
	cQrySelect +=        "O0F_VLPRRE, "
	cQrySelect +=        "O0F_VLPREA, "
	cQrySelect +=        "O0F_VCPROV, "
	cQrySelect +=        "O0F_VJPROV, "
	cQrySelect +=        "O0F_SITUAC, "
	cQrySelect +=        "O0F_VLFINA, "
	cQrySelect +=        "BK_MOTIVO_ENCERRAMENTO, "
	cQrySelect +=        "O0F_DTULAT, "
	cQrySelect +=        "O0F_DTENCE, "
	cQrySelect +=        "O0F_DTREAB, "
	cQrySelect +=        "MOVIMENTACAO, "
	cQrySelect +=        "MUDANCA_AREA, "
	cQrySelect +=        "STATUS_CONTINGENCIA, "
	cQrySelect +=        "VALOR_DESPESA PAGAMENTOS, "
	cQrySelect +=        "STATUS_GARANTIA, "
	cQrySelect +=        "STATUS_POSSIVEL, "
	cQrySelect +=        "STATUS_REMOTO, "
	cQrySelect +=        " '01' AS INSTANCIA "

	cQryFrom   := "FROM ( SELECT A.BK_FILIAL BK_FILIAL, "
	cQryFrom   +=               "COALESCE(A.BK_PROCESSO_JUR, B.BK_PROCESSO_JUR) BK_PROCESSO_JUR, "
	cQryFrom   +=               "COALESCE(A.BK_CLIENTE, B.BK_CLIENTE) BK_CLIENTE, "
	cQryFrom   +=               "B.BK_AREA_JURIDICA BK_AREA_JURIDICA, "
	cQryFrom   +=               "COALESCE(A.BK_MARCA, M.MARCA1) MARCA1, "
	cQryFrom   +=               "B.BK_MARCA MARCA2, "
	cQryFrom   +=               "COALESCE(B.O0F_VLPROV, 0) - COALESCE(A.O0F_VLPROV, 0) O0F_VLPROV, "
	cQryFrom   +=               "COALESCE(B.O0F_VAPROV, 0) - COALESCE(A.O0F_VAPROV, 0) O0F_VAPROV, "
	cQryFrom   +=               "COALESCE(B.O0F_VLPRPO, 0) - COALESCE(A.O0F_VLPRPO, 0) O0F_VLPRPO, "
	cQryFrom   +=               "COALESCE(B.O0F_VLPPOA, 0) - COALESCE(A.O0F_VLPPOA, 0) O0F_VLPPOA, "
	cQryFrom   +=               "COALESCE(B.O0F_VLPRRE, 0) - COALESCE(A.O0F_VLPRRE, 0) O0F_VLPRRE, "
	cQryFrom   +=               "COALESCE(B.O0F_VLPREA, 0) - COALESCE(A.O0F_VLPREA, 0) O0F_VLPREA, "
	cQryFrom   +=               "COALESCE(B.O0F_VCPROV, 0) - COALESCE(A.O0F_VCPROV, 0) O0F_VCPROV, "
	cQryFrom   +=               "COALESCE(B.O0F_VJPROV, 0) - COALESCE(A.O0F_VJPROV, 0) O0F_VJPROV, "
	cQryFrom   +=               "B.O0F_SITUAC O0F_SITUAC, "
	cQryFrom   +=               "COALESCE(B.O0F_VLFINA, 0) O0F_VLFINA, "
	cQryFrom   +=               "COALESCE(B.O0F_VAFINA, 0) O0F_VAFINA, "
	cQryFrom   +=               "B.BK_MOTIVO_ENCERRAMENTO BK_MOTIVO_ENCERRAMENTO, "
	cQryFrom   +=               "B.O0F_DTULAT O0F_DTULAT, "
	cQryFrom   +=               "B.O0F_DTENCE O0F_DTENCE, "
	cQryFrom   +=               "B.O0F_DTREAB O0F_DTREAB, "
	
	//CASE DE MOVIMENTAÇÃO
	cQryFrom   +=               "CASE "
	cQryFrom   +=                  "WHEN COALESCE(A.O0F_SITUAC, ' ') = ' ' "
	cQryFrom   +=                      "AND B.O0F_SITUAC = '1' THEN 'CASO NOVO' "
	cQryFrom   +=                  "WHEN COALESCE(A.O0F_SITUAC, ' ') = ' ' "
	cQryFrom   +=                      "AND B.O0F_SITUAC = '2' THEN 'NOVO ENCERRADO' "
	cQryFrom   +=                  "WHEN A.O0F_SITUAC = '1' "
	cQryFrom   +=                      "AND B.O0F_SITUAC = '2' THEN 'ENCERRADO NO MES' "
	cQryFrom   +=                  "WHEN A.O0F_SITUAC = '2' "
	cQryFrom   +=                      "AND B.O0F_SITUAC = '1' THEN 'CASO REABERTO' "
	cQryFrom   +=                  "WHEN A.O0F_SITUAC = '1' "
	cQryFrom   +=                      "AND B.O0F_SITUAC = '1' THEN 'ANDAMENTO ESTOQUE' "
	cQryFrom   +=                  "ELSE 'DESENV' "
	cQryFrom   +=               "END MOVIMENTACAO, "

	//CASE DE MUDANÇA DE AREA
	cQryFrom   +=               "CASE "
	cQryFrom   +=                  "WHEN COALESCE(A.BK_AREA_JURIDICA, ' ') <> B.BK_AREA_JURIDICA THEN 1 "
	cQryFrom   +=                  "ELSE 0 "
	cQryFrom   +=               "END MUDANCA_AREA, "

	//CASE DE STATUS DE CONTINGENCIA
	cQryFrom   +=               "CASE "
	cQryFrom   +=                  "WHEN A.O0F_SITUAC = '2' "
	cQryFrom   +=                       "AND B.O0F_SITUAC = '1' THEN 'CASO REABERTO' "
	cQryFrom   +=                  "WHEN A.O0F_SITUAC = '1' "
	cQryFrom   +=                       "AND B.O0F_SITUAC = '2' "
	cQryFrom   +=                       "AND COALESCE(A.O0F_VLPROV, 0) = 0 THEN 'BAIXA POR ENCERRAMENTO' "
	cQryFrom   +=                  "WHEN COALESCE(B.VALOR_DESPESA, 0) > "
	cQryFrom   +=                       "COALESCE(A.VALOR_DESPESA, 0) THEN  'BAIXA POR PAGAMENTO' "
	cQryFrom   +=                  "WHEN A.O0F_SITUAC = '1' "
	cQryFrom   +=                       "AND B.O0F_SITUAC = '2' "
	cQryFrom   +=                       "AND COALESCE(B.VALOR_DESPESA, 0) = 0 THEN 'BAIXA POR VITORIA' "
	cQryFrom   +=                  "WHEN A.O0F_SITUAC = '1' "
	cQryFrom   +=                       "AND B.O0F_SITUAC = '2' "
	cQryFrom   +=                       "AND COALESCE(A.O0F_VLPROV, 0) > 0 THEN 'REVERSAO POR NAO UTILIZACAO' "
	cQryFrom   +=                  "WHEN ( COALESCE(A.O0F_VLPROV, 0) = 0  "
	cQryFrom   +=                         "AND COALESCE(B.O0F_VLPROV, 0) > 0 ) THEN 'ADICAO DE PROVISAO' "
	cQryFrom   +=                  "WHEN ( ( COALESCE(B.O0F_VLPRPO, 0) < COALESCE(A.O0F_VLPRPO, 0) "
	cQryFrom   +=                           "OR COALESCE(B.O0F_VLPRRE, 0) < COALESCE(A.O0F_VLPRRE, 0) ) "
	cQryFrom   +=                           "AND COALESCE(B.O0F_VLPROV, 0) > COALESCE(A.O0F_VLPROV, 0) ) "
	cQryFrom   +=                           "OR ( COALESCE(B.O0F_VLPROV, 0) > COALESCE(A.O0F_VLPROV, 0) ) THEN 'AUMENTO DE PROVISAO' "
	cQryFrom   +=                  "WHEN COALESCE(B.O0F_VLPROV, 0) < COALESCE(A.O0F_VLPROV, 0) THEN 'REDUCAO PROVISAO' "
	cQryFrom   +=                  "WHEN COALESCE(B.O0F_VLPROV, 0) = COALESCE(A.O0F_VLPROV, 0) "
	cQryFrom   +=                       "AND COALESCE(B.O0F_VAPROV, 0) > COALESCE(A.O0F_VAPROV, 0) THEN 'CORRECAO MONETARIA' "
	cQryFrom   +=                  "WHEN COALESCE(B.O0F_VLPROV, 0) = 0 "
	cQryFrom   +=                       "AND COALESCE(A.O0F_VLPROV, 0) = 0 THEN 'SEM PROVISAO' "
	cQryFrom   +=                  "WHEN COALESCE(B.O0F_VLPROV, 0) > 0 "
	cQryFrom   +=                       "AND COALESCE(A.O0F_VLPROV, 0) > 0 "
	cQryFrom   +=                       "AND COALESCE(B.O0F_VLPROV, 0) = COALESCE(A.O0F_VLPROV, 0) THEN 'SEM ALTERACAO' "
	cQryFrom   +=                  "ELSE 'DESENV' "
	cQryFrom   +=               "END STATUS_CONTINGENCIA, "

	cQryFrom   +=               "COALESCE(B.VALOR_DESPESA, 0) - COALESCE(A.VALOR_DESPESA, 0) VALOR_DESPESA, "

	//CASE DE STATUS DE GARANTIA
	cQryFrom   +=               "CASE "
	cQryFrom   +=                  "WHEN B.O0H_VLRATU - B.O0H_LEVANT <= 0 THEN 'BAIXA TOTAL' "
	cQryFrom   +=                  "WHEN B.O0H_LEVANT > 0 "
	cQryFrom   +=                       "AND B.O0H_VLRATU - B.O0H_LEVANT > 0 THEN 'BAIXA PARCIAL' "
	cQryFrom   +=                  "WHEN B.O0H_VALOR > A.O0H_VALOR THEN 'ADICAO DE VALOR' "
	cQryFrom   +=                  "WHEN B.O0H_VCPROC > A.O0H_VCPROC "
	cQryFrom   +=                       "OR B.O0H_VJPROV > A.O0H_VJPROV THEN 'CORRECAO MONETARIA' "
	cQryFrom   +=                  "ELSE '0' "
	cQryFrom   +=               "END STATUS_GARANTIA, "

	//CASE DE STATUS POSSIVEL
	cQryFrom   +=               "CASE "
	cQryFrom   +=                  "WHEN ( COALESCE(A.O0F_VLPRPO, 0) = 0 "
	cQryFrom   +=                         "AND COALESCE(B.O0F_VLPRPO, 0) > 0 ) THEN 'ADICAO DE PROVISAO' "
	cQryFrom   +=                  "WHEN ( COALESCE(A.O0F_VLPRPO, 0) > 0 "
	cQryFrom   +=                         "AND COALESCE(B.O0F_VLPRPO, 0) > "
	cQryFrom   +=                         "COALESCE(A.O0F_VLPRPO, 0) ) THEN 'AUMENTO DE PROVISAO' "
	cQryFrom   +=                  "WHEN COALESCE(B.O0F_VLPRPO, 0) < COALESCE(A.O0F_VLPRPO, 0) THEN 'REDUCAO DE PROVISAO' "
	cQryFrom   +=                  "WHEN COALESCE(B.O0F_VLPRPO, 0) = COALESCE(A.O0F_VLPRPO, 0) "
	cQryFrom   +=                       "AND COALESCE(B.O0F_VLPPOA, 0) > COALESCE(A.O0F_VLPPOA, 0) THEN 'CORRECAO MONETARIA' "
	cQryFrom   +=                  "WHEN COALESCE(B.O0F_VLPRPO, 0) = 0 "
	cQryFrom   +=                       "AND COALESCE(A.O0F_VLPRPO, 0) = 0 THEN 'SEM PROVISAO' "
	cQryFrom   +=                  "WHEN COALESCE(B.O0F_VLPRPO, 0) > 0 "
	cQryFrom   +=                       "AND COALESCE(A.O0F_VLPRPO, 0) > 0 "
	cQryFrom   +=                       "AND COALESCE(B.O0F_VLPRPO, 0) = COALESCE(A.O0F_VLPRPO, 0) THEN 'SEM ALTERACAO' "
	cQryFrom   +=                  "ELSE 'DESENV' "
	cQryFrom   +=               "END STATUS_POSSIVEL, "

	//CASE DE STATUS REMOTO
	cQryFrom   +=               "CASE "
	cQryFrom   +=                  "WHEN ( COALESCE(A.O0F_VLPRRE, 0) = 0 "
	cQryFrom   +=                        "AND COALESCE(B.O0F_VLPRRE, 0) > 0 ) THEN 'ADICAO DE PROVISAO' "
	cQryFrom   +=                  "WHEN ( COALESCE(A.O0F_VLPRRE, 0) > 0 "
	cQryFrom   +=                        "AND COALESCE(B.O0F_VLPRRE, 0) > "
	cQryFrom   +=                      "COALESCE(A.O0F_VLPRRE, 0) ) THEN 'AUMENTO DE PROVISAO' "
	cQryFrom   +=                  "WHEN COALESCE(B.O0F_VLPRRE, 0) < COALESCE(A.O0F_VLPRRE, 0) THEN 'REDUCAO DE PROVISAO' "
	cQryFrom   +=                  "WHEN COALESCE(B.O0F_VLPRRE, 0) = COALESCE(A.O0F_VLPRRE, 0) "
	cQryFrom   +=                      "AND COALESCE(B.O0F_VLPREA, 0) > COALESCE(A.O0F_VLPREA, 0) THEN 'CORRECAO MONETARIA'  "
	cQryFrom   +=                  "WHEN COALESCE(B.O0F_VLPRRE, 0) = 0 AND COALESCE(A.O0F_VLPRRE, 0) = 0 THEN 'SEM PROVISAO' "
	cQryFrom   +=                  "WHEN COALESCE(B.O0F_VLPRRE, 0) > 0 "
	cQryFrom   +=                      "AND COALESCE(A.O0F_VLPRRE, 0) > 0 "
	cQryFrom   +=                      "AND COALESCE(B.O0F_VLPRRE, 0) = COALESCE(A.O0F_VLPRRE, 0) THEN 'SEM ALTERACAO' "
	cQryFrom   +=                  "ELSE 'DESENV' "
	cQryFrom   +=               "END STATUS_REMOTO,"  
	cQryFrom   +=                " '01' AS INSTANCIA "
	cQryFrom   +=         "FROM ( SELECT DISTINCT A1.O0E_MARCA MARCA1, "
	cQryFrom   +=                                "B1.O0E_MARCA MARCA2 "
	cQryFrom   +=                "FROM ( SELECT O0E_MARCA "
	cQryFrom   +=                       "FROM <<O0E_COMPANY>> "
	cQryFrom   +=                       "WHERE D_E_L_E_T_ =' ') A1, "
	cQryFrom   +=                     "( SELECT O0E_MARCA "
	cQryFrom   +=                       "FROM <<O0E_COMPANY>> "
	cQryFrom   +=                       "WHERE D_E_L_E_T_ =' ') B1 "
	cQryFrom   +=                "WHERE B1.O0E_MARCA > A1.O0E_MARCA "
	cQryFrom   +=                       dateFilter() 
	cQryFrom   +=                " ) M "

	cQryFrom   +=         "RIGHT JOIN ( SELECT <<KEY_FILIAL_O0F_FILPRO+O0F_FILIAL>> AS BK_FILIAL, "
	cQryFrom   +=                             "<<KEY_NSZ_O0F_FILPRO+O0F_CAJURI>> AS BK_PROCESSO_JUR, "
	cQryFrom   +=                             "<<KEY_SA1_O0F_CCLIEN+O0F_LCLIEN>> AS BK_CLIENTE, "
	cQryFrom   +=                             "<<KEY_NRB_O0F_CAREAJ>> AS BK_AREA_JURIDICA, "
	cQryFrom   +=                             "<<KEY_NQI_O0F_CMOENC>> AS BK_MOTIVO_ENCERRAMENTO, "
	cQryFrom   +=                             "O0F_MARCA BK_MARCA, "
	cQryFrom   +=                             "COALESCE(NULLIF(O0F_DTPROV, ''), '19990101') O0F_DTPROV, "
	cQryFrom   +=                             "COALESCE(O0F_VLPROV, 0) O0F_VLPROV, "
	cQryFrom   +=                             "COALESCE(O0F_VAPROV, 0) O0F_VAPROV, "
	cQryFrom   +=                             "COALESCE(O0F_VLPRPO, 0) O0F_VLPRPO, "
	cQryFrom   +=                             "COALESCE(O0F_VLPPOA, 0) O0F_VLPPOA, "
	cQryFrom   +=                             "COALESCE(O0F_VLPRRE, 0) O0F_VLPRRE, "
	cQryFrom   +=                             "COALESCE(O0F_VLPREA, 0) O0F_VLPREA, "
	cQryFrom   +=                             "COALESCE(NULLIF(O0F_VCPROV, 0), OBJETO_PROV.O0G_CCORPC) O0F_VCPROV, "
	cQryFrom   +=                             "COALESCE(NULLIF(O0F_VJPROV, 0), "
	cQryFrom   +=                             "OBJETO_PROV.O0G_CJURPC) O0F_VJPROV, "
	cQryFrom   +=                             "COALESCE(NULLIF(O0F_DTULAT, ''), '19990101') O0F_DTULAT, "
	cQryFrom   +=                             "O0F_SITUAC, "
	cQryFrom   +=                             "COALESCE(NULLIF(O0F_DTENCE, ''), '19990101') O0F_DTENCE, "
	cQryFrom   +=                             "COALESCE(NULLIF(O0F_DTREAB, ''), '19990101') O0F_DTREAB, "
	cQryFrom   +=                             "O0F_VLFINA, "
	cQryFrom   +=                             "O0F_VAFINA, "
	cQryFrom   +=                             "COALESCE(DESPESA.O0I_VALOR, 0) VALOR_DESPESA, "
	cQryFrom   +=                             "GARANTIA.O0H_LEVANT, "
	cQryFrom   +=                             "GARANTIA.O0H_VALOR, "
	cQryFrom   +=                             "GARANTIA.O0H_VCPROC, "
	cQryFrom   +=                             "GARANTIA.O0H_VJPROV, "
	cQryFrom   +=                             "GARANTIA.O0H_VLRATU "
	cQryFrom   +=                      "FROM <<O0F_COMPANY>> O0F "
	cQryFrom   +=                      "LEFT JOIN <<SA1_COMPANY>> SA1 ON O0F_CCLIEN = A1_COD "
	cQryFrom   +=                                                   "AND O0F_LCLIEN = A1_LOJA "
	cQryFrom   +=                                                   "AND O0F_FILPRO = A1_FILIAL "
	cQryFrom   +=                                                   "AND SA1.D_E_L_E_T_ = ' ' "
	cQryFrom   +=                      "LEFT JOIN <<NRB_COMPANY>> NRB ON O0F_CAREAJ = NRB_COD "
	cQryFrom   +=                                                   "AND O0F_FILPRO = NRB_FILIAL "
	cQryFrom   +=                                                   "AND NRB.D_E_L_E_T_ = ' ' "
	cQryFrom   +=                      "LEFT JOIN <<NQI_COMPANY>> NQI ON O0F_CMOENC = NQI_COD  "
	cQryFrom   +=                                                   "AND O0F_FILPRO = NQI_FILIAL "
	cQryFrom   +=                                                   "AND NQI.D_E_L_E_T_ = ' ' "
	cQryFrom   +=                      "LEFT JOIN (SELECT O0I.O0I_CAJURI, "
	cQryFrom   +=                                        "O0I.O0I_MARCA MARCA, "
	cQryFrom   +=                                        "SUM(O0I.O0I_VALOR) O0I_VALOR "
	cQryFrom   +=                                 "FROM <<O0I_COMPANY>> O0I "
	cQryFrom   +=                                 "JOIN <<NSR_COMPANY>> NSR ON ( NSR.NSR_COD = O0I.O0I_CTPDES "
	cQryFrom   +=                                                               "AND NSR.D_E_L_E_T_ = ' ' "
	cQryFrom   +=                                                               "AND NSR.NSR_ATPROV = '1' ) "
	cQryFrom   +=                                 "WHERE O0I.D_E_L_E_T_ = ' ' "
	cQryFrom   +=                                 "GROUP BY O0I_CAJURI, "
	cQryFrom   +=                                          "O0I.O0I_MARCA) DESPESA "
	cQryFrom   +=                             "ON DESPESA.O0I_CAJURI = O0F.O0F_CAJURI "
	cQryFrom   +=                                "AND DESPESA.MARCA = O0F_MARCA "
	cQryFrom   +=                      "LEFT JOIN (SELECT O0G.O0G_CAJURI, "
	cQryFrom   +=                                        "O0G.O0G_MARCA MARCA, "
	cQryFrom   +=                                        "SUM(O0G.O0G_CCORPC) O0G_CCORPC, "
	cQryFrom   +=                                        "SUM(O0G.O0G_CJURPC) O0G_CJURPC, "
	cQryFrom   +=                                        "SUM(O0G.O0G_VLCONA) O0G_VLCONA, "
	cQryFrom   +=                                        "SUM(O0G.O0G_VLCONT) O0G_VLCONT "
	cQryFrom   +=                                 "FROM <<O0G_COMPANY>> O0G "
	cQryFrom   +=                                 "JOIN <<NQ7_COMPANY>> NQ7 ON ( NQ7.NQ7_COD = O0G.O0G_CPROG "
	cQryFrom   +=                                                               "AND NQ7.D_E_L_E_T_ = ' ' "
	cQryFrom   +=                                                               "AND NQ7.NQ7_TIPO = '1' ) "
	cQryFrom   +=                                 "WHERE  O0G.D_E_L_E_T_ = ' ' "
	cQryFrom   +=                                 "GROUP  BY O0G_CAJURI, "
	cQryFrom   +=                                           "O0G.O0G_MARCA)  OBJETO_PROV "
	cQryFrom   +=                             "ON OBJETO_PROV.O0G_CAJURI = O0F.O0F_CAJURI "
	cQryFrom   +=                                "AND OBJETO_PROV.MARCA = O0F_MARCA "
	cQryFrom   +=                      "LEFT JOIN (SELECT O0H.O0H_CAJURI, "
	cQryFrom   +=                                        "O0H.O0H_MARCA MARCA, "
	cQryFrom   +=                                        "SUM(O0H.O0H_VALOR) O0H_VALOR, "
	cQryFrom   +=                                        "SUM(O0H.O0H_VLRATU) O0H_VLRATU, "
	cQryFrom   +=                                        "SUM(O0H.O0H_VCPROV) O0H_VCPROC, "
	cQryFrom   +=                                        "SUM(O0H.O0H_VJPROV) O0H_VJPROV, "
	cQryFrom   +=                                        "SUM(O0H.O0H_LEVANT) O0H_LEVANT "
	cQryFrom   +=                                 "FROM  <<O0H_COMPANY>> O0H "
	cQryFrom   +=                                 "WHERE O0H.D_E_L_E_T_ = ' ' "
	cQryFrom   +=                                 "GROUP BY O0H.O0H_CAJURI, "
	cQryFrom   +=                                          "O0H.O0H_MARCA) GARANTIA "
	cQryFrom   +=                             "ON GARANTIA.O0H_CAJURI = O0F.O0F_CAJURI "
	cQryFrom   +=                                "AND GARANTIA.MARCA = O0F_MARCA "
	cQryFrom   +=                      "WHERE O0F.D_E_L_E_T_ = ' ') A "
	cQryFrom   +=                 "ON (A.BK_MARCA = M.MARCA1) "
	
	cQryFrom   +=         "RIGHT JOIN ( SELECT <<KEY_FILIAL_O0F_FILPRO>> AS BK_FILIAL, "
	cQryFrom   +=                             "<<KEY_NSZ_O0F_FILPRO+O0F_CAJURI>> AS BK_PROCESSO_JUR, "
	cQryFrom   +=                             "<<KEY_SA1_O0F_CCLIEN+O0F_LCLIEN>>  AS BK_CLIENTE, "
	cQryFrom   +=                             "<<KEY_NRB_O0F_CAREAJ>>  AS BK_AREA_JURIDICA, "
	cQryFrom   +=                             "<<KEY_NQI_O0F_CMOENC>>  AS BK_MOTIVO_ENCERRAMENTO, "
	cQryFrom   +=                             "O0F_MARCA BK_MARCA, "
	cQryFrom   +=                             "COALESCE(NULLIF(O0F_DTPROV, ''), '19990101') O0F_DTPROV, "
	cQryFrom   +=                             "COALESCE(O0F_VLPROV, 0) O0F_VLPROV, "
	cQryFrom   +=                             "COALESCE(O0F_VAPROV, 0) O0F_VAPROV, "
	cQryFrom   +=                             "COALESCE(O0F_VLPRPO, 0) O0F_VLPRPO, "
	cQryFrom   +=                             "COALESCE(O0F_VLPPOA, 0) O0F_VLPPOA, "
	cQryFrom   +=                             "COALESCE(O0F_VLPRRE, 0) O0F_VLPRRE, "
	cQryFrom   +=                             "COALESCE(O0F_VLPREA, 0) O0F_VLPREA, "
	cQryFrom   +=                             "COALESCE(NULLIF(O0F_VCPROV, 0), OBJETO_PROV.O0G_CCORPC) O0F_VCPROV, "
	cQryFrom   +=                             "COALESCE(NULLIF(O0F_VJPROV, 0), OBJETO_PROV.O0G_CJURPC) O0F_VJPROV, "
	cQryFrom   +=                             "COALESCE(NULLIF(O0F_DTULAT, ''), '19990101') O0F_DTULAT, "
	cQryFrom   +=                             "O0F_SITUAC, "
	cQryFrom   +=                             "COALESCE(NULLIF(O0F_DTENCE, ''), '19990101') O0F_DTENCE, "
	cQryFrom   +=                             "COALESCE(NULLIF(O0F_DTREAB, ''), '19990101') O0F_DTREAB, "
	cQryFrom   +=                             "O0F_VLFINA, "
	cQryFrom   +=                             "O0F_VAFINA, "
	cQryFrom   +=                             "COALESCE(DESPESA.O0I_VALOR, 0) VALOR_DESPESA, "
	cQryFrom   +=                             "GARANTIA.O0H_LEVANT, "
	cQryFrom   +=                             "GARANTIA.O0H_VALOR, "
	cQryFrom   +=                             "GARANTIA.O0H_VCPROC, "
	cQryFrom   +=                             "GARANTIA.O0H_VJPROV, "
	cQryFrom   +=                             "GARANTIA.O0H_VLRATU "
	cQryFrom   +=                      "FROM <<O0F_COMPANY>> O0F "
	cQryFrom   +=                           "LEFT JOIN <<SA1_COMPANY>> SA1 ON O0F_CCLIEN = A1_COD "
	cQryFrom   +=                                                            "AND O0F_LCLIEN = A1_LOJA "
	cQryFrom   +=                                                            "AND SA1.D_E_L_E_T_ = ' ' "
	cQryFrom   +=                                                            "AND O0F_FILPRO = A1_FILIAL "
	cQryFrom   +=                           "LEFT JOIN <<NRB_COMPANY>> NRB ON O0F_CAREAJ = NRB_COD "
	cQryFrom   +=                                                            "AND O0F_FILPRO = NRB_FILIAL "
	cQryFrom   +=                                                            "AND NRB.D_E_L_E_T_ = ' ' "
	cQryFrom   +=                           "LEFT JOIN <<NQI_COMPANY>> NQI ON O0F_CMOENC = NQI_COD "
	cQryFrom   +=                                                            "AND O0F_FILPRO = NQI_FILIAL "
	cQryFrom   +=                                                            "AND NQI.D_E_L_E_T_ = ' ' "
	cQryFrom   +=                           "LEFT JOIN (SELECT O0I.O0I_CAJURI, "
	cQryFrom   +=                                             "O0I.O0I_MARCA MARCA, "
	cQryFrom   +=                                             "SUM(O0I.O0I_VALOR) O0I_VALOR "
	cQryFrom   +=                                      "FROM <<O0I_COMPANY>> O0I "
	cQryFrom   +=                                      "JOIN <<NSR_COMPANY>> NSR "
	cQryFrom   +=                                        "ON ( NSR.NSR_COD = O0I.O0I_CTPDES "
	cQryFrom   +=                                             "AND NSR.D_E_L_E_T_ = ' ' "
	cQryFrom   +=                                             "AND NSR.NSR_ATPROV = '1' ) "
	cQryFrom   +=                                      "WHERE O0I.D_E_L_E_T_ = ' ' "
	cQryFrom   +=                                      "GROUP  BY O0I_CAJURI, O0I.O0I_MARCA) DESPESA "
	cQryFrom   +=                                 "ON DESPESA.O0I_CAJURI = O0F.O0F_CAJURI "
	cQryFrom   +=                                    "AND DESPESA.MARCA = O0F_MARCA "
	
	cQryFrom   +=                           "LEFT JOIN (SELECT O0G.O0G_CAJURI, "
	cQryFrom   +=                                             "O0G.O0G_MARCA MARCA, "
	cQryFrom   +=                                             "SUM(O0G.O0G_CCORPC) O0G_CCORPC, "
	cQryFrom   +=                                             "SUM(O0G.O0G_CJURPC) O0G_CJURPC, "
	cQryFrom   +=                                             "SUM(O0G.O0G_VLCONA) O0G_VLCONA, "
	cQryFrom   +=                                             "SUM(O0G.O0G_VLCONT) O0G_VLCONT "
	cQryFrom   +=                                      "FROM <<O0G_COMPANY>> O0G "
	cQryFrom   +=                                           "JOIN <<NQ7_COMPANY>> NQ7 "
	cQryFrom   +=                                             "ON ( NQ7.NQ7_COD = O0G.O0G_CPROG "
	cQryFrom   +=                                                  "AND NQ7.D_E_L_E_T_ = ' ' "
	cQryFrom   +=                                                  "AND NQ7.NQ7_TIPO = '1' ) "
	cQryFrom   +=                                      "WHERE O0G.D_E_L_E_T_ = ' ' "
	cQryFrom   +=                                      "GROUP BY O0G_CAJURI, O0G.O0G_MARCA) OBJETO_PROV "
	cQryFrom   +=                                 "ON OBJETO_PROV.O0G_CAJURI = O0F.O0F_CAJURI "
	cQryFrom   +=                                    "AND OBJETO_PROV.MARCA = O0F_MARCA "
	cQryFrom   +=                           "LEFT JOIN (SELECT O0H.O0H_CAJURI, "
	cQryFrom   +=                                             "O0H.O0H_MARCA MARCA, "
	cQryFrom   +=                                             "SUM(O0H.O0H_VALOR) O0H_VALOR, "
	cQryFrom   +=                                             "SUM(O0H.O0H_VLRATU) O0H_VLRATU, "
	cQryFrom   +=                                             "SUM(O0H.O0H_VCPROV) O0H_VCPROC, "
	cQryFrom   +=                                             "SUM(O0H.O0H_VJPROV) O0H_VJPROV, "
	cQryFrom   +=                                             "SUM(O0H.O0H_LEVANT) O0H_LEVANT "
	cQryFrom   +=                                      "FROM   <<O0H_COMPANY>> O0H "
	cQryFrom   +=                                      "WHERE  O0H.D_E_L_E_T_ = ' ' "
	cQryFrom   +=                                      "GROUP  BY O0H.O0H_CAJURI, "
	cQryFrom   +=                                                "O0H.O0H_MARCA) GARANTIA "
	cQryFrom   +=                                 "ON GARANTIA.O0H_CAJURI = O0F.O0F_CAJURI "
	cQryFrom   +=                                    "AND GARANTIA.MARCA = O0F_MARCA "
	cQryFrom   +=                      "WHERE  O0F.D_E_L_E_T_ = ' ') B "
	cQryFrom   +=                 "ON ( A.BK_PROCESSO_JUR = B.BK_PROCESSO_JUR "
	cQryFrom   +=                      "AND B.BK_MARCA = M.MARCA2 ) "
	cQryFrom   +=         "WHERE  A.BK_MARCA = M.MARCA1 "
	cQryFrom   +=                "AND B.BK_MARCA = M.MARCA2 "

	//UNION ALL
	cQryFrom   +=         "UNION ALL "
	cQryFrom   +=         "SELECT <<KEY_FILIAL_O0F_FILIAL>> AS BK_FILIAL, "
	cQryFrom   +=                "<<KEY_NSZ_O0F_FILPRO+O0F_CAJURI>> AS BK_PROCESSO_JUR, "
	cQryFrom   +=                "<<KEY_SA1_O0F_CCLIEN+O0F_LCLIEN>> AS BK_CLIENTE, "
	cQryFrom   +=                "<<KEY_NRB_O0F_CAREAJ>> AS BK_AREA_JURIDICA, "
	cQryFrom   +=                "M.MARCA1, "
	cQryFrom   +=                "M.MARCA2, "
	cQryFrom   +=                "COALESCE(C.O0F_VLPROV, 0) O0F_VLPROV, "
	cQryFrom   +=                "COALESCE(C.O0F_VAPROV, 0) O0F_VAPROV, "
	cQryFrom   +=                "COALESCE(C.O0F_VLPRPO, 0) O0F_VLPRPO, "
	cQryFrom   +=                "COALESCE(C.O0F_VLPPOA, 0) O0F_VLPPOA, "
	cQryFrom   +=                "COALESCE(C.O0F_VLPRRE, 0) O0F_VLPRRE, "
	cQryFrom   +=                "COALESCE(C.O0F_VLPREA, 0) O0F_VLPREA, "
	cQryFrom   +=                "COALESCE(NULLIF(C.O0F_VCPROV, 0), OBJETO_PROV.O0G_CCORPC) O0F_VCPROV, "
	cQryFrom   +=                "COALESCE(NULLIF(C.O0F_VJPROV, 0), OBJETO_PROV.O0G_CJURPC) O0F_VJPROV, "
	cQryFrom   +=                "C.O0F_SITUAC O0F_SITUAC, "
	cQryFrom   +=                "COALESCE(C.O0F_VLFINA, 0) O0F_VLFINA, "
	cQryFrom   +=                "COALESCE(C.O0F_VAFINA, 0) O0F_VAFINA, "
	cQryFrom   +=                "<<KEY_NQI_O0F_CMOENC>>  AS BK_MOTIVO_ENCERRAMENTO, "
	cQryFrom   +=                "COALESCE(NULLIF(C.O0F_DTULAT, ''), '19990101') O0F_DTULAT, "
	cQryFrom   +=                "COALESCE(NULLIF(C.O0F_DTENCE, ''), '19990101') O0F_DTENCE, "
	cQryFrom   +=                "COALESCE(NULLIF(C.O0F_DTREAB, ''), '19990101') O0F_DTREAB, "

	//CASE MOVIMENTAÇÃO
	cQryFrom   +=                "CASE "
	cQryFrom   +=                   "WHEN C.O0F_SITUAC = '2' "
	cQryFrom   +=                        "AND C.O0F_DTREAB = '      ' THEN 'NOVO ENCERRADO' "
	cQryFrom   +=                   "WHEN C.O0F_SITUAC = '2' "
	cQryFrom   +=                        "AND C.O0F_DTREAB > '      ' THEN 'CASO REABERTO' "
	cQryFrom   +=                   "ELSE 'CASO NOVO' "
	cQryFrom   +=                "END MOVIMENTACAO, 0 "
	cQryFrom   +=                "MUDANCA_AREA, "

	//CASE STATUS CONTINGENCIA
	cQryFrom   +=                "CASE "
	cQryFrom   +=                   "WHEN COALESCE(O0F_VLPROV, 0) > 0 THEN 'ADICAO DE PROVISAO' "
	cQryFrom   +=                   "WHEN COALESCE(O0F_VLPROV, 0) = 0 THEN 'SEM PROVISAO' "
	cQryFrom   +=                   "ELSE 'CASO NOVO' "
	cQryFrom   +=                "END STATUS_CONTINGENCIA, "
	cQryFrom   +=                "COALESCE(DESPESA.O0I_VALOR, 0) VALOR_DESPESA, "

	//CASE STATUS GARANTIA
	cQryFrom   +=                "CASE "
	cQryFrom   +=                   "WHEN O0H_VLRATU - O0H_LEVANT <= 0 THEN 'BAIXA TOTAL' "
	cQryFrom   +=                   "WHEN O0H_LEVANT > 0 "
	cQryFrom   +=                        "AND O0H_VLRATU - O0H_LEVANT > 0 THEN 'BAIXA PARCIAL' "
	cQryFrom   +=                   "WHEN O0H_VALOR > 0 THEN 'ADICAO DE VALOR' "
	cQryFrom   +=                   "ELSE '0' "
	cQryFrom   +=                "END STATUS_GARANTIA, "
	cQryFrom   +=                "CASE "
	cQryFrom   +=                   "WHEN COALESCE(O0F_VLPRPO, 0) > 0 THEN 'ADICAO DE PROVISAO' "
	cQryFrom   +=                   "WHEN COALESCE(O0F_VLPRPO, 0) = 0 THEN 'SEM PROVISAO' "
	cQryFrom   +=                   "ELSE 'CASO NOVO' "
	cQryFrom   +=                "END STATUS_POSSIVEL, "

	//CASE STATUS REMOTO
	cQryFrom   +=                "CASE "
	cQryFrom   +=                   "WHEN COALESCE(O0F_VLPRRE, 0) > 0 THEN 'ADICAO DE PROVISAO' "
	cQryFrom   +=                   "WHEN COALESCE(O0F_VLPRRE, 0) = 0 THEN 'SEM PROVISAO' "
	cQryFrom   +=                   "ELSE 'CASO NOVO' "
	cQryFrom   +=                "END STATUS_REMOTO,"  
	cQryFrom   += 				" '01' AS INSTANCIA "
	cQryFrom   +=                "FROM   (SELECT DISTINCT A1.O0E_MARCA MARCA1, "
	cQryFrom   +=                "B1.O0E_MARCA MARCA2 "
	
	cQryFrom   +=         "FROM ( SELECT O0E_MARCA FROM <<O0E_COMPANY>> WHERE  D_E_L_E_T_ = ' ') A1, "
	cQryFrom   +=              "( SELECT O0E_MARCA FROM <<O0E_COMPANY>> WHERE  D_E_L_E_T_ = ' ') B1 "
	cQryFrom   +=         "WHERE B1.O0E_MARCA > A1.O0E_MARCA "
	cQryFrom   +=                dateFilter()
	cQryFrom   +=                ") M "
	cQryFrom   +=         "JOIN <<O0F_COMPANY>> C ON C.O0F_MARCA = M.MARCA2 "
	cQryFrom   +=                                   "AND C.D_E_L_E_T_ = ' ' "
	cQryFrom   +=                                   "AND NOT EXISTS (SELECT 1 "
	cQryFrom   +=                                                    "FROM   <<O0F_COMPANY>> "
	cQryFrom   +=                                                    "WHERE  O0F_MARCA = M.MARCA1 "
	cQryFrom   +=                                                           "AND O0F_CAJURI = C.O0F_CAJURI "
	cQryFrom   +=                                                           "AND D_E_L_E_T_ = ' ') "
	cQryFrom   +=         "LEFT JOIN (SELECT O0I.O0I_CAJURI, "
	cQryFrom   +=                            "O0I.O0I_MARCA MARCA, "
	cQryFrom   +=                            "SUM(O0I.O0I_VALOR) O0I_VALOR "
	cQryFrom   +=                           "FROM <<O0I_COMPANY>> O0I "
	cQryFrom   +=                                "JOIN <<NSR_COMPANY>> NSR "
	cQryFrom   +=                                  "ON ( NSR.NSR_COD = O0I.O0I_CTPDES "
	cQryFrom   +=                                       "AND NSR.D_E_L_E_T_ = ' ' "
	cQryFrom   +=                                       "AND NSR.NSR_ATPROV = '1' ) "
	cQryFrom   +=                           "WHERE  O0I.D_E_L_E_T_ = ' ' "
	cQryFrom   +=                           "GROUP  BY O0I_CAJURI, "
	cQryFrom   +=                                     "O0I.O0I_MARCA) DESPESA "
	cQryFrom   +=                       "ON DESPESA.O0I_CAJURI = C.O0F_CAJURI "
	cQryFrom   +=                          "AND DESPESA.MARCA = C.O0F_MARCA "
	
	cQryFrom   +=         "LEFT JOIN (SELECT O0G.O0G_CAJURI, "
	cQryFrom   +=                           "O0G.O0G_MARCA MARCA, "
	cQryFrom   +=                           "SUM(O0G.O0G_CCORPC) O0G_CCORPC, "
	cQryFrom   +=                           "SUM(O0G.O0G_CJURPC) O0G_CJURPC, "
	cQryFrom   +=                           "SUM(O0G.O0G_VLCONA) O0G_VLCONA, "
	cQryFrom   +=                           "SUM(O0G.O0G_VLCONT) O0G_VLCONT "
	cQryFrom   +=                    "FROM <<O0G_COMPANY>> O0G "
	cQryFrom   +=                         "JOIN <<NQ7_COMPANY>> NQ7 "
	cQryFrom   +=                           "ON ( NQ7.NQ7_COD = O0G.O0G_CPROG "
	cQryFrom   +=                                "AND NQ7.D_E_L_E_T_ = ' ' "
	cQryFrom   +=                                "AND NQ7.NQ7_TIPO = '1' ) "
	cQryFrom   +=                    "WHERE  O0G.D_E_L_E_T_ = ' ' "
	cQryFrom   +=                    "GROUP  BY O0G_CAJURI, "
	cQryFrom   +=                              "O0G.O0G_MARCA) OBJETO_PROV "
	cQryFrom   +=                "ON OBJETO_PROV.O0G_CAJURI = C.O0F_CAJURI "
	cQryFrom   +=                          "AND OBJETO_PROV.MARCA = C.O0F_MARCA "
	cQryFrom   +=         "LEFT JOIN (SELECT O0H.O0H_CAJURI, "
	cQryFrom   +=                           "O0H.O0H_MARCA MARCA, "
	cQryFrom   +=                           "SUM(O0H.O0H_VALOR)  O0H_VALOR, "
	cQryFrom   +=                           "SUM(O0H.O0H_VLRATU) O0H_VLRATU, "
	cQryFrom   +=                           "SUM(O0H.O0H_VCPROV) O0H_VCPROC, "
	cQryFrom   +=                           "SUM(O0H.O0H_VJPROV) O0H_VJPROV, "
	cQryFrom   +=                           "SUM(O0H.O0H_LEVANT) O0H_LEVANT "
	cQryFrom   +=                    "FROM   <<O0H_COMPANY>> O0H "
	cQryFrom   +=                    "WHERE  O0H.D_E_L_E_T_ = ' ' "
	cQryFrom   +=                    "GROUP  BY O0H.O0H_CAJURI, "
	cQryFrom   +=                              "O0H.O0H_MARCA) GARANTIA "
	cQryFrom   +=                "ON GARANTIA.O0H_CAJURI = C.O0F_CAJURI "
	cQryFrom   +=                   "AND GARANTIA.MARCA = C.O0F_MARCA) F "
	cQryFrom   +=         "JOIN <<O0E_COMPANY>> M1 ON ( F.MARCA1 = M1.O0E_MARCA ) "
	cQryFrom   +=         "JOIN <<O0E_COMPANY>> M2 ON ( F.MARCA2 = M2.O0E_MARCA ) "
	cQryWhere  := "WHERE  F.MARCA1 IS NOT NULL "
	cQryWhere  +=        "AND F.MARCA2 IS NOT NULL "

	cQuery := cQrySelect + cQryFrom + cQryWhere

Return cQuery

//-------------------------------------------------------------------
/*/{Protheus.doc} dateFilter
Cria o filtro de data

@return cReturn - Filtro de Datas

@since   06/02/2018
/*/
//-------------------------------------------------------------------
Static Function dateFilter()
Local cReturn    := ""
Local cDatabase  := Upper( SGDB() )
	
	If "ORACLE" $ cDatabase
		cReturn := "AND SUBSTRING(B1.O0E_MARCA,1,6) = SUBSTR(<<FINAL_DATE>>,1,6) "
		cReturn += "AND SUBSTRING(A1.O0E_MARCA,1,6) IN ( "
		cReturn +=     "to_char(add_months(to_date(B1.O0E_MARCA,'yyyymmdd'),-1),'yyyymm'), "
		cReturn +=     "to_char(add_months(to_date(B1.O0E_MARCA,'yyyymmdd'),-2),'yyyymm'), "
		cReturn +=     "to_char(add_months(to_date(B1.O0E_MARCA,'yyyymmdd'),-3),'yyyymm'), "
		cReturn +=     "to_char(add_months(to_date(B1.O0E_MARCA,'yyyymmdd'),-6),'yyyymm'), "
		cReturn +=     "to_char(add_months(to_date(B1.O0E_MARCA,'yyyymmdd'),-11),'yyyymm'), "
		cReturn +=     "to_char(add_months(to_date(B1.O0E_MARCA,'yyyymmdd'),-12),'yyyymm')) "
	Elseif "POSTGRES" $ cDatabase
		cReturn := "AND SUBSTRING(B1.O0E_MARCA,1,6) = SUBSTRING(<<FINAL_DATE>>,1,6) "
		cReturn += "AND SUBSTRING(A1.O0E_MARCA,1,6) IN ( "
		cReturn +=     "TO_CHAR(TO_DATE(B1.O0E_MARCA,'YYYYMMDD') - 'INTERVAL 1 MONTH','YYYYMM'), "
		cReturn +=     "TO_CHAR(TO_DATE(B1.O0E_MARCA,'YYYYMMDD') - 'INTERVAL 2 MONTH','YYYYMM'), "
		cReturn +=     "TO_CHAR(TO_DATE(B1.O0E_MARCA,'YYYYMMDD') - 'INTERVAL 3 MONTH','YYYYMM'), "
		cReturn +=     "TO_CHAR(TO_DATE(B1.O0E_MARCA,'YYYYMMDD') - 'INTERVAL 6 MONTH','YYYYMM'), "
		cReturn +=     "TO_CHAR(TO_DATE(B1.O0E_MARCA,'YYYYMMDD') - 'INTERVAL 11 MONTH','YYYYMM'), "
		cReturn +=     "TO_CHAR(TO_DATE(B1.O0E_MARCA,'YYYYMMDD') - 'INTERVAL 12 MONTH','YYYYMM')) "
	Else 
		cReturn := "AND LEFT(B1.O0E_MARCA,6) = LEFT(<<FINAL_DATE>>,6) "
		cReturn += "AND LEFT(A1.O0E_MARCA,6) IN ( "
		cReturn +=      "LEFT(CONVERT(VARCHAR(6),dateadd(month,-1,CONVERT(DATE,B1.O0E_MARCA,112)),112), 6), "
		cReturn +=      "LEFT(CONVERT(VARCHAR(6),dateadd(month,-2,CONVERT(DATE,B1.O0E_MARCA,112)),112), 6), "
		cReturn +=      "LEFT(CONVERT(VARCHAR(6),dateadd(month,-3,CONVERT(DATE,B1.O0E_MARCA,112)),112), 6), "
		cReturn +=      "LEFT(CONVERT(VARCHAR(6),dateadd(month,-6,CONVERT(DATE,B1.O0E_MARCA,112)),112), 6), "
		cReturn +=      "LEFT(CONVERT(VARCHAR(6),dateadd(month,-11,CONVERT(DATE,B1.O0E_MARCA,112)),112), 6), "
		cReturn +=      "LEFT(CONVERT(VARCHAR(6),dateadd(month,-12,CONVERT(DATE,B1.O0E_MARCA,112)),112), 6)) "
	EndIf
	
Return cReturn
