#include "tlpp-core.th"

namespace pc.products

static __oActiveData  as Object

//------------------------------------------------------------------------------
/*/{Protheus.doc} ProductsDataFactory
	Classe Protheus Factory
	@type		Class
	@sample		ProductsDataFactory:New()
	@author		Lucas Panão / Squad CRM & Faturamento
	@since		27/11/2023
	@version	12.1.2310
/*/
//------------------------------------------------------------------------------
Class ProductsDataFactory
	Static Method getData() as object
EndClass

//------------------------------------------------------------------------------
/*/{Protheus.doc} getData
	Retorna o tipo de objeto utilizado para consulta.
	@type		method
	@return		_Object,_oActiveData
	@author		Lucas Panão / Squad CRM & Faturamento
	@since		27/11/2023
	@version	12.1.2310
/*/
//------------------------------------------------------------------------------
Method getData() as Object class ProductsDataFactory
	If __oActiveData == Nil
		__oActiveData := ProductsProtheusData():new()
	EndIf
Return __oActiveData
