CREATE PROCEDURE CTBA231A_## (
	@IN_HAGLUT           VARCHAR(231), 
	@IN_MVPAR05          INTEGER,
	@IN_MVPAR14          INTEGER,	
	@IN_FILIAL           CHAR( 'CT2_FILIAL' ),
   @IN_TRANSACTION      CHAR(1),
	@OUT_RET  INTEGER OUTPUT) AS
BEGIN
   IF @IN_MVPAR14 = 1 BEGIN
      EXEC CTBA231C_##  @IN_HAGLUT, @IN_MVPAR05, @IN_FILIAL, @IN_TRANSACTION, @OUT_RET OUTPUT
   END
   ELSE BEGIN
      EXEC CTBA231D_##  @IN_HAGLUT, @IN_FILIAL, @IN_TRANSACTION, @OUT_RET OUTPUT
   END
   SELECT @OUT_RET=1
END