#INCLUDE "PROTHEUS.CH"
#INCLUDE "APWEBSRV.CH"

/* ===============================================================================
WSDL Location    http://172.16.33.123:81/webservice/RHEMPLOYEEREGISTRATION.apw?WSDL
Gerado em        01/04/13 09:30:13
Observações      Código-Fonte gerado por ADVPL WSDL Client 1.120703
                 Alterações neste arquivo podem causar funcionamento incorreto
                 e serão perdidas caso o código-fonte seja gerado novamente.
=============================================================================== */

User Function _OONNZPY ; Return  // "dummy" function - Internal Use 

/* -------------------------------------------------------------------------------
WSDL Service WSRHEMPLOYEEREGISTRATION
------------------------------------------------------------------------------- */

WSCLIENT WSRHEMPLOYEEREGISTRATION

	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD RESET
	WSMETHOD CLONE
	WSMETHOD GETMESSAGE
	WSMETHOD GETREGEMPLOYEE

	WSDATA   _URL                      AS String
	WSDATA   _HEADOUT                  AS Array of String
	WSDATA   _COOKIES                  AS Array of String
	WSDATA   cEMPLOYEEFIL              AS string
	WSDATA   cREGISTRATION             AS string
	WSDATA   cEMPLOYEEEMP              AS string
	WSDATA   oWSGETMESSAGERESULT       AS RHEMPLOYEEREGISTRATION_DATAMESSAGES
	WSDATA   oWSGETREGEMPLOYEERESULT   AS RHEMPLOYEEREGISTRATION_FIELDSGROUP

ENDWSCLIENT

WSMETHOD NEW WSCLIENT WSRHEMPLOYEEREGISTRATION
::Init()
If !FindFunction("XMLCHILDEX")
	UserException("O Código-Fonte Client atual requer os executáveis do Protheus Build [7.00.120420A-20120726] ou superior. Atualize o Protheus ou gere o Código-Fonte novamente utilizando o Build atual.")
EndIf
Return Self

WSMETHOD INIT WSCLIENT WSRHEMPLOYEEREGISTRATION
	::oWSGETMESSAGERESULT := RHEMPLOYEEREGISTRATION_DATAMESSAGES():New()
	::oWSGETREGEMPLOYEERESULT := RHEMPLOYEEREGISTRATION_FIELDSGROUP():New()
Return

WSMETHOD RESET WSCLIENT WSRHEMPLOYEEREGISTRATION
	::cEMPLOYEEFIL       := NIL 
	::cREGISTRATION      := NIL 
	::oWSGETMESSAGERESULT := NIL 
	::oWSGETREGEMPLOYEERESULT := NIL 
	::Init()
Return

WSMETHOD CLONE WSCLIENT WSRHEMPLOYEEREGISTRATION
Local oClone := WSRHEMPLOYEEREGISTRATION():New()
	oClone:_URL          := ::_URL 
	oClone:cEMPLOYEEFIL  := ::cEMPLOYEEFIL
	oClone:cREGISTRATION := ::cREGISTRATION
	oClone:oWSGETMESSAGERESULT :=  IIF(::oWSGETMESSAGERESULT = NIL , NIL ,::oWSGETMESSAGERESULT:Clone() )
	oClone:oWSGETREGEMPLOYEERESULT :=  IIF(::oWSGETREGEMPLOYEERESULT = NIL , NIL ,::oWSGETREGEMPLOYEERESULT:Clone() )
Return oClone

// WSDL Method GETMESSAGE of Service WSRHEMPLOYEEREGISTRATION

WSMETHOD GETMESSAGE WSSEND cEMPLOYEEFIL,cREGISTRATION WSRECEIVE oWSGETMESSAGERESULT WSCLIENT WSRHEMPLOYEEREGISTRATION
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<GETMESSAGE xmlns="http://172.16.33.123:81/">'
cSoap += WSSoapValue("EMPLOYEEFIL", ::cEMPLOYEEFIL, cEMPLOYEEFIL , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("REGISTRATION", ::cREGISTRATION, cREGISTRATION , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += "</GETMESSAGE>"

oXmlRet := SvcSoapCall(	Self,cSoap,; 
	"http://172.16.33.123:81/GETMESSAGE",; 
	"DOCUMENT","http://172.16.33.123:81/",,"1.031217",; 
	"http://172.16.33.123:81/webservice/RHEMPLOYEEREGISTRATION.apw")

::Init()
::oWSGETMESSAGERESULT:SoapRecv( WSAdvValue( oXmlRet,"_GETMESSAGERESPONSE:_GETMESSAGERESULT","DATAMESSAGES",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.

// WSDL Method GETREGEMPLOYEE of Service WSRHEMPLOYEEREGISTRATION

WSMETHOD GETREGEMPLOYEE WSSEND cEMPLOYEEFIL,cREGISTRATION,cEMPLOYEEEMP WSRECEIVE oWSGETREGEMPLOYEERESULT WSCLIENT WSRHEMPLOYEEREGISTRATION
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<GETREGEMPLOYEE xmlns="http://172.16.33.123:81/">'
cSoap += WSSoapValue("EMPLOYEEFIL", ::cEMPLOYEEFIL, cEMPLOYEEFIL , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("REGISTRATION", ::cREGISTRATION, cREGISTRATION , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("EMPLOYEEEMP", ::cEMPLOYEEEMP, cEMPLOYEEEMP , "string", .T. , .F., 0 , NIL, .F.) 
cSoap += "</GETREGEMPLOYEE>"

oXmlRet := SvcSoapCall(	Self,cSoap,; 
	"http://172.16.33.123:81/GETREGEMPLOYEE",; 
	"DOCUMENT","http://172.16.33.123:81/",,"1.031217",; 
	"http://172.16.33.123:81/webservice/RHEMPLOYEEREGISTRATION.apw")

::Init()
::oWSGETREGEMPLOYEERESULT:SoapRecv( WSAdvValue( oXmlRet,"_GETREGEMPLOYEERESPONSE:_GETREGEMPLOYEERESULT","FIELDSGROUP",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.


// WSDL Data Structure DATAMESSAGES

WSSTRUCT RHEMPLOYEEREGISTRATION_DATAMESSAGES
	WSDATA   cCOMPANYMESSAGE           AS string
	WSDATA   cEMPLOYEEMESSAGE          AS string
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT RHEMPLOYEEREGISTRATION_DATAMESSAGES
	::Init()
Return Self

WSMETHOD INIT WSCLIENT RHEMPLOYEEREGISTRATION_DATAMESSAGES
Return

WSMETHOD CLONE WSCLIENT RHEMPLOYEEREGISTRATION_DATAMESSAGES
	Local oClone := RHEMPLOYEEREGISTRATION_DATAMESSAGES():NEW()
	oClone:cCOMPANYMESSAGE      := ::cCOMPANYMESSAGE
	oClone:cEMPLOYEEMESSAGE     := ::cEMPLOYEEMESSAGE
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT RHEMPLOYEEREGISTRATION_DATAMESSAGES
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::cCOMPANYMESSAGE    :=  WSAdvValue( oResponse,"_COMPANYMESSAGE","string",NIL,"Property cCOMPANYMESSAGE as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cEMPLOYEEMESSAGE   :=  WSAdvValue( oResponse,"_EMPLOYEEMESSAGE","string",NIL,"Property cEMPLOYEEMESSAGE as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
Return

// WSDL Data Structure FIELDSGROUP

WSSTRUCT RHEMPLOYEEREGISTRATION_FIELDSGROUP
	WSDATA   cEMPLOYEEIMG              AS base64Binary OPTIONAL
	WSDATA   oWSLISTOFFIELDSGROUP      AS RHEMPLOYEEREGISTRATION_ARRAYOFFIELDSSTRUCT
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT RHEMPLOYEEREGISTRATION_FIELDSGROUP
	::Init()
Return Self

WSMETHOD INIT WSCLIENT RHEMPLOYEEREGISTRATION_FIELDSGROUP
Return

WSMETHOD CLONE WSCLIENT RHEMPLOYEEREGISTRATION_FIELDSGROUP
	Local oClone := RHEMPLOYEEREGISTRATION_FIELDSGROUP():NEW()
	oClone:cEMPLOYEEIMG         := ::cEMPLOYEEIMG
	oClone:oWSLISTOFFIELDSGROUP := IIF(::oWSLISTOFFIELDSGROUP = NIL , NIL , ::oWSLISTOFFIELDSGROUP:Clone() )
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT RHEMPLOYEEREGISTRATION_FIELDSGROUP
	Local oNode2
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::cEMPLOYEEIMG       :=  WSAdvValue( oResponse,"_EMPLOYEEIMG","base64Binary",NIL,NIL,NIL,"SB",NIL,NIL) 
	oNode2 :=  WSAdvValue( oResponse,"_LISTOFFIELDSGROUP","ARRAYOFFIELDSSTRUCT",NIL,"Property oWSLISTOFFIELDSGROUP as s0:ARRAYOFFIELDSSTRUCT on SOAP Response not found.",NIL,"O",NIL,NIL) 
	If oNode2 != NIL
		::oWSLISTOFFIELDSGROUP := RHEMPLOYEEREGISTRATION_ARRAYOFFIELDSSTRUCT():New()
		::oWSLISTOFFIELDSGROUP:SoapRecv(oNode2)
	EndIf
Return

// WSDL Data Structure ARRAYOFFIELDSSTRUCT

WSSTRUCT RHEMPLOYEEREGISTRATION_ARRAYOFFIELDSSTRUCT
	WSDATA   oWSFIELDSSTRUCT           AS RHEMPLOYEEREGISTRATION_FIELDSSTRUCT OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT RHEMPLOYEEREGISTRATION_ARRAYOFFIELDSSTRUCT
	::Init()
Return Self

WSMETHOD INIT WSCLIENT RHEMPLOYEEREGISTRATION_ARRAYOFFIELDSSTRUCT
	::oWSFIELDSSTRUCT      := {} // Array Of  RHEMPLOYEEREGISTRATION_FIELDSSTRUCT():New()
Return

WSMETHOD CLONE WSCLIENT RHEMPLOYEEREGISTRATION_ARRAYOFFIELDSSTRUCT
	Local oClone := RHEMPLOYEEREGISTRATION_ARRAYOFFIELDSSTRUCT():NEW()
	oClone:oWSFIELDSSTRUCT := NIL
	If ::oWSFIELDSSTRUCT <> NIL 
		oClone:oWSFIELDSSTRUCT := {}
		aEval( ::oWSFIELDSSTRUCT , { |x| aadd( oClone:oWSFIELDSSTRUCT , x:Clone() ) } )
	Endif 
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT RHEMPLOYEEREGISTRATION_ARRAYOFFIELDSSTRUCT
	Local nRElem1, oNodes1, nTElem1
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNodes1 :=  WSAdvValue( oResponse,"_FIELDSSTRUCT","FIELDSSTRUCT",{},NIL,.T.,"O",NIL,NIL) 
	nTElem1 := len(oNodes1)
	For nRElem1 := 1 to nTElem1 
		If !WSIsNilNode( oNodes1[nRElem1] )
			aadd(::oWSFIELDSSTRUCT , RHEMPLOYEEREGISTRATION_FIELDSSTRUCT():New() )
			::oWSFIELDSSTRUCT[len(::oWSFIELDSSTRUCT)]:SoapRecv(oNodes1[nRElem1])
		Endif
	Next
Return

// WSDL Data Structure FIELDSSTRUCT

WSSTRUCT RHEMPLOYEEREGISTRATION_FIELDSSTRUCT
	WSDATA   cGROUP                    AS string
	WSDATA   oWSLISTOFFIELDSSTRUCT     AS RHEMPLOYEEREGISTRATION_ARRAYOFDATAFIELD OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT RHEMPLOYEEREGISTRATION_FIELDSSTRUCT
	::Init()
Return Self

WSMETHOD INIT WSCLIENT RHEMPLOYEEREGISTRATION_FIELDSSTRUCT
Return

WSMETHOD CLONE WSCLIENT RHEMPLOYEEREGISTRATION_FIELDSSTRUCT
	Local oClone := RHEMPLOYEEREGISTRATION_FIELDSSTRUCT():NEW()
	oClone:cGROUP               := ::cGROUP
	oClone:oWSLISTOFFIELDSSTRUCT := IIF(::oWSLISTOFFIELDSSTRUCT = NIL , NIL , ::oWSLISTOFFIELDSSTRUCT:Clone() )
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT RHEMPLOYEEREGISTRATION_FIELDSSTRUCT
	Local oNode2
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::cGROUP             :=  WSAdvValue( oResponse,"_GROUP","string",NIL,"Property cGROUP as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	oNode2 :=  WSAdvValue( oResponse,"_LISTOFFIELDSSTRUCT","ARRAYOFDATAFIELD",NIL,NIL,NIL,"O",NIL,NIL) 
	If oNode2 != NIL
		::oWSLISTOFFIELDSSTRUCT := RHEMPLOYEEREGISTRATION_ARRAYOFDATAFIELD():New()
		::oWSLISTOFFIELDSSTRUCT:SoapRecv(oNode2)
	EndIf
Return

// WSDL Data Structure ARRAYOFDATAFIELD

WSSTRUCT RHEMPLOYEEREGISTRATION_ARRAYOFDATAFIELD
	WSDATA   oWSDATAFIELD              AS RHEMPLOYEEREGISTRATION_DATAFIELD OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT RHEMPLOYEEREGISTRATION_ARRAYOFDATAFIELD
	::Init()
Return Self

WSMETHOD INIT WSCLIENT RHEMPLOYEEREGISTRATION_ARRAYOFDATAFIELD
	::oWSDATAFIELD         := {} // Array Of  RHEMPLOYEEREGISTRATION_DATAFIELD():New()
Return

WSMETHOD CLONE WSCLIENT RHEMPLOYEEREGISTRATION_ARRAYOFDATAFIELD
	Local oClone := RHEMPLOYEEREGISTRATION_ARRAYOFDATAFIELD():NEW()
	oClone:oWSDATAFIELD := NIL
	If ::oWSDATAFIELD <> NIL 
		oClone:oWSDATAFIELD := {}
		aEval( ::oWSDATAFIELD , { |x| aadd( oClone:oWSDATAFIELD , x:Clone() ) } )
	Endif 
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT RHEMPLOYEEREGISTRATION_ARRAYOFDATAFIELD
	Local nRElem1, oNodes1, nTElem1
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNodes1 :=  WSAdvValue( oResponse,"_DATAFIELD","DATAFIELD",{},NIL,.T.,"O",NIL,NIL) 
	nTElem1 := len(oNodes1)
	For nRElem1 := 1 to nTElem1 
		If !WSIsNilNode( oNodes1[nRElem1] )
			aadd(::oWSDATAFIELD , RHEMPLOYEEREGISTRATION_DATAFIELD():New() )
			::oWSDATAFIELD[len(::oWSDATAFIELD)]:SoapRecv(oNodes1[nRElem1])
		Endif
	Next
Return

// WSDL Data Structure DATAFIELD

WSSTRUCT RHEMPLOYEEREGISTRATION_DATAFIELD
	WSDATA   cFIELDACT                 AS string
	WSDATA   cFIELDCTX                 AS string
	WSDATA   nFIELDDEC                 AS integer
	WSDATA   cFIELDDESC                AS string
	WSDATA   nFIELDSEQ                 AS integer
	WSDATA   nFIELDSIZE                AS integer
	WSDATA   cFIELDTYPE                AS string
	WSDATA   cFIELDVAL                 AS string
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT RHEMPLOYEEREGISTRATION_DATAFIELD
	::Init()
Return Self

WSMETHOD INIT WSCLIENT RHEMPLOYEEREGISTRATION_DATAFIELD
Return

WSMETHOD CLONE WSCLIENT RHEMPLOYEEREGISTRATION_DATAFIELD
	Local oClone := RHEMPLOYEEREGISTRATION_DATAFIELD():NEW()
	oClone:cFIELDACT            := ::cFIELDACT
	oClone:cFIELDCTX            := ::cFIELDCTX
	oClone:nFIELDDEC            := ::nFIELDDEC
	oClone:cFIELDDESC           := ::cFIELDDESC
	oClone:nFIELDSEQ            := ::nFIELDSEQ
	oClone:nFIELDSIZE           := ::nFIELDSIZE
	oClone:cFIELDTYPE           := ::cFIELDTYPE
	oClone:cFIELDVAL            := ::cFIELDVAL
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT RHEMPLOYEEREGISTRATION_DATAFIELD
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::cFIELDACT          :=  WSAdvValue( oResponse,"_FIELDACT","string",NIL,"Property cFIELDACT as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cFIELDCTX          :=  WSAdvValue( oResponse,"_FIELDCTX","string",NIL,"Property cFIELDCTX as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::nFIELDDEC          :=  WSAdvValue( oResponse,"_FIELDDEC","integer",NIL,"Property nFIELDDEC as s:integer on SOAP Response not found.",NIL,"N",NIL,NIL) 
	::cFIELDDESC         :=  WSAdvValue( oResponse,"_FIELDDESC","string",NIL,"Property cFIELDDESC as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::nFIELDSEQ          :=  WSAdvValue( oResponse,"_FIELDSEQ","integer",NIL,"Property nFIELDSEQ as s:integer on SOAP Response not found.",NIL,"N",NIL,NIL) 
	::nFIELDSIZE         :=  WSAdvValue( oResponse,"_FIELDSIZE","integer",NIL,"Property nFIELDSIZE as s:integer on SOAP Response not found.",NIL,"N",NIL,NIL) 
	::cFIELDTYPE         :=  WSAdvValue( oResponse,"_FIELDTYPE","string",NIL,"Property cFIELDTYPE as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
	::cFIELDVAL          :=  WSAdvValue( oResponse,"_FIELDVAL","string",NIL,"Property cFIELDVAL as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
Return


