#INCLUDE "PROTHEUS.CH"
#INCLUDE "QUICKSEARCH.CH"
#INCLUDE "TECQ003.CH"

QSSTRUCT TECQ003 DESCRIPTION STR0001 MODULE 28 // "Previsão de Recursos Humanos" 

QSMETHOD INIT QSSTRUCT TECQ003
	
	QSTABLE "TFF" JOIN "TFL" ON "TFL.TFL_CODIGO = TFF.TFF_CODPAI" 
	QSTABLE "TFL" JOIN "CN9" ON "CN9.CN9_NUMERO = TFL.TFL_CONTRT AND CN9.CN9_REVISA = TFL.TFL_CONREV"
	QSTABLE "TFF" LEFT JOIN "SB1" ON "SB1.B1_COD = TFF.TFF_PRODUT"
	
	// campos do SX3 e indices do SIX
	QSPARENTFIELD "TFL_CONTRT" INDEX ORDER 4 
	QSPARENTFIELD "TFF_PRODUT" INDEX ORDER 4 
	
	// campos do SX3
	QSFIELD "TFL_CONTRT","TFF_PRODUT","B1_DESC","TFF_QTDVEN"
	
	QSFIELD "VLRTOT" EXPRESSION "((TFF_QTDVEN * TFF_PRCVEN) - TFF_VALDES)" LABEL STR0004 ; // "Valor Total"
	FIELDS "TFF_QTDVEN", "TFF_PRCVEN", "TFF_VALDES" TYPE "N" SIZE 14 DECIMAL 2 PICTURE "@E 99,999,999,999.99"
	
	QSFIELD "TFF_PERFIM"
	
	QSFILTER STR0003 WHERE "CN9.CN9_SITUAC = '05' AND '"+DTOS(Date())+"' BETWEEN TFF.TFF_PERINI AND TFF.TFF_PERFIM" // "Todos" 
Return
