#include "tlpp-core.th" 

namespace totvs.protheus.backoffice.pif.util

//------------------------------------------------------------------------------
/* {Protheus.doc} canAccess
    Verifica se o usuário possui permissão de acesso a uma determinada função no contexto informado.

    @type Function 
    @author Squad PIF
    @param cContext, Character, Contexto ou identificador da função a ser verificada
    @return Logical, Verdadeiro se o usuário possui acesso, Falso caso contrário
*/
//------------------------------------------------------------------------------
Function canAccess(cContext As Character) As Logical
    Local lActive := .F. As Logical
    Local lDev    := .F. As Logical

    lActive := findFunction(cContext) .And. (findClass("PIFUtilResponseTestSuite") .Or. lDev)

Return lActive
