c:\eADVPL\eADVPL TOTVSAPI.TTL MPAPET.TTL BEMATECH.TTL EPSON.TTL EPSON_A.TTL ITAUTEC.TTL ITAUTZPM.TTL darumanf.ttl CENTPAG.ttl IBM.ttl T88.ttl  CLISITEF.TTL bemanf.ttl SAT.ttl -name="DLL" -target=WIN32DLL -dontclean

Pause
